### ISSUE TITLE
循环中使用Insert，报错"不可添加，已存在于状态管理"

### ISSUE THREAD

**Issue by LiuYuLu** [dotnetcore/FreeSql#1007]
#### 问题描述及重现步骤：
![image](https://user-images.githubusercontent.com/16041268/149349455-982e76b9-9241-464b-85d4-a7de98691fc6.png)
![image](https://user-images.githubusercontent.com/16041268/149349608-15b95bde-2ba0-49f3-a421-219771ade1fc.png)

循环中调用，报错

#### 数据库的具体版本
```
mysql8
```

#### 安装的包
```
freesql 3.0.100
```

#### .net framework/. net core？ 及具体版本
```
net6.0
```

**Comment by LiuYuLu** [comment]
知道原因呢，主键ID设置错误导致

**Comment by 256051** [comment]
卧槽，我也是这个问题！！

**Comment by 2881099** [comment]
> 卧槽，我也是这个问题！！

看他回复，是 id 没有设置 IsPrimary IsIdentity
