### ISSUE TITLE
关于多表ToList的问题

### ISSUE THREAD

**Issue by fishjimi** [dotnetcore/FreeSql#101]
考虑以下语句
```
var members = _fsql.Select<TeamMember, Member>()
    .InnerJoin((teamMember, member) => teamMember.MemberId == member.Id)
    .ToList((teamMember, member) => new KeyValuePair<TeamMember, Member>(teamMember, member));
```
会爆异常
System.Exception:“映射异常：KeyValuePair`2 没有一个属性名相同”
似乎是因为我想返回一个KeyValuePair，而KeyValuePair里面并没有这些字段名
希望ToList能够支持传入Lambda表达式, 这样就可以任意生成返回的数据了

**Comment by 2881099** [comment]
可以 ToList((a,b)=> new {a,b})

**Comment by fishjimi** [comment]
@2881099 谢谢提醒，这个方式确实可以哦
不过如果想在ToList里面执行其他语句 甚至是函数 还是不允许的

**Comment by 2881099** [comment]
普通的可以，包含数据库的不行
