### ISSUE TITLE
sqlite 支持密码

### ISSUE THREAD

**Issue by xiaoxiong3533521** [dotnetcore/FreeSql#1011]
#### Feature 特性
支持创建和连接带密码的SQLITE数据库

#### 简要描述原因
在上位机中使用SQLITE数据库存储数据，但是用户可以直接用工具打开数据库文件修改表内容，所以希望能创建带密码的SQLITE数据库，保障数据安全。

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/discussions/999
