### ISSUE TITLE
Inserting using ExecuteAffrows() inserts not trimmed values

### ISSUE THREAD

**Issue by celli33** [dotnetcore/FreeSql#1012]
I´m inserting multiples values using:
```c#
fsql.Insert(items).ExecuteAffrows();
```
When I compare value inserted versus value expected I get: 
![image](https://user-images.githubusercontent.com/23373649/149871297-93a2be70-1d18-4e44-abea-bb8171e5a45b.png)

This error only happens when using `ExecuteAffrows()` when insertion is made one by one there are no spaces added to value.

I´m using:
net6.0
with firebird.

**Comment by 2881099** [comment]
var sql = fsql.Insert(items).ToSql();
Console.Write(sql);

Copy the printed content and run it directly. What is the feedback？

**Comment by celli33** [comment]
INSERT INTO "PERMISSIONS"("NAME", "CREATED_AT") SELECT FIRST 1 @Name_0, @CreatedAt_0 FROM rdb$database 
UNION ALL
 SELECT FIRST 1 @Name_1, @CreatedAt_1 FROM rdb$database 
UNION ALL
 SELECT FIRST 1 @Name_2, @CreatedAt_2 FROM rdb$database 
UNION ALL
 SELECT FIRST 1 @Name_3, @CreatedAt_3 FROM rdb$database 
UNION ALL
 SELECT FIRST 1 @Name_4, @CreatedAt_4 FROM rdb$database 
UNION ALL
 SELECT FIRST 1 @Name_5, @CreatedAt_5 FROM rdb$database

**Comment by 2881099** [comment]
Firebird database function returning. It does not support multi row data insertion. It can only insert single row data.
