### ISSUE TITLE
使用freesql-Tools出现关系 "pg_sequences" 不存在

### ISSUE THREAD

**Issue by kensmaster** [dotnetcore/FreeSql#1017]
![image](https://user-images.githubusercontent.com/15319050/150110120-d76382f4-0d5c-4f2e-943e-5f2897d4b864.png)

**Comment by kensmaster** [comment]
谁能做个在线版的呀，客户端不太方便

**Comment by densen2014** [comment]
这个工具不维护了

**Comment by luoyunchong** [comment]
在线版？ 要连接 你们自己本地的数据库怎么办。。。🤦‍♂️

**Comment by luoyunchong** [comment]
推荐使用 .NET Core CLI

 https://github.com/dotnetcore/FreeSql/wiki/DbFirst#net-core-cli%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8

**Comment by kensmaster** [comment]
> 推荐使用 .NET Core CLI
> 
> https://github.com/dotnetcore/FreeSql/wiki/DbFirst#net-core-cli%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8

这个也可以 只是想有个地方管理数据库
