### ISSUE TITLE
DbContext中InitPropSets方法报：TypeLoadException: GenericArguments[0], 'System.Guid', on 'FreeSql.DbSet`1[TEntity]' violates the constraint of type parameter 'TEntity'.

### ISSUE THREAD

**Issue by xye1989** [dotnetcore/FreeSql#1019]
#### 问题描述及重现步骤：
实体对象类似以下：public class ClassEntity : Entity。当执行到InitPropSets方法中的_dicGetDbSetProps.GetOrAdd时，就就会报：TypeLoadException: GenericArguments[0], 'System.Guid', on 'FreeSql.DbSet`1[TEntity]' violates the constraint of type parameter 'TEntity'.

#### 数据库的具体版本
mysql数据，目前异常根数据库版本不相关。

#### 安装的包
使用最新的版本v3.0.100

#### .net framework/. net core？ 及具体版本
.net 5

**Comment by luoyunchong** [comment]
给出具体代码。

**Comment by xye1989** [comment]
新年好！  如下是我的db上下文，我猜测可能是因为 我的上下文是继承了泛型基类导致的。
 public class AdminDbContext : RichDbContext<AdminDbContext>
    {
        public DbSet<ClassEntity> Classes { get; set; }

        public AdminDbContext(DbContextOptionsBuilder<AdminDbContext> options)
            : base(options)
        {

        }

        protected override void OnModelCreating(ICodeFirst codeFirst)
        {
            codeFirst.Entity<ClassEntity>(b =>
            {
                b.ToTable("rich_test_class");
                b.HasKey(p => p.Id);
                b.Property(c => c.Id).HasColumnName("id");
                b.Property(c => c.Name).HasColumnName("name");
                b.Property(c => c.Num).HasColumnName("num");
                b.Property(c => c.Desc).HasColumnName("desc");
            });
        }
    }

**Comment by xye1989** [comment]
后面发现是 再DbContext上放了一个属性protected virtual Guid? CurrentTenantId => CurrentTenant?.Id; 注释掉这就ok了。
