### ISSUE TITLE
[Bug] SQLite 数据库中 PadLeft 方法的实现

### ISSUE THREAD

**Issue by hd2y** [dotnetcore/FreeSql#1021]
#### 问题描述及重现步骤：

参考讨论：https://github.com/dotnetcore/FreeSql/discussions/945

SQLite 对应方法应该为 `padl`、`padr` 而非 `rpad` 以及 `lpad`。

但是 SQLite 不支持指定填充的字符，所以需要适当调整。

```sql
-- "text".PadLeft(10)
-- '      text'
select padl('text', 10);

-- "text".PadLeft(10, '0')
-- '000000text'
select leftstr(replace(padl('text', 10), ' ', '0'), 10 - length('text')) || 'text';
```

以上为 `padl` 的示例，`padr` 可以参考着调整。

#### 数据库的具体版本

SQLite 数据库

#### 安装的包

最新版本

**Comment by hd2y** [comment]
原本想着有没有 `repeat` 方法的，但是 SQLite 也不支持，所以考虑是截取出来填充字符再做一次替换，不知道有没有更好的方案。

**Comment by 2881099** [comment]
padl 可以先 pr 进来
