### ISSUE TITLE
仓储模式 有参构造函数 无法添加

### ISSUE THREAD

**Issue by wuzxc1230123** [dotnetcore/FreeSql#1022]
C# 8中可用引用类型 导致可空类型
非空类型 必须在构造函数赋值

但如果 实体里面有构造函数，仓储模式 无法添加

**Comment by hd2y** [comment]
添加一个无参数构造函数，base 到你需要的构造函数然后赋默认值。

**Comment by carbonhe** [comment]
@hd2y  全都赋默认值的话可空类型的意义就不大了
