### ISSUE TITLE
能否尽快添加freesql.provider 对TDengine 数据库支持？

### ISSUE THREAD

**Issue by liushoubing** [dotnetcore/FreeSql#1025]
#### Feature 特性
TDengine 数据库是国内时序数据库。

#### 简要描述原因
TDengine 数据库是国内时序数据库，目前在工业环境当中使用比较多。

#### 使用场景
TDengine 主要应用在数据采集方向和工业数据分析场景。

**Comment by 2881099** [comment]
v3.5.100 即将发布，支持 DuckDB 和 TDengine
