### ISSUE TITLE
Can i use Entity Framework Core side by side with FreeSql

### ISSUE THREAD

**Issue by chrisgate** [dotnetcore/FreeSql#1035]
I mean if i have Entity Framework Core app and i do migration and all that with EF Core but i just want to use FreeSQL for crazy and complex queries?

Thanks for this great library.

**Comment by hd2y** [comment]
https://github.com/dotnetcore/FreeSql/wiki/Getting-Started#declaring

you can disable migration by use `.UseAutoSyncStructure(false)`.

**Comment by chrisgate** [comment]
@hd2y That works but i am curious of better ways of injecting it in my aspnet core 6 app....

I register my DbContext like this:
` services.AddDbContext<ApplicationDbContext>((serviceProvider, options) =>
            {
                var connectionStringHelper = serviceProvider.GetRequiredService<ITenantResolver>();
                var currentUserService = serviceProvider.GetRequiredService<ICurrentUserService>();
                var currentTenant = connectionStringHelper.GetCurrentTenant(currentUserService.Host);

                options.UseNpgsql(currentTenant?.ConnectionString, builder =>
                {
                    builder.EnableRetryOnFailure();
                });
            });`

I thinking of better ways of registering it because my application is multitenant app.

Cheers

**Comment by hd2y** [comment]
I have an idea like this:
```cs
void Main()
{
	var connectionString = "Server=127.0.0.1;Port=5432;Database=postgres;User Id=postgres;Password=postgres;";

	// dependency injection
	IServiceCollection services = new ServiceCollection();
	services.AddDbContext<ApplicationDbContext>((provider, builder) =>
	{
		builder.UseNpgsql(connectionString);
	}).AddScoped<IDbConnection>(provider => provider.GetRequiredService<ApplicationDbContext>().Database.GetDbConnection());

	// use freesql like dapper
	var provider = services.BuildServiceProvider();
	using var scope = provider.CreateScope();
	var conn = scope.ServiceProvider.GetRequiredService<IDbConnection>();

	var result = conn.Select<object>().WithSql("select 1 as num").ToList(a => new { num = "num" });
	result.Dump();
}

public class ApplicationDbContext : Microsoft.EntityFrameworkCore.DbContext
{
	public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
		: base(options)
	{
	}
}
```

**Comment by chrisgate** [comment]
@hd2y Thanks

But i dont want to use it like dapper but like FreeSQL in all it glory.

Thanks

**Comment by hd2y** [comment]
(lll￢ω￢), In fact, you can use the CRUD method with the conn extension method, and if you want get the instance of ifreesql, you must create a resolver (freesql is singleton pattern):

```cs
void Main()
{
    var connectionString = "Server=127.0.0.1;Port=5432;Database=postgres;User Id=postgres;Password=postgres;";

    // dependency injection
    IServiceCollection services = new ServiceCollection();
    services.AddDbContext<ApplicationDbContext>((provider, builder) => { builder.UseNpgsql(connectionString); })
        .AddScoped<IDbConnection>(provider =>
            provider.GetRequiredService<ApplicationDbContext>().Database.GetDbConnection())
        .AddSingleton<IFreeSqlResolver, FreeSqlResolver>();

    // use freesql like dapper
    var provider = services.BuildServiceProvider();
    using (var scope = provider.CreateScope())
    {
        var conn = scope.ServiceProvider.GetRequiredService<IDbConnection>();

        var result = conn.Select<object>().WithSql("select 1 as num").ToList(a => new { num = "num" });
        result.Dump();
    }

    using (var scope1 = provider.CreateScope())
    {
        var conn = scope1.ServiceProvider.GetRequiredService<IDbConnection>();

        var result = conn.Select<object>().WithSql("select 2 as num").ToList(a => new { num = "num" });
        result.Dump();
    }

    using (var scope2 = provider.CreateScope())
    {
        var resolver = scope2.ServiceProvider.GetRequiredService<IFreeSqlResolver>();
        var context = scope2.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var result = resolver.GetFreeSql(context).Select<object>().WithSql("select 2 as num")
            .ToList(a => new { num = "num" });
        result.Dump();
    }

    using (var scope3 = provider.CreateScope())
    {
        var resolver = scope3.ServiceProvider.GetRequiredService<IFreeSqlResolver>();
        var context = scope3.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var result = resolver.GetFreeSql(context).Select<object>().WithSql("select 3 as num")
            .ToList(a => new { num = "num" });
        result.Dump();
    }
}

public class ApplicationDbContext : Microsoft.EntityFrameworkCore.DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }
}

public interface IFreeSqlResolver
{
    IFreeSql GetFreeSql(Microsoft.EntityFrameworkCore.DbContext context);
}

public class FreeSqlResolver : IFreeSqlResolver
{
    private readonly object _locker = new object();
    private static readonly Dictionary<string, IFreeSql> FreeSqlDictionary = new Dictionary<string, IFreeSql>();

    public IFreeSql GetFreeSql(Microsoft.EntityFrameworkCore.DbContext context)
    {
        lock (_locker)
        {
            var connectionString = context.Database.GetConnectionString();
            if (FreeSqlDictionary.TryGetValue(connectionString, out var freeSql)) return freeSql;

            var db = new FreeSqlBuilder()
                .UseConnectionString(DataType.PostgreSQL, connectionString)
                .Build();

            FreeSqlDictionary.Add(connectionString, db);

            return db;
        }
    }
}
```

https://github.com/dotnetcore/FreeSql/discussions/1033

**Comment by chrisgate** [comment]
Wow !

You are my genius !

it works and its clean...........thanks

Let me ask you here in the same vein.

I want to save many to many where i can a Company and User as many to many with join table CompanyUsers:

I try it like below:

` var users = new List<AppUser>();
            var ctx = unitOfWork.Fsql.CreateDbContext();
            var myComp = ctx.Set<Company>();
            var myUser = ctx.Set<AppUser>();
            var repo = unitOfWork.Fsql.GetRepository<Company>();
            repo.DbContextOptions.EnableAddOrUpdateNavigateList = true;
            //var company = await dbContext.Companies.FindAsync(request.CompanyId);
            var company = await myComp.Select.Where(x=>x.Id == request.CompanyId).ToOneAsync();
            if (company != null)
            {
               
                foreach (var id in request.UserIds)
                {
                    //var user = await dbContext.Users.FindAsync(id);
                    var user = await myUser.Select.Where(x => x.Id == id).ToOneAsync();
                   
                    users.Add(user);
                }
                company.Users.AddRange(users);

                try
                {
                    //await unitOfWork.FreeSqlDbContext.SaveChangesAsync(cancellationToken);
                 
                    await myComp.UpdateAsync(company);
                   await ctx.SaveChangesAsync(cancellationToken);
                }
               // catch (DbUpdateConcurrencyException)
                catch (Exception ex)
                {
                    return await Result<int>.FailAsync($"This current resource has been modified by another User since last loaded,Please refresh to get the upated version!");

                }`
                
                I wanted to add Users to a company in a many to many pattern ...........keep in my i have configure the many to many  right ...i can get all the data in many to many ways but its just the saving.
                
                
                
                cheers
