### ISSUE TITLE
表达式解析错误

### ISSUE THREAD

**Issue by wangronghua** [dotnetcore/FreeSql#1047]
sqlserver数据库

表达式值为   

x => (False OrElse ((True AndAlso (x.AppType == Android)) AndAlso (x.VersionName == "3.1.7")))

解析出来的sql

SELECT a.[Id], a.[AppType], a.[VersionName], a.[VersionCode], a.[Message], a.[URL], a.[Force], a.[IsOnline] 
FROM [VersionControlLog] a 
WHERE ((0 OR 1=1 AND a.[AppType] = 1 AND a.[VersionName] = N'3.1.7'))

第一个0应该为 1=0吧，不然sql报错

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/158838803-99e0bd4c-dd4d-460d-905e-7166f22069df.png)

试下这样写
https://github.com/dotnetcore/FreeSql/wiki/%e8%a1%a8%e8%be%be%e5%bc%8f%e5%87%bd%e6%95%b0

**Comment by hd2y** [comment]
是的，应该时有个BUG：https://github.com/dotnetcore/FreeSql/blob/5dc014bc7ccfe6b21e8e3eb768c9080aecaff149/FreeSql/Internal/CommonExpression.cs#L594

@2881099 叶老板看看，这里是不是当 `leftExp` 类型时 `bool`，需要加一个 `GetBoolString()` 方法的调用。

**Comment by 2881099** [comment]
> 是的，应该时有个BUG：
> 
> https://github.com/dotnetcore/FreeSql/blob/5dc014bc7ccfe6b21e8e3eb768c9080aecaff149/FreeSql/Internal/CommonExpression.cs#L594
> 
> @2881099 叶老板看看，这里是不是当 `leftExp` 类型是 `bool`，需要加一个 `GetBoolString()` 方法的调用。

是的，要加
