### ISSUE TITLE
请问Code First 可以支持 Firebird 4 迁移结构至数据库吗？

### ISSUE THREAD

**Issue by Iveny8** [dotnetcore/FreeSql#1048]
UseAutoSyncStructure(true) 
fsql.CodeFirst.SyncStructure<表名>()
两种方式都会报错
请问Code First 是不支持Firebird 数据库迁移吗？

**Comment by densen2014** [comment]
来个demo试试

**Comment by 2881099** [comment]
database=localhost:D:\fbdata\EXAMPLES.fdb;user=sysdba;password=123456;

只支持本地数据库

**Comment by Iveny8** [comment]
> database=localhost:D:\fbdata\EXAMPLES.fdb;user=sysdba;password=123456;
> 
> 只支持本地数据库

不是链接的问题啦，只有没有迁移的语句：
UseAutoSyncStructure(true)
fsql.CodeFirst.SyncStructure<表名>()

CRUD都是正常的，在官方文档没能找到Firebird 数据库CodeFirst迁移的说明，但实际有迁移语句是会报错

**Comment by 2881099** [comment]
Firebird 分两种模式，嵌入式本地数据库和服务端数据库。

FreeSql.Provider.Firebird 是根据 Firebird 3.0 嵌入式版本进行开发的。

- 据当时（去年）适配 Firebird 的时候，4.0 是不支持嵌入式本地数据库的。
- Firebird 嵌入式本地数据库和服务端数据库的数据结构，迁移脚本差异化挺大，无法一起使用。

**Comment by Iveny8** [comment]
謝謝叶老板亲自答复，翻阅了几天issue找到问题了，原因在于有timestamp字段，
Firebird 4 DB删除timestamp列后，迁移操作全部正常。
（P.S 我们实测Firebird 4.0.1支持嵌入式本地数据库，而且性能强悍，我们工作室已开始将项目从2.5升级到4.0.1）

**Comment by Iveny8** [comment]
謝謝叶老板亲自答复，翻阅了几天issue找到问题了，原因在于有timestamp字段，
Firebird 4 DB删除timestamp列后，迁移操作全部正常。
FreeSQL实在太棒了，是我用过最优秀的ORM
（P.S 我们实测Firebird 4.0.1支持嵌入式本地数据库，而且性能强悍，我们工作室已开始将项目从2.5升级到4.0.1）

**Comment by Iveny8** [comment]
謝謝叶老板亲自答复，原以為是timestamp字段的問題，
但用FreeSQL 直接建Firebird 4 DB Table，迁移操作全部正常，
問題出在修改修改原來由firebird_maestro软件建立的Table才报错，证实FreeSQL很好支持Firebird 4 的实体迁移。
FreeSQL实在太棒了，是我用过最优秀的ORM
（P.S 我们实测Firebird 4.0.1支持嵌入式本地数据库，而且性能强悍，我们工作室已开始将项目从2.5升级到4.0.1）

**Comment by Iveny8** [comment]
謝謝叶老板亲自答复，原以為是timestamp字段的問題，
但用FreeSQL 直接建Firebird 4 DB Table，迁移操作全部正常，
問題出在修改原來由firebird_maestro软件建立的Table才报错，证实FreeSQL很好支持Firebird 4 的实体迁移。
報錯的SQL如下：
```
case when d.rdb$unique_flag = 1 then 1 else 0 end
from rdb$indices d
inner join rdb$index_segments c on c.rdb$index_name = d.rdb$index_name
where d.rdb$index_type = 0 and trim(d.rdb$relation_name) = 'TODOLIST'
   CommitTimeoutTransaction: 0ms
PrepareCommand: 1.4738ms Total: 1.4738ms
Pool.Get: 0ms Total: 1.4738ms
ExecuteReader: 0.7059ms Total: 2.1797ms
Pool.Return: 0ms Total: 2.1797ms
 select trim(rdb$external_description) from rdb$relations where rdb$system_flag=0 and trim(rdb$relation_name) = 'TODOLIST'
主库（执行SQL）耗时1.0061ms
 select trim(rdb$external_description) from rdb$relations where rdb$system_flag=0 and trim(rdb$relation_name) = 'TODOLIST'
   CommitTimeoutTransaction: 0ms
Pool.Return: 0ms Total: 1.0061ms
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);

主库数据库出错（执行SQL）〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);

Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 1
ALTER
主库（执行SQL）耗时27.5982ms
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);

   CommitTimeoutTransaction: 0ms
Pool.Return: 0ms Total: 27.5982ms
引发的异常:“System.Exception”(位于 FreeSql.dll 中)
```


（P.S 我们实测Firebird 4.0.1支持嵌入式本地数据库，而且性能强悍，我们工作室已开始将项目从2.5升级到4.0.1）

**Comment by Iveny8** [comment]
謝謝叶老板亲自答复，原以為是timestamp字段的問題，
但用FreeSQL 直接建Firebird 4 DB Table，迁移操作全部正常，
問題出在修改原來由firebird_maestro软件建立的Table才报错，证实FreeSQL很好支持Firebird 4 的实体迁移。
報錯的SQL如下：
```
case when d.rdb$unique_flag = 1 then 1 else 0 end
from rdb$indices d
inner join rdb$index_segments c on c.rdb$index_name = d.rdb$index_name
where d.rdb$index_type = 0 and trim(d.rdb$relation_name) = 'TODOLIST'
   CommitTimeoutTransaction: 0ms
PrepareCommand: 1.4738ms Total: 1.4738ms
Pool.Get: 0ms Total: 1.4738ms
ExecuteReader: 0.7059ms Total: 2.1797ms
Pool.Return: 0ms Total: 2.1797ms
 select trim(rdb$external_description) from rdb$relations where rdb$system_flag=0 and trim(rdb$relation_name) = 'TODOLIST'
主库（执行SQL）耗时1.0061ms
 select trim(rdb$external_description) from rdb$relations where rdb$system_flag=0 and trim(rdb$relation_name) = 'TODOLIST'
   CommitTimeoutTransaction: 0ms
Pool.Return: 0ms Total: 1.0061ms
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);

主库数据库出错（执行SQL）〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);

Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 1
ALTER
主库（执行SQL）耗时27.5982ms
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);

   CommitTimeoutTransaction: 0ms
Pool.Return: 0ms Total: 27.5982ms
引发的异常:“System.Exception”(位于 FreeSql.dll 中)
```


（P.S 我们实测Firebird 4.0.1支持嵌入式本地数据库，而且性能强悍，已开始将项目从2.5升级到4.0.1）

**Comment by 2881099** [comment]
信息太少，可以获取的信息：

1、Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 1

2、SQL 执行失败：

```sql
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);
```

SQL 直接拿到控制台能执行吗？

**Comment by 2881099** [comment]
还是说不能同时执行多条 SQL 组合的内容，即使用分号分割，试试直接用 ado.net 直接执行：

```sql
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);
```

并且分开三次 ado.net 执行：

```sql
ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
```

```sql
ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
```

```sql
ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);
```

**Comment by Iveny8** [comment]
> 信息太少，可以获取的信息：
> 
> 1、Dynamic SQL Error SQL error code = -104 Token unknown - line 2, column 1
> 
> 2、SQL 执行失败：
> 
> ```sql
> ALTER TABLE "TODOLIST" ALTER COLUMN "TITLE" TYPE VARCHAR(255) ;
> ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
> ALTER TABLE "TODOLIST" ADD "tt" VARCHAR(255);
> ```
> 
> SQL 直接拿到控制台能执行吗？

第一句和第三句正常，第2句报错：

```
SQL> ALTER TABLE "TODOLIST" ALTER COLUMN "DETAILS" TYPE VARCHAR(255);
Statement failed, SQLSTATE = 42000
unsuccessful metadata update
-ALTER TABLE TODOLIST failed
-New size specified for column DETAILS must be at least 600 characters.
```
查看了firebird maestro软件建立的Table中DETAILS字段长度是600，
Code First的代码中没有指定字段长度

**Comment by 2881099** [comment]
这样更简单了，FreeSql 未指定长度默认是 255，迁移失败说明数据库不允许从 600 长度修改为 255，怕数据截断风险。

```c#
[Column(StringLength = 600)]
```

把实体类属性标记成这种长度就行了。

或者统一设置默认为 600 长度

```c#
fsql.Aop.ConfigEntityProperty += (_, e) => {
    if (e.Property.PropertyType == typeof(string))
        e.ModifyResult.StringLength = 600;
};
```

**Comment by Iveny8** [comment]
> 这样更简单了，FreeSql 未指定长度默认是 255，迁移失败说明数据库不允许从 600 长度修改为 255，怕数据截断风险。
> 
> ```cs
> [Column(StringLength = 600)]
> ```
> 
> 把实体类属性标记成这种长度就行了。
> 
> 或者统一设置默认为 600 长度
> 
> ```cs
> fsql.Aop.ConfigEntityProperty += (_, e) => {
>     if (e.Property.PropertyType == typeof(string))
>         e.ModifyResult.StringLength = 600;
> };
> ```

是的，没想到问题出在这么简单的地方
增加[Column(DbType = "varchar(600)")]解决
谢谢叶老板帮忙解答
FreeSQL确实好棒，希望这么优秀的ORM继续发展O(∩_∩)O
