### ISSUE TITLE
可空字段类型在Where条件查询时，发生异常 System.InvalidOperationException 可为空的对象必须具有一个值。

### ISSUE THREAD

**Issue by TinManGo** [dotnetcore/FreeSql#1051]
#### 问题描述及重现步骤：

可空字段类型在Where条件查询时，发生异常 System.InvalidOperationException 可为空的对象必须具有一个值。
Select<类型>().where(带条件时)。

上一个版本没有这个问题。

#### 数据库的具体版本
```
Mysql 5.7
```

#### 安装的包
```
3.2.100
```

#### .net framework/. net core？ 及具体版本
```
4.5.2
```

**Comment by 2881099** [comment]
方便给出具体重现代码吗

**Comment by TinManGo** [comment]
> 方便给出具体重现代码吗
定位到问题了。 使用string list.Contains 方法 作为 where 条件 就会出错。无论是否设置 isnullable 或者数据库表是否为空 是否有空值。

 List<string> loginName_List = new List<string>();
loginName_List.Add("TEST");
List<SysUser>  list = FreeSqlHelper.Fsql.Select<SysUser>().Where(w => loginName_List.Contains(w.LoginName)).ToList();

**Comment by TinManGo** [comment]
新版本 问题已解决。
