### ISSUE TITLE
arm,树莓派使用freesql, 需用Provider : Microsoft.Data.Sqlite但是不支持内插, 目前需开启 .UseNoneCommandParameter(true)避坑

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/FreeSql#1052]
#### 问题描述及重现步骤：

需用Provider : Microsoft.Data.Sqlite但是不支持内插, 目前需开启 .UseNoneCommandParameter(true)避坑

        arm,树莓派使用freesql
         1.添加包
        <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.0.100" />
        <PackageReference Include = "Microsoft.Data.Sqlite" Version="6.0.3" />

         2.代码
        Microsoft.Data.Sqlite.SqliteConnection _database = new Microsoft.Data.Sqlite.SqliteConnection($"Data Source=document.db");

        var fsql = new FreeSql.FreeSqlBuilder()
        .UseConnectionFactory(FreeSql.DataType.Sqlite, () => _database, typeof(FreeSql.Sqlite.SqliteProvider<>))
        .UseAutoSyncStructure(true)
        .UseNoneCommandParameter(true) //必须开启,因为Microsoft.Data.Sqlite内插处理有bug
        .UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
        .Build();

#### 数据库的具体版本
```
Sqlite
```

#### 安装的包
```
		<PackageReference Include="FreeSql.Provider.Sqlite" Version="3.2.100" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.3" />

```

#### .net framework/. net core？ 及具体版本
```
net6.0
```

#### 错误信息
```
插入语句执行不对,或者其他信息,原因是 Microsoft.Data.Sqlite不支持内插 $"xxx {par1}"形式

System.Exception
  HResult=0x80131500
  Message=SQLite Error 19: 'UNIQUE constraint failed: Item.Idu'.
  Source=FreeSql
  StackTrace:
   在 FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.InsertProvider`1.RawExecuteAffrows()
   在 FreeSql.Internal.CommonProvider.InsertProvider`1.SplitExecuteAffrows(Int32 valuesLimit, Int32 parameterLimit)
   在 FreeSql.Sqlite.Curd.SqliteInsert`1.ExecuteAffrows()
   在 FreeSqlDemos.Program.Main(String[] args) 在 F:\Repos\FreeSqlDemos\ARM_ConsoleApp\Program.cs 中: 第 66 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]

内部异常 1:
SqliteException: SQLite Error 19: 'UNIQUE constraint failed: Item.Idu'.
```

**Comment by densen2014** [comment]
**有条件的同学直接试试 FreeSql.Provider.SqliteCore 包,使用的就是Microsoft.Data.Sqlite驱动.**

**Comment by luoyunchong** [comment]
docs:[http://freesql.net/guide/freesql-provider-sqlitecore.html](http://freesql.net/guide/freesql-provider-sqlitecore.html)
