### ISSUE TITLE
MySql自动同步时DateTime支持不完善

### ISSUE THREAD

**Issue by liazheyua** [dotnetcore/FreeSql#1053]
#### 问题描述及重现步骤：
Code2DB
DateTime字段同步时报错，错误及sql如下：
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3) NOT NULL, 
  PRIMARY KEY (`id`)
) Engine=InnoDB' at line 5

CREATE TABLE IF NOT EXISTS `test`.`test_topic2` (  
  `id` INT(11) AUTO_INCREMENT, 
		`Title` VARCHAR(32), 
			`Content` VARCHAR(256), 
				`CreateTime` DATETIME(3) NOT NULL, 
					PRIMARY KEY (`id`)
					) Engine=InnoDB;

DateTime字段添加属性之后正常
[Column(DbType = "datetime")]

#### 数据库的具体版本
```
MySql 5.5
```

#### 安装的包
```
3.2.100
```

#### .net framework/. net core？ 及具体版本
```
4.8
```

**Comment by 2881099** [comment]
see #75
