### ISSUE TITLE
数组类型返回失败

### ISSUE THREAD

**Issue by jesse996** [dotnetcore/FreeSql#1054]
#### 问题描述及重现步骤：
数据库一个字段是json类型，我存的是形如： `["asd", "afg"]` ，字段添加并开启了JsonMap。增加操作可以正常添加，但是查询的时候这个字段一直返回 [] 
##### 添加：
![image](https://user-images.githubusercontent.com/20895372/160111388-08cfa795-5098-4a89-b589-76619ddc7fab.png)
##### 添加成功，数据库显示：
<img width="124" alt="image" src="https://user-images.githubusercontent.com/20895372/160111489-a13ad404-2ab7-4664-99a8-bf32575aeea4.png">

##### 查询返回 []：
![image](https://user-images.githubusercontent.com/20895372/160111583-5f933fb7-bcc8-4189-9923-d4997392ffed.png)

#### 数据库的具体版本
```
mysql 8
```

#### 安装的包
![image](https://user-images.githubusercontent.com/20895372/160110800-90bb704f-3e58-4575-a6a9-16b4f5741227.png)

#### .net framework/. net core？ 及具体版本
```
.net 6
```

**Comment by 2881099** [comment]
实体类发一下

**Comment by jesse996** [comment]
> 实体类发一下

![image](https://user-images.githubusercontent.com/20895372/160112073-08499507-d16a-498f-828a-bca9764500fb.png)

**Comment by 2881099** [comment]
JsonMap 不建议直接用在 string[] 等基础类型上。应该用在自定义类型上，如下：

```c#

[JsonMap]
public FuNengImgInfo FuNengImg { get; set; }

public class FuNengImgInfo
{
    public string[]? FuNengImg { get; set; }
}
```

**Comment by jesse996** [comment]
我解决了，用List就好了
```
        [JsonProperty, Column(Name = "fu_neng_img", DbType = "json")]
        [JsonMap]
        public List<string>? FuNengImg { get; set; }
```
