### ISSUE TITLE
Select.WithSql(sql, null).ToList<string>(sql ,null)  报错

### ISSUE THREAD

**Issue by Roadbeg** [dotnetcore/FreeSql#1056]
.Net standard 2.0
数据库: Sql Server 2019 
FreeSql 版本 2.5.2

代码:
string sql="Select Top 10 name From tbl";
//以下代码可以正常返回数据:
return _fsql.Ado.Query<string>(sql, null);
//以下代码报错: 没有为该对象定义无参数的构造函数
return Select.WithSql(sql, null).ToList<string>();

**Comment by 2881099** [comment]
```c#
fsql.Select<object>().WithSql("select title from tttorder").Limit(10).ToList<string>("*")
```

这样测试没问题，需要在 ToList 参数内设置查询的内容

**Comment by 2881099** [comment]
ToList\<TDto\>

这个方法是给映射查询用的，有一点误导

**Comment by Roadbeg** [comment]
谢谢，我现在改成这样用

          var typeString = typeof(TDto).ToString().ToLower();
          switch (typeString)
	  {
                case "system.string":
                case "system.int16"://short
                case "system.int32"://int
                case "system.int64"://long
                case "system.uint16"://ushort
                case "system.uint32"://uint
                case "system.uint64"://ulong
                case "system.single"://float
                case "system.double"://double
                case "system.datetime"://datetime
                case "system.boolean"://bool                
                case "system.decimal":                    
                case "system.char":
                case "system.byte":
                case "system.sbyte":
                    return Select.WithSql(sql, p).ToList<TDto>("*");
                default:
                    return Select.WithSql(sql, p).ToList<TDto>();
            }
