### ISSUE TITLE
Firebird 无法解析List.Contains 提示Unknown type: System.Collections.Generic.List`1[System.String].”

### ISSUE THREAD

**Issue by lvwei244954744** [dotnetcore/FreeSql#1061]
#### 问题描述及重现步骤：
[FirebirdDemo.zip](https://github.com/dotnetcore/FreeSql/files/8379385/FirebirdDemo.zip)
示例：
var names = new List<string> { "A1", "A2" };
var firebirdDemoEntities = freeSql.Select<FirebirdDemoEntity>().Where(x => names.Contains(x.Name)).ToList();

#### 数据库的具体版本
```
Firebird 2.5.9
```

#### 安装的包
```
FreeSql.Provider.Firebird 3.2.200
```

#### .net framework/. net core？ 及具体版本
```
.net 6.0
```

**Comment by 2881099** [comment]
原因：UseGenerateCommandParameterWithLambda(true) 功能与 List\<string\> 冲突

解决方法：暂时关闭该功能，或者等下个版本发布

**Comment by 2881099** [comment]
此问题 v3.0.xx 以下没有问题，由于 v3.2.x 解决 #800 问题导致出的新问题
