### ISSUE TITLE
Sqlite 数据库，主键设置不可为空无效

### ISSUE THREAD

**Issue by hyzx86** [dotnetcore/FreeSql#1065]
设置 Nullable 与不设置都一样

freesql 版本：3.2.301
.net 6

![image](https://user-images.githubusercontent.com/15613121/162134170-b79c6da2-a70b-4b7d-a6f3-86e3ac703bb1.png)

**Comment by 2881099** [comment]
只有 int? 才有必要设置 IsNullable

因为：int 无法接收 null

**Comment by hyzx86** [comment]
收到，问题不大，只是我看 Yessql 创建出来的表是 勾选了的
