### ISSUE TITLE
postgresql 数据库下 tsvector 类型 插入双英文单引号时发生异常

### ISSUE THREAD

**Issue by MrZol** [dotnetcore/FreeSql#1069]
#### 问题描述及重现步骤：
1、.NET Core CLI 无法生成“tsvector”类型对应的基础类型，如string
2、当提交的字段数据为‘’（双英文单引号时），发生sql异常

sql：
INSERT INTO "empi_ktdoc_work_log_copy1"("clinic_id", "clinic_time", "org_code", "dept_id", "diagnose", "emp_id", "empi_id", "is_our_org", "org_name", "register_id") VALUES('1111111', '0001-01-01 00:00:00.000000', '', NULL, '''''', NULL, 0, NULL, NULL, NULL) 

异常：
42601: syntax error in tsvector: \"''\"

#### 数据库的具体版本
```
postgresql 14.2
```

#### 安装的包
```
FreeSql.Provider.PostgreSQL 3.2.303
```

#### .net framework/. net core？ 及具体版本
```
net core 3.1
```

**Comment by 2881099** [comment]
不支持 tsvector 类型呢
