### ISSUE TITLE
这种sql语句怎么执行

### ISSUE THREAD

**Issue by jiangpnj** [dotnetcore/FreeSql#1083]
SET @uids := null;
    UPDATE test_table
       SET status = 2 
     WHERE status = 1 
     AND id =1  
   AND(SELECT @uids:= concat_ws(',', id, @uids)) LIMIT 10; 
            SELECT CONVERT(@uids USING utf8) as ids; 

执行上面sql，返回修改后的id，目前使用freesql尝试了好几种办法都没成功，求指教

**Comment by 2881099** [comment]
数据库是什么，最好提供下简易 demo

**Comment by jiangpnj** [comment]
> 数据库是什么，最好提供下简易 demo
多谢回复，现在解决了，连接字符串加上 Allow User Variables=True 就可以了

**Comment by jiangpnj** [comment]
谢谢回复，已经解决了，连接字符串加上 Allow User Variables=True 就可以了
