### ISSUE TITLE
日期映射成字符串在 linux 格式不正确

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1085]
版本 3.2.100
model 源码如下
![image](https://user-images.githubusercontent.com/36889438/165018476-0204d1aa-155e-4f87-b0b8-9a655da2bb8b.png)

在windows 下 语句 
![image](https://user-images.githubusercontent.com/36889438/165018464-7221fd71-fbd8-4909-9d2e-5ea87bc96a4c.png)

在contos7下语句
![image](https://user-images.githubusercontent.com/36889438/165018448-c9c1f155-0b1b-4958-8761-22ecb09f2985.png)

**Comment by sukney** [comment]
![image](https://user-images.githubusercontent.com/36889438/165018584-bfd3ede7-31b4-424f-bf34-355942554a00.png)
设置了 jsonmap 日期格式，不生效。

**Comment by 2881099** [comment]
因为你使用的 MapType string

**Comment by sukney** [comment]
这种情况要怎么解决，我数据库里字段类型是 varchar(19)， model 里有string 的串，程序里 日期查询 全要转一次，那太麻烦了。

**Comment by 2881099** [comment]
全局初始化的时候执行一次代码

```c#
FreeSql.Internal.Utils.GetDataReaderValueBlockExpressionObjectToStringIfThenElse.Add((LabelTarget returnTarget, Expression valueExp, Expression elseExp, Type type) =>
{
    return Expression.IfThenElse(
        Expression.AndAlso(Expression.Equal(Expression.Constant(type), Expression.Constant(typeof(string))), Expression.TypeEqual(valueExp, typeof(DateTime))),
        Expression.Return(returnTarget, Expression.Convert(Expression.Call(
            Expression.Convert(valueExp, typeof(DateTime)), 
            typeof(DateTime).GetMethod("ToString", new[] { typeof(string) }), 
            Expression.Constant("yyyy-MM-dd HH:mm:ss")), typeof(object))),
        elseExp);
});
```

**Comment by sukney** [comment]
谢谢 大神。

>
