### ISSUE TITLE
 FreeSql.Generator 在mac系统提示信息乱码

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/FreeSql#1087]
#### 问题描述及重现步骤：

 FreeSql.Generator 在mac系统下生成文件打开乱码

#### 安装的包
```
FreeSql.Generator
```

#### . net core？ 及具体版本
```
net 6
```

**Comment by densen2014** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/8428709/165197114-8a56abbd-3de8-47f1-bd8b-4b3676c1ed53.png">

**Comment by 2881099** [comment]
newb kalass
