### ISSUE TITLE
在xamarin.form.ios下使用Microsoft.Data.Sqlite的问题

### ISSUE THREAD

**Issue by peng0829** [dotnetcore/FreeSql#1089]
在xamarin.form.ios下使用Microsoft.Data.Sqlite的问题
创建SqliteConnection后需要添加SQLitePCL.Batteries.Init();
否则会出现错误
在Class SqliteConnectionPool
        public DbConnection OnCreate()
        {
            var conn = new SqliteConnection(_connectionString);
//加入
            **SQLitePCL.Batteries.Init();**
            return conn;
        }
在其余平台,windows,android都正常的

**Comment by peng0829** [comment]
我使用的是SQLitePCLRaw.bundle_e_sqlite3和SQLitePCLRaw.bundle_e_sqlcipher

**Comment by densen2014** [comment]
issue 搜索 xamarin

**Comment by luoyunchong** [comment]
bundle_e_sqlite3 和bundle_e_sqlcipher 只要二选一就行

`SQLitePCL.Batteries.Init();` 只用调用一次，不需要在new SqliteConnection 每次都调用 

https://docs.microsoft.com/zh-cn/dotnet/standard/data/sqlite/xamarin#ios

**Comment by peng0829** [comment]
> bundle_e_sqlite3 和bundle_e_sqlcipher 只要二选一就行
> 
> 
> 
> `SQLitePCL.Batteries.Init();` 只用调用一次，不需要在new SqliteConnection 每次都调用 
> 
> 
> 
> https://docs.microsoft.com/zh-cn/dotnet/standard/data/sqlite/xamarin#ios

谢谢 已解决问题

**Comment by peng0829** [comment]
> issue 搜索 xamarin

谢谢 已解决问题
