### ISSUE TITLE
Orm.Ado.ExecuteReader 方法

### ISSUE THREAD

**Issue by snail2015** [dotnetcore/FreeSql#109]
在使用ExecuteReader 得到返回的DbDataReader 对象后,如果根据使用ADO的习惯,直接进行While(dr.Read()) 
{ ... }
会导致首行数据丢失,原因为,在 AdoProvider.cs 文件中, 为了判断是否有返回数据,底层提前进行了一次Read,导致读取器往下走了一次.
源码:
if (IsTracePerformance) logtxt_dt = DateTime.Now;
                            bool isread =  dr.Read();       // <======================
                            if (IsTracePerformance) logtxt.Append("	dr.Read: ").Append(DateTime.Now.Subtract(logtxt_dt).TotalMilliseconds).Append("ms Total: ").Append(DateTime.Now.Subtract(dt).TotalMilliseconds).Append("ms\r\n");
                            if (isread == false) break;

建议修改成:
if (IsTracePerformance) logtxt_dt = DateTime.Now;
                            bool hasRows =  dr.HasRows;   // <======================
                            if (IsTracePerformance) logtxt.Append("	dr.Read: ").Append(DateTime.Now.Subtract(logtxt_dt).TotalMilliseconds).Append("ms Total: ").Append(DateTime.Now.Subtract(dt).TotalMilliseconds).Append("ms\r\n");
                            if (hasRows == false) break;

**Comment by 2881099** [comment]
ExecuteReader 回调方法里面，其实不需要自己循环 Read() 向下读取，它是 Read() 循环体内的处理方法。

已经设计成这样，动一发牵涉面较多。抱歉

**Comment by 2881099** [comment]
很少有用户用上这个方法，试试 ExecuteArray 返回二维数组 object[][]，缺点：多一次类型转换。
