### ISSUE TITLE
如果在连表查询中都加上WithLock

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/FreeSql#1090]
#### 问题描述及重现步骤：
我们使用的是Mssql,查询默认是带上锁的,所以避免这样问题,,我们查询语句都是这样子
fsql.Select<Topic>().WithLock().ToList();
但是现在有两个问题
1. 如何在全局设置WithLock()
2. 如何在连表的时候,如果把导航表也加上WithLock
Fsql.Select<MesPackingDetail>().WithLock()
  .InnerJoin(x => x.Wo.WoNo == x.WoNo)
  .InnerJoin(x => x.Wo.RouteMain.RouteNo == x.Wo.RouteNo)
怎样把Wo和RouteMain都加上WithLock

**Comment by 2881099** [comment]
1、全局设置 WithLock

```c#
//以下代码设置一次
fsql.SetGlobalSelectWithLock(SqlServerLock.NoLock);

//或者指定类型加锁
fsql.SetGlobalSelectWithLock(SqlServerLock.NoLock, new Dictionary<Type, bool>
{
    [typeof(Order)] = true,
    [typeof(OrderItem)] = true,
});
```

---

2、单次设置多表加锁

```c#
var sql = orm.Select<Topic>()
    .InnerJoin(a => a.Type.Guid == a.Id)
    .WithLock()
    .ToSql();
```

```sql
SELECT a.[Id], a.[Clicks], a.[TypeGuid], a__Type.[Guid], a__Type.[ParentId], a__Type.[Name], a.[Title], a.[CreateTime] 
FROM [tb_topic22] a With(NoLock) 
INNER JOIN [TestTypeInfo] a__Type With(NoLock) ON a__Type.[Guid] = a.[Id]
```

**Comment by bao2314483** [comment]
@2881099 
public static IFreeSql SetGlobalSelectWithLock(this IFreeSql that, SqlServerLock lockType, Dictionary<Type, bool> rule)
请第二个参数是设置null吗?还是需要遍历表对象一一加进去

**Comment by 2881099** [comment]
@bao2314483 null 就是全部生效，除非你玩指定实体才生效
