### ISSUE TITLE
oracle  使用 delete<> 删除超过1000个实体时，报错参数太多

### ISSUE THREAD

**Issue by zhouandke** [dotnetcore/FreeSql#1091]
#### 问题描述及重现步骤：
`var myClassList = Fsql.Select<MyClass>().Take(10000).ToList();
Fsql.Delete<MyClass>(myClassList).ExecuteAffrows();`
会报错参数超过1000个的异常，希望可以分解成一个事务里的多条sql来解决。

虽然可以像下面这样来规避这个异常
`Fsql.Delete<MyClass>().Where(o=> idArray.ConTain(o.Id).ExecuteAffrows(); `
但如果MyClass是复合主键的时候特别麻烦

#### 数据库的具体版本
```
oracle 11g
```

#### 安装的包
```
FreeSql.Provider.Oracle   3.2.500
```

#### .net framework/. net core？ 及具体版本
```
.net core 5.0
```

**Comment by 2881099** [comment]
也可以这样：

```c#
Fsql.Select<MyClass>().Take(10000).ToDelete().ExecuteAffrows();
```

**Comment by zhouandke** [comment]
这次是用在 冷数据转移，由于规则比较复杂，只能用代码来分页读取。
由于主库一直在写入，相同条件的前后两次查询结果总是不同，所以删除的时候只能按已写入冷库数据的主键来进行
我曾尝试 select<MyClass>(somelist).ToDelete()也会报同样的错误
