### ISSUE TITLE
生成工具读取自定义模版时中文编码错误

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/FreeSql#1096]
#### 问题描述及重现步骤：
生成工具读取自定义模版时中文编码错误。
1.  复制工具生成的`__razor.cshtml.txt`
2.  去掉txt用vs的razor编辑器改
3.  从浏览器复制表格的html元素到vs的xml文件中格式化
4.  从xml文件中复制到模版文件中，把文字替换为razor语法

原始: `<span style="font-size: 12pt;" data-mce-style="font-size: 12pt;">@gen.FullTableName  xxx表</span>`
生成: `<span style="font-size: 12pt;" data-mce-style="font-size: 12pt;">eform_qms_closereview  xxx��</span>`

#### 数据库的具体版本
mysql 8.0.17 docker部署的

#### 安装的包
```
 FreeSql.Generator v3.2.610
```

#### .net framework/. net core？ 及具体版本
```
.NET 6.0 SDK
```

我知道工具可以读取库的注释，但我这里没使用，乱码的是模版部分。

**Comment by 2881099** [comment]
.txt 编码是 utf8 的吗

**Comment by hjkl950217** [comment]
是的  我放到notepad++上面看了下  是UTF8。。 但数据库是docker版的，有这个影响么？

**Comment by hjkl950217** [comment]
再补充一下我的场景： 
我是想快速生成数据库设计文档，生成后自己改注释（数据表是另一个产品创建的，他不会写入注释）。
按要求，要在页面的富文本编辑器中手写。我看了一下，表格是比较简单的HTML元素， 就想利用这个自定义模版功能帮我生成一部分。生成后手动复制去改页面上就行了

**Comment by 2881099** [comment]
乱码一般是编码的问题，看看是读的时候出问题，还是写的时候。

**Comment by hjkl950217** [comment]
恩。。明天我模拟工具读取的方式读取看看。

**Comment by 2881099** [comment]
升级下 freesql.generator 版本

**Comment by hjkl950217** [comment]
好  明天我测试了再来反馈一下。。

**Comment by hjkl950217** [comment]
我把源代码拉进来跑了调试下，确实在读取时发生乱码了，又查看文件居然是不是utf8（在改成cshtml编辑时，确实是UTF8）。
我的问题解决了， 但有个建议，回头我提个PR过来，贡献一波啊哈哈
