### ISSUE TITLE
oracle 自动分表，查询报错

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1098]
freesql 版本3.2.610
生成如下语句，

SELECT  t.* FROM (SELECT  t.* FROM (SELECT  * from (SELECT a."ID" as1, a."CREATED_BY" as2, a."CREATED_BY_NAME" as3,
 a."CREATED_TIME" as4, a."REAL_NAME" as5, a."IP" as6, a."BROWSER" as7, a."OS" as8, a."DEVICE" as9,
 a."BROWSERINFO" as10, a."ELAPSED_MILLISECONDS" as11, a."STATUS" as12, a."MESSAGE" as13, a."RESULT" as14
FROM "SYS_L_LOG_202204" a
ORDER BY a."ID" DESC) t WHERE ROWNUM < 21) ftb

UNION ALL

SELECT  * from (SELECT a."ID" as1, a."CREATED_BY" as2, a."CREATED_BY_NAME" as3, a."CREATED_TIME" as4, a."REAL_NAME" as5, a."IP" as6, a."BROWSER" as7, a."OS" as8, a."DEVICE" as9, a."BROWSERINFO" as10, a."ELAPSED_MILLISECONDS" as11, a."STATUS" as12, a."MESSAGE" as13, a."RESULT" as14
FROM "SYS_L_LOG_202201" a
ORDER BY a."ID" DESC) t WHERE ROWNUM < 21) ftb

报如下错
![image](https://user-images.githubusercontent.com/36889438/167867572-19b23e3b-cb4b-47ae-beaf-a57969771109.png)

**Comment by sukney** [comment]
相同的代码 pgsql 是正常的，oracle 生成的语句有问题。

**Comment by 2881099** [comment]
确实，嵌套多层拼接有问题

**Comment by 2881099** [comment]
v3.2.620 已发布

**Comment by sukney** [comment]
升级了 包出现兼容性问题了，编译通不过。
![image](https://user-images.githubusercontent.com/36889438/168008256-67c42fc9-1890-44a4-95c4-91e92804f9dc.png)

**Comment by 2881099** [comment]
你玩把所有 freesql 相关 dll 都升级

**Comment by sukney** [comment]
都升级了

**Comment by 2881099** [comment]
错误提示明明显示高于 3.2.610

**Comment by 2881099** [comment]
刚查看了下，是发布版本的问题，等会重新发布
