### ISSUE TITLE
freesql Oracel 自动分表，当查询的日期在一个月内，但生成的sql 仍然  几个月的

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1099]
freesql 3.2.630
Oracel 自动分表，当查询的日期在一个月内，但生成的sql 仍然 是查询几个月的 数据，生成的sql如下
SELECT * from (SELECT t.* FROM (SELECT a."ID" as1, a."CREATED_BY" as2, a."CREATED_BY_NAME" as3, a."CREATED_TIME" as4, a."REAL_NAME" as5, a."IP" as6, a."BROWSER" as7, a."OS" as8, a."DEVICE" as9, a."BROWSERINFO" as10, a."ELAPSED_MILLISECONDS" as11, a."STATUS" as12, a."MESSAGE" as13, a."RESULT" as14
FROM "SYS_L_LOG_202204" a
WHERE (a."CREATED_TIME" between to_timestamp('2022-05-01 00:00:00.000000','YYYY-MM-DD HH24:MI:SS.FF6') and to_timestamp('2022-05-12 21:26:31.639469','YYYY-MM-DD HH24:MI:SS.FF6'))
ORDER BY a."ID" DESC) t WHERE ROWNUM < 21) ftb

UNION ALL

SELECT * from (SELECT t.* FROM (SELECT a."ID" as1, a."CREATED_BY" as2, a."CREATED_BY_NAME" as3, a."CREATED_TIME" as4, a."REAL_NAME" as5, a."IP" as6, a."BROWSER" as7, a."OS" as8, a."DEVICE" as9, a."BROWSERINFO" as10, a."ELAPSED_MILLISECONDS" as11, a."STATUS" as12, a."MESSAGE" as13, a."RESULT" as14
FROM "SYS_L_LOG_202201" a
WHERE (a."CREATED_TIME" between to_timestamp('2022-05-01 00:00:00.000000','YYYY-MM-DD HH24:MI:SS.FF6') and to_timestamp('2022-05-12 21:26:31.639469','YYYY-MM-DD HH24:MI:SS.FF6'))
ORDER BY a."ID" DESC) t WHERE ROWNUM < 21) ftb

我的代码
![image](https://user-images.githubusercontent.com/36889438/168086613-79e1a2b6-0ffb-4a3b-9be5-5fd177bc7ab9.png)

**Comment by sukney** [comment]
实体  注解   [Table(Name = "sys_l_log_{yyyyMM}", AsTable = "CreatedTime=2022-1-1(3 month)")]

**Comment by sukney** [comment]
同样的代码pgsql是正常的，生成的只有一条语句
SELECT a."ID" as1, a."CREATED_BY" as2, a."CREATED_BY_NAME" as3, a."CREATED_TIME" as4, a."REAL_NAME" as5, a."IP" as6, a."BROWSER" as7, a."OS" as8, a."DEVICE" as9, a."BROWSERINFO" as10, a."ELAPSED_MILLISECONDS" as11, a."STATUS" as12, a."MESSAGE" as13, a."RESULT" as14
FROM "sys_login_log_202204" a
WHERE (a."CREATED_TIME" between '2022-05-01 00:00:00.000000' and '2022-05-12 21:40:45.573591')
ORDER BY a."ID" DESC
limit 20

**Comment by 2881099** [comment]
收到，等会发布新版本

**Comment by 2881099** [comment]
v3.2.631
