### ISSUE TITLE
建议增加对System.Transactions.TransactionScope的支持

### ISSUE THREAD

**Issue by liuguiyou** [dotnetcore/FreeSql#110]
对System.Transactions.TransactionScope不支持，当使用System.Transactions.TransactionScope出 
    现异常时没有回滚，例如

     using (var trans = new System.Transactions.TransactionScope(System.Transactions.TransactionScopeAsyncFlowOption.Enabled))
     {
                    var r1 = await freeSql.Delete<ApplicationUserRole>(new ApplicationUserRole() { UserId = 91, RoleId = 1 }).ExecuteAffrowsAsync();
                    var r2 = await freeSql.Update<ApplicationUser>().SetSource(new ApplicationUser() { Id = 1, CreatedBy = 1 }).UpdateColumns(new string[] { nameof(ApplicationUser.CreatedBy) }).ExecuteAffrowsAsync();

                    throw new System.Exception();

                    var r3 = await freeSql.Insert<ApplicationUserRole>(new ApplicationUserRole() { UserId = 91, RoleId = 1 }).ExecuteAffrowsAsync();
         
                    trans.Complete();
    }

**Comment by 2881099** [comment]
目前不支持TransactionScope

**Comment by 2881099** [comment]
按道理说应该支持，是不是不能用异步方法

**Comment by liuguiyou** [comment]
数据库驱动使用的MysqlConnector,
MysqlConnector本身是支持TransactionScope的,
由于FreeSql使用了自己的池化技术，
导致无法TransactionScope无法正确传递到底层驱动

**Comment by 2881099** [comment]
问题来了，是否要放弃自有的池化技术。或者有没其他解决办法？从资料看来，它的限制挺多，https://m.aliyun.com/yunqi/articles/683443，欢迎继续讨论

**Comment by liuguiyou** [comment]
不知放弃自有的池化技术对FreeSql有哪些影响？大多底层数据库驱动都实现了链接池。
如果不使用自有的池化技术，是否事务也可以支持异步方法了？

**Comment by 2881099** [comment]
> 不知放弃自有的池化技术对FreeSql有哪些影响？大多底层数据库驱动都实现了链接池。
> 如果不使用自有的池化技术，是否事务也可以支持异步方法了？

自有池化目的是为了保障多种数据库间的一致行为，之前有测试不同的数据库ado.net的释放行为有差异。有了池化技术后，使用者不再会出现连接资源报错的问题。

池化技术，和事务异步没关系。因为前面已经先实现了同步事务，再使用异步事务会搞乱内部对象，可能会导致难以排查的bug，如用户同时开启了异步，和同步事务。

异步事务通过 AsyncLocal 可以实现，目前我在 FreeSql.DbContext UintOfWork 种增加了 Current 属性可以访问当前工作单元对象。

异步事务，推荐使用工作单元。
