### ISSUE TITLE
集合为空会删除 null数据

### ISSUE THREAD

**Issue by donet5** [dotnetcore/FreeSql#1107]
var testlinq = select.Where(a => testlinqlist.Contains(a.Int)).ToList();
            var testlinq2list = new string[] { };
            var testlinq2 = g.sqlite.Delete<TableAllType>().Where(a => testlinq2list.Contains(a.String)).ToSql();
            Assert.Equal("DELETE FROM \"tb_alltype\" WHERE (((\"String\") in (NULL)))", testlinq2);

            //in not in
            var sql111 = select.Where(a => new[] { 1, 2, 3 }.Contains(a.Int)).ToList();

**Comment by donet5** [comment]
正确的是 where 1<>2

**Comment by donet5** [comment]
https://github.com/dotnetcore/FreeSql/issues/1107

**Comment by 2881099** [comment]
谢谢，这个是早期机制确定问题，用户意见不统一，现在看来 1<>2 是比较合适。由于不想改变前面的习惯，所以就这样了。

**Comment by donet5** [comment]
在给你提个BUG  ，这个count是假异步吧，where都没有生效，count应该输出0实际输出不是0
```
long xx = 0;
var data1 = FreeSqlContext.fsql.Select<Test>()
    .Page(1,10)
    .Count(out xx)
        .Where(x => false) //不查一条记录
        .ToListAsync()```
```

**Comment by 2881099** [comment]
谢谢反馈，因为 out 不支持异步，Count(out var total) 是同步方法，Where 在后面不被执行，这些都是已知的，只能说 api 设计不同，不是 bug

**Comment by donet5** [comment]
100万以上的数据 Count时间是大于 分页时间的  ，你知道我就先关了
