### ISSUE TITLE
.Net Framwork4.0 下异常

### ISSUE THREAD

**Issue by shusongLu** [dotnetcore/FreeSql#1114]
![image](https://user-images.githubusercontent.com/26265884/169769598-e09af822-70d4-4196-a532-f5911fb44377.png)
提示连接字符串错误

![image](https://user-images.githubusercontent.com/26265884/169769680-a73a8a82-e7b8-4db7-9da2-7972e3c36748.png)
实际上是找不到sqlite.Interop.dll
![image](https://user-images.githubusercontent.com/26265884/169769804-47ebb041-0be2-4f93-9a49-36f90860c88c.png)
将生成改为x64或x86都无法解决

**Comment by 2881099** [comment]
这是 .net framework dll 引用问题，要在启动项目引用才行

**Comment by shusongLu** [comment]
在https://stackoverflow.com/questions/26768005/system-data-sqlite-from-nuget-interop-dll-not-copied-to-output-directory 找到解决了
