### ISSUE TITLE
子查询报错 是因为Type关键字吗？

### ISSUE THREAD

**Issue by zhangkeyuan** [dotnetcore/FreeSql#1118]
![image](https://user-images.githubusercontent.com/24730412/169979343-81a6bf5b-2bb5-4351-927b-1883604ffea8.png)

使用.Where(o => o.ActivityType == ac.Type)报错
版本号：3.2.640

`        var activityPeopleCountList = _fsql.Select<SalesmanActivityConfig>()
             .Where(a => a.SalesmanId == req.SalesmanId)
             .ToList(a => new ActivityPeopleCountModel
             {
                 Type = a.Type,
                 Count = _fsql.Select<SalesmanActivityOrder>()
                     .Where(o => o.SalesmanId == a.SalesmanId)
                     .Where(o => a.Type == o.ActivityType)//报错ArgumentException: Requested value 'a.`Type`' was not found.
                                                          //.Where("o.ActivityType = a.Type", null)//正常
                     .Where(o => o.PayStatus == SalesmanActivityOrderPayStatusEnum.YiWanCheng)
                     .WhereIf(req.StartTime.HasValue, o => o.AddTime.Between(req.StartTime.Value, req.EndTime.Value))
                     .Count(),
             });`

**Comment by zhangkeyuan** [comment]
使用 .Where("o.ActivityType = a.Type", null)正常

**Comment by zhangkeyuan** [comment]
![微信截图_20220524155412](https://user-images.githubusercontent.com/24730412/169979531-15a9e5b0-d032-42de-83f6-506d71551143.png)

**Comment by 2881099** [comment]
```c#
[Fact]
        public void PropertyType()
        {
            var fsql = g.mysql;

            var item = new issues1118_01 { Type = "xxx" };
            var list1 = fsql.Select<issues1118_01>()
                .Where(o => o.Type == item.Type)
                .ToList();
        }

        public class issues1118_01
        {
            public int id { get; set; }
            public string name { get; set; }
            public string Type { get; set; }
        }
```

测试正常

**Comment by zhangkeyuan** [comment]
> ```cs
> [Fact]
>         public void PropertyType()
>         {
>             var fsql = g.mysql;
> 
>             var item = new issues1118_01 { Type = "xxx" };
>             var list1 = fsql.Select<issues1118_01>()
>                 .Where(o => o.Type == item.Type)
>                 .ToList();
>         }
> 
>         public class issues1118_01
>         {
>             public int id { get; set; }
>             public string name { get; set; }
>             public string Type { get; set; }
>         }
> ```
> 
> 测试正常

那会是什么原因呀

**Comment by zhangkeyuan** [comment]
> > ```cs
> > [Fact]
> >         public void PropertyType()
> >         {
> >             var fsql = g.mysql;
> > 
> >             var item = new issues1118_01 { Type = "xxx" };
> >             var list1 = fsql.Select<issues1118_01>()
> >                 .Where(o => o.Type == item.Type)
> >                 .ToList();
> >         }
> > 
> >         public class issues1118_01
> >         {
> >             public int id { get; set; }
> >             public string name { get; set; }
> >             public string Type { get; set; }
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 测试正常
> 
> 那会是什么原因呀

是在子查询里面哦，外面查询没问题的

**Comment by 2881099** [comment]
```c#
[Fact]
public void PropertyType()
{
    var fsql = g.mysql;

    var item = new issues1118_01 { Type = "xxx" };
    var list1 = fsql.Select<issues1118_01>()
        .ToList(ac => new {
                
            count = fsql.Select<issues1118_01>().Where(o => o.Type == ac.Type).First(o => o.name)
        });
}

public class issues1118_01
{
    public int id { get; set; }
    public string name { get; set; }
    public string Type { get; set; }
}

```

也没问题哦，试试把 ac 改名为 a

**Comment by zhangkeyuan** [comment]
![image](https://user-images.githubusercontent.com/24730412/169981961-f88078dd-654f-42ba-9bf7-bc80c6aa0204.png)
改成a还是报错

**Comment by 2881099** [comment]
打印 SQL，正常吗

**Comment by zhangkeyuan** [comment]
![image](https://user-images.githubusercontent.com/24730412/169982449-85e67489-b760-44d9-a273-a35f1bd9a545.png)
直接赋值也没问题

**Comment by 2881099** [comment]
他是提示找不到 a.`Type`，SalesmanActivityConfig 这个表

**Comment by zhangkeyuan** [comment]
> 打印 SQL，正常吗

![image](https://user-images.githubusercontent.com/24730412/169983314-93b7547c-e7a7-4b04-915f-6f3caf598941.png)
换个顺序又提示ActivityType不存在了，表里是有这个字段的

**Comment by zhangkeyuan** [comment]
[JsonObject(MemberSerialization.OptIn), Table(Name = "salesman_activity_config", DisableSyncStructure = true)]
	public partial class SalesmanActivityConfig
	{
        /// <summary>
        ///<para>    </para>
        /// </summary>
	    [JsonProperty, Column(Name = "Id", DbType = "char(32)", IsNullable = false, IsPrimary=true)]
	    public string Id { get; set; }
	 
        /// <summary>
        ///<para>推销员Id    </para>
        /// </summary>
	    [JsonProperty, Column(Name = "SalesmanId", DbType = "char(32)", IsNullable = false)]
	    public string SalesmanId { get; set; }
	 
        /// <summary>
        ///<para>洗车卡业务类型:0=自助卡 1=自动卡 2=通用卡[BaseCardBussinessType]    </para>
        /// </summary>
	    [JsonProperty, Column(Name = "Type", DbType = "int", IsNullable = false)]
	    public BaseCardBussinessType Type { get; set; }
	 
        /// <summary>
        ///<para>收益    </para>
        /// </summary>
	    [JsonProperty, Column(Name = "DivideAmount", DbType = "decimal(10,2)", IsNullable = false)]
	    public decimal DivideAmount { get; set; }
	 
        /// <summary>
        ///<para>    </para>
        /// </summary>
	    [JsonProperty, Column(Name = "AddTime", DbType = "datetime", IsNullable = false)]
	    public DateTime AddTime { get; set; }
	 
        /// <summary>
        ///<para>    </para>
        /// </summary>
	    [JsonProperty, Column(Name = "UpdateTime", DbType = "datetime", IsNullable = true)]
	    public DateTime? UpdateTime { get; set; }
	 
    }
