### ISSUE TITLE
mysql的tinyint(1)被按照bit类型读取

### ISSUE THREAD

**Issue by dongfangzhizhu** [dotnetcore/FreeSql#1123]
#### 问题描述及重现步骤：
从mysql种读取类型为tinyint(1)的数据，在实体类种被映射为sbyte类型，这没有问题，但是读取的时候是按照bit类型读的，导致读出的数据只有0，1两种值，但是数据库种实际存储的值要更多一些。

#### 数据库的具体版本
```
mysql 8.0.25
```

#### 安装的包
```
FreeSql.Provider.MySql 3.2.660-preview22020525
```

#### .net framework/. net core？ 及具体版本
```
.Net 6
```

**Comment by 2881099** [comment]
实体类发一下

**Comment by dongfangzhizhu** [comment]
问题已经解决了，实体类是用FreeSql.Generator.exe生成的，java中同样的问题需要在连接串中增加tinyInt1isBit=false选项解决，.net中需要在连接串中增加TreatTinyAsBoolean=False就可以了

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/wiki/%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84#mysql%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
