### ISSUE TITLE
关于自动迁移

### ISSUE THREAD

**Issue by yangfan19** [dotnetcore/FreeSql#1125]
自动迁移能不能安全的在生产环境中使用，
如果使用了会有哪些问题？
如果需要在生产环境中自动分表，又不想开启自动迁移，该如何解决？

**Comment by 2881099** [comment]
自动迁移在线上不建议使用。

---

用于创建表，增加字段等操作，是安全的。
用于修改属性类型，或者实体类与表不完全映射的，都是不安全的，严重可能（可能）丢失数据。

---

自动分表，建议用【定时任务】调用 fsql.CodeFirst.SyncStructure(typeof(T), "table202206") 建表

**Comment by yangfan19** [comment]
好的，多谢指导

**Comment by 2881099** [comment]
轻量化定时任务，可以考虑 IdleScheduler：

第一步：安装 IdleScheduler

```
.NETFramework 4.0
FreeSql >= 3.2.500)
IdleBus >= 1.5.2)
WorkQueue (>= 1.3.0)

.NETStandard 2.0
FreeSql >= 3.2.500)
IdleBus >= 1.5.2)
WorkQueue (>= 1.3.0)
```

-----

第二步：

```c#
//每在 11:00:00 触发
db.Scheduler.AddTaskRunOnDay("新建分表", "", round: 999999, 11, 0, 0);

public static class db
{
    static Lazy<IdleScheduler.Scheduler> schedulerLazy = new Lazy<Scheduler>(() =>
    {
        var scheduler = new Scheduler(new DbSchedulerHandler());
        return scheduler;
    });
    public static Scheduler Scheduler => schedulerLazy.Value;

    class DbSchedulerHandler : TestHandler
    {
        public override void OnExecuting(Scheduler scheduler, TaskInfo task)
        {
            switch (task.Topic)
            {
                case "新建分表":
                    fsql.CodeFirst.SyncStructure(typeof(Log), $"Log{DateTime.Now.AddDays(1).ToString("yyyyMM")}") 
                    break;
            }
        }
    }
}

**Comment by yangfan19** [comment]
嗯，明白了，感谢🙏

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 2881099 ***@***.***>
发送时间: Friday, May 27, 2022 6:57:30 PM
收件人: dotnetcore/FreeSql ***@***.***>
抄送: Fanix ***@***.***>; State change ***@***.***>
主题: Re: [dotnetcore/FreeSql] 关于自动迁移 (Issue #1125)


轻量化定时任务，可以考虑 IdleScheduler：

第一步：安装 IdleScheduler

.NETFramework 4.0

FreeSql >= 3.2.500)

IdleBus >= 1.5.2)

WorkQueue (>= 1.3.0)



.NETStandard 2.0

FreeSql >= 3.2.500)

IdleBus >= 1.5.2)

WorkQueue (>= 1.3.0)



________________________________

第二步：

//每在 11:00:00 触发

db.Scheduler.AddTaskRunOnDay("新建分表", "", round: 999999, 11, 0, 0);



public static class db

{

    static Lazy<IdleScheduler.Scheduler> schedulerLazy = new Lazy<Scheduler>(() =>

    {

        var scheduler = new Scheduler(new DbSchedulerHandler());

        return scheduler;

    });

    public static Scheduler Scheduler => schedulerLazy.Value;



    class DbSchedulerHandler : TestHandler

    {

        public override void OnExecuting(Scheduler scheduler, TaskInfo task)

        {

            switch (task.Topic)

            {

                case "新建分表":

                    fsql.CodeFirst.SyncStructure(typeof(Log), $"Log{DateTime.Now.AddDays(1).ToString("yyyyMM")}")

                    break;

            }

        }

    }

}
