### ISSUE TITLE
期望 Aop.SyncStructureAfter 能够传递自动同步的类型和表名称，而不是仅传递自动同步的类型。

### ISSUE THREAD

**Issue by VicBilibily** [dotnetcore/FreeSql#1127]
#### Feature 特性
期望 Aop.SyncStructureAfter 能够传递自动同步的类型和表名称，而不是仅传递自动同步的类型。
https://github.com/dotnetcore/FreeSql/blob/f7f54ceaacd6ec934b7acf8c05731a37fa1a7d60/FreeSql/Internal/CommonProvider/CodeFirstProvider.cs#L94-L131

#### 使用场景
在开启自动分表的情况下需要知道具体自动处理了哪个表以便进行后续操作。

**Comment by 2881099** [comment]
```c#
var tb = fsql.CodeFirst.GetTableByEntity(entityType);
var tableName = tb.Attribute.Name;
```

**Comment by VicBilibily** [comment]
翻了一下动态 是可以定时执行分表处理 https://github.com/dotnetcore/FreeSql/issues/1125#issuecomment-1139226763
