### ISSUE TITLE
3.2.651 - Aop.AuditValue is not fired at updating

### ISSUE THREAD

**Issue by zsolt777** [dotnetcore/FreeSql#1129]
Hi,

Using the code below the AuditValue event is fired at insert as expected, but it is not fired at update.

I'm using .NET Framework 4.6.2, and Sqlite

Thank you!

```
    [Table(Name = "NtakRendelesOsszesito")]
    public class NtakRendelesOsszesitoData
    {
        [Column(IsPrimary = true, IsIdentity = true)]
        public long ID { get; set; }

        [Column]
        public long RowVersion { get; set; }
    }

                DB.Aop.AuditValue += (_, e) =>
                {
                    if (e.Column.CsName == "RowVersion")
                    {

                    }
                };

                var dto = new NtakRendelesOsszesitoData();
                dto.ID = DB.Insert(dto).ExecuteIdentity();

                DB.Update<NtakRendelesOsszesitoData>(dto.ID)
                    .Set(p => p.RowVersion, 1234).ExecuteAffrows();

```

**Comment by 2881099** [comment]
This AOP AudutValue is only valid for entity operations.

You try it :

\[Column(IsVersion = true)\]

Or describe your usage scenarios.

**Comment by zsolt777** [comment]
Basically I would like to periodically send the changed records to a server, I do not need locking.

So what I need is similar to the timestamp datatype in Sql Server. If anything changes in a row then its version is updated to the biggest version number in that table (not just incremented by one), so later I can easily determine which records to synchronize, because I just need to konw the biggest version number I sent to the server last time.

Thank you!

**Comment by 2881099** [comment]
```c#
DB.Update<NtakRendelesOsszesitoData>(dto.ID)
    .Set (p => p.rowversion, 1234)
    .ExecuteAffrows();
```

This operation is object-based and cannot trigger AOP AuditValue.

If all operations are object-based, it is easy to be realistic.

```c#
var item = new NtakRendelesOsszesitoData
{
    ID = dto.ID,
    RowVersion = 1234
};
DB.Update<NtakRendelesOsszesitoData>()
    .SetSource(item)
    UpdateColumn(p => p.RowVersion)
    .ExecuteAffrows();
```
