### ISSUE TITLE
Maui App中 FreeSql Sqlite 不能用 Android运行  会报错  希望能兼容下  Maui正式发布了 可以跟进了哇

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#1134]
希望大佬看看

**Comment by lhtuling** [comment]
或者是不是我使用方法问题?  有没有相关示例或者教程!

**Comment by luoyunchong** [comment]
see http://freesql.net/guide/freesql-provider-sqlitecore.html

**Comment by lhtuling** [comment]
> see http://freesql.net/guide/freesql-provider-sqlitecore.html

感谢大佬 我这边测下看看

**Comment by 2881099** [comment]
https://www.cnblogs.com/densen2014/p/16240966.html

**Comment by densen2014** [comment]
https://github.com/densen2014/FreeSqlDemos/tree/master/Maui
