### ISSUE TITLE
关于uow的问题

### ISSUE THREAD

**Issue by yangfan19** [dotnetcore/FreeSql#1138]
当 using(var uow = freesql.CreateUnitOfWork()) 时，是否只能使用 uow.GetRepository()的仓储实例进行 CRUD 才能实现事务？

**Comment by yangfan19** [comment]
在using代码块内如果使用 非仓储的增删改查，提交时会被事务所限制么？

**Comment by 2881099** [comment]
是的，cud 才开启事务，或者主动提前开启，uow.GetOrBeginTransaction(true)

**Comment by yangfan19** [comment]
可以用非仓储的方式cud么？这样的话还能回滚么？

**Comment by 2881099** [comment]
非仓储方法，可以使用 repo.Orm 或者 uow.Orm 操作，也属于一个事务。

**Comment by yangfan19** [comment]
嗯，好的。多谢。
