### ISSUE TITLE
Insert方法不传形参代码执行不抛异常数据插入不成功

### ISSUE THREAD

**Issue by wangyimingok** [dotnetcore/FreeSql#1139]
#### 问题描述及重现步骤：
freesq.Insert(DataEntity).ExecuteAffrowsAsync()
代码执行正常，数据库并没有插入数据，监视窗口也没有生成insert语句。
Insert<UserInfo>(DataEntity).ExecuteAffrowsAsync()
代码执行正常，数据被成功插入

#### 数据库的具体版本
```
SQL Server 2019
```

#### 安装的包
```
FreeSql 3.2.651
FreeSql.Provider.SqlServer 3.2.651
```

#### .net framework/. net core？ 及具体版本
```
.NET 6.0.5
```
建议：
插入失败时抛出异常提示，需传入与实体对应的形参类型。或者其他友好提示

**Comment by 2881099** [comment]
有 demo 吗

**Comment by wangyimingok** [comment]
> 有 demo 吗

我写一个demo上传过来看看
