### ISSUE TITLE
调用BaseRepository<TEntity>.Delete(t=>true)偶发性假死

### ISSUE THREAD

**Issue by qile3897** [dotnetcore/FreeSql#1142]
#### 问题描述及重现步骤：
首先偶发性问题，暂时没有发现能稳定触发的条件
出现假死后，其他语句可正常执行，但是删除语句尤其是全表清除语句假死，即不报错也不向后执行
同时我在vs本地debug可复现该问题，重启docker可解决此问题，但不定时会出。
出现时也查了下数据库的v$session,和v$process发现没什么问题
怀疑我的库有问题、docker+oracle xe 、但是出现问题其他语句可以执行，故暂时排除，后续可能会将数据库从docker中拿出再进行测试
1. 出现问题的语句1：
`BaseRepository<Appointment_Current> _appointmentCurrentRepository;//注入`
`_appointmentCurrentRepository.Delete(t => true);//全表清除`
2. 出现问题的语句2：
`_freeSql.Delete<Round_Current>().Where("1=1").ExecuteAffrows();//全表清除`
#### 数据库的具体版本
```
oracle 11gR2 xe + docker环境
```

#### 安装的包
```
FreeSql
FreeSql.DbContext
FreeSql.Provider.Oracle
```

#### .net framework/. net core？ 及具体版本
```
.net core 3.1
```

**Comment by qile3897** [comment]
> 可能是表死锁，批量操作应该开事务，隔离级别调至表

调用的时候，是开着事务的

**Comment by 2881099** [comment]
> > 可能是表死锁，批量操作应该开事务，隔离级别调至表
> 
> 调用的时候，是开着事务的

事务级别要设置，百度一下
