### ISSUE TITLE
ExecuteIdentity增加Oracle、MySQL的支持，特别是Oracle

### ISSUE THREAD

**Issue by cuiwenyuan** [dotnetcore/FreeSql#1149]
#### Feature 特性

long ExecuteIdentity();
        /// <summary>
        /// 执行SQL语句，返回插入后的记录<para></para>
        /// 注意：此方法只有 Postgresql/SqlServer 有效果
        /// </summary>
        /// <returns></returns>

#### 简要描述原因

没有这个功能，没办法替换现在用的DAL

**Comment by 2881099** [comment]
ExecuteIdentity，还是 ExecuteInserted ？

**Comment by luoyunchong** [comment]
是`ExecuteInserted`只有 Postgresql/SqlServer 有效果

**Comment by 2881099** [comment]
估计看茬了注释，ExecuteIdentity 不受数据库限制的
