### ISSUE TITLE
oracle 自动分表数据库大的时候会卡住

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1162]
oracle 自动分表数据量大的时候很慢偶尔会卡住。
在不开启自动迁移的情况下，有没有办法手工创建分表，oracle当数据量大的时候自动迁移有时候会卡住。比如在插入数据的时候手工创建某月的分表。

**Comment by 2881099** [comment]
fsql.Codefirst.SyncStructure 方法可以手动建表

var tb = fsql.CodeFirst.GetTableByEntity(typeof(T));

tb.AsTableImpl.GetTableByXxx 可以得到表名
