### ISSUE TITLE
最近研究DDD,请问FreeSql对于充血模型和IOC如何处理?

### ISSUE THREAD

**Issue by aaasssmnb** [dotnetcore/FreeSql#117]
DDD要求实体有行为有业务逻辑
业务逻辑需要依赖其他东西,比如仓储,比如其他一些Domain基础设施,这些都通过接口注入
现在问题是FreeSql返回的实体或者列表如何实现自动注入?
比如我使用autofac,能否通过实现一些FreeSql的接口实现自动注入?

**Comment by 2881099** [comment]
了解，实体注入不了这些窗口的信息。FreeSql与注入没有绑定关系。

但是可以通过 TrackToList 方法重新修饰查询到实体对象，再用反射手段设置其应该设置的类型。

```csharp
fsql.Select<T>().TrackToList(Action).ToList();
```

这个不好做，麻烦，之前弄的 BaseEntity 设置的全局属性来做的。
每个实体与一个 IFreeSql 强制关联。

代码在这里：https://github.com/2881099/FreeSql/blob/master/Extensions/FreeSql.Extensions.BaseEntity/BaseEntityReadOnly.cs
