### ISSUE TITLE
freeSql查询单条记录时，传入可为null的Id值时，会默认返回一条无效数据

### ISSUE THREAD

**Issue by q13044256742** [dotnetcore/FreeSql#1179]
#### 问题描述及重现步骤：
调用 freeSql.Select<Entity>(Id).ToOne(); 时，如果Id为null，会返回一条无效但正常的数据，实际开发中，Id值多为动态传入，有可能为null，此时会导致出现非期望的结果，目前只能手动对涉及的Id全部做非null判断，希望对Id传入null的能直接返回null
（包括 ToOneAsync 、First、FirstAsync 等均为相同逻辑）

#### 数据库的具体版本
```
无
```

#### 安装的包
```
无
```

#### .net framework/. net core？ 及具体版本
```
net 5
```

**Comment by 2881099** [comment]
研究发现了以下问题导致无法优化。

由于 Select(object dywhere) 这个定义，如下：

int? id = null;
fsql.Select(id).First();

内部 Select 方法无法得到 int? 类型，从而无法判断查询为主键的情况。

目前 dywhere 可以是：

* 主键值
* `new[] { 主键值1, 主键值2 }`
* Topic 对象
* `new[] { Topic对象1, Topic对象2 }`
* `new { id = 1 }`
