### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yangQingYu123** [dotnetcore/FreeSql#118]
使用多表关联时,全局filter不起效！
多次IgnoreColumns不起效！
update时多次Set会报错

**Comment by 2881099** [comment]
全局filter只针对仓储类的查询方法。如果直接使用 IFreeSql.Select 是不起做用。

IgnoreColumns只有最后一次起使用，所以需要提前把 string[] 组装好了再传入。

update时多次Set会报错，可能根数据库有关，有的支持有的不支持。要不直接更新整个实体吧，利用仓储的功能（只更新变化的属性，没有变化的属性不产生SQL）
