### ISSUE TITLE
贪懒加载子集数据为null的问题

### ISSUE THREAD

**Issue by cesaryuan** [dotnetcore/FreeSql#1181]
#### 问题描述及重现步骤：

当贪婪加载子集数据（`IncludeMany(x => x.Songs)`）时，若子集（Songs）类型为`public Song[] Songs { get; set; }`而不是`public List<Song> Songs { get; set; }`时，前者获取到的Songs为null，后者则正常。
建议这里如果为Array则抛出异常，并提醒用户更换为List

#### 数据库的具体版本
```
无关
```

#### 安装的包
![image](https://user-images.githubusercontent.com/35998162/178142992-6c73dbd1-189d-4ddb-9609-f7e94f2e78d0.png)

#### .net framework/. net core？ 及具体版本
```
.net core 6
```

**Comment by 2881099** [comment]
可以是 ICollection，ObservableCollection，List 类型，不可以数组，因为数组类型对一些功能有限制。

**Comment by 2881099** [comment]
可以是 ICollection，ObservableCollection，List 类型，不可以数组，因为数组类型对一些功能有限制。

**Comment by cesaryuan** [comment]
> 可以是 ICollection，ObservableCollection，List 类型，不可以数组，因为数组类型对一些功能有限制。

嗯嗯，希望可以Warning一下或者在文档里说明
