### ISSUE TITLE
过滤条件叠加问题

### ISSUE THREAD

**Issue by zztongtong** [dotnetcore/FreeSql#1182]
例如：
var query=_context.Table.where(e=>e.a=="b");
var clist= query.where(e=>e.c=="c").toList();
var dlist=query.where(e=>e.d=="d").toList();
最后dlist 的结果是条件e.c=="c" 和 e.d=="d" 两个条件过滤出来的，并不是e.d=="d" 过滤出来的

**Comment by 2881099** [comment]
query 是引用对象，不是值对象。

如果需要可以看 #644

**Comment by zztongtong** [comment]
赵自通已收到，请放心

**Comment by zztongtong** [comment]
赵自通已收到，请放心
