### ISSUE TITLE
Db First代码生成器增加Json配置项

### ISSUE THREAD

**Issue by LeaFrock** [dotnetcore/FreeSql#1183]
#### Feature 特性

CLI增加新的option，-json STJ/NTJ （当然，最终参数名称可以商榷）

#### 简要描述原因

目前通过CLI使用DbFirst生成数据库实体模型，会默认绑定NewtonSoft.Json。在实际情况下，越来越多的新项目倾向于使用System.Text.Json，而不再使用NewtonSoft.Json。

Issue #633 提到STJ的易用性问题，现在（6.0.5+）大多已经解决。未支持的功能如JsonPath等，应该并不影响FreeSql做JsonMap的使用。

当前的DBFirst功能会导致FreeSql实际和NewtonSoft.Json强制绑定，如果Db表及列的数量较多，手动修改工作量巨大。希望能够完善DBFirst的代码生成功能，允许使用配置项指定生成代码所依赖的Json库。

当然，这个FR优先级可能不算高。但个人希望能将该其加入贵项目的迭代计划。

#### 使用场景

使用CLI基于DBFirst生成数据库实体类。

**Comment by 2881099** [comment]
收到

**Comment by 2881099** [comment]
暂时不处理，关闭。
