### ISSUE TITLE
能在ConfigEntityProperty的 ConfigEntityPropertyEventArgs 参数里获取model的值吗？

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1186]
使用场景，排序字段和编号生成字段，当新增的时候如果该字段为空就使用插入语句，如果该字段值不为空就不使用插入语句，用输入的值。目前在ConfigEntityProperty里不能获取model的字段值，请问能加个 e.object来传递model的值吗，我的代码如下，目前这里不能判断字段的值是什么。
![image](https://user-images.githubusercontent.com/36889438/179104297-569558e1-d77a-4d0c-8aa3-9c3a125d5560.png)

**Comment by 2881099** [comment]
ConfigEntityProperty 是实体特性处理，还没有到实体对象crud环节。并且实体特性处理是需要缓存的，而不是每次crud时才获取这些信息。

**Comment by sukney** [comment]
AuditValue  事件中能获取 IFreeSql 实例吗？  我想把这个放到AuditValue   用sql语句获取值。

**Comment by 2881099** [comment]
IFreeSql 是单例，任何地方都可以获取
