### ISSUE TITLE
ExecuteMySqlBulkCopy方法批量插入 ,bool类型字段问题

### ISSUE THREAD

**Issue by rongguohao** [dotnetcore/FreeSql#1187]
#### 问题描述及重现步骤：

ExecuteMySqlBulkCopy方法批量插入数据 ,bool类型字段，默认false，数据库中却显示为 1，试了ExecuteAffrows方法，数据库中显示正确为0    数据库字段类型 是 bit类型

#### 数据库的具体版本

Mysql5.7

#### 安装的包

FreeSql.Provider.MySqlConnector 3.2.665

#### .net framework/. net core？ 及具体版本

.net core 2.1

**Comment by 2881099** [comment]
群内回复结果：

fsql.Insert(list).ToDataTable() 得到值是正常的 true/false，数据库表类型是 bit，映射失败

解决办法：

修改表字段类型为 int

**Comment by luoyunchong** [comment]
[ConsoleApp1.zip](https://github.com/dotnetcore/FreeSql/files/9173845/ConsoleApp1.zip)

经测试也没有重现

**Comment by rongguohao** [comment]
> 

我在数据库中 SoftDeleted 前面加了一个字段 Name，代码中未添加Name属性，删除表数据后，重新insert，复现了这个问题

**Comment by 2881099** [comment]
数据库表和实体类，要一一对应，因为 mysql bulkcopy 应该采用的 cvs 导入，可能导致偏移

**Comment by luoyunchong** [comment]
你用的不是code first？手动修改了表结构啊

**Comment by rongguohao** [comment]
> 你用的不是code first？手动修改了表结构啊
是的 ，操作方式问题吧
