### ISSUE TITLE
分库分表

### ISSUE THREAD

**Issue by zgmqdl** [dotnetcore/FreeSql#119]
可否增加一些分库分表的示例，刚看了文档，就一句话很不明白，谢谢

**Comment by 2881099** [comment]
看完后，总结哪些不明白

**Comment by zgmqdl** [comment]
FreeSql.Repository 之分表
FreeSql 提供 AsTable 分表的基础方法，GuidRepository 作为分存式仓储将实现了分表与分库（不支持跨服务器分库）的封装。

var logRepository = fsql.GetGuidRepository<Log>(null, oldname => $"{oldname}_201903");
比如这个我用IFreeSql fsql = new FreeSql.FreeSqlBuilder()
    .UseConnectionString(FreeSql.DataType.MySql, "")
    .UseSlave("connectionString1", "connectionString2") //使用从数据库，支持多个
    .Build();取得的fsql就没有这个GetGuidRepository方法
另外我是刚用freesql，freesql支持sql server的反向工程吗？由程序动态创建数据库和表？

**Comment by 2881099** [comment]
仓储，IFreeSql 自带的crud 都可以分表操作。

IFreeSql 主打就是 CodeFirst 根据实体类自动创建表或更改表结构。

**Comment by zgmqdl** [comment]
自动创建数据库是否支持？谢谢您

**Comment by zgmqdl** [comment]
好的，谢谢

**Comment by zgmqdl** [comment]
不好意思还有个问题，
如果我配置自动生成表的话，这个操作应该是在哪里配置，我的表结构是order_1……n？
分库分表的规则是在哪里可以配置？
如果查询某个表的话需要指定数据库吗？还是程序会自动搜索对应的数据库？

**Comment by 2881099** [comment]
规则在AsTable上定义，或者仓储类。
数据库指定，如果是sqlverver也是上面的做法。其他数据库再说

**Comment by zgmqdl** [comment]
好的，我看看astable和仓储类。如果配置了分库分表的规则之后会自动根据规则创建数据表吗

**Comment by 2881099** [comment]
一会创建一对一的表，分表不会创建，要人工管理这块。

**Comment by 2881099** [comment]
规则目前需要每次指定，可以写个工厂模式管理。

**Comment by 2881099** [comment]
## v0.11.12

- 增加 AsTable 和 Repository 分表时的自动迁移分表功能；
- 增加 ICodeFirst.SyncStructure(Type entityType, string tableName) 指定表名来迁移实体；
```csharp
fsql.CodeFirst.SyncStructure(typeof(Log), "Log_1"); //迁移到 Log_1 表
fsql.CodeFirst.SyncStructure(typeof(Log), "Log_2"); //迁移到 Log_2 表
```
- 增加 PostgreSQL 特有功能 On Conflict Do Update 功能，[wiki](https://github.com/2881099/FreeSql/wiki/%e6%b7%bb%e5%8a%a0%e6%88%96%e4%bf%ae%e6%94%b9)；
- 完善 所有参数化 object parms 可使用 IDictionary 类型传入；

**Comment by 2881099** [comment]
> 不好意思还有个问题，
> 如果我配置自动生成表的话，这个操作应该是在哪里配置，我的表结构是order_1……n？
> 分库分表的规则是在哪里可以配置？
> 如果查询某个表的话需要指定数据库吗？还是程序会自动搜索对应的数据库？

分表的创建，在v0.11.12上实现了自动化

**Comment by zgmqdl** [comment]
感谢大哥，我拉下来试试。查询分库分表的数据库是如何工作的，是根据分库分表规则便利还是其他方式

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%e5%88%86%e5%8c%ba%e5%88%86%e8%a1%a8

分表，要手工管理规则
