### ISSUE TITLE
 能不能提供根据lamda只生成sql的功能

### ISSUE THREAD

**Issue by liyang-live** [dotnetcore/FreeSql#120]
能不能提供根据lamda只生成sql的功能，后续执行交给用户控制，有些业务上可能要把生成的sql给第三方让他们执行。

**Comment by 2881099** [comment]
需要哪些功能，目前根据导航属性，类型映射，主键，的特征生成的sql

**Comment by pjy612** [comment]
没理解错的话 正常写逻辑 最后 ToSql 就是产生的Sql 了。

至于Sql后续怎么执行 可以试试 fsql.Ado.xxx
