### ISSUE TITLE
使用FreeSql.Generator对SqlServer数据库表生成的实体属性位置和表中不一致

### ISSUE THREAD

**Issue by mildspark** [dotnetcore/FreeSql#1204]
FreeSql.Generator版本：3.2.665

表中显示顺序如下
![image](https://user-images.githubusercontent.com/40229360/183008543-b5fd9d34-b7af-4d44-9a8a-29747d6ee064.png)

但是生成的实体属性是按照字典顺序排的
![image](https://user-images.githubusercontent.com/40229360/183008691-b4f4eca6-ff2c-4f9b-82f4-dc79c805c676.png)

生成模板中如果按照字段的Position来排序，显示顺序也不正常
![image](https://user-images.githubusercontent.com/40229360/183008816-338bae1f-8694-4aac-a09b-5dfa7908c391.png)

查看了issues#1154，又看了下源代码，好像PgSql和Mysql是获取字段的ordinal_position之后根据ordinal_position来设置Position，而SqlServer是通过++position的方式来迭代position。
![image](https://user-images.githubusercontent.com/40229360/183009148-3d84afb4-8e0b-4386-8d35-0ab7b9f0d918.png)

**Comment by 2881099** [comment]
后面还有逻辑，顺序是：

主键
外键
名称排序

**Comment by 2881099** [comment]
```c#
loc4.Primarys.Sort((c1, c2) => c1.Name.CompareTo(c2.Name));
loc4.Columns.Sort((c1, c2) =>
{
    int compare = c2.IsPrimary.CompareTo(c1.IsPrimary);
    if (compare == 0)
    {
        bool b1 = loc4.ForeignsDict.Values.Where(fk => fk.Columns.Where(c3 => c3.Name == c1.Name).Any()).Any();
        bool b2 = loc4.ForeignsDict.Values.Where(fk => fk.Columns.Where(c3 => c3.Name == c2.Name).Any()).Any();
        compare = b2.CompareTo(b1);
    }
    if (compare == 0) compare = c1.Name.CompareTo(c2.Name);
    return compare;
});
```

**Comment by mildspark** [comment]
希望不是用默认的排序，而是能通过Position排序之后生成模板，参照OdbcMySqlDbFirst.cs中取ordinal_position来设置Position，对SqlServerDbFirst.cs进行了下修改，取sys.columns中的column_id来作为Position，之后在模板文件中根据Postion把字段排序，可以获得想要的结果
![image](https://user-images.githubusercontent.com/40229360/183024616-9e3b53fa-e382-4810-828e-694dea519517.png)


![image](https://user-images.githubusercontent.com/40229360/183025424-60dccbc2-464a-46d8-a7fe-81e3b3f473a8.png)


![image](https://user-images.githubusercontent.com/40229360/183024844-b2e96f3b-cf07-4af4-b432-5064fb589817.png)

**Comment by 2881099** [comment]
谢谢，已测试 sqlserver 2005 通过
