### ISSUE TITLE
AttachOnlyPrimary 修改字段异常

### ISSUE THREAD

**Issue by xf599** [dotnetcore/FreeSql#1211]
#### 问题描述及重现步骤：
我在使用AttachOnlyPrimary修改时，这三个字段是null，可最终生成的语句还有数据库中的结果都表示，我将这三个字段的值改成了空字符串了

<img width="882" alt="1660206714625" src="https://user-images.githubusercontent.com/45196859/184094766-12725fe9-57d8-46d5-a016-486b6b658157.png">

![image](https://user-images.githubusercontent.com/45196859/184094139-969771e2-4a26-4928-9d95-4361c0ffef71.png)

监测的sql语句，sql server数据库
UPDATE [bus_achievement_evaluator_expert] SET [UPDATED_BY] = @p_0, [UPDATED_BY_NAME] = @p_1, [UPDATED_TIME] = getdate(), [ExpertUserID] = @p_2, [AchEvaID] = @p_3, [AchID] = @p_4, [IsAccept] = @p_5, [REVISION] = isnull([REVISION], 0) + 1
WHERE ([ID] = N'6963526781723426816') AND ([IS_DELETED] = 0) AND [REVISION] = 0

#### 数据库的具体版本
```
3.2.665
```

#### 安装的包
```

```

#### .net framework/. net core？ 及具体版本
```
.net core 3.1
```

**Comment by 2881099** [comment]
_busachievementevaluatorexpertRepository.DbContextOptions.NoneParameter = true;

无参数化开启一下。

AttachOnlyPrimary 只会附加主键值状态。
