### ISSUE TITLE
子查询内的 Select AsType 后会 LeftJoin 基类表名

### ISSUE THREAD

**Issue by VicBilibily** [dotnetcore/FreeSql#1215]
DEMO示例 https://github.com/VicBilibily/FreeSql/commit/0712474875a8b7f56b7ebfc4935def81cf199293

**Comment by 2881099** [comment]
这个问题一直都存在，感谢反馈

**Comment by 2881099** [comment]
v3.2.666-preview20220819

已修复该问题
