### ISSUE TITLE
能否在实体定义时对表和列分别添加表注释 、列注释信息？

### ISSUE THREAD

**Issue by hchxxzx** [dotnetcore/FreeSql#1217]
#### Feature 特性
在实体定义特性中，针对表(Table)和列(Column)特性，分别添加表注释、列注释 字段。

#### 简要描述原因
一是可借助表注释、字段注释，可在代码中读取完整表、字段信息（如我需要将实体对象读取到缓存中并展示？或是需要使用该信息进行其他开发）
二是在自动建表时，可直接将此注释添加到表注释中（无需通过其他配置）。

**Comment by luoyunchong** [comment]
https://freesql.net/guide/code-first.html#%E5%A4%87%E6%B3%A8

**Comment by hchxxzx** [comment]
freesql可直接将xml写入数据库形成注释功能已知悉。
但我描述的与此功能并不一致。
1.添加新特性成本极低，且不影响其他功能。
直接在特性字段中，添加表备注、字段备注，由于不会对表、字段使用功能有任何影响，直接明了、成本低廉、简单方便。
对于读取XML、或Description 特性形成备注功能同样不影响。可通过优先级处理，理论上以特性字段为最优先。
2.添加此特性后，方便二次开发
现有特性已很丰富，仅缺少备注（注释）字段，虽然可通过XML注释或其他方式获取，但明明有了最好最直接的载体，为什么要拐弯来处理呢？
关于二次开发，比如我可能需要将所有对象的名称、字段等信息进行处理（如读取到缓存中，或是借此提供代码生成器等），如果有备注字段，则我直接读取特性信息即可；无需再辛辛苦苦读取XML文件。

以上。

**Comment by 2881099** [comment]
关于二次开发，可以这样：

```c#
var tb = fsql.CodeFirst.GetTableByEntity(typeof(T));
string entityDesc = tb.Comment; //实体类注释
var columnDesc = tb.Columns["Id"].Comment; //属性注释
```
