### ISSUE TITLE
更新传入 实体不工作。

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1218]
版本 3.2.660    pgsql
            var userBlance= await _accountRepository.Orm.Select<UserBlance>().Where(x => x.UserId == account.UserId).FirstAsync();
            userBlance.Blance =11111;
            await _accountRepository.Orm.Update<UserBlance>(userBlance).ExecuteAffrowsAsync();
在update构造函数中传入实体 userBlance  并不执行更新，生成的语句为  UPDATE "ms_user_blance" SET  ,set 后的都没有了。

await   _accountRepository.Orm.Delete<UserBlance>(userBlance).ExecuteAffrowsAsync();
同样的删除这样写是可以删除的。

**Comment by 2881099** [comment]
既然用了仓储应该这样更新，而不要随意使用 IFreeSql：

```c#
var userBlance= await _accountRepository.Select.Where(x => x.UserId == account.UserId).FirstAsync();
userBlance.Blance =11111;
await _accountRepository.Update(userBlance);
```

_accountRepository.Orm 对象是 IFreeSql 类型，所以 .Update 应该遵从 IUpdate 要求。

IUpdate 更新有两种模式：

1、更新对象：fsql.Update\<T\>().SetSource(object).ExecuteAffrows();

- SetSource 不需要传递 Where，因为会根据 Primary 设置产生 where 条件；
- SetSource 可以使用 UpdateColumns/IgnoreColumns 指定或忽略字段；

2、更新字段：fsql.Update\<T\>().Set(a => a.Blance, 11111).Where(...).ExecuteAffrows();

fsql.Update\<T\>(object dywhere) 这里参数只是条件、是条件、是条件，文档有说明的，虽然容易理解成更新对象。

**Comment by 2881099** [comment]
如果追求性能，你的代码可以用这种：

```c#
_accountRepository.UpdateDiy.Set(a => a.Blance, 11111).Where(a => a.UserId == account.UserId).ExecuteAffrows();

_accountRepository.Orm.Update<T>().Set(a => a.Blance, 11111).Where(a => a.UserId == account.UserId).ExecuteAffrows();
```

两行代码都是一样的效果
