### ISSUE TITLE
请教下主备库的问题

### ISSUE THREAD

**Issue by yinhz** [dotnetcore/FreeSql#122]
看了您主备库的示例，又翻了下代码。不知道以下描述是否正确。

当没开启事务时（使用UOW），是默认到备库查询的，要到主库查询需要使用 Master()

如果开启了事务，应该会一直用主库进行查询、更新等。

谢谢！

**Comment by 2881099** [comment]
又没有事务，都使用备库查询。

你的建议挺好，之后改成开启事务后，查主库。

**Comment by yinhz** [comment]
谢谢！

关于事务，我使用了以下两种使用方式，请综合考虑，谢谢。

using (var uow = MIDatabase.IFreeSql.CreateUnitOfWork())
{
    var equipmentRepo = uow.GetRepository<Equipment>();
}

using (var uow = MESDatabase.IFreeSql.CreateUnitOfWork())
{
    var equipmentRepo = new Repositories.MES.EquipmentRepository(uow);
}

public class EquipmentRepository : BaseRepository<Equipment, int>
{
        public EquipmentRepository() : base(MESDatabase.IFreeSql, null, null)
        {

        }
        public EquipmentRepository(IUnitOfWork uow) : this()
        {
            this.UnitOfWork = uow;
        }
}

**Comment by 2881099** [comment]
好的，没事。事务在最底层可以处理，只要是事务开了的查询，默认都查主库。

**Comment by 2881099** [comment]
不好意思，之前人外面，刚到家看了源码，是我搞错了。

事务的机制如您所说的规则，未开启事务的才会走备库查询。刚才做了测试也是如此。

![image](https://user-images.githubusercontent.com/16286519/68070031-4a539900-fda3-11e9-8fb5-073293cf38e4.png)

**Comment by 2881099** [comment]
有个坑需要注意，工作单元 Create 后不是马上开启事务，在使用其产生第一次 插入、更新、删除 操作才开启事务。以此操作之前做查询，不会开启事务，所以还是会去备库查询。

**Comment by yinhz** [comment]
您好，刚才看了下代码，好像我只需要把以下代码的 uow?.GetOrBeginTransaction(false) 里的false给去掉，应该就会在使用了工作单元的时候，自动会开事务了。

我想确认下

1. 修改了这里是否会产生其它不可预知的影响

2. 是否修改这里就足够了，我看了下代码应该只需要这里搞一下就够了。想确认下。 

    
    public abstract partial class DbSet<TEntity> : IDbSet where TEntity : class
    {
        internal DbContext _db { get; set; }
        internal IUnitOfWork _uow { get; set; }

        protected virtual ISelect<TEntity> OrmSelect(object dywhere)
        {
            DbContextExecCommand(); //查询前先提交，否则会出脏读
            return _db.Orm.Select<TEntity>().AsType(_entityType).WithTransaction(_uow?.GetOrBeginTransaction(false)).TrackToList(TrackToList).WhereDynamic(dywhere);
        }

**Comment by 2881099** [comment]
没有影响，这里就是给查询用的，目的是查询不开启事务。

**Comment by yinhz** [comment]
所以我只需要在这里把false给去掉，就可以实现开了uow的，都会在主库查询了。

**Comment by yinhz** [comment]
请问下我做的这个改动，您会合并到未来的版本吗。

**Comment by 2881099** [comment]
第一次查询也开启事务，说的是这个功能吗？如果做成配置开关会不会好些。因为工作单元不一定要开启事务，可能只使用了查询。

**Comment by 2881099** [comment]
第一次查询也开启事务，说的是这个功能吗？如果做成配置开关会不会好些。因为工作单元不一定要开启事务，可能只使用了查询。

**Comment by yinhz** [comment]
嗯。目前我自己项目中，已经将 DbSet 类
OrmSelect(object dywhere) 方法中 uow?.GetOrBeginTransaction(false) 里的false给去掉了。
这样只要uow不为空，就会开启事务。

 {
     DbContextExecCommand(); //查询前先提交，否则会出脏读
     return _db.Orm.Select<TEntity>().AsType(_entityType).WithTransaction(_uow?.GetOrBeginTransaction(false)).TrackToList(TrackToList).WhereDynamic(dywhere);
 }

**Comment by 2881099** [comment]
select 原先的逻辑是：

- uow 未开事务时，返回 null，不打开事务
- uow 已开事务时，返回已打开的事务如果 uow 未开启事务，查询的时候不开事务

(这个是 false 的功效)

---

insert, update, delete 没有传 false，所以逻辑是：

- uow 未开事务时，打开事务并返回
- uow 已开事务时，直接返回事务对象
