### ISSUE TITLE
在CodeFirst 中创建表的拼接是否可以使用池化的StringBuilder?

### ISSUE THREAD

**Issue by flowkingsss** [dotnetcore/FreeSql#1222]
#### Feature 特性
内存优化的可行性，参照代码在：[roslyn](https://github.com/dotnet/roslyn) Dependencies/ PooledObjects/PooledStringBuilder.cs

#### 简要描述原因
CodeFirst 中创建表的拼接方式。如MySqlCodeFirst, 第99行。

#### 使用场景
性能优化

**Comment by 2881099** [comment]
暂时不需要这种级别的性能优化，随便一条 SQL 执行就是此开销的千万倍。
