### ISSUE TITLE
能不能增加自定义分表,发现分表还是很有必要的.

### ISSUE THREAD

**Issue by yundou147** [dotnetcore/FreeSql#1223]
#### 使用场景

现在的项目都需要分表,数据都很多.现在只支持时间.希望支持一下自定义的方式

**Comment by 2881099** [comment]
自定义具体是什么样的规则，涉及到的功能：

1、查询、更新、删除时，像时间分表一样解析 where sql 得到多个分表名

2、插入时定向插入
