### ISSUE TITLE
字段转换失败

### ISSUE THREAD

**Issue by woodcoal** [dotnetcore/FreeSql#1224]
我对已经存在的数据库（mysql）编程时，如果原数据库字段为 tinyint(1)，而我模型中对应的为枚举的话，导致枚举转换失败。

如：
数据库字段 status 为 tinyint(1)

模型字段为：
```
        /// <summary>状态</summary>
        [Column(Name = "status", MapType = typeof(sbyte))]
        public StatusEnum Status { get; set; }
```

枚举数据：
```
public enum StatusEnum
{

    /// <summary>删除</summary>
    DELETE = 0,

    /// <summary>拒绝</summary>
    DISABLED = 1,

    /// <summary>待审</summary>
    WAIT = 2,

    /// <summary>通过</summary>
    PASS = 3,

    /// <summary>过期</summary>
    OVER = 4
}
```

不论我 MapType 为 byte short int long 都将在查询 ToList（ToOne）时出现错误：Requested value 'True' was not found.

我尝试找出问题原因：
第一步：我在查询时，不同表同样字段同样类型，有的报错有的不报错。检查发现如果存在关联查询，使用 Include，则不会出现错误，如果单表查询故障依旧。但是关联查询虽然不报错，转换结果是不正确，如：status=3 转换的枚举为 DISABLED(1)

第二步：根据第一步的问题，我尝试修改数据库原始字段，将 status 由 tinyint 直接修改为 int，问题解决，不论单表还是关联都正确

综合以上问题，我分析：默认应该是将 tinyint(1) 字段识别为 boolean 只允许 0 和 1，但是 mysql 中 tinyint 的范围 -128〜127 或者 0~255（无符号），所以在转换时关联查询会将原始值转换成 0或者1，而单表查询会先识别为 true / false 从而导致转换 enum 失败。

**Comment by 2881099** [comment]
tinyint(1)  在驱动层面已经被认定为 bool 映射

不是 FreeSql 报的错。

**Comment by woodcoal** [comment]
问题时为何关联多表查询却无错误提示呢

**Comment by luoyunchong** [comment]
![Screenshot_2022-08-25-11-31-02-361_com baidu searchbox](https://user-images.githubusercontent.com/18613266/186568489-7c5d1d2b-6443-4bac-8ce2-76ddabbb5981.jpg)

**Comment by woodcoal** [comment]
另外如果我将模型字段修改为：
```
        /// <summary>状态</summary>
        [Column(Name = "status", MapType = typeof(sbyte))]
        public sbyte Status { get; set; }
```

不报错，且查询的结果也是正确的。只有修改为 枚举，就错误了

**Comment by 2881099** [comment]
结果正常是因为读到的内容是 True, False 可以转化为 1, 0

你试试数据库内容是 3, 10 的时候读一下

**Comment by 2881099** [comment]
## Mysql注意事项

如果int、byte类型，指定了 DbType="tinyint(1)",请注意，tinyint(1)在ado.net中默认将此值映射为bool类型，可在链接串中指定TreatTinyAsBoolean=false,使映射 tinyint(1) 为 SByte 而非 bool。

**Comment by woodcoal** [comment]
确实是此问题，谢谢已经解决。
