### ISSUE TITLE
能否支持postgresql 的jsonb

### ISSUE THREAD

**Issue by zhujiancc** [dotnetcore/FreeSql#1225]
#### Feature 特性
支持postgresql 的jsonb 相关函数的映射

#### 简要描述原因
目前我了解的开源的pgsql 支持jsob 的orm  , 只有marten , 不过marten 整成了 文档数据库这种使用模式
能不能 fsql 支持 jsonb 的orm

#### 使用场景
业务依赖pgsql 的 jsonb ,  纯手写 sql , 效率低 ,维护性差

**Comment by 2881099** [comment]
PostgreSQL pgsql jsonb 类型 POCO 访问扩展现实方案
https://github.com/dotnetcore/FreeSql/discussions/1071

**Comment by zhujiancc** [comment]
非常感谢~~
