### ISSUE TITLE
贪婪加载 IncludeMany 支持 TakeLast 和 OrderBy

### ISSUE THREAD

**Issue by thtznet** [dotnetcore/FreeSql#1226]
#### Feature 特性
贪婪加载 IncludeMany 可以支持 TakeLast 和 OrderBy 和 OrderByDescending

#### 简要描述原因
目前只支持 Take，既然能支持 Task，可以也支持下 TakeLast么？或者在 IncludeMany 里可以支持 OrderBy 和 OrderByDescending 也可以，因为只要截取数量，一定要会需要先保证List的排序，Take的截取数据才会有业务意义，否则很多默认排序都是根据Guid乱序的。

#### 使用场景
例如，IncludeMany 贪婪加载子表时需要先根据子表的 Date 字段进行 OrderBy 或者 OrderByDescending，然后进行 Take 或者 TakeLast 取出的数据才有意义。

**Comment by 2881099** [comment]
```c#
.IncludeMany(a => a.Childs, 
   then => then.OrderBy(b => b.Time).IncludeMany(b => b.xxx))
```

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/wiki/%e8%b4%aa%e5%a9%aa%e5%8a%a0%e8%bd%bd

**Comment by thtznet** [comment]
谢谢，的确有效。
