### ISSUE TITLE
多字段分组后嵌套查询生成的SQL语句提示找不到字段

### ISSUE THREAD

**Issue by pjkpjpk** [dotnetcore/FreeSql#1237]
#### 问题描述及重现步骤：
1.按demo项目，还原测试数据库，修改连接字符串，执行查询，拷贝生成的sql语句至Navicat执行，
#### 数据库的具体版本
```
mysql 8.0

```

#### 安装的包
```
3.2.666
```
[Demo.zip](https://github.com/dotnetcore/FreeSql/files/9493187/Demo.zip)

#### .net framework/. net core？ 及具体版本
```
.net core 6.0 控制台
```

**Comment by 2881099** [comment]
这个昨天好像修了，我再验证一下

**Comment by 2881099** [comment]
确认过了，是一个 bug，已经修了

**Comment by pjkpjpk** [comment]
叶老板解决很及时，点赞👍
