### ISSUE TITLE
.net 6.0，按照上面的式例，在方法添加Transactional特性，但是没有生效，不是进入事务里，这个是什么原因引起吗？

### ISSUE THREAD

**Issue by km93522719** [dotnetcore/FreeSql#1239]
.net 6.0，按照上面的式例，在方法添加Transactional特性，但是没有生效，不是进入事务里，这个是什么原因引起吗？
Service相关代码：
```cs
[Transactional]
private async Task SaveFlowInfoAsync(FlowInfoAddInput flowInfoInput, CancellationToken cancellationToken)
{
    //using IUnitOfWork unitOfWork = _unitOfWorkManager.Begin(isolationLevel: IsolationLevel.Snapshot);
    //try
    //{
    await this._flowDetailService.AddAsync(flowInfoInput, cancellationToken); 
    //其他业务逻辑
    。。。
   
    //    unitOfWork.Commit();
    //}
    //catch (Exception e)
    //{
    //    unitOfWork.Rollback();
    //    LogUtils.LogErr(this, $"流程提交异常:{e.Message}。PARAMS:{flowInfoInput.FlowSubmitInput.ToJson()}", e);
    //    throw new CustomException(ExceptionConst.FlowSubmitFail);
    //}
}
```
programe.cs代码：
```cs
var app = builder.Build();

//使用Correlation中间件
app.UseCorrelationId();
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
//使用自定义的异常中间件
app.UseErrorHandling();
app.UseStaticFiles();
app.UseLocalLogViewer();
app.Use(async (context, next) =>
{
    TransactionalAttribute.SetServiceProvider(context.RequestServices);
    await next();
});
//使用路由中间件
app.UseRouting()
//使用终端中间件
.UseEndpoints(endpoints =>
{
    endpoints.MapGet("/", async context =>
    {
        await context.Response.WriteAsync("Hello World!");
    });
    endpoints.MapControllers();
});

app.Run();
```
_Originally posted by @km93522719 in https://github.com/dotnetcore/FreeSql/issues/289#issuecomment-1237965854_

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/wiki/DI-UnitOfWorkManager

你的代码和文档这里相差很大

**Comment by km93522719** [comment]
> https://github.com/dotnetcore/FreeSql/wiki/DI-UnitOfWorkManager
> 
> 你的代码和文档这里相差很大

我是按照上面的文档进行引用的，上面问题的代码只是其中一部分代码

**Comment by km93522719** [comment]
> > https://github.com/dotnetcore/FreeSql/wiki/DI-UnitOfWorkManager
> > 你的代码和文档这里相差很大
> 
> 我是按照上面的文档进行引用的，上面问题的代码只是其中一部分代码

直接使用using IUnitOfWork unitOfWork = _unitOfWorkManager.Begin(isolationLevel: IsolationLevel.Snapshot);是可以使用事务的，现在是想使用特性方式进行使用事务，然后我们这边也按照上面文档，如下：
第一步引入动态，添加TransactionalAttribute这个特性类
第二步是在program.cs文件（由于.net 6.0去掉了startup.cs这个文件，相关的代码都在program.cs了）
第三步是在Service类添加相关的Transactional这个特性，但是调试时没有进入这个特性类的方法里

**Comment by luoyunchong** [comment]
因为你是private方法，一般情况下，必须拥有接口，或此方法是public + virtual  具体看AOP要求

**Comment by km93522719** [comment]
> 因为你是private方法，一般情况下，必须拥有接口，或此方法是public + virtual 具体看AOP要求

这跟private方法没有关系吧，我这边试着将其改成public也不无法调用特性transalational里面的方法

**Comment by luoyunchong** [comment]
项目中有示例：https://github.com/dotnetcore/FreeSql/tree/master/Examples/aspnetcore_transaction

**Comment by km93522719** [comment]
> 项目中有示例：https://github.com/dotnetcore/FreeSql/tree/master/Examples/aspnetcore_transaction

这个例子我这边也试用过，也是不行😓

**Comment by luoyunchong** [comment]
## 其他方案
- 1.按此文档集成autofac+aop
https://freesql.net/extra/aop-freesql-autofac.html

- 2 使用IGeekFan.FreeKit.Extras 包：实现了基于特性标签的 AOP 事务
默认拦截了以Service为后缀的类。
https://igeekfan.cn/dotnetcore/freekit/Extras.html

增加了 `UnitOfWorkActionFilter`,也支持Controller级别

**Comment by km93522719** [comment]
我想问一下TransactionalAttribute这个特性是通过什么进行触发的？

**Comment by 2881099** [comment]
> 我想问一下TransactionalAttribute这个特性是通过什么进行触发的？

动态代理组件触发的，上面有资料，这是面向切面编程的一种设计。 AOP
