### ISSUE TITLE
Quartz.Net与PostgreSQL包冲突

### ISSUE THREAD

**Issue by CarlWhite2020** [dotnetcore/FreeSql#1244]
问题描述:在未安装Quartz包库的环境下，使用Freesql访问PostgreSQL一切正常。安装Quartz以后，程序访问数据库时报错：
`System.TypeInitializationException
  HResult=0x80131534
  Message=“FreeSql.PostgreSQL.PostgreSQLProvider`1”的类型初始值设定项引发异常。
  Source=ESMS.GateWay.App
  StackTrace:
   at ESMS.GateWay.App.Program.CurrentDomain_UnhandledException(Object sender, UnhandledExceptionEventArgs e) in E:\3.Document\CSharp\Project\ESMS\ESMS.GateWay\ESMS.GateWay.App\Program.cs:line 43

  此异常最初是在此调用堆栈中引发的: 

内部异常 1:
FileLoadException: 未能加载文件或程序集“System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)`

报错位置:FreesqlBuilder类第314行：
`ret = Activator.CreateInstance(type, new object[] { _masterConnectionString, _slaveConnectionString, _connectionFactory }) as IFreeSql<TMark>;`
程序环境:.net4.6.1 FrameWork +Winfrom框架
IDE:vs2022
包库版本：Quartz3.4.0 Freesql3.2.665

**Comment by 2881099** [comment]
dll依赖版本冲突，再所难免，是不是 Quartz3.4.0 非要依赖 System.ValueTuple, Version=4.0.3.0 版本。

可以升级 Quartz3.4.0
