### ISSUE TITLE
时不时出现异常信息：[【Exception】：The transaction operation cannot be performed because there are pending requests working on this transaction.]

### ISSUE THREAD

**Issue by km93522719** [dotnetcore/FreeSql#1246]
### Discussed in https://github.com/dotnetcore/FreeSql/discussions/1236

<div type='discussions-op-text'>

<sup>Originally posted by **km93522719** September  3, 2022</sup>

```c#
using IUnitOfWork unitOfWork = _unitOfWorkManager.Begin(isolationLevel: IsolationLevel.Snapshot);
try
{
   //业务相关的代码
    ...
    unitOfWork.Commit();
}
catch (Exception e)
{
    unitOfWork.Rollback();
    throw new CustomException(ExceptionConst.FlowSubmitFail);
}
```

时不时出现异常信息：[【Exception】：The transaction operation cannot be performed because there are pending requests working on this transaction.]</div>

**Comment by 2881099** [comment]
- 检查事务体内，异步方法是不是没有 await
- try 后面手工使用 unitOfWork.GetOrBeginTransaction()

**Comment by km93522719** [comment]
> 



> * 检查事务体内，异步方法是不是没有 await
--异步方法都已有await进行调用了。
> * try 后面手工使用 unitOfWork.GetOrBeginTransaction()
--我检查了日志，发现业务A已开启事务A在执行中，突然有另一业务B也要开启事务，然后就出现上面的问题，请问怎样做到事务之间不干扰，即业务A开启事务A，而业务B开启事务B，两者之间都各自通过自己的事务进行业务处理。
我看了unitOfWork.GetOrBeginTransaction()的描述，如果使用这个方法，会不会出现业务A使用的事务A，也会被业务B使用呢？
/// <summary>
/// 开启事务，或者返回已开启的事务
/// </summary>
/// <param name="isCreate">若未开启事务，则开启</param>
/// <returns></returns>
DbTransaction GetOrBeginTransaction(bool isCreate = true);

**Comment by 2881099** [comment]
事务A，事务B都是独立的

假设是 uow1、uow2

uow1.Orm.curd
uow2.Orm.curd

是两个独立的，不会乱窜。

如果用 Repository/IFreeSql 就要当心了

- 单例 IFreeSql 与 uow1 uow2 没任何关系
- Repository 同一时间，只能与一个 IUnitOfWork 关联

**Comment by km93522719** [comment]
1、program.cs是以下面的代码注入FreeSql
//注入FreeSql
builder.Services.AddSingleton(new FreeSqlBuilder()
               .UseConnectionString(DataType.SqlServer, AppConfig.AppSettings.ConnectionStr)
               .UseAutoSyncStructure(false) //自动迁移实体的结构到数据库
               .Build());
builder.Services.AddScoped<UnitOfWorkManager>();
builder.Services.AddFreeRepository();

2、Repository是继承了DefaultRepository，如下代码：

**Comment by 2881099** [comment]
是说你的事务体的用到哪些对象，按上面我说的排查一下

**Comment by km93522719** [comment]
> 单例 IFreeSql 与 uow1 uow2 没任何关系
--这一点可以理解，我们这边没有用到
> Repository 同一时间，只能与一个 IUnitOfWork 关联
--这一点不太理解，同一时间要怎样才能与一个IUnitOfWork 关联

**Comment by km93522719** [comment]
> 是说你的事务体的用到哪些对象，按上面我说的排查一下
现在就是按照你们提供的这个例子，也是继承了DefaultRepository这个类，只是没有使用AOP面向切面的方式进行事务处理
https://github.com/dotnetcore/FreeSql/tree/master/Examples/aspnetcore_transaction

以下是我们的代码：
using var unitOfWork = _unitOfWorkManager.Begin(isolationLevel: IsolationLevel.Snapshot);
try
{
	//1、生成审核详情信息
	await detailService.AddAsync(flowDetailInfo, cancellationToken);

	//2、生成审核记录信息                
	await recordService.AddAsync(recordList, cancellationToken);

	//3、提交事务
	unitOfWork.Commit();
}
catch (Exception ex)
{
	unitOfWork.Rollback();
	throw new CustomException(ExceptionConst.FlowSubmitFail);
}

**Comment by 2881099** [comment]
detailService、recordService 里面排查。

事务A，事务B都是独立的

假设是 uow1、uow2

uow1.Orm.curd
uow2.Orm.curd

是两个独立的，不会乱窜。

如果用 Repository/IFreeSql 就要当心了

单例 IFreeSql 与 uow1 uow2 没任何关系
Repository 同一时间，只能与一个 IUnitOfWork 关联

**Comment by 2881099** [comment]
建议把事务文档回下锅

**Comment by km93522719** [comment]
好的，谢谢，看来是我想多了，以为Service里Service的Repository会自动将unitOfWork传递过来作为同一事务进行

**Comment by 2881099** [comment]
想要自动，可以看下 UnitOfWorkManager 事务文档： https://github.com/dotnetcore/FreeSql/wiki/DI-UnitOfWorkManager

需要用 AOP 事务动态代理

**Comment by km93522719** [comment]
> 

不是哦，一开始我就打算使用AOP这个方式进行事务处理，但是相关的方法使用特性TransactionalAttribute就是死活运行不了事务，所以才改成

**Comment by 2881099** [comment]
不会死，只会活，看事务特点有没有生效，生效了就活。

**Comment by km93522719** [comment]
如果使用AOP这种方式的话，代码是不是这样写：
[Transactional]
private async Task SaveAsync(TbFlowDetail flowDetailInfo, List<TbFlowRecord> recordList, EAuditEquipment auditEquipment,
	CancellationToken cancellationToken = default)
{
	List<TbImMessage> imMessageInfoList = null;
	using var unitOfWork = _unitOfWorkManager.Begin(isolationLevel: IsolationLevel.Snapshot);
	try
	{
		//1、生成审核详情信息
		await _detailService.AddAsync(flowDetailInfo, cancellationToken);

		//2、生成审核记录信息                
		await _recordService.AddAsync(recordList, cancellationToken);

		//3、提交事务
		unitOfWork.Commit();
	}
	catch (Exception ex)
	{
		unitOfWork.Rollback();
		throw new CustomException(ExceptionConst.FlowSubmitFail);
	}
}

[Transactional(Propagation = Propagation.Nested)]
public async Task AddAsync(TbFlowDetail flowDetail, CancellationToken cancellationToken = default)
{
	await this._detailRepository.InsertAsync(flowDetail, cancellationToken);
}

**Comment by 2881099** [comment]
如果使用AOP这种方式的话，代码这样写：

```c#
[Transactional(IsolationLevel = IsolationLevel.Snapshot)]
private async Task SaveAsync(TbFlowDetail flowDetailInfo, List<TbFlowRecord> recordList, EAuditEquipment auditEquipment,
	CancellationToken cancellationToken = default)
{
	List<TbImMessage> imMessageInfoList = null;
		//1、生成审核详情信息
		await _detailService.AddAsync(flowDetailInfo, cancellationToken);

		//2、生成审核记录信息                
		await _recordService.AddAsync(recordList, cancellationToken);

}

[Transactional(Propagation = Propagation.Nested)]
public async Task AddAsync(TbFlowDetail flowDetail, CancellationToken cancellationToken = default)
{
	await this._detailRepository.InsertAsync(flowDetail, cancellationToken);
}
```

**Comment by km93522719** [comment]
> 如果使用AOP这种方式的话，代码这样写：
> 
> ```cs
> [Transactional(IsolationLevel = IsolationLevel.Snapshot)]
> private async Task SaveAsync(TbFlowDetail flowDetailInfo, List<TbFlowRecord> recordList, EAuditEquipment auditEquipment,
> 	CancellationToken cancellationToken = default)
> {
> 	List<TbImMessage> imMessageInfoList = null;
> 		//1、生成审核详情信息
> 		await _detailService.AddAsync(flowDetailInfo, cancellationToken);
> 
> 		//2、生成审核记录信息                
> 		await _recordService.AddAsync(recordList, cancellationToken);
> 
> }
> 
> [Transactional(Propagation = Propagation.Nested)]
> public async Task AddAsync(TbFlowDetail flowDetail, CancellationToken cancellationToken = default)
> {
> 	await this._detailRepository.InsertAsync(flowDetail, cancellationToken);
> }
> ```

好的，谢谢您耐心的回复
