### ISSUE TITLE
使用mysql同时引用mysql.data和mysqlconnector的问题

### ISSUE THREAD

**Issue by 417827155** [dotnetcore/FreeSql#1249]
历史项目里用了dapper+mysql.data的方式。mysql.data版本较低不能升级。想用freesql+mysqconnector，但是freesql里只有datatype.mysql没法区分这两个。

**Comment by 2881099** [comment]
引用 FreeSql.Provider.MySqlConnector 就会使用 mysqlconnector

**Comment by 2881099** [comment]
引用 FreeSql.Provider.MySqlConnector 的话，就移除 FreeSql.Provider.MySql

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/discussions/1207 看第9点
