### ISSUE TITLE
WithSql后的ToList是否可以支持不存在的字段映射返回Null

### ISSUE THREAD

**Issue by thtznet** [dotnetcore/FreeSql#1250]
#### Feature 特性
TableDTO 中有 a,b,c 三个字段
数据库中只有2个字段 a,b，使用脚本查询：var sql = "select a,b from table";
支持全部映射：db.Select<object>().WithSql(sql).ToList\<TableDTO\>("*");
c 默认返回Null

#### 简要描述原因
多个相似数据库99%字段相同，但每个数据库都有个别自定义扩展字段，使用一套模型去查询，查询过程可以使用每个数据库的脚本，但是使用相同的DTO输出，不存在的字段建模的时候设计为可空。
没有这个特性，必须为每个数据库建立独立的DTO模型，其中99%的字段是相同的，特别费事，还得合并。

#### 使用场景
从多个相似数据库中查询数据并合并输出，例如一个ERP系统下的多个账套实例，提供给外部BI系统时做DTO的合并。

**Comment by 2881099** [comment]
直接 fsql.Ado.Query\<DTO\>(sql)

**Comment by thtznet** [comment]
目前是使用：db.Select<object>().WithSql(sql).ToList<object>("*"); 然后再配套 Maepper 工具映射解决。
