### ISSUE TITLE
.net6下使用FreeSql.Provider.MySqlConnector发生主库不可用

### ISSUE THREAD

**Issue by wxcox** [dotnetcore/FreeSql#1255]
在.net6版本下，只要短时间内多次查询，就会导致主库不可用，time out相关错误。短时间多次查询体现为（比如1s）触发多次2-3次查询，持续5s左右必然触发。
目前测试MySql版本为mysql-5.7.26-winx64 与mysql-8.0.30-winx64 错误触发频率表现均一致。
切换为FreeSql.Provider.MySql程序运转正常

**Comment by 2881099** [comment]
和网络有关，试试把 UseConnectionString 换成：

.UseConnectionFactory(DataType.MySql, () => new MySqlConnection(connectionString))

**Comment by wxcox** [comment]
谢谢，改成UseConnectionFactory就可以了，之前是接copy指南文档中的写法，并未深究其他调用方式，希望能在文档调用此处标注下这个，不然确实容易误导。再次感谢！！！

**Comment by chad122** [comment]
> 和网络有关，试试把 UseConnectionString 换成：
> 
> .UseConnectionFactory(DataType.MySql, () => new MySqlConnection(connectionString))

请问，为什么这样修改以后就可以了？可以指教下原因嘛

**Comment by 2881099** [comment]
> > 和网络有关，试试把 UseConnectionString 换成：
> > .UseConnectionFactory(DataType.MySql, () => new MySqlConnection(connectionString))
> 
> 请问，为什么这样修改以后就可以了？可以指教下原因嘛

前面说过，和网络有关，UseConnectionString 和 UseConnectionFactory 机制不一样，前者是二次连接池封装，后者直接使用 adonet
