### ISSUE TITLE
Xamarin IOS 错误：Encoding 936 data could not be found. Make sure you have correct international codeset assembly installed and enabled.

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#126]
FreeSql 没有显式使用 Encoding.GetEncoding("gb2312") ，但有可能编译后要求这个。

解决办法：加了codepage包，勾起中文字体就ok了

![image](https://user-images.githubusercontent.com/16286519/68522509-fab32700-02e6-11ea-9c28-2d0705e914df.png)

![image](https://user-images.githubusercontent.com/16286519/68522506-f2f38280-02e6-11ea-91e4-2091ae33ea19.png)

**Comment by densen2014** [comment]
哈哈, 是我
