### ISSUE TITLE
GuidRepository删除实体后会把实体置空

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/FreeSql#1275]
#### 问题描述及重现步骤：
var rep = fsql.GetGuidRepository<SysPageFunction>();
var theone = await rep.GetAsync(Guid.Parse("08daa206-07d8-4618-2cf0-5d4ef1fa0000"));
rep.Delete(theone);
;debug

执行删除后会断点查看 theone ，发现id会变成guid.Empty。 这是否不符合使用习惯，希望id还是保持原值

#### 数据库的具体版本
```
mysql 5.6.0
```

#### 安装的包
```
<PackageReference Include="FreeSql.Provider.MySql" Version="3.2.669" />

```

#### .net framework/. net core？ 及具体版本
```
net6
```

**Comment by 2881099** [comment]
一直是这样，为了方便二次重新插入，自增也如此。

**Comment by yangbocheng** [comment]
如果谈实际开发中遇到的业务，经常遇到要在删除元素后，做些其他附加操作，传参厚实这个查到的实体。 
按照习惯，大部分人在开发时都会默认实体删除后，实体还是原样，然后传入到方法内写其他业务方法。  所以这时候的自动id为guid.empty的方便之处，就会在不知道的情况下容易造成不必要的坑点。
并且 二次重新插入的业务场景能举个例子吗，确实感觉不多

我就个人想法是 insert,update 后，实体的id都是最新的。    而delete的实体还是维持原样，是否更符合一般的使用习惯

**Comment by 2881099** [comment]
言之有理，不过目前4年没人反馈。

可以考虑 class NewBaseRepository : BaseRepository

重写 override Delete 方法

var table = Orm.CodeFirst.GetTableByEntity(EntityType)

table.Primarys 判断主键的类型 Guid

table.GetPropertyValue 获取属性的值

table.SetPropertyValue 设置属性的值

**Comment by 2881099** [comment]
回头可以考虑在 DbContextOptions 增加一个配置，控制行为。
