### ISSUE TITLE
Collection was modified after the enumerator was instantiated

### ISSUE THREAD

**Issue by mahonecode** [dotnetcore/FreeSql#1278]
#### 问题描述及重现步骤：
偶发，在调用 await InsertAsync(entity); 时捕捉到异常
异常堆栈信息如下：
{"ClassName":"System.InvalidOperationException","Message":"Collection was modified after the enumerator was instantiated.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\n   at FreeSql.DbContext.FlushCommandAsync(CancellationToken cancellationToken)\n   at FreeSql.RepositoryDbContext.SaveChangesAsync(CancellationToken cancellationToken)\n   at FreeSql.BaseRepository`1.InsertAsync(TEntity entity, CancellationToken cancellationToken)\n   at 
省略....

#### 数据库的具体版本
```
tidb
```

#### 安装的包
```
FreeSql.Provider.MySqlConnector 3.2.669
FreeSql.Repository 3.2.669
FreeSql 3.2.669
```

#### .net framework/. net core？ 及具体版本
```
.net core 3.1
```

**Comment by 2881099** [comment]
仓储对象，多线程不安全。
