### ISSUE TITLE
生产环境偶发性出现 Master Database status is unavailable

### ISSUE THREAD

**Issue by chad122** [dotnetcore/FreeSql#1283]
#### 问题描述及重现步骤：
在生产环境偶发性出现以下报错
{
    "ClassName": "System.Exception",
    "Message": "FreeSql:The FreeSql:Master Database status is unavailable and cannot be used until the background checker is restored. The Command Timeout expired before the operation completed.",
    "Data": null,
    "InnerException": {
        "ClassName": "System.Exception",
        "Message": "FreeSql:The FreeSql:Master Database status is unavailable and cannot be used until the background checker is restored. The Command Timeout expired before the operation completed.",
        "Data": null,
        "InnerException": {
            "ClassName": "MySqlConnector.MySqlException",
            "Message": "The Command Timeout expired before the operation completed.",
            "Data": null,
            "InnerException": null,
            "HelpURL": null,
            "StackTraceString": " at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 107\\n at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 34\\n at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 409\\n at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 480\\n at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 910\\n at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44\\n at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 107\\n at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 450\\n at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56\\n at MySqlConnector.MySqlCommand.ExecuteScalarAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 284\\n at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteScalarAsync(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)",
            "RemoteStackTraceString": null,
            "RemoteStackIndex": 0,
            "ExceptionMethod": null,
            "HResult": -2147467259,
            "Source": "MySqlConnector",
            "WatsonBuckets": null,
            "Number": -1,
            "SqlState": null
        },
        "HelpURL": null,
        "StackTraceString": " at FreeSql.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)\\n at FreeSql.Internal.ObjectPool.ObjectPool`1.GetAsync()\\n at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)",
        "RemoteStackTraceString": null,
        "RemoteStackIndex": 0,
        "ExceptionMethod": null,
        "HResult": -2146233088,
        "Source": "FreeSql",
        "WatsonBuckets": null
    },
    "HelpURL": null,
    "StackTraceString": " at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)\\n at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultipleAsync(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Func`3 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms, CancellationToken cancellationToken)\\n at FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivateAsync(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData, CancellationToken cancellationToken)\\n at FreeSql.Internal.CommonProvider.Select0Provider`2.ToOneAsync(CancellationToken cancellationToken)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": "FreeSql",
    "WatsonBuckets": null
}
不确定是否和 https://github.com/dotnetcore/FreeSql/issues/1255 的情况一样。

#### 数据库的具体版本
```
MySQL 8.0
```

#### 安装的包
```
FreeSql.Provider.MySqlConnector (3.2.664)
```

#### .net framework/. net core？ 及具体版本
```
.net6.0
```

**Comment by chad122** [comment]
用了IdleBus单例注入。
在压测环境使用UseConnectionString/UseConnectionFactory都没问题，无法复现该问题（可能压测的时间不够）。

**Comment by 2881099** [comment]
The Command Timeout expired before the operation completed.

你的问题根本原因是命令执行超时，和 #1255 不一样

**Comment by chad122** [comment]
> The Command Timeout expired before the operation completed.
> 
> 你的问题根本原因是命令执行超时，和 #1255 不一样

我们的查询操作及其简单，单表查询，且该表数据量只有几十条，按理不应该出现超时的
服务端线程池线程数不高，数据库连接数也还有冗余

**Comment by 2881099** [comment]
https://blog.csdn.net/bshhr/article/details/126673964
Hangfire使用MySQL出现The Command Timeout expired before the operation completed

参考解释，更多可以看下百度，这是 ado.net 层报的错误。

**Comment by chad122** [comment]
> https://blog.csdn.net/bshhr/article/details/126673964 Hangfire使用MySQL出现The Command Timeout expired before the operation completed
> 
> 参考解释，更多可以看下百度，这是 ado.net 层报的错误。

好的，谢谢
