### ISSUE TITLE
pgsql的ToSql 字段别名添加双引号引发的问题

### ISSUE THREAD

**Issue by lijianxin520** [dotnetcore/FreeSql#1286]
您好，我们目前使用freesql组件，针对pg做查询。但是发现tosql()后，表及所有字段都加上了双引号；但是这样的操作，对于我们来说，如果没有在实体对象上面进行声明表字段，实体字段就必须要与库里的表字段大小写需要一致；
然而经过我查看资料，pg查询：
1、PostgreSQL对表名、字段名都是区分大小写的。但是，PostgreSQL在SQL语句中对大小写是不敏感的，在不加双引号的情况下，创建时无论使用大写还是小写，表中都会统一转为小写显示的，因此查询时也会将语句中的字段名统一改成小写，因此，此时使用大小写查询均可。
2、用SQL语句的时候需要加双引号，或者转义符号。如果要创建名称为大写字母的字段名，需加双引号，此时表中的字段名不含双引号，但是查询时需加上双引号，执行时语句中的双引号将被抹去，因此能查出对应字段。
3、查询执行时，只会发生字段"双引号被抹去"和“大写转小写”中其中一个，优先发生"双引号被抹去"。
[https://blog.csdn.net/chenruijia170707/article/details/81195948](上述内容来源)
[https://blog.csdn.net/weixin_36267013/article/details/113472667](参考内容)
所以针对pg加双引号，能否在实体表主动声明是才加，默认与pg执行方式应该一样，全部转小写执行。

**Comment by luoyunchong** [comment]
全局 FreeSqlBuilder 设置     
PostgreSQL 建议：`.UseNameConvert(FreeSql.Internal.NameConvertType.ToLower)`
Oracle 建议：`.UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper)`
MySql 建议：`.UseNameConvert(FreeSql.Internal.NameConvertType.PascalCaseToUnderscoreWithLower)`

单独指定 [Column(Name = "xxx")]

**Comment by 2881099** [comment]
楼上正解，不关引号的是，映射可以设置大小写规则。

引号可以支持sql关键字，中文，特殊字符，更规范。
