### ISSUE TITLE
Sqlite 用Include 会导致网页都卡崩溃。。？ 调试时候无问题很快  但是如果直接执行 就会崩溃 去掉Include又没问题了 不知道什么情况导致的

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#1289]
#### 问题描述及重现步骤：

```
    .UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=db.db")
```

用Include 会导致网页都卡崩溃。。？ 调试时候无问题很快  但是如果直接执行 就会崩溃 去掉Include又没问题了 知道什么情况导致的

![image](https://user-images.githubusercontent.com/44140500/194864349-fdbb81ee-f6d7-4c0a-9404-a94c12351c17.png)
就正常的几个表然后搞几个导航
用Include 查询
发现 只要+Include 调用接口或者再Swagger上调用测试都会让网页卡崩溃
![image](https://user-images.githubusercontent.com/44140500/194864738-051cde59-a0ee-4253-97ac-d4e274508308.png)

#### 数据库的具体版本
```
3.2.680
```

#### 安装的包
```
    <PackageReference Include="FreeSql" Version="3.2.680" />
    <PackageReference Include="FreeSql.Extensions.JsonMap" Version="3.2.680" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.2.680" />
```

#### .net framework/. net core？ 及具体版本
```
.net 6
```

测试数据不太方便发出来     大佬看下能确定是什么问题不   确实需要的话我私发给你一份测试程序+数据

一开始以为是索引问题  然后给用到的列都设置上索引了也不行~~

**Comment by 2881099** [comment]
代码不要马赛克，有可能死循环了

**Comment by luoyunchong** [comment]
可能是序列化 循环依赖

**Comment by densen2014** [comment]
别用ui。纯代码试试或者url直接get你的api

**Comment by densen2014** [comment]
> 代码不要马赛克，有可能死循环了

数据太多也会UI卡死的。毕竟一般浏览器不能随便调试几十万数据显示出来

**Comment by lhtuling** [comment]
> 代码不要马赛克，有可能死循环了

明白了我检查下看看

**Comment by lhtuling** [comment]
> 代码不要马赛克，有可能死循环了

应该不是循环的问题    我这测试确定没有循环引用还是一样

**Comment by lhtuling** [comment]
我的问题。。。 确实没有循环引用
是每条信息里面导航的那条数据内容太多。。。然后每条信息都包含这条数据。。。
导致整个返回json超级大。。。。导致的ui崩溃
