### ISSUE TITLE
持续观望

### ISSUE THREAD

**Issue by nbaiguo** [dotnetcore/FreeSql#129]
这个在.net core的Startup要怎么注入初始化连接？

**Comment by 2881099** [comment]
这里有几个示例项目，可以参考下 

https://github.com/2881099/FreeSql/tree/master/Examples

![image](https://user-images.githubusercontent.com/16286519/68751456-92dd4300-063c-11ea-8a47-9dc4615d6015.png)

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/68751510-a688a980-063c-11ea-8181-35775da12e40.png)

我正在弄的一个采集项目的定义
