### ISSUE TITLE
ToListAsync报错：object reference not set to an instance of an object

### ISSUE THREAD

**Issue by PanGuoDong** [dotnetcore/FreeSql#1297]
#### 问题描述及重现步骤：
![image](https://user-images.githubusercontent.com/35752396/195494751-affae80a-6286-440d-8d81-7157b8d2902c.png)
ToList方法处理数据正常， 使用ToListAsync报下方图片错误
![image](https://user-images.githubusercontent.com/35752396/195493930-8483f135-88eb-46db-8c0e-b3b49afa734b.png)

#### 数据库的具体版本
oracle

#### 安装的包
FreeSql 3.2.680
FreeSql.Repository 3.2.680
FreeSql.Provider.Oracle 3.2.680
FreeSql.Extensions.AggregateRoot 1.0.1

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by 2881099** [comment]
v3.2.681 已解决这个问题

3.2.666-3.2.680 偶发性会有这个错误
