### ISSUE TITLE
Oracle数据库执行自定义SQL并分页

### ISSUE THREAD

**Issue by MJTucDi** [dotnetcore/FreeSql#1301]
叶老板好，

![image](https://user-images.githubusercontent.com/7964859/196077098-2fe8bc4d-6321-47fc-a7ab-b2285749056f.png)

FreeSql.Provider.Oracle  3.2.681
Net 6

**Comment by 2881099** [comment]
.ToSql("*")

原因是你用的 object

**Comment by MJTucDi** [comment]
解决，谢叶老板[抱拳]
