### ISSUE TITLE
freesql后台检查可用性，将起不到效果；

### ISSUE THREAD

**Issue by mingrenliu** [dotnetcore/FreeSql#1305]
1、基本信息：Freesql版本：3.2.666；Mysql 版本：5.7；web项目：.net6.0
2、实际场景描述：我得web采用freesql连接mysql数据库，获取数据；但现场web服务器和mysql服务器分别部署在不同的服务器上；一旦网络出现波动，freesql就会出现：主库不可用的错误，即使网络恢复正常，freesql也不会恢复。Freesql的后台定时检查程序完全没有效果；
3、原因分析：由于网络波动，freesql服务无法连接数据库，但web请求依旧会源源不断的进来，会很快挤满freesql的线程池（默认100），由于freesql后台定时检查程序，同用一个线程池，所以GetFree(false)也许永远都无法获取连接，所以freesql无法恢复；建议后台定时检查的连接采用独立的连接。
![后天检查程序](https://user-images.githubusercontent.com/55024844/197146210-82989ce4-babb-4b77-920a-72a778791d4f.png)

4、重现步骤：
1、采用locust进行压力测试，同时100个用户进行数据库插入操作：
        public void InsertOrUpdate()
        {
            var son = new Son() { Id = new Random().Next(), Value = new 	Random().NextDouble() };
            freesql.Insert<Son>(son).ExecuteAffrows();
            Task.Delay(150).Wait();
        }

from locust import HttpUser, task

class HelloWorldUser(HttpUser):
    @task
    def hello_world(self):
        self.client.get("/Parent/InsertOrUpdate")
        self.client.get("/Parent/InsertOrUpdate")

2、断开mysql数据库网路，直到freesql出现：主库不可用错误；
3、恢复mysql数据库网路的连接；

**Comment by 2881099** [comment]
试试改用 UseConnectionFactory(DataType.MySql, () => new MySqlConnection(str))

看看测试结果，这个没有背后不可用机制。

**Comment by mingrenliu** [comment]
> 试试改用 UseConnectionFactory(DataType.MySql, () => new MySqlConnection(str))
> 
> 看看测试结果，这个没有背后不可用机制。

谢谢，试了下，是有效；如果两个能结合下就最好了
