### ISSUE TITLE
ExecuteInsertedAsync在mysql下生成的语句报错

### ISSUE THREAD

**Issue by JaymzZh** [dotnetcore/FreeSql#1306]
#### 问题描述及重现步骤：
调用下面方法
`await (await TestRepository.InsertAsync()).AppendData(info).ExecuteInsertedAsync()`
生成的sql语句如下
`INSERT INTO `Test`(`Id`, `Name`, `CreateTime`) VALUES(0, 'string', '0001-01-01 00:00:00.000') RETURNING `Id` as `Id`, `Name` as `Name`, `CreateTime` as `CreateTime``

#### 数据库的具体版本
```
mysql 8.0.17.0
```

#### 安装的包
```
FreeSql.Repository 3.2.682
```

#### .net framework/. net core？ 及具体版本
```
net core 6.0
```

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/blob/674d7421b3d5c4ba7b74f306dec55f866559e4d6/FreeSql/Interface/Curd/IInsert.cs#L154

```
        /// <summary>
        /// 执行SQL语句，返回插入后的记录<para></para>
        /// 注意：此方法只有 Postgresql/SqlServer 有效果
        /// </summary>
        /// <returns></returns>
        List<T1> ExecuteInserted();
```

实际 Mariadb 也支持，Mariadb是MySql原作者维护的分支，Mysql8并不支持此功能

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/issues/160
