### ISSUE TITLE
按月自动分表，跨月分页查询时，每个月都分了页尺寸的数据

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1307]
.net 6.0,pgsql,freesql版本3.2.682，
按月自动分表，查询时每页10条数据，返回的结构是每是月10条数据了，而不是总的10条数据。
如查询9月1日至10月22日的数据，那出来的是9月10条，10月10条数据，而不是10条数据。
生成的语句如下，应当是先UNION ALL 再分页，而不是先分页再UNION ALL.
SELECT  * from (SELECT a."id" as1, a."category" as2, a."real_name" as3, a."api_title" as4, a."api_path" as5, a."api_method" as6, a."ip" as7, a."browser" as8, a."elapsed_milliseconds" as9, a."status" as10, a."message" as11, a."created_by" as12, a."created_by_name" as13, a."created_time" as14
FROM "sys_oper_log_202210" a
WHERE (a."created_time" >= '2022-09-01 00:00:00.000000') AND (a."created_time" < '2022-10-22 00:00:00.000000') AND (a."created_by" = 760203095982080)
ORDER BY a."id" DESC
limit 10) ftb

UNION ALL

SELECT  * from (SELECT a."id" as1, a."category" as2, a."real_name" as3, a."api_title" as4, a."api_path" as5, a."api_method" as6, a."ip" as7, a."browser" as8, a."elapsed_milliseconds" as9, a."status" as10, a."message" as11, a."created_by" as12, a."created_by_name" as13, a."created_time" as14
FROM "sys_oper_log_202209" a
WHERE (a."created_time" >= '2022-09-01 00:00:00.000000') AND (a."created_time" < '2022-10-22 00:00:00.000000') AND (a."created_by" = 760203095982080)
ORDER BY a."id" DESC
limit 10) ftb

**Comment by 2881099** [comment]
自动分表的分页，是难题，要自己解决
