### ISSUE TITLE
高并发下异常问题

### ISSUE THREAD

**Issue by yinhz** [dotnetcore/FreeSql#131]
您好，我们遇到以下情况，还请您帮忙看下。
我已经将FreeSql代码加到自己的解决方案中。
以下单元测试方法，在并发量低的时候，不会抛出以下异常。
但是并发量较高的时候，会出现以下异常，并且主程序无法捕获。
看了下是在 析构函数中，有 trans.RollBak()，这时候 trans 是 Null，虽然前面有判断trans是否为null，就导致了异常的出现。
由于无法捕获，会导致程序崩溃。。

![1](https://user-images.githubusercontent.com/11548282/68863930-3efd5780-072b-11ea-995b-e0fac7bd8119.png)
![2](https://user-images.githubusercontent.com/11548282/68863931-3efd5780-072b-11ea-9d25-958e96f76e68.png)
![3](https://user-images.githubusercontent.com/11548282/68863951-458bcf00-072b-11ea-9f00-f4e647dd0cef.png)

**Comment by 2881099** [comment]
第二张图，堆栈信息，显示的是 
![image](https://user-images.githubusercontent.com/16286519/68917868-00a57e00-07a7-11ea-8fac-ec8a6b744c95.png)

**Comment by 2881099** [comment]
把相同的测试代码，换成 sqlserver 或 mysql 试试，看看是不是驱动层报的

**Comment by 2881099** [comment]
这个析构函数，我用 try 包装一下吧

**Comment by 2881099** [comment]
看测试代码 uow 用 using 了，会自动调用 Dispose 方法

为什么析构函数执行的时候， tran != null 条件还成立呢？

**Comment by yinhz** [comment]
嗯，我们调试的时候也觉得很奇怪。
首先我们没有在程序中使用异步，都是同步的程序。
而且只有当sql执行效率较低(我故意去掉了数据库的索引），并发较高的时候才会出现。

**Comment by 2881099** [comment]
我提交下代码，方便配合引用代码测试下吗

**Comment by yinhz** [comment]
额，您的代码我在本地有修改过。
1个是签名，二个是UOW不为Null的时候，即使只查询，也会开启事务。

我会把最新的UOW的代码覆盖到我本地这里，做下测试。

**Comment by yinhz** [comment]
是只修改了 UnitOfWork 这个类的代码吗

**Comment by 2881099** [comment]
if (_isdisposed) return;
_isdisposed = true;

我把这些代码，全改成了
if (Interlocked.Increment(ref _disposeCounter) != 1) return;

**Comment by yinhz** [comment]
![1](https://user-images.githubusercontent.com/11548282/68920725-128c1e80-07b1-11ea-9a28-8eb04e15059d.png)

**Comment by 2881099** [comment]
所以，这个 oracle 那个驱动内部报的 null 错误。

> 第二张图，堆栈信息，显示的是
> ![image](https://user-images.githubusercontent.com/16286519/68917868-00a57e00-07a7-11ea-8fac-ec8a6b744c95.png)

**Comment by 2881099** [comment]
把完整的堆栈信息发一下，StackTrace

**Comment by yinhz** [comment]
![1](https://user-images.githubusercontent.com/11548282/68921285-33ee0a00-07b3-11ea-8638-dbde75de89b0.png)

**Comment by 2881099** [comment]
你的代码行，和我这边怎么不一样

**Comment by 2881099** [comment]
兄弟把搜索 ctrl + f， ~ 把项目内所有析构方法去掉试下

**Comment by 2881099** [comment]
新代码，您试下。。DbContext 类的析构可能是有这个问题。。
