### ISSUE TITLE
时间类型对比报

### ISSUE THREAD

**Issue by youlo0018a** [dotnetcore/FreeSql#1314]
The conversion of a varchar data type to a datetime data type resulted in an out-of-range value

**Comment by luoyunchong** [comment]
以下为必读项，不仔细阅读会导致你的 Issue 被关闭

1. 该分类下只能提交 Bug，如果要询问使用方法等，请前往讨论区：https://github.com/dotnetcore/FreeSql/discussions
2. FreeSql写了许多文档，在提问题前，麻烦先查看[常见问题](http://freesql.net/reference/faq.html) 
3. 不完整的信息将不会得到任何回复！发布问题后，请保持对 issue 的关注，有时会有需要进一步沟通的信息，很长时间内没有得到答复的 issue 将被关闭。
4. 提供可重现的代码，至少应描述以下信息 

#### 问题描述及重现步骤：


#### 数据库的具体版本
```

```

#### 安装的包
```

```

#### .net framework/. net core？ 及具体版本
```

```

**Comment by 2881099** [comment]
.UseMonitorCommand(cmd => Console.WriteLine(cmd.CommandText))

把 SQL 执行的内容打印出来，看看是执行哪条 SQL 报错的，应该是数据库表类型问题。
