### ISSUE TITLE
Table属性无效

### ISSUE THREAD

**Issue by playfund** [dotnetcore/FreeSql#1316]
![image](https://user-images.githubusercontent.com/28752075/199172489-1e6fe375-0e69-4d95-9ce6-ffb2b121402f.png)
![image](https://user-images.githubusercontent.com/28752075/199172527-b53f552a-5d21-456a-9a20-97295ad2f290.png)

为什么我指定了表名，结果还是生成了类名？

**Comment by playfund** [comment]
![HZD{{8 FMMR2Q1EN2VZ~VP1](https://user-images.githubusercontent.com/28752075/199183302-704f8e19-8815-4dfa-b8d4-817f982482b9.png)

**Comment by 2881099** [comment]
```
select Name from sqlite_master
```

 这个语句也不是 FreeSql 生成的

```
CREATE TABLE "TradeDays"(
"date" datetime NOT NULL  ,
"is_trade" bit NOT NULL      )
```

像这个没格式规则的 SQL 也不是 FreeSql 生成的

FreeSql 生成的 SQL 内容，有严格的缩进，一个空格不都会多

```sql
CREATE TABLE IF NOT EXISTS xxx (
...
```
FreeSql 生成的创建表内容，是以这个开头的
