### ISSUE TITLE
类型映射，类中为object 映射到数据库为sting  读取数据Tolist市报错

### ISSUE THREAD

**Issue by liuyanchen1994** [dotnetcore/FreeSql#1317]
#### 问题描述及重现步骤：
![image](https://user-images.githubusercontent.com/19524048/199631808-a575e8f9-0fa3-45d9-b7d0-0d4cc0ff8003.png)
![image](https://user-images.githubusercontent.com/19524048/199631831-362d87ca-e67a-4cb2-8689-6ccdee9006cf.png)
![image](https://user-images.githubusercontent.com/19524048/199631853-606fb8a3-8bc6-4744-9e03-0015e57e0f1f.png)

#### 数据库的具体版本
人大金仓V8

#### 安装的包
3.2682

#### .net framework/. net core？ 及具体版本
.net core 3.1

**Comment by 2881099** [comment]
群里已回复，实体类属性用 string
