### ISSUE TITLE
MySql Ado中enum类型不支持转为int 查询

### ISSUE THREAD

**Issue by ldaxian0229** [dotnetcore/FreeSql#1324]
#### Feature 特性
MySql Ado中enum类型不支持转为int 查询，希望能支持通过配置实现enum参数化时，以int类型查询

#### 简要描述原因
MySql Ado中enum类型不支持转为int 查询

**Comment by 2881099** [comment]
select enum_field+0 from table

这样就返回 int

**Comment by ldaxian0229** [comment]
> select enum_field+0 from table
> 
> 这样就返回 int

select * from table where enum=@enum 的情况

**Comment by ldaxian0229** [comment]
目前采用这种形式，觉得不是很友好
` 
fsql.Aop.CommandBefore += Aop_CommandBefore;
private static void Aop_CommandBefore(object sender, CommandBeforeEventArgs e)
        {
            if (e.Command.Parameters?.Count > 0)
            {
                foreach (var parameter in e.Command.Parameters)
                {
                    if (parameter is MySqlParameter mySqlParameter)
                    {
                        if (mySqlParameter.MySqlDbType == MySqlDbType.Enum)
                        {
                            mySqlParameter.MySqlDbType = MySqlDbType.Int32;
                        }
                    }
                }
            }
        }
`
