### ISSUE TITLE
支持 TimescaleDB 时序数据库

### ISSUE THREAD

**Issue by zfchai** [dotnetcore/FreeSql#1325]
####  FreeSql 支持 TimescaleDB 

- FreeSql.Provider.TimescaleDB

#### 原因

TimescaleDB 在许多方面的行为都类似于标准 PostgreSQL 数据库：

1. 与 PostgreSQL 服务器上的其他 TimescaleDB 和 PostgreSQL 数据库共存。
2. 使用 SQL 作为其接口语言。包含标准数据库对象，例如表，索引和触发器。
3. 使用通用的 PostgreSQL 连接器连接第三方工具。

#### 使用场景

TimescaleDB 提供的超越 PostgreSQL 的优势主要与处理【时序数据】有关。 
https://docs.timescale.com/timescaledb/latest/

**Comment by 2881099** [comment]
FreeSql.Provider.PostgreSQL 可以访问 TimescaleDB
