### ISSUE TITLE
Postgresql Error  FreeSql.Tools Error

### ISSUE THREAD

**Issue by gsgoodluck** [dotnetcore/FreeSql#133]
使用FreeSql.Tools-1.0.0  连接Postgresql 报错

   42703: 字段 e.adsrc 不存在

**Comment by 2881099** [comment]
0.10.13 处理过 https://github.com/2881099/FreeSql/commit/615023f012a8d14db0beba1363de09fdb745dc35
FreeSql.Tools引用包需要更新重新编译
