### ISSUE TITLE
zhontai.admin 达梦迁移表出现 command time out

### ISSUE THREAD

**Issue by Butt3rcup** [dotnetcore/FreeSql#1334]
#### 问题描述及重现步骤：
这边是采用基于zhontai.admin框架使用开发
在zhontai迁移数据库的时候 配置如下
![image](https://user-images.githubusercontent.com/28386305/201625610-58750f55-0195-4565-a9d6-4a015a78bc3b.png)
出现了
![image](https://user-images.githubusercontent.com/28386305/201625761-e4b9bec2-988f-417d-87f0-5a08177dcf26.png)
这应该是freesql codefirst生成的临时表 然后去查询对应数据库的表是否存在 然后进行更新或者修改操作(字段上)
报错错误为 command time out
使用框架的迁移 无增加表的情况下 是没问题的 目前看
是否是框架生成表太多造成的执行超时问题？
或者是达梦并发试用版有限制?
框架生成表的操作 事务的生命周期问题?
这里看到操作迁移的时候会去生成一个 FTmp_xxx 表 然后对比后无问题 就把这个临时表删除掉或者更新掉？然后这个表就删除 迁移成功！  出现错误时 发现数据库生成的临时表还在 已存在  则爆出一下错位信息

   在 Dm.DmError.ThrowDmException(Int32 code)
   在 Dm.DmCsi.CommunicateTryInner(DmCommTcpip commTcpip, DmMsg SendMsg, DmMsg RecvMsg, Int32 commandTimeOut)
   在 Dm.DmCsi.Communicate(DmMsg SendMsg, DmMsg RecvMsg, Boolean& standby, Int32 commandTimeOut, Int32 PrimaryStmtid)
   在 Dm.DmCsi.PrepareSql(DmMsg SendMsg, DmMsg RecvMsg, DmStatement stmt, String sql, Boolean direct, Int32 checkFlag)
   在 Dm.DmStatement.ExecuteUpdate(String sql)
   在 Dm.DmCommand.ExecuteNonQuery()
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)

   在 IdleBus`2.ItemInfo.GetOrCreate()
   在 IdleBus`2.Get(TKey key)
   在 FreeSql.FreeSqlCloud`1.GetBySnapshot(TDBKey dbkey)
   在 FreeSql.FreeSqlCloundSnapshot`1.get_CodeFirst()
   在 ZhonTai.Admin.Core.Db.DbHelper.RegisterDb(FreeSqlCloud freeSqlCloud, IUser user, DbConfig dbConfig, AppConfig appConfig, HostAppOptions hostAppOptions)
   在 ZhonTai.Admin.Core.Db.DBServiceCollectionExtensions.AddDb(IServiceCollection services, IHostEnvironment env, HostAppOptions hostAppOptions)
   在 ZhonTai.Admin.Core.HostApp.ConfigureServices(IServiceCollection services, IWebHostEnvironment env, IConfiguration configuration, ConfigHelper configHelper, AppConfig appConfig)
   在 ZhonTai.Admin.Core.HostApp.Run(String[] args)
   在 Program.<Main>$(String[] args) 在 Admin\src\hosts\WJ.Admin.Host\Program.cs 中: 第 12 行

数据库的具体版本
达梦8 linux 试用版本

 
安装的包
3.2.682 达梦驱动

.net framework/. net core？ 及具体版本
.net core 6.0
zhontai.admin 2.3.2

**Comment by 2881099** [comment]
FTmp_xxx 这个表是对比表结构的操作未完成，留下的残余表，可以手工移除。

建议表太多的情况，循环迁移避免超时，如下：

foreach (var entityType in types)
    fsql.CodeFirst.SyncStructure(entityType);


还有一个问题提醒一下，dm 客户端管理工具查询表的结果，会锁表，试试关掉工具再运行代码。

**Comment by Butt3rcup** [comment]
感谢大佬解答
