### ISSUE TITLE
Aop.AuditDataReader对匿名对象无效

### ISSUE THREAD

**Issue by gudufy** [dotnetcore/FreeSql#1339]
#### 问题描述及重现步骤：

我需要所有avatar返回的时候带上图片保存的服务器域名
`fsql.Aop.AuditDataReader += (_, e) =>
            {
                if (e.DataReader.GetName(e.Index) == "avatar")
                    e.Value = App.HttpContext.GetDomain() + e.Value;
            };`

我直接ToOne()是正常的，如果我只返回指定列，如：ToOne(x=>new { x.id, x.avatar })，这时取到的avatar不会被改变。

#### 数据库的具体版本
```
mysql 8

```

#### 安装的包
```
v3.2.682

```

#### .net framework/. net core？ 及具体版本
```
.net6

```

**Comment by 2881099** [comment]
有一些场景 .GetName 拿到的值不是 "avatar" 了，比如 as1 as2 ...

**Comment by 2881099** [comment]
感觉这个倒不如在数据查询之后想办法解决

**Comment by gudufy** [comment]
> 

确实是as1,as2，但我想统一处理，有办法吗？解决不了那就只能另外处理了

**Comment by hd2y** [comment]
@gudufy 虽然可以参考扩展 JsonMap 的代码，但是不太建议这么做，用 AutoMapper 或者 Mapster 做处理感觉会更适合。

**Comment by gudufy** [comment]
> @gudufy 虽然可以参考扩展 JsonMap 的代码，但是不太建议这么做，用 AutoMapper 或者 Mapster 做处理感觉会更适合。

懒得写DTO，呵呵，现在放前端去处理了
