### ISSUE TITLE
能否考虑扩展模块支持BSON？

### ISSUE THREAD

**Issue by a850651477** [dotnetcore/FreeSql#1341]
#### Feature 特性
能否考虑扩展模块支持BSON？

#### 简要描述原因
JSON转成的String占用空间比较大。

#### 使用场景
数据量大，需要高速场景。

**Comment by 2881099** [comment]
可以参考这个体交 https://github.com/dotnetcore/FreeSql/commit/1dae5b9573a855b5b6ed0f5d49d2f15225ca4741

**Comment by a850651477** [comment]
Nice
