### ISSUE TITLE
插入时增加附加列插入

### ISSUE THREAD

**Issue by cn0o0king** [dotnetcore/FreeSql#1342]
#### Feature 特性
`fsql.Insert(items).InsertColumns(new { Id = 1,OrgId = "1001" }).ExecuteAffrows();`

**其中假设item为**
```
public class item
{
   public name { get; set; }
   public age { get; set; }
｝
```
**那么最终形成的SQL语句为：**
`insert into items (id,orgid,name,age) values (1,'1001','name1',age1),(1,'1001','name2',age2)`

#### 简要描述原因
比如有一个主从表，从表中一批每行都有主表的id，这样就可以附加进去，我现在的解决办法是先把实体加id字段，然后再遍历赋值，感觉这样麻烦而且效率不高，而且如果多个地方要调用写入，有没有赋值不好统一

#### 使用场景
实体中没有的属性，需要写入到数据库的情况，一般主要用于明细表写入，比如明细表中含有汇总表中的id，或许会说明细表直接加上对应的列，但是如果是自己设计的api接口没有问题，有时候是对接别人的接口，比如获取百度的一个接口，汇总返回了id，但是明细没有返回id，这样就要手动拼装赋值，比较麻烦

**Comment by 2881099** [comment]
我觉得可以考虑定义一个完整实体类解决问题。

实在不行，也可以用 fsql.InsertDict(字典).ExecuteAffrows(); 来解决。

**Comment by 2881099** [comment]
### 字典插入

```
var dic = new Dictionary<string, object>();
dic.Add("id", 1);
dic.Add("name", "xxxx");

fsql.InsertDict(dic).AsTable("table1").ExecuteAffrows();
```

**Comment by cn0o0king** [comment]
@2881099 这样就更麻烦了，这样只会写入dic里面的，我类里面本身有的字段又没有写入

**Comment by hd2y** [comment]
实体设计可能有些问题，首先主键不需要赋值，外键可以参考仓储级联保存，也不需要遍历赋值。
