### ISSUE TITLE
联网状态下，使用FreeSql.Provider.MsAccess读取加密的*.accdb格式数据库文件耗时极长。

### ISSUE THREAD

**Issue by wxysy** [dotnetcore/FreeSql#1344]
#### 问题描述及重现步骤：
在联网状态下，使用FreeSql.Provider.MsAccess读取加密的*.accdb格式数据库文件耗时极长。
但是在断网的情况下，就不会出现这种情况。
具体耗时如下图所示：
1、联网情况下耗时
![联网状态](https://user-images.githubusercontent.com/41404936/202880408-7a9a3ba6-8a75-46c3-bbe0-687ce7f13e75.png)
2、断网情况下耗时
![断网状态](https://user-images.githubusercontent.com/41404936/202880415-f10184fc-f367-407e-ab9e-0ed74203d92f.png)

#### 数据库的具体版本
MS Access 2019 X64

#### 安装的包
Microsoft Access Database Engine 2016 X64
FreeSql.Provider.MsAccess
FreeSql.Extensions.Linq

#### .net framework/. net core？ 及具体版本
.Net 6 框架
WPF 项目

#### 主要代码（C#）
`IFreeSql fsql;
            IFreeSql fsqlpwd;
            Stopwatch stopwatch = new();//using System.Diagnostics;

            //----[基础]连接字符串：Access文件未加密----
            stopwatch.Start();
            string connectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDB_V1.94.accdb";
            fsql = new FreeSql.FreeSqlBuilder()
               .UseConnectionString(FreeSql.DataType.MsAccess, connectionString)
               .Build();//请务必定义成 Singleton 单例模式
            stopwatch.Stop();
            var timeused = stopwatch.ElapsedMilliseconds;
            string mes = $"连接Access数据库未加密accdb文件MyAccessDB_V1.94.accdb已完成。用时：{timeused}ms";
            progress?.Report($"{mes}");//IProgress<string> progress;

            //----[基础]连接字符串：Access文件已加密（【联网状态下】带密码的连接比没有密码的慢很多）----
            stopwatch.Restart();
            string connectionStringpwd = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDBpwd_V1.94.accdb;Jet OLEDB:Database Password=xy12341234";
            fsqlpwd = new FreeSql.FreeSqlBuilder()
               .UseConnectionString(FreeSql.DataType.MsAccess, connectionStringpwd)
               .Build();//请务必定义成 Singleton 单例模式
            stopwatch.Stop();
            timeused = stopwatch.ElapsedMilliseconds;
            mes = $"连接Access数据库已加密abbdc文件MyAccessDBpwd_V1.94.accd已完成。用时：{timeused}ms";
            progress?.Report($"{mes}");

            //----【实际】连接字符串并查询数据----
            try
            {
                IFreeSql fsqlReal;
                Stopwatch stopwatchReal = new();

                //----[实际]连接字符串：Access文件已加密（【联网状态下】带密码的连接比没有密码的慢很多）----
                stopwatchReal.Start();
                string dir = @"D:\MyProgramTesting";//更常用的是：System.IO.Directory.GetCurrentDirectory();//字符串末尾没有“\”。
                string filename = @"MyWorkAccessDBpwd_V1.94.accdb";
                string sourcePath = System.IO.Path.Combine(dir, filename);
                string accessPassword = "xy12341234";
                string connectionStringReal = $@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source={sourcePath};Jet OLEDB:Database Password={accessPassword}";//加密的accdb文件用
                //string connectionStringReal = $@"Provider=Microsoft.ACE.OLEDB.12.0;Data Source={sourcePath}";//未加密accdb文件用
                fsqlReal = new FreeSql.FreeSqlBuilder()
                   .UseConnectionString(FreeSql.DataType.MsAccess, connectionStringReal)
                   .Build();//请务必定义成 Singleton 单例模式
                stopwatchReal.Stop();
                long timeConsumption = stopwatchReal.ElapsedMilliseconds;
                string mesRead = $"连接Access数据库已加密abbdc文件{filename}已完成。用时：{timeConsumption}ms";
                progress?.Report($"{mesRead}");

                //----读取查询数据----
                var res_Select = fsqlReal.Select<T0001_版本信息表>().Where(p => true).ToList();
                //var res = fsql.Select<T0101_公司情况表>().Where(p => p.统一社会信用代码 == "91420300MA49E8PA1F").First();
                foreach (var item in res_Select)
                {
                    progress?.Report($"{item.版本号}--{item.版本说明}");
                }
            }
            catch (Exception ex)
            {
                mes = $"未能从accdb文件获取数据。原因：\n{ex.Message}";
                progress?.Report($"{mes}");
            }`

**Comment by 2881099** [comment]
直接使用如下代码测试呢？

```c#
using (var conn = new OledbConnection(connectionString))
{
    conn.Open();
    var cmd = conn.CreateCommand();
    cmd.CommandText = "select * from T0001_版本信息表";
    using (var dr = cmd.ExecuteDataReader())
    {
        while (dr.Read())
        {
        }
    }
    conn.Close();
}
```

**Comment by wxysy** [comment]
> 直接使用如下代码测试呢？
> 
> ```cs
> using (var conn = new OledbConnection(connectionString))
> {
>     conn.Open();
>     var cmd = conn.CreateCommand();
>     cmd.CommandText = "select * from T0001_版本信息表";
>     using (var dr = cmd.ExecuteDataReader())
>     {
>         while (dr.Read())
>         {
>         }
>     }
>     conn.Close();
> }
> ```

抱歉，我刚学习数据库方面知识，您写的这个用法我暂时不会使用。

**Comment by wxysy** [comment]
> 直接使用如下代码测试呢？
> 
> ```cs
> using (var conn = new OledbConnection(connectionString))
> {
>     conn.Open();
>     var cmd = conn.CreateCommand();
>     cmd.CommandText = "select * from T0001_版本信息表";
>     using (var dr = cmd.ExecuteDataReader())
>     {
>         while (dr.Read())
>         {
>         }
>     }
>     conn.Close();
> }
> ```

我尝试摸索了一下，**直接使用给出的方法并不会出现耗时极长的情况**。
反馈结果如下：
![联网状态下直接使用oledbconnection](https://user-images.githubusercontent.com/41404936/202955714-0faac010-b4ce-40a6-8c9d-bf58011e27ac.png)

主要代码如下：
```csharp
private void Btn_Action_Click(object sender, RoutedEventArgs e)
        {
            string connectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDB_V1.94.accdb";
            Test2(connectionString);
            string connectionStringpwd = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDBpwd_V1.94.accdb;Jet OLEDB:Database Password=xy12341234";
            Test2(connectionStringpwd);
        }
        void Test2(string connectionString)
        {
            Stopwatch stopwatch = new();
            stopwatch.Start();           
            using (var conn = new OleDbConnection(connectionString))
            {
                conn.Open();
                var cmd = conn.CreateCommand();
                cmd.CommandText = "select * from T0001_版本信息表";
                using (var dr = cmd.ExecuteReader())
                {
                    while (dr.Read())
                    {
                    }
                }
                conn.Close();
            }
            stopwatch.Stop();
            var timeused = stopwatch.ElapsedMilliseconds;
            string mes = $"连接Access数据库accdb文件已完成。用时：{timeused}ms";
            progress?.Report($"{mes}");//IProgress<string> progress;
        }```

**Comment by 2881099** [comment]
测试一，利用上面的代码同时 dr.GetValue 把所有字段都读取一下

> 先排除 oledb 驱动问题

测试二，同时把 UseConnectionString 换成 UseConnectionFactory(xx.Access, () => new OledbConnection(...)) 

> 如果排除 oledb 问题，改这种肯定没问题

测试三，把 UseConnectionString 连接串加个 min pool size=1 的模式也试试

> 如果不改，用这种也能解决

**Comment by wxysy** [comment]
> 测试一，利用上面的代码同时 dr.GetValue 把所有字段都读取一下
> 
> > 先排除 oledb 驱动问题
> 



测试一：我在联网状态下，按你要求，将主要代码修改后，运行结果如下。
**依然没有出现耗时极长的情况。**
测试二、测试三：你说的 UseConnectionString 是指改哪里，请明确。

![1联网状态下使用GetValue情况](https://user-images.githubusercontent.com/41404936/203264438-fb36d1cd-bb10-490d-ae30-1edbae58adea.png)

主要代码：
```csharp
void Test2(string connectionString)
        {
            Stopwatch stopwatch = new();
            stopwatch.Start();           
            using (var conn = new OleDbConnection(connectionString))
            {
                conn.Open();
                var cmd = conn.CreateCommand();
                cmd.CommandText = "select * from T0001_版本信息表";
                using (OleDbDataReader dr = cmd.ExecuteReader())
                {
                    while (dr.Read())
                    {
                        var p1 = dr.GetValue(0).ToString();
                        var p2 = dr.GetValue(1).ToString();
                        progress?.Report($"{p1}--{p2}");
                    }
                }
                conn.Close();
            }
            stopwatch.Stop();
            var timeused = stopwatch.ElapsedMilliseconds;
            string mes = $"连接Access数据库accdb文件已完成。用时：{timeused}ms";
            progress?.Report($"{mes}");//IProgress<string> progress;
        }
```

**Comment by 2881099** [comment]
测试二，三都是针对一下的定义：


fsql = new FreeSql.FreeSqlBuilder()
           .UseConnectionString(FreeSql.DataType.MsAccess, connectionString)
           .Build();

**Comment by wxysy** [comment]
> 测试二，三都是针对一下的定义：
> 
> fsql = new FreeSql.FreeSqlBuilder() .UseConnectionString(FreeSql.DataType.MsAccess, connectionString) .Build();

测试二：出现了新问题
这回不会耗时极长了，但是仿佛是瞬间读取了一般。
测试三还是不知道怎么加，可否具体指出。

结果如下图：
![3、使用Factory出现新问题](https://user-images.githubusercontent.com/41404936/203278954-bbd7613e-c2e8-4476-b446-e2c733d0b622.png)

主要代码如下：
```csharp
void Test3()
        {
            IFreeSql fsql;
            IFreeSql fsqlpwd;
            Stopwatch stopwatch = new();//using System.Diagnostics;

            //----[基础]连接字符串：Access文件未加密----
            stopwatch.Start();
            string connectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDB_V1.94.accdb";
            fsql = new FreeSql.FreeSqlBuilder()
               .UseConnectionString(FreeSql.DataType.MsAccess, connectionString)
               .Build();//请务必定义成 Singleton 单例模式
            stopwatch.Stop();
            var timeused = stopwatch.ElapsedMilliseconds;
            string mes = $"连接Access数据库未加密accdb文件MyAccessDB_V1.94.accdb已完成。用时：{timeused}ms";
            progress?.Report($"{mes}");//IProgress<string> progress;

            //----[基础]连接字符串：Access文件已加密（【联网状态下】带密码的连接比没有密码的慢很多）----
            Stopwatch stopwatch2 = new();
            stopwatch2.Start();
            string connectionStringpwd = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDBpwd_V1.94.accdb;Jet OLEDB:Database Password=xy12341234";
            fsqlpwd = new FreeSql.FreeSqlBuilder()
               //.UseConnectionString(FreeSql.DataType.MsAccess, connectionStringpwd)
               .UseConnectionFactory(FreeSql.DataType.MsAccess, () => new OleDbConnection(connectionStringpwd))
               .Build();//请务必定义成 Singleton 单例模式
            stopwatch2.Stop();
            var timeused2 = stopwatch2.ElapsedMilliseconds;
            mes = $"连接Access数据库已加密abbdb文件MyAccessDBpwd_V1.94.accdb已完成。用时：{timeused2}ms";
            progress?.Report($"{mes}");

            //----读取查询数据----
            var res_Select = fsqlpwd.Select<T0001_版本信息表>().Where(p => true).ToList();
            //var res = fsql.Select<T0101_公司情况表>().Where(p => p.统一社会信用代码 == "91420300MA49E8PA1F").First();
            foreach (var item in res_Select)
            {
                progress?.Report($"{item.版本号}--{item.版本说明}");
            }


        }
```

**Comment by 2881099** [comment]
那你就用 UsrConnectionFactory

**Comment by wxysy** [comment]
> 那你就用 UsrConnectionFactory

好的，这也算是种解决方法吧。
另外，**我用UseConnectionFactory测试了一下读取未加密文件，速度极快，只有先前UseConnectionString方法的1/5左右的耗时。**


![5、使用UseConnectionFactory读取未加密accdb文件速度极快](https://user-images.githubusercontent.com/41404936/203457739-cab349ec-41ff-4a42-b817-bac4a11fd54d.png)

**Comment by 2881099** [comment]
UseConnectionString会预热，UseConnectionFactory不会预热

预热肯定会初始化慢一点点，所以我让你前面设置 min pool size=1 也测试一下（测试三）

**Comment by wxysy** [comment]
> 预热肯定会初始化慢一点点，所以我让你前面设置 min pool size=1 也测试一下（测试三）

能否具体说一下，这个“min pool size=1 ”到底放在哪里？这个要求比较深入和详细，我暂时理解不明白。

**Comment by 2881099** [comment]
连接字符串上面。

**Comment by 2881099** [comment]
3.2.684-preview20221124 已优化 MsAccess 默认只预热一个 OledbConnection。

**Comment by wxysy** [comment]
> 连接字符串上面。

我尝试写了如下连接字符串：
```csharp
string connectionStringPwd = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\MyProgramTesting\MyAccessDBpwd_V1.94.accdb;Jet OLEDB:Database Password=xy12341234;Min Pool Size=1";
```
并且使用UseConnectionString方法，实际运行结果如下：
![使用min pool size](https://user-images.githubusercontent.com/41404936/203672459-44e98d7f-1b64-4454-b3ff-f612cc25c211.png)


**确实没有出现耗时极长的问题了。**

主要代码：
```csharp
void Method_2(string connectionString, IProgress<string>? progress)
        {
            Stopwatch stopwatch = new();//using System.Diagnostics;
            stopwatch.Start();

            //----连接数据库数据----
            IFreeSql fsql;
            fsql = new FreeSql.FreeSqlBuilder()
               .UseConnectionString(FreeSql.DataType.MsAccess, connectionString)//不要用这个方法
               //.UseConnectionFactory(FreeSql.DataType.MsAccess, () => new OleDbConnection(connectionString))//UseConnectionString替代方法
               .Build();//请务必定义成 Singleton 单例模式    
            stopwatch.Stop();
            var timeused = stopwatch.ElapsedMilliseconds;
            string mes = $"使用FreeSql连接Access数据库已完成。用时：{timeused}ms。";
            progress?.Report($"{mes}");//IProgress<string> progress;

            /* 为什么不用 UseConnectionString，而改用 UseConnectionFactory？
             * 经与FreeSql作者沟通，得知：
             * UseConnectionString，该方法带预热。
             * 然而【联网状态下】读取带密码的accdb文件耗时极长，但对于无密码的文件又不会有这种情况。
             * UseConnectionFactory，该方法不带预热，不会出现上述bug，而且速度极快。
             */

            //----读取查询数据----
            var res_Select = fsql.Select<T0001_版本信息表>().Where(p => true).ToList();
            //var res = fsql.Select<T0101_公司情况表>().Where(p => p.统一社会信用代码 == "91420300MA49E8PA1F").First();
            foreach (var item in res_Select)
            {
                progress?.Report($"{item.版本号}--{item.版本说明}");
            }
        }
```

**Comment by wxysy** [comment]
> 3.2.684-preview20221124 已优化 MsAccess 默认只预热一个 OledbConnection。

3.2.683版本试用了，对Access支持的很好，不论是加密还是未加密的accdb文件，连接都很正常。
感谢耐心解答，此问题可以关闭了。

**Comment by wxysy** [comment]
> 3.2.684-preview20221124 已优化 MsAccess 默认只预热一个 OledbConnection。

3.2.684版本试用了，对Access支持的很好，不论是加密还是未加密的accdb文件，连接都很正常，目前没有再出现耗时极长的情况。
感谢耐心答复，此问题目前可关闭了。
