### ISSUE TITLE
FireBird 的sql.CodeFirst.SyncStructure<table1>(); 时候table的索引名称有误。

### ISSUE THREAD

**Issue by jianliulin** [dotnetcore/FreeSql#1346]
#### 问题描述及重现步骤：
产生的sql中 {tablename} 未替换成实际的表名
CREATE INDEX "{tablename}_Name" ON "table1"("Name");

![image](https://user-images.githubusercontent.com/4531974/203259964-f0037e8a-0a36-461b-be7c-7e52c8f6f278.png)

#1336 ### 数据库的具体版本
Firebird Firebird-4.0.2.2816-0-x64

```

#### 安装的包
```
    internal class Program
    {

        public static string connectionString = "client library=fbclient.dll;user id=SYSDBA;password=masterkey;initial catalog=__SampleDatabase.fdb;character set=UTF8;server type=Embedded";
        static void Main(string[] args)
        {

            try
            {
                FbConnection.CreateDatabase(connectionString, 4096, true,true);

                IFreeSql sql = new global::FreeSql.FreeSqlBuilder()
                .UseConnectionString(FreeSql.DataType.Firebird, connectionString)
                .UseAutoSyncStructure(false)
                .UseMonitorCommand(cmd => Console.WriteLine("\n" + cmd?.Connection?.Database + "\n" + cmd?.CommandText + "\n\n"))
                .UseNoneCommandParameter(true)
                .Build();

                sql.CodeFirst.SyncStructure<table1>();

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            Console.ReadLine();

        }
    }

    [Index("{tablename}_Name", nameof(Name))]
    public class table1
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }
```

#### .net framework/. net core？ 及具体版本
net7.0

```

**Comment by 2881099** [comment]
已处理，等待 preview 包发布

**Comment by 2881099** [comment]
3.2.684-preview20221123  已发布，10分钟后可更新
