### ISSUE TITLE
oracle 自动分表，有时候接口像会卡死，不出结果，直到接口超时。

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1347]
我访问10月的数据可以出来，访问9月的就卡着，感觉是里面一直在等待，直接接口超时。需要重启程序才可以，centos7服务器,freesql最新版。

**Comment by 2881099** [comment]
提供demo

**Comment by sukney** [comment]
_workSaleRepository.Select
                .From<GOODSDOC, BUSINESSDOC, ORGDOC>((a, b, c, d) => a.LeftJoin(z => z.GOODSID == b.GOODSID && z.ENTID == b.ENTID)
                 .LeftJoin(z => z.CLIENTID == c.BusinessId && z.ENTID == c.EntId)
                 .LeftJoin(z => z.REQORGID == d.ORGID))
                .WhereIf(state >= 0, (a, b, c, d) => a.State == state)
                .WhereIf(isDeleted.HasValue, (a, b, c, d) => a.IsDeleted == isDeleted.Value)
                .WhereIf(!string.IsNullOrWhiteSpace(xybm), (a, b, c, d) => b.XYBM == xybm)
                .WhereIf(!string.IsNullOrWhiteSpace(xycj), (a, b, c, d) => b.XYCJ.Contains(xycj))
                .WhereIf(req.Filter != null && req.Filter.Marks != null && req.Filter.Marks.Length > 0, (a, b, c, d) => req.Filter.Marks.Contains(a.Mark))
                  .WhereIf(!string.IsNullOrWhiteSpace(key), (a, b, c, d) => a.BILLCODE.Contains(key)
                  || b.GOODSNAME.Contains(key)
                  || b.MGOODCODE.Contains(key)
                  || b.GOODSCODE.Contains(key))
                  .DisableGlobalFilter()

**Comment by 2881099** [comment]
自动分表，实体类都没提供。

**Comment by sukney** [comment]
/// <summary>
    /// 新的销售表计算出的最终结果。
    /// </summary>
    [Description("康鑫销售数据")]
     [Table(Name = "WORK_SA_{yyyyMM}", AsTable = "DATETIME=2021-3-1(1 month)")]
    public class WorkSale : DisableEntity
    {
        /// <summary>
        /// 主键 单据号
        /// </summary>
        [Display(Name = "单据号")]
        public string PK { get; set; } = "";

        /// <summary>
        /// 来源
        /// </summary>
        [Display(Name = "来源")]
        public long WorkSaleTranId { get; set; }


        /// <summary>
        /// 来源
        /// </summary>
        public WorkSaleTran WorkSaleTran { get; set; } = new WorkSaleTran();


        /// <summary>
        /// 日期
        /// </summary>
        [Display(Name = "日期")]
        [Column(Name = "DATETIME")]
        public DateTime DATETIME { get; set; }
        /// <summary>
        /// ENTID
        /// </summary>
        [Display(Name = "ENTID")]
        public string ENTID { get; set; } = "";

        /// <summary>
        /// DATES
        /// </summary>
        [Display(Name = "DATES")]
        public string DATES { get; set; } = "";

        /// <summary>
        /// 时间
        /// </summary>
        [Display(Name = "时间")]
        public string ONTIME { get; set; } = "";
        /// <summary>
        /// 单据ID
        /// </summary>
        [Display(Name = "单据ID")]
        public int BILLNO { get; set; }

        /// <summary>
        /// 单据序号
        /// </summary>
        [Display(Name = "单据序号")]
        public int BILLSN { get; set; }

        /// <summary>
        /// 单据编号
        /// </summary>
        [Display(Name = "单据编号")]
        public string BILLCODE { get; set; } = "";


        /// <summary>
        /// 终端公司。（如宜草堂大药房连锁公司）
        /// </summary>
        [Display(Name = "终端公司")]
        public string CLIENTID { get; set; } = "";

        public string GOODSPK { get; set; } = "";
        /// <summary>
        /// 商品ID
        /// </summary>
        [Display(Name = "商品ID")]
        public string GOODSID { get; set; } = "";

        /// <summary>
        /// 数量 退的话为负数
        /// </summary>
        [Display(Name = "数量")]
        public decimal NUM { get; set; }
        /// <summary>
        /// 基本含税价
        /// </summary>
        [Display(Name = "单价")]
        public decimal TAXPRICE { get; set; }

        /// <summary>
        /// 计划金额 （退的话为负数）
        /// </summary>
        [Display(Name = "金额")]
        public decimal TAXAMOUNT { get; set; }

        /// <summary>
        /// 相关摘要  (SUMMARIES)  '销售出库单'  如果不是就是退回
        /// </summary>
        [Display(Name = "相关摘要")]
        public string SUMMARIES { get; set; } = "";

        /// <summary>
        /// 订单类型
        /// </summary>
        [Display(Name = "订单类型")]
        public string ORDERTYPE { get; set; } = "";

        /// <summary>
        /// 销售员
        /// </summary>
        [Display(Name = "销售员")]
        public string SALENAME { get; set; } = "";

        /// <summary>
        /// 批号 
        /// </summary>
        public string BATCHCODE { get; set; } = "";

        /// <summary>
        /// 生产日期
        /// </summary>
        public string PRODUCEDATE { get; set; } = "";

        /// <summary>
        /// 效期
        /// </summary>
        public string VALDATE { get; set; } = "";
        /// <summary>
        /// 单位
        /// </summary>
        public string UNIT { get; set; } = "";
        /// <summary>
        /// 标识说明
        /// </summary>
        [Display(Name = "标识说明")]
        public string PREFIXDESC { get; set; } = "";
        /// <summary>
        /// 需求组织ID
        /// </summary>
        [Display(Name = "备注")]
        public string REMARK { get; set; } = "";
        /// <summary>
        /// 需求组织ID （具体的药房）
        /// </summary>
        [Display(Name = "需求组织")]
        public string REQORGID { get; set; } = "";
        /// <summary>
        /// 机构名称具体的药房  orgid
        /// </summary>
        [Display(Name = "机构名称")]
        public string REQORGNAME { get; set; } = "";

        /// <summary>
        /// 转换类别 0不该品种不涉及规则，
        /// 1该品涉及规则但不需转换本身的目标跟转换的目标一致，
        /// 2转换的数据  用这个来判断宜草堂要转换的初始数据
        /// 10导入
        /// </summary>
        [Display(Name = "转换类别")]
        public int Mark { get; set; } = 0;


        /// <summary>
        /// 0未处理，1已处理
        /// </summary>
        [Display(Name = "店铺转换状态")]
        public int YctTran { get; set; } = 0;



        /// <summary>
        /// 订单成本金额
        /// </summary>
        public decimal COSTAMT { get; set; }


        /// <summary>
        /// 成本单价
        /// </summary>
        public decimal COSTPRICE { get; set; }


        /// <summary>
        /// 是否上传  0是默认，1是上传
        /// </summary>
        public int State { get; set; }=0;

        /// <summary>
        /// 转换使用数
        /// </summary>
        [Column(IsIgnore = true)]
        public decimal UseNum { get; set; } = 0;
    }

**Comment by 2881099** [comment]
你上面的查询用到 4 个实体类，这里却只发一个实体类。

算了，直接提供能编译通过的 demo 吧，不要挤牙膏一般零零碎碎地的发。

**Comment by 2881099** [comment]
```
.UseMonitorCommand(cmd =>
               {
                   cmd.CommandTimeout = 9999;
                   if (_systemConfig.CurrentValue != null && _systemConfig.CurrentValue.WatchCurd) {
                       _logger.LogInformation(cmd.CommandText);
                   }
               })
```

这里输出的日志贴出来。
