### ISSUE TITLE
.net 6.0  freesql 最新版  在win7上 连接 不了mysql

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1356]
<PackageReference Include="FreeSql" Version="3.2.683" />
		<PackageReference Include="FreeSql.Provider.MySql" Version="3.2.683" />
		<PackageReference Include="FreeSql.Repository" Version="3.2.683" />
using FreeSql;
using Microsoft.OpenApi.Models;
using System.Diagnostics;
using System.Reflection;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Unicode;
using XinFaData.Model;
using XinFaData.Services;

namespace XinFaData
{
    public class Program
    {

        public static void Main(string[] args)
        {

            var builder = WebApplication.CreateBuilder(args);
            var constr = builder.Configuration.GetConnectionString("mysql");

            var Fsql = new FreeSqlBuilder()
              .UseConnectionString(DataType.MySql, constr)
              .UseAutoSyncStructure(true)
              .UseMonitorCommand(cmd => Trace.WriteLine(cmd.CommandText))
              .UseNoneCommandParameter(true)
              .Build();

            // Add services to the container.

            builder.Services.AddControllers()
                .AddJsonOptions(options =>
                {
                    //空字段不响应Response
                    options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
                    //时间格式化响应
                    options.JsonSerializerOptions.Converters.Add(new DateTimeJsonConverter("yyyy-MM-dd HH:mm:ss"));
                    //格式化日期时间格式
                    // options.JsonSerializerOptions.Converters.Add(new DatetimeJsonConverter());
                    //数据格式首字母小写
                    options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
                    //数据格式原样输出
                    options.JsonSerializerOptions.PropertyNamingPolicy = null;
                    // 取消Unicode编码
                    options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All);
                    //  忽略空值
                    //options.JsonSerializerOptions.IgnoreNullValues = true;
                    // 允许额外符号
                    //options.JsonSerializerOptions.AllowTrailingCommas = true;
                    // 反序列化过程中属性名称是否使用不区分大小写的比较
                    //options.JsonSerializerOptions.PropertyNameCaseInsensitive = false;

                });

            //;
            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new OpenApiInfo
                {
                    Version = "v1",
                    Title = "API文档",
                    Description = "兴发票证接口",
                    //TermsOfService = new Uri(""),
                    //Contact = new OpenApiContact
                    //{
                    //    Name = "Li Contact",
                    //   // Url = new Uri("")
                    //},
                    //License = new OpenApiLicense
                    //{
                    //    Name = "Li License",
                    //    //Url = new Uri("")
                    //}
                });

                var xmlFilename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, xmlFilename));
            });

            builder.Services.AddSingleton<IFreeSql>(Fsql);
            builder.Services.AddScoped<UnitOfWorkManager>();

            //批量注入
            foreach (var repo in typeof(Program).Assembly.GetTypes()
                .Where(a => a.IsAbstract == false && typeof(IBaseRepository).IsAssignableFrom(a)))
                builder.Services.AddScoped(repo);

            builder.Services.AddScoped<TicketInfoService>();

            var app = builder.Build();

            // Configure the HTTP request pipeline.
            // if (app.Environment.IsDevelopment())
            //{
            app.UseSwagger();
            app.UseSwaggerUI();
            // }

            app.UseHttpsRedirection();

            app.UseAuthorization();

            app.MapControllers();

            app.Run();
        }
    }
}
using FreeSql;
using XinFaData.Data;
using XinFaData.Entity;
using XinFaData.Model;

namespace XinFaData.Services
{
    public class TicketInfoService
    {
        TicketRepository _repoTicketInfo;

        public TicketInfoService(TicketRepository repoTicketInfo)
        {
            _repoTicketInfo = repoTicketInfo;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        /// <param name="ticketInfo"></param>
        /// <returns></returns>
        public async Task<ResultDTO<TicketInfo>> Save(TicketInfo ticketInfo)
        {
            var res = await _repoTicketInfo.InsertOrUpdateAsync(ticketInfo);
            return new ResultDTO<TicketInfo>() { Data = res, Code = 1, Success = true, Message = "保存成功！" };
        }
    }
}
using FreeSql;
using XinFaData.Entity;

namespace XinFaData.Data
{
    public class TicketRepository : DefaultRepository<TicketInfo, string>
    {
        public TicketRepository(UnitOfWorkManager uowManger) : base(uowManger.Orm, uowManger)
        {
        }
    }
}
using FreeSql.DataAnnotations;
using System;
using System.ComponentModel.DataAnnotations;

namespace XinFaData.Entity
{
    /// <summary>
    ///  票务信息
    /// </summary>
    public class TicketInfo
    {
        /// <summary>
        /// 唯一标识
        /// </summary>
        [Display(Name = "唯一标识")]
        [Column(IsPrimary = true, IsIdentity = false)]
        [MaxLength(40)]
        public string id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// 装货井口
        /// </summary>
        [Display(Name = "装货井口")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(100,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string zhjk { get; set; }
        /// <summary>
        /// 发往单位
        /// </summary>
        [Display(Name = "发往单位")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(250,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string fwdw { get; set; }
        /// <summary>
        /// 发往货场
        /// </summary>
        [Display(Name = "发往货场")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(250,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string fwhc { get; set; }
        /// <summary>
        /// 车牌号
        /// </summary>
        [Display(Name = "车牌号")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(30,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string carNum { get; set; }
        /// <summary>
        /// 车队
        /// </summary>
        [Display(Name = "车队")]
        [MaxLength(250,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string carteam { get; set; }
        /// <summary>
        /// 品位编码
        /// </summary>
        [Display(Name = "品位编码")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(20,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string grade_code { get; set; }
        /// <summary>
        /// 品种编码
        /// </summary>
        [Display(Name = "品种编码")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(20,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string kind_code { get; set; }
        /// <summary>
        /// 打印时间 格式(yyyy-MM-dd HH:mm:ss)如2022-10-18 12:11:11
        /// </summary>
        [Display(Name = "打印时间")]
        public DateTime printtime { get; set; }
        /// <summary>
        /// 毛重
        /// </summary>
        [Display(Name = "毛重")]
        [Required(ErrorMessage ="{0}是必填项")]
        public float weight_com1 { get; set; }
        /// <summary>
        /// 皮重
        /// </summary>
        [Display(Name = "皮重")]
        [Required(ErrorMessage ="{0}是必填项")]
        public float weight_com2 { get; set; }
        /// <summary>
        /// 净重
        /// </summary>
        [Display(Name = "净重")]
        [Required(ErrorMessage ="{0}是必填项")]
        public float weight_com3 { get; set; }
        /// <summary>
        /// 通道
        /// </summary>
        [Display(Name = "通道")]
        [Required(ErrorMessage ="{0}是必填项")]
        [MaxLength(250,ErrorMessage ="{0}必须在{1}个字符以内")]
        public string source_id { get; set; }

    }
}
报如下错，mysql版本 10.10.2-MariaDB
【主库】Next recovery time: 2022-11-30 11:23:04 (Object cannot be cast from DBNull to other types.)
【主库】Next recovery time: 2022-11-30 11:23:06 (Object cannot be cast from DBNull to other types.)
【主库】Next recovery time: 2022-11-30 11:23:08 (Object cannot be cast from DBNull to other types.)
【主库】Next recovery time: 2022-11-30 11:23:10 (Object cannot be cast from DBNull to other types.)
【主库】Next recovery time: 2022-11-30 11:23:12 (Object cannot be cast from DBNull to other types.)

**Comment by sukney** [comment]
发现用FreeSql.Provider.MySql这个有问题，用FreeSql.Provider.MySqlConnector没问题

**Comment by 2881099** [comment]
Object cannot be cast from DBNull to other types.

用FreeSql.Provider.MySqlConnector没问题

**Comment by luoyunchong** [comment]
MariaDB 不是MySQL,  Oracle从未在任何地方说明MySql.Data支持其他类MySql的数据库。

https://mysqlconnector.net 社区实现才支持

MySqlConnector is an [ADO.NET](https://msdn.microsoft.com/en-us/library/e80y5yhx.aspx) data provider for [MySQL Server](https://www.mysql.com/), [MariaDB](https://mariadb.org/), [Percona Server](https://www.percona.com/software/mysql-database/percona-server), [Amazon Aurora](https://aws.amazon.com/rds/aurora/), [Azure Database for MySQL](https://azure.microsoft.com/en-us/services/mysql/), [Google Cloud SQL for MySQL](https://cloud.google.com/sql/docs/mysql/) and more. It provides implementations of DbConnection, DbCommand, DbDataReader, DbTransaction — the classes needed to query and update databases from managed code.
