### ISSUE TITLE
使用Contains进行模糊匹配时，查询条件中带下划线导致非期望的查询结果

### ISSUE THREAD

**Issue by KamenRiderKuuga** [dotnetcore/FreeSql#1359]
#### 问题描述及重现步骤：

描述：使用`Contains`进行模糊匹配时，`_`导致出现非期望的结果

重现步骤：
1. Clone项目：https://github.com/KamenRiderKuuga/ProjectForReproduce
2. 打开文件夹`FreeSqlLikeProblem`中的控制台项目
3. 使用一个可用的数据库，在里面执行`ScriptToInitData.sql`脚本，创建相关数据，并调整代码中的数据库连接字符串
4. 运行项目，查看运行结果

期望结果：所有的查询结果均为空

实际结果：
```
关键词: 姓名_, 搜索结果：姓名1,姓名2,姓名3
关键词: 姓名%, 搜索结果：
关键词: 姓_, 搜索结果：姓名1,姓名2,姓名3
关键词: 姓%, 搜索结果：
```

#### 数据库的具体版本
```
mariadb:10.5
```

#### 安装的包
```xml
<PackageReference Include="FreeSql" Version="3.2.683" />
<PackageReference Include="FreeSql.Provider.MySql" Version="3.2.683" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
```

#### .net framework/. net core？ 及具体版本
```
net6.0
```

**Comment by KamenRiderKuuga** [comment]
鉴于目前项目上的使用需要，调整了`MySqlExpression.cs`的相关代码，编译并发布到了私有仓库使用：
https://github.com/KamenRiderKuuga/FreeSql/commit/e71138001b3899d4f09e70a56bd4492b2a761955

参考了EF Core的MySQL驱动的做法：
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/a896e1f2dba5718a42060e78dcc23b6e8f349036/src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs#L638

**Comment by 2881099** [comment]
其实可以用《自定义表达式函数解析》解决问题。
