### ISSUE TITLE
SyncStructure 的速度很慢，能不能加快一些？

### ISSUE THREAD

**Issue by sgf** [dotnetcore/FreeSql#1360]
### Feature 特性

SyncStructure 的速度很慢，能不能加快一些？

#### 简要描述原因

情况是这样的，实体类大概有20枚左右（20个表左右，字段平均20个左右）。
每个类大概有1-3个索引（每个索引平均算8个字段）不等，在没有数据库的情况下使用SyncStructure 进行首次数据库初始化。
但是这块的时间很慢。平均大概要20秒左右（0硬盘访问的情况下），有时候甚至更长（有些硬盘访问的情况下）。

#### 使用场景

数据库是Sqlite，
硬盘是机械硬盘。
统计的时间存粹就是 SyncStructure  函数调用的消耗时间。

**Comment by densen2014** [comment]
请把demo贴上
