### ISSUE TITLE
Firebird事务中批量插入数据出错，当插入语句不在事务中则正常。

### ISSUE THREAD

**Issue by jianliulin** [dotnetcore/FreeSql#1368]
#### 问题描述及重现步骤：
Firebird事务中批量插入数据出错，当插入语句不在事务中则正常，如图：
![image](https://user-images.githubusercontent.com/4531974/205595921-79592a44-c25c-4dd0-a18f-e5c02b71603b.png)

测试代码：
`using FirebirdSql.Data.FirebirdClient;
using FreeSql.DataAnnotations;

namespace ConsoleApp1
{
    internal class Program
    {

        public static string connectionString = "initial catalog=c:\\__SampleDatabase.fdb;character set=UTF8;client library=fbclient.dll;user id=SYSDBA;password=masterkey;server type=Embedded";

        public static IFreeSql _freeFirebird = null;

        static void Main(string[] args)
        {

            try
            {
                FbConnection.CreateDatabase(connectionString, 16384, true, true);

                _freeFirebird = new FreeSql.FreeSqlBuilder()
                                .UseConnectionString(FreeSql.DataType.Firebird, connectionString)
                                .UseAutoSyncStructure(true)
                                .UseMonitorCommand(cmd => Console.WriteLine("\nFirebird:    " + cmd?.CommandText + "\n\n"))
                                .UseNoneCommandParameter(true)
                                .Build();

                var list = new List<Table1>();
                for (int i = 0; i < 10000; i++)
                {
                    list.Add(new Table1 { data = $"测试文本:{i}" });
                }

                var iffff = 1;

                if (iffff == 1)
                {
                    _freeFirebird.Transaction(() =>
                    {
                       
                        _freeFirebird.Insert(list).ExecuteAffrows();  //加在事务里就出错
                    });
                }
                else
                {
                    _freeFirebird.Insert(list).ExecuteAffrows(); ///不加事务则OK
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            Console.WriteLine("\n\n=========== End ===============");
            Console.ReadLine();

        }

    }

    public class Table1
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        [Column(StringLength = -1)]
        public string data { get; set; } = "市";
    }

}`
#### 数据库的具体版本
嵌入式 Firebird 4.02 ，
FirebirdSql.Data.FirebirdClient 9.1.0

#### 安装的包
```

```

#### .net framework/. net core？ 及具体版本
net7.0

**Comment by 2881099** [comment]
这是自动迁移功能和事务冲突的问题。

进拉事务内，创建了表，因为功能是分开的，建表时没有延用事务。所以在事务内报错【表不存在】。

解决办法：提前预热实体，提前触发自动迁移功能。

```c#
//批量预热
foreach (var type in types)
    fsql.Select<object>().AsType(type);
```

如果你上面的例子，在事务之前调用：

```c#
fsql.Select<Table>();
```

**Comment by 2881099** [comment]
因为 FreeSql 没有像 efcore DbSet 那样的定义，所以提前不知道哪些 class 是实体类。

**Comment by jianliulin** [comment]
谢谢，
