### ISSUE TITLE
Codefirst配置字段

### ISSUE THREAD

**Issue by ainidajingzi** [dotnetcore/FreeSql#137]
字段设置的IsNullable=false 但自动创建表后 字段类型还是可为Null，数据库：MySql
![image](https://user-images.githubusercontent.com/13308889/69227277-8b79e480-0bbc-11ea-8910-cc4b260149b3.png)

![image](https://user-images.githubusercontent.com/13308889/69227184-684f3500-0bbc-11ea-80f3-9d7b5b0275ba.png)

**Comment by 2881099** [comment]
有没有打Column特性

**Comment by 2881099** [comment]
还有 Aop 有没设置，呆会我试下

**Comment by 2881099** [comment]
已查明原因，待会发个包解决

**Comment by 2881099** [comment]
v0.11.23 包已发

**Comment by ainidajingzi** [comment]
Hi，IsNullable方法我测试着还有问题，当字段是string类型我设置IsNullable=**false**这时没有问题，生成的数据库字段确实是 不可为null ；
但是如果字段是DataTime/long等字段时，这时设置IsNullable=**true**不起作用。

**Comment by 2881099** [comment]
比使用 DateTime?

**Comment by ainidajingzi** [comment]
是的 
![image](https://user-images.githubusercontent.com/13308889/69301881-a4cd7000-0c52-11ea-8486-fca48855fb49.png)
![image](https://user-images.githubusercontent.com/13308889/69301925-cf1f2d80-0c52-11ea-8ecd-770e0856e0e8.png)

**Comment by 2881099** [comment]
哈哈，我的意思是，此时应该用 DateTime 后面带问好的类型

**Comment by pjy612** [comment]
就是 实体类 得用
DateTime?
long?

**Comment by 2881099** [comment]
> 就是 实体类 得用
> DateTime?
> long?

嗯

**Comment by 2881099** [comment]
IsNullable 基本只有 string 才有意义设置，其他是否可空，用 Nullable\<T\> 即 "类型?" 就行

**Comment by 2881099** [comment]
DateTime?、long? 设置 IsNullable 可以有意义
DateTime、long 设置 IsNullable 感觉上没意义

个人感觉

**Comment by ainidajingzi** [comment]
OK，这里不应该讨论有没有意义，应该是IsNullable起不起作用的问题。。。。
已修改为可空类型

**Comment by lxh023** [comment]
@ainidajingzi ，你好，我看到代码中的UserTableFluent类很好，想了解一下在程序启动的时候，怎么执行到它的？

**Comment by ainidajingzi** [comment]
@lxh023 配置CodeFirst
![image](https://user-images.githubusercontent.com/13308889/69400504-dadf2280-0d2c-11ea-8637-e4f95c60cce4.png)
