### ISSUE TITLE
查询clickhouse数据库时会发生的两个问题

### ISSUE THREAD

**Issue by hzw5251** [dotnetcore/FreeSql#1383]
clickhouse在分布式查询时 表名前必须带库名，此外不能直接使用left join，必须添加GLOBAL关键字，如GLOBAL left join否则会报错Double-distributed IN/JOIN subqueries is denied ；
举个例子：

```c#
class t1{//实体
string id
string name
}
class testDto{
string id
string name
string pname
}
```

freesql无法实现下列sql

```sql
SELECT a.*,b.name as pname
    FROM  db1.t1 AS a
    GLOBAL LEFT JOIN db2.t1 as b on t1.pid=t1.id
```

```c#
_IfreeSql_SqlClickHouse.Select<t1, t2>().LeftJoin(w => w.t1.pid = w.t2.id).ToList<testDto>();
```

//会报错Double-distributed IN/JOIN subqueries is denied ；需要把left join改成global  left join
这个bug导致了只要跨库查询，clickhouse就无法正常使用。tosql后替换字符的方法我也想过，但tosql必须在tolist之前，无法指定b表的字段。所以只能通过Ado.Query直接写sql。

此外，在clickhouse中，如果使用了*号然后使用Ado.Query的方式读取数据，返回的结果也会有问题。例如上面的sql语句，a.*号表示的a.id和a.name无法读取。但*以外的，如pname字段则显示正常。

我自己写了一个，发现在clickhouse中.IDataReader返回的字段读取为“表名.字段名"，也就是a.id和a.name，而非id和name

希望这两个bug作者大佬能一并修复。

**Comment by 2881099** [comment]
已发布 preview 包，请验证。

**Comment by hzw5251** [comment]
测试了一下，数据能读取到了。谢谢。
