### ISSUE TITLE
支持跨库事务

### ISSUE THREAD

**Issue by thtznet** [dotnetcore/FreeSql#1384]
#### Feature 特性
sqlserver下支持跨数据库的事务

#### 简要描述原因
TransactionScope 在 .Net 6/7 下支持有问题，且跨分布式使用需要一些服务器配置并只能在Windows下使用。SqlSugar 有可替代 TransactionScope的功能，参考：https://www.donet5.com/Home/Doc?typeId=1183 （2、多库事务（可跨库））。

#### 使用场景
某些场景下，需要同时像2个数据库添加数据，例如客户数据同步，同时写入销售管理、物流管理的数据库，任何一方失败希望全局回滚。不太适合使用TCC（或者说TCC使用很麻烦），同时写入的数据并没有前后的业务顺序

**Comment by 2881099** [comment]
这是什么神仙多库事务，什么机制能确保一致性。

**Comment by thtznet** [comment]
> 这是什么神仙多库事务，什么机制能确保一致性。

不确定SqlSugar的实现机制，但是的确是有效的。

**Comment by 2881099** [comment]
> > 这是什么神仙多库事务，什么机制能确保一致性。
> 
> 不确定SqlSugar的实现机制，但是的确是有效的。

一致性要测试的情况，A库成功，B库失败之后的逻辑。普通测试的话，只需要开两个事务嵌套即可，这样确保不了一致性。
