### ISSUE TITLE
动态类查询结果到DTO时语句解析有误

### ISSUE THREAD

**Issue by VicBilibily** [dotnetcore/FreeSql#1389]
#### 问题描述及重现步骤：
重现代码：https://github.com/VicBilibily/FreeSql/commit/6b4c7d251276eccc994dbb54d306a48b512788a7

尝试临时解决方法 WithTempQuery(dto).ToList() 套了一层后正确解析

#### 数据库的具体版本
```
MySQL8
```

#### 安装的包
```
    <PackageReference Include="FreeSql.DbContext" Version="3.2.684" />
    <PackageReference Include="FreeSql.Provider.MySqlConnector" Version="3.2.684" />
    <PackageReference Include="FreeSql.Provider.SqlServerForSystem" Version="3.2.684" />
```

#### .net framework/. net core？ 及具体版本
```
net7
```

**Comment by ALer-R** [comment]
临时处理
`.AsType(typeof(GoodsData))`
改为
`.AsTable((_,_) => (typeof(GoodsData).GetCustomAttribute(typeof(TableAttribute), false) as TableAttribute).Name)`

**Comment by 2881099** [comment]
fsql.Select\<object\>().AsType(typeof(T))

这样也行。
