### ISSUE TITLE
请增加NavigateAttribute的类型关系

### ISSUE THREAD

**Issue by 454116278** [dotnetcore/FreeSql#1391]
期望以下列方式进行导航，在实体类实现时，进行实现类向接口类的转换。
现有的框架还不能实现该需求。
    
public class NavigateAttribute : Attribute
    {

        /// <summary>
        /// OneToOne：[Navigate(nameof(Primary))] &lt;-&gt; (缺省)外表.Primary<para></para>
        /// ManyToOne：Topic.cs 文件 [Navigate(nameof(Topic.CategoryId))] &lt;-&gt; (缺省)Category.Id<para></para>
        /// _________________public Category Category { get; set; }<para></para>
        /// OneToMany：Category.cs 文件 (缺省)Category.Id &lt;-&gt; [Navigate(nameof(Topic.CategoryId))]<para></para>
        /// _________________public List&lt;Topic&gt; Topics { get; set; }<para></para>
        /// </summary>
        public string Bind { get; set; }
        /// <summary>
        /// 手工绑定 ManyToMany 导航关系
        /// </summary>
        public Type ManyToMany { get; set; }

        /// <summary>
        /// 当返回对象为基类型时，该属性指向具体的类型
        /// </summary>
        public Type InstanceType { get; set; }

        /// <summary>
        /// OneToOne：[Navigate(nameof(Primary))] &lt;-&gt; (缺省)外表.Primary<para></para>
        /// ManyToOne：Topic.cs 文件 [Navigate(nameof(Topic.CategoryId))] &lt;-&gt; (缺省)Category.Id<para></para>
        /// _________________public Category Category { get; set; }<para></para>
        /// OneToMany：Category.cs 文件 (缺省)Category.Id &lt;-&gt; [Navigate(nameof(Topic.CategoryId))]<para></para>
        /// _________________public List&lt;Topic&gt; Topics { get; set; }<para></para>
        /// </summary>
        public NavigateAttribute(string bind)
        {
            this.Bind = bind;
        }
        public NavigateAttribute()
        {
        }
    }
}

/// <summary>
    /// 在数据接口层定义该实体接口，用户角色接口
    /// </summary>
    public interface IRole
    {

    }   

	/// <summary>
	/// 在数据接口层定义该实体接口，用户角色关系表接口
	/// </summary>
    public interface IUserRole
    {

    }

	/// <summary>
	/// 在数据访问层定义该实体类，用户角色关系表。
	/// 目的：供助IOC，分隔应用层与数据访问层之差的关系，隔离应用层对ORM、数据访问层的依赖。
    /// </summary>
	[JsonObject(MemberSerialization.OptIn)]
	public partial class UserRole : BaseEntity<UserRole>, IUserRole{
		/// <summary>
		/// 角色编号1
		/// </summary>
		[JsonProperty]
		public long RoleId { get; set; }
		/// <summary>
		/// 角色导航，
		/// </summary>
		[Navigate("RoleId", InstanceType=typeof(Role))]
		public IRole Role { get; set; }

		/// <summary>
		/// 用户编号
		/// </summary>
		[JsonProperty, Column(DbType = "varchar(50)")]
		public string UserId { get; set; }
		/// <summary>
		/// 用户导航
		/// </summary>
		[Navigate("UserId")]
		public User Users { get; set; }

	}

**Comment by 2881099** [comment]
改动和测试量大，暂时不支持

**Comment by jianliulin** [comment]
非常希望有这项功能,
