### ISSUE TITLE
IUpdate,IInsert的InsertColumns(string[])、UpdateColumns(string[])、IgnoreColumns(string[])大小写问题

### ISSUE THREAD

**Issue by malegend** [dotnetcore/FreeSql#1396]
IUpdate,IInsert的InsertColumns(string[])、UpdateColumns(string[])、IgnoreColumns(string[])大小写是否存在BUG或有意为之？

如：数据库表中有字段名为Name，如果用 xxxColumn(new []{"name"})则无效，必须使用xxxColumn(new []{"Name"})才可以。

**Comment by 2881099** [comment]
这个跟实体类Column特性映射有关，或者也可以用属性名

**Comment by malegend** [comment]
对于数组模式且手敲下，忽略大小写可以提高容错率，建议忽略大小写。

**Comment by 2881099** [comment]
多用 nameof(T.P1) 可以避免这种问题

UpdateColumns(new [] { nameof(T.P1) })

```c#
class T
{
    public string P1 {get;set;}
}
```
