### ISSUE TITLE
希望 WithTempQuery可以跟 tolist dto 一样 属性名相同的自动映射

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1399]
#1394 
看了下用 WithTempQuery 后再排序可以，但希望 WithTempQuery可以跟 tolist dto 一样 属性名相同的自动映射。

**Comment by 2881099** [comment]
嵌套查询太复杂了，自动映射在这个环节做需要评估。

**Comment by 2881099** [comment]
WithTempQuery 是一个 Expression\<Func\<T, object\>> 类型，其实可以自已根据映射需求，写一个构建。
