### ISSUE TITLE
达梦V8查询出错，提示：连接字符串错误，请检查。

### ISSUE THREAD

**Issue by xtxk110** [dotnetcore/FreeSql#1401]
#### 问题描述及重现代码：
连接达梦V8数据库查询时，提示：
【主库】连接字符串错误，请检查。"
连接字符串：server=xx.xx.xx.xx;User Id=SYSDBA;password=SYSDBA;compatibleMode=1;conn_pooling=True
用达梦官方DmProvider.dll没有问题
```c#
//连接部分代码
FreeSqlBuilder freeSqlBuilder = new FreeSqlBuilder().UseConnectionString(conn.DataType, conn.Connection);
```

#### 数据库版本 
达梦V8

#### 安装的Nuget包
FreeSql.Provider.Dameng 3.2.6.85
FreeSql.Repository 32.6.85

#### .net framework/. net core？ 及具体版本
.net5

**Comment by xtxk110** [comment]
我发现了。连接字符串除了server, user id, password这三个外，其他的都不设置，这样才能连接上
后期能不能适配其他的连接字符串参数呢

**Comment by 2881099** [comment]
每款数据库驱动，对应的连接串都有所不同，文档有给出连接串示例。
