### ISSUE TITLE
JsonMap 调整后，对字典数据失效

### ISSUE THREAD

**Issue by woodcoal** [dotnetcore/FreeSql#1404]
```v3.2.686 优化 JsonMap 对基础类型的无效判断；#1385```

更新后 v3.2.686，导致字典类型无法使用，如：
```
[JsonMap]
public Dictionary<string, string> Extension { get; set; }
```

JsonMap 失效，建议保留字典类型和列表类型

**Comment by 2881099** [comment]
数据库是 postgresql 吗？

如果是，Dictionary<string, string> 默认映射 pgsql hstore 类型，其实用 JSON 反而不合适。

**Comment by 2881099** [comment]
等待回复再权衡

**Comment by woodcoal** [comment]
> 数据库是 postgresql 吗？
> 
> 如果是，Dictionary<string, string> 默认映射 pgsql hstore 类型，其实用 JSON 反而不合适。

不是，是 MySQL，或者建议 JsonMap 设置一个参数，默认是否允许禁用某些类型

**Comment by 2881099** [comment]
## v3.2.687

- **修复 3.2.686 JsonMap bug；**
- 优化 参数化增加 ExpandoObject 支持；#1403
- 优化 pgsql15.0 Version 版本号处理；
- 优化 pgsql CodeFirst Syncsture CREATE INDEX code；
