### ISSUE TITLE
二进制文件 FreeSql.Provider.Sqlite.dll 是在调试模式下生成的。

### ISSUE THREAD

**Issue by adxpcc** [dotnetcore/FreeSql#1407]
基于WindowsAppSdk+.net6 开发的客户端程序(WinUI3),
在打包安装程序后,使用Windows App Certification Kit 验证包时,出现以下提示:

#### 问题描述及重现代码：

![image](https://user-images.githubusercontent.com/15758574/215430486-f87feb9d-da0a-433d-8a31-17f7032068ad.png)

#### 数据库版本
sqlit
#### 安装的Nuget包
 Include="FreeSql" Version="3.2.687" 
 Include="FreeSql.Provider.Sqlite" Version="3.2.687" 

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by adxpcc** [comment]
<PackageReference Include="FreeSql" Version="3.2.687" />
		<PackageReference Include="FreeSql.Provider.Sqlite" Version="3.2.687" />

**Comment by 2881099** [comment]
是 debug 模式发布的，便于解决问题。
