### ISSUE TITLE
设置全局脏读后，查询报错

### ISSUE THREAD

**Issue by yinsitan** [dotnetcore/FreeSql#1410]
#### 问题描述及重现代码：
全局脏读
![image](https://user-images.githubusercontent.com/86031918/216509618-59b9d73c-84f9-4b55-ad6f-fa698b937691.png)

C#代码
![image](https://user-images.githubusercontent.com/86031918/216509725-7ff6d18a-57c3-4f29-9f68-d60c9718ff6d.png)

生成的sql
![image](https://user-images.githubusercontent.com/86031918/216509649-51d27c1a-603a-45b3-8528-31529fb3b4b7.png)

```c#
// c# code
```
实体：
/// <summary>
    /// 房间
    /// 创建时间：2022-11-07
    /// </summary>
    [Table(Name = "Room")]
    public class Room : BaseEntity<string>
    {
        /// <summary>
        /// 1 上架，2下架,3禁租
        /// </summary>
        [Description("状态")]
        [Column(IsNullable = false )]
        public int? State { get; set; }

        /// <summary>
        /// 1独立办公，2联合办公，3店铺，4场地
        /// </summary>
        [Description("房源类型 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Type { get; set; }

        [Description("是否首页推荐 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public bool? IsIndex { get; set; }

        [Description("园区ID ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string ParkId { get; set; }

        [Description("图片 ")]
        [Column(StringLength = 256, IsNullable = false)]
        public string Image { get; set; }

        [Description("名称 ")]
        [Column(StringLength = 128, IsNullable = false)]
        public string Name { get; set; }

        [Description("单价 ")]
        [Column(IsNullable = false)]
        public decimal Price { get; set; }

        [Description("转让费 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string CedePrice { get; set; }

        [Description("单价/元/工位/月 ")]
        [Column(IsNullable = false)]
        public decimal StationPrice { get; set; }

        [Description("总价 ")]
        [Column(IsNullable = false)]
        public decimal TotalPrice { get; set; }

        [Description("面积 ")]
        [Column( IsNullable = false)]
        public decimal Proportion { get; set; }

        [Description("使用面积 ")]
        [Column( IsNullable = false)]
        public decimal ProportionUse { get; set; }

        [Description("经营状态 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string MengState { get; set; }

        [Description("经营业态 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string MengType { get; set; }

        [Description("证照 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Licence { get; set; }

        [Description("楼层 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string FloorNum { get; set; }

        [Description("装修 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Renovation { get; set; }

        [Description("户型 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string HouseType { get; set; }

        [Description("预定方式 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Booking { get; set; }

        [Description("工商注册 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string IsRegister { get; set; }

        [Description("房源朝向 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Orientation { get; set; }

        [Description("窗面朝向 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Face { get; set; }

        [Description("免租期 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string RentFree { get; set; }

        [Description("起租日 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string StartFree { get; set; }

        [Description("最短租期 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string MinLeaseTerm { get; set; }

        [Description("押付方式押 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string PledgeNum { get; set; }

        [Description("押付方式付 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string PledgePayNum { get; set; }

        [Description("看房时间 ")]
        [Column(StringLength = 128, IsNullable = false)]
        public string OpenRemark { get; set; }

        [Description("房源描述 ")]
        [Column(StringLength = -1, IsNullable = false)]
        public string Remark { get; set; }

        [Description("顾问ID ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string AdviserId { get; set; }

        [Description("顾问姓名 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string AdviserName { get; set; }

        [Description("顾问电话 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string AdviserPhone { get; set; }

        [Description("场地类型 ")]
        [Column(StringLength = 64, IsNullable = true)]
        public string SiteType { get; set; }

        [Description("最大容纳 ")]
        [Column( IsNullable = true)]
        public int? MaxPeople { get; set; }

        [Description("浏览量（关注人数） ")]
        [Column(IsNullable = false)]
        public int? BrowseNum { get; set; }

        [Description("场地守则 ")]
        [Column(StringLength = -1, IsNullable = true)]
        public string SiteRule { get; set; }

        [Description("省 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Province { get; set; }

        [Description("市 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string City { get; set; }

        [Description("区 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string AreaCode { get; set; }

        [Description("街道（路） ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Road { get; set; }

        [Description("门牌 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string House { get; set; }

        [Description("经度 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Longitude { get; set; }

        [Description("纬度 ")]
        [Column(StringLength = 64, IsNullable = false)]
        public string Latitude { get; set; }

        [Description("城市标识")]
        [Column(StringLength = 64, IsNullable = false)]
        public string CityId { get; set; }

    }

-- 查询代码
await _room.Select
                .FromQuery(_roomconsult.Select
                    .GroupBy(b => new { tt2 = b.RoomId })
                    .WithTempQuery(b => new
                    {
                        RoomId = b.Key.tt2,
                        Number = b.Count(),
                    })
                    ).LeftJoin((a, b) => a.Id == b.RoomId)
                    .Where(a=>a.t1.ParkId==dto.Id)
                    .GroupBy(a => new { tt2 = a.t1.Type })
                    .OrderBy(a => a.Key.tt2)
                    .ToListAsync<RoomNumDto>(a => new RoomNumDto
                    {
                        Type = a.Key.tt2,
                        Number = a.Count(),
                        Price = a.Min(a.Value.Item1.Price),
                        Proportion = a.Min(a.Value.Item1.Proportion) + "~" + a.Max(a.Value.Item1.Proportion),
                        BrowseNum = a.Sum(a.Value.Item1.BrowseNum) > 9999 ? (a.Sum(a.Value.Item1.BrowseNum) / 10000).ToString() + "w" : a.Sum(a.Value.Item1.BrowseNum).ToString(),
                        FloowNum = a.Sum(a.Value.Item2.Number) > 9999 ? a.Sum(a.Value.Item2.Number).ToString() + "w" : a.Sum(a.Value.Item2.Number).ToString()
                    });

#### 数据库版本
sql server 2019

#### 安装的Nuget包
FreeSql 3.2.682
FreeSql.Repository  3.2.682
FreeSql.Provider.SqlServer  3.2.682

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by 2881099** [comment]
是嵌套查询和该功能的冲突，有没有升级3.2.687试试？

**Comment by yinsitan** [comment]
![image](https://user-images.githubusercontent.com/86031918/216861848-d687084d-3b52-4909-b149-5a78a3d11480.png)
升级到3.2.687就可以了，感谢！
