### ISSUE TITLE
freesql 执行pg 过程错误

### ISSUE THREAD

**Issue by lijianxin520** [dotnetcore/FreeSql#1415]
![image](https://user-images.githubusercontent.com/47262889/217734566-65639633-e58b-4aeb-abef-7a7a150b50e5.png)
存储过程声明如下：
CREATE OR REPLACE PROCEDURE "public"."sp_condiext_casecauseupdateallpid"("cc_idchar" varchar)

**Comment by 2881099** [comment]
这是npgsql 7中一个有文档记录的突破性更改。
关于存储过程/函数的文档还指出：
警告
从Npgsql 7.0开始，CommandType.StoredProcedure现在调用存储过程，并且不再像以前那样工作。有关详细信息以及如何退出此更改，请参阅发行说明。
有两个选择
1.禁用新功能
当NpgsqlCommand.CommandType设置为CommandType.StoredProcedure时，Npgsql现在生成SQL来调用PostgreSQL存储过程，而不是像以前一样生成函数。要退出此破坏性更改并继续像以前一样调用函数，请按如下所示启用Npgsql.EnableStoredProcedureCompatMode AppContext开关：
AppContext.SetSwitch("Npgsql.EnableStoredProcedureCompatMode", true);
或
1.使用常规select调用函数
using var cmd = new NpgsqlCommand("SELECT my_func(1, 2)", conn);

**Comment by 2881099** [comment]
参考一下

**Comment by lijianxin520** [comment]
感谢！原来是ado的问题。
