### ISSUE TITLE
关于审计日志的问题

### ISSUE THREAD

**Issue by TinManGo** [dotnetcore/FreeSql#1419]
#### 问题描述及重现代码：

```c#
//官网的这个审计例子报错，正确的用法是怎样的？
var uow = fsql.CreateUnitOfWork();
uow.OnEntityChange = report => {
  Console.WriteLine(report);
};
```

#### 数据库版本
mysql 5.6.45

#### 安装的Nuget包

3.2.687
#### .net framework/. net core？ 及具体版本
framework 4.5.2

**Comment by 2881099** [comment]
什么错，数据审计只适合 仓储或者DbContext 模式

**Comment by TinManGo** [comment]
![image](https://user-images.githubusercontent.com/12207054/218620764-b7ed7e4f-8e54-462a-b695-fd5d244c604f.png)
编译器自动报了一个错不知道怎么回事。

**Comment by TinManGo** [comment]
![image](https://user-images.githubusercontent.com/12207054/218621793-ac2dcff7-cc20-4162-80a1-7616cf8c9b15.png)

**Comment by TinManGo** [comment]
另外能否追加一个可选参数，在SetDbContextOptions拦截时 ChangeInfo 中可以读取。insert和update还可以 如果是delete 就获取不到操作者的相关信息，达不到审计追踪的效果了。

**Comment by 2881099** [comment]
uow.EntityChangeReport.OnChange = report => {
   //todo...
};

delete 如果是先查询再删除就可以，如果直接传 lambda 或者 sql 类型作为条件，达不到目的。

**Comment by TinManGo** [comment]
感谢 删除的问题已经解决了。顺便再问下，OnEntityChange 事件能否屏蔽对某些字段的触发呢？

**Comment by 2881099** [comment]
暂时不能
