### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by ProximaB** [dotnetcore/FreeSql#142]
Is there space to free contribution to this project?
At first glance, it seems to be targeted to only Chinese people. Would you like to make it more universal so more people could appreciate it?
Maybe I could help you to translate documentation to English, and help to maintain it.
I look forward to hearing from you soon. 😀

**Comment by 2881099** [comment]
Thank you. I'll get back to you later

**Comment by ajdwfnhaps** [comment]
Congratulations, a big step towards for the international open soure project.

**Comment by alexinea** [comment]
This is a small step for @2881099 , but it is a big step for FreeSql. 😁

**Comment by 2881099** [comment]
@ProximaB 

Welcome to join the project, and we are looking forward to your translation.

(translation from fanyi.baidu.com 😀)

**Comment by xingwen1987** [comment]
This is a small step for @2881099 , not only a big step for FreeSql but also a huge step for .Net Core! 😀😀

**Comment by densen2014** [comment]
Hello , proximaB, soy chino en Madrid 😀

**Comment by mdissel** [comment]
For a simple start we can make google translate a little bit smarter by not translating code via the html tag translate="no" or class="notranslate"
see https://cloud.google.com/translate/faq#technical_questions
and add a button

**Comment by 2881099** [comment]
@mdissel Chinese Simple
