### ISSUE TITLE
DbFirst 命令行 -Json不工作

### ISSUE THREAD

**Issue by shengqiang996** [dotnetcore/FreeSql#1424]
#### 问题描述及重现代码：
使用命令行工具生成模型类的时候，命令中的-Json NONE 不起作用

#### .net framework/. net core？ 及具体版本
项目：net core 2.2  最高版本net 7

**Comment by 2881099** [comment]
-Json 设置没有实现的

**Comment by 2881099** [comment]
原需求 https://github.com/dotnetcore/FreeSql/issues/1183

卡在 stj 的特性上，之前和提需求的朋友 qq 上分析过原因。然后搁置了，但是 --help 信息提交了。
