### ISSUE TITLE
sqlite DbFirst 获取不到表索引

### ISSUE THREAD

**Issue by jianliulin** [dotnetcore/FreeSql#1425]
#### 问题描述及重现代码：

var aaa= freeSql.DbFirst.GetTablesByDatabase("main");

 获取回来aaa[0]的UniquesDict，IndexesDict 均为空

#### 数据库版本

sqlite

#### 安装的Nuget包
FreeSql.Provider.Sqlite 3.2.687

#### .net framework/. net core？ 及具体版本
.net7.0

**Comment by 2881099** [comment]
收到，3.2.688 完善。

UniquesDict.Name 貌似有问题，PRAGMA INDEX_LIST 获取到的 name 与 navicat 中设置的不一致。

**Comment by 2881099** [comment]
发布了 v3.2.688-preview20230216 体验版
