### ISSUE TITLE
使用动态where，虽然传入的了条件，但是没有效果。

### ISSUE THREAD

**Issue by lijianxin520** [dotnetcore/FreeSql#1428]
使用动态where，虽然传入的了条件，但是没有效果。
![image](https://user-images.githubusercontent.com/47262889/219856264-ef740fb6-6a15-45c4-b7e5-a95e47766702.png)

**Comment by 2881099** [comment]
fywhere 是怎么实现的

**Comment by luoyunchong** [comment]
Expression<Func<Materialquality,bool>>dywhere

.Where(dywhere) 才对

**Comment by lijianxin520** [comment]
哦，抱歉，我以为是这样做也可以呢。
