### ISSUE TITLE
Master Database Block access and wait for recovery

### ISSUE THREAD

**Issue by hellokuls** [dotnetcore/FreeSql#1430]
#### 问题描述及重现代码：

日志频繁报以下三类错误：

FreeSql：Master Database Block access and wait for recovery

"System.Exception: Connection must be valid and open.

The FreeSql: Master Database status is unavailable and cannot be used until the background checker is restored. Object reference not set to an instance of an object

上面三类错误频繁出现，部署在Linux环境。不知是freesql连接方面问题，还是服务器层tcp连接的问题。

#### 数据库版本

8.0
#### .net framework/. net core？ 及具体版本
.net6.0

**Comment by 2881099** [comment]
Connection must be valid and open.

Object reference not set to an instance of an object

什么数据库？

UseConnectionString 换成 UseConnectionFactory 试试。

这个错误报错是因为 ado.net 层面的 new MySqlConnection().Open() 或者 cmd.Execute 报错。

**Comment by hellokuls** [comment]
不好意思没有写全，MySQL 8.0

**Comment by hellokuls** [comment]
根据抓取的tcp包，发现有一些tcp连接是可以正常完成并结束的，但是有一些是在三次握手之后直接reset掉了。这个也是跟UseConnectionString有关吗？

**Comment by 2881099** [comment]
没关系，跟网络有关
