### ISSUE TITLE
Clickhosue datetime64 格式的字段，单条insert和多条insert后的时间不一样

### ISSUE THREAD

**Issue by rxjhfmf** [dotnetcore/FreeSql#1437]
发现Clickhosue datetime64 格式的字段，单条insert和多条insert后的时间不一样

**Comment by 2881099** [comment]
因为单条是 SQL 执行，多条是用 ClickHouseBulkCopy

**Comment by 2881099** [comment]
ClickHouseBulkCopy 是由 ClickHouse.Client 控制的，不知道有没有提供设置。

**Comment by rxjhfmf** [comment]
怎么设置？

**Comment by rxjhfmf** [comment]
另外，发现从数据库中获取到datetime字段的值，这个时间是DateTimeKind.Unspecified的

**Comment by rxjhfmf** [comment]
> ClickHouseBulkCopy 是由 ClickHouse.Client 控制的，不知道有没有提供设置。

请教下，怎么设置呢
