### ISSUE TITLE
不支持私有字段

### ISSUE THREAD

**Issue by klpjp87** [dotnetcore/FreeSql#1439]
#### 问题描述及重现代码：
使用导航属性，list字段想private，然后提供add  remove getlist方法，但是freesql在获取实体字段时，使用的是GetProperties方法，只会获取公共属性，导致查询的时候不会赋值，新增的时候通过增加column特性可以新增成功
```c#
// c# code
```
[Navigate(nameof(SysBaseDicElements.DicCategoryCode))]
        [Column]
        private IList<SysBaseDicElements> DicElements { get; set; }
#### 数据库版本

oracle
#### .net framework/. net core？ 及具体版本
core

**Comment by klpjp87** [comment]
只能通过这么解决

private IList<SysBaseDicElements> _dicElement;
        /// <summary>
        /// 字典元素信息
        /// </summary>
        [Navigate(nameof(SysBaseDicElements.DicCategoryCode))]
        public IList<SysBaseDicElements> DicElements { get { return _dicElement?.AsReadOnly(); } private set { _dicElement = value; } }

**Comment by 2881099** [comment]
可以用 ICollection\<T\>
