### ISSUE TITLE
请问能够提供对很老版本Oracle的支持吗？

### ISSUE THREAD

**Issue by hesi726** [dotnetcore/FreeSql#1442]
我看了一下源代码，对 Oracle数据库，底层使用了 ODP.NET, 但根据 Oracle的官方文档，
* Access to Oracle Database 10g Release 2 or later

而我们公司一直使用的 Oracle9i (升级价格太贵,而且也够用), 这个目前没有哪个 ORM 支持;
但是一直使用的是 System.Data.OracleClient （https://github.com/tonyrapozo/System.Data.OracleClient) 在 Linux 使用原始SQL进行操作；

请问一个提供一个  FreeSql.DataType.OracleClient 类似的方式，支持 Oracle9i 吗？

### WINDOWS
* 下载 oracle instantclient 10.2 的压缩包
* 解压到类似 D:\Oracle\instantclient_10_2 目录
    

* 设置如下环境变量
  > 不能在 dos 窗口下使用 set 去设置;
  > 不能在代码中设置

  * LD_LIBRARY_PATH=D:\Oracle\instantclient_10_2
  * NLS_LANG =SIMPLIFIED CHINESE_CHINA.ZHS16GBK
  * OCI_HOME=D:\Oracle\instantclient_10_2
  * OCI_LIB_DIR =D:\Oracle\instantclient_10_2
  * ORACLE_HOME=D:\Oracle\instantclient_10_2
  * PATH=%PATH%;D:\Oracle\instantclient_10_2

### Linux 或者 Unix
* 下载 oracle instantclient 10.2 的压缩包
* 解压到类似 /usr/share/oracle_instantclient 目录
* 在 Linux环境下：（修改  /etc/profile 文件) 增加如下环境变量设置:
  * export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/share/oracle_instantclient
  * export NLS_LANG="SIMPLIFIED CHINESE_CHINA.ZHS16GBK"
  * export OCI_HOME=/usr/share/oracle_instantclient
  * export OCI_LIB_DIR=/usr/share/oracle_instantclient
  * export ORACLE_HOME=/usr/share/oracle_instantclient

* 增加 liboci.so 的链接文件
  *（因为加载的是 liboci库而不是 libociei 库;
  > ln -s /usr/share/oracle_instantclient/libociei.so /usr/share/oracle_instantclient/liboci.so 

## 引入 FreeSql.Provider.Odbc 项目:

使用 FreeSql 去访问 Oracle数据库
```
private static string conn = @"Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=adshel)));User Id=abcabcabc;Password=abcabcabc";
 private static IFreeSql Fsql = new FreeSql.FreeSqlBuilder()
            .UseConnectionString(FreeSql.DataType.OracleClient , conn)            
            .UseAutoSyncStructure(false)
            .Build();
```

**Comment by 2881099** [comment]
https://freesql.net/guide/freesql-provider-oracle.html
有没有看这个

**Comment by hesi726** [comment]
问题是，我们项目需要升级到 netcore, 而 netcore 下 oracle 没有找到支持 oracle9i 的驱动.

**Comment by 2881099** [comment]
我明白，这个不是简单增加一个 DataType.OracleClient 能解决的，需要配置类型映射。

目前三种方式， ODP.NET 或者 OLEDB 或者 ODBC，三种都不行吗？

**Comment by hesi726** [comment]
ODP.net 和 OLEDB 都肯定不行，
ODBC 我去测试一下看看通过 
https://www.unixodbc.org/  
在 unix 下安装一下  odbc 的驱动，试试看看可以不。

**Comment by 2881099** [comment]
System.Data.OracleClient 已经6年没有更新了哦

**Comment by 2881099** [comment]
有结果了吗
