### ISSUE TITLE
freesql 和 SqlSugar,dapper 很类似，谁能做个详细的比较。

### ISSUE THREAD

**Issue by neozhu** [dotnetcore/FreeSql#145]

**Comment by 2881099** [comment]
主要的区别

1. CodeFirst的支持程度，FreeSql使用体验优势明显；
2. 导航属性，表达式、级联查询、级联保存，这三个只有FreeSql可以；
3. 多种数据库的使用习惯一致性，FreeSql有3000多个单元测试。

其他是细节问题了，FreeSql友好程度可以通过使用才能发现。

FreeSql的部分黑科技功能 https://github.com/2881099/FreeSql/wiki/%E9%AA%9A%E6%93%8D%E4%BD%9C

**Comment by 2881099** [comment]
补充：FreeSql 有状态功能，更新实体只执行变化部分的更新。这个是可选功能，在 FreeSql.DbContext 实现。

**Comment by neozhu** [comment]
你说的导航属性，是不是就是标注外键，和EF [ForeignKey] 一样的功能
FreeSQL确实不错，文档也非常详细，在国内的程序员里肯花这么多时间在一个免费开源的项目上真的很佩服！

**Comment by 2881099** [comment]
获奖了，

是的，和 ForeignKey 类似，我们的不依赖外键。
