### ISSUE TITLE
Orm多表查询后，在进行排序报错（进行了自动分表）

### ISSUE THREAD

**Issue by lanfeirj** [dotnetcore/FreeSql#1450]
![image](https://user-images.githubusercontent.com/16495460/223895401-7dd383d3-d96b-4708-87d2-09ff9b43a2b5.png)
进行排序后会报错
![1678327008874](https://user-images.githubusercontent.com/16495460/223895851-1d86b8a2-641d-4259-b570-43ffda8c5e40.png)

**Comment by lanfeirj** [comment]
或者是报这个错
![image](https://user-images.githubusercontent.com/16495460/223910143-d32997c1-f98c-4c69-b9b3-5014a5cb2081.png)

**Comment by lanfeirj** [comment]
SELECT  * from (SELECT TOP 10 a.[TrajectoryId], a.[VehicleId], a.[VehicleNumber], a.[ZoneId], a.[MasterId], a.[BaseId], a.[EnterTime], a.[VehicleDirection], a.[IsShow] 
FROM [VehicleTrajectory_202303] a 
INNER JOIN [Zone] b ON a.[ZoneId] = b.[ZoneId] 
INNER JOIN [MasterStation] c ON a.[MasterId] = c.[MasterId] 
INNER JOIN [BaseStation] d ON a.[BaseId] = d.[BaseId] 
INNER JOIN [Coordinate] e ON e.[DeviceType] = 0 AND e.[DeviceId] = a.[BaseId] AND e.[ZoneId] = a.[ZoneId] 
INNER JOIN [Vehicles] f ON f.[VehicleId] = a.[VehicleId] 
INNER JOIN [Department] g ON g.[DepartmentId] = f.[DepartmentId] 
WHERE (a.[EnterTime] >= cast(N'2022-10-24 11:06:14' as datetime)) AND (a.[EnterTime] <= cast(N'2023-02-24 11:06:14' as datetime)) 
ORDER BY a.[EnterTime] DESC) ftb
 
UNION ALL
 
SELECT  * from (SELECT TOP 10 a.[TrajectoryId], a.[VehicleId], a.[VehicleNumber], a.[ZoneId], a.[MasterId], a.[BaseId], a.[EnterTime], a.[VehicleDirection], a.[IsShow] 
FROM [VehicleTrajectory_202212] a 
INNER JOIN [Zone] b ON a.[ZoneId] = b.[ZoneId] 
INNER JOIN [MasterStation] c ON a.[MasterId] = c.[MasterId] 
INNER JOIN [BaseStation] d ON a.[BaseId] = d.[BaseId] 
INNER JOIN [Coordinate] e ON e.[DeviceType] = 0 AND e.[DeviceId] = a.[BaseId] AND e.[ZoneId] = a.[ZoneId] 
INNER JOIN [Vehicles] f ON f.[VehicleId] = a.[VehicleId] 
INNER JOIN [Department] g ON g.[DepartmentId] = f.[DepartmentId] 
WHERE (a.[EnterTime] >= cast(N'2022-10-24 11:06:14' as datetime)) AND (a.[EnterTime] <= cast(N'2023-02-24 11:06:14' as datetime)) 
ORDER BY a.[EnterTime] DESC) ftb
 
UNION ALL
 
SELECT  * from (SELECT TOP 10 a.[TrajectoryId], a.[VehicleId], a.[VehicleNumber], a.[ZoneId], a.[MasterId], a.[BaseId], a.[EnterTime], a.[VehicleDirection], a.[IsShow] 
FROM [VehicleTrajectory_202209] a 
INNER JOIN [Zone] b ON a.[ZoneId] = b.[ZoneId] 
INNER JOIN [MasterStation] c ON a.[MasterId] = c.[MasterId] 
INNER JOIN [BaseStation] d ON a.[BaseId] = d.[BaseId] 
INNER JOIN [Coordinate] e ON e.[DeviceType] = 0 AND e.[DeviceId] = a.[BaseId] AND e.[ZoneId] = a.[ZoneId] 
INNER JOIN [Vehicles] f ON f.[VehicleId] = a.[VehicleId] 
INNER JOIN [Department] g ON g.[DepartmentId] = f.[DepartmentId] 
WHERE (a.[EnterTime] >= cast(N'2022-10-24 11:06:14' as datetime)) AND (a.[EnterTime] <= cast(N'2023-02-24 11:06:14' as datetime)) 
ORDER BY a.[EnterTime] DESC) ftb
 
UNION ALL
 
SELECT  * from (SELECT TOP 10 a.[TrajectoryId], a.[VehicleId], a.[VehicleNumber], a.[ZoneId], a.[MasterId], a.[BaseId], a.[EnterTime], a.[VehicleDirection], a.[IsShow] 
FROM [VehicleTrajectory_202206] a 
INNER JOIN [Zone] b ON a.[ZoneId] = b.[ZoneId] 
INNER JOIN [MasterStation] c ON a.[MasterId] = c.[MasterId] 
INNER JOIN [BaseStation] d ON a.[BaseId] = d.[BaseId] 
INNER JOIN [Coordinate] e ON e.[DeviceType] = 0 AND e.[DeviceId] = a.[BaseId] AND e.[ZoneId] = a.[ZoneId] 
INNER JOIN [Vehicles] f ON f.[VehicleId] = a.[VehicleId] 
INNER JOIN [Department] g ON g.[DepartmentId] = f.[DepartmentId] 
WHERE (a.[EnterTime] >= cast(N'2022-10-24 11:06:14' as datetime)) AND (a.[EnterTime] <= cast(N'2023-02-24 11:06:14' as datetime)) 
ORDER BY a.[EnterTime] DESC) ftb

这个是tosql的语句

**Comment by lanfeirj** [comment]
语句在数据库种执行没问题  但是代码报错

**Comment by 2881099** [comment]
用 Aop.CommandBefore 监视 CommandText，定位报错的 SQL

**Comment by lanfeirj** [comment]
SELECT  * from (SELECT TOP 10 a.[VehicleId] as1, a.[VehicleNumber] as2, f.[VehicleName] as3, f.[DepartmentId] as4, g.[DepartmentName] as5, f.[VehicleType] as6, f.[DriverName] as7, a.[ZoneId] as8, b.[ZoneName] as9, a.[MasterId] as10, c.[MasterName] as11, a.[BaseId] as12, d.[BaseName] as13, a.[VehicleDirection] as14, a.[IsShow] as15, e.[CoordinateAxis] as16, a.[EnterTime] as17 
FROM [VehicleTrajectory_202206] a 
INNER JOIN [Zone] b ON a.[ZoneId] = b.[ZoneId] 
INNER JOIN [MasterStation] c ON a.[MasterId] = c.[MasterId] 
INNER JOIN [BaseStation] d ON a.[BaseId] = d.[BaseId] 
INNER JOIN [Coordinate] e ON e.[DeviceType] = 0 AND e.[DeviceId] = a.[BaseId] AND e.[ZoneId] = a.[ZoneId] 
INNER JOIN [Vehicles] f ON f.[VehicleId] = a.[VehicleId] 
INNER JOIN [Department] g ON g.[DepartmentId] = f.[DepartmentId] 
WHERE (a.[EnterTime] >= cast(N'2022-10-24 11:06:14' as datetime)) AND (a.[EnterTime] <= cast(N'2023-02-24 11:06:14' as datetime)) 
ORDER BY a.[EnterTime] DESC, a.[EnterTime] DESC, a.[EnterTime] DESC, a.[EnterTime] DESC, a.[EnterTime] DESC, a.[EnterTime] DESC) ftb

Aop.CommandBefore 监视 CommandText 里面显示 a.[EnterTime] 被定义了多个 这个是什么原因？ @2881099

**Comment by lanfeirj** [comment]
每个INNER JOIN 表都需要加个orderby排序字段？

**Comment by 2881099** [comment]
提供完整的实体类代码

**Comment by lanfeirj** [comment]
[Table(Name = "VehicleTrajectory_{yyyyMM}", AsTable = "EnterTime=2022-06-01(3 month)")]
    public class VehicleTrajectoryModel
    {
        [Column(IsIdentity = true, IsPrimary = true, IsNullable = false)]
        public long TrajectoryId { get; set; }

        [Column(DbType = "int NOT NULL")]
        public int VehicleId { get; set; }

        [Column(DbType = "varchar(50) NOT NULL")]
        public string VehicleNumber { get; set; }

        [Column(DbType = "int NOT NULL")]
        public int ZoneId { get; set; }

        [Column(DbType = "int NOT NULL")]
        public int MasterId { get; set; }

        [Column(DbType = "int NOT NULL")]
        public int BaseId { get; set; }

        [Column(DbType = "datetime NOT NULL")]
        public DateTime EnterTime { get; set; }

        [Column(DbType = "int NOT NULL")]
        public int VehicleDirection { get; set; }

        [Column(DbType = "bit NOT NULL")]
        public bool IsShow { get; set; }
    }

**Comment by 2881099** [comment]
是完整的实体类代码。

**Comment by 2881099** [comment]
暂时先关闭，提供完整代码再跟进回复。
