### ISSUE TITLE
SetSource根据主键生成的条件为空。

### ISSUE THREAD

**Issue by 981476460** [dotnetcore/FreeSql#1452]
#### 问题描述及重现代码：

SetSource根据主键生成的条件为空。

![image](https://user-images.githubusercontent.com/49896324/224200557-a272bb4a-ab40-4923-8b02-a867c53f7175.png)
![image](https://user-images.githubusercontent.com/49896324/224200586-79bc8fe1-282a-40f6-a1fb-04ddc104b7e5.png)
![image](https://user-images.githubusercontent.com/49896324/224200600-423e8e1a-3486-4734-aa9d-10fcdfee546f.png)

```c#
```

#### 数据库版本

3.2.685
#### 安装的Nuget包

![image](https://user-images.githubusercontent.com/49896324/224200115-cb66300a-4f21-4a94-9128-71cb1c76acef.png)

#### .net framework/. net core？ 及具体版本
.net core3.1  7.0

**Comment by 2881099** [comment]
原因是 model 实体类型没有定义 IsPrimary = true

SetSource 是根据 IsPrimary = true 进行附加 where 条件更新的。

出于安全考虑，与其报错，总比 update t set ... 更新全表（未知）的更稳当。

--------

你的情况，应该优先考虑 Set 或者 SetDto，SetDto 最新也是拼组 Set。

更新数据的文档都有讲解。

**Comment by 981476460** [comment]
![image](https://user-images.githubusercontent.com/49896324/224217673-2598869e-0f70-46de-bec2-0ee7ed88b53f.png)
实体明确了主键的IsPrimary

**Comment by 2881099** [comment]
还有问题可以提供测试 demo
