### ISSUE TITLE
二级缓存

### ISSUE THREAD

**Issue by sgf** [dotnetcore/FreeSql#1457]
#### Feature 特性
支持二级缓存功能

#### 简要描述原因
减少 频繁的但又不必要的，数据库查询请求
不具备使用Redis的条件。
1.硬件条件(没有足够的内存)
2.软件环境(只有windows客户机) 
3.预算问题(没有额外的投入给放Redis)

#### 使用场景
系统字典，系统热点基础数据查询。
不适合上Redis的各种场景，毕竟很多时候打鸟需要的是鸟枪，你非要上个大炮 不合适。

**Comment by 2881099** [comment]
业务层自己用动态代理技术实现
