### ISSUE TITLE
字典的更新和插入会报Incorrect integer value: 'false' for column

### ISSUE THREAD

**Issue by xuecat** [dotnetcore/FreeSql#1463]
#### 问题描述及重现代码：
mysql类型是tinyint

问题我知道，我自己插入报这个错我肯定能解决。
主要问题在于，我用freesql查询出来的row ，tinyint会自动转化成bool（查询我用的datatable返回的，我直接`GetFieldValue<object>()`就是bool）。然后我再拿着这个查询结果数据去更新就报错。Incorrect integer value: 'false' for column

请问要怎么解决才能正常更新？
如果让我自己转化的话，这样导致我不信任查询结果，每次查询完了都要自己转化一遍bool和byte才能更新。
```c#
// c# code
```

#### 数据库版本
10.7

#### 安装的Nuget包
最新版本的nuget3.2.687

#### .net framework/. net core？ 及具体版本
.netcore版本

**Comment by 2881099** [comment]
字典的操作信息有限，如果字典值是 bool，那么对应的映射为 Bit

NoneParameter(true) 时对应的 SQL 值是 1/0

NoneParameter(false) 时对应的值是 true/false，DbType 是 Bit

建议使用 .NonePrameter() 进行操作。
