### ISSUE TITLE
多线程下的BaseEntity.Update()方法偶尔出错，且后续都无法存储数据

### ISSUE THREAD

**Issue by cctczyg** [dotnetcore/FreeSql#1464]
#### 问题描述及重现代码：
一个物联网项目，最近接入设备突然增多，消息解析及数据存储用的是多线程，在调用继承于BaseEntity的设备实体数据xxxx.Update()时，偶尔会出现以下错误，并且出现错误后，后续执行的xxxx.Update()都无法存储数据，造成每次发布新版本程序时，实体类xxxx的数据都只停留在出错前的最后一次保存的数据，请大佬看看是什么问题。错误如下：

System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at FreeSql.DbSet`1.DbContextBatchUpdatePriv(EntityState[] ups, Boolean isLiveUpdate)
   at FreeSql.DbSet`1.DbContextBatchUpdateNow(EntityState[] ups)
   at lambda_method450(Closure , Object , Object[] )
   at FreeSql.DbContext.<>c__DisplayClass65_0.<FlushCommand>g__dbsetBatch|0(String method)
   at FreeSql.DbContext.<>c__DisplayClass65_0.<FlushCommand>g__funcUpdate|3(Boolean isLiveUpdate)
   at FreeSql.DbContext.FlushCommand()
   at FreeSql.RepositoryDbContext.SaveChanges()
   at FreeSql.BaseRepository`1.Update(TEntity entity)
   at FreeSql.BaseEntity`1.Update()

```c#
// c# code
xxxx.Update()
```

#### 数据库版本
Mysql5.7

#### 安装的Nuget包
FreeSql.Extensions.BaseEntity 2.5.200

#### .net framework/. net core？ 及具体版本
.net 5

**Comment by 2881099** [comment]
实体是查询出来，一直常驻内存的吗？

同一个实体类已经绑定的仓储，仓储不支持多个线程操作。

是否符合这个分析。解决办法，查询后再更新，或者取消仓储绑定，这样一来就不支持只修改 set 变化的属性了。

**Comment by cctczyg** [comment]
对，程序启动后，会查询所有设备数据，然后直接缓存了，为了方便查看所有设备的最后状态数据，所以把设备的最后状态数据存在一个字段里，设备上报数据后就只更新实体，这个程序已经正常运行两年多了，只是最近设备增加了一些，才会出现此故障，如果查询后再更新，这样实时性可能就没这么好了

**Comment by 2881099** [comment]
FreeSql.BaseEntity 每个实体对象都有 Repository 属性。

FreeSql.BaseEntity 单次查询的结果，会共享设置同一个 Repository 对象，而不是为每个实体对象都分配不同的 Repositoty，目的是为了节约内存。

主要原因是 Repositoty 不支持并发操作。

例如，var datas = Data.Select.ToList();

datas[0].Update()
datas[1].Update()

同时并发执行，就会造成 Repository 错误。

解决办法：

1. 更新加锁
2. 查询时特殊处理，不共享 Repository，var datas = Data.Select.NoTracking().ToList()

datas.FotEach(d => d.Attach());

**Comment by 2881099** [comment]
FreeSql.BaseEntity 每个实体对象都有 Repository 属性。

FreeSql.BaseEntity 单次查询的结果，会共享设置同一个 Repository 对象，而不是为每个实体对象都分配不同的 Repositoty，目的是为了节约内存。

主要原因是 Repositoty 不支持并发操作。

例如，var datas = Data.Select.ToList();

datas[0].Update()
datas[1].Update()

同时并发执行，就会造成 Repository 错误。这个问题有点深入，你可以按照我的分析测试一下。

解决办法：

1. 更新加锁
2. 查询时特殊处理，不共享 Repository，var datas = Data.Select.NoTracking().ToList()

datas.FotEach(d => d.Attach());

**Comment by cctczyg** [comment]
好的，谢谢大佬。另外咨询一下“XXXX.Orm.Update<XXXX>().Set(p => p.xxx, "zzz").Set(p => p.yyy, "aaa").ExecuteAffrows();”这个方法是线程安全的么？因为我的逻辑并不复杂，如果是线程安全的，我改一下调用方式好了。另外，对性能应该是没有影响的吧？

**Comment by 2881099** [comment]
XXXX.Orm 是否线程安全取决于 BaseEntity.Init 第二个参数工作单元的配置，如果没有配置则是安全的。

其实就是最终采用哪个 DbConnection 执行命令，DbConnection 线程是不安全的。

如果没有配置 BaseEntity.Init 第二个参数，.Orm 每次执行都会使用连接池 DbConnection，则没有安全问题。

**Comment by cctczyg** [comment]
好的，目前我初始化的第二个参数为null，BaseEntity.Initialization(fsql, null);我就先调整一下调用方式吧，谢了

**Comment by 9a6c** [comment]
BaseEntity 模式，如何多线程加锁呢？
目前尝试这样加锁，但是还是会出现错误。(使用ab 200并发压测Login，共2000次请求，有100多错误请求。 去掉数据库操作，0错误请求)
![image](https://github.com/dotnetcore/FreeSql/assets/51264840/6f8f44ff-81d6-4318-b0ad-0f9a69050455)
