### ISSUE TITLE
withsql 之后不能使用 WhereDynamicFilter

### ISSUE THREAD

**Issue by zscqin** [dotnetcore/FreeSql#1473]
```c#
Db.Select<object>().WithSql($"select * from {options.table_name}") .WhereDynamicFilter(filterInfo)
// c# code
```
![image](https://user-images.githubusercontent.com/18527382/227816786-606877eb-d002-4a5c-8b60-43cdfc1d3d27.png)

withsql 查询之后不能使用动态条件查询   例如查询  contract_no字段 会报错上面的提示

**Comment by 2881099** [comment]
WhereDynamicFilter 依赖实体类，你直接用 object 不行，或者使用 .AsType 指定

**Comment by 2881099** [comment]
如果不基于实体类型构建 where，那还不如直接拼 sql 呢。

基于实体类相当于验证属性名，不会输入不存在的字段，也不会注入sql。

**Comment by zscqin** [comment]
明白了 这种我拼sql吧
