### ISSUE TITLE
.NET Framework 最低支持到 4.6.2 了~~ 是不是可以升级一波依赖？

### ISSUE THREAD

**Issue by hyzx86** [dotnetcore/FreeSql#1478]
#### Feature 特性
![image](https://user-images.githubusercontent.com/15613121/229277015-8f2a8c4a-157e-450c-870a-11ede50e26bf.png)

**Comment by 2881099** [comment]
只是csproj问题而已，你可以修改一份net48的csproj管理源码

**Comment by hyzx86** [comment]
不太会搞。。要不出一波源码编译教程？ 🤣

**Comment by densen2014** [comment]
那就更没必要了。又不是不能用

**Comment by luoyunchong** [comment]
使用此方式安装 .NET Framework 4、和.NET Framework4.5
https://www.cnblogs.com/Stay627/p/15549958.html

https://github.com/MrXhh/VSTools/releases/tag/VS2022Net4NotCompileFix_v1.1.0

**Comment by densen2014** [comment]
问题是，net4.8照样能用freesql，这波操作是要干啥

**Comment by hyzx86** [comment]
用不是问题，改 是问题

**Comment by densen2014** [comment]
你都要改了，那就直接改csproj里面的4.x成你要的

**Comment by hyzx86** [comment]
🤣 要是还想提交到仓库呢？

**Comment by densen2014** [comment]
> 🤣 要是还想提交到仓库呢？

没必要！

**Comment by hyzx86** [comment]
> > 🤣 要是还想提交到仓库呢？
> 
> 没必要！

那是你以为。。.

**Comment by hyzx86** [comment]
> 使用此方式安装 .NET Framework 4、和.NET Framework4.5 https://www.cnblogs.com/Stay627/p/15549958.html
> 
> https://github.com/MrXhh/VSTools/releases/tag/VS2022Net4NotCompileFix_v1.1.0

感谢， 用第二种方式已解决
