### ISSUE TITLE
源码文件名的大小写问题

### ISSUE THREAD

**Issue by cuiwenyuan** [dotnetcore/FreeSql#1487]
#### 问题描述及重现代码：

```c#
// c# code
```
DatabaseModel目录下DBColumnInfo.cs和DBTableInfo.cs文件，文件名应该以Db为前缀。

**Comment by 2881099** [comment]
谢谢提醒，不合理肯定很多，再完美也会有缺陷。

我们尽力做到一次定义的机制，不轻易改变。

因为开源这么久，不确定有没有人依赖这些命名， 例如反射？

**Comment by cuiwenyuan** [comment]
重申一下是文件名，而不是类名。

**Comment by 2881099** [comment]
不好意思，没仔细看文字，谢谢反馈。
