### ISSUE TITLE
MySql Enum 类型插入不符合预期

### ISSUE THREAD

**Issue by DHclly** [dotnetcore/FreeSql#1495]
#### 问题描述及重现代码：
希望插入的预期值是 Private，结果数据库里面仍然是 Public，采用仓储模式的插入或更新数据

```c#

/// <summary>
    /// 地图类型
    /// </summary>
    public enum MapType : int
    {
        /// <summary>
        /// 公开
        /// </summary>
        Public= 1,
        /// <summary>
        /// 私有
        /// </summary>
        Private = 2
    }

var entity = new Map(){
MapType =MapType .Private 
};
await mapRepository.InsertOrUpdateAsync(entity );
```

#### 数据库版本

MySql 8.0.17

#### 安装的Nuget包

3.2.687

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by 2881099** [comment]
Public, Private

枚举不要定义数值，除非使用 Column MapType = typeof(int) 映射成 int

提示：mysql 默认支持枚举 enum 类型，FreeSql 默认映射的也是 enum，但是不支持 c# 枚举指定数值。

**Comment by 2881099** [comment]
也可以设置 Column MapType = typeof(string) 映射成 varchar

**Comment by 2881099** [comment]
issues 搜索 `mysql enum` 有相关的问题。

**Comment by DHclly** [comment]
> Public, Private
> 
> 枚举不要定义数值，除非使用 Column MapType = typeof(int) 映射成 int
> 
> 提示：mysql 默认支持枚举 enum 类型，FreeSql 默认映射的也是 enum，但是不支持 c# 枚举指定数值。

好的，感谢作者回复，原来是这样，我后面也是按照官网里面的aop.configEntity把枚举类型maptype指为int解决的，不过我看了下，既然mysql enum 支持的不是很友好，为何不和其他数据库一样，默认映射为int，配置后才才用enum？因为我发现偶尔还会被映射成set类型。

之前用Guid类型也是，映射后写入不对，后面把guid类型映射为string类型处理的

**Comment by 2881099** [comment]
如果 c# 枚举定义 成 [Flags] 就会映射成 mysql set

这个从一开始就这样映射了，其实匹配度还好只需要注意一点点。

过去做过很多项目，越到后期维护越能体会梦幻数字的痛苦，1代表什么，99代表什么，对于新加入的成员太不友好，因此比较偏向枚举的使用。

**Comment by DHclly** [comment]
> 如果 c# 枚举定义 成 [Flags] 就会映射成 mysql set
> 
> 这个从一开始就这样映射了，其实匹配度还好只需要注意一点点。
> 
> 过去做过很多项目，越到后期维护越能体会梦幻数字的痛苦，1代表什么，99代表什么，对于新加入的成员太不友好，因此比较偏向枚举的使用。

好吧，原来是加了[Flags]才变的，数据库字段确实全是数字很痛苦，但是目前因为枚举指定了数字导致**枚举无效**更头痛，因为枚举往往还需要进行位运算，所以指定数值是很正常的操作，如果要可读性，还是映射为varchar 类型好点，至于魔数问题，
目前不都是code first 么，模型上的注释写好也问题不大，除非对外对接
