### ISSUE TITLE
SqlServer 标识增量 和 标识种子

### ISSUE THREAD

**Issue by Wildcatii** [dotnetcore/FreeSql#1508]
#### Feature 特性
数据库：SqlServer
1.CodeFirst模式，自增列 Column 特性无法设置 标识增量  和  标识种子，因为有时候希望自增列从指定值开始递增
2.基于第1点，通过SSMS设定 自增列 标识增量  和  标识种子后，在使用自动分表 AsTable 时， 标识增量  和  标识种子 设定不会复制到分表
3.DBFirst模式，自增列 标识增量  和  标识种子 设定未映射到实体类，因为没有特性可用。
```c#
// c# code
```

#### 简要描述原因

```c#
// c# code
```

#### 使用场景

```c#
// c# code
```

**Comment by 2881099** [comment]
1. [Column(IsIdentity = true, DbType = "int identity(1000, 1)")]
2. 自动分表，不支持也不适合用自增，建议使用 Guid 或者 雪花id
3. DbFirst 模式，对于自增的增量和种子设置特性，没有意义，因为值来源于数据库，除非又使用实体进行创建新表

**Comment by Wildcatii** [comment]
明白了。感谢您的解惑。
