### ISSUE TITLE
希望能够将orm生成的脚本中将主键的值也进行参数化

### ISSUE THREAD

**Issue by yjqGitHub** [dotnetcore/FreeSql#1517]
####  当前orm生成的更新sql主键值不是参数化

![image](https://github.com/dotnetcore/FreeSql/assets/15052182/32e7b25a-ac12-4559-ac32-e4ad432ca869)

```c#
UPDATE `aaaa_log` SET `latest_login_time` = @p_0 WHERE (`id` = 2)
```
这里的`id=2`没有进行参数化

#### 实现sql去重

我们想要在开发或者测试环境根据 aop获取到生成的sql，判断数据库中是否有当前sql，如果没有则写入，如果有则跳过。但是目前情况相同的orm在主键不同的情况下就会产生多条，导致我们审计的时候获取到的sql就是多条，增加了我们审计的筛选功能。希望能够将主键这些也进行参数化。

**Comment by 2881099** [comment]
Update SetSource 涉及单条、多条更新

单条产生 where pk = 1

多条产生 where pk in (1,2,3,4...)，IN 无法参数化

-----

目前参数化功能

UseNoneCommandParameter 是 Insert/Update 参数化

UseGenerateCommandParameterWithLambda 是之后加的 Where lambda 参数化

-----

FreeSql 开源第5年，基本不做机制变动的更新，你的需求可能影响老用户体验，暂时还没想好怎么在当前版本做你这个需求。

如果有需要尝试源码解决业务问题，代码在 FreeSql/Internal/CommonUtils.cs WhereItems 方法，可以将 IUpdate\<T\> _params 成员传进来。PS：WhereItems 使用的地方只有几处。

例：

```c#
public string WhereItems<TEntity>(ColumnInfo[] primarys, string aliasAndDot, IEnumerable<TEntity> items, List<DbParameter> dbParms)
{
    if (items == null || items.Any() == false) return null;
    if (primarys.Any() == false) return null;
    var its = items.Where(a => a != null).ToArray();

    var pk1 = primarys.FirstOrDefault();
    if (primarys.Length == 1)
    {
        var indt = its.Select(a => pk1.GetDbValue(a)).Where(a => a != null).ToArray();
        if (indt.Any() == false) return null;
        var sbin = new StringBuilder();
        sbin.Append(aliasAndDot).Append(this.QuoteSqlName(pk1.Attribute.Name));
        var dbParm = AppendParamter(dbParms, null, pk1, pk1.CsType, indt.First());
        if (indt.Length == 1) sbin.Append(" = ").Append(dbParm);
        ....
```

**Comment by yjqGitHub** [comment]
好的 了解
