### ISSUE TITLE
WithTempQuery后再分页,  查询第一页之后的内容 会报ORA-00923

### ISSUE THREAD

**Issue by 516018579** [dotnetcore/FreeSql#1519]
#### 问题描述及重现代码：
_sql.Select<PLAF_POE>()
                .WithTempQuery(x => new { x.PlanOrder })
                .Page(2, 20)
                .ToSql()

生成的sql

SELECT t.* FROM (SELECT *, ROWNUM AS "__rownum__"
FROM (
    SELECT a."PLNUM" "PLANORDER"
    FROM "PLAF_POE" a ) a
WHERE ROWNUM < 41) t WHERE t."__rownum__" > 20

正确的sql应该是
SELECT t.* FROM (SELECT a.*, ROWNUM AS "__rownum__"
FROM (
    SELECT a."PLNUM" "PLANORDER"
    FROM "PLAF_POE" a ) a
WHERE ROWNUM < 41) t WHERE t."__rownum__" > 20

#### 数据库版本
oracle

#### 安装的Nuget包
FreeSql.Provider.Oracle

#### .net framework/. net core？ 及具体版本
.Net6

**Comment by 2881099** [comment]
已修复，等几分钟更新
