### ISSUE TITLE
如何插入一组不同模型的数据

### ISSUE THREAD

**Issue by pardont** [dotnetcore/FreeSql#153]
我有一个方法，批量插入一组不同模型的数据，比如items里面有类A和类B的两个实例，这种如何处理呢？我试过 fsql.Insert(item)，但是sql没办法正常生成列。

> public static void SaveData(IFreeSql fsql, List\<object\> items)
        {
        }
>

**Comment by 2881099** [comment]
List items 这个是什么

**Comment by 2881099** [comment]
object类型都是一样的吗？

**Comment by 2881099** [comment]
fsql.Insert\<object\>().AppendData(list).AsType(typeof(类型)).ExecuteAffrows()

弱类型可以这样插入，但是要求list里面的元素类型都一样，如果不一样，可以考虑先按type分组，list.ToDictionary(a=> a.GetType())，再循环使用上面的方法插入。

**Comment by pardont** [comment]
收到，方法适合使用，谢谢了

**Comment by pardont** [comment]
@2881099 
fsql.Insert<object>().AppendData(list).AsType(typeof(类型)).ExecuteAffrows() 
这个方法新版本不支持了啊，会报操作的数据类型和AsType的数据类型不一致。

**Comment by 2881099** [comment]
fsql.Insert().AsType(typeof(类型)). AppendData(list). ExecuteAffrows()

换个位置

**Comment by pardont** [comment]
非常棒，可以了，谢谢
