### ISSUE TITLE
实体对象为JObject时，执行ExecutePgCopyAsync时报错

### ISSUE THREAD

**Issue by arcchen** [dotnetcore/FreeSql#1532]
#### Feature 特性

```c#
实体：
	[JsonProperty, Column(Name = "value")]
		public JObject Value { get; set; }
```

 public async Task<List<T>> BatchInsertAsync(IEnumerable<T> entitys, int valuesLimit = 5000, int parameterLimit = 3000, bool enablePgCopy = false)
        {
            var iInsert = InsertDiy.AppendData(entitys).NoneParameter().BatchOptions(valuesLimit, parameterLimit);
            if (enablePgCopy)
                await iInsert.ExecutePgCopyAsync<T>();
            return await iInsert.ExecuteInsertedAsync();
        }

报错：System.NotSupportedException:“The CLR array type Newtonsoft.Json.Linq.JObject isn't supported by Npgsql or your PostgreSQL. If you wish to map it to a PostgreSQL composite type array you need to register it before usage, please refer to the documentation.

**Comment by 2881099** [comment]
直接用 ado.net 应该怎么处理

**Comment by arcchen** [comment]
[Table(Name = "tb_topic_insert_pgcopy")]
        class TopicPgCopy
        {
            [Column(IsIdentity = true, IsPrimary = true)]
            public int Id { get; set; }
            public int Clicks { get; set; }
            public TestTypeInfo Type { get; set; }
            public string Title { get; set; }
            public DateTime CreateTime { get; set; }
            public JObject Jb { get; set; }
        }

            var items = new List<TopicPgCopy>();
            for (var a = 0; a < 10; a++) items.Add(new TopicPgCopy { Id = maxId + a + 1, Title = $"newtitle{a}", Clicks = a * 100, CreateTime = DateTime.Now,Jb= JObject.Parse("{\"a\":1}") });

            g.pgsql.Insert(items).InsertIdentity().ExecutePgCopy();

报错行：
           copyFromCommand.Append(") FROM STDIN BINARY");
            using (var writer = conn.BeginBinaryImport(copyFromCommand.ToString()))
            {
                foreach (DataRow item in dt.Rows)
                {
                    writer.WriteRow(item.ItemArray);//报错行，npgsql 的写法是：writer.Write(myData.ClassID, NpgsqlDbType.Integer);
                }
                writer.Complete();
            }
            copyFromCommand.Clear();
        };


求大神修复一下

**Comment by 2881099** [comment]
更新一下 3.2.698-preview20230608

**Comment by arcchen** [comment]
谢谢😊
