### ISSUE TITLE
是否有AOT支持计划?

### ISSUE THREAD

**Issue by SmRiley** [dotnetcore/FreeSql#1533]
查阅了相关Issue,只看到在20年有过一个[相关提问](https://github.com/dotnetcore/FreeSql/issues/557#issue-748006258),但是现在.net8已经开始把asp.net core做aot支持,ef core 8.0中也有相关计划,请问下FreeSql后续会有相关AOT支持计划么?

**Comment by 2881099** [comment]
等成熟了在再考虑
