### ISSUE TITLE
生成的sql表的别名错乱了

### ISSUE THREAD

**Issue by caijie17780520163** [dotnetcore/FreeSql#1535]
var exp1 = () =>
            {
                return _fsql.Select<Mem_MultRelation>().Where(d => d.BranchId == request.BranchId);
            };
            var exp2 = () =>
            {
                return _fsql.Select<Mem_BranchRelation>().Where(e => _fsql.Select<Mem_MultRelation>().Where(d => d.BranchId == request.BranchId).Where(f => e.LevelId == f.LinkBranchId).Any());
            };
            var posStaticCount = async (long staticDate, Expression<Func<Pos_Machine, bool>> exp) =>
            {
                if (request.TeamType == TeamType.Team)
                {
                    exp = exp.And(a => (exp1().Where(b => b.LinkBranchId == a.BranchId && b.LinkMerchantId == a.MerchantId).Any() || exp2().Where(c => c.BranchId == a.BranchId && c.MerchantId == a.MerchantId).Any()));
                }
                else
                {
                    exp = exp.And(a => exp1().Where(c => c.LinkBranchId == a.BranchId&&c.MerchantId==a.MerchantId).Any());
                }

                var result = await _fsql.Select<Pos_Machine>().Where(exp).ToListAsync(a => new
                {
                    MachineNo = a.MachineNo,
                    Amount = _fsql.Select<Mch_BizTypeDayStatic>()
                      .Where(b => b.MachineNo == a.MachineNo && mids.Contains(b.MerchantId) && b.StaticDate >= staticDate).Sum(c => c.Amount)
                });
                return result.GroupBy(a => a.MachineNo);
            };

---以上是代码  
---以下是生成的sql

 SELECT a.[MachineNo] as1, isnull((SELECT sum(b.[Amount])
    FROM [Mch_BizTypeDayStatic] b
    WHERE (b.[MachineNo] = a.[MachineNo] AND ((b.[MerchantId]) in (10021)) AND b.[StaticDate] >= 20230416)), 0) as2
FROM [Pos_Machine] a
WHERE (a.[IsBind] = 1 AND (exists(SELECT TOP 1 1
    FROM [Mem_MultRelation] b
    WHERE (a.[BranchId] = '640000001000046') AND (b.[LinkBranchId] = a.[BranchId] AND b.[LinkMerchantId] = a.[MerchantId])) OR exists(SELECT TOP 1 1
    FROM [Mem_BranchRelation] c
    WHERE (exists(SELECT TOP 1 1
        FROM [Mem_MultRelation] d
        WHERE (d.[BranchId] = '640000001000046') AND (a.[LevelId] = d.[LinkBranchId]))) AND (c.[BranchId] = a.[BranchId] AND c.[MerchantId] = a.[MerchantId]))))
![image](https://github.com/dotnetcore/FreeSql/assets/12708456/47e53ddf-d0be-4e32-a4d0-a2ad75b8c2e5)

**Comment by 2881099** [comment]
```c#
        var exp1 = () =>
        {
            return _fsql.Select<Mem_MultRelation>().As("sub_d").Where(d => d.BranchId == request.BranchId);
        };
        var exp2 = () =>
        {
            return _fsql.Select<Mem_BranchRelation>().As("sub_e").Where(e => _fsql.Select<Mem_MultRelation>().Where(d => d.BranchId == request.BranchId).Where(f => e.LevelId == f.LinkBranchId).Any());
        };
```
