### ISSUE TITLE
多数据库实例如何同时使用

### ISSUE THREAD

**Issue by q315523275** [dotnetcore/FreeSql#154]
容器获取IList<IFreeSql>对象，然后选择对应的实例进行使用

**Comment by q315523275** [comment]
在创建IFreeSql对象Build()的时候是否可以传入实例名称,然后IFreeSql接口里增加实例名称值的获取

**Comment by 2881099** [comment]
可以的，收录在常见问题
https://github.com/2881099/FreeSql/wiki/%e5%b8%b8%e8%a7%81%e9%97%ae%e9%a2%98

**Comment by 2881099** [comment]
.Build\<TMark>

**Comment by landonzeng** [comment]
@q315523275 老大，FamilyBucket  准备用freesql了吗？欢迎欢迎啊，希望FamilyBucket中使用freesql，这样可以多些freesql的使用案例了

**Comment by landonzeng** [comment]
@q315523275 我这里有个多库连接的方法，和官方给的有点不同
NormalUnitOfWork.cs

`public class NormalUnitOfWork : IRepositoryUnitOfWork
    {
        private readonly IRepositoryUnitOfWork _uow;
        public NormalUnitOfWork(IFreeSqlFactory freeSqlFactory, string databaseName)
        {
            _uow = freeSqlFactory.GetFreeSql(databaseName).CreateUnitOfWork();
        }

        public void Dispose()
        {
            _uow.Dispose();
        }

        public DbTransaction GetOrBeginTransaction(bool isCreate = true)
        {
            return _uow.GetOrBeginTransaction(isCreate);
        }

        public void Commit()
        {
            _uow.Commit();
        }

        public void Rollback()
        {
            _uow.Rollback();
        }

        public void Close()
        {
            _uow.Close();
        }

        public void Open()
        {
            _uow.Open();
        }

        public IsolationLevel? IsolationLevel
        {
            get => _uow.IsolationLevel;
            set
            {
                if (value != null) _uow.IsolationLevel = value;
            }
        }

        public bool Enable => _uow.Enable;

        public DbContext.EntityChangeReport EntityChangeReport =>  _uow.EntityChangeReport;

        public DefaultRepository<TEntity, TKey> GetRepository<TEntity, TKey>(Expression<Func<TEntity, bool>> filter = null) where TEntity : class
        {
            return _uow.GetRepository<TEntity, TKey>(filter);
        }

        public BaseRepository<TEntity> GetRepository<TEntity>(Expression<Func<TEntity, bool>> filter = null) where TEntity : class
        {
            return _uow.GetRepository<TEntity>(filter);
        }

        public GuidRepository<TEntity> GetGuidRepository<TEntity>(Expression<Func<TEntity, bool>> filter = null, Func<string, string> asTable = null) where TEntity : class
        {
            return _uow.GetGuidRepository<TEntity>(filter, asTable);
        }
    }`

FreeSqlCollections.cs
`public class FreeSqlCollections
    {
        public List<FreeSqlItem> FreSqls { get; set; } = new List<FreeSqlItem>();
    }
    /// <summary>
    /// FreeSql项
    /// </summary>
    public class FreeSqlItem
    {
        public FreeSqlItem()
        {
        }

        public FreeSqlItem(FreeSqlConfig config, ILogger<IFreeSql> log)
        {
            this.DataBase = config.DataTableName;
            var freeBuilder = new FreeSqlBuilder()
                .UseConnectionString(config.DataType, config.MasterConnetion)
                .UseLazyLoading(true)
                .UseAutoSyncStructure(config.IsSyncStructure)
                .UseMonitorCommand(
                    executing =>
                    {
                        executing.CommandTimeout = 6000;
                        //执行中打印日志
                        //log.LogInformation(executing.CommandText);
                        Console.WriteLine(executing.CommandText);
                        for (int i = 0; i < executing.Parameters.Count; i++)
                        {
                            Console.WriteLine($"{executing.Parameters[i].ParameterName}:{executing.Parameters[i].Value}");
                        }


                    }
                );
            if (config.SlaveConnections?.Count > 0)//判断是否存在从库
            {
                freeBuilder.UseSlave(config.SlaveConnections.Select(x => x.ConnectionString).ToArray());
            }

            this.FreeSql = freeBuilder.Build();
            this.FreeSql.SetDbContextOptions(opt => opt.EnableAddOrUpdateNavigateList = false);
        }
        /// <summary>
        /// 数据库名称
        /// </summary>
        public string DataBase { get; set; }
        /// <summary>
        /// 对应的FreeSql 
        /// </summary>
        public IFreeSql FreeSql { get; set; }

    }`

FreeSqlFactory.cs

`public class FreeSqlFactory : IFreeSqlFactory
    {
        /// <summary>
        /// FreeSql集合
        /// </summary>
        private readonly FreeSqlCollections _freeSqls;
        /// <summary>
        /// 从构造函数获取FreeSql集合
        /// </summary>
        /// <param name="freeSqls"></param>
        public FreeSqlFactory(FreeSqlCollections freeSqls)
        {
            _freeSqls = freeSqls ?? throw new ArgumentNullException("FreeSql集合尚未注入");
        }

        /// <summary>
        /// 获取FreeSql 通过数据库名称
        /// </summary>
        /// <param name="databaseName"></param>
        /// <returns></returns>
        public IFreeSql GetFreeSql(string databaseName)
        {
            return _freeSqls.FreSqls.FirstOrDefault(x => x.DataBase == databaseName)?.FreeSql ?? throw new NullReferenceException($"数据库{databaseName} 不存在 或未注入");
        }
    }
    /// <summary>
    /// FreeSql工厂类
    /// </summary>
    public interface IFreeSqlFactory
    {
        IFreeSql GetFreeSql(string databaseName);
    }`

**Comment by q315523275** [comment]
@landonzeng 感谢，我参考参考

**Comment by landonzeng** [comment]
@q315523275 客气了，只是我这个会破坏传统的仓储模式，不需要创建IRepository和Repository，只要IServices和Services就可以了，有点怪异
