### ISSUE TITLE
Is there any EFCore - HasConversion alternative?

### ISSUE THREAD

**Issue by james655360** [dotnetcore/FreeSql#1544]
hi,
thank you for this fantastic library.
Is there any way to use similar function of EFCore property.HasConvertion?
I'm planning to use Value Object type variables ([ValueOf](https://github.com/mcintyre321/ValueOf), [Vogen](https://github.com/SteveDunn/Vogen), [StronlyTypedID](https://github.com/andrewlock/StronglyTypedId) etc) for my next project.
I have already tried some code AOP ConfigEntity, ConfigEntityProperty, AuditDataReader but didn't make it :(
thanks for your help

**Comment by 2881099** [comment]
see doc: [Column(MapType= typeof(string)]

(HasConvertion) not implement.

**Comment by 2881099** [comment]
```csharp
FreeSql.Internal.Utils.TypeHandlers.TryAdd(typeof(JsonClass), new String_JsonClass());

class Product
{
    public Guid id { get; set; }
    [Column(MapType = typeof(string), StringLength = -1)]
    public JsonClass json { get; set; }
}

class JsonClass
{
    public int a { get; set; }
    public int b { get; set; }
}
class String_JsonClass : TypeHandler<JsonClass>
{
    public override object Serialize(JsonClass value) => JsonConvert.SerializeObject(value);
    public override JsonClass Deserialize(object value) => JsonConvert.DeserializeObject<JsonClass>((string)value);
}
```
