### ISSUE TITLE
DBFirst模式下，string字段可空性配置

### ISSUE THREAD

**Issue by Wildcatii** [dotnetcore/FreeSql#1547]
#### Feature 特性
DB First模式，  字符串类型的可空字段生成实体类，比如下面生成的Name属性：
```c#
public string Name{ get; set; }
```
希望通过生成器的配置项能生成如下Name属性：
```c#
public string? Name{ get; set; }
```
差异就是string带不带问号。
#### 简要描述原因
如果可空string不带问号，通过api提交的json中未提供Name属性时，会报错 “The Name field is required.”.
如果可空string带了问号，就不会报错了. 虽然string本身是引用类型，是可空的。
但目前根据我的理解，string 是否带问号在C#语义里面，是这个字段是否必须要有值。vs的波浪线提示应该可以印证这一点。
![string_null](https://github.com/dotnetcore/FreeSql/assets/23210705/5e642da9-6280-4404-b32a-d33a95b91528)
目前的解决办法：
1.根据数据库字符串字段的可空性，手动调整生成的实体类。
2.services.AddControllers(options => options.SuppressImplicitRequiredAttributeForNonNullableReferenceTypes = true);
方法1体力活，如果能用生成器来干就好了。
方法2不完美，会让数据不够安全或者不够完整，方法2也是微软官方的处理方式，参考官方  
 issue   https://github.com/dotnet/aspnetcore/issues/18403,  所以官方的这个issue 另外一个解决方式就是给接口参数language的类型string加?  
#### 使用场景
webapi 提交数据

**Comment by 2881099** [comment]
这个根据 FrreSql.Generator 模板修改一下就可以了

在生成后的目录下，修改 __razor.cshtml 文件

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/discussions/1580
