### ISSUE TITLE
支持国产数据库达梦吗？有test案例吗？

### ISSUE THREAD

**Issue by tonglei2019** [dotnetcore/FreeSql#155]
辛苦大神了。

**Comment by tonglei2019** [comment]
和其他数据库使用有什么区别吗？

**Comment by 2881099** [comment]
支持，单元测试有300多个针对达梦得。

**Comment by 2881099** [comment]
> 和其他数据库使用有什么区别吗？

orm 使用习惯，和其他数据库一样

**Comment by tonglei2019** [comment]
{DM8 ODBC Driver} 专用访问实现   兼容DM7吗

**Comment by 2881099** [comment]
> {DM8 ODBC Driver} 专用访问实现 兼容DM7吗

要再安装 dm7 的odbc 驱动，这里的配置换成对应的

**Comment by tonglei2019** [comment]
@2881099    再哪配置啊？

**Comment by 2881099** [comment]
https://www.cnblogs.com/kellynic/p/12034995.html

看这个

**Comment by tonglei2019** [comment]
@2881099 辛苦大神了，我先研究研究

**Comment by tonglei2019** [comment]
大神，为什么我使用orm提示我找不到表名呢，我看查询语句前面没有加达梦的模式名称啊

**Comment by 2881099** [comment]
表不是 user id 创建的对吧？

解决方法1（单个加）：

``csharp
[Table("xxx.tablename")]
class Table {
   //....
}
```

解决方法2（统一加 schema)：

``csharp
IFreeSql fsql = ...; //假设已经定义好了 IFreeSql 对象

//执行一次
g.mysql.Aop.ConfigEntity += new EventHandler<Aop.ConfigEntityEventArgs>((_, e) =>
{
    e.ModifyResult.Name = "模式名." + e.EntityType.Name;
});
```

**Comment by tonglei2019** [comment]
嗯好了，辛苦大神了

**Comment by tonglei2019** [comment]
大神在问个问题啊  ，使用DmConnection提示：用户名或密码错误   ,   连接字符串Data Source=ip+端口;User ID=用户名;Password=密码;  这个是什么问题啊

**Comment by tonglei2019** [comment]
我用你的orm就没问题

**Comment by 2881099** [comment]
这是 ado.net 在连接吗？不清楚，我只能用 odbc 连

**Comment by fayuanliu** [comment]
FreeSql  能拿到  DbConnection么？叶老板

**Comment by 2881099** [comment]
@fayuanliu 可以拿
```csharp
using (var item = fsql.Ado.MasterPool.Get()) {
  DbConnection conn = item.Value;
  //最好 using 包着用，这样保证归还
}
```

**Comment by fayuanliu** [comment]
3Q，我试试

**Comment by tonglei2019** [comment]
大神 orm框架支持连接两个sqlserver数据库吗，支持的话我再注入后怎么知道我添加的是哪个库的数据呢？

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/issues/44 @tonglei2019

**Comment by tonglei2019** [comment]
感谢大神

**Comment by pjy612** [comment]
> 大神 orm框架支持连接两个sqlserver数据库吗，支持的话我再注入后怎么知道我添加的是哪个库的数据呢？

也可以试试 https://github.com/2881099/FreeSql/issues/33

**Comment by tonglei2019** [comment]
谢谢 ，
大神现在用orm，有人把数据库命名为：testV1.0   这样了，框架提示找不到  数据库 testV1   把后面得
.0 给删除掉了，这个怎么办啊？ 还有我没有修改数据库名称得权限。

**Comment by 2881099** [comment]
testV1.0 中间的点，和 schema.table 格式有冲突 @tonglei2019

**Comment by tonglei2019** [comment]
@2881099  【主库】状态不可用，等待后台检查程序恢复方可使用  什么问题呢

**Comment by 2881099** [comment]
@tonglei2019  如果网通没问题，大概率是连接串不对
