### ISSUE TITLE
在高并发下出现 An item with the same key has already been added

### ISSUE THREAD

**Issue by jakey188** [dotnetcore/FreeSql#1555]
System.ArgumentException: An item with the same key has already been added. Key: XXXXEntity
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at FreeSql.RepositoryDbContext.Set(Type entityType)
   at FreeSql.DbContext.Set[TEntity]()
   at FreeSql.BaseRepository`1.get__dbset()
   at FreeSql.BaseRepository`1.get_Select()

#### 问题描述及重现代码：

```c#
await XXX.Where(XXX).FirstAsync(cancellationToken);
```

#### 安装的Nuget包
FreeSql.Provider.MySqlConnector  3.2.693
FreeSql.DbContext 3.2.693

#### .net framework/. net core？ 及具体版本
net6

**Comment by 2881099** [comment]
仓储对象，不支持并发操作的，线程不安全。

除了 IFreeSql，其他都没有说过线程安全

**Comment by jakey188** [comment]
这里的并发操作是指压测接口,只是用到了仓储。

**Comment by jakey188** [comment]
> 仓储对象，不支持并发操作的，线程不安全。
> 
> 除了 IFreeSql，其他都没有说过线程安全

感谢您的回复,这里说明一下：
这里的并发操作是指压测接口,只是用到了仓储。

**Comment by 2881099** [comment]
这不就说明你的仓储不是 scoped 注入么

**Comment by jakey188** [comment]
> 这不就说明你的仓储不是 scoped 注入么

仓储是scoped注入的

**Comment by 2881099** [comment]
都加了 await 吗？

**Comment by jakey188** [comment]
> 都加了 await 吗？

确定都加了的

**Comment by 2881099** [comment]
项目发上来

**Comment by jakey188** [comment]
> 项目发上来


代码是在项目中出现的,我单独搞个项目,压测下尽量复现线上的场景,晚点再发上来.

**Comment by 2881099** [comment]
从堆栈看，是多线程使用了同一个 repository 导致的。

**Comment by jakey188** [comment]
> 从堆栈看，是多线程使用了同一个 repository 导致的。

后面没有复现出来了,我们对freesql又封装了很多,我再检查下代码.

**Comment by DHclly** [comment]
> 从堆栈看，是多线程使用了同一个 repository 导致的。

问一下，因为我看官方文档写的是仓储不支持多线程操作，但是实际过程中，就算每个异步方法都有await，但是执行当前task的thread（比如 task.delay(1000)后再await 剩下task,在当前task和await的下一个task里面threadid都不是同一个）都可能会变，这会有影响么，freesql也是scope注入的

**Comment by 2881099** [comment]
> > 从堆栈看，是多线程使用了同一个 repository 导致的。
> 
> 问一下，因为我看官方文档写的是仓储不支持多线程操作，但是实际过程中，就算每个异步方法都有await，但是执行当前task的thread（比如 task.delay(1000)后再await 剩下task,在当前task和await的下一个task里面threadid都不是同一个）都可能会变，这会有影响么，freesql也是scope注入的

你描述的使用没有问题。

任何对象都可以多线程操作，只是不能多线程同时操作，过去没有异步咱们不是还用过 lock 避免同时操作的问题么。

异步加上了 await 可以认为执行过程在等他完成，提醒异步不加 await 其实蛮危险，web 项目可能造成数据库链接池瘫痪。

最后，IFreeSql 是没有必要 Scoped 注入的，因为 IFreeSql 本身是单例设计，多线程并发是安全的。

**Comment by 2881099** [comment]
@DHclly 一般adonet都有链接池功能，理论上是你说的这种效果。

FreeSql有一下几种方式：

1. UseConnectionString 默认声明是FreeSql自己的链接池，可以用 Ado.MasterPool 查看使用情况，你所描述的是对的，这种方式确实不会主动清理长时间不是使用的连接。max pool size是池的最大上限，至于你说这些连接占用多少内存，我的回答是不会太大，浪费是有一点，但是既然有这么大的并发，随时候着也没什么问题。

缺点：浪费数据库服务器的连接数


2. UseConnectionFactory 自己传入对应的 DbConnection 对象，如下：

new FreeSqlBuilder()
.UseConnectionFactory(DataType.MySql, () => new MySqlConnection(str))

这种方式相当于直接用adonet，链接池是adonet自己的规则，和直接使用adonet效果一样，可以满足你的想法。


3. v3.2.697 增加了 UseAdoConnectionPool(true)，如下：

new FreeSqlBuilder()
.UseConnectionString(DataType.MySql, str)
.UseAdoConnectionPool(true)


你可能疑问为什么有这么多用法。

第一种是最早期的，解决多种数据库驱动，应该是实现不统一的情况，同时也可以亲测连接使用情况。

第二种是为了实现外部传入DbConnection，甚至可以是 odbc/oledb，ssh 连接 mysql，还实现了类似 dapper 的使用方式，在 ado 文档中有介绍。

第三种是为了解惑一些人，对第一种连接池技术有疑问的情况。
