### ISSUE TITLE
连接mysql，始终报错连接超时

### ISSUE THREAD

**Issue by makyo5** [dotnetcore/FreeSql#156]
已经下载相应provider。但是连接了就超时。
不是很懂是怎么的？
换了一个sqlsugercore，可以连接没有问题。
[
<img width="708" alt="Screen Shot 2019-12-13 at 8 28 49 PM" src="https://user-images.githubusercontent.com/16131127/70800572-87ba3600-1de7-11ea-80cb-7cbcd652f3ca.png">
<img width="721" alt="Screen Shot 2019-12-13 at 8 29 53 PM" src="https://user-images.githubusercontent.com/16131127/70800577-88eb6300-1de7-11ea-81f1-47d73424e5a8.png">

](url)

**Comment by makyo5** [comment]
另外问问，我这样写，符合使用规范吗？？？？

**Comment by 2881099** [comment]
看不到图片，

DataType | ConnectionString
-- | --
DataType.MySql | Data Source=127.0.0.1;Port=3306;User ID=root;Password=root; Initial Catalog=cccddd;Charset=utf8; SslMode=none;Min pool size=1

用这个连接串试试呢，连接不上的提示是什么？

**Comment by pjy612** [comment]
实在不行用 MySqlConnectionStringBuilder 构建一个连接字符串比较靠谱

**Comment by 2881099** [comment]
问题解决了吗？

**Comment by makyo5** [comment]
<img width="708" alt="Screen Shot 2019-12-13 at 8 28 49 PM" src="https://user-images.githubusercontent.com/16131127/70848093-85b7ac00-1ea7-11ea-8cff-6f0fbeb6d85d.png">
<img width="721" alt="Screen Shot 2019-12-13 at 8 29 53 PM" src="https://user-images.githubusercontent.com/16131127/70848095-88b29c80-1ea7-11ea-921c-933a6d36c6de.png">

**Comment by makyo5** [comment]
问题没有解决，我就是用的官文档提供的连接字符串。

Data Source=127.0.0.1;Port=3306;User ID=root;Password=root; Initial Catalog=cccddd;Charset=utf8; SslMode=none;Min pool size=1

我是mariadb 10.4.10

**Comment by 2881099** [comment]
我看到连接串上有换行，把换行去掉试试。
我们有两个 Provider，分别是 FreeSql.Provider.MySql 和 FreeSql.Provider.MySqlConnector 这两个也都试下。

再不行，加我QQ 2881099，我们远程桌面

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/70848510-aa168700-1ead-11ea-9577-d6f5b2d25f99.png)

![image](https://user-images.githubusercontent.com/16286519/70848513-b13d9500-1ead-11ea-9739-28a068a7d842.png)

**Comment by 2881099** [comment]
刚才下载了一个 mariadb 10.4.11 ，连接测试正常

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/70848531-f06be600-1ead-11ea-895c-f34146385b92.png)

这两个是运行测试后，自动创建的表

**Comment by makyo5** [comment]
奇怪了。。。。难道和mac有关系？。。。再搞一下看。第一次遇到这种情况。
