### ISSUE TITLE
ExecutePgCopy报错

### ISSUE THREAD

**Issue by zhj11226** [dotnetcore/FreeSql#1560]
1、Insert一个DataTable，但ExecutePgCopy不支持，源码中有 that.ToDataTable() 函数，应该只需要在 ToDataTable 里判断一下，如果Insert传入的本来就是DataTable就直接返回该DataTable即可。
```c#
var dt = new DataTable();
dt.Columns.Add("a");
var dr = dt.NewRow();
dr["a"] = 1;
dt.Rows.Add(dr);

freesql.Insert(dt).AsTable("test").ExecutePgCopy();
```
2、Insert一个匿名类列表，但ExecutePgCopy不支持
```c#
var lst = (from r in dt.AsEnumerable()
           select new
           {
               cmd_id = r["a"].ToString()
           }).ToList();
freesql.Insert(lst ).AsTable("test").ExecutePgCopy();
```

**Comment by luoyunchong** [comment]
正常是使用实体

```cs
List<Department> departments = new List<Department>()
{
    new Department() { Id=1, Name ="部门1"},
    new Department() { Id=2, Name ="部门2"},
    new Department() { Id=3, Name ="部门3"}
};
fsql.Insert(departments)
    .ExecutePgCopy();
```

**Comment by zhj11226** [comment]
可能某些场景需要从oracle批量复制到pg？还有些场景需要从数据库或接口报文的json字段中，动态提取字段，不能直接定义实体？我们是一个中间系统，南向北向都有不同的厂家对接，考虑到后期扩展性，字段不唯一，所以新场景来了，我只需要按接口文档，数据库里加表加字段就行了，程序一行代码都不用改，我扩展了
`
var dt2 = (from r in dt.AsEnumerable()
                       select new
                       {
                           cmd_id = r["cmd_id"].ToString()
                       }).ToList();

            db.Ado.Transaction(() =>
            {
                var tran = db.Ado.TransactionCurrentThread;

                db.Ado.CommandFluent("""
                    create temp table aaa ("CMD_ID" varchar(100), b varchar(100)) on commit drop;
                    """).WithTransaction(tran).ExecuteNonQuery();

                db.GetPgCopyer(dt2).AsTable("aaa")
                    .InsertColumns(x => new { x.cmd_id })
                    .InsertColumns(x => new { x.cmd_id })
                    .InsertMapping(new PgMapping() { { "cmd_id", "\"CMD_ID\"" },{ "cmd_id", "b" } })
                    .WithTran(tran).DoCopy();

                //db.Insert(dt).InsertColumns().WithTransaction(tran).ExecutePgCopy();  //报错

                var ret = db.Ado.CommandFluent("""
                    select * from aaa;
                    """).WithTransaction(tran).ExecuteDataTable();

                Console.WriteLine(ret.Rows.Count);
                Console.WriteLine($"{ret.Rows[0]["CMD_ID"]} , {ret.Rows[0]["b"]}");
            });
`

`
    public class FreeSqlPgCopy<T>: FreeSqlPgCopy
    {
        private IEnumerable<T> rows;

        public FreeSqlPgCopy(IFreeSql fs, IEnumerable<T> rows) : base(fs, new DataTable(), typeof(T).Name)
        {
            this.rows = rows;

            foreach (var f in typeof(T).GetFields())
            {
                dt.Columns.Add(f.Name, f.FieldType);
            }
            foreach (var p in typeof(T).GetProperties())
            {
                dt.Columns.Add(p.Name, p.PropertyType);
            }
            foreach (T o in rows)
            {
                var row = dt.NewRow();
                foreach (var f in typeof(T).GetFields())
                {
                    row[f.Name] = f.GetValue(o);
                }
                foreach (var p in typeof(T).GetProperties())
                {
                    row[p.Name] = p.GetValue(o);
                }
                dt.Rows.Add(row);
            }
        }

        public FreeSqlPgCopy<T> AsTable(string tbName)
        {
            this.tbName = tbName;
            return this;
        }
        /// <summary>
        /// x=>new { x.f1, x.f2 }
        /// </summary>
        /// <param name="columns"></param>
        /// <returns></returns>
        public FreeSqlPgCopy<T> InsertColumns(Expression<Func<T, object>> columns)
        {
            if (rows.Any())
            {
                var TR = columns.Compile().Invoke(rows.FirstOrDefault()).GetType();
                foreach (var p in TR.GetProperties())
                {
                    if (dt.Columns.Contains(p.Name)) fields.Add(p.Name);
                }
            }
            return this;
        }
    }

    public class PgMapping : Dictionary<string, List<string>>
    {
        public void Add(string key, string val)
        {
            if (this.ContainsKey(key))
            {
                this[key].Add(val);
            }
            else this.Add(key, new List<string>() { val });
        }
        public void Add(string key, string[] val)
        {
            if (this.ContainsKey(key))
            {
                this[key].AddRange(val);
            }
            else this.Add(key, val.ToList());
        }

        public List<string> GetMappingFields(List<string> fields)
        {
            var remoteFields = new HashSet<string>();
            Dictionary<string, int> rCnt = new Dictionary<string, int>();
            foreach (var f in fields)
            {
                if (this.ContainsKey(f))
                {
                    if (!rCnt.ContainsKey(f))
                    {
                        remoteFields.Add(this[f][0]);
                        rCnt.Add(f, 0);
                    }
                    else
                    {
                        var idx = rCnt[f] + 1;
                        if (this[f].Count > idx)
                        {
                            remoteFields.Add(this[f][idx]);
                            rCnt[f] = idx;
                        }
                        else
                        {
                            remoteFields.Add(f);
                        }
                    }
                }
                else remoteFields.Add(f);
            }
            return remoteFields.ToList();
        }
    }

    public class FreeSqlPgCopy
    {
        protected readonly IFreeSql fs;
        protected readonly DataTable dt;
        protected string tbName;
        protected List<string> fields = new List<string>();
        NpgsqlConnection conn;
        PgMapping mapping = new();

        public FreeSqlPgCopy(IFreeSql fs, DataTable dt, string tbName)
        {
            this.fs = fs;
            this.dt = dt;
            this.tbName = tbName;
            this.conn = (NpgsqlConnection)fs.Ado.MasterPool.Get().Value;
        }

        public FreeSqlPgCopy WithTran(IDbTransaction tran)
        {
            conn = ((NpgsqlTransaction)tran).Connection;
            return this;
        }

        /// <summary>
        /// 允许重复，比如说 ["a","a"]，用于一个本地字段要导入多个远程字段的情况
        /// </summary>
        /// <param name="columns">本地字段名称列表</param>
        /// <returns></returns>
        public FreeSqlPgCopy InsertColumns(string[] columns)
        {
            foreach (var f in columns)
            {
                if (dt.Columns.Contains(f)) fields.Add(f);
            }
            return this;
        }

        /// <summary>
        /// key=本地字段名称,value=远程字段名称
        /// </summary>
        /// <param name="mapping"></param>
        /// <returns></returns>
        public FreeSqlPgCopy InsertMapping(PgMapping mapping)
        {
            if (mapping != null)
            {
                foreach (var p in mapping)
                {
                    if (dt.Columns.Contains(p.Key))
                    {
                        if (!this.mapping.ContainsKey(p.Key))
                        {
                            this.mapping.Add(p.Key, p.Value.ToList());
                        }
                        else
                        {
                            this.mapping[p.Key].AddRange(p.Value);
                        }
                    }
                }
            }

            return this;
        }


        public virtual void DoCopy()
        {
            if (dt.Rows.Count == 0) return;

            if (fields.Count == 0)
            {
                fields = dt.Columns.Cast<DataColumn>()
                                .Select(column => column.ColumnName)
                                .ToList();
            }

            #region 本地字段，可能对应多个远程字段
            var remoteFields = mapping.GetMappingFields(fields);
            #endregion

            var cf = fs.CodeFirst;

            string copyFromCommand = $"COPY {tbName} ({string.Join(",", remoteFields)}) FROM STDIN BINARY";

            using (var writer = conn.BeginBinaryImport(copyFromCommand))
            {
                foreach (DataRow item in dt.Rows)
                {
                    writer.StartRow();
                    foreach (string colName in fields)
                    {
                        NpgsqlDbType? npgsqlDbType = null;
                        var trycol = dt.Columns[colName];
                        var tp = cf.GetDbInfo(trycol.DataType)?.type;
                        if (tp != null) npgsqlDbType = (NpgsqlDbType)tp.Value;
                        if (npgsqlDbType.HasValue && npgsqlDbType != NpgsqlDbType.Unknown)
                            writer.Write(item[colName], npgsqlDbType.Value);
                        else
                            writer.Write(item[colName]);
                    }
                }
                try
                {
                    writer.Complete();
                }
                catch {
                    throw new Exception("08P01: 信息中剩下的数据不够（有可能是DataTable和数据库中的table字段类型不一致！）");
                }
            }

        }
    }

    public static class FreeSqlPgCopyExt
    {
        public static FreeSqlPgCopy GetPgCopyer(this IFreeSql fs, DataTable dt, string tbName)
        {
            return new FreeSqlPgCopy(fs, dt, tbName);
        }
        public static FreeSqlPgCopy<T> GetPgCopyer<T>(this IFreeSql fs, IEnumerable<T> rows)
        {
            return new FreeSqlPgCopy<T>(fs, rows);
        }
    }
`
