### ISSUE TITLE
UnitOfWork 使用 Select...ToUpdate 不受事务控制

### ISSUE THREAD

**Issue by Jess-Qiu** [dotnetcore/FreeSql#1562]
#### 问题描述及重现代码：
使用 Uow 执行 Select...ToUpdate 的方式进行更新操作不受 Uow 控制

```c#
var uow = freesql.CreateUnitOfWork();
try
{
    var key = "创建实体";

    await uow.Orm.Select<UowTable>()
        .Where(x => x.Message == key)
        .ToUpdate()
        .WithTransaction(uow.GetOrBeginTransaction())  // 需要手动指定 Transaction 方式才能回滚
        .Set(e => e.Message, "更新实体")
        .Set(e => e.ActionTime, DateTime.Now)
        .ExecuteAffrowsAsync();

    throw new Exception("取消更新操作");

    uow.Commit();

}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
    uow.Rollback();
}
```

**Comment by 2881099** [comment]
这个原因是 uow 默认 select 不开事务导致的，比如下面这样就没问题：

> 下个版本将优化

```c#
using (var uow = freesql.CreateUnitOfWork())
{
   uow.GetOrBeginTransaction();
   await uow.Orm.Select<UowTable>()
        .Where(x => x.Message == key)
        .ToUpdate()
        .WithTransaction(uow.GetOrBeginTransaction())  // 需要手动指定 Transaction 方式才能回滚
        .Set(e => e.Message, "更新实体")
        .Set(e => e.ActionTime, DateTime.Now)
        .ExecuteAffrowsAsync();

    uow.Commit();
}
```

另外还请注意，uow 尽量用 using 的方法来使用。

**Comment by Haale** [comment]
> 这个原因是 uow 默认 select 不创建事务导致的（只用事务，不创建事务），比如下面这样就没问题：
> 
> > 下个版本将优化
> 
> ```cs
> using (var uow = freesql.CreateUnitOfWork())
> {
>    uow.GetOrBeginTransaction();
>    await uow.Orm.Select<UowTable>()
>         .Where(x => x.Message == key)
>         .ToUpdate()
>         .WithTransaction(uow.GetOrBeginTransaction())  // 需要手动指定 Transaction 方式才能回滚
>         .Set(e => e.Message, "更新实体")
>         .Set(e => e.ActionTime, DateTime.Now)
>         .ExecuteAffrowsAsync();
> 
>     uow.Commit();
> }
> ```
> 
> 另外还请注意，uow 尽量用 using 的方法来使用。

使用using语句怎么在出现异常时回滚？难道离开using语句能自动回滚？？？！

**Comment by 2881099** [comment]
是的，若无commit，dispose将rollback
