### ISSUE TITLE
公开Connection 对象或当前链接的 Transaction 对象

### ISSUE THREAD

**Issue by hyzx86** [dotnetcore/FreeSql#1563]
部分场景下需要显式调用事务对象，比如对一批数据的 先清理后插入
虽然硬编码可以实现一些事务操作，但对于多链接场景不够灵活

建议实现以下功能

开放一个方法 可以获取当前事务对象或者创建新的，该事务对象 将绑定在 IFreeSql 实例上

**Comment by hd2y** [comment]
这里的用法有符合你需求的吗？根据描述推荐试一下 DbContext: https://github.com/dotnetcore/FreeSql/wiki/%e4%ba%8b%e5%8a%a1

**Comment by hyzx86** [comment]
> 这里的用法有符合你需求的吗？根据描述推荐试一下 DbContext: https://github.com/dotnetcore/FreeSql/wiki/%e4%ba%8b%e5%8a%a1

看过了 ~ 木得。。

仔细想了下，我需要的是 **通过获取当前事务对象或者 获取当前连接对象 手动创建事务**，而IFreesql 实例通常是单例 
但实际测试下来，SQL Server 中 开启了事务后相关的表就不能用SSMS查了，只有在连接中指定事务中才可以
（可能并不准确，因为我注意到 freesql 源码里面有个叫 _trans 的集合变量，多事务，嵌套事务？？）



因为我在做一种类似于工作流的东西，它运行在脚本中，通过 自定义的 方法 调用 freesql 相关接口 执行多次查询/更新操作

比如 有个场景就是 一边删除后插入数据，如果过程中出现问题， 那么可能导致数据丢失

目前的实现方式是 完成所有校验后再 清理 并插入

![image](https://github.com/dotnetcore/FreeSql/assets/15613121/2c6755ce-49a4-4920-a629-e520bc5ff045)

**Comment by luoyunchong** [comment]
https://freesql.net/guide/transaction.html#%E8%8E%B7%E5%8F%96dbtransaction
这个不就能获取当前connection
![image](https://github.com/dotnetcore/FreeSql/assets/18613266/24ebf738-be09-4f3d-905e-355ebacebd51)

**Comment by hyzx86** [comment]
> https://freesql.net/guide/transaction.html#%E8%8E%B7%E5%8F%96dbtransaction 这个不就能获取当前connection ![image](https://user-images.githubusercontent.com/18613266/250276163-24ebf738-be09-4f3d-905e-355ebacebd51.png)

欸~~ 对对。没注意这个~ 3Q
