### ISSUE TITLE
老大怎么把全局过虑的生成条件放到where最前面，或者可以指定放到where的什么位置呢？

### ISSUE THREAD

**Issue by sukney** [dotnetcore/FreeSql#1566]
我现在加的全局过虑租户的条件生成的语句都在where的最后面，
 请问怎么把全局过虑的生成条件放到where最前面，或者可以指定放到where的什么位置呢？

**Comment by 2881099** [comment]
什么数据库，哪个驱动我先升一个给你用

**Comment by sukney** [comment]
mysql 数据库
