### ISSUE TITLE
sqlserver字段为公式时造成读取卡住

### ISSUE THREAD

**Issue by wanghu572** [dotnetcore/FreeSql#1567]
#### 问题描述及重现代码：
就这样一行就导致了代码卡住无响应，sql表格中使用了公式字段
WstItOaAccount表中含有了公式计算的字段，去掉公式字段后，恢复正常
```c#
var OaAccounts = await DataSource.fsql.Select<WstItOaAccount>().Where(x => x.OaUserID!=ClientInfo.MyOaInfo.OaUserID).OrderBy(x => x.OaUserName).ToListAsync();
```

#### 数据库版本
sqlserver2016

#### 安装的Nuget包
3.2.697

#### .net framework/. net core？ 及具体版本
.net6

**Comment by 2881099** [comment]
是不是开了事务的原因？

把 SQL 监视拿到控制台执行试试

**Comment by 256051** [comment]
> 是不是开了事务的原因？
> 
> 把 SQL 监视拿到控制台执行试试

他的意思是，https://learn.microsoft.com/zh-cn/previous-versions/office/developer/sharepoint-2010/bb862071(v=office.14)
这种字段：




Column1 | Column2 | 公式 | 说明（可能的结果）
-- | -- | -- | --
15000 | 9000 | =[Column1]>[Column2] | Column1 是否大于 Column2？(Yes)
15000 | 9000 | =IF([Column1]<=[Column2], "OK", "Not OK") | Column1 是否小于或等于 Column2？(Not OK)

**Comment by 2881099** [comment]
> > 是不是开了事务的原因？
> > 把 SQL 监视拿到控制台执行试试
> 
> 他的意思是，https://learn.microsoft.com/zh-cn/previous-versions/office/developer/sharepoint-2010/bb862071(v=office.14) 这种字段：
> 
> Column1	Column2	公式	说明（可能的结果）
> 15000	9000	=[Column1]>[Column2]	Column1 是否大于 Column2？(Yes)
> 15000	9000	=IF([Column1]<=[Column2], "OK", "Not OK")	Column1 是否小于或等于 Column2？(Not OK)

我主要关注生成的 SQL 和正确的 SQL 比较。
