### ISSUE TITLE
分库分表问题

### ISSUE THREAD

**Issue by xinshun** [dotnetcore/FreeSql#157]
1、分表操作做select.count()时报错“没有为 'ftb' 的列 1 指定任何列名称。\r\n没有为 'ftb' 的列 1 指定任何列名称。\r\n没有为 'ftb' 的列 1 指定任何列名称”
2、查看生成的SQL，--类似于
SELECT  * from (SELECT count(1) 
FROM  a 
WHERE a.startTime > '2019-10-01') ftb 
UNION ALL
SELECT  * from (SELECT count(1) 
FROM  a1 
WHERE a1.startTime > '2019-10-01') ftb 
UNION ALL
SELECT  * from (SELECT count(1) 
FROM  a2 
WHERE a2.startTime > '2019-10-01') ftb 
3、在SQLServer中执行报错

**Comment by 2881099** [comment]
把 select.Count() 方法

改成 select.First(a => Convert.ToInt64("count(1) as1')) 试试

**Comment by 2881099** [comment]
select.ToList<int>("count(1) as1").FirstOrDefault()
这样也行，先这样过渡一下

**Comment by 2881099** [comment]
已测试通过，整理进 1.0 版本，元旦发布
