### ISSUE TITLE
maui使用freesql操作sqlite3，生成的安卓应用出现【主库】连接字符串错误

### ISSUE THREAD

**Issue by aslyr** [dotnetcore/FreeSql#1577]
#### 问题描述及重现代码：
maui使用freesql操作sqlite3，生成的安卓应用出现【主库】连接字符串错误，请检查项目属性，或者改用Freesql.Provider.SqliteCore访问arm平台,已经按照文档使用nuget安装了FreeSql.Provider.SqliteCore，SQLitePCLRaw.bundle_e_sqlite3两个包。生成uwp没有问题，一切正常,安卓平台不行，使用Freesql.Provider.Sqlite也不行
```c#
// c# code
 string dbpath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "free.db");
        IFreeSql fsql = new FreeSql.FreeSqlBuilder()
              .UseConnectionString(FreeSql.DataType.Sqlite, @$"Data Source={dbpath}")
              //监听SQL语句
              .UseAutoSyncStructure(true) //自动同步实体结构到数据库，FreeSql不会扫描程序集，只有CRUD时才会生成表。
              .Build();
        MainPage = new NavigationPage(new MainPage(fsql));
```

#### 数据库版本
sqlite3

#### 安装的Nuget包
Freesql
FreeSql.Provider.SqliteCore
SQLitePCLRaw.bundle_e_sqlite3

#### .net framework/. net core？ 及具体版本
net7

**Comment by aslyr** [comment]
工程换成rider编译居然又管用了，估计是visualstudio2022没有清理缓存吧

**Comment by 2881099** [comment]
如出现此类问题，可以直接用 new SqliteConnection(str).Open() 测试。
