### ISSUE TITLE
InsertOrUpdate 增加 忽略更新 null 值的属性 SetSourceIgnore

### ISSUE THREAD

**Issue by f0508crm2** [dotnetcore/FreeSql#1579]
#### Feature 特性

```c#
// c# code
```

#### 简要描述原因
InsertOrUpdate 增加 忽略更新 null 值的属性 SetSourceIgnore 跟Update一样

fsql.Update<Topic>()
  .SetSourceIgnore(item, col => col == null)

```c#
// c# code
```

#### 使用场景

```c#
// c# code
```

**Comment by 2881099** [comment]
IUpdate.SetSourceIgnore不支持批量

IInsertOrUpdate 是插入或者更新，支持 UpdateColumns 指定更新时的字段

建议直接在应用层提取 string[]，传给UpdateColumns

**Comment by f0508crm2** [comment]
我没有要求批量，就是单条IInsertOrUpdate ，希望能直接忽略null字段，而不要手动提取有值的字段。IUpdate都有SetSourceIgnore，为什么IInsertOrUpdate 不可以有SetSourceIgnore呢
