### ISSUE TITLE
分库分表之分页

### ISSUE THREAD

**Issue by xinshun** [dotnetcore/FreeSql#158]
1、PageSize为200条记录，select在AsTable三次后，进行分页操作
select.Page(query.PageIndex, query.PageSize)
生成的是分页后UNION，最后得到的600条记录
生成的示例SQL如下
SELECT  * from (SELECT TOP 200 *
FROM [T] a 
LEFT JOIN [T20190101] b ON a.keyid = b.keyid
ORDER BY  orderField ) ftb 

UNION ALL

SELECT  * from (SELECT TOP 200 *
FROM [T] a 
LEFT JOIN [T20190102] b ON a.keyid = b.keyid
ORDER BY  orderField ) ftb 

UNION ALL

SELECT  * from (SELECT TOP 200 *
FROM [T] a 
LEFT JOIN [T20190103] b ON a.keyid = b.keyid
ORDER BY  orderField ) ftb 
2、实际上想要的是先UNION，再在外部取200条记录
实际上想要生成的SQL如下：
SELECT TOP 200 * from (SELECT *
FROM [T] a 
LEFT JOIN [T20190101] b ON a.keyid = b.keyid

UNION ALL

SELECT  *
FROM [T] a 
LEFT JOIN [T20190102] b ON a.keyid = b.keyid

UNION ALL

SELECT  *
FROM [T] a 
LEFT JOIN [T20190103] b ON a.keyid = b.keyid
) ftb
order by orderField
或者
SELECT  TOP 200 * from (SELECT *
FROM [T] a 
LEFT JOIN (
SELECT * FROM [T20190101]

UNION ALL

SELECT * FROM [T20190102] 

UNION ALL

SELECT * FROM [T20190103] 
) 
b ON a.keyid = b.keyid
) ftb
order by orderField

**Comment by xinshun** [comment]
使用如下方法解决：
1、/// <summary>
        /// 设置表
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <typeparam name="ET"></typeparam>
        /// <param name="dbInfo"></param>
        /// <param name="select"></param>
        /// <param name="tableName"></param>
        /// <param name="suff"></param>
        /// <param name="asTable"></param>
        /// <returns></returns>
        public static bool SetTable<T>(List<DbTableInfo> dbInfo, ISelect<T> select, string tableName, string suff, Func<Type, string, string> asTable) where T : class
        {
            if (dbInfo != null)
            {
                if (dbInfo.Exists(x => x.Name == tableName + suff))
                {
                    select = select.AsTable(asTable);

                    return true;
                }
            }

            return false;
        }
2、
private Func<Type, string, string> BuildTableRule(string asTable, bool isSQL = false)
        {
            Func<Type, string, string> tableRule = (type, oldname) =>
            {
                if (type == typeof(ARecordEntity)) return isSQL ? asTable : oldname + asTable;
                if (type == typeof(BRecordEntity)) return isSQL ? asTable : oldname + asTable;
                return oldname;
            };

            return tableRule;
        }
3、
var select = this.freeSql.Select<DEntity>()                
                .LeftJoin(a => a.KeyID == a.ARecord.KeyID)
                .Where(a => a.ARecord.Id > 0 && a.ARecord.STime >= query.StartTime && a.ARecord.STime < query.EndTime);


            int nIndex = 0;
            var eTime = query.EndTime;
            var ar = this.freeSql.Select<ARecordEntity>();
            var dbInfo = this.freeSql.DbFirst.GetTablesByDatabase();
            var oldTableName = freeSql.CodeFirst.GetTableByEntity(typeof(ARecordEntity)).DbName;
            // 按天分表
            while (query.StartTime.AddDays(nIndex) < eTime)
            {
                DateTime sTime = query.StartTime.AddDays(nIndex);
                var suff = sTime.ToString("yyyyMMdd");

                RepositoryCommon.SetTable<ARecordEntity>(dbInfo, ar, oldTableName, suff, BuildTableRule(suff));
                nIndex++;
            }
            select = select.AsTable(BuildTableRule(" (" + ar.ToSql() + ") ", true));
            //获取总记录数
            total = select.Count();
           //分页
            return select.Page(query.PageIndex, query.PageSize)
                      .OrderBy(" stime ")
                      .ToList();

**Comment by 2881099** [comment]
由于 AsTable 使用多次会，会存在多个 Union ALL 结果集拼接，对于聚合函数做了以下处理：

## 1、对应的 .Count()

```csharp
return this.ToList<int>("count(1) as1").Sum()
```

## 2、对应的 .Avg()

```csharp
var lst = this.ToList<TMember>("avg(a.Xxx) as1");
var sum = lst.Sum();
return list.Sum() / lst.Count();
```

## 3、对应的 .Avg()

```csharp
return this.ToList<TMember>("sum(a.Xxx) as1").Sum();
```

## 4、对应的 .Max()

```csharp
return this.ToList<TMember>("max(a.Xxx) as1").Max();
```

## 5、对应的 .Min()

```csharp
return this.ToList<TMember>("min(a.Xxx) as1").Min();
```

这样能兼容前后使用习惯，是否可行？

**Comment by 2881099** [comment]
```sql
SELECT TOP 200 * from (SELECT *
FROM [T] a
LEFT JOIN [T20190101] b ON a.keyid = b.keyid

UNION ALL

SELECT *
FROM [T] a
LEFT JOIN [T20190102] b ON a.keyid = b.keyid

UNION ALL

SELECT *
FROM [T] a
LEFT JOIN [T20190103] b ON a.keyid = b.keyid
) ftb
order by orderField
```

这种可以换种方式做：

```csharp
var leftJoin = fsql.Select<T>()
    .AsTable((_, old) => $"{old20190101}")
    .AsTable((_, old) => $"{old20190102}")
    .AsTable((_, old) => $"{old20190103}").ToSql();

var lst = fsql.Select<T>()
    .LeftJoin($"( {leftjoin} ) b ON a.keyid = b.keyid")
    .OrderBy(orderField)
    .Page(1, 200)
    .ToList();
```

**Comment by 2881099** [comment]
先 union all 再分页，这个功能我再考虑考虑，看怎么做兼顾所有

**Comment by hd2y** [comment]
@xinshun 建议markdown语法了解一下，排版一下阅读体验会好很多。🤣

**Comment by Ashhhhhh520** [comment]
提供几个场景给老哥,A表 150行数据,B表 N行数据 情况下, 分表取100条数据,size为100,用的mysql:
1, page=1的时候, 可以 select xxx from A limit 0,100 union all select xxx from B limit 0,100,取出100+条数据后,后台take 前100条可以;
2.page =2的时候, select xxx from A limit 100,200 union all select xxx from B limit 100,200, 表B已经不是前100条了, 而且表B可能第三页不足100条
3.page=3 ,select xxx from A limit 200,300 union all select xxx from B limit 200,300, 表A只有50条,表B已经不是前100条了, 而且表B可能第三页不足100条

分表又分页,不好控制表B呀,要分页只能从业务上限制单表了吧,
如果几个表先union起来在分页,数据量大的情况下跑不动的,而且需要分表的一般是大数据表,之前遇到过分表分页问题,但是没想到解决办法,只好业务上限制分表了,看下老哥有什么好的办法不....

**Comment by 2881099** [comment]
> ```sql
> SELECT TOP 200 * from (SELECT *
> FROM [T] a
> LEFT JOIN [T20190101] b ON a.keyid = b.keyid
> 
> UNION ALL
> 
> SELECT *
> FROM [T] a
> LEFT JOIN [T20190102] b ON a.keyid = b.keyid
> 
> UNION ALL
> 
> SELECT *
> FROM [T] a
> LEFT JOIN [T20190103] b ON a.keyid = b.keyid
> ) ftb
> order by orderField
> ```
> 
> 这种可以换种方式做：
> 
> ```cs
> var sql = fsql.Select<ARecordEntity, BRecordEntity>()
>     .AsTable((type, old) => type == typeof(BRecordEntity) ? $"{old20190101}" : null)
>     .AsTable((type old) => type == typeof(BRecordEntity) ? $"{old20190102}" : null)
>     .AsTable((type old) => type == typeof(BRecordEntity) ? $"{old20190103}" : null)
>     .LeftJoin((a,b) => b.keyid == a.keyid)
>     //.Where ... 其他条件
>     .ToSql((a,b) => new { a,b });
> 
> var list = fsql.Select<Dto>()
>     .AsTable((type, old) => $"( {sql} )")
>     //.OrderBy(orderField)
>     .Page(1, 200)
>     .ToList();
> ```
> 
> 这个办法，OrderBy 暂时不智能，有限制，因为 sql 返回语句的字段别名是 as1, as2....
> 
> 如果使用 OrderBy(a => a.id) 会报错列名不存在，如果用 OrderBy("as1") 倒是没问题。。

更新了这部分内容，各位哥看下

**Comment by 2881099** [comment]
```csharp
var sqlsss = select
    .AsTable((type, old) => type == typeof(Topic) ? $"{old}_1" : null)
    .AsTable((type, old) => type == typeof(Topic) ? $"{old}_2" : null)
    .ToSql(a => new
    {
        a.Id,
        a.Clicks
    }, FieldAliasOptions.UsePropertyName);

var slsld3 = select
    .AsTable((type, old) => type == typeof(Topic) ? $"({sqlsss})" : null)
    .Page(1, 20)
    .ToList(a => new
    {
        a.Id,
        a.Clicks
    });
```

在 ToSql 上增加了选项，FieldAliasOptions，支持使用属性名作为别名。不知道是否可以解决 OrderBy 的问题。

> 上面提到 OrderBy 暂时不智能，有限制，因为 sql 返回语句的字段别名是 as1, as2....

晚上弄了一堆代码改动，发现成本过大，把代码都撤销了，目前感觉 FieldAliasOptions 代价最小。各位看下怎么样。

**Comment by pjy612** [comment]
貌似发现了好东西...
