### ISSUE TITLE
使用pgsql的数据库，最大连接数据配置的为4，查看数据库连接数多了一个

### ISSUE THREAD

**Issue by PengYouLin** [dotnetcore/FreeSql#1582]
这是我使用的包：
![image](https://github.com/dotnetcore/FreeSql/assets/71313757/96580804-e16f-4f22-b7e2-44c51aa7f939)
这是我配置的数据库连接字符串
User ID=default; Password=default; Host=10.1.3.10; Port=5432; Database=DeviceCenter1;Pooling=true; Min Pool Size=0; Max Pool Size=4; Connection Lifetime=5
这个是我查询连接数的SQL语句
select datname, count(1) num from pg_stat_activity 
where datname='DeviceCenter1'
group by datname order by num desc;
![image](https://github.com/dotnetcore/FreeSql/assets/71313757/4be45482-6d50-4450-8807-488ea918ffcd)
![image](https://github.com/dotnetcore/FreeSql/assets/71313757/9a9b4c21-97ba-4b0d-a46c-20bb5a507d8c)
服务是用docker容器部署的。

**Comment by 2881099** [comment]
是这样的，如果介意可以使用

,UseConnectionString(...)
.UseAdoConnectionPool(true)

**Comment by pjy612** [comment]
弱弱问问，这个 执行SQL的 UI 是 第三方工具的，还是你的程序里的。
如果是第三方的话 可能是会多...

**Comment by PengYouLin** [comment]
> 弱弱问问，这个 执行SQL的 UI 是 第三方工具的，还是你的程序里的。 如果是第三方的话 可能是会多...

查询是第三方的，需要登陆postgress账号去查询，不过占的连接数算postgress的，不算我这我的目标库的连接数。
