### ISSUE TITLE
在ArcMap Add-in中使用FreeSql开发SQLite数据库总是报错

### ISSUE THREAD

**Issue by l1985q** [dotnetcore/FreeSql#1583]
我基于ArcMap的.Net SDK开发，其中使用了FreeSql，极为简单的代码：
public class Blog
{
[Column(IsIdentity = true, IsPrimary = true)]
public int BlogId { get; set; }
public string Url { get; set; }
public int Rating { get; set; }
}
public class DB
{
static Lazy<IFreeSql> sqliteLazy = new Lazy<IFreeSql>(() => new FreeSql.FreeSqlBuilder()
.UseMonitorCommand(cmd => Trace.WriteLine($"Sql：{cmd.CommandText}"))//监听SQL语句,Trace在输出选项卡中查看
.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=D:\\testdb.db")
.UseAutoSyncStructure(true) //自动同步实体结构到数据库，FreeSql不会扫描程序集，只有CRUD时才会生成表。
.Build());
public static IFreeSql Sqlite => sqliteLazy.Value;
}

IFreeSql fsql = DB.Sqlite;
fsql.CodeFirst.SyncStructure<Blog>();

以上同样的代码可以在Console程序中运行，就是不能在ArcMap Addin中运行就报
System.Exception:“【主库】Status unavailable, waiting for recovery. 连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64，或者改用 FreeSql.Provider.SqliteCore 访问 arm 平台”
这是什么原因，ArcMap的Add-in开发是基于.Net Framework 4.5进行的，结果就是一个dll库。

**Comment by l1985q** [comment]
> 指定生成 x86 或 x64 的试试？ 有时候 AnyCPU 没那么好使... 不过DLL 好像确实没分那么细 = =。

试过生成x86，因为ArcMap是32位程序，一样的问题。

**Comment by 2881099** [comment]
直接用 new SqliteConnection(xxx).Open测试

**Comment by l1985q** [comment]
缺少SQLite.Interop.dll，已经处理了
