### ISSUE TITLE
FreeSql.Generator -match参数如何批量生成指定名称的表实体

### ISSUE THREAD

**Issue by damonxx** [dotnetcore/FreeSql#1584]
假如要生成表名称为 tzt_1,jkg2,jts 三张表的实体，-match 参数应该怎么写？ -match tzt_1|jkg2|jts  这样写就卡着不动了

**Comment by 2881099** [comment]
建议用这个项目源码debug一下

**Comment by 2881099** [comment]
也可以执行三行命令来分别生成，反正是.bat批处理文件
