### ISSUE TITLE
BaseEntity模式下使用 子表First/Count/Sum/Max/Min/Avg 出错

### ISSUE THREAD

**Issue by j4587698** [dotnetcore/FreeSql#1586]
#### 问题描述及重现代码：
假设有类A继承于BaseEntity，类B继承于BaseEntity
使用代码
```c#
await A.Select.ToListAsync(x => new 
        {
            Count = B.Where(y => y.AId == x.Id).Count()
        });
```
报错
```
System.AggregateException: One or more errors occurred. (variable 'x' of type 'A' referenced from scope '', but it is not defined)
```
如果改用
```
freeSql.Select<B>().Where(y => y.AId == x.Id).Count()
```
则正常

#### 数据库版本
sqlite

#### 安装的Nuget包
3.2.70-preview20230726

#### .net framework/. net core？ 及具体版本
.net7

**Comment by 2881099** [comment]
Count = B.Select.Where(y => y.AId == x.Id).Count()

**Comment by 2881099** [comment]
see #216

**Comment by 2881099** [comment]
已优化等待下次发布版本

当前可以使用 Count = B.Select.Where(y => y.AId == x.Id).Count() 解决
