### ISSUE TITLE
clickhouse中插入影响行数一直为0

### ISSUE THREAD

**Issue by wangboshun** [dotnetcore/FreeSql#1589]
#### 问题描述及重现代码：

使用

 _fsql.Insert(model).ExecuteAffrows()单条插入

_fsql.Insert(list).ExecuteAffrows()批量插入

一直为0，更新和删除暂时未测试。

```c#
// c# code
```

 _fsql.Insert(model).ExecuteAffrows()
_fsql.Insert(list).ExecuteAffrows()

#### 数据库版本
clickhouse 23

#### 安装的Nuget包
3.2.700

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by 2881099** [comment]
单条也是0吗？

多条行为使用 bulkcopy 没有返回值

**Comment by wangboshun** [comment]
> 单条也是0吗？
> 
> 多条行为使用 bulkcopy 没有返回值

单条也是0

**Comment by 2881099** [comment]
可以考虑把 freesql.provider.clickhouse.csproj 引进 debug 一下

**Comment by d4ilys** [comment]
https://github.com/DarkWanderer/ClickHouse.Client/issues/249
ClickHouse.Client是基于HTTP方式访问的ClickHouse，HTTP返回值中并不包含影响行数，我提过一个issuse
![image](https://github.com/dotnetcore/FreeSql/assets/54463101/c9066c28-904b-48c8-9db6-8f042d2ce50a)

**Comment by wangboshun** [comment]
> https://github.com/DarkWanderer/ClickHouse.Client/issues/249
> 
> ClickHouse.Client是基于HTTP方式访问的ClickHouse，HTTP返回值中并不包含影响行数，我提过一个issuse
> 
> ![image](https://github.com/dotnetcore/FreeSql/assets/54463101/c9066c28-904b-48c8-9db6-8f042d2ce50a)
> 
> 

好吧，那就没办法知道插入成功与否

**Comment by 2881099** [comment]
不报错，代表成功
