### ISSUE TITLE
查询表结构时新增主键名称

### ISSUE THREAD

**Issue by AN-535** [dotnetcore/FreeSql#1597]
#### Feature 特性
使用GetTableByName返回的表结构里面，现在没有主键的名称，只有主键列。希望主键名称一并返回

#### 简要描述原因
需要查询具体的表结构信息

#### 使用场景
页面上需要显示具体的键名称用于修改

**Comment by 2881099** [comment]
主键列和名称不一样么

**Comment by AN-535** [comment]
> 主键列和名称不一样么

![image](https://github.com/dotnetcore/FreeSql/assets/33016525/52429903-cb17-4a48-ab7d-ce18a494b718)
就像是这种，我需要hospital_fee_pk这个名称

**Comment by 2881099** [comment]
这个在索引里看看

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/blob/master/FreeSql.DbContext/EfCoreFluentApi/EfCoreTableFluent.cs
