### ISSUE TITLE
测试用例合理性讨论

### ISSUE THREAD

**Issue by LambertW** [dotnetcore/FreeSql#16]
SqlServerInsertTest.cs

增加
```c#
[Fact]
public void InsertWithExistData()
{
    var items = GenerateItems(10);

    items[0].Id = (int)insert.AppendData(items[0]).ExecuteIdentity();

    Assert.Equal(0, insert.AppendData(items[0]).ExecuteAffrows());
}
```
预期item.Id > 0的时候，应该是会跳过吧？
或者是可配置？

**Comment by LambertW** [comment]
同理，AppendData(items)的时候，Id有效情况下，是否也应该跳过插入

**Comment by LambertW** [comment]
问题2，
```C#
var inarray = new[] { 1, 2, 3 };
var inList = inarray.ToList();
var list = select.Where(a => inList.Contains(a.testFieldInt)).ToList();
var list1 = select.Where(a => !inList.Contains(a.testFieldInt)).ToList();
```
报错 未实现函数表达式，`List.Contains`，有考虑支持吗？

**Comment by 2881099** [comment]
插入跳过的潜规则，目前只跳过列表中null的对象，是否会增加解释成本啊，因为确实会有id>0仍然执行。


list.Container 应该是没测试到位，我记录一下

**Comment by LambertW** [comment]
> 
> 
> 插入跳过的潜规则，目前只跳过列表中null的对象，是否会增加解释成本啊，因为确实会有id>0仍然执行。
> 

这种场景感觉会出现异常呀，可能是用户处理不当，例如 Add/Edit 的操作，对应MVC的一个Action，仅按照id判断是进行编辑还是新增~
处理不当可能会产生新数据~

这个是框架设计问题，也不是一定就是错的，说清楚就好

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/54473631-49222b80-4815-11e9-80df-e6e4696e18d9.png)

问题2，已修

**Comment by LambertW** [comment]
👍，是通用的IEnumerable/ IList 接口，还是其他

**Comment by 2881099** [comment]
IList，因为它是独立的 Contains
Linq.Enumerable 和这里定义的不一样，之前只作了 linq.Contains 判断

**Comment by 2881099** [comment]
> > 插入跳过的潜规则，目前只跳过列表中null的对象，是否会增加解释成本啊，因为确实会有id>0仍然执行。
> 
> 这种场景感觉会出现异常呀，可能是用户处理不当，例如 Add/Edit 的操作，对应MVC的一个Action，仅按照id判断是进行编辑还是新增~
> 处理不当可能会产生新数据~
> 
> 这个是框架设计问题，也不是一定就是错的，说清楚就好

针对这个问题，可不可以在 FreeSql.Repository 的 filter 上实现约束。
因为在最里层加这个，感觉会得罪其中一派人。

**Comment by LambertW** [comment]
可以呀，例如初始化的时候，
``` c#
new FreeSql.FreeSqlBuilder(options => {
  options.InsertOptions.InsertWithExistPrimaryKey = InsertWithExistPrimaryKey.ThrowException;
});

// ThrowException, Skip, IngoreAndCreateNew , Default: ThrowException
```
类似吧，放在Repository都可以

**Comment by LambertW** [comment]
参考下别人的做法，这方面还是要看具体框架明确下来，就好了

**Comment by 2881099** [comment]
现在配置这块确实有些乱。
想到一个加一个。

FreeSqlBuilder 那里的 一堆 UseXxx，哈哈
