### ISSUE TITLE
SyncStructure 执行后 引发的异常:“System.MissingMethodException”(位于 System.Private.CoreLib.dll 中)

### ISSUE THREAD

**Issue by sgf** [dotnetcore/FreeSql#1605]
#### 问题描述及重现代码：
执行完SyncStructure 输出就出现  引发的异常:“System.MissingMethodException”(位于 System.Private.CoreLib.dll 中)
但是具体查原因,又查不到.

```c#
freeSql.CodeFirst.SyncStructure(entyties);
```

![图片](https://github.com/dotnetcore/FreeSql/assets/2557696/bc7d1a15-d048-4598-99f4-0d54fe0dc4b3)

#### 数据库版本
Sqlite 最新版?

#### 安装的Nuget包
![图片](https://github.com/dotnetcore/FreeSql/assets/2557696/9f11a49f-d5e8-42be-93ae-1119200fe288)

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by 2881099** [comment]
MissingMethodException

这个错误是由于版本不一致导致的，检查有关dll版本

**Comment by 2881099** [comment]
例如

A接口定义的项目，修改了接口参数
B实现层，访问了这个接口

b访问a接口，必须匹配版本号，否则可能会出现那个错误

**Comment by sgf** [comment]
> 

这么说应该是我 FreeSql的包版本不一致导致额...晚点我看看.谢谢

**Comment by sgf** [comment]
> 例如
> 
> A接口定义的项目，修改了接口参数 B实现层，访问了这个接口
> 
> b访问a接口，必须匹配版本号，否则可能会出现那个错误

确实是版本问题,虽然我也不知道是怎么回事.
但是升级完就解决了,谢谢叶老板

**Comment by sgf** [comment]
> 例如
> 
> A接口定义的项目，修改了接口参数 B实现层，访问了这个接口
> 
> b访问a接口，必须匹配版本号，否则可能会出现那个错误


叶老板,更新之后遇到了新的问题.


“System.IO.FileNotFoundException”类型的异常在 System.Private.CoreLib.dll 中发生，并且未在托管/本机边界之前进行处理

Could not load file or assembly 'System.Data.SQLite.SEE.License, Version=1.0.115.5, Culture=neutral, PublicKeyToken=433d9874d0bb98c5, processorArchitecture=MSIL'. 系统找不到指定的文件。

如有适用于此异常的处理程序，该程序便可安全地继续运行。

**Comment by luoyunchong** [comment]
没有问题，没付费，不要带密码，或者 debugger时，可配置跳过此异常。

**Comment by sgf** [comment]
> 没有问题，没付费，不要带密码，或者 debugger时，可配置跳过此异常。

没有密码,都是普通正常使用. 之前好的,更新了最新版本FreeSql 就出现了这个问题.怀疑是不是 System.Sqlite.data 的新版本,搞的鬼.

**Comment by sgf** [comment]
我再研究研究吧.

**Comment by luoyunchong** [comment]
https://freesql.net/guide/freesql-provider-sqlitecore.html

**Comment by sgf** [comment]
> https://freesql.net/guide/freesql-provider-sqlitecore.html

![图片](https://github.com/dotnetcore/FreeSql/assets/2557696/b43a093b-7965-4656-8d5c-6ce7e51292fd)


微软的版本 明显不行哇.
问题更多.
算了,实在不行,我强行忽略这个报错吧.

**Comment by 2881099** [comment]
new SqliteConnection(...).Open() 测试一下

**Comment by sgf** [comment]
> new SqliteConnection(...).Open() 测试一下



生产环境遇到  database disk image is malformed 问题.
考虑到 最近更新了FreeSql最新版本.而且正好又是 SyncStructure 的错误.
然后我正好损坏的数据库开启了 UseAutoSyncStructure

因此我觉得可能最新版本的FreeSql,针对Sqlite数据库 存在 损坏数据库文件的风险.

**Comment by sgf** [comment]
> new SqliteConnection(...).Open() 测试一下

经过进一步排查 发现可能是
Serilog.Sinks.SQLite 这个包导致 Sqlite版本 问题.
总之 似乎是  Sqlite版本 问题导致FreeSql出错.
出错版本为 Sqlite 1.0.115.5
