### ISSUE TITLE
当相互引用关系很复杂的时候，[Navigate(nameof(CusGroup))] 可能导致首次使用导航属性失败

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/FreeSql#1606]
#### 问题描述及重现代码：

demo

https://github.com/densen2014/FreeSqlDemos/tree/FreeSql_issues1606?WT.mc_id=DT-MVP-5005078

 语句 fsql.Select<ResCustomersLite>()
            .Include(a => a.groupName)
 
第一次执行, 出来的sql是    LEFT JOIN [CusGroupName] a__groupName ON , 获取不到 nameof(CusGroup) 的内容. 

第二次执行, 出来sql才是 LEFT JOIN [CusGroupName] a__groupName ON a__groupName.[CusGroupID] = a.[CusGroup] 

改为 [Navigate("CusGroup")] 就没问题

```c#
class ResCustomersLite{ 
       public int? CusGroup { get; set; }

        [Navigate(nameof(CusGroup))]
        //[Navigate("CusGroup")]
        public virtual CusGroupName groupName { get; set; }
}

```
https://github.com/dotnetcore/FreeSql/wiki/%E5%AE%9E%E4%BD%93%E5%85%B3%E7%B3%BB#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE

主要是循环依赖的导航属性，可能需要预热,实体类不能一次加载所需的导航配置数据,有可能A引用B, B引用C, C里面又引用了A
尝试循环执行 fsql.Select<object>().AsType(实体类), 现象依旧. 改回  [Navigate("CusGroup")] 没问题

![~(9GN9X)0%M7%C S4{Q77F](https://github.com/dotnetcore/FreeSql/assets/8428709/8b6b325a-81e1-4b18-97f9-cff660b4c2c0)

#### .net framework/. net core？ 及具体版本
nf461

**Comment by 2881099** [comment]
预热说明：导航属性配置的加载，因为要解决死循环引用，当相互引用关系很复杂的时候，可能导致首次使用导航属性失败，第二次就可以了。解决办法可以程序启动时就预热所有实体类，循环执行 fsql.Select<object>().AsType(实体类);

最好跟在 FreeSqlBuilder 之后预热，批量预热如下：

```c#
Assembly asse = typeof(T).Assembly;
var types = asse.GetTypes().Where(a => a.IsAbstract == false && a.FullName.StartsWith("xxx.Entities.");

foreach (var type in types)
    fsql.Select<object>().AsType(type);
```
