### ISSUE TITLE
OneToOne,OneToMany,ManyToMany,ManyToOne文档完善

### ISSUE THREAD

**Issue by tceioos47** [dotnetcore/FreeSql#1608]
建议将这四种关系分别在文档里给出完整的、清晰明了的说明和FreeSql支持的Demo应用样例。
关于这方面的说明文档和例子有点碎片化（有些例子需要在Issue里找）。
OneToOne,OneToMany,ManyToMany,ManyToOne在Wiki给出背景知识，这些关系是针对功能层面还是仓储表级的，对我来说很是不清楚。我觉得好文档应该给以相关解惑（虽然不是必须的）。

FreeSql不支持ManyToOne吗？

`public class Student
{
       public int Id {get;set;}
       public string Name {get;set;}
       public int ClassId {get;set;}
}`
`public class Class
{
       public int Id {get;set;}
       public int Address {get;set;}
}
`
以Student类为主体，Student和Class构成了Many-to-One的结构。在程序的功能开发中，获取一个学生的信息后再获取它所在班级的其他信息（如地址）是需要的。

```[tasklist]
### Tasks
```

**Comment by 2881099** [comment]
FreeSql 提供 OneToMany, ManyToOne, ManyToMany, OneToOne, Parent, PgArrayToMany 六种导航属性关系。

导航属性能干什么？

[《多表查询》](https://freesql.net/guide/select-multi-table.html) Where(a => a.Parent.Parent.Name == "xx")
[《贪婪加载》](https://freesql.net/guide/select-include.html) Include/IncludeMany
[《延时加载》](https://freesql.net/guide/select-lazy-loading.html)
[《树表查询》](https://freesql.net/guide/select-as-tree.html)
[《级联保存》](https://freesql.net/guide/cascade-saving.html)
[《级联删除》](https://freesql.net/guide/cascade-delete.html)
[《聚合根仓储》](https://freesql.net/guide/aggregateroot.html)
导航属性进行多表查询非常方便，lambda 表达式中直接使用导航对象点点点，舒服！！

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb

这个文档应该挺全了啊，能做什么，以及怎么配置

**Comment by densen2014** [comment]
看不明白可以看一下测试项目，就更清楚了

**Comment by tceioos47** [comment]
> 看不明白可以看一下测试项目，就更清楚了
可以给一下测试项目的链接吗

**Comment by tceioos47** [comment]
FreeSql不支持ManyToOne的CRUD吗？我看没人回答我这个问题，我看文档上说不支持这种模式下的保存。
我看github首页给出了FreeSql的四种开发mode，请问在DbContext和Repository模式下都不支持ManyToOne的保存吗？如果不支持由这方面的更新计划吗？

**Comment by 2881099** [comment]
@tceioos47 ManyToOne不适合做极联更新，因为不符合聚合根理论

**Comment by 2881099** [comment]
聚合根的模型，应该从上至下的设计。

ManyToOne 是从下向上

**Comment by tceioos47** [comment]
> 聚合根的模型，应该从上至下的设计。
> 
> ManyToOne 是从下向上

那像“学生-班级”这种以学生为主体数据表的ManyToOne只能手动保存吗

**Comment by 2881099** [comment]
是的，班级不属于学生，应该分开更新

**Comment by sgf** [comment]
> https://github.com/dotnetcore/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb
> 
> 这个文档应该挺全了啊，能做什么，以及怎么配置



```C#


//OneToMany
class Group
{
    [Navigate(nameof(User.GroupId))]
    public List<User> Users { get; set; }
    //在 User 查找 GroupId 属性，与 本实体.主键 关联
}

//ManyToOne
class User
{
    public int GroupId { get; set; }
    [Navigate(nameof(GroupId))]
    public Group Group { get; set; }
    //在 本实体 查找 GroupId 属性，与 Group.主键 关联
}

//ManyToMany
[Navigate(ManyToMany = typeof(TagSong))]
public List<Tag> Items { get; set; }
```



但是文档偷懒,各种模式的实体声明混在了一起.

OneToMany 肯定又One和Many
但是你这里Many里面 又带了ManyToMany 的定义,所以很让人迷惑.
所以OneToMany的情况下 User类型中到底要不要声明 Group 属性?

    public Group Group { get; set; }

**Comment by 2881099** [comment]
@sgf 不需要，你最后发的是反过来配置，ManyToOne，两者独立
