### ISSUE TITLE
服务运行一段时候后，freesql对数据库的读写突然卡住

### ISSUE THREAD

**Issue by wcyzero** [dotnetcore/FreeSql#1611]
数据库用的postgresql，服务启动的时候一切正常，但是运行两三天之后就会突然卡死，主库所有的读写都无法执行，但是只读库仍旧是好的。
而且直接到数据库执行sql也是没问题的。
排查半天不清楚是什么问题。
freesql版本是2.5.200

**Comment by luoyunchong** [comment]
talk is cheap show me the code

**Comment by wcyzero** [comment]
> talk is cheap show me the code

似乎没有非常值得展示的代码，下面是其中一段执行sql的代码，只是读写操作都无法进行
![image](https://github.com/dotnetcore/FreeSql/assets/32378383/e1981511-a1a7-4d46-9583-7ee3f489c38d)
这里有注册数据源的代码，不过看起来应该没有什么问题。
![image](https://github.com/dotnetcore/FreeSql/assets/32378383/165c53de-4ccf-4466-a2c2-d9ac4ded7adf)
当出现问题的时候，我尝试在数据库中杀死相关连接，但是依旧没有效果，重启服务可以临时解决，只是过一段时间后还是出了问题。

**Comment by 2881099** [comment]
数据库卡住，不是因为死锁吗？

**Comment by wcyzero** [comment]
> 数据库卡住，不是因为死锁吗？

到数据库没有查询到死锁任务，而且数据库本身的访问、读写都没有问题，其他连接这个数据库的服务也没有问题。只要当前服务与数据库连接卡住，并且重启后又恢复正常

**Comment by 2881099** [comment]
任务量大不大，尝试UseAdoConnectionPool(true)
