### ISSUE TITLE
InsertOrUpDate.SetSource 以及导航级联保存时，将插入的自增ID赋值给实体的对应字段

### ISSUE THREAD

**Issue by tceioos47** [dotnetcore/FreeSql#1621]
#### Feature 特性

```c#

```

#### 简要描述原因
每次新增和更新（使用SetSource）都需要额外从数据库获取插入的自增主键ID，尤其是使用List<T>时还需要额外保存插入的ID。
虽然可以使用GetRepository使用仓储级的InsertOrUpDate返回插入更新实体。（或者GetRepository.InsertOrUpDate支持插入列表批量）
```c#
// c# code
```

#### 使用场景

```c#
// c# code
```

**Comment by 2881099** [comment]
建议用 Repository 做，IFreeSql 原生 API 尽量保持和 SQL 一样的习惯吧
