### ISSUE TITLE
FreeSql对Oracle11g的CodeFirst生成的PK Index名字超过30字符的问题

### ISSUE THREAD

**Issue by CTUzkc** [dotnetcore/FreeSql#1622]
环境为：
net 6.0
oracle 11g
FreeSQL 3.2.698
BUG原因：
1.表名有点长
2.生成创建表的SQL中，创建Index的名称模板是:{表空间}_{表名}_pk 
碰巧生成的index名字超过了oracle限制的30字符

想请教几个问题：
1.能不能自定义生成或不生成pk的索引（之前简单测试了一下在oracle下会自动生成PK索引，在PostgreSQL上不会自动生成）？
2.能不能在oracle下生成PK索引时修改生成规则或者生成名字？

**Comment by 2881099** [comment]
[OraclePrimaryKeyName(name)]
class table {...}

**Comment by CTUzkc** [comment]
十分感谢
