### ISSUE TITLE
多表 UNION ALL 之后，如何返回ISelect对象。

### ISSUE THREAD

**Issue by 981476460** [dotnetcore/FreeSql#1623]
多表 UNION ALL 之后，如何返回ISelect对象。强制转换执行会报错。
![image](https://github.com/dotnetcore/FreeSql/assets/49896324/7e9d16f4-7ae3-4e1a-94d0-d1d6d75a7d81)

**Comment by 2881099** [comment]
都用一样的WithTempQuery
