### ISSUE TITLE
TypeHandler<DateTime> 在Select时不生效

### ISSUE THREAD

**Issue by Skymly** [dotnetcore/FreeSql#1634]
#### 问题描述及重现代码：
我尝试使用TypeHandler<DateTime> 尝试转为long再存入数据库,插入语句执行正常，查询语句报错。
我换了一种TypeHandler<DateTime> 的实现，尝试转换为字符串再存入数据库，Insert正常，Select没报错但是结果不正确，得到的结果是DateTime的默认值。测试代码已经上传github。

**Comment by 2881099** [comment]
目前的限制

1. 基础类型不可以，可以特别开放 DateTime 的处理
2. DateTime lambda表达式函数基本不能使用，只可以使用 between and 大于小于这些
3. 目前映射规则是全局化的，一但设置 DateTime 多个 IFreeSql 都同样映射规则

**Comment by 2881099** [comment]
v3.2.802-preview20231010 已支持 TypeHandler\<DateTime\>

**Comment by Skymly** [comment]
> v3.2.802-preview20231010 已支持 TypeHandler<DateTime>

谢谢，TypeHandler功能对我的项目非常重要，我会继续反馈我的使用情况。
