### ISSUE TITLE
ado，使用原生sql时，IN关键字会报查询异常

### ISSUE THREAD

**Issue by quqi-beep** [dotnetcore/FreeSql#1635]
![image](https://github.com/dotnetcore/FreeSql/assets/59988881/a45ea217-a072-41ab-9f50-513b58f439b8)
如图，ids参数为一个list集合，执行时报异常

**Comment by 2881099** [comment]
看用哪个驱动，不同的驱动，前辍有点区别

例如：?ids   :ids

**Comment by quqi-beep** [comment]
![image](https://github.com/dotnetcore/FreeSql/assets/59988881/abfc6690-a5c2-4670-8992-1f25d23f8773)
驱动是这个

**Comment by quqi-beep** [comment]
![image](https://github.com/dotnetcore/FreeSql/assets/59988881/abf9d60f-c0bc-4044-885f-018be6367506)
是这个吗

**Comment by luoyunchong** [comment]
![image](https://github.com/dotnetcore/FreeSql/assets/18613266/8df63c68-2a8c-48b6-b358-65866c8ef618)
https://freesql.net/guide/ado.html#%E6%9F%A5%E8%AF%A2-sql-%E8%BF%94%E5%9B%9E%E5%AE%9E%E4%BD%93
