### ISSUE TITLE
使用动态实体DynamicEntity新增数据时报The data type of the operation * is inconsistent with AsType *

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#1640]
#### 问题描述及重现代码：
使用 DynamicEntity 创建动态实体，将一份数据迁移到多个数据库中时，第一个正常执行，之前的都报类型不匹配的错误了。

demo在附件中
[ConsoleApp2.zip](https://github.com/dotnetcore/FreeSql/files/12974249/ConsoleApp2.zip)

**Comment by 2881099** [comment]
System.Exception:“操作的数据类型(EntityClass) 与 AsType(EntityClass) 不一致，请检查。”

**Comment by 2881099** [comment]
DynamicEntity 内部根据【类名】区分，需要设置成不同的【类名】

```c#
            var type1 = CreateType(fsql1, tableName + "1", table);
            Trans(fsql1, fsql, type1, tableName);

            var type2 = CreateType(fsql2, tableName + "2", table);
            Trans(fsql2, fsql, type2, tableName);
```
