### ISSUE TITLE
Ado.Query方法使用参数报错

### ISSUE THREAD

**Issue by tpnest** [dotnetcore/FreeSql#1647]
#### 问题描述及重现代码：
使用Ado.Query<T>方法带参数报错
![image](https://github.com/dotnetcore/FreeSql/assets/57797158/9ddf0545-a8a1-465c-9335-c2165068ab3f)

```c#
// c# code
        List<Users> list = _dbContext.Ado
            .Query<Users>("select * from users where id = @id", new {id = 1});
```

#### 数据库版本
MySql5.7

#### 安装的Nuget包
![image](https://github.com/dotnetcore/FreeSql/assets/57797158/e22d651e-3328-45e8-952f-f056f7886fca)

#### .net framework/. net core？ 及具体版本
.Net7

**Comment by 2881099** [comment]
?id
你用的驱动语法是这样
