### ISSUE TITLE
Fatal error in Unity CIL Linker

### ISSUE THREAD

**Issue by 2022Cyberpunk** [dotnetcore/FreeSql#1648]
<!-- 

#### 问题描述及重现代码：
Unity2021.3.16f1中使用freeSql的sqlite，打包到window平台报错

#### 安装的Nuget包
FreeSql-3.2.801

#### .net framework/. net core？ 及具体版本
net40
![image](https://github.com/dotnetcore/FreeSql/assets/114492189/2335d2a1-6835-4842-906f-6dcb8b164653)

```[tasklist]
### Tasks
```

**Comment by 2881099** [comment]
https://www.cnblogs.com/FreeSql/p/17836000.html
.NET8.0 AOT 经验分享 FreeSql/FreeRedis/FreeScheduler 均已通过测试
