### ISSUE TITLE
Oracle 连接数据库报错 ORA-12649

### ISSUE THREAD

**Issue by jiaomy2016** [dotnetcore/FreeSql#1652]
【主库】Status unavailable, waiting for recovery. ORA-12649: Native Services: Unknown encryption or data integrity algorithm

连接串
user id=user;password=dsdfsdf#21; data source=192.168.1.21:1521/MM;Pooling=true;Min Pool Size=1
连接出错数据库版本如下
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

如下版本都可以正常连接
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

有没有人遇到，是不是咱们连接串中需要增加哪一些参数才可以正常连接

`   在 FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReader(DbConnection connection, DbTransaction transaction, Action`1 fetchHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.AdoProvider.Query[T](Type resultType, DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.AdoProvider.Query[T](DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.Select0Provider`2.ToListQfPrivate[TTuple](String sql, String field)
   在 FreeSql.Internal.CommonProvider.Select0Provider`2.ToList[TTuple](String field)
`

**Comment by 2881099** [comment]
用 new OracleConnection 测试

**Comment by jiaomy2016** [comment]
using (OracleConnection connection = new OracleConnection(connectionString))
 {
     connection.Open();
     Console.WriteLine("ServerVersion: " + connection.ServerVersion
         + "\nDataSource: " + connection.DataSource);
 }


使用这个测试 也一样报错
