### ISSUE TITLE
更新方法问题

### ISSUE THREAD

**Issue by guusji** [dotnetcore/FreeSql#1657]
我在代码里使用了和文档一样的更新步骤，但是导致我没更新的字段，更新成空，是哪里产生了问题
![Uploading 微信图片_20231107103549.png…]()

```[tasklist]
### Tasks
```

**Comment by guusji** [comment]
我更新的是密码和更新时间字段，但是账户手机号字段会变空
`var accountRepo = _patientRepository.GetRepository<UserAccountEntity>();

var item = new UserAccountEntity { ID = accountId };
accountRepo.Attach(item);
item.Password = password;
item.UpdateTime = DateTime.Now;
var rows = await accountRepo.UpdateAsync(item);
return rows;`

**Comment by 2881099** [comment]
把 SQL 监视打开，查看执行的 SQL
