### ISSUE TITLE
是否考虑将TableInfo 的AsTableImpl属性赋值放开，通过注入的方式或者参数传入的方式，以便分表可以自定义处理

### ISSUE THREAD

**Issue by weiyan2012** [dotnetcore/FreeSql#1663]
是否考虑将TableInfo 的AsTableImpl属性赋值放开，通过注入的方式或者参数传入的方式赋值，以便分表可以自定义处理

**Comment by 2881099** [comment]
fsql.GetTableByEntity(typeof(T)).AsTableImpl 

目前可以通过这样的方式设置

**Comment by weiyan2012** [comment]
看了下这个属性是只读的，
不过找到一个SetAsTable 方法，

**Comment by 2881099** [comment]
> 看了下这个属性是只读的， 不过找到一个SetAsTable 方法，

目前的设计是 beta 模式，可能会考虑不周全。

对外公开的 api 在合适的时候，再重新整理一套符合使用者习惯的方式，否则容易出现设计不合理的 api ，到时候再移除麻烦。
