### ISSUE TITLE
MySQL CodeFirst 倒序索引重复执行生成

### ISSUE THREAD

**Issue by JadynWong** [dotnetcore/FreeSql#1664]
#### 问题描述及重现代码：

添加索引指定为倒序, 生成一次后, 不做任何修改, 每当允许迁移时总会删除已存在索引, 再重写创建
```csharp
[Index("{tablename}_idx_02", $"{nameof(UserId)}, {nameof(SubmitTime)} DESC")]
```

```sql
DROP INDEX `tablename_idx_02` ON `dbname`.`tablename`;
CREATE INDEX `tablename_idx_02` ON `dbname`.`tablename`(`UserId`, `SubmitTime` DESC);
```

#### 数据库版本
MySQL 8.0

#### 安装的Nuget包
FreeSql.Provider.MySqlConnector 3.2.802

#### .net framework/. net core？ 及具体版本
.NET 7.0.403

https://github.com/dotnetcore/FreeSql/blob/a4dca345474363939d855c52bac72bf831cacb0f/Providers/FreeSql.Provider.MySql/MySqlCodeFirst.cs#L266-L280

查看源码是上面的SQL引起的. 为何查询索引信息`IsDesc`固定写死为0?

看文档`COLLATION`似乎可以确定是否为倒序

https://dev.mysql.com/doc/refman/8.0/en/information-schema-statistics-table.html
> COLLATION
> How the column is sorted in the index. This can have values A (ascending), D (descending), or NULL (not sorted).

https://downloads.mysql.com/docs/refman-5.6-en.pdf#page=3323&zoom=100,72,799
> ![image](https://github.com/dotnetcore/FreeSql/assets/13699353/7acf4359-db96-41b1-baaa-ab05a40fd325)

**Comment by 2881099** [comment]
开发使用的5.6版本版，不支持降序
看来要判断一下版本

**Comment by JadynWong** [comment]
> 开发使用的5.6版本版，不支持降序 看来要判断一下版本

MySQL 8.0之前版本确实不支持, 但是`COLLATION`同样存在, 只是全部都是`A`, 即使创建索引时指定了DESC. 

是否可以仅在文档中声明不支持在MySQ 8.0中创建倒序索引? 如果要代码判断版本是否还要考虑[MariaDB](https://jira.mariadb.org/browse/MDEV-13756)或者其他兼容MySQL的数据库?

**Comment by 2881099** [comment]
mysql 5.6 有 collation 这个字段，说明 MariaDB 都是兼容的，只是值都是 A

**Comment by 2881099** [comment]
过5分钟后更新 nuget  v3.2.803-preview20231114

**Comment by JadynWong** [comment]
> 过5分钟后更新 nuget  v3.2.803-preview20231114

已更新，测试在mysql8.0上正常了。mysql5.6行为与之前一致。感谢。
