### ISSUE TITLE
使用最新版的clickhouse.client后，批量插入报错

### ISSUE THREAD

**Issue by wangboshun** [dotnetcore/FreeSql#1666]
使用最新版的clickhouse.client 6.8.1后，批量插入失败，找不到方法。
回退到6.7.5没问题

```c#
// c# code

 _fsql.Insert(list).NoneParameter().ExecuteAffrows();

报错信息：System.MissingMethodException: Method not found: 'Void ClickHouse.Client.Copy.ClickHouseBulkCopy.set_DestinationTableName(System.String)'

```

#### 数据库版本
clickhouse 23

#### 安装的Nuget包
3.2.803

#### .net framework/. net core？ 及具体版本
6

**Comment by 2881099** [comment]
clickhouse.client 6.8.1 与 6.7.5 API 调整导致的错误

先用 6.7.5，之后待 FreeSql.Provider.Clickhouse 升级解决

**Comment by 2881099** [comment]
单独升级 FreeSql.Provider.Clickhouse 3.2.804
