### ISSUE TITLE
Oracle 9i使用OracleOledb驱动循环插入300条记录后，报错：ORA-01000超过了最大打开游标

### ISSUE THREAD

**Issue by netty2019** [dotnetcore/FreeSql#1673]
Oracle 9i使用OracleOledb驱动循环插入300条记录后，报错：ORA-01000超过了最大打开游标数，增加系统游标数可以解决，但是不太合理，应该是库里面有使用完的资源没有释放

#### 数据库版本
Oracle 9i

#### 安装的Nuget包
FreeSql.Provider.OracleOledb 3.2.805

#### .net framework/. net core？ 及具体版本
.net6

**Comment by 2881099** [comment]
是按照文档的方式创建单另模式吗？

**Comment by netty2019** [comment]
> 是按照文档的方式创建单例模式吗？

是的

**Comment by 2881099** [comment]
.UseAdoConnectionPool(true)

加上这个

**Comment by netty2019** [comment]
试了，还是不行。
不像是连接池导致的，开启事务的情况下，在一个方法中以同步方式循环执行插入语句，应该只产生一个连接的吧

**Comment by 2881099** [comment]
那要看用哪种事务了
