### ISSUE TITLE
添加 ToArray 支持

### ISSUE THREAD

**Issue by XtremlyRed** [dotnetcore/FreeSql#1674]
#### Feature 特性
* 能否在查询返回数据时添加ToArray() 方法功能
```c#
// 如下所示
var arrayData=freesql.Select<Data>().ToArray();
var arrayData=await freesql.Select<Data>().ToArrayAsync();
```

#### 简要描述原因

在大多数情况下使用 ToList 或是 ToListArray 已经完成够用的，但是在一些输入参数固定的情况下 比如已经封装好的库中，可能只支持 Array 参数类型输入，在这样的情况下 还需要在外部在转换一次，数据大的情况下可能会耗时增多
```c#
// c# code

//耗费性能
var listData=await freesql.Select<Data>().ToListAsync();
var arrayData= listData.ToArray();

//性能优化
var arrayData=await freesql.Select<Data>().ToArrayAsync(); 

```

#### 使用场景

输入参数固定的情况下，无需在次在外部进行类型转换而是直接使用 ToArray 就好了 而不需要 在toList 然后在 ToArray
```c#
// c# code

//耗费性能
var listData=await freesql.Select<Data>().ToListAsync();
var arrayData= listData.ToArray();
xxxMethod(arrayData);

//性能优化
var arrayData=await freesql.Select<Data>().ToArrayAsync(); 
xxxMethod(arrayData);

//固定方法（或其他动态库中的方法）
public void  xxxMethod(Array array)
{
      //todo
}

```

**Comment by 2881099** [comment]
ToArray() 只能是 ToList() 再 ToArray()

二次开销是肯定的，因为 DataReader 读取的时候，不知道记录多长，因此无法 new Array[length]

**Comment by 2881099** [comment]
如果其实需要，我可以用扩展方法的形式处理，ISelect API 不动。

**Comment by XtremlyRed** [comment]
能否使用   Array.Resize  进行性能优化  在目前的硬件基础上，这个花销应该不是很大

**Comment by 2881099** [comment]
你可以试试用 ToChunk + Array.Resize 测试下

ToChunk 是分批返回的 List<T>

**Comment by XtremlyRed** [comment]
我的意思是  在处理 datareader的时候 使用 array.resize 就像memoryStream一样进行空间优化（可能起始需要大一点） 这样在外部就无需额外处理了

**Comment by XtremlyRed** [comment]
或者直接提供一个 toArray 和 toArrayAsync 的拓展方法吧-   这样可能更合理一些

**Comment by NMSAzulX** [comment]
楼主的需求主要是针对大数量情况下，解决 ToArray 带来的性能影响吧？ 

## 临时方案：
如果 Copy 性能低于反射性能，可以考虑 反射/emit/expression 实现，否则使用 ToArray.
```c#
// 获取 List<int> 的类型信息
Type type = list.GetType();

// 找到表示内部数组的字段
FieldInfo fieldInfo = type.GetField("_items", BindingFlags.NonPublic | BindingFlags.Instance);

// 反射字段以获取内部数组的引用
int[] internalArray = (int[])fieldInfo.GetValue(list);
```

## 其他方案：
实现一个高性能的泛型填充序列，需要一些性能实验支持，另外还需要针对类型进行优化。简单实现成本不高，但高性能实现需要验证和优化。
1. 针对简单实现提供给用户一个 DataReader -> TResult 及 TResult -> Result<TResultCollection> 的实现缺口，可以扩展映射逻辑。
2. 自实现或接受 PR，提供一个高性能的 ToArray 映射。

**Comment by NMSAzulX** [comment]
注：

不管是自实现，还是反射内部数组，还是ToArray，如果你想得到一个满载元素的数组，而不是多出一节，那都离不开一次Buffer.Memmove/Copy 操作。
