### ISSUE TITLE
添加DistinctBy支持

### ISSUE THREAD

**Issue by ZUOXIANGE** [dotnetcore/FreeSql#1680]
#### Feature 特性

```c#
_freeSql.Select<TestTable>().DistinctBy(x => new{ Column1, Column2 }).ToList();
```

[PostgreSQL distinct on 用法](https://www.zhangbj.com/p/1603.html)

#### 使用场景

根据某几个字段去重,但是又可以查询出未去重字段的值

**Comment by 2881099** [comment]
见楼上

**Comment by ZUOXIANGE** [comment]
命名还是建议用DistinctBy,虽然和数据库函数不一致,但是和Enumerable.DistinctBy方法保持了一致.这样以后可以扩展到其他数据库.目前我使用中的clickhouse和PostgreSQL是支持这个功能

**Comment by 2881099** [comment]
这种方法暂时只能用扩展方式提供，不加入正式 API。

个人建议以数据库命名比较好，Enumerable.DistinctBy 了解的人不多（例如我从未用过，更不知道它做什么的）

**Comment by ZUOXIANGE** [comment]
那先待定吧,可以参考EF对于这个的支持进度  https://github.com/dotnet/efcore/issues/27470

**Comment by 2881099** [comment]
上面我发的扩展方法试了没有
