### ISSUE TITLE
DM数据库适配，如何指定模式前缀？

### ISSUE THREAD

**Issue by ZQL200207** [dotnetcore/FreeSql#1684]
#### 问题描述及重现代码：

CREATE TABLE "config_audit_event"
是否可以
CREATE TABLE "SYSDBA"."config_audit_event"
#### 数据库版本
DM7

#### 安装的Nuget包
FreeSql.All.3.2.805

#### .net framework/. net core？ 及具体版本
.net6

**Comment by 2881099** [comment]
指定设置

\[Table(Name = "sysdba.config_audit_event")\]

统一设置

```c#
//提前设置 FreeSqlBuilder AOP 优先级
//UseMappingPriority(MappingPriorityType.Attribute, MappingPriorityType.FluentApi, MappingPriorityType.Aop)

fsql.Aop.ConfigEntity += (s, e) => {
    e.ModifyResult.Name = "public." + e.ModifyResult.Name;
};
```
