### ISSUE TITLE
Enum.GetValues与AOT不兼容

### ISSUE THREAD

**Issue by vgxl** [dotnetcore/FreeSql#1691]
#### 问题描述及重现代码：

```c#
IFreeSql fsql = new FreeSql.FreeSqlBuilder()
        .UseConnectionString(FreeSql.DataType.MySql, @"Server=localhost;Port=3306;Database=good;User Id=root;")
        .UseAutoSyncStructure(true)
        .Build();
fsql.Select<TestEnum>().ToList();
public class TestEnum
{
    public Ab Type { get; set; }
}
public enum Ab
{
    A, B
}
```

#### 数据库版本
Mysql 8.0

#### 安装的Nuget包
FreeSql.Provider.MySqlConnector源代码

#### .net framework/. net core？ 及具体版本
dotnet 8.0

####  建议
可以考虑使用GetFields(BindingFlags.Static | BindingFlags.Public)代替

**Comment by 2881099** [comment]
Console.WriteLine(Enum.GetValues(typeof(TestEnum)));

在启动项目执行一下，这个就可以了

有关这个问题，我之前写过文章 https://www.cnblogs.com/FreeSql/p/17836000.html

**Comment by 2881099** [comment]
所谓优化，当下的版本只能 try catch 兼容处理。

**Comment by vgxl** [comment]
> Console.WriteLine(Enum.GetValues(typeof(TestEnum)));
> 
> 在启动项目执行一下，这个就可以了
> 
> 有关这个问题，我之前写过文章 https://www.cnblogs.com/FreeSql/p/17836000.html

感谢回复，我现在是使用Enum.GetValues<TestEnum>()，只是希望更易用。😄

**Comment by vgxl** [comment]
> 所谓优化，当下的版本只能 try catch 兼容处理。

我昨天尝试将UtilsExpressionTree.cs的256行到264行改为如下代码：
```C#
var isEqualsEnumValue = false;
var enumValues = mapType.GetFields(BindingFlags.Static | BindingFlags.Public).Select(x => x.GetValue(null)).ToArray();
for (var a = 0; a < enumValues.Length; a++)
    if (object.Equals(defaultValue, enumValues[a]))
    {
        isEqualsEnumValue = true;
        break;
    }
if (isEqualsEnumValue == false && enumValues.Length > 0)
    defaultValue = enumValues[0];
```
您看是否合适？

**Comment by 2881099** [comment]
GetFields 与 Enum.GetValues 返回的顺序不同吗，我没来得及测试，如果不一致不适合。

这里其实用处不大，大概逻辑是判断 c# defaultValue 的值是否存在于 Enum 中，不存在则使用 Enum 第一个值。
