### ISSUE TITLE
达梦数据库，数据库连接总是“请求执行超时”！

### ISSUE THREAD

**Issue by ZQL200207** [dotnetcore/FreeSql#1695]
#### 问题描述及重现代码：
页面刷新就报错，这可能是什么原因导致的呢？

![企业微信截图_17029816463144](https://github.com/dotnetcore/FreeSql/assets/79621277/94a2887a-a8c7-438a-846a-b7d32ab69cae)

#### 数据库版本
DM7

#### 安装的Nuget包
FreeSql.All.3.2.805

#### .net framework/. net core？ 及具体版本
.NET6

**Comment by 2881099** [comment]
连接串用文档的吗？

**Comment by ZQL200207** [comment]
完全参照文档写的

![image](https://github.com/dotnetcore/FreeSql/assets/79621277/948f9914-fa6a-4289-97e5-856a35a55482)

**Comment by 2881099** [comment]
请求执行超时，你用原生ado.net测试过没有？

**Comment by ZQL200207** [comment]
还没有，达梦数据库的问题？我去测试下

**Comment by 2881099** [comment]
和数据库无关和驱动有关，但是这个错误是驱动执行超时，例如，查询的内容被其他事务锁住了

**Comment by ZKUTF-8** [comment]
> 和数据库无关和驱动有关，但是这个错误是驱动执行超时，例如，查询的内容被其他事务锁住了

我观察了一下，在程序刚启动时和隔一段时间就会出现超时，只要出现了超时那一段时间所有的操作都会超时，如果没有超时那一段时间都会正常
那么这种情况，能不能提供一下解决的思路呢
我现在也用ado.net去测试一下
如果按照您说的如果是事务锁住了，那么我用ado.net去测试似乎也没有什么意义，因为不太可能用ado.net将数据库操作都实现一遍

**Comment by 2881099** [comment]
只要出现了超时那一段时间所有的操作都会超

针对这个，如果是状态不可用错误，可以使用 UseAdoConnectionPool(true) 设置。

但是你上面发的错误，确实是 ado.net 底层抛出的超时。

**Comment by ZKUTF-8** [comment]
> UseAdoConnectionPool
好的我试试，我也用ado.net试试

**Comment by 2881099** [comment]
@trackycn 命令超时问题，不是达梦专有的，其他数据库也会，默认值一般在15-30秒的样子。
