### ISSUE TITLE
在oracle中有这样的数据类型  NUMBER(38,8)。 在c#是没有对应类型的。该如何解决？

### ISSUE THREAD

**Issue by wang2650** [dotnetcore/FreeSql#1697]
c# 中的 decimal 是不符合要求的。 NUMBER(38,8)是没法给 decimal 赋值的。
同理 NUMBER(38,0) 用long也是不行的。用biginterger 是可以的，但是又没法传到数据库。

**Comment by 2881099** [comment]
用字符串映射，或者定义一个新类型映射，看类型映射文档，自定义映射

**Comment by hjkl950217** [comment]
如果能确定，业务上存储不会超过 decimal的范围，也可以强转一下
