### ISSUE TITLE
sqlserver保存image类型,开启IsNoneCommandParameter会导致内容长度变少

### ISSUE THREAD

**Issue by aaasssmnb** [dotnetcore/FreeSql#170]
实体是使用的 byte[] 类型
方法是使用DbContext的实体Update
开启IsNoneCommandParameter之后发现更新的图片格式错误
跟踪到最后执行Update,发现实体内长度还是正常的
但是Update之后的审计Sql发现内容的长度会变少,目前来看每次长度是不定的,出现过10~200等的情况

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/71466956-27ba8b00-27fc-11ea-8d67-2b15cbd2a002.png)

测试代码：

```csharp
class TestByte
{
    public Guid id { get; set; }
    public byte[] pic { get; set; }
}

var testByte = new TestByte {
    pic = File.ReadAllBytes(@"C:\Users\28810\Desktop\github\FreeSql\functions06.png")
};
var sql = fsql.Insert(testByte).NoneParameter().ToSql();
fsql.Insert(testByte).ExecuteAffrows();

var getTestByte = fsql,Select<TestByte>(testByte).First();

File.WriteAllBytes(@"C:\Users\28810\Desktop\github\FreeSql\functions06_write.png", getTestByte.pic);
```

监视器：

  | 名称 | 值 | 类型
-- | -- | -- | --
◢ | testByte | {FreeSql.Tests.UnitTest3.TestByte} | FreeSql.Tests.UnitTest3.TestByte
  | ▶ id | {5e04de6c-d783-5ab0-00d2-e40a40f17eb3} | System.Guid
  | ▶ pic | {byte[97690]} | byte[]
◢ | getTestByte | {FreeSql.Tests.UnitTest3.TestByte} | FreeSql.Tests.UnitTest3.TestByte
  | ▶ id | {5e04de6c-d783-5ab0-00d2-e40a40f17eb3} | System.Guid
  | ▶ pic | {byte[255]} | byte[]

原因：

byte[] 默认映射 DbType 是 varbinary(255)，所以被截取了。

解决办法：

[Column(DbType = "varbinary(max)")]
public byte[] pic { get; set; }

![image](https://user-images.githubusercontent.com/16286519/71467104-c0510b00-27fc-11ea-923d-b99ea8064fe7.png)

**Comment by aaasssmnb** [comment]
意思是dbtype映射成image不支持吗?要映射成varbinary(max)才有效?

**Comment by pjy612** [comment]
> 意思是dbtype映射成image不支持吗?要映射成varbinary(max)才有效?

你试试 [Column(DbType = "image")] 
然后 看看大佬有没有对应的适配。。。
没有再问问大佬...

**Comment by aaasssmnb** [comment]
> > 意思是dbtype映射成image不支持吗?要映射成varbinary(max)才有效?
> 
> 你试试 [Column(DbType = "image")]
> 然后 看看大佬有没有对应的适配。。。
> 没有再问问大佬...

目前我是映射成image的
``` 
a.Property(b => b.defectpic_pic).Name("defectpic_pic").DbType("image NULL")

**Comment by 2881099** [comment]
image 是 sqlserver 早期的类型，跟 text 类型一样？？
现在基本没人用 text 类型了。

image 不知道是写的时候截断了，还是读的时候。
我看了生成的 NoneParameter SQL 是完整的

**Comment by pjy612** [comment]
> image 是 sqlserver 早期的类型，跟 text 类型一样？？
> 现在基本没人用 text 类型了。
> 
> image 不知道是写的时候截断了，还是读的时候。
> 我看了生成的 NoneParameter SQL 是完整的

看你之前发的感觉读的时候 截断了？

**Comment by 2881099** [comment]
> > image 是 sqlserver 早期的类型，跟 text 类型一样？？
> > 现在基本没人用 text 类型了。
> > image 不知道是写的时候截断了，还是读的时候。
> > 我看了生成的 NoneParameter SQL 是完整的
> 
> 看你之前发的感觉读的时候 截断了？

我用 codefirst 测试的，因为 byte[] 默认映射的类型是 varbinary(255)，所以创建表的时候就只有这么长

**Comment by aaasssmnb** [comment]
我是通过 fsql.Aop.CurdBefore 进行sql跟踪的,然后把生成的sql对应图片字段的值整个拷贝到sqlserver,
用SELECT datalength(XXXX) 来确认sql里面图片的长度, 这个值和已插入的值是一致的, 所以我得感觉就是转sql的时候被截断了,另外这里我刚刚写了一个简单的demo,不管是映射成image,varbinary(max),varchar(max),text貌似结果都是内容截断了 :

```C#
public class m_defectPic
{
    [Column(IsPrimary = true, IsIdentity = true)]
    public long defectpicid { get; set; }
    public string databasename { get; set; }
    public long defectid { get; set; }
    [Column(DbType = "varbinary(max) null")]
    public byte[] defectpic_pic { get; set; }
    public string designpic_cruserid { get; set; }
    public string designpic_crname { get; set; }
    public DateTime? designpic_crdate { get; set; }
    public string designpic_remark { get; set; }
}
```
```C#
static void Main(string[] args)
{
    string connstr = @"Data source=xxx;initial catalog=xxx;user id=xxx;password=xxx;MultipleActiveResultSets = True;";

    var picFSql = new FreeSql.FreeSqlBuilder()
                    .UseConnectionString(FreeSql.DataType.SqlServer, connstr)
                    .Build();
    picFSql.CodeFirst.IsNoneCommandParameter = true;
    picFSql.SetDbContextOptions(opt => opt.EnableAddOrUpdateNavigateList = false);


    picFSql.Aop.CurdBefore = (s, e) =>
    {
        Debug.WriteLine($"写入时sql:{e.Sql}");
    };


    var testModel = new m_defectPic
    {
        defectpicid = 29,
        databasename = "testDB",
        defectid = 49,
        defectpic_pic = File.ReadAllBytes(@"E:\Desktop\test.png"),
        designpic_crdate = DateTime.Now,
        designpic_crname = "XXX",
        designpic_cruserid = "1234",
        designpic_remark = "XXX",
    };


    Console.WriteLine($"写入前长度{testModel.defectpic_pic.Length}");


    picFSql.Update<m_defectPic>().SetSource(testModel).ExecuteAffrows();
    testModel = picFSql.Select<m_defectPic>().Where(o => o.defectpicid == 29).ToOne();


    Console.WriteLine($"写入后长度{testModel.defectpic_pic.Length}");


    Console.ReadKey();
}
```

结果是:
```
写入前长度281547
写入后长度278502
```

已经尽量模拟成实际代码的样子,实体基本没有变动 ,DB环境 是 2008 R2

**Comment by 2881099** [comment]
```csharp
var bytes = value as byte[];
var sb = new StringBuilder().Append("0x");
foreach (var vc in bytes)
{
    if (vc < 10) sb.Append("0");
    sb.Append(vc.ToString("X"));
}
return sb.ToString();
```

@aaasssmnb 用这个试试

**Comment by 2881099** [comment]
现在是这样处理二进制拼接的，有一个判断 \< 10，是不是这里的问题 @aaasssmnb

**Comment by aaasssmnb** [comment]
@2881099  直接转换长度正确, 不过提示 操作数类型冲突: ntext 与 image 不兼容

**Comment by aaasssmnb** [comment]
@2881099 看错了,转换之后用SELECT datalength 确实是被长度短了

**Comment by 2881099** [comment]
@aaasssmnb 把图片上传一下，我测试下你的图片

**Comment by aaasssmnb** [comment]
![QQ截图20191227110152](https://user-images.githubusercontent.com/16997390/71500003-0ad69400-289e-11ea-85cb-36a54f52ebc0.png)

**Comment by 2881099** [comment]
@aaasssmnb File.ReadAllBytes(@"E:\Desktop\test.png"), 是这个图片吗

**Comment by aaasssmnb** [comment]
不是,不过后面的测试我都换成这张了

**Comment by 2881099** [comment]
试出来了。。判断  \< 0 处理有问题，问题修了

**Comment by 2881099** [comment]
试出来了。。判断  \< 0 处理有问题，问题修了 @aaasssmnb

**Comment by 2881099** [comment]
我前面测试的代码，在 Insert().ExecuteAffrows() 这里漏了加 .NoneParameter()。。以为是正常的

**Comment by aaasssmnb** [comment]
噢~大佬牛逼(32个赞
