### ISSUE TITLE
 关于分库的问题

### ISSUE THREAD

**Issue by MicroHeartWangZheng** [dotnetcore/FreeSql#1703]
我有多个数据库，db1,db2,db3......  每个库中，数据表都是一样的，假如每个库都只有一张表user，且字段都相同,  我用了freesql的仓储，写了对应表的实体和仓储。 我是不是需要写多个实体和多个仓储？ 然后在加上  [Table(Name = "db1.dbo.table1")]

`
[Table(Name = "db1.dbo.user")]
class  User_1 { ... }

[Table(Name = "db2.dbo.user")]
class  User_2{ ... }

[Table(Name = "db3.dbo.user")]
class  User_3{ ... }

public interface IUser1Repository : IBaseRepository<User_1, int>, IScope

public interface IUser2Repository : IBaseRepository<User_2, int>, IScope

public interface IUser3Repository : IBaseRepository<User_3, int>, IScope

`
只能这么写吗？  有没有简单的方法，我不想一个类型 写多个类，而且里面字段相同。  我看了文档 没有找到类似问题的解决方案。

**Comment by 2881099** [comment]
类型只定义一个，具体映射哪个表，再使用 AsTable 处理

FreeSql 原生用法、FreeSql.Repository 仓储用法 都提供了 AsTable 方法对分表进行 CRUD 操作，例如：

```csharp
var repo = fsql.GetRepository<Log>();
repo.AsTable(oldname => $"{oldname}_201903"); //对 Log_201903 表 CRUD
//repo.AsTable((type, oldname) => $"{oldname}_201903"); //对 Log_201903 表 CRUD（级联有关表也增加该后辍）

repo.Insert(new Log { ... });
```

跨库，但是在同一个数据库服务器下，也可以使用 AsTable(oldname => $"db2.dbo.{oldname}")

如果是多租户，可以看视频的三种方案

【.NET ORM FreeSql 官方视频教程系列-哔哩哔哩】 https://b23.tv/HxEZTcl
