### ISSUE TITLE
多表联表查询时设置了别名， ON 那里的别名还是默认的a、b

### ISSUE THREAD

**Issue by ntzw** [dotnetcore/FreeSql#1705]
#### 问题描述及重现代码：

多表联表查询时设置了别名， ON 那里的别名还是默认的a、b

```c#
var select = _freeSql.Select<ClassroomRegister, EducateCenter>().LeftJoin((register, center) => center.Num == register.RegisterCenterNum);
select.Page(req.Current, req.Size);
select.As("t", "organ")
```

SELECT TOP 20 t.[Id], t.[Num], t.[Status], t.[IsDel], t.[Sort], t.[CreateDate], t.[CreateUser], t.[UpdateDate], t.[UpdateUser], t.[OrganNum], t.[RoomName], t.[ExaminationSite], t.[ExaminationSiteLocation], t.[ClassroomName], t.[Email], t.[MAC], t.[SoftwareVersions], t.[DatabaseVersions], t.[ServerVersions], t.[Code], t.[IsSendMessage], t.[IsManyPeopleVerify], t.[VerifyPeopleNumber], t.[RegisterType], t.[IsClientVerify], t.[RegisterCenterNum], t.[MachineInfo], t.[Capacity], t.[Type], t.[IsEnabled] 
FROM [TST_PC_ClassroomRegister] t 
LEFT JOIN [TST_EducateCenter] organ ON b.[Num] = a.[RegisterCenterNum] 
WHERE (1=1 AND t.RegisterCenterNum = @P658c1b4bf9b6b28c) 
ORDER BY t.id desc

#### 数据库版本
SqlServer

#### 安装的Nuget包
最新版本

#### .net framework/. net core？ 及具体版本
.net6

**Comment by 2881099** [comment]
项目顺序调一下

**Comment by ntzw** [comment]
> 项目顺序调一下

可以了，谢谢。一开始我用 AsAlias 放在LeftjJoin 前面不行，调到后面也不行，换了这个没调到前面试一下了。
