### ISSUE TITLE
偶发性错误 【主库】仍然不可用，下一次恢复检查时间

### ISSUE THREAD

**Issue by haoyoua** [dotnetcore/FreeSql#1706]
【主库】仍然不可用，下一次恢复检查时间: 2024/1/11 15:53:16，错误: <A network-related or instance-specific error occurred while establishing a connection to sQL Server. The server was not found or was not accessible. Uerify that the instance name is correct and that SQL Server is configured to allow remote connections. Kprovider: Named Pipes Provider, error: 40-Could not open a connection to SQL Server>>

**Comment by 2881099** [comment]
new SqlConnection(str).Open()

测试一下

**Comment by haoyoua** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by haoyoua** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
