### ISSUE TITLE
提个批量删除的建议

### ISSUE THREAD

**Issue by Angus221** [dotnetcore/FreeSql#171]
我看删除里面有个
fsql.Select<T1>().Where(a => a.Options.xxx == 1).ToDelete().ExecuteAffrows();
转成的SQL
**DELETE FROM `T1` WHERE id in (select a.id from T1 a left join Options b on b.t1id = a.id where b.xxx = 1)**

其中子查询如果数据量大的话 性能会比较差。建议改成 delete from join 的方式
例如：
Delete from T1 a left join Options b on b.t1id = a.id where b.xxx = 1

**Comment by 2881099** [comment]
多表查询没深入研究，这样写可能数据库间不通用吧
