### ISSUE TITLE
clickhouse使用字典方式更新失败

### ISSUE THREAD

**Issue by wangboshun** [dotnetcore/FreeSql#1712]
使用UpdateDict方法进行数据更新时报异常。

![image](https://github.com/dotnetcore/FreeSql/assets/6279612/e6a10b6e-8403-4fb8-b9e9-1214c28f50d4)

表结构：
create table if not exists test.st_pptn_r_3
(
    STCD String,
    TM DateTime,
    DRP Nullable(Decimal(9, 6)),
    DRP_C Nullable(Int32)
)
 engine = ReplacingMergeTree()
        PARTITION BY toYYYYMMDD(TM)
        PRIMARY KEY (STCD, TM)
        ORDER BY (STCD, TM)
        SETTINGS index_granularity = 8192

```c#

var dic = new Dictionary<string, object>
            {
                { STCD, "12345678" },
                { TM, "2024-01-01 00:00:00" },
                { "DRP, "123" },
                { "DRP_C", 100 }
            };
var primary = new[] { "STCD", "TM"};

_fsql.UpdateDict(dic).AsTable("st_pptn_r_3").WherePrimary(primary).ExecuteAffrows() > 0;

```

#### 数据库版本
clickhouse 23.6.2.18

#### 安装的Nuget包
3.2.810

#### .net framework/. net core？ 及具体版本
.net 6

**Comment by wangboshun** [comment]
跟踪了代码，其中ColumnInfo里面的Attribute.DbType为空

**Comment by 2881099** [comment]
FreeSql.Provider.ClickHouse 3.2.811-preview20240115

升这一个包
