### ISSUE TITLE
各个实例需单独分开的OneToMany如何处理？

### ISSUE THREAD

**Issue by tceioos47** [dotnetcore/FreeSql#1715]
public class A
{
    [Column(IsIdentity = true)]
    public int Id { get; set; }
    public string Name { get; set; }

    public int B1Id { get; set; }
    [Navigate(nameof(B1Id))]
    public B B1 { get; set; }

    public int B2Id { get; set; }
    [Navigate(nameof(B2Id))]
    public B B2 { get; set; }
}

public class B
{
    [Column(IsIdentity = true)]
    public int Id { get; set; }
    public string Name { get; set; }
}

注意这里的Navigate属性可能使用的不恰当，传统的导航属性和级联保存只适用于列表的一对多，但加载到列表以后，往往无法区分各个实例，比如上面的类A内有两个B类的实例，这里OneToMany的数量是固定有限的（就两个），我想根据类A的B1Id和B2Id来从表B中索引处对应的实例B1和B2（而不是一个列表），对于这种情况如何处理，可以适用导航属性吗？或者其他更好的实现方法

**Comment by 2881099** [comment]
没问题，就是这样用的

其实你举的例子是两个ManyToOne，而不是OneToMany

OneToMany 是用自身的pk对应某一个表字段

**Comment by tceioos47** [comment]
> 没问题，就是这样用的
> 
> 其实你举的例子是两个ManyToOne，而不是OneToMany
> 
> OneToMany 是用自身的pk对应某一个表字段

也就是说只能手动保存（Inlcude或者includeMany进行删除查询）了？那这个导航属性起了什么作用？是不是只要我手动保存或者使用Include我不用Navigate声明也行？

**Comment by tceioos47** [comment]
建议针对上面形式的ManyToOne搞一个专门的函数来支持上述数据结构形式的数据库保存，因为现在都是用户手动编写保存语句，感觉完全可以在FreeSql里搞一个函数来自动化搞定这种情形的保存，

**Comment by 2881099** [comment]
导航属性，不只是保存，还有查询功能。

对保存要求高，可以看下聚合根仓储文档：https://freesql.net/guide/aggregateroot.html

从聚合根角度看，ManyToOne 不适合级联保存，因为它不是实体所属信息。

例如 Topic 文章所属 Type 分类

更新 Topic 时把 Type 更新的不合理原因：Type 有可能是其他文章所属，其他文章并不想修改 Type。
