### ISSUE TITLE
在PostgreSql 函数getdate()不存在

### ISSUE THREAD

**Issue by pengxinglove** [dotnetcore/FreeSql#1728]
#### 问题描述及重现代码：
之前使用SQL SERVER 数据库，里面有一些日期字段，如CreateTime，采用getdate()作为默认值，导出Model的时候，注解上面带了一个getdate(),
现在切换到PostgreSql, 在执行Insert 语句的时候，即使CreateTime在代码里面设置了值，但还是会出来getdate
![image](https://github.com/dotnetcore/FreeSql/assets/10840137/e379dc7e-425a-4c4b-b7fd-11b7eba83b49)
![image](https://github.com/dotnetcore/FreeSql/assets/10840137/8c60a8ad-ee9b-495f-bd61-eee224bcc66a)

```c#
// c# code
```

**Comment by pengxinglove** [comment]
我现在只能手动删除这些特性

**Comment by 2881099** [comment]
因为这些实体类你是从 sqlserver 生成的。

只有纯 CodeFirst 模式，才比较方便切换数据库。
