### ISSUE TITLE
WebApi項目遇到泰國日期格式化問題

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/FreeSql#1743]
#### 问题描述及重现代码：
最近開發項目在泰國那邊實施發現一個很奇怪的情況,我們項目是一個WEB項目,然而當瀏覽器設置語言為泰文時候,出現日期類型格式化問題導致Freesql生成的sql語句也是錯誤的
**假設當前時間為  2024/3/7 14:00:00**
當http請求頭設置為 Accept-Language:  th, 那datetime時間就變為 7/3/2567 14:00:00 ,導致Freesql生成sql語句也跟著錯誤
```c#
var dt = DateTime.Now.AddDays(1);
//當瀏覽器第一語言為zh時候,輸出為 2024/3/8 14:00:00
//當瀏覽器第一語言為th時候,輸出為 8/3/2567 14:00:00
var dtstr = dt.ToString();

//當瀏覽器第一語言為zh時候,輸出為
// SELECT {省略}
//   FROM[CT_BO_AnalysisSummaryMain] a With(NoLock)
//   WHERE(a.[CreatedUtcTime] >= '2024-03-08 14:00:00')
//當瀏覽器第一語言為th時候,輸出為
// SELECT {省略}
//   FROM[CT_BO_AnalysisSummaryMain] a With(NoLock)
//   WHERE(a.[CreatedUtcTime] >= '2567-03-08 14:00:00')
var sql = Svc.Fsql.Select<BoAnalysisSummaryMain>()
            .Where(x => x.CreatedUtcTime >= dt)
            .ToSql();

```
我也搞不懂為什麼C#本身會這樣子轉換,找了網上也沒有很好的解決辦法,我想問下freesql有沒有生成sql時候的aop攔截處理

**Comment by 2881099** [comment]
Aop.CommandBefore 事件中 debugger 一下试试

**Comment by bao2314483** [comment]
> Aop.CommandBefore 事件中 debugger 一下试试
我日誌也打印出來了,其實你建立一個WebApi項目,然後把瀏覽器語言設置為泰文就可以復現了
![image](https://github.com/dotnetcore/FreeSql/assets/6925099/e4bac8ed-2718-447e-bcd5-3aedd645b698)

**Comment by 2881099** [comment]
我的建议：服务器用 en-us 文化

**Comment by pjy612** [comment]
感觉这种多时区的 要么 入参全是UTC 输出全是 UTC，然后 存的话 看是 UTC 还是 服务器 时间。
前端页面上 再根据 浏览器和系统时间 自己转换...

**Comment by bao2314483** [comment]
> 我的建议：服务器用 en-us 文化

找到根本原因了,因為th是使用佛教日曆,所以我只需把泰語國際化默認的佛教日曆改為公曆即可
CultureInfo.CurrentCulture.DateTimeFormat.Calendar = new GregorianCalendar();

**Comment by bao2314483** [comment]
> 感觉这种多时区的 要么 入参全是UTC 输出全是 UTC，然后 存的话 看是 UTC 还是 服务器 时间。 前端页面上 再根据 浏览器和系统时间 自己转换...

你說的是時區問題,我描述的是日曆類型問題

**Comment by pjy612** [comment]
难道是用了 UseRequestLocalization ?
