### ISSUE TITLE
树型向上查询并去重会报错

### ISSUE THREAD

**Issue by AN-535** [dotnetcore/FreeSql#1751]
#### 问题描述及重现代码：
_fsql.Select<MenuInfo>().Where(a => a.Status == GlobalEnum.DataStatus.Enable && !_fsql.Select<RoleMenuRelation>().Where(b => b.RoleId == id && b.Status == GlobalEnum.DataStatus.Enable && a.Id == b.MenuId).Any()).AsTreeCte(null, true).Distinct().OrderBy(a => a.Order).ToListAsync()
执行时sql里面自动加了排序字段，导致sql报错
![image](https://github.com/dotnetcore/FreeSql/assets/33016525/f0e2753d-fe21-42da-a3d3-fde6f3228b38)

#### 数据库版本
postgresql 10
#### 安装的Nuget包
![image](https://github.com/dotnetcore/FreeSql/assets/33016525/9ecc9889-e07d-4d5a-8275-f43be71c191f)

#### 具体版本
.net 6.0

**Comment by 2881099** [comment]
递归查询不支持distinct
