### ISSUE TITLE
低代码扩展 ZeroDbContext 操作非聚合根实体

### ISSUE THREAD

**Issue by jerry-nom** [dotnetcore/FreeSql#1756]
#### Feature 特性

低代码扩展 ZeroDbContext 现在是以聚合根为操作起点的，如果需要单独操作子实体和外部聚合根时怎么操作呢？例如例子里的用户角色关系，我现在要插入一个角色，该怎么操作呢？

**Comment by 2881099** [comment]
```c#
public ZeroDbContext(IFreeSql orm, TableDescriptor[] schemas)
{
   ...
}
```

这是 ctor 定义

单独操作子实体，可以直接在上层聚合根对象进行操作。

外部聚合根，需要独立再创建一个 ZeroDbContext 对象，schemas 是它对应的结构关系描述。

**Comment by jerry-nom** [comment]
感谢大佬回复，这样感觉有点繁琐，如果可以提供如下使用方式就方便了：
针对所有表建一个 ZeroDbContext，保存了所有表的结构关系，然后使用的地方根据指定操作起点对象及关联的对象来应用级联操作。看了下源码，想改，但是没有思路。

**Comment by 2881099** [comment]
TableDescripter[] 管理好这个就行

**Comment by gudufy** [comment]
我也觉得麻烦，失去了低代码的意义

**Comment by 2881099** [comment]
不依赖导航属性，每个表都是聚合根，每个表都有 TableDescriptor

**Comment by gudufy** [comment]
> 不依赖导航属性，每个表都是聚合根，每个表都有 TableDescriptor

对这个组件我有以下建议，望参考：

1、一个地方定义TableDescriptor（这样改后聚合根可手动指定），
2、TableDescriptor可由现有数据库生成
3、查询可通过json的方式来查
4、查询加上数据筛选器
5、查询加上分页

这样做以后大部分工作基本我调用一个增删改查的api就能完成了。不用再一个功能写一个api
