### ISSUE TITLE
达梦8数据库，Insert新增方法bug

### ISSUE THREAD

**Issue by zgmqdl** [dotnetcore/FreeSql#1759]
#### 问题描述及重现代码：

```c#
var rows = await _freeSql.Insert<Model>(entity).ExecuteInsertedAsync();
```
这个方法的返回值里面没有返回插入的实体Id
#### 数据库版本
DM8

#### 安装的Nuget包
 <PackageReference Include="FreeSql" Version="3.2.815" />
 <PackageReference Include="FreeSql.Provider.Dameng" Version="3.2.815" />

#### .net framework/. net core？ 及具体版本
.Net core7

**Comment by zgmqdl** [comment]
mysql也有这个问题

**Comment by 2881099** [comment]
看同步方法的注释

ExecuteInsered

**Comment by zgmqdl** [comment]
好的，看到了。“注意：此方法只有 Postgresql/SqlServer 有效果” 那达梦或者mysql有没有替代的方法

**Comment by 2881099** [comment]
没有，mariadb 可以，mysql 不行。

**Comment by luoyunchong** [comment]
可以使用仓储的方法，会回填id

https://freesql.net/guide/repository.html
