### ISSUE TITLE
只能单例注入orm吗？

### ISSUE THREAD

**Issue by tonglei2019** [dotnetcore/FreeSql#176]
services.AddScoped()//需要注入什么？

**Comment by 2881099** [comment]
IFreeSql是单例注入设计

仓储类，工作单元 是 Scope 设计

延伸问题，多个 IFreeSql 怎么注入 https://github.com/2881099/FreeSql/issues/44

**Comment by tonglei2019** [comment]
谢谢大神，使用IFreeSql 单例注入能支持多少人同时使用查询啊？

**Comment by 2881099** [comment]
> 谢谢大神，使用IFreeSql 单例注入能支持多少人同时使用查询啊？

线程安全的，多少人同时使用查询，取决于 max pool size设置，网络情况，还有数据库是否有锁

**Comment by tonglei2019** [comment]
好滴，辛苦大神了

**Comment by 2881099** [comment]
单例设计，也可以用 scope 注入，不过性能会有损耗

scope 设计，就不能单例注入了

**Comment by tonglei2019** [comment]
使用orm后服务器内存疯涨是为什么啊？

**Comment by tonglei2019** [comment]
求大神救命

**Comment by 2881099** [comment]
> 使用orm后服务器内存疯涨是为什么啊？

过程和原因，就这一句话无法判断
