### ISSUE TITLE
如何在一个项目中同时使用FreeSql.Provider.Oracle  FreeSql.Provider.OracleOledb ？

### ISSUE THREAD

**Issue by netty2019** [dotnetcore/FreeSql#1760]
我的项目中需要访问不同版本的Oracle数据库，使用了下面两个Oracle Provider，发现只有一个库起作用，另外一个用不了，去掉一个，另外一个就可以访问，
请教一下，有没有办法同时使用这个两个库，谢谢
PackageReference Include="FreeSql.Provider.Oracle" Version="3.2.815" 
 PackageReference Include="FreeSql.Provider.OracleOledb" Version="3.2.805"

**Comment by luoyunchong** [comment]
参考第9点

https://github.com/dotnetcore/FreeSql/discussions/1207
