### ISSUE TITLE
DateOnly 字段不能生成到插入语句中

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#1763]
#### 问题描述及重现代码：

实体中有DateOnly 的字段
```c#
        [Column(TypeName = "date")]
        public DateOnly begin { get; set; }
        [Column(TypeName = "date")]
        public DateOnly end { get; set; }
```
生成的插入语句中，缺少这两个字段

#### 数据库版本 
mysql 10.5.5-MariaDB

#### nuget包：
 FreeSql.All  3.2.820

#### 目标框架: .net 6.0, dotnet --version 8.0.200

```[tasklist]
### Tasks
```

**Comment by sqlite-me** [comment]
特性使用的是 System.ComponentModel.DataAnnotations 命令空间里的

**Comment by 2881099** [comment]
只有sqlserver处理了新类型
