### ISSUE TITLE
dbcontext.Remove(Expression<Func<TEntity, bool>> predicate)直接返回影响行数

### ISSUE THREAD

**Issue by yaoze1989** [dotnetcore/FreeSql#1764]
dbcontext.Remove(Expression<Func<TEntity, bool>> predicate)直接返回影响行数，接着调用savechange返回0；如不调用savechange则数据库不会删除数据。

efcore：类似方法不需要调用 savechange
ps：希望update也支持使用Expression批量更新

var dbSet = dbContext.Set<t_account>();
Log("操作前：" + dbSet.Select.Where(f => f.FID > accountId).Count());
var ret1 = dbSet.Remove(f => f.FID > accountId);
Log("remove条数：" + ret1);
var ret = dbContext.SaveChanges();
Log("savechange条数：" + ret);
Log("删除后：" + dbSet.Select.Where(f => f.FID > accountId).Count());

![image](https://github.com/dotnetcore/FreeSql/assets/12637847/12facce7-23a4-4f82-a525-a5d3308a5f8c)

**Comment by 2881099** [comment]
dbcontext模式定型了，不适合改造，比不过efcore，适合过渡。

推荐使用 repository
