### ISSUE TITLE
Unity中正确导入FreeSql.Provider.MySqlConnector

### ISSUE THREAD

**Issue by 9a6c** [dotnetcore/FreeSql#1767]
#### 简要描述原因
FreeSql.Provider.MySqlConnector 依赖MySqlConnector2.0.0，在unity中导入后有报错信息。 MySqlConnector最新版本(2.3.6)可以正确导入，无报错信息。
![image](https://github.com/dotnetcore/FreeSql/assets/51264840/e5b43bf6-3fa4-468d-a806-7c5fbe59064f)

#### 使用场景
unity中使用FreeSql.和FreeSql.Provider.MySqlConnector 访问数据库

**Comment by 2881099** [comment]
安装 FreeSql.Provider.MySqlConnector

之后，再安装 MySqlConnector 新版本

**Comment by 9a6c** [comment]
您的意思是安装 FreeSql.Provider.MySqlConnector后，卸载依赖的MySqlConnector2.0.0， 然后下载新版本MySqlConnector， FreeSql.Provider.MySqlConnector对MySqlConnector版本对MySqlConnector没有限制？

**Comment by 2881099** [comment]
同时安装。

**Comment by 9a6c** [comment]
感谢您的回复， 我在unity中使用的nuget for unity插件来管理包， 当我安装了FreeSql.Provider.MySqlConnector， 需要将MySqlConnector2.0.0删除后，才可以安装MySqlConnector的其它版本， 我目前简单的测试了一下，可以正确连接和插入数据
