### ISSUE TITLE
希望增加 fsql.Date() 方法，可以直接访问到数据库的当前时间

### ISSUE THREAD

**Issue by ping9719** [dotnetcore/FreeSql#1772]
希望增加 fsql.Date() 方法，可以直接访问到数据库的当前时间，我用于校对本地的时间和数据库时间的差距。
可以是 fsql.Date() 也可以是 fsql.Ado.Date()。

相当于执行（mysql） fsql.Ado.Query<DateTime>("SELECT NOW();");
在不同的数据库中可能不一样。

**Comment by luoyunchong** [comment]
https://freesql.net/guide/ado.html#%E6%9F%A5%E8%AF%A2-sql-%E8%BF%94%E5%9B%9E%E5%AE%9E%E4%BD%93

```
//SELECT now(), utc_timestamp()
var result = fsql.Ado.QuerySingle(() => new
{
    DateTime.Now,
    DateTime.UtcNow
});
```
