### ISSUE TITLE
Sqlite 数据库子查询枚举转换问题

### ISSUE THREAD

**Issue by 2270969436** [dotnetcore/FreeSql#1780]
使用的是DbContext的方式。

#### 问题描述及重现代码：
这里将枚举映射成字符串类型
![image](https://github.com/dotnetcore/FreeSql/assets/45121491/025ed503-9f42-4f15-9b31-373a84ce047d)
查询的时候
![image](https://github.com/dotnetcore/FreeSql/assets/45121491/0fd051dc-405e-4677-8796-eae79ae523f4)
![image](https://github.com/dotnetcore/FreeSql/assets/45121491/e6e92b34-e433-46ae-8339-e9657cac88c2)
单表查询用枚举==枚举的方式是没问题的，仅在使用子查询的时候会出现这个问题，
后面改写成.Equals(Enum.ToString())才能正常查询出自己需要的数据。

#### 数据库版本
Sqlite 3

#### 安装的Nuget包
v3.2.820

#### .net framework/. net core？ 及具体版本
Net 8.0

**Comment by 2881099** [comment]
.HasColumnType("...").Help().MapType(typeof(string))

要加上 MapType

**Comment by 2270969436** [comment]
您好，您的邮件已收到。我会尽快给您回复。
