### ISSUE TITLE
mysql连接数据库字符串如果密码里面带有分号则属于特殊字符，导致无法连接

### ISSUE THREAD

**Issue by 2007cc** [dotnetcore/FreeSql#1783]
mysql连接数据库字符串如果密码里面带有分号则属于特殊字符，导致无法连接，
如 Data Source=localhost;Port=3306;User ID=root;Password=3~7AE2^!nlFO9r;w; Initial Catalog=test;Charset=utf8; SslMode=none;Min pool size=1

**Comment by 2881099** [comment]
用 MySqlConnectionStringBuilder 类构建
