### ISSUE TITLE
FreeSql Unity使用问题

### ISSUE THREAD

**Issue by 9a6c** [dotnetcore/FreeSql#1796]
unity2021.3.35f1  .net 45
FreeSql最新   .net 45 达梦数据库

使用FreeSql在Unity编辑器中正常，打出pc包或其它(Unity Server 或  Android)
已尝试Unity mono与il2cpp方式打包工程，都会有如下错误信息出现。如下图
![21fd80f0bc550b189cc6cb82f077596](https://github.com/dotnetcore/FreeSql/assets/51264840/6ff5a668-f286-4d74-b92f-5516e7ff18ad)

异常信息：
从 [Freesol:Master Database] Connection string error, please check. 开始

其它问题：
freesql 是否支持unity mono与il2cpp模式

如上问题有解决方法吗？

**Comment by 9a6c** [comment]
异常可能从这里出现
![image](https://github.com/dotnetcore/FreeSql/assets/51264840/be462745-a3e8-4848-b5fd-9612b7588fb0)

看不出问题
![5d485be83e7d59a91fd1468e9906d78](https://github.com/dotnetcore/FreeSql/assets/51264840/91d530cf-5cc6-4b2e-a265-6ac6a9a2553f)
![cd1a86888574acfaf10111c6a2b1441](https://github.com/dotnetcore/FreeSql/assets/51264840/1b7849bf-7947-4676-b1d9-65159d5368b5)

**Comment by 2881099** [comment]
据我所知，il2cpp不支持，除非aot编译，貌似是两个东西。

或者你测试一下原生ado.net如何进行访问

new DmConnection(str).Open()

**Comment by 9a6c** [comment]
我用unity写了一个超简单的demo， 发现freesql 和 dm驱动，都是正常的。

**Comment by 9a6c** [comment]
解决方法：使用netstandard2.1版本
