### ISSUE TITLE
pgsql 使用freesql生成器生成数组类型错误

### ISSUE THREAD

**Issue by zkh-balance** [dotnetcore/FreeSql#1798]
#### 问题描述及重现代码：

```c#
pgsql type字段为int 维度是1；
dbfirst 生成的Dbtype是,DbType = "int" ； 应该是 DbType = "int[]" 或者不生成DbType
		/// <summary>
		/// 类型
		/// </summary>
		[JsonProperty, Column(Name = "type",DbType = "int" )]
		public int[] Type { get; set; }

```

#### 数据库版本

select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 14.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
(1 row)

#### 安装的Nuget包
  <ItemGroup>
    <PackageReference Include="FreeSql" Version="3.2.806-preview20231120" />
    <PackageReference Include="FreeSql.DbContext" Version="3.2.806-preview20231120" />
    <PackageReference Include="FreeSql.Provider.PostgreSQL" Version="3.2.806-preview20231120" />
    <PackageReference Include="FreeSql.Repository" Version="3.2.806-preview20231120" />
  </ItemGroup>

#### .net framework/. net core？ 及具体版本

    <TargetFramework>net6.0</TargetFramework>

**Comment by 2881099** [comment]
暂时，先修改模板重新生成解决
