### ISSUE TITLE
通过SSH与TCP/IP连接MySql

### ISSUE THREAD

**Issue by ALer-R** [dotnetcore/FreeSql#180]
[通过SSH与TCP/IP连接MySql](https://dev.mysql.com/doc/connector-net/en/connector-net-ssh-tunneling.html#connector-net-ssh-tunneling-example-1)

```cs
var builder = new MySqlConnectionStringBuilder();
builder.UserID = "myUser";
builder.Password = "test";
builder.Server = "localhost";
builder.SshHostName = "10.0.0.2";
builder.SshUserName = "mySshUser";
builder.SshPassword = "sshtest";
builder.SshPort= "23";
using (var connection = new MySqlConnection(builder.ConnectionString))
{
  connection.Open();
  ...
  connection.Close();
}
```

**Comment by 2881099** [comment]
FreeSql.Provider.MySql 用这个包高版本支持

FreeSql.Provider.MySqlConnector 这个不支持

**Comment by lhtuling** [comment]
> FreeSql.Provider.MySql 用这个包高版本支持
> 
> FreeSql.Provider.MySqlConnector 这个不支持

支持SSH 连接数据库么  直接修改连接字符串  还是说有什么特殊方法   现在有个需求要用SSH连接并数据库做操作！

**Comment by 2881099** [comment]
补充：

```c#
/// <summary>
/// 不要用在单例
/// </summary>
class MySqlSshFreeSql : IFreeSql
{
    IDisposable _sshClient;
    int _localPort;
    IFreeSql _localFsql;

    public SshMySqlFreeSql(string server, string user, string pass, string keyfile, string passPhrase, int port, string connectionString)
    {
        (_sshClient, _localPort) = ConnectSsh(server, user, pass, keyfile, passPhrase, port);
        var cb = new MySqlConnectionStringBuilder(connectionString);
        cb.Server = "127.0.0.1";
        cb.Port = _localPort;
        cb.MinimumPoolSize = 1;
        _localFsql = new FreeSqlBuilder()
            .UseConnectionString(DataType.MySql, connectionString)
            .Build();
    }
    public void Dispose()
    {
        _localFsql.Dispose();
        _sshClient.Dispose();
    }

    public IAdo Ado => _localFsql.Ado;
    public IAop Aop => _localFsql.Aop;
    public ICodeFirst CodeFirst => _localFsql.CodeFirst;
    public IDbFirst DbFirst => _localFsql.DbFirst;
    public GlobalFilter GlobalFilter => _localFsql.GlobalFilter;

    public void Transaction(Action handler) => _localFsql.Transaction(handler);
    public void Transaction(IsolationLevel isolationLevel, Action handler) => _localFsql.Transaction(isolationLevel, handler);

    public ISelect<T1> Select<T1>() where T1 : class => _localFsql.Select<T1>();
    public ISelect<T1> Select<T1>(object dywhere) where T1 : class => Select<T1>().WhereDynamic(dywhere);

    public IDelete<T1> Delete<T1>() where T1 : class => _localFsql.Delete<T1>();
    public IDelete<T1> Delete<T1>(object dywhere) where T1 : class => Delete<T1>().WhereDynamic(dywhere);

    public IUpdate<T1> Update<T1>() where T1 : class => _localFsql.Update<T1>();
    public IUpdate<T1> Update<T1>(object dywhere) where T1 : class => Update<T1>().WhereDynamic(dywhere);

    public IInsert<T1> Insert<T1>() where T1 : class => _localFsql.Insert<T1>();
    public IInsert<T1> Insert<T1>(T1 source) where T1 : class => Insert<T1>().AppendData(source);
    public IInsert<T1> Insert<T1>(T1[] source) where T1 : class => Insert<T1>().AppendData(source);
    public IInsert<T1> Insert<T1>(List<T1> source) where T1 : class => Insert<T1>().AppendData(source);
    public IInsert<T1> Insert<T1>(IEnumerable<T1> source) where T1 : class => Insert<T1>().AppendData(source);

    public IInsertOrUpdate<T1> InsertOrUpdate<T1>() where T1 : class => _localFsql.InsertOrUpdate<T1>();
}
```

**Comment by Allvirus** [comment]
补充：ConnectSsh方法
`

    using Renci.SshNet;
    public static (SshClient SshClient, uint Port) ConnectSsh(string sshHostName, string sshUserName, string sshPassword = null, string sshKeyFile = null, string sshPassPhrase = null, int sshPort = 22, string databaseServer = "localhost", int databasePort = 3306)
        {
            // check arguments
            if (string.IsNullOrEmpty(sshHostName))
                throw new ArgumentException($"{nameof(sshHostName)} must be specified.", nameof(sshHostName));
            if (string.IsNullOrEmpty(sshHostName))
                throw new ArgumentException($"{nameof(sshUserName)} must be specified.", nameof(sshUserName));
            if (string.IsNullOrEmpty(sshPassword) && string.IsNullOrEmpty(sshKeyFile))
                throw new ArgumentException($"One of {nameof(sshPassword)} and {nameof(sshKeyFile)} must be specified.");
            if (string.IsNullOrEmpty(databaseServer))
                throw new ArgumentException($"{nameof(databaseServer)} must be specified.", nameof(databaseServer));

            // define the authentication methods to use (in order)
            var authenticationMethods = new List<AuthenticationMethod>();
            if (!string.IsNullOrEmpty(sshKeyFile))
            {
                authenticationMethods.Add(new PrivateKeyAuthenticationMethod(sshUserName,
                    new PrivateKeyFile(sshKeyFile, string.IsNullOrEmpty(sshPassPhrase) ? null : sshPassPhrase)));
            }
            if (!string.IsNullOrEmpty(sshPassword))
            {
                authenticationMethods.Add(new PasswordAuthenticationMethod(sshUserName, sshPassword));
            }

            // connect to the SSH server
            var sshClient = new SshClient(new ConnectionInfo(sshHostName, sshPort, sshUserName, authenticationMethods.ToArray()));
            sshClient.Connect();

            // forward a local port to the database server and port, using the SSH server
            var forwardedPort = new ForwardedPortLocal("127.0.0.1", databaseServer, (uint)databasePort);
            sshClient.AddForwardedPort(forwardedPort);
            forwardedPort.Start();

            return (sshClient, forwardedPort.BoundPort);
        }
`

**Comment by ALer-R** [comment]
**推荐 SSH.NET 另开隧道，或其他 SSH Tunnel 技术实现**

```
The SSH Tunneling (port forwarding) feature, which was added to support MySQL products in making secure connections on Windows, is no longer needed by other products. Now, using an alternative such as Oracle Cloud Infrastructure or SSH.NET to create a tunnel is preferred. The related connection options (, , , , , and ) are no longer valid when making Connector/NET connections, starting with this release. SshHostNameSshKeyFileSshPassPhraseSshPasswordSshPortSshUserName

[来源](https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-0-24.html)
```



**注意：下图用例未经过大规模测试**
![D){E9K6BE83PFJXYL@ O5TL](https://user-images.githubusercontent.com/27998280/154879222-b3a918d7-1e41-4a5d-ae54-794999088761.png)
