### ISSUE TITLE
讨论一下, 增加数据库默认值 特性的可行性.

### ISSUE THREAD

**Issue by easy999000** [dotnetcore/FreeSql#1803]
codefirst的时候,创建表和字段.大部分字段特性都已经支持.
但是唯独没有 "字段默认值"这个基础特性.
默认值这个特性是既普遍,又常用的一个特性,而且大部分数据库都需要设置这个特性.
所以说我认为freesql应该支持这个特性.
这种基础的东西,我相信freesql肯定的考虑过的,至于为什么没有支持,不得而知.

我有想过自己写一个自定义特性,来实现这个功能,但是默认值这个特性,并不是一个冷门,独特的特性.他是一个普遍的,如果需要我自己来写,那么大家都需要自己写一个吗, 这是重复的造轮子.  

我的想法可能比较简单,默认值这个特性,就用字符串类型就可以了,把数据库的默认值参数,存进来.
创建表或字段的时候,把这个默认值的这一段,拼到 sql里面就好了. 

我把事情想的比较简单, 如果这其中 有什么难以处理的问题. 可以讨论一下, 也好让我死心.

**Comment by densen2014** [comment]
这么多种数据库。实现这个功能收益不高

**Comment by easy999000** [comment]
> 这么多种数据库。实现这个功能收益不高

这个收益怎么计算呢,  默认值不是少数数据库才有的特性,也不是很偏门很冷门的特性.
这个支持了,我感觉收益是非常大的.
其次,需要花费的工时成本有多少,我感觉不会很多, 把字符串插入到创建语句里面而已.

**Comment by zxm13588** [comment]
[Column(IsNullable=false)]
public int filed{get;set;} =1;

上面这么写，mysql可以生成默认值，其他的你可以试试
