### ISSUE TITLE
AuditValue 在插入时被重复执行

### ISSUE THREAD

**Issue by infFox** [dotnetcore/FreeSql#1804]
#### 问题描述及重现代码：
使用 `SomeRepo.InsertAsync(obj)` 插入新记录时，实际的 insert 语句执行了一次，但 `AuditValue` 会被执行两遍，导致字段值被重复处理。

**下断点可以发现**
第一次显示 `AuditValueType` 为 `Insert`
![image](https://github.com/dotnetcore/FreeSql/assets/96704962/6550665f-9971-4f65-bafa-5c630f672e2a)

第二次显示 `AuditValueType` 为 `Update`
![image](https://github.com/dotnetcore/FreeSql/assets/96704962/24124ee4-314e-4b30-92cc-d41554318a4e)

**AuditValue 的代码：**
```c#
        // 使用 AuditValue 实现对带 [Aes] 的字段自动加密
        fsql.Aop.AuditValue += (_, e) =>
        {
            if (e.Column.CsType == typeof(string))
            {
                var attr = e.Property.GetCustomAttribute<AesAttribute>(false);
                if (attr != null)
                {
                    // 使用 base64 模拟加密过程
                    var newval= Convert.ToBase64String(Encoding.UTF8.GetBytes(e.Value.ToString()));
                    Log.Error("进行加密 {Name} {Old} {New}", attr.KeyName, e.Value, newval);
                    e.Value = newval;
                }
            }
        };
```
**打印的日志：**
![image](https://github.com/dotnetcore/FreeSql/assets/96704962/35a7702e-94ae-4cd6-b086-1aa9fc90143a)

#### 数据库版本
MySQL 5.7.23

#### 安装的Nuget包
- freesql 3.2.822
- freesql.provider.mysqlconnector 3.2.822
- freesql.repository 3.2.822

#### .net framework/. net core？ 及具体版本
.NET 8.0.101

**Comment by 2881099** [comment]
提供一个简易复现的demo

**Comment by infFox** [comment]
在 [demo](https://github.com/infFox/AuditValue) 里试了一下发现 AuditValue 还是被执行了两次，但是这回 insert 的语句中只使用了第一次处理后的值。

![image](https://github.com/dotnetcore/FreeSql/assets/96704962/3f6f220c-5bca-408b-8a58-68e6ef388aa8)

然后在原来的项目里重新尝试，虽然还是被执行了两次，也是只使用了第一次处理后的值

![image](https://github.com/dotnetcore/FreeSql/assets/96704962/8cde11d5-def1-4ec4-aacb-c5fe1c62f3ec)

但是之前测试的时候 insert 语句里的值是被处理了两遍的。。。不过目前复现不出来了，可能是之前眼花了😂
