### ISSUE TITLE
ClickHouse PARTITION BY support in CodeFirst CREATE TABLE

### ISSUE THREAD

**Issue by wizzard0** [dotnetcore/FreeSql#1814]
For large clickhouse tables, partition key is essential. Currently there's no way to specify partition key (usually a function from the timestamp primary key column, like toYYYYMM(time)), and looking at the clickhouse provider there's no code that could insert the PARTITION BY clause in CREATE TABLE statement builder either.

Since the partition can be an arbitrary function, this calls for a new property in the TableAttribute, not ColumnAttribute

Thanks in advance!

**Comment by d4ilys** [comment]
```c#
    public class Table
    {
        [Column(IsPrimary = true, IsIdentity = true)]
        public int Id { get; set; }
		
        public string Name { get; set; }

        [ClickHousePartition("toYYYYMM({0})")]   //partition attribute , toYYYYMM({0}) is string format
        [Column(Name = "create_time")]
        public DateTime CreateTime { get; set; }
    }
```

~~~sql
CREATE TABLE IF NOT EXISTS `Table` (  
  `Id` Int32, 
  `Name` Nullable(String), 
  `create_time` DateTime('Asia/Shanghai'), 
   PRIMARY KEY ( `Id` ) 
) 
ENGINE = MergeTree() 
ORDER BY ( `Id` )  
PARTITION BY toYYYYMM(`create_time`)    -- table partition
SETTINGS index_granularity = 8192
~~~

Does this design meet your needs, or do you have any good suggestions

**Comment by 2881099** [comment]
FreeSql.Provider.ClickHouse 3.2.826-preview20240530

**Comment by wizzard0** [comment]
Missed the email, sorry! Yes this meets the needs. Also the FreeSql currently doesn't properly handle Array(Int64) columns while the underlying Clickhouse.Client works OK, but I'll create a separate issue for that
