### ISSUE TITLE
我观察sqlsrver profiler,发现每次查询都会出现4次select1

### ISSUE THREAD

**Issue by zjbdiy** [dotnetcore/FreeSql#1816]
#### 问题描述及重现代码：
private readonly IFreeSql fsql = new FreeSqlBuilder()
    .UseConnectionString(DataType.SqlServer, @"server=.\sql2016;database=v4server;uid=sa;pwd=sakey")
    .UseAutoSyncStructure(false).Build();

public DataTable PostTestTable()
{
    var dic = new Dictionary<string, object>
    {
        { "UserId", UserId }
    };

    return fsql.Ado.CommandFluent($"select 222", dic).ExecuteDataTable();

    //return new DataTable();
}

#### 数据库版本
sqlserver 2016

#### 安装的Nuget包
<PackageReference Include="FreeSql.Provider.SqlServer" Version="3.2.825" />

#### .net framework/. net core？ 及具体版本
netcore 6

![image](https://github.com/dotnetcore/FreeSql/assets/35357314/c08e1b8d-215a-433c-9196-6ad4716b4d0c)
不知道是bug 还是设计使然

**Comment by 2881099** [comment]
连接串min pool size=1

以第二次执行为准

**Comment by zjbdiy** [comment]
ok 3Q
