### ISSUE TITLE
特殊情况下，添加暂时关闭乐观锁的方法

### ISSUE THREAD

**Issue by MoDao1990217** [dotnetcore/FreeSql#1817]
#### Feature 特性
可以手动关闭乐观锁检查
```c#
// c# code
```

#### 简要描述原因
数据表中已经添加了乐观锁，乐观锁需要先查出来，才能更新，但在某些特定情况下，有需要大批量更新，已经确定这个更新的数据不需要效验乐观锁，大批量更新时先查再更橷，性能会成问题。可否加一个特定的方法，在某些情况下，可以关闭乐观锁效验。
```c#
// c# code
```

#### 使用场景
批量更新
```c#
// c# code
```

**Comment by 2881099** [comment]
转成字典，用UpdateDict解决一下

**Comment by MoDao1990217** [comment]
> 转成字典，用UpdateDict解决一下

嗯，这样是也可以。
