### ISSUE TITLE
查询JArray的第一个元素报错

### ISSUE THREAD

**Issue by netssfy** [dotnetcore/FreeSql#1818]
#### 问题描述及重现代码：

```c#
public class POCO
{
  public JArray Tags { get; set; };
}

await FreeSql.Select<Hotel>().Where(h => (string)h.Tags[0]! == "tag a").FirstAsync();
```
生成的SQL为
SELECT p."tags"
FROM "poco" p
WHERE (p."tags"->0  = 'tag a')
导致数据库报错22P02: invalid input syntax for type json

正确的sql应该是WHERE (p."tags"->>0  = 'tag a')

不知道是生成SQL的代码有问题，还是我where里的表达式写的不对

#### 数据库版本
psql 16

#### 安装的Nuget包
<PackageReference Include="FreeSql" Version="3.2.825" />
<PackageReference Include="FreeSql.Provider.PostgreSQL" Version="3.2.825" />

#### .net framework/. net core？ 及具体版本
.net8.0

**Comment by 2881099** [comment]
http://www.postgres.cn/docs/12/functions-json.html

你的数据库定义的是jsonb类型，就可以.

如上，你说不行，可能是行为字段类型是text不是jsonb

**Comment by 2881099** [comment]
解决办法，自定义函数解析，或者修改类型，或者lambda转一次jsonb再使用

**Comment by netssfy** [comment]
我找到解决办法了
因为生成的SQL是->操作符而不是->>，所以只要把
await FreeSql.Select<Hotel>().Where(h => (string)h.Tags[0]! == "tag a").FirstAsync();
改成
await FreeSql.Select<Hotel>().Where(h => (string)h.Tags[0]! == JsonConvert.SerializeObject("tag a")).FirstAsync();
