### ISSUE TITLE
where字符串插值枚举被转换成数字

### ISSUE THREAD

**Issue by samueltian666** [dotnetcore/FreeSql#1820]
string k = $"test{联通}";
var data = await db.Select<Config>().Where(x => x.k == $"test{联通}").FirstAsync(x => x.v);
//WHERE (a."k" = 'test'||coalesce((10010)::text, '')||'')
应该默认为字符

**Comment by samueltian666** [comment]
3.2.825

**Comment by 2881099** [comment]
用变量解决
