### ISSUE TITLE
whereif条件生成sql有问题

### ISSUE THREAD

**Issue by renxuefeng** [dotnetcore/FreeSql#1821]
#### 问题描述及重现代码：

```c#
.WhereIf(!string.IsNullOrEmpty(diagnosisText),
                    (reportResult, reportStatus, favoritesReport, diagnosisResult, auditResult,
                        diagnosisReportResult) => (diagnosisReportResult.Id > 0
                        ? diagnosisReportResult.DiagnosisDiagnose.Contains(diagnosisText)
                        : auditResult.DiagnosisDiagnose.Contains(diagnosisText)))
```

生成的sql：
AND ( CASE WHEN f.[id] > 0 THEN ( f.[DiagnosisDiagnose] ) LIKE N'%11%' ELSE ( e.[DiagnosisDiagnose] ) LIKE N'%11%' END ) 

#### 数据库版本
sqlserver

#### 安装的Nuget包
freesql 3.2.815

#### .net framework/. net core？ 及具体版本
.netcore 6.0

**Comment by 2881099** [comment]
哪里有问题

**Comment by renxuefeng** [comment]
生成的sql执行报错
[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]关键字 'LIKE' 附近有语法错误。 (156)

**Comment by renxuefeng** [comment]
> (diagnosisReportResult.Id > 0 ? diagnosisReportResult.DiagnosisDiagnose : auditResult.DiagnosisDiagnose)
> 
> .Contains(diagnosisText)
> 
> 这样呢？

这样写没问题
