### ISSUE TITLE
update语句，二元运算解析出错

### ISSUE THREAD

**Issue by LiaoLiaoWuJu** [dotnetcore/FreeSql#184]
` var now = DateTime.Now;
short notstarted = (short)ExaminationState.NotStarted, ongoing = (short)ExaminationState.Ongoing, finished = (short)ExaminationState.Finished;

fsql.Update<Examination>().Set(it => it.StateId == (it.EndTime < now ? finished : ongoing)).Where(it => it.StateId == notstarted && it.StartTime <= now).ExecuteAffrows();
`
解析出错![QQ图片20200116145708](https://user-images.githubusercontent.com/49226625/72500939-8eb5e780-3870-11ea-9816-cc6239866559.png)

**Comment by pjy612** [comment]
这种应该不支持这么写吧？
先 ToSql 试试 看看生成的语句是啥？

**Comment by LiaoLiaoWuJu** [comment]
> 这种应该不支持这么写吧？
> 先 ToSql 试试 看看生成的语句是啥？

支持这种写法，解析出错，没办法ToSql的。

**Comment by pjy612** [comment]
> > 这种应该不支持这么写吧？
> > 先 ToSql 试试 看看生成的语句是啥？
> 
> 支持这种写法，解析出错，没办法ToSql的。

说的是 这种解析不支持 = =。你要不要试试包一个自定义解析试试？
或者先全部查出来 再改完 SetSource Update 回去。

**Comment by LiaoLiaoWuJu** [comment]
> > > 这种应该不支持这么写吧？
> > > 先 ToSql 试试 看看生成的语句是啥？
> > 
> > 
> > 支持这种写法，解析出错，没办法ToSql的。
> 
> 说的是 这种解析不支持 = =。你要不要试试包一个自定义解析试试？
> 或者先全部查出来 再改完 SetSource Update 回去。

已经换回原来写的方法
fsql.Update<Examination>().Set(it => new Examination { StateId = (it.EndTime < now ? finished : ongoing) }).Where(it => it.StateId == notstarted && it.StartTime <= now).ExecuteAffrows();
等叶老板调整

**Comment by 2881099** [comment]
原因是与 MapType 处理冲突，现在是分开解决的
