### ISSUE TITLE
加载数据库失败：子查询返回的值不止一个。。。

### ISSUE THREAD

**Issue by KaryoYou** [dotnetcore/FreeSql#1844]
加载数据库失败
子查询返回的值不止一个。当子查询跟随在 =、!=、<、<=、>、>= 之后，或子查询用作表达式时，这种情况是不允许的。
数据库连接串：Data Source=IP地址,1433;Initial Catalog=;User ID=sa;Password=密码;Pooling=true;Max Pool Size=5

![无标题](https://github.com/dotnetcore/FreeSql/assets/62101443/6e0c0fcf-58d5-45da-b68f-938b4c917741)

sql server 2008 r2 的数据库，ssms管理器正常curd，WPF项目也能正常curd

**Comment by 2881099** [comment]
用命令行生成工具 FreeSql.Generator

这个工具如果生成失败，控制台上面会打印有关的SQL

**Comment by KaryoYou** [comment]
命令行生产工具 FreeSql.Generator 可以生成 FreeSql.Tools 项目打不开的数据库的所有表为实体，问题已解决。

**Comment by KaryoYou** [comment]
命令行生产工具 FreeSql.Generator 的输出文件(.txt和.bat)会因为不同用户的系统设置受到严重性影响，无法正常读取和使用。
怀疑是保存格式引起：UTF8-BOM 。
![1](https://github.com/dotnetcore/FreeSql/assets/62101443/fbe4fd1f-e31a-402f-882b-de4f68eb0320)
![2](https://github.com/dotnetcore/FreeSql/assets/62101443/03d5a0e5-a204-4105-9070-332fa554c45f)
![4](https://github.com/dotnetcore/FreeSql/assets/62101443/7152e985-6d7b-43d3-9189-2ed8a723cded)

修改并另存为UTF8格式后，正常使用。
![1-1](https://github.com/dotnetcore/FreeSql/assets/62101443/e4776bf3-ef52-4c69-9817-219cc62845ba)
![2-1](https://github.com/dotnetcore/FreeSql/assets/62101443/652eb7e0-d72e-443a-9f80-3bf7af74c902)
![5](https://github.com/dotnetcore/FreeSql/assets/62101443/9dbe0319-4b0a-4bcd-ad1f-06991ca5c967)


如何自定义模板还得研究一下。
