### ISSUE TITLE
加载数据库失败

### ISSUE THREAD

**Issue by lostluna1** [dotnetcore/FreeSql#1845]
【主库】状态不可用，等待后台检查程序恢复方可使用。Connection request timed out
数据库连接串：user id=system;password=asd123;data source=//192.168.200.128:1521/MES;Pooling=true;Max Pool Size=5

**Comment by densen2014** [comment]
急着端口都写错了

**Comment by hjkl950217** [comment]
确实是链接字符串写错了

**Comment by 2881099** [comment]
可能连接的是 firebird
