### ISSUE TITLE
FreeSql.Provider.SqliteCore 打开sqlite数据库 报错

### ISSUE THREAD

**Issue by tqsoft888** [dotnetcore/FreeSql#1847]
问题描述及重现代码：

【主库】Status unavailable, waiting for recovery. 未能加载文件或程序集“System.Data.SQLite.SEE.License, Version=1.0.115.5, Culture=neutral, PublicKeyToken=433d9874d0bb98c5”或它的某一个依赖项。系统找不到指定的文件

![image](https://github.com/dotnetcore/FreeSql/assets/139480907/e8784159-2455-4358-8fb5-179aa93b3230)

安装的Nuget包
FreeSql.Provider.SqliteCore（3.2.830）

 .net framework 4.8

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/discussions/1207

9、同时安装了FreeSql.Provider.MySql和FreeSql.Provider.MySqlConnector 无法使用 ExecuteMySqlBulkCopy 方法
二个共存时，默认根据 FreeSql.Provider.MySql 得到 的MySqlProvider 实现 ，可在UseConnectionStrings中第三个参数指定Type

UseConnectionStrings(DataType.MySql,"连接串",Type.GetType("FreeSql.MySql.MySqlProvider`1,FreeSql.Provider.MySqlConnector"));


第9点，Sqlite和SqliteCore也同样会默认Sqlite，Framework 包管理有问题，删除包没有删除bin中，依旧使用了Sqlite包


二个包都安装时，可配置第三个参数，使用SqliteCore
```
UseConnectionStrings(DataType.Sqlite,"连接串",Type.GetType("FreeSql.Sqlite.SqliteProvider`1,FreeSql.Provider.SqliteCore"));
```

https://github.com/dotnetcore/FreeSql/blob/a5d75956479e78191c1a9e8923ae618b5289ba23/FreeSql/FreeSqlBuilder.cs#L282
