### ISSUE TITLE
Dbfirst中获取List<DbColumnInfo>列集合可否按照数据库中顺序来，或者有个顺序字段标识，sqlserver

### ISSUE THREAD

**Issue by yezi34880** [dotnetcore/FreeSql#185]
Dbfirst中获取List<DbColumnInfo>列集合可否按照数据库中顺序来，或者有个顺序字段标识，sqlserver

**Comment by 2881099** [comment]
这个需求表面看非常简单，不过因为和数据库schema存储方式差异非常大，不好实现。

目前的排序规则是，主键排最前面，随后是外键，随后是普通字段

**Comment by 2881099** [comment]
这个功能增加好了，DbColumnInfo Pisition
