### ISSUE TITLE
SQLSERVER 有时间类型做主键时，批量更新Case语句报错

### ISSUE THREAD

**Issue by chenbinhy** [dotnetcore/FreeSql#1857]
#### 问题描述及重现代码：
SQLSERVER数据库， 有时间类型做主键时，批量更新Case语句报错，Case语句的时间格式与表格中的时间格式不一致
```c#
FreeSql.Update<T_DATA>().
                SetSource(new List<T_DATA>() { B1,B2 }).ExecuteAffrows()
// c# code
```

#### 数据库版本
SQLSERVER2022

#### 安装的Nuget包
3.2.821，最新版本也试过

**Comment by 2881099** [comment]
不要用时间做主键，Date time有毫秒精度的问题。

如果一定要用时间做组件，可以考虑把它转换成int类型，存储时间戳值。
