### ISSUE TITLE
GroupBy 类型转换错误

### ISSUE THREAD

**Issue by xime2009** [dotnetcore/FreeSql#186]
![image](https://user-images.githubusercontent.com/53549764/72591144-61ce0700-393a-11ea-868e-760cafcf5b7c.png)

**Comment by 2881099** [comment]
刚到家测试，问题确实存在。

.ToList(a => new { sum = a.Sum(a.Value.Item1.Id) }) 

可以先这样处理

**Comment by 2881099** [comment]
.ToList(a => (decimal)a.Sum(a.Value.TypeGuid))

这样也是 ok 的
