### ISSUE TITLE
我想要基于FreeSql 和官方的MongoDB 驱动来通过FreeSql的实现Mongo数据库的相应操作

### ISSUE THREAD

**Issue by AlianBlank** [dotnetcore/FreeSql#1862]
我想要基于FreeSql 和官方的MongoDB 驱动来通过FreeSql的实现Mongo数据库的相应操作.
我现在的需求会在Mongo 和mysql 或者sqlserver 这样的数据库之前来回切换.可能有不同的用户.
但是我想要对外提供FreeSQL的操作方式.将mongo 的部分封装为下层实现.让上层的用户无感知的切换数据库.
期待您的回复.

**Comment by 2881099** [comment]
mongodb和关系型数据库的用法，区别还是蛮大的。

关系型数据库可能会用到大量的多表查，mongodb讲究数据冗余存储，尽量的不用连表。

基于种种区别，很难使用orm无缝切换。

个人建议，在应用创建 IRepository 做增删改查对外开放，避免在业务层随意使用orm方法，导致切换兼容性问题。

**Comment by AlianBlank** [comment]
那我如果按照您的建议方式.只对外提供IRepository 方式的CRUD的方式.那有没有相应的接入方式或者文档参考呢?这样我就直接封闭了大部分Orm的功能.直接在接口层限制上层用户的使用.因为我的目标用户的游戏服务器群体.不会有太多的表关联这样的需求.

**Comment by 2881099** [comment]
单表增生改查很简单啊，接口的定义可以参考 FreeSql.IBaseRepository 代码
