### ISSUE TITLE
希望增加select时排除某些字段的功能 

### ISSUE THREAD

**Issue by chatop2020** [dotnetcore/FreeSql#1866]
#### Feature 特性
希望增加select时排除某些字段的功能 
```c#
var result = fsql.Select<YourEntity>()
                 .Where(e => e.SomeCondition)
                 .Ignore(e => e.YourBlobField)  // 排除 BLOB 字段
                 .ToList();

```

#### 简要描述原因

因为有些时候查询时不需要查询个别字段内容，而写要查询字段又比较费时间，所以是否增加一个
排除某些字段的条件，比如.Ignore(e=>e.bigfield) 这样就能在这次的select时，把bigfield字段排除在外
提升查询性能

**Comment by 2881099** [comment]
看这个 #528
