### ISSUE TITLE
DateOnly and TimeOnly Support Postgresql

### ISSUE THREAD

**Issue by FatTigerWang** [dotnetcore/FreeSql#1868]
#### Feature 特性

```c#
// c# code
```

#### 简要描述原因

```c#
目前看起来DateOnly和TimeOnly仅支持MSSQL Server, 希望能够增加对postgresql的支持, 或者有什么方法能够进行自定义的类型处理
```

#### 使用场景

```c#
// c# code
```

**Comment by FatTigerWang** [comment]
已经看到preview版本，非常感谢。

**Comment by FatTigerWang** [comment]
存储时没问题，但是查询时报异常：
ExpressionTree 转换类型错误，值(10:00:00)，类型(System.TimeSpan)，目标类型(System.TimeOnly)，Object must implement IConvertible.

**Comment by FatTigerWang** [comment]
用的是最新的preview版本3.5.100-preview20240815

**Comment by 2881099** [comment]
npgsql.dll 目前的版本改动较大，升级会造成 Could not load type 'Npgsql.TypeHandling.NpgsqlTypeHandlerFactory`1' from assembly 'Npgsql,

低版本，又报错：Can't write CLR type System.TimeOnly with handler type TimeHandler

**Comment by FatTigerWang** [comment]
现在问题还蛮严重的，因为貌似没有方法能够绕过，哪怕我用string去映射。除非更改数据库字段类型。

**Comment by 2881099** [comment]
他已经改变了传统ado.net使用习惯，进退两难

**Comment by 2881099** [comment]
v3.5.100-preview20240819 已解决该问题
