### ISSUE TITLE
[Table] 注解能不能增加 DbType 参数

### ISSUE THREAD

**Issue by xrjxs** [dotnetcore/FreeSql#1872]
因为Mysql表名大小写的问题，经常要用[Table]注解重命名表名，但又会影响到其他数据库比如 SqlServer，对迁移或者多数据库使用非常不方便。现在只能通过CodeFirst.ConfigEntity来重合名表名。[Table] 注解能不能增加 DbType 参数，使用如：[Table(Name = "user_profile", DbType = FreeSql.DataType.MySql)]

**Comment by 2881099** [comment]
UseConvertName 可以解决大小写，驼峰，下划线问题。

Aop.ConfigEntity 可以解决动态表名问题，在这里可以判断 sender 的类型，debugger 可以观察。

UseMappingPriority 可以调整 Attribute Aop 优先级。

**Comment by xrjxs** [comment]
感谢回复，之前研究了很多怎么解决这个问题，UseConvertName 也看过，但这个设置了好像也是全局的吧，设置了 UseConvertName 为下划线，然后 SqlServer 里也会变成下划线。目前就是用 ConfigEntity 来实现的，只是觉得非常的麻烦和不直观，还要切换到配置类里才能看到表名是什么。目前是这样：
// MySQL 设置
if (fsql.Ado.DataType == DataType.MySql)
{
    fsql.CodeFirst.ConfigEntity<UserProfile>(t => t.Name("user_profile"));

   // 这里是否可以使用 UseConvertName 来针对 MySql 动态设置表名规则而不影响其他数据库 ？
}

如上代码，UseConvertName 是否可以这样动态设置呢 ？

**Comment by 2881099** [comment]
FreeSqlBuilder 的时候就可以判断，进行 UseConvertName 设置。

每个 IFreeSql 有自己的 UseConvertName 设置，不会相互影响。

**Comment by xrjxs** [comment]
感谢，应该是 builder.UseNameConvert(NameConvertType.PascalCaseToUnderscoreWithLower); 当时怎么就没想到配置连接字符串时也是要指定数据库类型的 builder.UseConnectionString(DataType.MySql, connString); 既然要指定那就刚好一起配置了。

**Comment by xrjxs** [comment]
不好意思重开 issue 了，试了下 builder.UseNameConvert(NameConvertType.PascalCaseToUnderscoreWithLower);  然后程序整个崩溃了，发现 UseNameConvert 对表名，字段名都生效，比如 UserName 生成的 sql 也变成 user_name。但我只是需要表名为下划线，字段名仍然保持为 UserName。因为 MySql 的表名是不能命名为 UserProfile 的，会统一变成 userprofile 表名，所以需要下划线，但字段名是可以保持 UserName 大小写的。

还有什么解决办法吗，这么看来要想不用 Aop.ConfigEntity，最好的解决办法就是 [Table] 注解能不能增加 DbType 参数 ？

**Comment by 2881099** [comment]
可以看下 FreeSqlBuilder.cs 源代码，其实 UseNameConvert 也是用的 Aop.ConfigEntity，这块源代码比较简单，可以看看。

**Comment by luoyunchong** [comment]
https://freesql.net/guide/fluent-api.html
用这个解决

**Comment by 2881099** [comment]
也可以看这个，https://freesql.net/guide/fluent-api.html

**Comment by xrjxs** [comment]
谢谢，翻了一下源代码，抄了过来，最终用 Aop.ConfigEntity 完美解决，代码如下，放在 builder.Build(); 后面就可以

```
var fsql = builder.Build();
// MySql 仅表名转换为小写下划线，如需要表名和字段名都转换，可直接用 builder.UseNameConvert(NameConvertType.PascalCaseToUnderscoreWithLower); 
if (fsql.Ado.DataType == DataType.MySql)
{
    string PascalCaseToUnderScore(string str) => string.IsNullOrWhiteSpace(str) ? str : string.Concat(str.Select((x, i) => i > 0 && char.IsUpper(x) ? "_" + x.ToString() : x.ToString()));
    fsql.Aop.ConfigEntity += (_, e) => { if (string.IsNullOrWhiteSpace(e.ModifyResult.AsTable)) e.ModifyResult.Name = PascalCaseToUnderScore(e.ModifyResult.Name); };
}
```
