### ISSUE TITLE
达梦驱动升级更新到 DM.DmProvider

### ISSUE THREAD

**Issue by wwq3021** [dotnetcore/FreeSql#1873]
#### Feature 特性

[FreeSql.Provider.Dameng](https://github.com/dotnetcore/FreeSql/tree/master/Providers/FreeSql.Provider.Dameng) 

提供的达梦驱动版本比较旧了，有计划升级到 官方驱动nuget包  [DM.DmProvider](https://www.nuget.org/packages/DM.DmProvider)

 [DM.DmProvider](https://www.nuget.org/packages/DM.DmProvider)支持了空间字段类型，有计划升级支持么？

**Comment by 2881099** [comment]
写入时重写 SQL、读取时重写 SQL，例如 geography 类型的读写场景：

```cs
class Topic 
{
    [Column(DbType = "geography", 
        RewriteSql = "geography::STGeomFromText({0}, 4236)", 
        RereadSql = "{0}.STAsText()")]
    public string geo { get; set; }
}
//插入：INSERT INTO [ts_geocrud01]([id], [geo]) 
//VALUES(@id_0, geography::STGeomFromText(@geo_0, 4236))

//查询：SELECT TOP 1 a.[id], a.[geo].STAsText() 
//FROM [ts_geocrud01] a 
//WHERE (a.[id] = 'c7227d5e-0bcf-4b71-8f0f-d69a552fe84e')
```

lambda 表达式自定义函数解析：

https://freesql.net/guide/expression-function.html

**Comment by wwq3021** [comment]
谢谢  这个方案确实能解决 空间字段 读写操作 sql转换问题。

但是，[FreeSql.Provider.Dameng](https://github.com/dotnetcore/FreeSql/tree/master/Providers/FreeSql.Provider.Dameng) 底层DmProvider驱动不支持空间字段

我们也只能在封装一个  FreeSql.Provider.Dameng 源码之上封装一个[DM.DmProvider](https://www.nuget.org/packages/DM.DmProvider) 的类库来使用

**Comment by 2881099** [comment]
还是 DmProvider.dll吗，如果是可以在启动项目安装覆盖。

**Comment by 2881099** [comment]
也可以使用 FreeSql.Provider.Custom

使用 DataType.OdbcOracle，具体看 freesql.net 国产数据库文档说明。
