### ISSUE TITLE
FreeSql.Extensions.JsonMap 预览版where true 死循环

### ISSUE THREAD

**Issue by luoyunchong** [dotnetcore/FreeSql#1875]
https://github.com/dotnetcore/FreeSql/blame/8ab5372a09499885cc1774099f9e9bcb15d5b931/Extensions/FreeSql.Extensions.JsonMap/JsonMapCore.cs#L130

最新预览 版有一个死循环，where(true) 的情况 下使用 switch case ,如果case 条件 不满足，while永远无法结束

#### 安装的Nuget包
- FreeSql.Extensions.JsonMap [3.5.100-preview20240821](https://www.nuget.org/packages/FreeSql/3.5.100-preview20240821)

**Comment by 2881099** [comment]
好的，缺一个 defualt return
