### ISSUE TITLE
DynamicFilterInfo to where sql

### ISSUE THREAD

**Issue by mansai** [dotnetcore/FreeSql#1877]
_reportRepository.FreeSql.Ado.Query<dynamic>(sql)
后面不支持WhereDynamicFilter，
查询条件已经从前端传入，如何把前端传的DynamicFilterInfo直接转换为对应的sql条件，这样方便动态拼接sql
例如：
{
    "Logic": "And",
    "Filters":
    [
        {
            "Field": "id",
            "Operator": "Equals",
            "Value": 1
        },
        {
            "Field": "id",
            "Operator": "Equals",
            "Value": 2
        }
    ]
}
转换后的结果为：WHERE id = 1 AND id = 2   或者不带WHERE的条件  id = 1 AND id = 2

**Comment by 2881099** [comment]
这个依赖实体类型

**Comment by mansai** [comment]
我自己实现一个
` public class QueryHelper
 {

     public static (string, Dictionary<string, object>, string) GenerateWhereString(DynamicFilterInfo filterInfo)
     {
         string order = "Id desc";
         var lstValues = new Dictionary<string, object>();
         int index = 0;
         var whereClause = GenerateWhereClause(filterInfo, ref index);

         filterInfo.Travel((filterInfo) => lstValues.Add(lstValues.Count.ToString(), GetValue(filterInfo)));
         return (whereClause, lstValues, order);
     }
     public static string GenerateOrder(QueryCondition queryCondition)
     {
         string order = "Id desc";
         if (queryCondition.sort.Count > 0)
         {
             order = string.Empty;
             foreach (var item in queryCondition.sort)
             {
                 order += $"{item.field} {item.order},";
             }
             order = order.Trim(',');
         }
         return order;
     }
     static bool isArray =false;
     static DateTime[] dates;
     static bool isDate1 = false;
     protected static string GenerateWhereClause(DynamicFilterInfo filterInfo, ref int index)
     {
         var lstConditions = new List<string>();

         if (filterInfo.Value!=null && filterInfo.Value.ToString().Trim()!=string.Empty)
         {
             if (filterInfo.Value.GetType() == typeof(JArray))
             {
                 isArray=true;
                 dates = Newtonsoft.Json.JsonConvert.DeserializeObject<DateTime[]>(filterInfo.Value.ToString());
                 isDate1=true;
                 lstConditions.Add(ConvertToCondition(filterInfo, index++));
             }
             isArray = false;
             lstConditions.Add(ConvertToCondition(filterInfo, index++));            
         }
         if (filterInfo.Filters != null && filterInfo.Filters.Count > 0)
         {
             foreach (var subGroup in filterInfo.Filters)
             {
                 if (subGroup.Value != null && subGroup.Value.ToString().Trim() != string.Empty)
                 {
                     lstConditions.Add(GenerateWhereClause(subGroup, ref index));
                 }
             }
         }

         return $"({lstConditions.JoinAsString(filterInfo.Logic.ToString().ToLower() == "and" ? " and " : " or ")})";
     }

     protected static string ConvertToCondition(DynamicFilterInfo condition, int index)
     {
         string left = GetLeft(condition, index);
         string right = GetRight(condition, index);
         switch (condition.Operator.ToString().ToLower())
         {
             case "equals":
             case "equal":
             case "eq":
             case "=":
             case "==":
                 return $"{left} = {right}";
             case "<>":
             case "!=":
             case "notequal":
                 return $"{left} <> {right}";
             case "greater":
             case "greaterthan":
             case ">":
                 return $"{left} > {right}";
             case "greaterorequal":
             case "greaterthanorequal":
             case ">=":
                 return $"{left} >= {right}";
             case "less":
             case "lessthan":
             case "<":
                 return $"{left} < {right}";
             case "lessorequal":
             case "lessthanorequal":
             case "<=":
                 return $"{left} <= {right}";
             case "startwith":
                 return $"{left} like {right}";
             case "notstartwith":
                 return $"{left} not like {right}";
             case "endwith":
                 return $"{left} like {right}";
             case "notendwith":
                 return $"{left} not like {right}";
             case "contain":
             case "contains":
             case "like":
                 return $"{left} like {right}";
             case "notcontains":
                 return $"{left} not like {right}";
             case "range":
                 return $"{left} in({right})";
             case "daterange":
                 if (isArray)
                 {
                     return $"{left} >={right}";
                 }
                 else
                 {
                     return $"{left} <={right}";
                 }
             case "in":
             case "any":
                 return $"{left} in({right})";
             case "notany":
             case "notcontain":
                 return $"{left} not in({right})";
             default:
                 throw new InvalidOperationException($"Unknown dynamic query operator: {condition.Operator}");
         }
     }
     protected static object GetValue(DynamicFilterInfo condition)
     {

         switch (condition.Operator.ToString().ToLower())
         {

             case "startwith":
             case "notstartwith":
                 return $"{condition.Value}%";
             case "endwith":
             case "notendwith":
                 return $"%{condition.Value}";
             case "contain":
             case "contains":
             case "like":              
             case "notcontains":
                 return $"%{condition.Value}%";
             case "daterange":
                 if (isDate1)
                 {
                     isDate1 = false;
                     return dates[0];
                 }
                 else
                 {
                     return dates[1];
                 }
             default:
                 return condition.Value;
         }
     }
     protected static string GetLeft(DynamicFilterInfo condition, int index)
     {
         return condition.Field;
     }

     protected static string GetRight(DynamicFilterInfo condition, int index)
     {
         return $"@{index}";
     }

 }
 public static class FilterExtensions
 {
     public static void Travel(this DynamicFilterInfo dynamicFilterInfo, Action<DynamicFilterInfo> conditionAction)
     {
         if (dynamicFilterInfo.Value != null && dynamicFilterInfo.Value.ToString().Trim()!=string.Empty)
         {
             if (dynamicFilterInfo.Value.GetType() == typeof(JArray))
             {
                 conditionAction(dynamicFilterInfo);
             }
             conditionAction(dynamicFilterInfo);
         }
         if (dynamicFilterInfo.Filters != null && dynamicFilterInfo.Filters.Count > 0)
         {
             foreach (var subGroup in dynamicFilterInfo.Filters)
             {
                 Travel(subGroup, conditionAction);
             }
         }
     }
     public static string JoinAsString<T>(this IEnumerable<T> source, string separator)
     {
         return string.Join(separator, source);
     }
 }`

调用示例
` var (predicate, args, order) = QueryHelper.GenerateWhereString(search.FilterInfo);
var sql = "select * from table";//你的sql
if (args.Count > 0)
{
    if (sql.IndexOf("where", StringComparison.OrdinalIgnoreCase) > 0)
    {
        sql = sql + predicate;
    }
    else
    {
        sql = $"{sql} where {predicate}";
    }
 DbParameter[] cmdParms = _reportRepository.FreeSql.Ado.GetDbParamtersByObject(args);
var cmdType = System.Data.CommandType.Text;
var dynamics = _reportRepository.FreeSql.Ado.Query<dynamic>(cmdType, sql, cmdParms);
}
`

**Comment by mansai** [comment]
上面的代码格式有点乱，附图
![image](https://github.com/user-attachments/assets/921ae456-6ca5-4e7e-8a2e-a9b2b5243621)
