### ISSUE TITLE
使用codefirst时序列化json或jsonb数据类型报错

### ISSUE THREAD

**Issue by feijie999** [dotnetcore/FreeSql#19]
使用postgresql+ef配置数据映射关系，使用FreeSql的映射扩展时，对于json类型的数据映射出错。debug代码如下：
![image](https://user-images.githubusercontent.com/23080599/54528759-d3ef5b80-49b8-11e9-8138-1f4e784dffba.png)

**Comment by feijie999** [comment]
> Npgsql.PostgresException (0x80004005): 42804: 字段 "SchemeContextJson" 不能自动转换成类型 json
   at FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(ObjectPool`1 pool, DbCommand cmd, Exception e, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbTransaction transaction, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(CommandType cmdType, String cmdText, DbParameter[] cmdParms)

对json列的插入好像也有问题。我实体对象定义的json列为字符串类型

**Comment by 2881099** [comment]
这个要要定义成JToken，我做了判断。

**Comment by feijie999** [comment]
JToken 类型无法兼容ef core支持的对象，能否根据关系映射中配置的ColumnType来判断是否为json对象，这样兼容性会更好一些

**Comment by feijie999** [comment]
如果定义为JToken或JObject对象那么，mysql和sqlserver都将无法使用

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/blob/master/FreeSql.Tests/PostgreSQL/PostgreSQLCodeFirstTest.cs

这是pg有所有类型的插入测试，包括数组，json，hstore，gis

json兼容问题我记下了

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/blob/master/FreeSql.Tests/PostgreSQL/PostgreSQLCodeFirstTest.cs

这是pg有所有类型的插入测试，包括数组，json，hstore，gis

定义成JToken可以使用Contains查询，string就不行了

json兼容问题我记下了

**Comment by 2881099** [comment]
高级特性比较难兼容多数据库，除了基础类型。

**Comment by feijie999** [comment]
嗯确实。可否弄一个类似与这样的静态方法来转换string为JToken，这样就可以使用JToken的表达式了
![image](https://user-images.githubusercontent.com/23080599/54530093-c63bd500-49bc-11e9-8285-d6a3be4a86d2.png)

**Comment by feijie999** [comment]
嗯。那现在就是定义为string类型的实体，通过实体映射为json或jsonb后无法插入到postgresql里面的问题了。
