### ISSUE TITLE
查询使用dynamic接收 只能用字典获取吗？

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#190]
因为dynamic依赖microsoft.csharp，并且还依赖了很多其他dll，发布后的dll数据太多不友好，另外还容易发生dll版本冲突问题。因为不是所有人都需要dynamic，所以目前改成了Dictionary返回，Dictionary和dynamic转换很方便，大约需要2行代码，可以百度查查相关资料。

**Comment by a6336747** [comment]
大佬你好.
我看了一下fsql.Ado.Query<dynamic> 可以返回dictionary的结构.
ISelect有类似的方法吗.
fsql.Select<表名>.ToList<dynamic>().好像并不能这么用.
ISelect提供的ToDictionary的重载方法也并不能达到Ado的那种纯dictionary效果.
我想把现在的项目ORM整体换成FreeSql,但原项目大量使用了操作dictionary集合的方法,导致迁移遇到了困难

**Comment by 2881099** [comment]
请给出一些示例

ISelect.ToDictionary() 功能不强大，可以在 ISelect.ToList() 之后再使用 linq 内存操作。

**Comment by a6336747** [comment]
项目有些地方查询结果返回的是dictionary集,可以很方便在不新建dto的情况下对每个单独对象扩展新字段.
虽然说这些问题只要不嫌麻烦,都可以新建实体类就可以解决...但这样会多太多的dto文件.

**Comment by 2881099** [comment]
感觉你是问题是：如果当 List\<T> 转换成 List\<Dictionary\<string, object>>

**Comment by a6336747** [comment]
对，但事实上，这么做会报出 Dictionary`2 没有一个属性名相同的 映射异常，而且我也没找到相关能实现的方法

**Comment by 2881099** [comment]
简单的话循环反射一下就行啊

很多工具类可以转

**Comment by 2881099** [comment]
https://blog.csdn.net/anonymous_qsh/article/details/78596695 很多代码

**Comment by a6336747** [comment]
感谢回答，目前我就是这么做的，但多了一到处理感觉怪别扭的，而且数据量大了后，性能上也会出现瓶颈，所以就想问问有没有直接一步到位的哈

**Comment by 2881099** [comment]
可以给 ISelect\<T> 实现扩展方法 ToDictlist()

数据多可以用 ToChunk 加载

性能问题还好，就是多了一次复制

**Comment by a6336747** [comment]
`internal List<TReturn> ToListMrPrivate<TReturn>(string sql, ReadAnonymousTypeAfInfo af, ReadAnonymousTypeOtherInfo[] otherData)
        {
            var type = typeof(TReturn);

            var dbParms = _params.ToArray();

            if (type==typeof(object))
            {
                var ret1 = new List<TReturn>();
                if (string.IsNullOrEmpty(sql)) return ret1;
                var type1 = typeof(TReturn);
                string flag = null;
                int[] indexes = null;


                var tb = _commonUtils.GetTableByEntity(type);
                var props = tb?.Properties ?? type.GetPropertiesDictIgnoreCase();
                _orm.Ado.ExecuteReader(_connection, _transaction, dr =>
                {
                    if (indexes == null)
                    {
                        var sbflag = new StringBuilder().Append("adoQuery");
                        var dic = new Dictionary<string, int>(StringComparer.CurrentCultureIgnoreCase);
                        for (var a = 0; a < dr.FieldCount; a++)
                        {
                            var name = dr.GetName(a);
                            if (dic.ContainsKey(name)) continue;
                            sbflag.Append(name).Append(":").Append(a).Append(",");
                            dic.Add(name, a);
                        }
                        indexes = props.Select(a => dic.TryGetValue(a.Key, out var tryint) ? tryint : -1).ToArray();
                        flag = sbflag.ToString();
                    }
                    ret1.Add((TReturn)Utils.ExecuteArrayRowReadClassOrTuple(flag, type1, indexes, dr, 0, _commonUtils).Value);
                }, CommandType.Text, sql, dbParms);
                return ret1;
            }

            var before = new Aop.CurdBeforeEventArgs(_tables[0].Table.Type, _tables[0].Table, Aop.CurdType.Select, sql, dbParms);
            _orm.Aop.CurdBeforeHandler?.Invoke(this, before);
            var ret = new List<TReturn>();
            Exception exception = null;
            try
            {
                _orm.Ado.ExecuteReader(_connection, _transaction, dr =>
                {
                    var index = -1;
                    ret.Add((TReturn)_commonExpression.ReadAnonymous(af.map, dr, ref index, false, null));
                    if (otherData != null)
                        foreach (var other in otherData)
                            other.retlist.Add(_commonExpression.ReadAnonymous(other.read, dr, ref index, false, null));
                }, CommandType.Text, sql, dbParms);
            }
            catch (Exception ex)
            {
                exception = ex;
                throw ex;
            }
            finally
            {
                var after = new Aop.CurdAfterEventArgs(before, exception, ret);
                _orm.Aop.CurdAfterHandler?.Invoke(this, after);
            }
            if (typeof(TReturn) == typeof(T1))
                foreach (var include in _includeToList) include?.Invoke(ret);
            _trackToList?.Invoke(ret);
            return ret;
        }`

现在就是抄了一份大大的fsql.Ado.Query<dynamic>(sql)实现
发现竟然可以直接用..
