### ISSUE TITLE
分表传入时间生成的sql与预期不符

### ISSUE THREAD

**Issue by AnyThing-Well** [dotnetcore/FreeSql#1901]
#### 问题描述及重现代码：
传入了分表传入时间后生成的sql与预期不符，预期sql：
    SELECT  * from (SELECT a.`OrderNo`, a.`Amount`, a.`PayAmount`, a.`PayTime`, a.`PayTradeNo`, a.`PayType`, a.`State`, a.`Type`, a.`VendId`, a.`Id` 
    FROM `Order` a 
    WHERE (a.`CreateTime` > '2023-07-08 00:00:00.000' AND a.`CreateTime` < '2023-07-22 00:00:00.000')) ftb ) a
相关代码
```c#
//设置Order分表第一个表的表名
fsql.CodeFirst.GetTableByEntity(typeof(OrderEntity)).AsTableImpl.SetTableName(0, "Order");
//没有传入时间时默认查Order表最近三个
fsql.CodeFirst.GetTableByEntity(typeof(OrderEntity)).AsTableImpl.SetDefaultAllTables(value => value.Take(3).ToArray());

[Table(Name = "Order_{yyyyMM}", AsTable = "createtime=2024-7-1(3 month)")]
[Index("{tablename}_idx_01", "OrderNo")]
[Index("{tablename}_idx_01", "OrganizeId")]
[Index("{tablename}_idx_01", "CreateTime")]
public class OrderEntity : TenantBaseEntity<long>
{
//....
}
var startDate = model.StartDate.AddDays(-3);
var endDate=model.EndDate.AddDays(1);
var order = _freeSql.Select<OrderEntity>()
    .Where(o => o.CreateTime > startDate && o.CreateTime < endDate)
    .WithTempQuery(o => new
    {
        o.OrderNo,
        o.Amount,
        o.PayAmount,
        o.PayTime,
        o.PayTradeNo,
        o.PayType,
        o.State,
        o.Type,
        o.VendId,
        o.Id
    });
```
#### 生成的sql
SELECT * 
FROM ( 
    SELECT  * from (SELECT a.`OrderNo`, a.`Amount`, a.`PayAmount`, a.`PayTime`, a.`PayTradeNo`, a.`PayType`, a.`State`, a.`Type`, a.`VendId`, a.`Id` 
    FROM `Order_202410` a 
    WHERE (a.`CreateTime` > '2023-07-08 00:00:00.000' AND a.`CreateTime` < '2023-07-22 00:00:00.000')) ftb
 
    UNION ALL
 
    SELECT  * from (SELECT a.`OrderNo`, a.`Amount`, a.`PayAmount`, a.`PayTime`, a.`PayTradeNo`, a.`PayType`, a.`State`, a.`Type`, a.`VendId`, a.`Id` 
    FROM `Order` a 
    WHERE (a.`CreateTime` > '2023-07-08 00:00:00.000' AND a.`CreateTime` < '2023-07-22 00:00:00.000')) ftb ) a

#### 数据库版本
mysql5.7

#### 安装的Nuget包
Freesql 3.2.833
FreeSql.Provider.MySql 3.2.833

#### .net framework/. net core？ 及具体版本
. net core6

**Comment by AnyThing-Well** [comment]
通过修改表的特性实现了[Table(Name = "as_table_log_{yyyyMM}", AsTable = "createtime=2022-7-1(24,3 month)")]实现了预期的sql，如果有更好的方式请告诉我，感谢

**Comment by AnyThing-Well** [comment]
通过这样设置实现了[Table(Name = "as_table_log_{yyyyMM}", AsTable = "createtime=2022-7-1(24,3 month)")]

**Comment by 2881099** [comment]
嗯，步长不一样
