### ISSUE TITLE
参数化查询没数据

### ISSUE THREAD

**Issue by wdqzdd** [dotnetcore/FreeSql#1905]
参数化查询，查不到数据

![image](https://github.com/user-attachments/assets/6918ff91-e803-4dd0-8b90-8d16fba41b57)

![image](https://github.com/user-attachments/assets/8ddfee66-9833-4702-9e5b-02522b857173)

#### 数据库版本
mysql5.6

#### 安装的Nuget包
![image](https://github.com/user-attachments/assets/f757a760-8467-45d8-a643-7a15fbe6bee4)

#### .net framework/. net core？ 及具体版本
.net core 6

**Comment by luoyunchong** [comment]
https://freesql.net/guide/ado.html#%E5%8F%82%E6%95%B0%E5%8C%96
