### ISSUE TITLE
桌面客户端连接数据库失败。

### ISSUE THREAD

**Issue by zflq2002** [dotnetcore/FreeSql#1911]
报错信息：Microsoft.Data.SqlClient.SqlException (0x80131904): 登录失败。该登录名来自不受信任的域，不能与集成身份验证一起使用。

数据库接字符串：Data Source=*;User ID=sa;Password=123;Initial Catalog=DDB;Encrypt=True;TrustServerCertificate=True;Integrated Security=false;
在相同环境下，用其它ORM 测试连接正常不报错。
#### 数据库版本
SQL Server 2019 

#### 安装的Nuget包
FreeSql.All 3.2.833

#### .net framework/. net core？ 及具体版本
. net core 8

**Comment by 2881099** [comment]
new SqlConnection("Data Source=*;User ID=sa;Password=123;Initial Catalog=DDB;Encrypt=True;TrustServerCertificate=True;Integrated Security=false;").Open()

测试这个通过，FreeSql 就没问题。
