### ISSUE TITLE
VS2010下FreeSql无法兼容.net4. framework !!!

### ISSUE THREAD

**Issue by sukai-cheng** [dotnetcore/FreeSql#1914]
**数据库版本**: oracle 11g
**NetFramework版本**: .NET Framework 4 Client Profile
**FreeSql版本**: 3.2.833
**Nuget报错**: FreeSql.Provider.Oracle
**截图如下:** 
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/58c76519-3d2f-49f6-8625-2f9e460c1058">

**Comment by 2881099** [comment]
建议用空项目添加引用测试

**Comment by 2881099** [comment]
http://freesql.net/guide/freesql-provider-oracle.html  三种访问方式，.net4.0 支持的。

**Comment by sukai-cheng** [comment]
vs2010, 你确定可以? 
![image](https://github.com/user-attachments/assets/12f81f7f-9be8-4801-883c-2e29a8f4ed66)

**Comment by sukai-cheng** [comment]
![bug](https://github.com/user-attachments/assets/40f74284-0807-4fa6-ade8-3bbdad63d711)

**Comment by 2881099** [comment]
vs2010只是开发工具，我当然试过.net4.0，vs2019以上的版本。

我这里没有低版本VS。

**Comment by 2881099** [comment]
下载nuget包，手工引用dll？

**Comment by sukai-cheng** [comment]
麻烦提供可以使用的dll ?

**Comment by sukai-cheng** [comment]
你连接的是oracle?

**Comment by sukai-cheng** [comment]
Oracle.ManagedDataAccess 23.6.0不兼容.NetFrameWork.Version=4.0

**Comment by 2881099** [comment]
![image](https://github.com/user-attachments/assets/6071a5f2-7033-4e4b-915f-a1d808bf49d1)

**Comment by 2881099** [comment]
![image](https://github.com/user-attachments/assets/a09df7c9-06fc-45f9-9fb4-f525eb9a0117)

**Comment by 2881099** [comment]
我本来不想回复你的，上来就各种质疑。

我不欠你的！

**Comment by sukai-cheng** [comment]
麻烦你用**vs2010**试, 否则请关闭你的评论, 谢谢!

**Comment by j4587698** [comment]
你的问题是vs2010已经不支持新版的nuget包了，你需要升级vs或者自己去Nuget上下载对应的dll，而不是在这里跟作者叫。人家兼容的是.net 4，又不是vs2010，不支持vs2010算什么BUG？

**Comment by izanhzh** [comment]
![ZOE{ ET%G83VI4Z}V7HNXKQ](https://github.com/user-attachments/assets/e8507f1a-9c58-4dc7-9b33-b486f6f4a11c)
![Y06N4LVB(8MH}M%WAPHQ)IS](https://github.com/user-attachments/assets/c636d6c7-df9b-4cd0-90f5-dd2aa9d25130)

**Comment by luoyunchong** [comment]
![image](https://github.com/user-attachments/assets/539db5bc-58b7-4864-8995-c1de8f25e95d)

**Comment by luoyunchong** [comment]
https://www.nuget.org/packages/FreeSql.Provider.Oracle/3.2.833
