### ISSUE TITLE
希望GBase支持GbsConnection方式 当前只能使用ODBC方式

### ISSUE THREAD

**Issue by zxr6367587** [dotnetcore/FreeSql#1918]
希望添加GbsConnection这种方式去链接数据库

[GeneralData.EntityFrameworkCore.GBase.DataProvider.zip](https://github.com/user-attachments/files/17676663/GeneralData.EntityFrameworkCore.GBase.DataProvider.zip)

**Comment by 2881099** [comment]
这个驱动我知道，早期用他们提供的 ef 驱动，其实底层也是依赖的 odbc。

你试试换一台电脑写项目测试一下。
