### ISSUE TITLE
gbase8s回写主键问题

### ISSUE THREAD

**Issue by zxr6367587** [dotnetcore/FreeSql#1919]
#### 问题描述及重现代码：

使用gbase8时不会回写主键，使用ExecuteIdentity能返回ID

![image](https://github.com/user-attachments/assets/d8997b18-8337-4ad4-ac1e-54d5a90f56fa)

![image](https://github.com/user-attachments/assets/6f4bd07e-82b4-4d21-b7ad-7373175eef39)

```c#

var fsql = new FreeSql.FreeSqlBuilder()
    .UseConnectionFactory(DataType.Custom, () => new GbsConnection("xxxxxxxxxxxx "))
    .UseMonitorCommand(cmd => Trace.WriteLine($"Sql：{cmd.CommandText}"))
    .UseQuoteSqlName(false)
    .Build();
 fsql.SetCustomAdapter(new GBSAdapter());
 fsql.SetDbProviderFactory(GbsFactory.Instance);

GBSAdapter
public override string InsertAfterGetIdentitySql => "select dbinfo('bigserial')   from dual";
// c# code
```

#### 数据库版本
gbase8s

#### 安装的Nuget包
3.2.833

#### .net framework/. net core？ 及具体版本
.net 5

**Comment by zxr6367587** [comment]
/// <summary>
     /// 主键
     /// </summary>
     [Column(IsPrimary = true, IsIdentity = true)]
     public long ID { get; set; }

**Comment by zxr6367587** [comment]
使用DataType.GBase类型的时候 会执行SELECT dbinfo('serial8') FROM dual 但是我们建库的时候使用的是bigserial 是否能使用datatype去动态修改查询语句

**Comment by zxr6367587** [comment]
获取主键可以改为
` SELECT
    DECODE(
        dbinfo('serial8'),
        0,
        DECODE(
            dbinfo('bigserial'),
            0,
            dbinfo('sqlca.sqlerrd1'),
            dbinfo('bigserial')
        ),
        dbinfo('serial8')
    )
FROM
    dual;`

**Comment by 2881099** [comment]
protected override long RawExecuteIdentity()

可以看 FreeSql.Provider.GBase 项目这个实现。

MapType = typeof(long) 也许可以帮到你

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/blob/ce4a77f45b8cd30e62b4e6af159a9c26aee17807/Providers/FreeSql.Provider.GBase/Curd/GBaseInsert.cs#L40
