### ISSUE TITLE
达梦8 支持codefirst吗？

### ISSUE THREAD

**Issue by jiahengaa** [dotnetcore/FreeSql#1924]
FreeSql, Version=3.2.833.0
freesql.provider.dameng, Version=3.2.833

达梦8 支持codefirst吗？切换到达梦后，使用 fsql.CodeFirst.SyncStructure 会报错
![image](https://github.com/user-attachments/assets/f73eaccf-599e-4f95-8b6c-652cb4600591)

**Comment by 2881099** [comment]
检查一下是不是有同名属性

**Comment by jiahengaa** [comment]
> 检查一下是不是有同名属性

是不是跟dm的模式有关，我把表都迁移到 模式 dbo下了，应该把表放到默认模式SYSDBA下吗

**Comment by 2881099** [comment]
不支持模式，userid 就是模式，你观察一下 aop commandbefore

**Comment by jiahengaa** [comment]
> 不支持模式，userid 就是模式，你观察一下 aop commandbefore

已解决，就是模式不对导致的
