### ISSUE TITLE
AuditValue审计操作更新数据不完整

### ISSUE THREAD

**Issue by LambertW** [dotnetcore/FreeSql#1931]
#### 问题描述及重现代码：

AuditValue与Repository的AttachOnlyPrimary、await UpdateAsync(entity)共用使用，存在触发两次执行AuditValue事件，以及检测到的数据更新不完整。附一个可以执行的包，
[ConsoleApp1.zip](https://github.com/user-attachments/files/17891328/ConsoleApp1.zip)

#### 数据库版本
sqlite

#### 安装的Nuget包
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.2.833" />
    <PackageReference Include="FreeSql.Repository" Version="3.2.833" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

#### .net framework/. net core？ 及具体版本
dotnet --version
9.0.100

**Comment by 2881099** [comment]
#1746 和这个有关，我再优化一下。

**Comment by 2881099** [comment]
FreeSql v3.5.100-preview20241123
FreeSql.DbContext v3.5.100-preview20241124

```xml
    <PackageReference Include="FreeSql.DbContext" Version="3.5.100-preview20241124" />
    <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.5.100-preview20241123" />
```

解决这个问题

**Comment by LambertW** [comment]
试了没问题了哈。不过现在项目要多引用这个组件FreeSql.DbContext。
没其他问题了。

**Comment by 2881099** [comment]
移除 FreeSql.Repository，只引用 FreeSql.DbContext

FreeSql.Repository 这个包目前没有源代码，和 FreeSql.DbContext 是一样的。
