### ISSUE TITLE
gbase nvl判断时间语法错误 

### ISSUE THREAD

**Issue by zxr6367587** [dotnetcore/FreeSql#1953]
#### 问题描述及重现代码：

UPDATE table SET startday = '2024-12-20 16:57:10.908', endday = (nvl(endday, '1970-01-01 00:00:00') + (days) units day) 
WHERE id = 1

```c#
// c# code
fsql.Update<Model>()
                .Set(p => p.StartDay, DateTime.Now)
                .Set(p => p.EndDay.AddDays(p.Days))
                .Where(p => p.Id== Id);

```

#### 数据库版本
gbase8s

#### 安装的Nuget包
3.5.101

**Comment by 2881099** [comment]
是什么问题，不生效，还是报错？

**Comment by zxr6367587** [comment]
报语法错误
![image](https://github.com/user-attachments/assets/399eb188-9e0e-480d-b01a-d8d7c8733084)

**Comment by 2881099** [comment]
正确的语法应该是什么

**Comment by 2881099** [comment]
用自定义表达式解析解决一下

**Comment by zxr6367587** [comment]
我也不知道 ，感觉是字符串没有正确的转为datetime ，用current当前时间是可以执行这个语句的，自定义表达式是在哪里配置？

**Comment by 2881099** [comment]
https://freesql.net/guide/expression-function.html

**Comment by zxr6367587** [comment]
可以改为 datetime(1970-01-01 00:00:00) year to second 替换 '1970-01-01 00:00:00'

**Comment by zxr6367587** [comment]
![image](https://github.com/user-attachments/assets/74d8ca58-d9c1-40f9-a66a-1c9e82b3c31e)

**Comment by 2881099** [comment]
为了最大兼容功能，被迫在 IsNull override 方法中使用正则表达式处理，请看代码：https://github.com/dotnetcore/FreeSql/commit/e7e169ae237bec91db955e24791af9c71b710ea6

**Comment by 2881099** [comment]
valueStr 一般是使用 GBaseAdo.cs 转化后的 SQLString，不会为 null
