### ISSUE TITLE
使用源码中的repository_01项目 未能自动创建数据库表

### ISSUE THREAD

**Issue by firelamb** [dotnetcore/FreeSql#205]
直接启动freesql源码中的repository_01项目 只生成了startup下的Sys1User和Sys1UserLogOn这两个表，但是源码中的song实体未生成。

**Comment by 2881099** [comment]
自动生成表，在使用的时候才会触发，如：

- fsql.Select\<Song>()
- fsql.Insert\<Song>()
- fsql.Update\<Song>()
- fsql.Delete\<Song>()

或者仓储的 crud 方法。
