### ISSUE TITLE
支持存储过程么

### ISSUE THREAD

**Issue by liyang-live** [dotnetcore/FreeSql#21]
支持存储过程么

**Comment by 2881099** [comment]
有提供 IAdo 接口实现执行SQL。

orm.Ado.方法

**Comment by 2881099** [comment]
文档：https://github.com/2881099/FreeSql/wiki/%E8%BF%94%E5%9B%9E%E6%9F%A5%E8%AF%A2%E7%9A%84%E6%95%B0%E6%8D%AE
