### ISSUE TITLE
ostgresql 唯一键 [[Index("uk_UserId", "UserId",IsUnique = true)]]无效

### ISSUE THREAD

**Issue by coreybrans** [dotnetcore/FreeSql#210]
在Postgresql12 上测试了下[[Index("uk_UserId", "UserId",IsUnique = true)]]，无论第三个参数是否为true结果都是建立索引而非唯一键

`[Index("UserInfo_uk_UserId",` "UserId",IsUnique = true)]
public class UserInfo : BaseEntity<UserInfo, int>
{
[MaxLength(30)]
public string UserId { get; set; }

    [MaxLength(50)]
    public string Name { get; set; }
}

**Comment by 2881099** [comment]
看代码是有区别对待

//创建表的索引
                foreach (var uk in tb.Indexes)
                {
                    sb.Append("CREATE ");
                    if (uk.IsUnique) sb.Append("UNIQUE ");
                    sb.Append("INDEX ").Append(_commonUtils.QuoteSqlName(uk.Name)).Append(" ON ").Append(tablename).Append("(");
                    foreach (var tbcol in uk.Columns)
                    {
                        sb.Append(_commonUtils.QuoteSqlName(tbcol.Column.Attribute.Name));
                        if (tbcol.IsDesc) sb.Append(" DESC");
                        sb.Append(", ");
                    }
                    sb.Remove(sb.Length - 2, 2).Append(");\r\n");
                }

**Comment by coreybrans** [comment]
> 看代码是有区别对待
> 
> //创建表的索引
> foreach (var uk in tb.Indexes)
> {
> sb.Append("CREATE ");
> if (uk.IsUnique) sb.Append("UNIQUE ");
> sb.Append("INDEX ").Append(_commonUtils.QuoteSqlName(uk.Name)).Append(" ON ").Append(tablename).Append("(");
> foreach (var tbcol in uk.Columns)
> {
> sb.Append(_commonUtils.QuoteSqlName(tbcol.Column.Attribute.Name));
> if (tbcol.IsDesc) sb.Append(" DESC");
> sb.Append(", ");
> }
> sb.Remove(sb.Length - 2, 2).Append(");\r\n");
> }

应该是生成的sql原因，手动创建没问题。
