### ISSUE TITLE
+更新dto方法

### ISSUE THREAD

**Issue by zhontai** [dotnetcore/FreeSql#218]
增加直接更新dto所有数据 + 实体审计数据的功能
为解决attach(entity) 会意外更新其它字段或者默认值无变化无法更新该字段的问题
entity = entityRep.getAsync(dto.id) 
_mapper.Map<entity>(dto)
entityRep.UpdateAsync(entity) 这里更新需要查询再更新有变化的字段
场景：
_entity仓储.updateDto(dto) => update entityTable set dto.所有字段 + 内部获取 new entity(){  }.更新审计字段

**Comment by 2881099** [comment]
根据 Dto 更新

```csharp
fsql.Update<T>()
  .SetDto(new { title = "xxx", clicks = 2 })
  .Where(a => a.Id == 1)
  .ExecuteAffrows();
//UPDATE `tb_topic` SET `Title` = ?p_0, `Clicks` = ?p_1 WHERE (Id = 1)

fsql.Update<T>()
  .SetDto(new Dictionary<string, object> { ["title"] = "xxx", ["clicks"] = 2 })
  .Where(a => a.Id == 1)
  .ExecuteAffrows();
```

**Comment by a6336747** [comment]
大佬,你好,Insert是否也能添加类似匿名,或者Dto方式的录入呢?
`fsql.Insert<Sys_LogDto>(log).AsTable(d => "Sys_Log").ExecuteAffrows();`
比如现在我要录入Dto数据只能通过这样的形式插入,感激不尽

**Comment by 2881099** [comment]
> 大佬,你好,Insert是否也能添加类似匿名,或者Dto方式的录入呢?
> `fsql.Insert<Sys_LogDto>(log).AsTable(d => "Sys_Log").ExecuteAffrows();`
> 比如现在我要录入Dto数据只能通过这样的形式插入,感激不尽

不一样，更新才需要指定字段。插入可以考虑把 Dto 对象映射成 Entity 在插入
