### ISSUE TITLE
关于 FreeSql.DbContext 的请教

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#22]
## DbContext
- 提供 SaveChanges 方法；
- 执行队列；

## DbSet
- 提供 Add、AddRange、Remove、RemoveRange、Update、UpdateRange 方法；
- 以及 Select 属性（连去原有的 FreeSql 查询对象）；
- 私有对象states，存储实体的副本哈希集合，key=实体的主键值，value=实体；

## Add/AddRange(entitys)
- 验证 entitys 主键值，是否存在于 states 中，存在时报错；
- 验证 entitys 主键中存在自增：
    * 若有，则立即开启 DbContext 事务，按数据库种类执行相应的方法，最终将返回的自增值，赋给entitys的属性；
    * 若无，并且 entitys 无主键值，则报错；
    * 否则，进入【打包执行队列】；
- 完成时更新 states；

## Remove/RemoveRange(entitys)
- 验证 entitys 主键值，若无则报错；
- 验证 states 中是否存在，若无则提醒应该先查询，再删除；
- 删除 states 对应的实体；
- 清除 entitys 内的自增属性值、Guid 类型的值，那这个 entitys 将变为可 Add 状态；
- 进入【打包执行队列】；

## Update/UpdateRange(entitys)
- 验证 entitys 主键值，若无则报错；
- 验证 states 中是否存在，若无则提醒应该先查询，再删除；
- 进入【打包执行队列】；

## Select
- 立即执行队列中的命令（打包方式），以免脏读到未提交的数据；
- 查询完成时，更新 states 的值；

## 更新数据规则
- 对比 states 中存在的历史快照值，返回即将修改的 fields；

# 演示

```csharp
using (var ctx = new SongContext()) {

    ctx.Songs.Select.Where(a => a.Id > 10).ToList();
    //查询结果，进入 states

    var song = new Song { };
    //可插入的 song

    ctx.Songs.Add(song);
    id = song.Id;
    //因有自增类型，立即开启事务执行SQL，返回自增值

    var adds = Enumerable.Range(0, 100)
        .Select(a => new Song { Create_time = DateTime.Now, Is_deleted = false, Title = "xxxx" + a, Url = "url222" })
        .ToList();
    //创建一堆无主键值

    ctx.Songs.AddRange(adds);
    //立即执行，将自增值赋给 adds 所有元素，因为有自增类型，如果其他类型，指定传入主键值，不会立即执行

    for (var a = 0; a < adds.Count; a++)
        adds[a].Title = "dkdkdkdk" + a;

    ctx.Songs.UpdateRange(adds);
    //批量修改，进入队列

    ctx.Songs.RemoveRange(adds.Skip(10).Take(20).ToList());
    //批量删除，进入队列，完成时 10-20 元素的主键值会被清除

    //ctx.Songs.Update(adds.First());

    adds.Last().Url = "skldfjlksdjglkjjcccc";
    ctx.Songs.Update(adds.Last());
    //单条修改 urls 的值，进入队列

    //throw new Exception("回滚");

    //ctx.Songs.Select.First();
    //这里做一个查询，会立即打包【执行队列】，避免没有提交的数据，影响查询结果

    ctx.SaveChanges();
    //打包【执行队列】，提交事务
}
```

**Comment by 2881099** [comment]
@LambertW @htrlq

**Comment by LambertW** [comment]
DbContext跟Repository项目，预期是如何整合的？
有没有一个整合的Sample看一下？

看上去很多功能重叠，Repository引用DbContext.Set<Entity>()？

**Comment by 2881099** [comment]
各自独立发展，两种使用方式。
功能重复的代码到时候抽取出来。

https://www.cnblogs.com/kellynic/p/10580936.html
这里是我昨天整理的dbcontext测试用例

**Comment by 2881099** [comment]
@LambertW

**Comment by LambertW** [comment]
看起来是大量参考了EF的操作习惯，那亮点就是不同数据库的操作一致性？
因为与EF相似程度较高，要做出优势比较难

**Comment by 2881099** [comment]
> 看起来是大量参考了EF的操作习惯，那亮点就是不同数据库的操作一致性？
> 因为与EF相似程度较高，要做出优势比较难

不喜欢比较，但是多说人总会拿去作比较，却不懂实践才出真知的理。
FreeSql 的理念是方便，EF不知道是什么理念，或许是纯商业制作。

我仍然希望探索出更加合理的 OO 模式。

EF不同版本对状态管理的规则不一样，切换数据库后差异也存在，虽然他们都是EF，但除了语法相似，不能算是一个库。

**Comment by LambertW** [comment]
相似程度较高的情况下，比较是大多数人的习惯吧..
如果不借鉴DbContext, 那可能你也出来的风格估计就是另外一回事了~

一般别人用EF，不用EF，也都是有所评估之后才会做出决定；例如不习惯code first，db first支持太弱，不习惯大量特性而丢失了性能，如果FreeSql的DbContext能针对相关的痛点进行解决，觉得应该会比较好推广~

**Comment by 2881099** [comment]
之前有人提过dbcontext需求，还pr了一个版本。

现在看来这块还是任重道远，毕竟是第三方，被认可的程度会比较低。

存在很多技术难题待突破，比如事务死锁。批量操作很容易发生。

**Comment by LambertW** [comment]
> 
> 
> 之前有人提过dbcontext需求，还pr了一个版本。
> 
> 现在看来这块还是任重道远，毕竟是第三方，被认可的程度会比较低。
> 
> 存在很多技术难题待突破，比如事务死锁。批量操作很容易发生。

知道问题在哪，就能考虑用测试案例去覆盖；就是工作量会挺大，我觉得可以考虑 先把`Repository`项目及测试项目再完善/整理一下；在快速开发这条道路上继续挖掘呀~
