### ISSUE TITLE
order和detail表，如何设置detail的联合主键和自动增长

### ISSUE THREAD

**Issue by zhusheping** [dotnetcore/FreeSql#23]
数据库为Sqlite
1、比如order有Id整形主键,detail表有OrderId 和 Id，如何设置OrderId + Id联合主键

2、实体对象如何定义才会生成表外键。按照导航属性设置后，fsql.CodeFirst.SyncStructure，数据库里面没有外键。

**Comment by 2881099** [comment]
[Column(IsPrimary = true]
public int Id { get; set; }

[Column(IsPrimary = true]
public int OrderID { get; set; }

这样应该可以，或者FluentApi方式配置，参考语法

fsql.CodeFirst
    .ConfigEntity<Detail>(a => {
        a.Property(b => b.Id).Name("Id22").IsIdentity(true);
        a.Property(b => b.name).DbType("varchar(100)").IsNullable(true);
    })
    .ConfigEntity<TestFluenttb2>(a => {
        a.Name("xxdkdkdk2").SelectFilter("a.Idx > 0");
        a.Property(b => b.Id).Name("Id22").IsIdentity(true);
        a.Property(b => b.name).DbType("varchar(100)").IsNullable(true);
    });

**Comment by zhusheping** [comment]
谢谢。不过好像不能联合主键自增。如果OrderID是新的，Id也从1开始。

**Comment by 2881099** [comment]
确实不可以

**Comment by zhusheping** [comment]
改用sqlserver，提示无法将多个 PRIMARY KEY 约束添加到表 'dbo.xxxx'。实体定义和数据库选择相关吗？sqlserver如何定义联合主键？

**Comment by 2881099** [comment]
不相关的，可能是数据存在有重复。

或者通过FreeSqlBuilder 创建的时候，.UseCommandMonitor，打印命令，看看执行的迁移语句，在这个贴发出来。

**Comment by zhusheping** [comment]
use [Test];
CREATE TABLE [dbo].[ConnModel] (
  [FlowId] INT NOT NULL primary key,
  [SourceId] INT NOT NULL primary key,
  [TargetId] INT NOT NULL primary key,
  [Instance] NVARCHAR(255),
  [File] NVARCHAR(255),
  [AllTheOther] BIT NOT NULL
);

**Comment by 2881099** [comment]
应该是个bug，修复好了通知你

**Comment by 2881099** [comment]
> use [Test];
> CREATE TABLE [dbo].[ConnModel] (
> [FlowId] INT NOT NULL primary key,
> [SourceId] INT NOT NULL primary key,
> [TargetId] INT NOT NULL primary key,
> [Instance] NVARCHAR(255),
> [File] NVARCHAR(255),
> [AllTheOther] BIT NOT NULL
> );

这条可以改正确了执行，再次迁移是，结构没变化不会重新创建

**Comment by 2881099** [comment]
@zhusheping 
前几天人在外地，sqlserver下这个bug已修复好。

同时增加了测试多组件迁移的单元测试：

![image](https://user-images.githubusercontent.com/16286519/55123533-f82c0480-513d-11e9-98de-026c0fad8bad.png)

**Comment by zhusheping** [comment]
联合主键可以了。
var curd1 = fsql.GetRepository<Song, int>(); 这种联合主键的写法如何写？
var curd1 = fsql.GetRepository<Song, int,int,string>();?

**Comment by 2881099** [comment]
谢谢反馈，目前是参考abp vnext的接口，它也没支持多主键的仓储。

多主键时候，用这个仓储会影响Find Get Delete TKey的方法，传入是实体的重载方法没影响。可以避开使用这几个方法。

我目前在整合DbContext，那里面会有与现在相同的仓储实现，并且包含了状态跟踪。目前基本完成开发，待测试完成可以考虑迁移过去使用。多主键的问题会在这里得以解决。

**Comment by 2881099** [comment]
状态跟踪，即Find实体后，设置指定的属性值，修改时只会更新变化的字段。

然后目前也实现了乐观锁，更新是比较放心的。

目前还在测试中……

**Comment by 2881099** [comment]
/// <summary>
	/// 返回默认仓库类
	/// </summary>
	/// <typeparam name="TEntity"></typeparam>
	/// <param name="that"></param>
	/// <param name="filter">数据过滤 + 验证</param>
	/// <returns></returns>
	public static BaseRepository<TEntity> GetRepository<TEntity>(this IFreeSql that, Expression<Func<TEntity, bool>> filter = null) where TEntity : class {
		return new DefaultRepository<TEntity, int>(that, filter);
	}

可以考虑在项目内实现这个扩展方法，支持联合主键的仓储类操作。

**Comment by zhusheping** [comment]
`            using (var uow = fsql.CreateUnitOfWork())
            {
                var flowRepos = uow.GetRepository<Flow>();               
                flowRepos.Insert(flow);
                //上面两个仓储，由同一UnitOfWork uow 创建
                //在此执行仓储操作
                //这里不受异步方法影响
                uow.Commit();
            }`
提示：
System.InvalidOperationException:“ExecuteNonQuery requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.”
stackoverflow:
`SqlTransaction sqlTrans = scon.BeginTransaction();`

**Comment by 2881099** [comment]
flow 的值，和实体发给我测试一下

**Comment by zhusheping** [comment]
public partial class FlowModel
    {
        public int UserId { get; set; }
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime LastModifyTime { get; set; }
        public string Desc { get; set; }
    }



            FlowModel flowModel = new FlowModel()
            {
                CreateTime = DateTime.Now,
                Name = "aaa",
                LastModifyTime = DateTime.Now,
                UserId = 1,    
            };





            fsql.CodeFirst.ConfigEntity<FlowModel>(f =>
            {
                f.Property(b => b.UserId).IsPrimary(true);
                f.Property(b => b.Id).IsPrimary(true);
                f.Property(b => b.Name).DbType("nvarchar(200)").IsNullable(false);
            }

------------------
Deep Mind Solutions. We Help .Solutions for Printing Industry 




Name：朱社平

Mob:  +8618993794536 
zhusp@deepmind.cn
Guangzhou, China


 

 




------------------ 原始邮件 ------------------
发件人: "2881099"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 中午11:34
收件人: "2881099/FreeSql"<FreeSql@noreply.github.com>;
抄送: "阿平"<790978@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [2881099/FreeSql] order和detail表，如何设置detail的联合主键和自动增长 (#23)




flow 的值，和实体发给我测试一下

**Comment by 2881099** [comment]
收到，我正在路上，大约30分钟后测试

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/56406055-18189900-62a2-11e9-9cb1-5d3e34b6e4cd.png)

老哥，用你给的代码没有发生错误

**Comment by 2881099** [comment]
我明白你的意思了，你是想id会联合主键下的自增是吧，谢谢反馈。正在支持，预计1小时后发布 nuget

**Comment by 2881099** [comment]
MySql.Data.MySqlClient.MySqlException:“Incorrect table definition; there can be only one auto column and it must be defined as a key”

这种联合主键，带自增在 mysql 下不被支持

**Comment by 2881099** [comment]
System.InvalidOperationException:“ExecuteScalar requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.”

试出你的错误了，sqlserver 下发生的，原因检查后再说明

**Comment by 2881099** [comment]
最新结果：pgsql/sqlite/pgsql 同样的操作没报错

**Comment by 2881099** [comment]
原因找到了，如果 SqlConnection 开启了事务，SqlCommand 要求同时设置 SqlConnection 和 SqlTransaction，才可以。

其他数据库的实现没有这个问题。。

**Comment by 2881099** [comment]
v0.5.2 nuget 包发布中，稍后再试。

**Comment by zhusheping** [comment]
ok测试数据存储进去了。
但是有个问题。
![image](https://user-images.githubusercontent.com/23443907/56410792-0e4a6200-62b1-11e9-81c5-365433bf83dc.png)
Id为0了，导致后面和它相关的id都是0了。

**Comment by 2881099** [comment]
Id = 0 的原因：
1、你没有给值，int 默认值被插入了进去；
2、你没有设置它为自增；

**Comment by 2881099** [comment]
这个贴楼层太高了，下次可以考虑开新贴，哈哈
