### ISSUE TITLE
关于 IFreeSql 注入，与 AspectCore 冲突的说明

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#233]
IFreeSql 作为 ORM 顶级对象，没有设置 NameSpace（命名空间），作者的用意是不想使用者在 .cs 文件顶部，多出一堆不必要的 using FreeSql.xxx。

最近有同学尝试用 AspectCore 翻车了。
![VY4PUS@({E}(}LQM(84TC 9](https://user-images.githubusercontent.com/16286519/76622575-b8d40f00-656c-11ea-84a5-bf61155c19f8.png)

经过定位以及源码调试发现，AspectCore 默认不支持 Ioc 容器内注入没有 NameSpace（命名空间）的类型。这个问题已经向作者反馈，但是作者并不想改，他的观点：没有 NameSpace（命名空间）是使用者的问题。

这种情况兼容一下其实只判断加个 if 判断即可。

好吧，绕道而行：

方法一：自己定义带 namespace 的类注入，包一层再注入使用。
```csharp
namespace xxx
{
   public class MyClass
   {
          public IFreeSql orm {get;set;}
   }
}
```

方法二：修改 AspectCore 源码

![IF_@XIF7N1O1}V0L~XM9(40](https://user-images.githubusercontent.com/16286519/76622813-3861de00-656d-11ea-8a82-3682220652a9.png)

**Comment by hajiuxbz** [comment]
一直搞不明白AspectCore的应用场景是什么 asp core默认的中间件和方法拦截不都可以实现它的功能吗 为什么还单独搞一套出来

**Comment by alexinea** [comment]
@hajiuxbz 因为 AspNetCore 中间件并不能包揽一切。

比当你需要属性输入的时候，AspNetCore 中间件就无能为力了。

而且，我们也有许多东西是不需要 AspNetCoe 参与的，这时候就没啥中间件不中间件了 ╮(￣▽￣")╭

**Comment by hajiuxbz** [comment]
@alexinea 谢谢,明白了，我局限在web开发了...
