### ISSUE TITLE
OneToMany 添加及查询问题

### ISSUE THREAD

**Issue by guliang21** [dotnetcore/FreeSql#245]
大神请教：
实体类如下：
```
public class EnergyType
{
    [Column(IsPrimary = true)]
    public int ID { get; set; }

    [Column(StringLength = 10, IsNullable = false)]
    public string Name { get; set; }
}

public class ProjectEnergyType
{
    [Column(IsPrimary = true, IsIdentity = true)]
    public int ID { get; set; }

    [Column(IsNullable = false)]
    public int PID { get; set; }

    [Column(IsNullable = false)]
    public int EnergyTypeID { get; set; }

    [Navigate(nameof(EnergyTypeID))]
    public EnergyType[] EnergyTypes { get; set; }
}
```
查询和插入我都没有试成功，插入我是这么写的
```
ProjectEnergyType pe = new ProjectEnergyType
{
    PID = 1,
    EnergyTypes = new EnergyType[]
    {
        new EnergyType{ ID = 1, Name = "电" },
        new EnergyType{ ID = 2, Name = "水" }
    }
};

var repo = db.GetRepository<ProjectEnergyType>();

repo.Insert(pe);
```
查询是不知道怎么写，会报错。

我对文档上的话没理解。
- 可约定，可不约定；
- 不约定的，需指定 Navigate 特性关联；
- 无关联的，查询时可以指明 On 条件，LeftJoin(a => a.Parent.Id == a.ParentId)；
- 已关联的，直接使用导航对象就行，On 条件会自动附上；

**Comment by 2881099** [comment]
你发的文档是导航属性的配置，目前看你的实体没问题，最好把 Array 数组换成 List\<T\>

级联保存分两种：

1、追加保存，即不处理已存在的数据

```csharp
var repo = fsql.GetRepository<ProjectEnergyType>();
repo.DbContextOptions.EnableAddOrUpdateNavigateList = true; //需要手工开启
repo.Insert(pe);
```

2、完整保存，会对比老数据计算出添加、修改、删除执行

```csharp
var repo = fsql.GetRepository<ProjectEnergyType>();
repo.Insert(pe);
repo.SaveMany(item, "EnergyTypes"); //在现有的数据上保存，内部会和现有数据进行对比，计算出应该插入、更新、删除的子记录
```

**Comment by guliang21** [comment]
我刚忘了开启联级保存了。

但是还有问题。

`EnergyType` 类的 `ID` 名称必须改为 `EnergyTypeID`。

改了之后执行是成功的，只是效果不是我想要的。

其实我只是想往 `ProjectEnergyType` 插两条数据。但我查看 SQL 语句，是往 `ProjectEnergyType` 插了一条数据，而且 `EnergyTypeID` 还是 0。

另外 Update 了 `EnergyType` 表，这其实是我不需要的。

**Comment by 2881099** [comment]
你上面的实体间关系是不是建错了，ProjectEnergyType 有多个 EnergyType，不应该在 EnergyType 下建 ProjectEnergyTypeId 属性来关联吗？

鉴于这块文档内容模糊，我更新了一下文档，看看现在是不是更容易看懂一些，看完给下建议，谢谢

https://github.com/2881099/FreeSql/wiki/%e8%81%94%e7%ba%a7%e4%bf%9d%e5%ad%98

**Comment by guliang21** [comment]
其实是我想错了。先说文档。

> 它还会遍历 Childs[0-..] 的集合属性保存，向下18层。

这意思就是遍历 `Childs` 属性，并递归吧？

> 计算出添加、修改、删除执行

略显拗口。“计算出应该执行添加、修改还是删除操作” 是不是好一点？

> 不向下遍历集合属性保存，只保存 Childs 属性

意思就是只遍历 `Childs` 不递归喽？

我会理解成方式一追加保存适用于 **父子结构**，可递归。方式二完全保存适用于 **非父子结构**，不递归。

咋感觉这个理解不对 [汗]

还说我的问题，我仔细理解了一下，其实应该属于多对多。一个项目可以有多个能源类型，一个能源类型可以属于多个项目。

但是我完全没有必要在能源类型下建立项目列表啊。因为我只会增删改某个项目下有什么能源类型，绝对不会有某个能源类型下有什么项目这种操作。所以我的实体关系才是这么建的。

然后，我就不知道怎么办了

**Comment by guliang21** [comment]
感谢大神周末还要为我答疑啊

**Comment by 2881099** [comment]
继续向下的意思，并不一定是父子关系。

比如类型表，下面有集合属性文章，文章下面有集合属性评论。

保存类型表对象的时候，他就会向下检索出集合属性文章，然后如果文章被保存的时候，再继续向下检索出集合属性评论。一起做 InsertOrUpdate 操作。

向下18层是这样的意思。

**Comment by 2881099** [comment]
完整保存的话，就不会继续向下检索，他只保存指定的那一个集合。

**Comment by 2881099** [comment]
多对多导航属性不是这样建的，你可以看一看，导航配置的那个文档。

**Comment by guliang21** [comment]
这样解释就明白了，文档中可以加入这个例子。相信大家一看就明白。

我试了多对多。但是怎么说呢，我这需求表面上是多对多，但实际应用中，还是一个项目可以包含多个能源类型，这属于一对多吧。

我上文中的例子，插入以后希望的表数据如下：

| ID | PID | EnergyType ID |
| -- | ---- | ---------------- |
| 1  |  1    |  1                     |
| 2  |  1    |  2                     |

而我现在尝试的写法，结果全都是 
| ID | PID | EnergyType ID |
| -- | ---- | ---------------- |
| 1  |  1    |  0                     |

**Comment by guliang21** [comment]
导航属性这里还是比较复杂的，文档中如果有实例的话会看的比较明白。代码 + 数据库数据 的形式。
