### ISSUE TITLE
能实现关联子查询吗？

### ISSUE THREAD

**Issue by wsj741** [dotnetcore/FreeSql#248]
比如实现以下SQL（查询所有书店，关统计每个店的书本数量）：
select a.*,b.COUNT from Shop a
Left Join (
select Shop_Id,COUNT(0) from ShopBook 
Group by Shop_Id
) AS b ON a.ShopId=b.Shop_Id
------------------
请示下，谢谢！

**Comment by 2881099** [comment]
看Leftjoin 重载方法注释

或者看 RawJoin 方法注释，需要安装最新的预览版

第一种
fsql.Select\<Shop>()
.LeftJoin(“(
select Shop_Id,COUNT(0) from ShopBook
Group by Shop_Id
) AS b ON a.ShopId=b.Shop_Id”)
.ToList(a => new { a, count = “b.COUNT” })

第二种
var leftjonSql = fsql.Selec\< ShopBook>()
.GroupBy(b=> b.Shop_Id)
.ToSql(b => new { b.Key, count = b.Count }, SelecrFieldAlias.AsProperty);

fsql.Select\<Shop>()
.LeftJoin($“({leftjonSql}) AS b ON a.ShopId=b.Shop_Id”)
.ToList(a => new { a, count = “b.COUNT” })

**Comment by 2881099** [comment]
fsql.Select<Shop>()
.ToList(a => new 
{
a, 
count =  fsql.Select< ShopBook>()
.Where(b=> b.Shop_Id == a.ShopId).Count()
})
