### ISSUE TITLE
guid 主键自动生成重复

### ISSUE THREAD

**Issue by fenfei100** [dotnetcore/FreeSql#250]
刚发现不是 guid 字段，是 long 字段。多线程添加数据的时候提示重复异常，估计是使用仓库没有线程安全引起的。

另外关于 guid 字段还是建议针对 sqlserver 下做个优化，因为 sqlserver guid字段排序的是 guid的最后几个字节。

参考：https://www.cnblogs.com/CameronWu/p/guids-as-fast-primary-keys-under-multiple-database.html

**Comment by 2881099** [comment]
这个问题知道，不好解决。

可以用其他办法解决 sql 这个问题， Aop.AuditValue 事件 或者 在实体类上给初始值

```csharp
    class BaseEntity<T, TKey>
    {
        protected BaseEntity()
        {
            if (typeof(TKey) == typeof(Guid))
                this.Id = (TKey)Convert.ChangeType(Guid.NewGuid(), typeof(TKey));
        }

        public TKey Id { get; set; }
    }

    class Topic : BaseEntity<Topic, int>
    {

    }
```

**Comment by 2881099** [comment]
Aop.AuditValue 可以对 Guid 设置值了
