### ISSUE TITLE
Xamarin.Forms WPF在Page.SizeChanged事件初始化IFreeSql会卡死

### ISSUE THREAD

**Issue by pardont** [dotnetcore/FreeSql#251]
Xamarin.Forms WPF在Page.SizeChanged事件初始化IFreeSql会卡死，不知道是什么原因。
附件是测试用的解决方案代码：
[TestFreeSqlXamarinForms.zip](https://github.com/2881099/FreeSql/files/4373970/TestFreeSqlXamarinForms.zip)

>    
        public MainPage()
        {
            InitializeComponent();

            this.SizeChanged += MainPage_SizeChanged;
        }

        bool isInited = false;
        private void MainPage_SizeChanged(object sender, EventArgs e)
        {
            Console.WriteLine("SizeChanged");
            if (isInited)
                return;

            isInited = true;

            //WPF上会一直卡住, 其他的平台都不会，很奇怪
            Init();

        }

        private void Init()
        {
            var fsql = new FreeSql.FreeSqlBuilder()
                        .UseAutoSyncStructure(true)
                        .UseNoneCommandParameter(true)
                        .UseConnectionString(FreeSql.DataType.Sqlite, "data source=test.db;max pool size=5")
                        .Build();
        }

**Comment by NovaNick** [comment]
SizeChanged会多次触发不符合单例，教程里不是让使用单例吗？

**Comment by 2881099** [comment]
这不是单例，其他 .cs 访问怎么办，不能每个 .cs 都定义一个 Init 方法

```csharp
class GlobalData
{
    static Lazy<IFreeSql> sqliteLazy = new Lazy<IFreeSql>(() => new FreeSql.FreeSqlBuilder()
        .UseConnectionString(FreeSql.DataType.Sqlite, @"Data Source=|DataDirectory|\document.db;Attachs=xxxtb.db;")
        //.UseConnectionFactory(FreeSql.DataType.Sqlite, () =>
        //{
        //    var conn = new System.Data.SQLite.SQLiteConnection(@"Data Source=|DataDirectory|\document.db;Pooling=true;");
        //    //conn.Open();
        //    //var cmd = conn.CreateCommand();
        //    //cmd.CommandText = $"attach database [xxxtb.db] as [xxxtb];\r\n";
        //    //cmd.ExecuteNonQuery();
        //    //cmd.Dispose();
        //    return conn;
        //})
        .UseAutoSyncStructure(true)
        //.UseGenerateCommandParameterWithLambda(true)
        .UseLazyLoading(true)
        .UseMonitorCommand(
            cmd => Trace.WriteLine("\r\n线程" + Thread.CurrentThread.ManagedThreadId + ": " + cmd.CommandText) //监听SQL命令对象，在执行前
            //, (cmd, traceLog) => Console.WriteLine(traceLog)
            )
        .Build());
    public static IFreeSql sqlite => sqliteLazy.Value;
}

**Comment by pardont** [comment]
@NovaNick 不是的，第一次就执行不过，你看我的代码里还加了判断，只能执行一次。我觉得是线程问题导致的。

**Comment by NovaNick** [comment]
不好意思，脑袋轴了，没看到。不过并不建议这样干，楼上大佬给你举了例子。

**Comment by pardont** [comment]
@2881099 我也是使用过程中偶然发现的，代码可以避免这样用，但是不知道为什么不行。

**Comment by pardont** [comment]
@NovaNick 没事啊，我只是想知道原因，代码不会这样写的

**Comment by pardont** [comment]
@2881099 WPF下，如果freesql的build在SizeChanged事件里执行就会卡住。我用GlobalData，在SizeChanged里面做一些操作，也会卡住：

> 
       private void MainPage_SizeChanged(object sender, EventArgs e)
        {
            Console.WriteLine("SizeChanged");
            if (isInited)
                return;

            isInited = true;

            //WPF上会一直卡住, 其他的平台都不会，很奇怪
            //Init();

            GlobalData.sqlite.CodeFirst.SyncStructure<Product>();
            //var table = GlobalData.sqlite.Ado.ExecuteDataTable("select * from Product");

        }

**Comment by 2881099** [comment]
@pardont 这个线程有关，我不知道 SizeChanged 事件是怎么触发的

但是这里可以加一个判断，可以保证只触发一次，最好把任务放到新的线程上支持，这样就不会阻塞 UI 线程

```csharp

   bool isInited = false;
   object isInitedLock = new object();
   private void MainPage_SizeChanged(object sender, EventArgs e)
    {
        Console.WriteLine("SizeChanged");

        if (isInited) return;

        lock (isInitedLock)
        {
            if (isInited) return;
            isInited = true;
        }
        new Thead(() =>
        {
           try
           {
               GlobalData.sqlite.CodeFirst.SyncStructure<Product>();
           }
           finally
           {
               lock (isInitedLock)
               {
                    isInited = false;  //还原状态
               }
           }
      }).Start();
    }
```

**Comment by pardont** [comment]
@2881099 嗯，这样是可以的

**Comment by densen2014** [comment]
居然有人撸Xamarin.Forms WPF,这么想不开. Xamarin.Forms WPF顶多也就是测试一下流程吧

**Comment by satelliteli** [comment]
【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 &gt; 生成 &gt; 目标平台：x86 | x64
为什么我一运行就报这个错误.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pardont"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午4:15
收件人:&nbsp;"2881099/FreeSql"<FreeSql@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[2881099/FreeSql] Xamarin.Forms WPF在Page.SizeChanged事件初始化IFreeSql会卡死 (#251)





 
Xamarin.Forms WPF在Page.SizeChanged事件初始化IFreeSql会卡死，不知道是什么原因。
 附件是测试用的解决方案代码：
 TestFreeSqlXamarinForms.zip
       public MainPage()     {         InitializeComponent();         this.SizeChanged += MainPage_SizeChanged;     }     bool isInited = false;     private void MainPage_SizeChanged(object sender, EventArgs e)     {         Console.WriteLine("SizeChanged");         if (isInited)             return;         isInited = true;         //WPF上会一直卡住, 其他的平台都不会，很奇怪         Init();     }     private void Init()     {         var fsql = new FreeSql.FreeSqlBuilder()                     .UseAutoSyncStructure(true)                     .UseNoneCommandParameter(true)                     .UseConnectionString(FreeSql.DataType.Sqlite, "data source=test.db;max pool size=5")                     .Build();     }

**Comment by 2881099** [comment]
> 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 &gt; 生成 &gt; 目标平台：x86 | x64 为什么我一运行就报这个错误.&nbsp;
> […](#)

sqlite 吗？按照提示设置了再运行

**Comment by satelliteli** [comment]
是sqllite, WPF的设置了是可以的。&nbsp;


但是在Xamarin.Forms&nbsp; Android下无论怎么配置都提示这个错误。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"2881099"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 上午8:41
收件人:&nbsp;"dotnetcore/FreeSql"<FreeSql@noreply.github.com&gt;;
抄送:&nbsp;"李卫星"<satelliteli@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/FreeSql] Xamarin.Forms WPF在Page.SizeChanged事件初始化IFreeSql会卡死 (#251)





  
【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 &gt; 生成 &gt; 目标平台：x86 | x64 为什么我一运行就报这个错误.&nbsp;
 …
  
sqlite 吗？按照提示设置了再运行

**Comment by 2881099** [comment]
@satelliteli 

1.主工程接口
public interface ISQLite
{
DbConnection GetConnection2();
}

3.安卓和ios分别平台分别引用Mono.Data.Sqlite，System.Data,实现 DbConnection GetConnection()

public DbConnection GetConnection2()
{
string MicrosoftdbPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Microsoft.Data.Sqlite.db");
var connv3 = new Mono.Data.Sqlite.SqliteConnection($"Data Source={MicrosoftdbPath};");
//connv3.Open();
return connv3;
}

4.主工程最终获取连接，建立IFreeSql

IFreeSql _fsql = new FreeSql.FreeSqlBuilder()
.UseConnectionFactory(FreeSql.DataType.Sqlite, () => DependencyService.Get().GetConnection2(), typeof(FreeSql.Sqlite.SqliteProvider<>))
.UseAutoSyncStructure(true)
//.UseMonitorCommand(cmd => Console.WriteLine(cmd.CommandText))
.UseNoneCommandParameter(true)
.Build();

来自：https://github.com/dotnetcore/FreeSql/issues/183#issuecomment-581886967
