### ISSUE TITLE
ToTreeList 的问题

### ISSUE THREAD

**Issue by guliang21** [dotnetcore/FreeSql#255]
试了多次都没成功，所以请教下，是否我写错了。
实体类：
```csharp
public class District
{
    [Column(IsPrimary = true, DbType = DbTypeConsts.Varchar, StringLength = 6)]
    public string Code { get; set; }

    [Column(StringLength = 20, IsNullable = false)]
    public string Name { get; set; }

    [Column(DbType = DbTypeConsts.Varchar, StringLength = 6)]
    public string ParentCode { get; set; }

    [Navigate(nameof(ParentCode))]
    public District Parent { get; set; }

    [Navigate(nameof(ParentCode))]
    public List<District> Childs { get; set; }
}
```
查询代码我是这么写的：
```csharp
db.Select<District>().LeftJoin(d => d.ParentCode == d.Parent.Code).ToTreeList();
```

**Comment by 2881099** [comment]
string 可能是null 的原因，等会发个 preview95 可以解决

**Comment by 2881099** [comment]
FreeSql.1.3.0-preview95

正在提交，预计 10 分钟后可以下载

**Comment by guliang21** [comment]
我测试没看到变化。我这个是行政区域表，应该是省、市、区 这样三级。我上面的写法返回结果是市一级的，367 条记录，而理论上，我想要的返回结果是省一级的 34 条记录。省下面有市，市下面有区。

我是用在页面选择区域的，类似淘宝的收获地址，一级级选择的。

**Comment by 2881099** [comment]
我这边用你的代码测试，可以。

测试代码  https://github.com/2881099/FreeSql/blob/e245543c5aa0c8b47984a104cfc7b2d4da4e69ba/FreeSql.Tests/FreeSql.Tests/Sqlite/Curd/SqliteSelectTest.cs#L213

**Comment by wanglantian** [comment]
hi,也遇到同样的问题，设置了导航属性，但是无法返回数据中没有Parent和Childs,可以请教下可能原因吗

**Comment by 2881099** [comment]
> hi,也遇到同样的问题，设置了导航属性，但是无法返回数据中没有Parent和Childs,可以请教下可能原因吗

注意如果继承的话，实体类的导航属性不要使用基类。
