### ISSUE TITLE
关于 oracle CLOB NCLOB 大文本类型

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#259]
v1.3.2 版本解决办法，使用 BLOB 类型 + byte[] 解决存储问题，读写正常。

```csharp
public byte[] Data { get; set; }
```

v1.3.2 后面的版本采取以下方法：

```csharp
[Column(DbType = "clob")]
public string Data { get; set; }

//或者

[Column(StringLength = -1)]
public string Data { get; set; }
```

**Comment by 2881099** [comment]
注意：

使用 .NoneParameter(true) 可能会报错 Oracle.ManagedDataAccess.Client.OracleException:“ORA-01704: 字符串文字太长”

**Comment by BangzhenTang** [comment]
为什么我使用
[Column(StringLength = -1)]
之后生成的表名会是
FTmp_开头的表？
