### ISSUE TITLE
SQL Server 批次添加不能成功

### ISSUE THREAD

**Issue by Bleibtreu** [dotnetcore/FreeSql#263]
批次添加SQL Server的时候出错，报SQL语法错误，可能是因为内部拼接SQL语句时出错

~~~C#

public virtual long Insert(object entity)
{
            return freeSql.Insert(entity).ExecuteAffrows();
 }

var songs = new[]
 {
             new Song { Name = "演员.mp3" },
             new Song { Name = "可一可再.mp3" },
             new Song { Name = "火.mp3" },
             new Song { Name = "达尔文.mp3" }
 };

Insert(songs);

~~~

**Comment by 2881099** [comment]
SQL语法错误，发出来看看，StackTrace，执行的 SQL 都发一下

**Comment by Bleibtreu** [comment]
主库（执行SQL）耗时33.8957ms
INSERT INTO [Object]() VALUES()
   CommitTimeoutTransaction: 1.4427ms
Pool.Return: 8.2911ms Total: 33.1088ms
“)”附近有语法错误。

**Comment by 2881099** [comment]
你这是弱类型啊，弱类型操作需要知道 T，但是 entity 这个 object 到底是什么类型？List ？ Song ？

public virtual long Insert<T>(T entity) where T : class
{
            return freeSql.Insert(entity).ExecuteAffrows();
 }

**Comment by Bleibtreu** [comment]
不太明白，我去了解下，解决后和你回复，至于object，应该是是我写的不对，确实不应该使用Object

**Comment by 2881099** [comment]
使用 object 可以，但不能直接 Insert(obj).ExecuteAffrows()，在 ORM 的层面要需要知道 obj 对应什么实体类型，然后才找得到对应数据库。

弱类型的话可以这样操作
```csharp
freeSql.Insert<object>().AsType(实体类型).AppendData(obj).ExecuteAffrows();
```

**Comment by 2881099** [comment]
另外可以看看 FreeSql.Repository 提供的通用仓储类实现

API：https://github.com/dotnetcore/FreeSql/wiki/API#baserepositorytentity-tkey

**Comment by 2881099** [comment]
FreeSql.Repository 实现了通用仓储层功能。与其他规范标准一样，仓储层也有相应的规范定义。FreeSql.Repository 参考 abp vnext 接口，定义和实现基础的仓储层（CURD）。

## 特性

- Select/Attach 快照对象，Update 只更新变化的字段；
- Insert 插入数据，适配各数据库优化执行 ExecuteAffrows/ExecuteIdentity/ExecuteInserted；
- InsertOrUpdate 插入或更新；
- SaveMany 方法快速保存导航对象（一对多、多对多）；

## 安装

> dotnet add package FreeSql.Repository

https://github.com/dotnetcore/FreeSql/wiki/Repository

**Comment by Bleibtreu** [comment]
强弱类型，了解了，但是你上面的示例如果传入List的话是不能直接执行插入操作吧，T与List不可以吧

System.NullReferenceException:“Object reference not set to an instance of an object.”

**Comment by 2881099** [comment]
```csharp
freeSql.Insert<object>().AsType(实体类型).AppendData(obj).ExecuteAffrows();
```

是说这个方法吗？此时 obj 为实体类型，而不应该是 List，AppendData F12 看看重载

**Comment by Bleibtreu** [comment]
~~~C#
public virtual long Insert<T>(T entity) where T : class
{
            return freeSql.Insert(entity).ExecuteAffrows();
}
~~~

**Comment by Bleibtreu** [comment]
~~~C#
public virtual long Insert<T>(List<T> entity) where T : class
{
        return freeSql.Insert(entity).ExecuteAffrows();
}
~~~

这样写就可以了

**Comment by Bleibtreu** [comment]
我看您的源码，都是接口，不太懂如何找到具体源码位置，这一块的源码位置可否告诉一下

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Internal/CommonProvider/InsertProvider.cs

**Comment by Bleibtreu** [comment]
好的
