### ISSUE TITLE
FreeSql.Generator-NameOptions可以不可以加一个全大写

### ISSUE THREAD

**Issue by lichen0210** [dotnetcore/FreeSql#264]
用freesql生成的表名如果是小写，或者大小写混合的话，
在Toad、DM管理工具里，写sql需要在字段名和表名外加引号，
不加引号，会提示表不存在或字段不存在，这样很不方便，
全大写就不需要加引号了

**Comment by lichen0210** [comment]
可以自己改模板

**Comment by 2881099** [comment]
FreeSqlBuilder().UseNameConvert( 这个方法可以设置大小写转换

**Comment by lichen0210** [comment]
喔，原来在这里，谢谢

**Comment by 2881099** [comment]
是的，两个环节

第一环：生成实体类的时候，考虑实体类的命名，是否符合开发

第二环：orm 使用的实体类，怎么与数据库对应
