### ISSUE TITLE
分页怎么指定 SqlServer 版本

### ISSUE THREAD

**Issue by guliang21** [dotnetcore/FreeSql#266]
文档中说：

> SqlServer 2012 以前的版本，使用 row_number 分页；
SqlServer 2012+ 版本，使用最新的 fetch next rows 分页；

但是，FreeSql 是怎么知道 SqlServer 版本的？

我看 SQL 语句里面，用的是 fetch next rows，咋那么智能的？

**Comment by 2881099** [comment]
使用的时候已经判断了 sqlserver 版本，里面再做对应的用法
