### ISSUE TITLE
怎么在abp中集成FreeSql

### ISSUE THREAD

**Issue by zanderzhg** [dotnetcore/FreeSql#267]
FreeSql太好用了.
请在怎么在abp中集成使用?

**Comment by 2881099** [comment]
https://github.com/abpframework/abp/issues/1665

**Comment by 2881099** [comment]
## 如果在 abp-vnext 中使用？

本方法依赖 Volo.Abp.Dapper，所以也依赖 Volo.Abp.EntityFrameworkCore

提示：FreeSql 兼容 EFCore 99% 的实体特性

> dotnet add package FreeSql.Extensions.AdoNet

```csharp
IDapperRepository repo = ...;

repo.DbConnection.Select<T>().Where(...).ToList();

repo.DbConnection.Insert(new T {}).ExecuteAffrows();

repo.DbConnection.Update().SetSource(new T {}).ExecuteAffrows();

repo.DbConnection.Delete<T>().Where(...).ExecuteAffrows();

IFreeSql fsql = repo.DbConnection.GetFreeSql(); //获取 IFreeSql 实例
```

**Comment by 2881099** [comment]
提示：扩展包 FreeSql.Extensions.AdoNet 已移除，合并到 FreeSql 中了。

## Ado.Net 扩展方法

提供了类似 Dapper 的使用方法，FreeSql 增加了 IDbConnection/IDbTransaction 对象的扩展方法 Select/Insert/Update/Delete 实现 CRUD。

```csharp
using (var conn = new SqlConnection(""))
{
    conn.Select<T>().Where(...).ToList();

    conn.Insert(new T {}).ExecuteAffrows();

    conn.Update().SetSource(new T {}).ExecuteAffrows();

    conn.Delete<T>().Where(...).ExecuteAffrows();

    IFreeSql fsql = conn.GetFreeSql(); //获取 IFreeSql 实例，然后可以设置 Aop
}
```

利用本功能可以快速将 FreeSql 使用到项目中，只需要处理好实体类的特性。

提示：FreeSql 兼容 EFCore 99% 的实体特性

**Comment by qiang999** [comment]
集成ABP VNext后，CodeFirst是否和DbFirst不可用
![image](https://user-images.githubusercontent.com/15817336/99639127-33511900-2a82-11eb-954a-f01e99af6702.png)
error：
Object reference not set to an instance of an object.

**Comment by 2881099** [comment]
> 集成ABP VNext后，CodeFirst是否和DbFirst一样不可用？
> ![image](https://user-images.githubusercontent.com/15817336/99639127-33511900-2a82-11eb-954a-f01e99af6702.png)
> error：
> fsql.CodeFirst.SyncStructure(typeof(BusinessCode), "business_codes_2");
> Object reference not set to an instance of an object.

扩展方法适合 crud，如果要用 codefirst/dbfirst 可以创建 Freesqlbuilder 来做

**Comment by qiang999** [comment]
> > 集成ABP VNext后，CodeFirst是否和DbFirst一样不可用？
> > ![image](https://user-images.githubusercontent.com/15817336/99639127-33511900-2a82-11eb-954a-f01e99af6702.png)
> > error：
> > fsql.CodeFirst.SyncStructure(typeof(BusinessCode), "business_codes_2");
> > Object reference not set to an instance of an object.
> 
> 扩展方法适合 crud，如果要用 codefirst/dbfirst 可以创建 Freesqlbuilder 来做

好的，谢谢

**Comment by DHclly** [comment]
```
public async Task<string> GetDatabaseInfoAsync()
        {
            using var connection = await GetDbConnectionAsync();
            var result = await connection.QueryFirstAsync<string>("select version()");
            var fs = connection.GetIFreeSql();
            var query = fs.Ado.CommandFluent("select version()");
            result = query.ExecuteScalar() as string;
            return await Task.FromResult(result);
        }
```
我这样写，第一个queryfirst可以正常查询出来，但是第二个  query.ExecuteScalar() 报错，提示
Object reference not set to an instance of an object.
通过 `onnection.GetIFreeSql();` 获取的实例无法正常使用？我直接单例build的IFreeSql可以执行第二个语句

**Comment by DHclly** [comment]
```
using var connection = await GetDbConnectionAsync();
result = await connection.QueryFirstAsync<string>("select version()");
var item1 = FreeSql.Select<TodoItem>().Where(x => x.Id == 1).ToOne();
var q = connection.Select<TodoItem>();
var item2 = q.Where(x => x.Id == 1).ToOne();
```
同样的查询代码，用IFreeSql的Select方法可以，但是用 `AdoNetExtensions.Select` 扩展方法报错，提示 `Unable to cast object of type 'MySqlConnector.MySqlConnection' to type 'MySql.Data.MySqlClient.MySqlConnection` , 我已经去掉了FreeSql.Provider.MySql，只保留了 FreeSql.Provider.MySqlConnector

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Extensions/AdoNetExtensions.cs

adonet 扩展代码的实现在这里。

**Comment by 2881099** [comment]
因为 mysql 有两个驱动，connection 类型要统一才行。

**Comment by tzm2270969436** [comment]
> ## 如果在 abp-vnext 中使用？
> 本方法依赖 Volo.Abp.Dapper，所以也依赖 Volo.Abp.EntityFrameworkCore
> 
> 提示：FreeSql 兼容 EFCore 99% 的实体特性
> 
> > dotnet add package FreeSql
> 
> IDapperRepository repo = ...;
> 
> repo.DbConnection.Select<T>().Where(...).ToList();
> 
> repo.DbConnection.Insert(new T {}).ExecuteAffrows();
> 
> repo.DbConnection.Update().SetSource(new T {}).ExecuteAffrows();
> 
> repo.DbConnection.Delete<T>().Where(...).ExecuteAffrows();
> 
> IFreeSql fsql = repo.DbConnection.GetFreeSql(); //获取 IFreeSql 实例

我有个疑问，如果需要访问MySql，我希望在abp vnext中使用FreeSql，我引用[Volo.Abp.Dapper](https://www.nuget.org/packages/Volo.Abp.Dapper)、[FreeSql](https://www.nuget.org/packages/FreeSql)、[FreeSql.Provider.MySql](https://www.nuget.org/packages/FreeSql.Provider.MySql)之后，我是否还需要引用[Volo.Abp.EntityFrameworkCore.MySQL](https://www.nuget.org/packages/Volo.Abp.EntityFrameworkCore.MySQL)???，然后依赖注入的时候注入了IFreeSql，那么我是否还需要注册EF Core DbContext的数据库连接？因为EF Core对国产数据库兼容不友好，我希望所有的数据库操作都是通过FreeSql连接去执行，不知道能不能做到...

**Comment by tzm2270969436** [comment]
> > 
> 
> 嗯，是的，估计是这个扩展模式只支持 的吧，本来想在 Abp 里面类似Dapper 集成下FreeSql的，后面发现问题多，把底层仓储模式直接改用FreeSql官网的 Repository 实现了，然后把Abp的CrudAppservice 源码里面的Repository调用用FreeSql的封装了一下，搞定了^.^，API确实差别不大，改动小`MySql.Data.MySqlClient.MySqlConnection`

我写了一个示例程序[book-store](https://gitee.com/tzm22270969436/book-store)，FreeSql继承abp的Repository，可以实现CRUD功能，但是没法绑定ABP的UowManager事务，请问你那边UowManager事务操作是怎么实现的？
