### ISSUE TITLE
[建议] FreeContext 能否提供 一些更有FreeSql特色的方法

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#270]
```C#
public ISelect<T1> Select<T1>() where T1 : class
{
   //调用Set<T1>().OrmSelect()
}
public IInsert<T1> Insert<T1>() where T1 : class
{
   //调用Set<T1>().OrmInsert()
}
public IUpdate<T1> Update<T1>() where T1 : class
{
   // 调用Set<T1>().OrmUpdate(null)
}
public IDelete<T1> Delete<T1>() where T1 : class
{
   // 调用Set<T1>().OrmDelete(null)
}
```
从这里调用的话，比起 直接Orm.Insert<T1>() 可以少写WithTransaction()等代码
不过， Select<T>() 和 Set<T1>().Select 有些重了，其他几个我觉得会比较有用
还有， OrmInsert、OrmUpdate、OrmDelete好像都是protected的

**Comment by 2881099** [comment]
你是用 fsql.CreateDbContext() 这样的方式还是继承？

**Comment by tky753** [comment]
我参考EfCore和FreeSql.DbContext自己实现了一套DbContext，
当然大部分代码都是直接复制粘贴的，还只支持.net standard 2.0。
然后遇到需求，要 "更新指定列"，看文档需要获取IUpdate<T>，但DbContext或DbSet似乎没有public的API，
只有DbSet里有个protected 的OrmUpdate，
虽然可以这么写：DbContext.Orm.Update<T>()，但发现每次都要WithTransaction()有点烦，因此想到如果能封装一个获取IUpdate<T>的接口就方便多了

**Comment by tky753** [comment]
我是 用依赖注入直接 Resolve DbContext的

**Comment by 2881099** [comment]
等一会提交了代码，我做了一个 IFreeSql 代理实现类

**Comment by 2881099** [comment]
之前：如果有事务  repo.Orm.Insert(...).WithTransaction(repo.UnitOfWork.GetOrBeginTransaction()).ExecuteAfforws()

  现在：直接 repo.Orm.Insert(...).ExecuteAffrows() 即可

**Comment by 2881099** [comment]
1.4.0-preview20200411 发布了
