### ISSUE TITLE
能否自定义Guid Generator

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#274]
FreeSql好像是调用 FreeUtil.NewMongodbId() 来生成Guid的，
我想要用其他的生成算法，虽然也可以在BaseEntity里new，但那地方不好依赖注入吧
如果能在 `FreeSqlBuilder`中设置的话，就太棒了

不行的话，能否加个不自动生成Guid，类似于EfCore里 PropertyBuilder . ValueGeneratedNever()
我在SaveChanges()方法中自己来赋值也可以

**Comment by 2881099** [comment]
可以的，我把优先级调低了，低于 Aop.AuditValue 事件

**Comment by 2881099** [comment]
```csharp
fsql.Aop.AuditValue += (s, e) => 
{
    if (e.Column.CsType == typeof(guid) && e.Column.IsPrimary)
        e.Value = Guid.NewGuid(); //在这里
};
```

**Comment by 2881099** [comment]
nuget v1.4.0-preview0414 版本已发布
