### ISSUE TITLE
IsNullable能否对Entity值为null的字段选择不插入

### ISSUE THREAD

**Issue by zerone1990** [dotnetcore/FreeSql#275]
目前Entity的字段如果值为Null，那么Insert的时候依然会插入默认值，能否设计成如果Entity的属性标记了IsNullable = true，那么值为Null的时候，生成插入语句时不插入该字段?

**Comment by 2881099** [comment]
考虑到批量插入的情况，不好判断

有可能第一行 col2 col3 null

第二行 col3 col4 null

**Comment by zerone1990** [comment]
那么，能否这样？InsertColumns必须一次性指定，能否提供可以调用多次的InsertColumn，这样的话可以根据请求参数动态处理需要插入的字段

**Comment by 2881099** [comment]
明白，因为简单设计把它和 IgnoreColumns 用的是一个字典存储信息，追加使用会产生使用性的矛盾。

可以自己定义一个 List<string> 最终一次性调用 InsertColumns 来处理。

**Comment by zerone1990** [comment]
自定义List的话，List中的元素必须是数据库中的字段名对吧？这样感觉不如实体属性来的舒服

**Comment by 2881099** [comment]
我记错了，IUpdate 才有 string[] 指定，我把 IInsert 也加上对应的方法吧。

字段名或属性名，都有效

**Comment by zerone1990** [comment]
我看InsertColumns的注释中，是有new[] {"name", "time"}的注释

**Comment by 2881099** [comment]
好吧，那就是功能重复，重载方法已经加了

**Comment by zerone1990** [comment]
感谢大佬，这个release预期什么时候发布呢？

**Comment by 2881099** [comment]
release 每个月底，正在发 preview

**Comment by zerone1990** [comment]
报告这次commit的1个bug，InsertColumns的string[]参数重载，如果是实体属性名称，没问题，如果是数据库字段就有问题，不过我觉得可以考虑先关闭此问题了

**Comment by 2881099** [comment]
大约是什么 bug 方便描述一下吗

**Comment by zerone1990** [comment]
mysql数据库，这次添加的InsertColumns的string[]参数重载，如果数组中是实体属性名称，没问题，如果是数据库的字段名，生成的sql就不正常

**Comment by zerone1990** [comment]
不过我觉得也正常，虽然你在方法的注释中填写了属性名或字段名，但是我觉得，字符串值的意义做到多样性很困难，现在这样很好了
