### ISSUE TITLE
是否可以插入一个全局的Datetime 格式化器

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#276]
针对所有DateTime 和 DateTime?类型且 != null 的数据，在生成查询结果
以及 保存进数据库前 统一 通过 `Datetime 格式化器` 进行格式化，例如 
```C#
public interface IClock
{
    DateTime Normalize(DateTime dateTime); //调用这个方法
}

public class Clock : IClock
{
    public DateTime Normalize(DateTime dateTime)
    {
        return dateTime.ToUniversalTime();
    }
}
```

**Comment by tky753** [comment]
估计很难实现吧，得要像JsonMap那样搞

**Comment by 2881099** [comment]
统一行为一刀切，可能把一些不需要转时区的地方也转了

**Comment by tky753** [comment]
我看Abp是在DbContext里设置的
![image](https://user-images.githubusercontent.com/18205977/79300894-a443b780-7f1a-11ea-809a-6ea3cd4f599e.png)
