### ISSUE TITLE
FreeSql.DbContext & FreeSql.Extensions.BaseEntity能否支持.NETStandard 2.0

### ISSUE THREAD

**Issue by shuaqq2004** [dotnetcore/FreeSql#277]
现在这些库是 .NetCoreApp  能够改成 NS的支持方式？

**Comment by 2881099** [comment]
netstandard 可以使用的

**Comment by 2881099** [comment]
因为 .net core 2.1 3.1 msdi 基础库版本问题，导致版本冲突。

netstandard 模式下，我们不知道要引用哪一个 msdi 版本。用最新的会导致老项目不可用，用旧的又不能在 core3.1 使用。
