### ISSUE TITLE
ColumnFluent能否增加扩展方法 UseJsonMap(a=>a.Property)

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#279]
ABP框架规定  领域层（定义实体的dll）和 数据库实现 解耦，
定义实体类的dll 不会引用 ORM框架 的dll，因此不会引用 `FreeSql.Extensions.JsonMap`。

我想到一个可能的解决方案：在ORM层引用 `FreeSql.Extensions.JsonMap`后，ColumnFluent 增加扩展方法 `UseJsonMap(a=>a.Property)`，那就迎刃而解了。

Mmm，这也是权宜之计，如果哪天ColumnFluent 实现了 `HasConversion`，可能这个方法也会被淘汰了吧。

**Comment by tky753** [comment]
话说是否应该在`ColumnAttribute`  增加一个Dictionary<string, object>来存储扩展数据，方便扩展，就是不知道对速度有多大影响

**Comment by 2881099** [comment]
HasConversion 和 UseJsonMap 之间有什么关系

**Comment by 2881099** [comment]
> 话说是否应该在`ColumnAttribute` 增加一个Dictionary<string, object>来存储扩展数据，方便扩展，就是不知道对速度有多大影响

主要是什么用途，ColumnAttribute 这里的属性有点多了，要控制尽量不增加

**Comment by 2881099** [comment]
```csharp
BaseEntity.Orm.UseJsonMap();
BaseEntity.Orm.CodeFirst.ConfigEntity<S_SysConfig<TestConfig>>(a =>
{
    a.Property(b => b.Config2).JsonMap();
});

new S_SysConfig<TestConfig> { Name = "testkey11", Config = new TestConfig { clicks = 11, title = "testtitle11" }, Config2 = new TestConfig { clicks = 11, title = "testtitle11" } }.Save();

new S_SysConfig<TestConfig> { Name = "testkey22", Config = new TestConfig { clicks = 22, title = "testtitle22" }, Config2 = new TestConfig { clicks = 11, title = "testtitle11" } }.Save();

new S_SysConfig<TestConfig> { Name = "testkey33", Config = new TestConfig { clicks = 33, title = "testtitle33" }, Config2 = new TestConfig { clicks = 11, title = "testtitle11" } }.Save();

var testconfigs11 = S_SysConfig<TestConfig>.Select.ToList();
```

其实蛮好扩展成 FluentApi

**Comment by tky753** [comment]
我是想在ColumnAttribute中保存 JsonMap状态，然后ConfigEntityProperty中根据这个状态来判断是否需要处理，
不过现在在外部用ConcurrentDictionary<Type, ConcurrentDictionary<string, bool>>保存状态。效果也一样就是了
