### ISSUE TITLE
JsonMap 无法 用Repository  Update

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#280]
```C#
[FreeSql.DataAnnotations.Table(Name = "BookTpls")]
public class BookTpl
{
    public Guid Id { get; protected set; }
    public string Name { get; set; }
    public Dictionary<string, object> ExtraProperties { get; protected set; }
    /// <summary>
    /// 备注
    /// </summary>
    [NotMapped]
    public string Remark
    {
        get => (string) ExtraProperties[nameof(Remark)];
        set => ExtraProperties[nameof(Remark)] = value;
    }
}

fsql.UseJsonMap();
fsql.CodeFirst.ConfigEntity<BookTpl>(a => a.Property(a1 => a1.ExtraProperties).JsonMap());
var guid = new Guid("552E91FE-5BBD-4048-0E8C-08D78A631E82");
var resp = fsql.GetRepository<BookTpl>();
var entity = await resp.Select.Where(a => a.Id == guid).FirstAsync();
entity.Remark = "qaz";
await resp.UpdateAsync(entity);
```

无法update

**Comment by 2881099** [comment]
对的，因为判断对象的引用还是一个

**Comment by 2881099** [comment]
```csharp
    [NotMapped]
    public string Remark
    {
        get => (string) ExtraProperties[nameof(Remark)];
        set
        {
             var clone = ExtraProperties.MyClone();
             clone[nameof(Remark)] = value;
         }
    }
```

**Comment by tky753** [comment]
好的

**Comment by tky753** [comment]
EntityUtilExtensions.cs 中的
public static void MapEntityValue(this IFreeSql orm, Type entityType, object entityFrom, object entityTo)
这个方法，Map的时候顺带深拷贝属性是否会好一些？

**Comment by tky753** [comment]
问一下，我看，Abp的Update是这么写的，FreeSql是不是应该去掉这句Attach？
![image](https://user-images.githubusercontent.com/18205977/79720009-565ff280-8312-11ea-8e87-f09e3f91e111.png)
```C#
public override async Task<TEntity> UpdateAsync(TEntity entity, bool autoSave = false, CancellationToken cancellationToken = default)
{
    DbContext.Attach(entity);

    var updatedEntity = DbContext.Update(entity).Entity;

    if (autoSave)
    {
        await DbContext.SaveChangesAsync(GetCancellationToken(cancellationToken));
    }

    return updatedEntity;
}
```

**Comment by 2881099** [comment]
> EntityUtilExtensions.cs 中的
> public static void MapEntityValue(this IFreeSql orm, Type entityType, object entityFrom, object entityTo)
> 这个方法，Map的时候顺带深拷贝属性是否会好一些？

深度 clone 有问题，特别是导航属性循环引用的时候，做这个会引来很多题外问题。

**Comment by 2881099** [comment]
> 问一下，我看，Abp的Update是这么写的，FreeSql是不是应该去掉这句Attach？
> ![image](https://user-images.githubusercontent.com/18205977/79720009-565ff280-8312-11ea-8e87-f09e3f91e111.png)
> 
> ```cs
> public override async Task<TEntity> UpdateAsync(TEntity entity, bool autoSave = false, CancellationToken cancellationToken = default)
> {
>     DbContext.Attach(entity);
> 
>     var updatedEntity = DbContext.Update(entity).Entity;
> 
>     if (autoSave)
>     {
>         await DbContext.SaveChangesAsync(GetCancellationToken(cancellationToken));
>     }
> 
>     return updatedEntity;
> }
> ```

对，机制应该不一样

**Comment by luoyunchong** [comment]
> > 问一下，我看，Abp的Update是这么写的，FreeSql是不是应该去掉这句Attach？
> > ![image](https://user-images.githubusercontent.com/18205977/79720009-565ff280-8312-11ea-8e87-f09e3f91e111.png)
> > ```cs
> > public override async Task<TEntity> UpdateAsync(TEntity entity, bool autoSave = false, CancellationToken cancellationToken = default)
> > {
> >     DbContext.Attach(entity);
> > 
> >     var updatedEntity = DbContext.Update(entity).Entity;
> > 
> >     if (autoSave)
> >     {
> >         await DbContext.SaveChangesAsync(GetCancellationToken(cancellationToken));
> >     }
> > 
> >     return updatedEntity;
> > }
> > ```
> 
> 对，机制应该不一样

这个我看 EFCore，如果一个数据在状态管理中，再次Attach，如果之前已经修改了数据，依然生效。


FreeSql的DbContext是Attach之后，之前的修改就失效了！ @2881099

**Comment by 2881099** [comment]
> > > 问一下，我看，Abp的Update是这么写的，FreeSql是不是应该去掉这句Attach？
> > > ![image](https://user-images.githubusercontent.com/18205977/79720009-565ff280-8312-11ea-8e87-f09e3f91e111.png)
> > > ```cs
> > > public override async Task<TEntity> UpdateAsync(TEntity entity, bool autoSave = false, CancellationToken cancellationToken = default)
> > > {
> > >     DbContext.Attach(entity);
> > > 
> > >     var updatedEntity = DbContext.Update(entity).Entity;
> > > 
> > >     if (autoSave)
> > >     {
> > >         await DbContext.SaveChangesAsync(GetCancellationToken(cancellationToken));
> > >     }
> > > 
> > >     return updatedEntity;
> > > }
> > > ```
> > 
> > 
> > 对，机制应该不一样
> 
> 这个我看 EFCore，如果一个数据在状态管理中，再次Attach，如果之前已经修改了数据，依然生效。
> 
> FreeSql的DbContext是Attach之后，之前的修改就失效了！ @2881099

相当于中间的那次Attach等同于Update+Attach
