### ISSUE TITLE
DbContext的OnModelCreating在构造函数时就会执行是否有点不好

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#282]
很多情况下会对DbContext进行继承订制，然后通过依赖注入的方式来创建实例，同时会注入很多东西。但因为`OnModelCreating`是在构造函数里调用的`(ctor -> InitPropSets() -> OnModelCreating())`，导致很多注入的组件还是null。

是不是在调用`IDbSet Set(Type entityType)`方法时再调用比较合理

Mmm，我是在EfCore的DbContxt转FreeSql时发现的这个问题。

**Comment by 2881099** [comment]
是的，现在在 InitPropSets 里面做的触发。在 ctor 这里处理这个，能保证实例化后直接使用 DbSet 属性。

如果是自己定义 DbContext，可以在自己的 ctor 重新触发一次 OnModelCreating

```csharp
class BaseDbContext : FreeSql.DbContext
{
     public BaseDbContext(IFreeSql fsql, DbContextOptions options) : base(fsql, options)
     { 
          OnModelCreating(fsql.CodeFirst);
     }
}
```

目前能发现的缺点：HasData 种子数据会触发两次事件，但不会重复添加。

**Comment by tky753** [comment]
如果是构造函数参数注入的话，这样就可以了。
但是，属性注入的话，因为是在执行完构造函数后再赋值的，就没办法了。

**Comment by 2881099** [comment]
属性 set 里面也加上：OnModelCreating(fsql.CodeFirst);

**Comment by 2881099** [comment]
为了保证执行顺序，可以考虑放弃属性注入

**Comment by tky753** [comment]
放弃属性注入的话，那就应该注入在DbContextOptions了，虽然有点奇怪，但也凑合能用。
至少比直接构造函数参数注入要轻很多。
