### ISSUE TITLE
有没有办法实现属性修改日志

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#284]
`DbContext.EntityChangeReport.ChangeInfo` 能不能扩展一下，增加属性修改相关的数据，例如，修改字段名、修改前字段值、修改后字段值

**Comment by 2881099** [comment]
因为它本身是一个List，Update前面的节点有他修改之前的值。

变化的属性，可以用未公开的内部方法，FreeSql.Extensions.EntityUtil 应该是这个类，下面有一些动态操作实体的方法。

**Comment by tky753** [comment]
好的，我研究一下

**Comment by 2881099** [comment]
可以对比出两个相同type，但是它们都是object弱类型的属性值变化部分
