### ISSUE TITLE
需求，批量插入时是否可以支持DataTable

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#286]
使用场景：
在一些专业性的系统中，需要将一些专业软件中的数据（如ArcGIS 的GDB，不支持Sql语句）导入到Sqlite中，以便使用一下Sql语句。这时，没有实体对象，会先根据gdb中的表在Sqlite中创建对应的表，然后将gdb中的数据查询到一个DataTable，在批量插入到Sqlite中

**Comment by 2881099** [comment]
> 会先根据gdb中的表在Sqlite中创建对应的表

这步是自己写 create table 创建的吗

**Comment by exy3351** [comment]
是的，若有其他好的方式那就更好了

**Comment by 2881099** [comment]
如果根据 gdb 生成一个 csharp 实体类，有没有难度，解决这个就全部解决了

**Comment by exy3351** [comment]
这个就有难度了，根据实际的业务不同，gdb里面的数据也是不一样的，而且同一业务中的数据也是有差别的，数据一般是甲方在生产过程中产生的，不同生产单位提交的数据结构都或多或少有差别，定义不了实体，我目前的操作方式是：先定义个字段对象，如Field，然后根据gdb中的表创建一个List<Field>的集合，在根据这个集合拼接成Sql，就可以建表了

**Comment by 2881099** [comment]
其实一样，问题在于 Field 是什么类型

**Comment by 2881099** [comment]
拼接成 create table 和我public class 是一样的，区别在类型上

**Comment by exy3351** [comment]
Field 就是一个字段对象，有字段名称、字段类型、长度等，也就是建表时说需要的一些信息；然后根据这个拼接成一个 Create Table 的语句，字段类型最后换转成数据库中实际对应的类型

**Comment by exy3351** [comment]
先说明一下，这是我在使用其他Orm时自己加的一个扩展，现在想迁移到FreeSql上，但考虑到项目中大量用到这个功能了，考虑到迁移的工作量的问题，所以看这个需求是否可以实现

**Comment by 2881099** [comment]
如果弄成codefirst的方式，就很好办了。

纯 Datatable 很容易发生转换失败的情况，不适合做插入

**Comment by 2881099** [comment]
还有一个办法，程序运行过程中，

1. 利用 freesql dbfirst 把 sqlite 表生成为 csharp 实体类

2. 把 DataTable 转换成 List\<object>

3. 利用 fsql.Insert AsType 功能插入

**Comment by exy3351** [comment]
codefirst、dbfirst之前都尝试过，基本上没法满足需求，做的就是数据检查、规整的项目，所有前期是没法规定数据结构的；在程序中控制好Datatable与生成的数据表保持一致，基本上不错出错，至少在目前使用的项目中是没有遇到导入失败的问题

**Comment by 2881099** [comment]
如果格式对的，可以考虑拼成 insert into t values() 这样的语句再执行。

只有 datatable 无法知道列，所以生成的 sql 只能默认顺序的方式。

**Comment by exy3351** [comment]
在插入DataTable时可以要求保证和表结构一致； 转成 insert into t values() 一是比较繁琐，一是性能怎么样，我现在用的是 Adapter.Update(datatable);  性能与insert into怎么样，没比较过，在可接受的范围内
SQLiteCommand cmd = new SQLiteCommand(sql, conn);
                    SQLiteDataAdapter adapter = new SQLiteDataAdapter(cmd);
                    //不能删除，否则新增失败
                    SQLiteCommandBuilder cb = new SQLiteCommandBuilder(adapter);
                    DataTable dsNew = new DataTable();
                    adapter.AcceptChangesDuringFill = false;
                    adapter.Fill(dsNew);
                    for (int i = 0; i < dataTable.Rows.Count; i++)
                    {
                        DataRow dr = dsNew.NewRow();
                        for (int j = 0; j < dataTable.Columns.Count; j++)
                        {
                            dr[dsNew.Columns[j].ColumnName] = dataTable.Rows[i][j];
                        }

                        dsNew.Rows.Add(dr);
                    }

                    adapter.Update(dsNew);
                    dataTable.Dispose();
