### ISSUE TITLE
在 asp.net core 中使用 UnitOfWorkManager 实现多种事务传播

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#289]
本篇文章内容引导，如何在 asp.net core 项目中使用特性(注解) 的方式管理事务。

> UnitOfWorkManager 只可以管理 Repository 仓储对象的事务，直接 fsql.Insert\<T>() 是不行的！！

支持六种传播方式(propagation)，意味着跨方法的事务非常方便，并且支持同步异步：

- Requierd：如果当前没有事务，就新建一个事务，如果已存在一个事务中，加入到这个事务中，默认的选择。
- Supports：支持当前事务，如果没有当前事务，就以非事务方法执行。
- Mandatory：使用当前事务，如果没有当前事务，就抛出异常。
- NotSupported：以非事务方式执行操作，如果当前存在事务，就把当前事务挂起。
- Never：以非事务方式执行操作，如果当前事务存在则抛出异常。
- Nested：以嵌套事务方式执行。

### 第一步：配置 Startup.cs 注入

```csharp
//Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IFreeSql>(fsql);
    services.AddScoped<UnitOfWorkManager>();
    services.AddFreeRepository(null, typeof(Startup).Assembly);
}
```

| UnitOfWorkManager 成员 | 说明 |
| -- | -- |
| IUnitOfWork Current | 返回当前的工作单元 |
| void Binding(repository) | 将仓储的事务交给它管理 |
| IUnitOfWork Begin(propagation, isolationLevel) | 创建工作单元 |

### 第二步：定义事务特性

```csharp
[AttributeUsage(AttributeTargets.Method)]
public class TransactionalAttribute : Attribute
{
    /// <summary>
    /// 事务传播方式
    /// </summary>
    public Propagation Propagation { get; set; } = Propagation.Requierd;
    /// <summary>
    /// 事务隔离级别
    /// </summary>
    public IsolationLevel? IsolationLevel { get; set; }
}
```

### 第三步：引入动态代理库

在 Before 从容器中获取 UnitOfWorkManager，调用它的 var uow = Begin(attr.Propagation, attr.IsolationLevel) 方法

在 After 调用 Before 中的 uow.Commit 或者 Rollback 方法，最后调用 uow.Dispose

### 第四步：在 Controller 或者 Service 或者 Repository 中使用事务特性

```csharp
public class SongService
{
    BaseRepository<Song> _repoSong;
    BaseRepository<Detail> _repoDetail;
    SongRepository _repoSong2;

    public SongService(
        BaseRepository<Song> repoSong,
        BaseRepository<Detail> repoDetail,
        SongRepository repoSong2)
    {
        _repoSong = repoSong;
        _repoDetail = repoDetail;
        _repoSong2 = repoSong2;
    }

    [Transactional]
    public virtual void Test1()
    {
        //这里 _repoSong、_repoDetail、_repoSong2 所有操作都是一个工作单元
        this.Test2();
    }

    [Transactional(Propagation = Propagation.Nested)]
    public virtual void Test2() //嵌套事务，新的（不使用 Test1 的事务）
    {
        //这里 _repoSong、_repoDetail、_repoSong2 所有操作都是一个工作单元
    }
}
```

是不是进方法就开事务呢？

不一定是真实事务，有可能是虚的，就是一个假的 unitofwork（不带事务）

也有可能是延用上一次的事务

也有可能是新开事务，具体要看传播模式

示范项目：https://github.com/dotnetcore/FreeSql/tree/master/Examples/aspnetcore_transaction

**Comment by 2881099** [comment]
下面是在 Controller Action 中做 AOP 处理：

```csharp
[AttributeUsage(AttributeTargets.Method)]
public class TransactionalAttribute : Attribute, IActionFilter
{
    public Propagation Propagation { get; set; } = Propagation.Requierd;
    public IsolationLevel? IsolationLevel { get; set; }

    public void OnActionExecuting(ActionExecutingContext context) => OnBefore(context.HttpContext.RequestServices.GetService(typeof(UnitOfWorkManager)) as UnitOfWorkManager);
    public void OnActionExecuted(ActionExecutedContext context) => OnAfter(context.Exception);

    Task OnBefore(UnitOfWorkManager uowm)
    {
        _uow = uowm.Begin(this.Propagation, this.IsolationLevel);
        return Task.FromResult(false);
    }
    Task OnAfter(Exception ex)
    {
        try
        {
            if (ex == null) _uow.Commit();
            else _uow.Rollback();
        }
        finally
        {
            _uow.Dispose();
        }
        return Task.FromResult(false);
    }
}
```

**Comment by yus1977** [comment]
FreeSql.DynamicProxy能够和Autofac一起使用吗

**Comment by 2881099** [comment]
> FreeSql.DynamicProxy能够和Autofac一起使用吗

不可以，Aop 用一个就好，Autofac 也有动态代理的功能。

**Comment by kyocn** [comment]
``` C#
using (var uow = BaseEntity.Begin())
{
      var u11 = await User1.FindAsync(Guid.Parse("5EB533BE-70AA-5CE8-00F2-85CC2D45A61E"));
      u11.Description = "备注22";
      await u11.SaveAsync();
      uow.Rollback(); //这个地方rollback无效
}
```
有个问题, FindAsync之后调用SaveAsync，Rollback无效

**Comment by 2881099** [comment]
@kyocn 这个问题与 UnitOfManager 无关，开个新问题吧

**Comment by yus1977** [comment]
事务传播使用过程中发现一个BUG
如下面的代码
`c#
public void FunMain(){
     //代码1：
     //事务处理方法
      FuncA();

      //代码2:
      //读取、前面FuncA中添加、更新的数据
       .......
}

[Transaction]
public virtual  void FunA(){
      //代码2.1
      //查询数据,或不访问数据库
      .........

      //代码2.2
      //添加、更新数据到数据库
      FuncA_1();
}

[Transaction]
public virtual  void FuncA_1(){
      //代码2.2.1
      //添加、更新数据到数据库
      .......
}
`
执行完“代码1”后，“代码2”访问不到前面的事务中提交的数据，只有当方法FunMain全部结束后，数据才真正的提交到数据库。
我分析原因可能如下：
1、方法FunA和FuncA_1都标记了事务
2、首先进入FunA，UnitOfWorkManager标记启动事务，
3、“代码2.1”到“代码2.2”之间并没有对数据库执行“增、删、改”操作，所以并没有真正启动事务
4、然后“代码2.2”中，FunA中调用了FuncA_1，FuncA_1中传递了工作单元，UnitOfWorkManager标记启动事务
5、FuncA_1中对数据库执行了“增、删、改”操作，真正启动了事务
6、最后，FuncA_1执行完成提交事务，FunA执行完成提交事务

在第3步并没有真正启动事务，可能导致了Bug，执行完第6步后并没有真正把数据提交到数据库。
如果在第3步中，增加修改数据库的代码，那么第3步时就会真正启动事务，执行完第6步后，数据库里就有提交的数据。

**Comment by yus1977** [comment]
另外请问，如果启用了主从库。
当启用事务时，会自动读取主库吗？
如果类似上面第3步的情况，会自动读取主库吗？

**Comment by 2881099** [comment]
是的，默认读取从库。

**Comment by 2881099** [comment]
2.1 2.2 之间会开启事务，看看是不是读了从库

**Comment by yus1977** [comment]
我确认了一下，开启事务或使用工作单元标记事务后，都是默认读取主库

**Comment by 2881099** [comment]
有没有demo，我试试

**Comment by yus1977** [comment]
我是直接在现有的项目中测试的，Demo一下子剥离不出来

**Comment by yus1977** [comment]
我是直接在现有的项目中测试的，Demo一下子剥离不出来

**Comment by 2881099** [comment]
TransactionAttribute 的 动态代理，有执行 OnBefore(Begin) OnAfter(Commit) 吗

**Comment by 2881099** [comment]
fsql.Aop.TraceBefore
fsql.Aop.TraceAfter

这两个事件监视起来

**Comment by yus1977** [comment]
OK，我试试   fsql.Aop.TraceBefore, fsql.Aop.TraceAfter

**Comment by yus1977** [comment]
上面的那段代码，
fsql.Aop.TraceBefore：执行“代码1“时，启动了一次事务
fsql.Aop.TraceAfter：执行完”代码1“时，这个跟踪没有被触发，事务没有成功提交

**Comment by yus1977** [comment]
经过测试，类似上面的代码，在同一个类中
在标记事务的方法内，调用另一个标记事务方法时。
跟踪结果是：
    fsql.Aop.TraceBefore：事务在第一次时启动了
    fsql.Aop.TraceAfter：方法执行结束后，事务并没有真正提交。只有当前线程执行结束后，才会真正提交事务。

**Comment by 2881099** [comment]
其实可以换个测试方式

var uowm = new UnitOfWorkManager(fsql);
var repo = new DefultRepository\<t\>(fsql, uowm);

using (var uow1 = uow.Begin())
{

using (var uow2 = uow.Begin())
{
repo.Insert(...);
uow2.Commit();
}
repo.Where(...).ToList(); //是否变化
uow1.Commit();
}

像这样整理一个 demo 传上来

**Comment by 2881099** [comment]
@yus1977 这样测试可以吗？

**Comment by yus1977** [comment]
OK，我找时间测试一下

**Comment by yus1977** [comment]
> @yus1977 这样测试可以吗？

 OK，我找时间测试一下

**Comment by yus1977** [comment]
经过测试，上面的代码没有问题，UnitOfWorkManager本身也没有问题。
是我这边问题，写的AOP有BUG。
我用的是Autufac，所以照着前面的TransactionalAttribute 重新写了AOP，TransactionInterceptor。
我的事务特性都是应用在Service对象上，当同一个对象多个标记了事务的方法嵌套时，抄过来的代码就会出问题
原因如下：
因为一个Servier实例通过AOP编织后，绑定的TransactionInterceptor是同一个实例。
如下面的代码中
`c#
IUnitOfWork _uow;
........
Task OnBefore(UnitOfWorkManager uowm)
    {
        _uow = uowm.Begin(this.Propagation, this.IsolationLevel);
        return Task.FromResult(false);
    }
`
同一个实例多次启用事务后，_uow会被后面启用的事务覆盖。
而第二次以后启动的事务创建的的工作单元是UnitOfWorkVirtual。
因此不能简单的使用变量来存储创建的IUnitOfWork
可以使用栈来存储启动事务时创建的IUnitOfWork，比如：
`c#
Stack<IUnitOfWork> _unitOfWorks = new Stack<IUnitOfWork>(10);
.........

        private void BeginTransaction(MethodInfo methodInfo)
        {
            TransactionAttribute attribute = methodInfo.GetCustomAttribute<TransactionAttribute>();
            //启动事务
            var unitOfWork = _uowManager.Begin(attribute.Propagation, attribute.IsolationLevel);
            //把创建的事务工作单元压入栈中
            _unitOfWorks.Push(unitOfWork);

            WriteConsole(0);
        }
`

**Comment by yus1977** [comment]
下面是完整的代码
AOP使用是的是 Autofac +Castle.DynamicProxy + Castle.Core.AsyncInterceptor
`c#
   /// <summary>
    /// 事务拦截器TranAOP, 支持同步和异步方法
    /// </summary>
    public class TransactionInterceptor : AsyncInterceptorBase,IDisposable
    {
        public TransactionInterceptor(UnitOfWorkManager uowManager, IConfiguration configuration)
        {
            _uowManager = uowManager;

            this.configuration = configuration;
            transactionMonitor = configuration["ContextAutoSetup:TransactionMonitor"].ToBool();
        }

        private readonly UnitOfWorkManager _uowManager;
        private readonly IConfiguration configuration;

        bool transactionMonitor = false;
        Stack<IUnitOfWork> _unitOfWorks = new Stack<IUnitOfWork>(10);

        /// <summary>
        /// 开始事务
        /// </summary>
        /// <param name="methodInfo"></param>
        private void BeginTransaction(MethodInfo methodInfo)
        {
            TransactionAttribute attribute = methodInfo.GetCustomAttribute<TransactionAttribute>();
            //启动事务
            var unitOfWork = _uowManager.Begin(attribute.Propagation, attribute.IsolationLevel);
            //把创建的事务工作单元压入栈中
            _unitOfWorks.Push(unitOfWork);

            WriteConsole(0);
        }

        /// <summary>
        /// //提交事务
        /// </summary>
        private void CommitTransaction()
        {
            var unitOfWork = _unitOfWorks.Peek();
            if (unitOfWork != null)
                unitOfWork.Commit();

            WriteConsole(1);
        }

        /// <summary>
        /// 回滚事务
        /// </summary>
        private void RollbackTransaction()
        {
            var unitOfWork = _unitOfWorks.Peek();
            if (unitOfWork != null)
                unitOfWork.Rollback();

            WriteConsole(2);
        }

        /// <summary>
        /// 结束事务
        /// </summary>
        private void EndTransaction()
        {
            //出栈
            var unitOfWork = _unitOfWorks.Pop();
            if(unitOfWork!=null)
                unitOfWork.Dispose();
        }

        /// <summary>
        /// 无返回值的 异步/同步 方法拦截
        /// </summary>
        /// <param name="invocation"></param>
        /// <param name="proceed"></param>
        /// <returns></returns>
        protected override async Task InterceptAsync(IInvocation invocation, Func<IInvocation, Task> proceed)
        {
            var methodInfo = invocation.MethodInvocationTarget ?? invocation.Method;
            //对当前方法的特性验证
            if (methodInfo.HasAttribute<TransactionAttribute>())
            {
                try
                {
                    BeginTransaction(methodInfo);

                    await proceed(invocation).ConfigureAwait(false);

                    CommitTransaction();
                }
                catch (Exception ex)
                {
                    RollbackTransaction();
                    throw ex;
                }
                finally
                {
                    EndTransaction();
                }
            }
            else
                await proceed(invocation).ConfigureAwait(false);
        }

        protected override async Task<TResult> InterceptAsync<TResult>(IInvocation invocation, Func<IInvocation, Task<TResult>> proceed)
        {
            var methodInfo = invocation.MethodInvocationTarget ?? invocation.Method;
            //对当前方法的特性验证
            if (methodInfo.HasAttribute<TransactionAttribute>())
            {
                try
                {
                    BeginTransaction(methodInfo);

                    var result = await proceed(invocation).ConfigureAwait(false);

                    CommitTransaction();

                    return result;
                }
                catch (Exception ex)
                {
                    RollbackTransaction();
                    throw ex;
                }
                finally
                {
                    EndTransaction();
                }
            }
            else
                return await proceed(invocation).ConfigureAwait(false);
        }

        /// <summary>
        /// 控制台输出信息
        /// </summary>
        /// <param name="msg"></param>
        /// <param name="type">0开始事务，1提交事务，2回滚事务</param>
        private void WriteConsole(int type)
        {
            if (transactionMonitor)
            {
                string msg = "";
                switch (type)
                {
                    case 0:
                        msg = $"***Transaction Begin***\n";
                        break;
                    case 1:
                        msg = $"***Transactio Commit***\n";
                        break;
                    case 2:
                        msg = $"***Transaction* Rollback**\n";
                        break;
                }

                ConsoleHelper.WriteSuccessLine(msg);
            }
        }

        public void Dispose()
        {
            if (_unitOfWorks != null)
                _unitOfWorks.Clear();
        }
    }
}

`

**Comment by 2881099** [comment]
# IdleBus<IFreeSql> + UnitOfWorkManager

默认 UnitOfWorkManager 只能绑定一个 FreeSql 使用，所以 Scoped 生命范围内不切换的情况下，可以实现 IdleBus + UnitOfWorkManager 以来实现。

第一步：定义 IdleBus 扩展方法

```c#
public static class IdleBusExtesions
{
    static AsyncLocal<string> AsyncLocalTenantId = new AsyncLocal<string>();
    public static IdleBus<IFreeSql> ChangeTenant(this IdleBus<IFreeSql> ib, string tenantId)
    {
        AsyncLocalTenantId.Value = tenantId;
        return ib;
    }
    public static IFreeSql Get(this IdleBus<IFreeSql> ib) => ib.Get(AsyncLocalTenantId.Value ?? "default");
    public static IBaseRepository<T> GetRepository<T>(this IdleBus<IFreeSql> ib) where T : class => ib.Get().GetRepository<T>();
}
```

第二步：定义 IFreeSql 代理类实现

```c#
class FreeSqlProxy : IFreeSql
{
    readonly IFreeSql _orm;

    public FreeSqlProxy(IFreeSql fsql)
    {
        _orm = fsql;
    }

    public IAdo Ado => _orm.Ado;
    public IAop Aop => _orm.Aop;
    public ICodeFirst CodeFirst => _orm.CodeFirst;
    public IDbFirst DbFirst => _orm.DbFirst;
    public GlobalFilter GlobalFilter => _orm.GlobalFilter;
    //关键在此处，释放无任何操作
    public void Dispose() { }

    public void Transaction(Action handler) => _orm.Transaction(handler);
    public void Transaction(IsolationLevel isolationLevel, Action handler) => _orm.Transaction(isolationLevel, handler);

    public ISelect<T1> Select<T1>() where T1 : class
    {
        return _orm.Select<T1>();
    }
    public ISelect<T1> Select<T1>(object dywhere) where T1 : class => Select<T1>().WhereDynamic(dywhere);

    public IDelete<T1> Delete<T1>() where T1 : class
    {
        return _orm.Delete<T1>();
    }
    public IDelete<T1> Delete<T1>(object dywhere) where T1 : class => Delete<T1>().WhereDynamic(dywhere);

    public IUpdate<T1> Update<T1>() where T1 : class
    {
        return _orm.Update<T1>();
    }
    public IUpdate<T1> Update<T1>(object dywhere) where T1 : class => Update<T1>().WhereDynamic(dywhere);

    public IInsert<T1> Insert<T1>() where T1 : class
    {
        return _orm.Insert<T1>();
    }
    public IInsert<T1> Insert<T1>(T1 source) where T1 : class => Insert<T1>().AppendData(source);
    public IInsert<T1> Insert<T1>(T1[] source) where T1 : class => Insert<T1>().AppendData(source);
    public IInsert<T1> Insert<T1>(List<T1> source) where T1 : class => Insert<T1>().AppendData(source);
    public IInsert<T1> Insert<T1>(IEnumerable<T1> source) where T1 : class => Insert<T1>().AppendData(source);

    public IInsertOrUpdate<T1> InsertOrUpdate<T1>() where T1 : class
    {
        return _orm.InsertOrUpdate<T1>();
    }
}
```

第三步：改造 Startup.cs 注入

```c#
public static IdleBus<IFreeSql> ib = new IdleBus<IFreeSql>();

public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();

    //ib.Register(..);
    //注意此时注入 AddScoped IFreeSql
    services.AddScoped<IFreeSql>(serviceProvider => new FreeSqlProxy(ib.Get()));
    services.AddScoped<UnitOfWorkManager>();
    services.AddFreeRepository(null, typeof(Startup).Assembly);
}

第四步：使用方法请参照 一楼

**Comment by km93522719** [comment]
.net 6.0，按照上面的式例，在方法添加Transactional特性，但是没有生效，不是进入事务里，这个是什么原因引起吗？
Service相关代码：
        [Transactional]
        private async Task SaveFlowInfoAsync(FlowInfoAddInput flowInfoInput, CancellationToken cancellationToken)
        {
            //using IUnitOfWork unitOfWork = _unitOfWorkManager.Begin(isolationLevel: IsolationLevel.Snapshot);
            //try
            //{
            await this._flowDetailService.AddAsync(flowInfoInput, cancellationToken); 

            //其他业务逻辑
            。。。
           
            //    unitOfWork.Commit();
            //}
            //catch (Exception e)
            //{
            //    unitOfWork.Rollback();
            //    LogUtils.LogErr(this, $"流程提交异常:{e.Message}。PARAMS:{flowInfoInput.FlowSubmitInput.ToJson()}", e);
            //    throw new CustomException(ExceptionConst.FlowSubmitFail);
            //}
        }
