### ISSUE TITLE
命令参数化的问题

### ISSUE THREAD

**Issue by yus1977** [dotnetcore/FreeSql#290]
我在做更新指定列时发现一个问题。
下面的代码，生成的SQL没有实现命令参数化。
`
            fsql.Update<Post>()
                .Set(a => new Post { Subject = "New Subject", DateAdded = DateTime.Now })
                .Where(a => a.Id == 12)
                .ExecuteAffrows();
`
其它的几种写法，都可以正常的实现命令参数化。
比如：
`
                fsql.Update<Post>()
                    .SetSource(new Post { Id = 12, Subject = "New Subject", DateAdded = DateTime.Now })
                    .UpdateColumns(a=>new { a.Subject,a.DateAdded})
                    .ExecuteAffrows();
          
               //或
                fsql.Update<Post>()
                                .SetDto(new {Subject = "New Subject", DateAdded = DateTime.Now })
                                .Where(a => a.Id == 12)
                                .ExecuteAffrows();*/
                //或
                fsql.Update<Post>()
                                .Set(a=> a.Subject,newSubJect)
                                .Set(a=> a.DateAdded,newDate)
                                .Where(a => a.Id == 12)
                                .ExecuteAffrows();*/
`

**Comment by 2881099** [comment]
Set(a => new Post { Subject = "New Subject", DateAdded = DateTime.Now })

这种走表达式解析逻辑，默认没有参数化

这个无所谓，我们的 NoneParameter 比参数化做得更好

**Comment by yus1977** [comment]
明白。
命令参数化，主要是用来防止SQL 注入
NoneParameter   可以有效的防止SQL注入吗

**Comment by 2881099** [comment]
可以的，防注入是基本操作

**Comment by yus1977** [comment]
好的，多谢！
