### ISSUE TITLE
选择字段返回能否实现a.*

### ISSUE THREAD

**Issue by zerone1990** [dotnetcore/FreeSql#293]
如题，sql语句比如这样
select a.*, b.desc from user a left join verify b on a.id = b.id;
那么用freesql的FirstAsync((a, b) = new {a, b.desc})没法组合出上面sql要的效果，请问怎么实现？
另外没有QQ群吗？

**Comment by 2881099** [comment]
FirstAsync((a, b) = new {a, b.desc})

得到的效果是 a.*,b.desc，你说的得不到效果是什么意思？

qq群 4336577

**Comment by zerone1990** [comment]
这样返回的对象，是{a, b.desc},  如果json出来是有二级结构的
而select a.*, b.desc会把a.*的所有字段和b.desc放在一级结构中

**Comment by 2881099** [comment]
先查询出来，再组装结构。活着看看 DTO 映射查询的文档：https://github.com/2881099/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%95%b0%e6%8d%ae
