### ISSUE TITLE
System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#294]
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=26; handshake=99; [Login] initialization=1; authentication=8; [Post-Login] complete=14012; 

如果在 linux 下连接 Sqlserver 请保证版本在 sqlserver 2012+，否则将出现上面的错误。这是 System.Data.SqlClient 的错误：https://github.com/dotnet/SqlClient/issues/126

![image](https://user-images.githubusercontent.com/16286519/80506408-1cdd5600-89a8-11ea-96eb-15ee91c5b0d6.png)

**Comment by pjy612** [comment]
这就尴尬了...公司用的是 SQL2008 ...还好我这边用的 NetCore2.2 还没升级到 3.x ...
