### ISSUE TITLE
ISelect<T1,T2,...> 能否降维

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#295]
现在低纬的ISelect<T1> 可以通过From<T2> 升维为 ISelect<T1,T2>
那是否可以反其道而行之，再将ISelect<T1,T2> 降回 ISelect<T1>

主要用于解决：
List查询 和 Count查询 的时候 where条件一致，想要复用代码，但是根据不同的查询条件，需要join 操作，
因此处理完where后 的 ISelect<t1> 可能  变成 不确定的ISelect<T1,T2,...>， 这就导致封装成方法时返回类型不好确定，虽然还是有解决方案的，比如返回类型改为 `Tuple<ISelect<T1>, ISelect<T1,T2>, ...>`，但如果有更漂亮的自由切换维度的方法的话，那灵活性将大大提升，就算单独作为一款Sql Builder，也非常好用了吧。

**Comment by 2881099** [comment]
能不能这样理解：

```csharp
var seln = fsql.Select<T1, T2>().ToSql((a,b) => a, FieldAliasOptions.AsProperty);
var sel1 = fsql.Select<T1>().WithSql(seln).Page(1,2).ToList();
```

**Comment by tky753** [comment]
办法总比困难多🎉
