### ISSUE TITLE
第一个issue我霸占了

### ISSUE THREAD

**Issue by caslt** [dotnetcore/FreeSql#3]
祝FreeSql发展壮大

我提几个建议

1. 提供RoadMap
2. 在#1的基础上，确定什么待完成
3. 在#1和#2的基础上，提供完善的（或者说起码基本的）测试案例
4. 在#1、#2和#3的基础上，完善每天的build

有了这几个东西，我觉得这个项目成功与否不敢说，但是用起来肯定会安心很多，会明白局限在哪里，适用场景在哪里，然后其他人合作起来也会目标明确。

**Comment by 2881099** [comment]
版本更新日志：https://github.com/2881099/FreeSql/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97
