### ISSUE TITLE
请教关于 Sum 集合导航属性里面属性的问题

### ISSUE THREAD

**Issue by parchon** [dotnetcore/FreeSql#300]
翻了两天的文档找不到相关的解决方法，所以请教一下：
两个表 `Order`（订单表） 和 `Detail`（明细表），`Order` 下面有集合属性 `DetailList`
我想统计 `Order.DetailList` 下面的 `Amount`这个属性值，比如是这样写吗：
```
freeSql.Select<Order>().Sum(a => a.DetailList.Sum(d => d.Amount))
freeSql.Select<Order>().IncludeMany(a => a.DetailList).Sum(a => a.DetailList.Sum(d => d.Amount))
```
会报错：
`“Order.DetailList 导航属性集合忘了 .AsSelect() 吗？如果在 ToList(a => a.DetailList) 中使用，请移步参考 IncludeMany 文档。”`

请问一下需要怎么写才能达到目的？
这里不能用 `freeSql.Select<Detail>().Sum(a => a.Amount)` 来统计的，一定是要以 `Order` 这个为基表来统计，因为前面有很多其它筛选条件

**Comment by parchon** [comment]
小弟不材，研究了很久，没有研究出来，但查询了文档，和 Issue 没有人提这个问题，估计是我能力没到位，但使用 EF Core 是很容易写出来的。所以请教一下各位大神

**Comment by 2881099** [comment]
```csharp
freeSql.Select<Order>()
.Sum(a => a.DetailList.AsSelect().Sum(d => d.Amount))
```

错误提示是要这样使用。

其实如果统计 Detail 直接查会不会更加好理解一点

```csharp
freeSql.Select<Detail>().Where(d => d.Order.Time == DateTime.Taday).Sum(d => d.Amount)
```

**Comment by 2881099** [comment]
因为我们不是基于 IQueryable 做的查询对象，所以集合属性在表达式中使用需要用 AsSelect() 转换为 ISelect。

IQueryable 因为方法侵入严重，所以自主创建的 ISelect。

**Comment by 2881099** [comment]
@parchon 严重怀疑 efcore 是先 ToList() 后在内存 Sum 的

建议直接查 Detail 表，或者查 Order 表 Inner Join Detail：

```csharp
freeSql.Select<Order, Detail>()
.InnerJoin((a,b) => a.Id == b.OrderId)
.Where((a,b) => a.Time = DateTime.Today)
.Sum((a,b) => b.Amount);
```

**Comment by parchon** [comment]
非常感谢作者的回复。
直接使用 Detail 表来查询统计肯定可以，但是目前我这里的具体业务实现不允许这样操作

使用
`freeSql.Select<Order>().Sum(a => a.DetailList.Sum(d => d.Amount))`
可以去到生成 SQL 这一步了，生成的 SQL 是长这样子的：
```
SELECT sum((SELECT TOP 1 sum(tb_2.[Amount]) 
	FROM [Detail] tb_2 
	WHERE (tb_2.[OrderID] = a.[OrderID]))) as1 
FROM [Order] a
```
会报 `不能对包含聚合或子查询的表达式执行聚合函数。` 的错误，我使用的 SQL Server 2012。

EF Core 不是在内存里操作的，是生成 SQL 获取数据。

**Comment by 2881099** [comment]
```csharp
freeSql.Select<Order>() 
.ToList(a => a.DetailList.AsSelect().Sum(d => d.Amount))
.Sum();
```

试试这样

**Comment by parchon** [comment]
> ```cs
> freeSql.Select<Order>() 
> .ToList(a => a.DetailList.AsSelect().Sum(d => d.Amount))
> .Sum();
> ```
> 
> 试试这样

这样是会读取数据生成列表然后再内存里 Sum，是可以的，但数据量比较大。

使用上面你提到的内联接可以实现了，我使用的是 Repository：
`model.Orm.Select<Order, Detail>().LeftJoin<Detail>((o, e) => o.OrderID == e.OrderID).Sum((o, e) => e.Amount);`
我再研究一下使用反射做成通用的方式来使用，感谢。

**Comment by 2881099** [comment]
```csharp
repo.Select.From<Detail>((s, e) => s)
.InnerJoin<Detail>((o, e) => o.OrderID == e.OrderID)
.Sum((o, e) => e.Amount);
```

仓储可以用 Orm 属性，也可以这样

**Comment by parchon** [comment]
> ```cs
> repo.Select.From<Detail>((s, e) => s)
> .InnerJoin<Detail>((o, e) => o.OrderID == e.OrderID)
> .Sum((o, e) => e.Amount);
> ```
> 
> 仓储可以用 Orm 属性，也可以这样

收到，感谢提醒。FreeSql 很强大了，我是从 EF Core 转 FreeSql 的。非常感谢

**Comment by parchon** [comment]
顺便吐嘈一下 EF Core，使用 EF Core 项目首次运行要20秒，改成 FreeSQL 后5秒。

**Comment by 2881099** [comment]
有空把那个 UnitOfWorkManager 接入使用，issues 里面的

**Comment by parchon** [comment]
好的，谢谢。
现在项目刚使用 FreeSql 改造完，目前使用 UnitOfWork 处理事务，UnitOfWorkManager 还需要花点时间研究一下作用。
