### ISSUE TITLE
参数化执行和bulkCopy的问题

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/FreeSql#301]
现在项目全部用freesql了。。。谢谢大佬的神器。。有个问题
实测 30字段15000条数据，sqlite3 ,
 用fsql.Insert(ps).ExecuteAffrows(); 需要30s
但是如果fsql.Insert(ps).NoneParameter().ExecuteAffrows(); 需要1.3s
这是不是意味着以后凡是插入都该带上.NoneParameter()？

还有bulkcopy功能好强啊，能不能用在sqlite和mysql上

**Comment by 2881099** [comment]
sqlite 不用参数化是快很多。我们的 NoneParameter 支持所有类型。mysql sqlserver pgsql 这三个实现了 bulk 文档有说，wiki 有性能测试的参考结果 https://github.com/2881099/FreeSql/wiki/%e6%80%a7%e8%83%bd

**Comment by yangbocheng** [comment]
谢谢回答 
还有，在wiki-添加-批量添加-Bulk Copy   这栏中表示bulk功能目前只包含pgsql sqlserver, 需要您更新下文档

**Comment by 2881099** [comment]
> 谢谢回答
> 还有，在wiki-添加-批量添加-Bulk Copy 这栏中表示bulk功能目前只包含pgsql sqlserver, 需要您更新下文档

已更新
