### ISSUE TITLE
不支持mongodb啊，能加上吗？

### ISSUE THREAD

**Issue by gxlqssjf** [dotnetcore/FreeSql#308]
如题

**Comment by 2881099** [comment]
主要面向关系应数据库做的，mongodb做不了。你的另一个 mysql DbFirst 问题解决了吗

**Comment by gxlqssjf** [comment]
解决了，是关联的数据库的问题，但是你的提示不够明显哪里缺少字段id，主要是面向关系数据库，应该想办法扩展到Nosql,未来肯定是二者共存，随着数据量的增多，MongoDB，Hbase,CouchDB等这些比较多，应该加上支持这个才对

**Comment by gxlqssjf** [comment]
还有应该扩展一个DbColumnInfo 属性csType转成C#Type的别名的扩展方法，如System.Int64转化成long,如果是Varchar(36)应该加上Guid的支持

**Comment by 2881099** [comment]
看看这个方法 fsql.DbFirst.GetCsType(DbColumnInfo)

**Comment by gxlqssjf** [comment]
看过了
