### ISSUE TITLE
FreeSql.Repository 会开源吗？

### ISSUE THREAD

**Issue by MetSystem** [dotnetcore/FreeSql#31]
FreeSql.Repository 会开源吗？

**Comment by 2881099** [comment]
是开源的呢，FreeSql.Repository 这个包之前有实现部分。

然后又推出了 FreeSql.DbContext 包，我们在这个包内又重新现实了 仓储。

所以现 FreeSql.Repository 没有代码，直接引用了 FreeSql.DbContext 包。

https://github.com/2881099/FreeSql.DbContext

**Comment by MetSystem** [comment]
OK
