### ISSUE TITLE
Update时能否支持Math.Max

### ISSUE THREAD

**Issue by yifanc62** [dotnetcore/FreeSql#313]
目前有MySql使用场景为类似 UPDATE table SET a=GREATEST(a, ?value1), b=GREATEST(b, ?value2)，目前不可以使用.Set(t => new Table { A = Math.Max(t.A, value1), B = Math.Max(t.B, value2) })这种方法。
另外还有更复杂的，INSERT INTO table(a,b,c) VALUES (1,2,3),(4,5,6) ON DUPLICATE KEY UPDATE a=GREATEST(a, VALUES(a)), ...
想请教下上边这两种除了执行RawSql以外是否还有其他方法。

**Comment by 2881099** [comment]
1、Math.Max 表达式解析是可以的

2、GREATEST 可以用自定义表达式解析

```csharp
[ExpressionCall]
public static class DbFunc {
    static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

    public static int GREATEST(this string that, int value)
    {
        var up = context.Value;
        if (up.DataType == FreeSql.DataType.MySql) //重写内容
          up.Result = $"GREATEST({up.ParsedContent["that"]}, {up.ParsedContent["value"]})";
        return that;
    }
}

fsql.Update<Table>().Where(...)
    .Set(a => DbFunc.GREATEST(a.fielda, value1))
    .Set(a => DbFunc.GREATEST(a.fieldb, value2))
```

自定义表达式解析文档：https://github.com/dotnetcore/FreeSql/wiki/%E8%A1%A8%E8%BE%BE%E5%BC%8F%E5%87%BD%E6%95%B0#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%A3%E6%9E%90

3、ON DUPLICATE KEY UPDATE 这个可以用我们提供的扩展方法：https://github.com/dotnetcore/FreeSql/wiki/%E6%B7%BB%E5%8A%A0%E6%88%96%E4%BF%AE%E6%94%B9
