### ISSUE TITLE
分页bug

### ISSUE THREAD

**Issue by zgmqdl** [dotnetcore/FreeSql#314]
SELECT a.[Id], a.[Name]
FROM [Journal] a
WHERE (a.[Status] = 1 AND a.[Status] <> -2)
ORDER BY a.[UpdateTime] DESC
OFFSET 40 ROW
FETCH NEXT 40 ROW ONLY

SELECT TOP 40 a.[Id], a.[Name]
FROM [Journal] a
WHERE (a.[Status] = 1 AND a.[Status] <> -2)
ORDER BY a.[UpdateTime] DESC
这是查询第一页和第二页的时候的sql语句，查询出来的数据是完全一致的
 result.data = await _freeSql.Select<Journal> ().Where (j => j
                        .Status == request.Status && j.Status != (int) JudgeEnum.Delete).Count (out var total)
                    .Page (request
                        .PageIndex, request.PageSize).OrderByDescending (a => a.UpdateTime)
                    .ToListAsync ();
                result.TotalCount = (int) total;
这是我的查询语句，数据库是SQL Server2014

**Comment by 2881099** [comment]
因为 update time 值一样？前面很多条时间一样的话没法排序，orderby 除了时间，再加个主键看看。

问题在外部已解决
