### ISSUE TITLE
多数据库操作如何自有切换当前操作库，又保证事务。

### ISSUE THREAD

**Issue by haoljp** [dotnetcore/FreeSql#315]
如题。当前配置大致如下
{
  "DbOptions": [
    {
      "Key": "Sys",
      "ConStr": "DbType=MySQL;Host=127.0.0.1;Port=3306;DataBase=jpfz_cms;UserName=root;Password=123"
    },
    {
      "Key": "Edx",
      "ConStr": "DbType=Oracle;Host=192.168.103.105;Port=1521;DataBase=Orcl;UserName=gdbase;Password=123"
    },
    {
      "Key": "Eip",
      "ConStr": "DbType=SQLite;DataBase=admindb.db;Password=123"
    }
  ]
}
配置中Key用作选择当前需要操作的数据库。
如果某个业务方法可能会对多个数据库都会操作，使用Repository不知如何操作。

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/44

这个看过没有

**Comment by haoljp** [comment]
谢谢，是这个意思。
