### ISSUE TITLE
[建议]不用Repository   实现添加或更新

### ISSUE THREAD

**Issue by liaozb** [dotnetcore/FreeSql#316]

**Comment by 2881099** [comment]
IFreeSql 定义了 InsertOrUpdate 方法实现添加或修改的功能，利用数据库特性：

| Database | Features |
| -- | -- |
| MySql | on duplicate key update |
| PostgreSQL | on conflict do update |
| SqlServer | merge into |
| Oracle | merge into |
| Sqlite | replace into |
| Dameng | merge into |

注意：FreeSql.Repository 通用仓储也有 InsertOrUpdate 方法，它们的机制不一样。

```csharp
fsql.InsertOrUpdate<T>()
  .SetSource(items) //需要操作的数据
  .ExecuteAffrows();
```

**Comment by YanmaY** [comment]
这个方法1.5.0上新加的吧？我看1.4.0上还木有

**Comment by 2881099** [comment]
> 这个方法1.5.0上新加的吧？我看1.4.0上还木有

是的，1.5 的功能，现在可以下载 1.5.0-preview0521
