### ISSUE TITLE
对于视图、存储过程、自定义方法等的更新 有没有推荐的解决方案

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#319]
我的情况是，其实本来数据数据库是另一个系统维护的，但一方面更新频繁，另一方面纯人工更新可靠性低下，还需要和另一个系统的程序更新同步，还同时需要更新好几家客户，几乎每次一改数据库都是一次灾难
经过协商，最终决定把部分和我的系统密切相关的部分数据库更新 转移到我的程序里，每次网站启动时自主判断有新的更新就执行更新sql
我知道，这严格来说不是ORM框架的责任，但想要听听建议，大神看看用 [fluentmigrator](https://github.com/fluentmigrator/fluentmigrator)是否能行。

**Comment by 2881099** [comment]
看了一下很强大，因为改结构还会涉及到数据，不知道用他好不好处理。

改动量不大的话，用sql维护可能更好一点，可以兼顾旧数据和新结构。

回滚版本可能基本用不上。

**Comment by tky753** [comment]
其实就打算内嵌sql文件，在Up()方法里直接执行sql文件的，这样应该可以，谢谢回复
