### ISSUE TITLE
oracle插入,提示ORA-00972: 标识符过长,这个错误

### ISSUE THREAD

**Issue by jetydu** [dotnetcore/FreeSql#32]
![image](https://user-images.githubusercontent.com/25604796/56122612-63cafa00-5fa5-11e9-8c1a-652472dce5bc.png)
实体
 [Column(DbType = "varchar2(1500)")]  这个地方用nvarchar(1500)是正常的
        public string srvReqstCntt { get; set; }       
        public string acptTime { get; set; }
        public string acptStaffDeptId { get; set; }   

json转为实体,json原型如下:
ing parse JS eval
[
{
"acptNumBelgCityName":"泰州",
"concPrsnName":"常**",
"srvReqstTypeName":"家庭业务→网络质量→家庭宽带→自有宽带→功能使用→游戏过程中频繁掉线→全局流转",
"srvReqstCntt":"客户来电表示宽带使用（ 所有）出现（频繁掉线不稳定） ，客户所在地址为（安装地址泰州地区靖江靖城街道工农路科技小区科技3区176号2栋2单元502），联系方式（具体联系方式），烦请协调处理。",
"acptTime":"2019-04-15 15:17:05",
"acptStaffDeptId":"0003002101010001000600020023"
},
{
"acptNumBelgCityName":"苏州",
"concPrsnName":"龚**",
"srvReqstTypeName":"移动业务→基础服务→账/详单→全局流转→功能使用→账/详单信息不准确→全局流转",
"srvReqstCntt":"用户参与 2018年苏州任我用关怀活动 送的分钟数500分钟，说自己只使用了116分钟，但是我处查询到本月已经使用了306分钟\r\n，烦请处理",
"acptTime":"2019-04-15 15:12:05",
"acptStaffDeptId":"0003002101010001000600020023"
}
]

**Comment by 2881099** [comment]
我测试一下，谢谢反馈

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/56124725-ddfd7d80-5fa9-11e9-9b92-ec9f00950551.png)

大哥看看我的测试，没有报错，使用的 varchar2(1500)

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/56124789-05ece100-5faa-11e9-97e2-b65f834f2382.png)

这是插入后的数据

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/56125323-384b0e00-5fab-11e9-8666-6cfedd080f46.png)

然后我用 nvarchar2(1500) 测试也是 ok 的

**Comment by 2881099** [comment]
ORA-00972: 标识符过长,这个错误，可能是 codefirst 自动迁移时，创建临时表的某标识过长，oracle 的标识长度有限制

**Comment by jetydu** [comment]
咱们这个项目有没有微信或者qq群，发现问题可以及时沟通！

**Comment by jetydu** [comment]
奇怪，我的varchar2（1500）为什么就插入不进去呢
！

**Comment by jetydu** [comment]
奇怪，我又改成varchar2，又测试了下，也正常了

**Comment by 2881099** [comment]
qq群 4336577

**Comment by caslt** [comment]
检查一下你的数据库的charset，这个数据类型和charset有密切关系
