### ISSUE TITLE
IFreeSql 事务另类玩法

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#322]
我们都知道 IFreeSql 以单例注入使用，所以直接使用 IFreeSql curd 做事务。

要么：

```csharp
fsql.Transaction(() => { ... }); //同线程事务，不能异步
```

要么：

```csharp
fsql.Insert(xxx).WithTransaction(tran).ExecuteAffrows(); //每次传递显麻烦
```

除了这两种事务，还可以选择使用 FreeSql.DbContext、FreeSql.Repository + UnitOfWork 来做事务，他们不受异步限制、并且能减少显示传递事务的麻烦。

条件允许还可以使用 FreeSql.Repository + UnitOfWorkManager 完成更高阶的事务管理操作。

---

## 本文内容

另类事务，直接在 IFreeSql 上开刀：

> 项目中注入 ITransactionFreeSql，项目内也是使用 ITransactionFreeSql

```csharp
var orgFsql = new FreeSql.FreeSqlBuilder()
  .UseConnectionString(...)
  .Build();

services.AddScoped<ITransactionFreeSql>(() => new TransactionFreeSql(orgFsql));
//注意：Scoped 注入，而不是 Singleton
```

> 使用事务：

```csharp
fsql.Transaction(null); //重写了 orgFsql 的同线程事务

try
{
  await fsql.Insert(xx).ExecuteAffrowsAsync();
  //...
  fsql.Commit();
}
catch
{
  fsql.Rollback();
}
```

ITransactionFreeSql 的代码定义如下：（相信大多数人都看得懂）

```csharp
using FreeSql;
using FreeSql.Internal;
using FreeSql.Internal.ObjectPool;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;

namespace Your
{
    public interface ITransactionFreeSql : IFreeSql
    {
        void Commit();
        void Roolback();
    }
    class TransactionFreeSql : ITransactionFreeSql
    {
        IFreeSql _originalFsql;
        int _transactionCount;
        DbTransaction _transaction;
        Object<DbConnection> _connection;
        public TransactionFreeSql(IFreeSql fsql)
        {
            _originalFsql = fsql;
        }

        public IAdo Ado => _originalFsql.Ado;
        public IAop Aop => _originalFsql.Aop;
        public ICodeFirst CodeFirst => _originalFsql.CodeFirst;
        public IDbFirst DbFirst => _originalFsql.DbFirst;
        public GlobalFilter GlobalFilter => _originalFsql.GlobalFilter;

        public ISelect<T1> Select<T1>() where T1 : class =>
          _originalFsql.Select<T1>().WithTransaction(_transaction);
        public ISelect<T1> Select<T1>(object dywhere) where T1 : class => Select<T1>().WhereDynamic(dywhere);

        public IDelete<T1> Delete<T1>() where T1 : class =>
          _originalFsql.Delete<T1>().WithTransaction(_transaction);
        public IDelete<T1> Delete<T1>(object dywhere) where T1 : class => Delete<T1>().WhereDynamic(dywhere);

        public IUpdate<T1> Update<T1>() where T1 : class =>
          _originalFsql.Update<T1>().WithTransaction(_transaction);
        public IUpdate<T1> Update<T1>(object dywhere) where T1 : class => Update<T1>().WhereDynamic(dywhere);

        public IInsert<T1> Insert<T1>() where T1 : class =>
          _originalFsql.Insert<T1>().WithTransaction(_transaction);
        public IInsert<T1> Insert<T1>(T1 source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(T1[] source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(List<T1> source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(IEnumerable<T1> source) where T1 : class => Insert<T1>().AppendData(source);

        public IInsertOrUpdate<T1> InsertOrUpdate<T1>() where T1 : class =>
          _originalFsql.InsertOrUpdate<T1>().WithTransaction(_transaction);

        public void Dispose() => TransactionCommitPriv(true);
        public void Transaction(Action handler) => TransactionPriv(null, handler);
        public void Transaction(IsolationLevel isolationLevel, Action handler) => TransactionPriv(isolationLevel, handler);
        void TransactionPriv(IsolationLevel? isolationLevel, Action handler)
        {
            if (_transaction != null)
            {
                _transactionCount++;
                return; //事务已开启
            }
            try
            {
                _connection = _originalFsql.Ado.MasterPool.Get();
                _transaction = isolationLevel == null ? _connection.Value.BeginTransaction() : _connection.Value.BeginTransaction(isolationLevel.Value);
                _transactionCount = 0; //
            }
            catch
            {
                TransactionCommitPriv(false);
                throw;
            }
        }
        public void Commit() => TransactionCommitPriv(true);
        public void Roolback() => TransactionCommitPriv(false);
        void TransactionCommitPriv(bool iscommit)
        {
            if (_transaction == null) return;
            _transactionCount--;
            try
            {
                if (iscommit == false) _transaction.Rollback();
                else if (_transactionCount <= 0) _transaction.Commit();
            }
            finally
            {
                if (iscommit == false || _transactionCount <= 0)
                {
                    _originalFsql.Ado.MasterPool.Return(_connection);
                    _connection = null;
                    _transaction = null;
                }
            }
        }
    }
}
```

**Comment by liuyl1992** [comment]
为什么不集成这种方式的事务到frees起来源码呢

**Comment by zhouandke** [comment]
在导入excel里的多行记录时, 每一行数据的写入都需要 begin 和 commit/rollback, 以保证每行的写入不会受其他行影响.
在 void TransactionPriv(IsolationLevel? isolationLevel, Action handler) 方法中
`_connection = _originalFsql.Ado.MasterPool.Get();`
需要改成
`if(_connection == null ) _connection = _originalFsql.Ado.MasterPool.Get();`

否则, 在默认情况下, 100行数据就会 **耗尽 数据库连接**

**Comment by luoyunchong** [comment]
一行数据，用一个事务？你这是什么操作。

**Comment by zhouandke** [comment]
我这个excel 的一行有很多数据,, 实际上是要写入3张表
只起一个事务的话, 如果第1行成功, 第2行失败, 就会导致第1行数据也 rollback
所以我是每行都起一个事务, 第2行失败与否, 不会影响第1行

**Comment by 2881099** [comment]
@zhouandke 一楼代码已更新，多谢提醒

**Comment by luoyunchong** [comment]
## fsql 外部事务demo

### 通过fsql得到transaction 
```
            using Object<DbConnection> conn = _freeSql.Ado.MasterPool.Get();
            using DbTransaction transaction = await conn.Value.BeginTransactionAsync();
```

### 通过外部事务WithTransaction 指定事务
```
await fsql.Update<xxx>()
  .WithTransaction(指定事务)
  .Set(a => a.Clicks + 1)
  .ExecuteAffrowsAsync();
```

### 如下demo
```

        /// <summary>
        /// 批量插入
        /// </summary>
        /// <param name="inputDto"></param>
        /// <returns></returns>
        public async Task CreateAsync(CreateGroupDto inputDto)
        {
            bool exist = await _groupRepository.Select.AnyAsync(r => r.Name == inputDto.Name);
            if (exist)
            {
                throw new LinCmsException("分组已存在，不可创建同名分组", ErrorCode.RepeatField);
            }

            LinGroup linGroup = Mapper.Map<LinGroup>(inputDto);

            using Object<DbConnection> conn = _freeSql.Ado.MasterPool.Get();
            using DbTransaction transaction = await conn.Value.BeginTransactionAsync();
            try
            {
                long groupId = await _freeSql.Insert(linGroup).WithTransaction(transaction).ExecuteIdentityAsync();
                List<LinPermission> allPermissions = await _freeSql.Select<LinPermission>().WithTransaction(transaction).ToListAsync();
                List<LinGroupPermission> linPermissions = new List<LinGroupPermission>();
                inputDto.PermissionIds.ForEach(r =>
                {
                    LinPermission pdDto = allPermissions.FirstOrDefault(u => u.Id == r);
                    if (pdDto == null)
                    {
                        throw new LinCmsException($"不存在此权限:{r}", ErrorCode.NotFound);
                    }
                    linPermissions.Add(new LinGroupPermission(groupId, pdDto.Id));
                });

                await _freeSql.Insert<LinGroupPermission>()
                       .WithTransaction(transaction)
                       .AppendData(linPermissions)
                       .ExecuteAffrowsAsync();
                await transaction.CommitAsync();
            }
            catch
            {
                await transaction.RollbackAsync();
                throw;
            }
        }
```

**Comment by Weilence** [comment]
![image](https://user-images.githubusercontent.com/11787429/141716577-0107d9b7-52f5-429f-b13a-ecdec313e96a.png)
这里代码有问题，应该是1。
如果是0，将导致A事务包含B事务，在B事务commit后，会立即提交全局事务，从而导致错误的结果

**Comment by cnkker** [comment]
> ![image](https://user-images.githubusercontent.com/11787429/141716577-0107d9b7-52f5-429f-b13a-ecdec313e96a.png) 这里代码有问题，应该是1。 如果是0，将导致A事务包含B事务，在B事务commit后，会立即提交全局事务，从而导致错误的结果

你这是说的哪个有问题？

**Comment by cnkker** [comment]
> ![image](https://user-images.githubusercontent.com/11787429/141716577-0107d9b7-52f5-429f-b13a-ecdec313e96a.png) 这里代码有问题，应该是1。 如果是0，将导致A事务包含B事务，在B事务commit后，会立即提交全局事务，从而导致错误的结果

你这是说的哪个有问题？

**Comment by hajiuxbz** [comment]
> ## fsql 外部事务demo
> ### 通过fsql得到transaction
> ```
>   using Object<DbConnection> conn = _freeSql.Ado.MasterPool.Get();
>   using DbTransaction transaction = await conn.Value.BeginTransactionAsync();
> ```
> 
> ### 通过外部事务WithTransaction 指定事务
> ```
> await fsql.Update<xxx>()
>   .WithTransaction(指定事务)
>   .Set(a => a.Clicks + 1)
>   .ExecuteAffrowsAsync();
> ```
> 
> ### 如下demo
> ```
> 
>         /// <summary>
>         /// 批量插入
>         /// </summary>
>         /// <param name="inputDto"></param>
>         /// <returns></returns>
>         public async Task CreateAsync(CreateGroupDto inputDto)
>         {
>             bool exist = await _groupRepository.Select.AnyAsync(r => r.Name == inputDto.Name);
>             if (exist)
>             {
>                 throw new LinCmsException("分组已存在，不可创建同名分组", ErrorCode.RepeatField);
>             }
> 
>             LinGroup linGroup = Mapper.Map<LinGroup>(inputDto);
> 
>             using Object<DbConnection> conn = _freeSql.Ado.MasterPool.Get();
>             using DbTransaction transaction = await conn.Value.BeginTransactionAsync();
>             try
>             {
>                 long groupId = await _freeSql.Insert(linGroup).WithTransaction(transaction).ExecuteIdentityAsync();
>                 List<LinPermission> allPermissions = await _freeSql.Select<LinPermission>().WithTransaction(transaction).ToListAsync();
>                 List<LinGroupPermission> linPermissions = new List<LinGroupPermission>();
>                 inputDto.PermissionIds.ForEach(r =>
>                 {
>                     LinPermission pdDto = allPermissions.FirstOrDefault(u => u.Id == r);
>                     if (pdDto == null)
>                     {
>                         throw new LinCmsException($"不存在此权限:{r}", ErrorCode.NotFound);
>                     }
>                     linPermissions.Add(new LinGroupPermission(groupId, pdDto.Id));
>                 });
> 
>                 await _freeSql.Insert<LinGroupPermission>()
>                        .WithTransaction(transaction)
>                        .AppendData(linPermissions)
>                        .ExecuteAffrowsAsync();
>                 await transaction.CommitAsync();
>             }
>             catch
>             {
>                 await transaction.RollbackAsync();
>                 throw;
>             }
>         }
> ```

这个用完不需要归还连接吗 之前自己写的都归还啦

**Comment by luoyunchong** [comment]
加了using

**Comment by 2881099** [comment]
> > ![image](https://user-images.githubusercontent.com/11787429/141716577-0107d9b7-52f5-429f-b13a-ecdec313e96a.png) 这里代码有问题，应该是1。 如果是0，将导致A事务包含B事务，在B事务commit后，会立即提交全局事务，从而导致错误的结果
> 
> 你这是说的哪个有问题？

```c#
        void TransactionCommitPriv(bool iscommit)
        {
            _transactionCount--;
            if (_transactionCount > 0) return; //内层事务，跳过
```

**Comment by TinyMaD** [comment]
请问这种方式怎么与IBaseRepository 结合使用？创建BaseRepository后需要手工绑定工作单元，但这个TransactionFreeSql类没有UnitOfWork相关的数据，我尝试为TransactionFreeSql类写了一个获取UnitOfWork的属性，但貌似不能满足DbContext事务的使用方式，不知道该怎么写，或者有没有更好实现方式？
` public class UowOfFsql : IUnitOfWork
 {
     private readonly TransactionFreeSql _fsql;

     public UowOfFsql(TransactionFreeSql fsql)
     {
         _fsql = fsql;
     }

     public IFreeSql Orm => _fsql;

     public IsolationLevel? IsolationLevel { get; set; }

     public DbContext.EntityChangeReport EntityChangeReport { get; }

     public Dictionary<string, object> States { get; }

     public void Commit() => _fsql.Commit();

     public void Dispose()
     {
         
     }

     public DbTransaction GetOrBeginTransaction(bool isCreate = true)
     {
         return _fsql.Ado.TransactionCurrentThread;
     }

     public void Rollback() => _fsql.Rollback();
 }`
 `public class TransactionFreeSql : ITransactionFreeSql
{
    IFreeSql _originalFsql;
    int _transactionCount;
    DbTransaction _transaction;
    Object<DbConnection> _connection;

    public IUnitOfWork UnitOfWork => new UowOfFsql(this);
    }`

**Comment by 2881099** [comment]
@TinyMaD 
```c#

IFreeSql fsql = ...;

using (var trans = new TransactionFreeSql(fsql))
{
    var uow = new UowOfFsql(trans);
    var repo = fsql.GetRepository<T>();
    repo.UnitOfWork = uow;

    repo.Insert(...);

    trans.Commit();
}
```

**Comment by Weilence** [comment]
@2881099 有个typo，是`Rollback`不是`Roolback`
