### ISSUE TITLE
事务超时能否回滚

### ISSUE THREAD

**Issue by gwhzh21** [dotnetcore/FreeSql#323]
事务超时能否在程序里面回滚?
已经出现了好几次，因为当时有阻塞，最后这些事务被提交之后，结果多扣除了客户的余额，还有数据错乱的问题。

**Comment by 2881099** [comment]
发一下代码

**Comment by gwhzh21** [comment]
freeSql.Transaction(() =>
                {

                    var updatesql = @"UPDATE tb_Mall_IntegralOrderMaster 
                                            SET Status=@Status
                                               ,DDefine2=@DDefine2
                                               ,LastModifierUserId=@LastModifierUserId
                                               ,LastModifierUserName=@LastModifierUserName
                                               ,LastModificationTime=@LastModificationTime
                                            WHERE Id=@Id
";
                    var updatesql3 = @"UPDATE [tb_Mall_Goods] SET [IDefine3]=[IDefine3]+@IDefine3 WHERE [Id]=@Id
";

                    var updatesql4 = @$"UPDATE [tb_Mall_Member] SET [Integral]=[Integral]-@Integral WHERE Id=@Id
";
                    freeSql.Ado.ExecuteNonQuery(@"Insert Into [tb_Mall_Integral]
           ([Code]
           ,[UserId]
           ,[MemberId]
           ,[SourceType]
           ,[SourceId]
           ,[Amount]
           ,[RealAmount]
           ,[Remark]
           ,[CreatorUserId]
           ,[CreatorUserName]
           ,[CreationTime]
           ,[LastModifierUserId]
           ,[LastModifierUserName]
           ,[LastModificationTime]
           ,[IsDeleted]
           ,[DDefine1]
           ,[SDefine1]
           )
            values(
            @Code
           ,@UserId
           ,@MemberId
           ,@SourceType
           ,@SourceId
           ,@Amount
           ,@RealAmount
           ,@Remark
           ,@CreatorUserId
           ,@CreatorUserName
           ,@CreationTime
           ,@LastModifierUserId
           ,@LastModifierUserName
           ,@LastModificationTime
           ,0
           ,@DDefine1
           ,@SDefine1
            )", new MallIntegral()
                    {
                        Code = moneycode.Data,
                        Amount = payorder.TotalAmount * -1,
                        RealAmount = payorder.TotalAmount * -1,
                        CreationTime = DateTime.Now,
                        CreatorUserId = queryuserinfo.Id,
                        CreatorUserName = queryuserinfo.Name,
                        LastModificationTime = DateTime.Now,
                        LastModifierUserId = queryuserinfo.Id,
                        LastModifierUserName = queryuserinfo.Name,
                        Remark = "",
                        SDefine1 = "优品券",
                        MemberId = payorder.MemberId,
                        SourceType = "消费",
                        SourceId = payorder.Id,
                        UserId = queryuserinfo.Id,
                        DDefine1 = DateTime.Now
                    }
                                );

                    freeSql.Ado.ExecuteNonQuery(updatesql, new
                    {
                        DDefine2 = DateTime.Now,
                        Status = "待发货",
                        Id = payorder.Id,
                        LastModifierUserId = payorder.CreatorUserId,
                        LastModifierUserName = payorder.CreatorUserName,
                        LastModificationTime = DateTime.Now
                    });

                    foreach (var orderiteminfo in paydetails)
                    {
                        freeSql.Ado.ExecuteNonQuery(updatesql3,
                            new
                            {
                                IDefine3 = orderiteminfo.Qty,
                                Id = orderiteminfo.GoodsId
                            });
                    }

                    freeSql.Ado.ExecuteNonQuery(updatesql4,
                            new
                            {
                                Integral = payorder.TotalAmount,
                                Id = queryuserinfo?.SourceId ?? 0
                            });

                });

**Comment by 2881099** [comment]
被其他线程提交，是因为数据太多确实执行慢，还是死锁

**Comment by gwhzh21** [comment]
有死锁。有一个表的明细在更新的时候。又在查。因为具体出现的时候，客户没有反应。也不知道。只能从日志上面看到。

**Comment by 2881099** [comment]
好吧，我把那个自动提交超时的事务机制去掉

**Comment by 2881099** [comment]
fsql.Transaction 这个用法才有这个机制。其他工作单元没有。

**Comment by gwhzh21** [comment]
那我先换一个姿势用unitwork了。我觉得可能是一个参数，能控制就好。

**Comment by 2881099** [comment]
好的，刚好我准备发布 preview 版本，优化 IFreeSql.InsertOrUpdate 新的预览功能，顺便一起改掉这个机制

**Comment by 2881099** [comment]
线程事务新的定义方法，移除了 TimeSpan timeout 参数。

```csharp
/// <summary>
/// 开启事务（不支持异步）
/// </summary>
/// <param name="handler">事务体 () => {}</param>
void Transaction(Action handler);
/// <summary>
/// 开启事务（不支持异步）
/// </summary>
/// <param name="isolationLevel"></param>
/// <param name="handler">事务体 () => {}</param>
void Transaction(IsolationLevel isolationLevel, Action handler);
```
