### ISSUE TITLE
是否考虑支持人大金仓

### ISSUE THREAD

**Issue by tianxin8206** [dotnetcore/FreeSql#325]
.net下貌似还没有ORM工具支持人大金仓，是否考虑支持？

**Comment by 2881099** [comment]
我申请了试用版，没有回音。

达梦好多了，直接可以下载安装。

**Comment by maikebing** [comment]
人大金仓 就是 pgsql ， 使用npgsql 就行了

**Comment by 2881099** [comment]
测试了用 Npgsql 连不了，文档里有提到他们自己的一个 .dll，但是 nuget 搜索不到，也没看到去哪里下载。目前只有 Odbc 的连接资料。它确实是用 pgsql 源码改，pg_ 一些系统表查询不了。

System.FormatException:“Input string was not in a correct format.”

var conn = new Npgsql.NpgsqlConnection("Server=127.0.0.1;Port=54321;UID=USER2;PWD=123456789;database=TEST");
conn.Open();

**Comment by 2881099** [comment]
有个好消息是，我已经把 OdbcKingbaseES CodeFirst 模式走通了，所有类型的插入、查询正常。

**Comment by 2881099** [comment]
CodeFirst 和 DbFirst 两种模式都已测试通过。

**Comment by 2881099** [comment]
1.6.0-preview0101 已推送

**Comment by fayuanliu** [comment]
666
