### ISSUE TITLE
事务模式下，并行执行时有些任务数据没有提交到数据库

### ISSUE THREAD

**Issue by yus1977** [dotnetcore/FreeSql#327]
比如            
```c#
//创建发送Job
//根据接收者，并行创建发送Job
Parallel.ForEach(msg.Receivers, receiver=>
{
  //创建发送Job
  TB_MC_MsgSendJob sendJob = new TB_MC_MsgSendJob()
  {
    BatchId = batchID,
    MsgTypeKey = msg.MsgTypeKey,
    ReceiverName = receiver.ReceiverName,
    ReceiverNo = receiver.ReceiverNo,
    MsgContent = msg.MsgContent,
    State = (int)MsgSendJobState.WaitSend,
    CTime = DateTime.Now
  };
  //记录到数据
  var jobID = fsql.Insert<TB_MC_MsgSendJob>(sendJob).ExecuteIdentity();
});
```

**Comment by 2881099** [comment]
事务并行的想法行不通

**Comment by 2881099** [comment]
可以用最高级别的事务，批量插入，在返回自增id

**Comment by yus1977** [comment]
是的，事务和并行是有点不相容。



---原始邮件---
发件人: "2881099"<notifications@github.com&gt;
发送时间: 2020年5月27日(周三) 凌晨1:54
收件人: "dotnetcore/FreeSql"<FreeSql@noreply.github.com&gt;;
抄送: "yus"<yus1977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [dotnetcore/FreeSql] 事务模式下，并行执行时有些任务数据没有提交到数据库 (#327)




 
事务并行的想法行不通

**Comment by yus1977** [comment]
我的程序，任务从 mq中获取的，任务具体能容在数据库中，还要把结果同步会数据库。为了提高效率，就用到了并行方式



---原始邮件---
发件人: "2881099"<notifications@github.com&gt;
发送时间: 2020年5月27日(周三) 凌晨1:55
收件人: "dotnetcore/FreeSql"<FreeSql@noreply.github.com&gt;;
抄送: "yus"<yus1977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [dotnetcore/FreeSql] 事务模式下，并行执行时有些任务数据没有提交到数据库 (#327)




 
可以用最高级别的事务，批量插入，在返回自增id

**Comment by 2881099** [comment]
单连接并行行不通

**Comment by yus1977** [comment]
单连接，多个线程并发时，我还发现，使用Repository时也会出错：
System.ArgumentException:“An item with the same key has already been added. Key: Ynzp.MsgCenter.Domain.Entities.TB_MC_MsgSendJob”

代码如下:
```c#
...
IBaseRepository <TB_MC_MsgSendJob> msgJobRep;
...
...
msgJobRep.Get(jobID);
//或
msgJobRep.Find(jobID);
```

**Comment by yus1977** [comment]
如果这样写：
```c#
     fsql.Select<TB_MC_MsgSendJob>()
                .Where(a => a.Id == jobID)
                .First();
```

**Comment by 2881099** [comment]
是的，仓储是 Scoped 模式不能并发

**Comment by 2881099** [comment]
为啥是 Scoped 模式，因为 Repository 的核心状态数据不能一直存在，用完要销毁，不然内存会只增不减。

**Comment by 2881099** [comment]
Repository 可以不手工销毁，交给 GC

**Comment by yus1977** [comment]
明白，多谢。
Repository模式做CURD时，可以省写点代码 ^V^
