### ISSUE TITLE
有对应的代码生成工具吗，类似三层的那种，常用的操作BLL里生成

### ISSUE THREAD

**Issue by efreer1988** [dotnetcore/FreeSql#332]
有对应的代码生成工具吗，类似三层的那种，常用的操作BLL里生成？
entity  dal  blll

**Comment by 2881099** [comment]
1、实体类生成模板，有

2、DAL生成模板，没有（但是可以把它看成 FreeSql.Repository），我们有通用仓储功能实现，如下：

```c#
var dal = fsql.GetRepository<实体类型>();
dal.Insert(new ....);
dal.Update(实体);
dal.Select.Where(a => a.Id == 10).ToList();
//...
```

3、BLL生成模板，没有

**Comment by efreer1988** [comment]
> 1、实体类生成模板，有
> 
> 2、DAL生成模板，没有（但是可以把它看成 FreeSql.Repository），我们有通用仓储功能实现，如下：
> 
> ```cs
> var dal = fsql.GetRepository<实体类型>();
> dal.Insert(new ....);
> dal.Update(实体);
> dal.Select.Where(a => a.Id == 10).ToList();
> //...
> ```
> 
> 3、BLL生成模板，没有

那看来是因为freesql已经不需要dal层了，直接根据业务逻辑直接写BLL就够了吧

**Comment by 2881099** [comment]
可以这么理解
