### ISSUE TITLE
UseMonitorCommand 能否根据不同来源选择性地记录日志

### ISSUE THREAD

**Issue by tky753** [dotnetcore/FreeSql#334]
前段时间把` 审计日志模块`(用于记录API调用以及实体修改) 的ORM层改用**FreeSql**实现后，日志量激增，有没有办法利用 appsettings里 不同`namespace`不同`LogLevel` 来选择性地记录日志。
```json
"LogLevel": {
       "Default": "Information",
        "XXX.Audit": "Warning"
      }
```

**Comment by tky753** [comment]
比如说，在`DbContext`或`Repository`里加一个 **LogCategory** 属性，默认等于 `DbContext`或`Repository` 的FullName(可以不包括泛型参数？), 
然后每次执行sql，都生成一个**context**参数，把这个**LogCategory** 传进**context**里，
在`UseMonitorCommand` 的时候传入这个**context**，`Action<XXContext> executing`
然后可以根据其中的**LogCategory** 用 `loggerFactory.loggerFactory(ctx.LogCategory )`生产`ILogger`，
用这个`ILogger`来记录日志 就能根据 `namespace`来过滤了吧

这个改动可能还是有点大，应该还有更简便的方法吧。

**Comment by 2881099** [comment]
现在有 UseMonitorCommand 里面可以使用 AsyncLocal 来获取当前请求的 url，用 url 来作为 logName 可能比较简单一点。

如果要针对不同的 DbContext/Repository 来记录日志，代码入侵会大一些。

**Comment by tky753** [comment]
UseMonitorCommand 那种闭包和 依赖注入一起用，愣是没整明白。
尤其注入还分Scoped和Singleton，感觉头要炸了

**Comment by 2881099** [comment]
https://www.cnblogs.com/FreeSql/p/12447112.html

看看这个，之前写的

**Comment by tky753** [comment]
最后，决定放弃每次都resolve一个 新的Logger，之前是以为 用的日志组件Serilog 在每次修改配置文件后都能动态刷新日志级别，所以觉得也要每次都resolve一个新的Logger。
但发现就 MinimumLevel会动态刷新， override的命名空间 改了还是要重启服务器才能生效，那我干脆就 resolve一次得了，瞬间简单了很多。
```yml
Serilog:
  MinimumLevel:
    Default: Debug
    Override:
    XXX.Audit: Warning
```
