### ISSUE TITLE
cast(a as varchar)在sqlserver中有问题

### ISSUE THREAD

**Issue by wzohxia** [dotnetcore/FreeSql#335]
cast(a as varchar)在sqlserve会截取长度为30位，freesql里面有比较多这样的语句转化 导致取数错误

**Comment by 2881099** [comment]
这些反馈，你使用的代码发一下

**Comment by wzohxia** [comment]
例如 var test= _context.Select<Table1>()
                 .Where(info => info.Relation.StartsWith(_context.Select<Table1>().Where(b => b.ID == 1109777748345225216).First(b => b.Relation)))
                 .ToList(info => info.ID);
我这里的relation是nvarchar(1000)  输出的时候

SELECT a.[ID] as1 
FROM [Table1] a With(NoLock) 
WHERE ((a.[Relation]) LIKE (cast((SELECT TOP 1 b.[Relation] 
	FROM [Table1] b With(NoLock) 
	WHERE (b.[ID] = 1109777748345225216)) as nvarchar)+'%'))
这里截取了relation的长度

**Comment by 2881099** [comment]
info.Relation.StartsWith 这个换成 info.Relation.StartsWith2

[ExpressionCall]
public static class DbFunc {
  //必要定义 static + ThreadLocal
  static ThreadLocal<ExpressionCallContext> context = new ThreadLocal\<ExpressionCallContext\>();

  public static string StartsWith2(this string that, [RawValue] string arg1)
  {
    var up = context.Value;
    return $"({up.ParsedContent["that"]}) like {arg1}"; // 处理下单引号
  }
}

**Comment by 2881099** [comment]
cast nvarchar 不好统一处理，可以这样针对性处理一下

**Comment by wzohxia** [comment]
![image](https://user-images.githubusercontent.com/22089141/83607217-67588080-a5ad-11ea-8bd7-78293c63d580.png)

**Comment by 2881099** [comment]
修改了一下，再看代码

**Comment by 2881099** [comment]
表达式解析做了整理，数字/enum 转换为 cast(.. as nvarchar(100))，其他类型转换为 cast(.. as nvarchar(max))

**Comment by 2881099** [comment]
1.6.0 中已解决
