### ISSUE TITLE
支持一个实体类对应多个表的查询吗？

### ISSUE THREAD

**Issue by db300** [dotnetcore/FreeSql#338]
如题，例如：
我定义了一个实体类：Tag
有多个不同名称的表，Tag001、Tag002……
可以都用Tag实体类，对这些表进行查询和修改等操作吗？

**Comment by 2881099** [comment]
var curd = fsql.GetRepository\<Tag\>(null, old => old + “001”);

或者 repo.AsTable(old => old + “001”);

或者 fsql.Select\<Tag\>().AsTable((_, old) => old + “001”); Update/Delete/Insert 都有该方法

**Comment by db300** [comment]
好的，赞，AsTable这个，我去查api
