### ISSUE TITLE
如何实现数据库的其他函数？

### ISSUE THREAD

**Issue by CGuoL** [dotnetcore/FreeSql#339]
项目中大量使用了位运算(orcl：bitand)，请问下怎么实现？

**Comment by 2881099** [comment]
## 自定义解析

```csharp
[ExpressionCall]
public static class DbFunc {
  //必要定义 static + ThreadLocal
  static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

  public static DateTime FormatDateTime(this DateTime that, string arg1)
  {
    var up = context.Value;
    if (up.DataType == FreeSql.DataType.Sqlite) //重写内容
      up.Result = $"date_format({up.ParsedContent["that"]}, {up.ParsedContent["arg1"]})";
    return that;
  }
}

var sql1 = fsql.Select<SysModule>()
  .ToSql(a => a.CreateTime.FormatDateTime("yyyy-MM-dd"));
//SELECT date_format(a."CreateTime", 'yyyy-MM-dd') as1 
//FROM "SysModule" a
```

\[ExpressionCall\] 特性可在静态扩展类上标记，也可以在单个静态方法上标记；

| ExpressionCallContext 属性 | 类型 |描述 |
| -- | -- | -- |
| DataType | FreeSql.DataType | 用于实现不同数据库的适配判断条件 |
| ParsedContent | Dictionary\<string, string\> |函数的各参数解析结果 |
| DbParameter | DbParameter | that 被参数化的对象（有可能为 null) |
| UserParameters | List\<DbParameter\> | 可附加参数化对象 |
| Result | string | 返回表达式函数表示的 SQL 字符串 |

> 当扩展方法返回值为 string 时，其返回值也可以当作 context.Value.Result 功能

> 当不想解析指定参数时，使用特性 \[RawValue\] 标记

**Comment by CGuoL** [comment]
感谢，我去试试。
