### ISSUE TITLE
达梦数据库数据插入问题

### ISSUE THREAD

**Issue by huafeis** [dotnetcore/FreeSql#341]
我的开发平台为.NET CORE 3.1，我用的是达梦7数据库，在做数据插入时，数据虽然插入进去了，但是出现在以下问题：
1.表的主键被删除了。
2.字段的数据类型被改变了，原字段的类型为VARCHAR的，被更改为NVARCHAR2，原字段类型为DATETIME的被更改为TIMESTAMP，原字段类型为INT的被更改为NUMBER了，不知是何原因，我的部分代码如下：
string conStr=“server=127.0.0.1;port=5236;user id=PRISON;password=123456789;database=PRISON;poolsize=5” 
IFreeSql fsql = new FreeSql.FreeSqlBuilder()
                       .UseConnectionString(FreeSql.DataType.Dameng, conStr)
                       .UseMonitorCommand(cmd => Trace.WriteLine($"线程：{cmd.CommandText}\r\n"), (cmd, traceLog) => Console.WriteLine(traceLog))
                       .UseAutoSyncStructure(true) //自动创建、迁移实体表结构
                       .UseLazyLoading(true)
                       .UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper)
                       .Build();
Yz_Rjsqxx xx = new Yz_Rjsqxx 
{
    ID=...,
    ......
};
fsql.Insert(xx).ExecuteAffrows();
ID为主键，数据插入后，ID的主键被取消。
另外：我尝试恢复ID的主键后，再插入就失败了，提示“无效的表[Yz_Rjsqxx]约束”
不知道大家遇到这个问题了没，如何解决？

**Comment by 2881099** [comment]
1.表的主键被删除了。

是什么意思，不明白？是不是开启了 UseAutoSyncStructure(true)，实体类属性又没有标记 [Column(IsPrimary)]。

2、问题同上。如果是 DbFirst，先不要开启 UseAutoSyncStructure(true)

**Comment by 2881099** [comment]
UseAutoSyncStructure(true) 是 CodeFirst 模式开发的功能，即先定义实体类型，curd 的时候会自动同步表结构。

如果已经建立了表，使用 FreeSql.Generator 工具生成实体类，这种模式不适合使用 CodeFirst 自动自动结构的方式了。

 FreeSql.Generator 工具生成实体类文档：https://github.com/dotnetcore/FreeSql/wiki/DbFirst

**Comment by huafeis** [comment]
> UseAutoSyncStructure(true) 是 CodeFirst 模式开发的功能，即先定义实体类型，curd 的时候会自动同步表结构。
> 
> 如果已经建立了表，使用 FreeSql.Generator 工具生成实体类，这种模式不适合使用 CodeFirst 自动自动结构的方式了。
> 
> FreeSql.Generator 工具生成实体类文档：https://github.com/dotnetcore/FreeSql/wiki/DbFirst

确实是这个原因，改为UseAutoSyncStructure(false) 正常！
