### ISSUE TITLE
实体都已Entity约定结尾，这个时候使用约定方式设计导航属性会报错，是否有哪里可以设置的方法

### ISSUE THREAD

**Issue by tt123456tt** [dotnetcore/FreeSql#342]
实体都已Entity约定结尾，这个时候使用约定方式设计导航属性会报错，是否哪里有可以设置的方法，比如像这种：【OneToMany】导航属性 Admin.Core.Entity.Admin.UserEntity.Roles 在 RoleEntity 中没有找到对应的字段，如：RolesUserEntityId、RolesUserEntity_Id

**Comment by 2881099** [comment]
这种情况是因为用了约定命名的方式，然后又没有使用约定方式命名报的错。
可以手工绑定属性进行关联。

# 自定义导航关系

```csharp
//导航属性，OneToMany
[Navigate(nameof(song_tag.song_id))]
public virtual List<song_tag> Obj_song_tag { get; set; }
//在 song_tag 查找 song_id 属性，与 本实体.主键 关联

//导航属性，ManyToOne/OneToOne
[Navigate(nameof(song_id))]
public virtual Song Obj_song { get; set; }
//在 本实体 查找 song_id 属性，与 Song.主键 关联

//导航属性，ManyToMany
[Navigate(ManyToMany = typeof(tag_song))]
public virtual List<tag> tags { get; set; }
```

---

也可以使用 FluentApi 在外部设置导航关系：

```csharp
fsql.CodeFirst.ConfigEntity<实体类>(a => a
    .Navigate(b => b.roles, null, typeof(多对多中间实体类))
    .Navigate(b => b.users, "uid")
);
```

文档：
https://github.com/dotnetcore/FreeSql/wiki/%E5%AE%9E%E4%BD%93%E5%85%B3%E7%B3%BB

**Comment by tt123456tt** [comment]
> 这种情况是因为用了约定命名的方式，然后又没有使用约定方式命名报的错。
> 可以手工绑定属性进行关联。
> 
> # 自定义导航关系
> ```cs
> //导航属性，OneToMany
> [Navigate(nameof(song_tag.song_id))]
> public virtual List<song_tag> Obj_song_tag { get; set; }
> //在 song_tag 查找 song_id 属性，与 本实体.主键 关联
> 
> //导航属性，ManyToOne/OneToOne
> [Navigate(nameof(song_id))]
> public virtual Song Obj_song { get; set; }
> //在 本实体 查找 song_id 属性，与 Song.主键 关联
> 
> //导航属性，ManyToMany
> [Navigate(ManyToMany = typeof(tag_song))]
> public virtual List<tag> tags { get; set; }
> ```
> 
> 也可以使用 FluentApi 在外部设置导航关系：
> 
> ```cs
> fsql.CodeFirst.ConfigEntity<实体类>(a => a
>     .Navigate(b => b.roles, null, typeof(多对多中间实体类))
>     .Navigate(b => b.users, "uid")
> );
> ```
> 
> 文档：
> https://github.com/dotnetcore/FreeSql/wiki/%E5%AE%9E%E4%BD%93%E5%85%B3%E7%B3%BB

这个错误产生的原因我了解，我想知道的是，freesql是否可以去配置实体后缀，因为有很多公司对实体类命名规则是有要求的，如果能配置实体类后缀或者前缀，然后导航属性关联那里自动根据这个配置再去做关联是不是可行

**Comment by 2881099** [comment]
理解你的想法，经过这一年半的实践证明，声明式比约定式真加直观，维护性更佳。

我现在只是做测试才用约定方式，真实项目会用 [Navigate] 声明式。

约定规则复杂之后，排查问题更加困难。

**Comment by tt123456tt** [comment]
那后期会考虑增加这个配置么？

**Comment by 2881099** [comment]
不考虑，因为使用出问题太隐晦，使用者出问题只会来这里求救，最终需要FreeSql维护者投入精力排查问题。

**Comment by tt123456tt** [comment]
好的，了解
