### ISSUE TITLE
建议【从库】增加权重值

### ISSUE THREAD

**Issue by HeebeLee** [dotnetcore/FreeSql#343]
根据权重随机出现可能性，这样可以根据不同的预期压力做设置。

**Comment by 2881099** [comment]
在考虑，能否不改变用户入口的使用方法来实现

**Comment by HeebeLee** [comment]
我觉得可以保留现在UseSlave的入口方法，默认为0或者100之类的。增加一个单独设置入口，AddUseSlave("string1", 50).AddUseSlave("string2", 30)。
这样可以避免现在的用户崩溃或者升级，未来考虑淘汰了现在的UseSlave([])的方法(过期机制)，考虑使用AddUseSlave(String, Int)的方法。

**Comment by HeebeLee** [comment]
AddUseSlave(String, Int, Bool = false);
连接信息，权重值，是否备用（只有前面不可用的情况下才会使用）

**Comment by 2881099** [comment]
backup 备用从库的设置，是否考虑从库都失败之后的问题。当下逻辑是查主库

**Comment by 2881099** [comment]
暂时先关闭，如有需求再继续讨论
