### ISSUE TITLE
如何在mysql连接时指定时区？

### ISSUE THREAD

**Issue by chatop2020** [dotnetcore/FreeSql#344]
因为mysql运行的时区不正确，需要在连接串里指定时区

如果现在不能支持，那么有没有办法让freesql执行如“set time_zone='+8:00';”这样的mysql语句？

**Comment by 2881099** [comment]
连接串不清楚，语完找资料。

如果想让连接后执行，可以用 UseConnectionFactory，参考：

https://github.com/dotnetcore/FreeSql/blob/7a2000a29e4ec6b68c85214df8f1a9c7d523e292/FreeSql.Tests/FreeSql.Tests/g.cs#L75

**Comment by 2881099** [comment]
能用连接串解决最好，看看 MySqlConnectionBuilder 里面有没有时区设置

**Comment by chatop2020** [comment]
谢谢，还是没搞定，最终还是直接修改了mysql服务的时区
