### ISSUE TITLE
DROP TABLE 后，就无法自动建表

### ISSUE THREAD

**Issue by guliang21** [dotnetcore/FreeSql#345]
开启自动同步以后，直接执行 SQL 语句 `DROP TABLE` 删除表，然后插入数据，就不会自动建表，而是报 `对象名 xx 无效。`

**Comment by 2881099** [comment]
是的，SyncStructure 有防止运行中重复迁移

https://github.com/dotnetcore/FreeSql/blob/7a2000a29e4ec6b68c85214df8f1a9c7d523e292/FreeSql/Internal/CommonProvider/CodeFirstProvider.cs#L71

两个办法的可以解决

1. 新建临时 IFreeSql 执行，SyncStructure，用完释放 IfreeSql

2. 反射控制内部变量，看上面文件 71 行那个字段
