### ISSUE TITLE
有没有类似Petapoco中的 【ResultColumn】这种实体特性

### ISSUE THREAD

**Issue by swimhigher** [dotnetcore/FreeSql#347]
比如我有一个表包含用户id，但是查询的时候我想关联到用户名，意思是这个用户名字段只做查询展示用，和数据库没有映射关系，

**Comment by 2881099** [comment]
可否给出简单的代码示例

**Comment by swimhigher** [comment]
> 可否给出简单的代码示例

fsql.Select<SysButton>().WithSql(sql.ToString()).Page
SysButton表有个MenuName字段（ignore字段，数据库不映射），如何做到生成的sql语句有select  MenuName这一列，

**Comment by 2881099** [comment]
不映射，又想查询的时候出现，不会出错字段不存在吗？

**Comment by swimhigher** [comment]
可能是我表述有问题，数据库不存在该字段，我sql语句用了join查询到的，

**Comment by 2881099** [comment]
是这个效果吗？fsql.Ado.Query\<T>(sql)

**Comment by swimhigher** [comment]
> 是这个效果吗？fsql.Ado.Query<T>(sql)

对滴，就是这个，但是这个Query没有page分页方法

**Comment by 2881099** [comment]
var pageSql = fsql.Select\<SysButton>().WithSql(sql.ToString()).Page(..).ToSql("*");

var result = fsql.Ado.Query\<T\>(pageSql);

**Comment by 2881099** [comment]
var result = fsql.Ado.Query\<T>(pageSql);

这里的 T 不能传 IsIgnore 的实体类型哦，否则也会被忽略。

```csharp
//这样或许可以
fsql.Select<SysButton>().WithSql(sql.ToString()).Page(..).ToList<SysButtonDto>();

class SysButtonDto : SysButton {}
```

**Comment by swimhigher** [comment]
> var result = fsql.Ado.Query<T>(pageSql);
> 
> 这里的 T 不能传 IsIgnore 的实体类型哦，否则也会被忽略。
> 
> ```cs
> //这样或许可以
> fsql.Select<SysButton>().WithSql(sql.ToString()).Page(..).ToList<SysButtonDto>();
> 
> class SysButtonDto : SysButton {}
> ```

我一开始也试过了用Dto继承实体，但是这个Dto会生成数据库表

**Comment by 2881099** [comment]
dto 如果不当成实体来用，就不会生成表。

这种情况，考虑要不要关闭自动生成迁移动作。或者给 Dto 打上特性 [Table(DisableSyncStructure = true)]。

**Comment by swimhigher** [comment]
谢谢你的回答
试了下，用tolist也不行，只能Dto加上 [Table(DisableSyncStructure = true)]了，希望提供个[ResultColumn]特性
https://www.cnblogs.com/youring2/archive/2012/06/19/2554976.html
