### ISSUE TITLE
使用Update ->SetDto方法生成的修改语句。报错。执行不了为什么？？

### ISSUE THREAD

**Issue by baimvc** [dotnetcore/FreeSql#349]
UPDATE "app_task_fltarr" SET "flt_dep_icao" = @p_0, "flt_eta" = @p_1, "flt_route" = @p_2 
WHERE ("task_id" = @exp_3)
@p_0                 = YCNK
@p_1                 = 2020/6/18 8:22:00
@p_2                 = CHINA EASTERN
@exp_3               = 6b949495-7de2-4cc9-ac55-50968d125f3a
Can't write CLR type System.String with handler type TimestampHandler

**Comment by 2881099** [comment]
flt_eta 是不是用了 MapType。

不用参数化呢？ fsql.Update\<t>().NoneParameter().SetDto(..)
