### ISSUE TITLE
作者你好，Repository+UnitOfWork  用autofac好像有问题。

### ISSUE THREAD

**Issue by ElvenP** [dotnetcore/FreeSql#350]

**Comment by 2881099** [comment]
是什么问题，https://github.com/dotnetcore/FreeSql/issues/289 有没有看这个

**Comment by ElvenP** [comment]
Duplicate of #

> 是什么问题，[＃289](https://github.com/dotnetcore/FreeSql/issues/289)有没有看这个

首先感觉作者的回复，并且是这么快的回复。
![2](https://user-images.githubusercontent.com/66731105/85007596-53587580-b18e-11ea-8c7c-ff35472fe6f7.png)
![3](https://user-images.githubusercontent.com/66731105/85007605-581d2980-b18e-11ea-9b77-68ff6028899d.png)
![4](https://user-images.githubusercontent.com/66731105/85007614-5a7f8380-b18e-11ea-946a-2a6660c93929.png)
![5](https://user-images.githubusercontent.com/66731105/85007621-5c494700-b18e-11ea-8baa-b43ee8d383da.png)
![6](https://user-images.githubusercontent.com/66731105/85007625-5e130a80-b18e-11ea-82c6-d28c30bbd188.png)
![7](https://user-images.githubusercontent.com/66731105/85007631-5fdcce00-b18e-11ea-8bce-f36d4f9392c1.png)
![1](https://user-images.githubusercontent.com/66731105/85007645-63705500-b18e-11ea-9cea-e9db89f43ebf.png)
大概的流程就是这样。最后一张图就是报错的。没有注入成功。
然后我的项目中还使用了autofac。我想是不是由于与asp.net core 本身的注入有冲突。
于是我写在了autofac里面。。如下图
![8](https://user-images.githubusercontent.com/66731105/85008257-4ee08c80-b18f-11ea-962a-94fc65cee907.png)

**Comment by 2881099** [comment]
builder.RegisterType\<IFreeSql> 这样是对的吗，单例，还需要指定实例 fsql。

前面的错误，提示没有注入 UnitOfWorkManager，但是前面的代码看着是注入了？

**Comment by ElvenP** [comment]
> builder.RegisterType<IFreeSql> 这样是对的吗，单例，还需要指定实例 fsql。
> 
> 前面的错误，提示没有注入 UnitOfWorkManager，但是前面的代码看着是注入了？ 
注入了，在第六张图里注入了。另外

builder.RegisterType<IFreeSql我只是写了个例子，并没在autofac中使用

**Comment by 2881099** [comment]
看前面的注入使用的是MS自带的DI的注入，没有看到 autofac 代码。

是不是从 IServiceCollection 转 autofac 的时候丢失了，在 .net core3.x 还能这样用吗

**Comment by ElvenP** [comment]
对，前面是ms自带的注入。auto注入的repos和serv.

2881099 <notifications@github.com>于2020年6月18日 周四18:38写道：

**Comment by 2881099** [comment]
能否整理一个简单demo上传一下？

**Comment by ElvenP** [comment]
https://github.com/ElvenP/DotNetCoreLearn


2881099 <notifications@github.com>于2020年6月18日 周四18:45写道：

**Comment by 2881099** [comment]
问题一：版本不一致，应该都用一样的版本（Admin.Core.Common.csproj）

```xml
      <PackageReference Include="FreeSql" Version="1.6.0-preview0611" />
      <PackageReference Include="FreeSql.Provider.SqlServer" Version="1.5.0" />
      <PackageReference Include="FreeSql.Repository" Version="1.6.0-preview0611" />
```

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/85012825-31fb8780-b196-11ea-9b78-436dbab12d90.png)

运行OK，没有出现说的注入错误

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/85012968-6ec77e80-b196-11ea-9c4b-31a4a144caa3.png)

在 UserService.GetAsync 方法上增加 [Transaction] 特性后，事务也生效了。

**Comment by ElvenP** [comment]
首先非常感谢您的回复，按照你的提示，我修改了这些东西后。发现f5下没有问题。。。但是ctrl+f5还是报原来的错。


2881099 <notifications@github.com> 于2020年6月18日周四 下午7:04写道：

**Comment by 2881099** [comment]
直接用控制台运行呢，dotnet run

**Comment by ElvenP** [comment]
原因找到了，还是由于同时使用了di注入和autofac 注入导致的。现在改为autofac注入就正常了。如下图。非常感谢回复，已打赏。
[image: image.png]

2881099 <notifications@github.com> 于2020年6月18日周四 下午7:44写道：

**Comment by 2881099** [comment]
谢谢
