### ISSUE TITLE
如何设置查询条件的like 呢？

### ISSUE THREAD

**Issue by pccai** [dotnetcore/FreeSql#351]
CUST enty = pdm.GetModel<CUST>(new { Name **like** parms.name });

**Comment by 2881099** [comment]
.表达式函数： Where(a=>a.Name.Contains(“xx”))

进阶：动态条件 https://github.com/dotnetcore/FreeSql/wiki/查询#特别介绍-wheredynamicfilter

**Comment by liuyl1992** [comment]
> .表达式函数： Where(a=>a.Name.Contains(“xx”))
> 
> 进阶：动态条件 [https://github.com/dotnetcore/FreeSql/wiki/查询#特别介绍-wheredynamicfilter](https://github.com/dotnetcore/FreeSql/wiki/%E6%9F%A5%E8%AF%A2#%E7%89%B9%E5%88%AB%E4%BB%8B%E7%BB%8D-wheredynamicfilter)

那 sql 的in又要用什么呢
.Where(a=> sqlids.Contains(a.Id.ToString())

**Comment by 2881099** [comment]
> > .表达式函数： Where(a=>a.Name.Contains(“xx”))
> > 进阶：动态条件 [https://github.com/dotnetcore/FreeSql/wiki/查询#特别介绍-wheredynamicfilter](https://github.com/dotnetcore/FreeSql/wiki/%E6%9F%A5%E8%AF%A2#%E7%89%B9%E5%88%AB%E4%BB%8B%E7%BB%8D-wheredynamicfilter)
> 
> 那 sql 的in又要用什么呢
> .Where(a=> sqlids.Contains(a.Id.ToString())

对像不一样

like 对应 String 对象 Contains 方法

in 对应 Array 对象 Contains 方法

**Comment by 2881099** [comment]
其实和 C# 一样，c# 包含也是 String Contains

c# 判断 List/Array 里面是否存在某面，也是 Enumable Contains

**Comment by liuyl1992** [comment]
那string 和string 只能是like的意义，没有 in，用in的表达得把先转换成集合在Contains

**Comment by 2881099** [comment]
是的，in 是针对 Array/List 的

new [] { str }.Contains(name)
