### ISSUE TITLE
uow.GetOrBeginTransaction()得到的事务可以单独使用吗?

### ISSUE THREAD

**Issue by xlfqiji** [dotnetcore/FreeSql#352]
```
IRepositoryUnitOfWork uow = freesql.CreateUnitOfWork();
DbTransaction trans = uow.GetOrBeginTransaction();
```
得到事务对象后, 是否可以丢掉uow对象不管, 直接用WithTransaction(trans) 增删改查, 然后trans.Commit()提交?
uow需要特地Dispose吗?
十分感谢!

**Comment by 2881099** [comment]
uow.commit rollback

只能获取事务，提交和回滚要用工作单元对象控制。

**Comment by 2881099** [comment]
trans.commit 无法释放工作单元，也没办的获取它的钩子。所以控制权要在 uow 上面。

**Comment by xlfqiji** [comment]
明白了,谢谢!
