### ISSUE TITLE
DbFirst 在生成代码时，数据库字段中设计不规范，从而生成的类属性字段重复，从而编译报错。

### ISSUE THREAD

**Issue by neoayi** [dotnetcore/FreeSql#356]
![image](https://user-images.githubusercontent.com/137907/85848737-3d753100-b7dc-11ea-9f4c-34687171d333.png)
如图：
以上是 EfCore Power Tools 根据数据库生成的代码

以下为数据库的格式 
![image](https://user-images.githubusercontent.com/137907/85848871-8331f980-b7dc-11ea-885c-dc8ff478115c.png)

-- 以下为 FreeSql Tools 生成的代码
![image](https://user-images.githubusercontent.com/137907/85848966-b07ea780-b7dc-11ea-8e35-0f235b750811.png)

仅供参考。

**Comment by 2881099** [comment]
这个问题可以在生成器的模板内解决
