### ISSUE TITLE
WebApi中若是dynamic 参数，不能直接给 new {ID = '****'} 参数

### ISSUE THREAD

**Issue by pccai** [dotnetcore/FreeSql#358]
比如：
 public HttpResponseMessage GetCustomDetail(dynamic parms)
        {
              CUST enty = pdm.GetModel<CUST>(new { ID = parms.ID });

GetModel失败，提示错误信息：
_不存在从对象类型 Newtonsoft.Json.Linq.JValue 到已知的托管提供程序本机类型的映射。。。。_

最后需要显式的：  parms.ID.ToString()

**Comment by 2881099** [comment]
这是动态类型 dynamic 的限制，错误信息是 CLR 报的。

**Comment by pccai** [comment]
tks
