### ISSUE TITLE
底层基于FreeSql实现Saas系统，如何过滤在仓储层过滤租户字段

### ISSUE THREAD

**Issue by tonfy** [dotnetcore/FreeSql#359]
底层基于FreeSql实现Saas系统，如何过滤在仓储层过滤租户字段？除了过滤我们还要在新增和修改时也加上保存相关字段的操作，有什么比较好的办法，谢谢！

**Comment by 2881099** [comment]
全局过滤器可以处理查询

Aop.AuditValue 事件配合 AsyncLocal 可以处理插入或更新

**Comment by tonfy** [comment]
OK,我研究一下，谢谢你的回答！

**Comment by tonfy** [comment]
> 全局过滤器可以处理查询
> 
> Aop.AuditValue 事件配合 AsyncLocal 可以处理插入或更新

OK,我研究一下，谢谢你的回答！
