### ISSUE TITLE
如何对大数据单表进行查询，如单表5000万条+

### ISSUE THREAD

**Issue by yzpopulation** [dotnetcore/FreeSql#360]
如何对大数据单表进行查询，如单表5000万条+，内存无法装载，会不会造成崩溃？

**Comment by 2881099** [comment]
会内存溢出，需要的时候再去查

**Comment by yzpopulation** [comment]
> 会内存溢出，需要的时候再去查

那么如何实现懒加载大型单表数据？我之前使用的是servicestack.ormlite，这个有lazy方法

**Comment by 2881099** [comment]
想全部查询吗，分段查询。ToChunk

**Comment by yzpopulation** [comment]
> 想全部查询吗，分段查询。ToChunk

是这样的，我要将数据转移，由于单表过大，拟采用分段取数据，skip limit 方法性能开销过大，例如在pl/sql 查询oracle 时 select * from t1 ,可以根据需要取部分数据，点击下一页，加载下一页数据，点击到最后取全部数据。想问freesql有没有这种懒加载机制。

**Comment by 2881099** [comment]
fsql.Select\<t\>().ToChunk 看看能不能满足

**Comment by yus1977** [comment]
@2881099  请问使用ToChunk 时，如果中途需要停止读取，怎么处理

**Comment by 2881099** [comment]
> @2881099 请问使用ToChunk 时，如果中途需要停止读取，怎么处理

暂时不能，需要增加 callback 委托的返回值才行。

**Comment by 2881099** [comment]
@yus1977 ToChunk 停止读取的需求已处理，不过影响到了一点用户习惯

执行查询，分块返回数据，可减少内存开销。比如读取10万条数据，每次返回100条处理。

```csharp
var testlist1 = fsql.Select<Song>().OrderBy(a => a.Id).ToList();
var testlist2 = new List<Song>();
fsql.Select<Song>().OrderBy(a => a.Id).ToChunk(100, done => {
    testlist2.AddRange(done.Object);
    //done.IsBreak = true; v1.7.0 停止读取
});
//这里示范，最终 testlist1 与 testlist2 返回的数据相同。
```
