### ISSUE TITLE
咨询string, parms 形式的OrderBy写法

### ISSUE THREAD

**Issue by pccai** [dotnetcore/FreeSql#361]
OrderBy | <this> | string, parms | 按原生sql语法排序，OrderBy("count(name) + ?cc", new { cc = 1 })

select * from Tags order by created, category desc

多个字段排序如何写呢？tks

return conn.Select<T>(parms)
 .Count(out total)
  .Page(current, pageSize)
  **.OrderBy(“created  + @cc" , new {cc= 1})**
  .ToList();

**Comment by 2881099** [comment]
OrderBy(“created desc, id asc”)

**Comment by zhaoxingyu999** [comment]
![1G_VJ(CT X~ZF YO4MC C9B](https://user-images.githubusercontent.com/27735252/167624577-0ce55d0b-2cbc-4ef3-8ea5-5af11831fd70.jpg)
ISelectGouping 如何实现上如string params orderby的写法

**Comment by 2881099** [comment]
ISelectGrouping 不能字符串
