### ISSUE TITLE
使用Page方法，进行GroupBy 时报错

### ISSUE THREAD

**Issue by landonzeng** [dotnetcore/FreeSql#363]
代码如下
``
var housePageList = _freeSql.Select<THousePageListInfo>().Where(it => it.IsEnd == false && it.Creation_Date == page.createDate)
                .GroupBy(it => new { it.AreaId, it.AreaName, it.HouseId, it.Url, it.Title, it.GoodHouse_Tags, it.Other_Tages, it.FollowInfo, it.ReleaseTime, it.IsEnd, it.PageNow })
                .Page(page.pageIndex, page.pageSize)
                .ToList
                (
                    it => new THousePageListInfo
                    {
                        Id = it.Min(it.Value.Id),
                        AreaId = it.Value.AreaId,
                        AreaName = it.Value.AreaName,
                        HouseId = it.Value.HouseId,
                        Borough = it.Min(it.Value.Borough),
                        Businessircle = it.Min(it.Value.Businessircle),
                        Url = it.Value.Url,
                        Title = it.Value.Title,
                        GoodHouse_Tags = it.Value.GoodHouse_Tags,
                        Other_Tages = it.Value.Other_Tages,
                        FollowInfo = it.Value.FollowInfo,
                        ReleaseTime = it.Value.ReleaseTime,
                        IsEnd = it.Value.IsEnd,
                        PageNow = it.Value.PageNow,
                        Creation_Date = it.Min(it.Value.Creation_Date),
                        Creation_Time = it.Min(it.Value.Creation_Time)
                    }
                );
``
然后代码运行到时，生成的sql里由于使用了别名，而page分页时默认使用的是id排序，所以SQL语句里没有id列，故报错，生成的sql如下
``
SELECT max(a.[Id]) as1, a.[AreaId] as2, a.[AreaName] as3, a.[HouseId] as4, min(a.[Borough]) as5, min(a.[Businessircle]) as6, a.[Url] as7, a.[Title] as8, a.[GoodHouse_Tags] as9, a.[Other_Tages] as10, a.[FollowInfo] as11, a.[ReleaseTime] as12, a.[IsEnd] as13, a.[PageNow] as14, min(a.[Creation_Date]) as15, min(a.[Creation_Time]) as16
      FROM [T_HousePageListInfo] a
      WHERE (a.[IsEnd] = 0 AND a.[Creation_Date] = '2020-07-07 00:00:00.000')
      GROUP BY a.[AreaId], a.[AreaName], a.[HouseId], a.[Url], a.[Title], a.[GoodHouse_Tags], a.[Other_Tages], a.[FollowInfo], a.[ReleaseTime], a.[IsEnd], a.[PageNow]
      ORDER BY a.[Id]
      OFFSET 651 ROW
      FETCH NEXT 651 ROW ONLY
``
报错信息：
``
消息 8127，级别 16，状态 1，第 8 行
ORDER BY 子句中的列 "T_HousePageListInfo.Id" 无效，因为该列没有包含在聚合函数或 GROUP BY 子句中。
``

**Comment by 2881099** [comment]
因为 sqlserver 分页的 sql 必须有一个排序字段，所以未设置 .OrderBy(..) 的情况下默认用了主键，然后因为它未被 group by 所以会报上述错误。

解决办法：

.Page(page.pagetIndex, page.pageSize)
.OrderBy(a => a.Key.AreaName)

**Comment by landonzeng** [comment]
好的，谢谢
