### ISSUE TITLE
多租户问题

### ISSUE THREAD

**Issue by qiuhaohui163** [dotnetcore/FreeSql#364]
如果多租户,能否使用postgresql的多schema模式而非多数据库模式?
在实体中定义Table特性可写入test schema下, 这种写法无法使用变量值. 
`
[Table(Name="test.test")]
`
使用aop
`sql.Aop.ConfigEntity += (s, e) => {
                e.ModifyResult.Name = "test.test"; //表名
            };
`
还是默认增加到public schema下
或者有其他方式吗?

**Comment by 2881099** [comment]
```c#
public class TenantAccessor : IDisposable
{
    static AsyncLocal<string> current = new AsyncLocal<string>();
    public static string Current => current.Value ?? "public";

    public TenantAccessor(string tenant)
    {
        current.Value = tenant;
    }

    public void Dispose()
    {
        current.Value = null;
    }
}

//TenantAccessor 在 mvc 中间件中处理
//aop 事件绑定一次
fsql.Aop.ConfigEntity += (s, e) => { e.ModifyResult.Name = $"{TenantAccessor.Current}.{e.EntityType.Name}"; //表名 };
```

**Comment by qiuhaohui163** [comment]
谢谢巨佬回答. 
可以了
之前aop失效
`sql.Aop.ConfigEntity += (s, e) => { e.ModifyResult.Name = "test.test"; //表名 };`
是因为实体设置了Table特性(Name="test"), 所以e.ModifyResult.Name = "test.test"无法生效
mark一记, 以免后来人采坑吧.

**Comment by 2881099** [comment]
文档有说明优先级

**Comment by jakey188** [comment]
> ```cs
> public class TenantAccessor : IDisposable
> {
>     static AsyncLocal<string> current = new AsyncLocal<string>();
>     public static string Current => current.Value ?? "public";
> 
>     public TenantAccessor(string tenant)
>     {
>         current.Value = tenant;
>     }
> 
>     public void Dispose()
>     {
>         current.Value = null;
>     }
> }
> 
> //TenantAccessor 在 mvc 中间件中处理
> //aop 事件绑定一次
> fsql.Aop.ConfigEntity += (s, e) => { e.ModifyResult.Name = $"{TenantAccessor.Current}.{e.EntityType.Name}"; //表名 };
> ```
这种切换租户后无效

**Comment by 2881099** [comment]
> > ```cs
> > public class TenantAccessor : IDisposable
> > {
> >     static AsyncLocal<string> current = new AsyncLocal<string>();
> >     public static string Current => current.Value ?? "public";
> > 
> >     public TenantAccessor(string tenant)
> >     {
> >         current.Value = tenant;
> >     }
> > 
> >     public void Dispose()
> >     {
> >         current.Value = null;
> >     }
> > }
> > 
> > //TenantAccessor 在 mvc 中间件中处理
> > //aop 事件绑定一次
> > fsql.Aop.ConfigEntity += (s, e) => { e.ModifyResult.Name = $"{TenantAccessor.Current}.{e.EntityType.Name}"; //表名 };
> > ```
> 
> 这种切换租户后无效

映射只会处理一次，然后缓存起来，所以这里aop只会执行一次生效。

新版本可以考虑增加这个功能。

**Comment by 2881099** [comment]
@jakey188 

v3.2.833 可以使用 Aop 动态设置 TableName

```c#
var fsql = new FreeSql.FreeSqlBuilder()
    .UseMappingPriority(MappingPriorityType.Attribute, MappingPriorityType.FluentApi, MappingPriorityType.Aop)
    ....;

fsql.Aop.ConfigEntity += (s, e) => { e.ModifyResult.Name = $"{TenantAccessor.Current}.{e.EntityType.Name}"; //表名 };

public class TenantAccessor : IDisposable
{
    static AsyncLocal<string> current = new AsyncLocal<string>();
    public static string Current => current.Value ?? "public";

    public TenantAccessor(string tenant)
    {
        current.Value = tenant;
    }

    public void Dispose()
    {
        current.Value = null;
    }
}
```
