### ISSUE TITLE
关于实体映射,建立表索引,目前名称会重复

### ISSUE THREAD

**Issue by pigwing** [dotnetcore/FreeSql#366]
![QQ截图20200710120941](https://user-images.githubusercontent.com/8393545/87115611-584ca880-c2a6-11ea-999a-53abf1899c64.png)
目前实体映射的attribute中,Index中的name是固定写死的.当使用FluentApi动态建立分表的时候.存在的情况为:
1_Table和2_Table中索引名称会重复,导致建表失败.能否加入format形式,例如  [Index("{TableName}-uk_phone", "phone", true)] 占位符的形式,在建表的时候,自动建立唯一的索引.

**Comment by 2881099** [comment]
[Index("{tablename}_idx_01", "name")]

**Comment by 2881099** [comment]
测试过程中发现，mysql/sqlserver 可以不用设置 {tablename}

**Comment by pigwing** [comment]
哎呀.又是postgresql的问题,我是postgresql下的
