### ISSUE TITLE
关于首次无法完整加载元数据的导航配置信息的问题

### ISSUE THREAD

**Issue by parchon** [dotnetcore/FreeSql#367]
从 1.4 版本更新到 1.6，首次加载程序，会出现实体的某个集合导航属性不是有效的导航属性的问题，例如：
> Order 表：
```
public class Order {
    public int OrderID { get; set; }

    public virtual List<PropertyValue> PropertyValueList { get; set; }
}
```
> PropertyValue 表：
```
public partial class PropertyValue {
    public int PropertyValueID { get; set; }
    public int OrderID { get; set; }

    public virtual Order Order { get; set; }
}
```

> 加载数据使用 IncludeMany：

```
Select.IncludeMany(e => e.PropertyValueList).ToList()
```
会提示错误：
```
FreeSql：IncludeMany 类型 Order 的属性 PropertyValueList 不是有效的导航属性，提示：IsIgnore = true 不会成为导航属性
```
> 加载前执行这个后正常：
```
var tbref = FreeSql.CodeFirst.GetTableByEntity(typeof(Order)).GetTableRef(nameof(Order.PropertyValueList), true); 
```

**Comment by 2881099** [comment]
是否方便引用最新源码，看看还会不会出现该问题。也许还会。

![image](https://user-images.githubusercontent.com/16286519/87239217-1d31ad00-c43f-11ea-9f5e-3c52fff3e17d.png)

UtilsExpressionTree.cs 475 -> 525 这段代码，两步存储元数据，防止死循环查找导航属性。如果在这中间并发执行了 GetTableByEntity 或许会得到 TableRef 为 null 的情况。增加上述一行代码再执行正常，是不是加了调试断点。

总之最好拿最新源码再跑一下试试，测试时不要使用断点。等待测试回音

**Comment by 2881099** [comment]
暂时的结论：

对于复杂的导航配置模型（有循环引用）的导航对象，检查导航属性必须要避免死循环，所以分了两步存储：第一步存基础元数据，第二步存导航配置信息。

所以，在第一步、第二步中间，如果有并发，会有短暂的获取不到导航配置信息。

解决办法：

循环程序集，得到实体类型，循环调用 fsql.GetTableByEntity(实体类)，在单线程的时候预热好元数据。

**Comment by parchon** [comment]
非常感谢作者的帮助和回复。
1、这里确实有多个并发请求，已经确定是并发并起的问题
2、在循环执行配置表映射和导航属性： FreeSql.CodeFirst.ConfigEntity 后，执行 FreeSql.CodeFirst.GetTableByEntity(entityType)，可以解决这个问题
再次感谢。
