### ISSUE TITLE
实体类支持私有属性吗

### ISSUE THREAD

**Issue by jingyiliu** [dotnetcore/FreeSql#368]
DDD 中的实体类常常使用私有属性，好像这样：

public class Song
    {
        public Song(DateTime? create_time, bool? is_deleted, string title, string url)
        {
            Create_time = create_time;
            Is_deleted = is_deleted;
            Title = title;
            Url = url;
        }
        public int Id { get; private set; }
        public DateTime? Create_time { get; private set; }
        public bool? Is_deleted { get; private set; }
        public string Title { get; private set; }
        public string Url { get; private set; }
    }

不知道 FreeSql 有没有可能支持这个？

**Comment by 2881099** [comment]
印象中是支持 protected set; 的，private set; 需要测试验证才知道。

**Comment by jingyiliu** [comment]
private set;  是不支持的，我试过

**Comment by 2881099** [comment]
那就做成 protected set; 吧，和 private 区别不大
