### ISSUE TITLE
批量插入含几何属性的实体集到postgis，报错geometry不存在

### ISSUE THREAD

**Issue by laddg8** [dotnetcore/FreeSql#369]
[Demo.zip](https://github.com/dotnetcore/FreeSql/files/4908184/Demo.zip)
一、错误描述:  

1、将实体集合(含PostgisGeometry类型属性)批量插入Postgis空间表时，有时能成功，有时报错，不稳定。

2、查询命令也是有时成功，有时报错。

Postgis已扩展，geodata库.public架构.Navaid表，search_path="$User",public。关于Geometry列、geometry _columns视图的增删改查权限都已开启。

二、环境 : 

.Net Core 3.1

Postgresql 9.6   

Postgis 2.3    

FreeSql 1.6.0   

Npgsql 4.1.3

目前能想到的原因有两个
1、数据库关于geometry列的权限问题。
2、Npgsql.LegacyPostgis对geometry类型的映射问题。

**Comment by laddg8** [comment]
1、DBConnConfiguration.pgFreeSql.Insert(listNavaid).NoneParameter() .ExecuteAffrows();
报错： The NpgsqlDbType "Geometry" isn't present in your database.You may need to install an extension or upgrade to a newer version.
2、var listNavaidPg = DBConnConfiguration.pgFreeSql.Select<Navaid>() .ToList();
报错 ： The field "Geom" has type 'public.geometry',which is currently unknown to Npgsql.You can retrieve it as a string by marking it as unknown,please see the FAQ.

**Comment by 2881099** [comment]
经过测试 LegacyPostgis 不支持 srid，NetTopologySuite 可以保存 srid 数据。
