### ISSUE TITLE
请问支持像ef codefirst自动创建数据库吗？

### ISSUE THREAD

**Issue by happywhp1** [dotnetcore/FreeSql#370]
请问能支持像ef codefirst那样如果连接字符串中的数据库不存在，则创建数据库的功能

**Comment by 2881099** [comment]
表可以，数据库不可以，ef core 基本只考虑 sqlserver 所以好做。

之前做过创建数据库，后来取消了。各种数据库创建数据库差异大，设置选项不同，比如字符集，还有权限问题。创建数据库手工操作，一劳永逸，程序自动创建的帮助不大。
