### ISSUE TITLE
WhereDynamicFilter

### ISSUE THREAD

**Issue by qiuhaohui163** [dotnetcore/FreeSql#371]
使用WhereDynamicFilter条件搜索, netcore 使用system.text.json
因为DynamicFilterInfo 的value 类型为object 故反序列化的时候value类型为jsonElement,
因此会报错
如下图:
![image](https://user-images.githubusercontent.com/59816746/87266681-6c87e400-c4f8-11ea-9a04-44dc60a4ad4c.png)
除了改用AddNewtonsoftJson,  请问有什么其他解决办法继续使用system.text.json吗?

**Comment by 2881099** [comment]
用的是哪个版本？

**Comment by 2881099** [comment]
前面传过来的 json 是什么内容，发出来我试试

**Comment by 2881099** [comment]
我测试了，system.text.json 得到的确实是 JsonElement，你应该用的是 1.5 版本，1.6 版本有过更新解决了该问题。

更新日志：https://github.com/dotnetcore/FreeSql/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

建议持续关注更新日志。

**Comment by qiuhaohui163** [comment]
大佬, 我改了一下版本好像还是不行. 还需要哪里设置吗?
原来用的是1.7.0-preview 0705
版本号 从1.6的第一个preview包括正式版本, 到1.7最新的preview都试了
`         var config = new JsonSerializerOptions()
            {
                PropertyNamingPolicy = null,
                AllowTrailingCommas = true,
                IgnoreNullValues = true,
                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
                Converters = { new JsonStringEnumConverter() }
            };
            DynamicFilterInfo dyfilter = JsonSerializer.Deserialize<DynamicFilterInfo>(@"
                {
                  ""Logic"" : ""And"",
                  ""Filters"" :
                  [
                    {
                      ""Field"" : ""Name"",
                      ""Operator"" : ""Contains"",
                      ""Value"" : ""test""
                    },
                    {
                      ""Field"" : ""EName"",
                      ""Operator"" : ""Eq"",
                      ""Value"" : ""test""
                    }
                  ]
                }
                ", config);
           
            var res = await _sql.Select<XXXX>().WhereDynamicFilter(dyfilter).ToListAsync();
`

**Comment by 2881099** [comment]
好的，测到了漏网之鱼，等我发个 preview0713

**Comment by 2881099** [comment]
1.7.0-preview0713 更新到这个版本可以解决你说的问题
