### ISSUE TITLE
关于可空bool类型

### ISSUE THREAD

**Issue by lzy198845** [dotnetcore/FreeSql#372]
!(bool)t.ChkVldRng是否应该转换为：not(a.[ChkVldRng]=1) 而不是not(a.[ChkVldRng])，或者更好的建议

![image-20200714182758665](https://gitee.com/yangzhongyun/markdownimage/raw/master/image-20200714182758665.png)

感谢

**Comment by 2881099** [comment]
!t.ChkVldRng.Value

试试这样

**Comment by 2881099** [comment]
(bool)t.ChkVldRng == false

试试这样

**Comment by 2881099** [comment]
!(bool)t.ChkVldRng是否应该转换为：not(a.[ChkVldRng]=1) 

这种解析需要很强的前后动作判断，需要判断被转换的表达式 t.ChkVldRng，有时候它可以是非常复杂的混合表达式。

另外还需要判断是 ! 或者左右逻辑表达式。

总之翻译起来难度比较较，目前只作了基本常用的 ! 转换。

**Comment by lzy198845** [comment]
@2881099

 感谢您的耐心回答
目前我用的替代方法：(t.ChkVldRng == false || t.ChkVldRng == null )

再次感谢
