### ISSUE TITLE
数据库不建立外键关系会导致导航属性起不到作用吗

### ISSUE THREAD

**Issue by tonfy** [dotnetcore/FreeSql#376]
我按照文档设置了相关的导航属性，导航属性一直没有生效，加载不出数据，不知道还要配置什么。谢谢

**Comment by 2881099** [comment]
贴出使用代码，实体类。

如何检测一个导航属性是否配置生效：

var tbref = g.sqlite.CodeFirst
    .GetTableByEntity(typeof(T))
    .GetTableRef("Children", true);

GetTableRef(string propertyName, bool isThrow);

**Comment by tonfy** [comment]
CompanyEntity
`
		#region 外键 => 导航属性，ManyToOne/OneToOne

		[Navigate(nameof(IndustryId))]
		public virtual DictionaryEntity Industry { get; set; }

		[Navigate(nameof(RegionId))]
		public virtual DictionaryEntity Region { get; set; }

		#endregion`
你看配置是不是有问题，谢谢你的回答

**Comment by 2881099** [comment]
没问题，查询代码怎么查询的

**Comment by tonfy** [comment]
`public async Task<IResponseOutput> PageAsync(PageInput<CompanyEntity> input)
        {
            var key = input.Filter?.Name;

            var list = await _companyRepository.Select
            .WhereIf(key.NotNull(), a => a.Name.Contains(key))
            .Count(out var total)
            .OrderByDescending(true, c => c.Id)
            .Include(a => a.Industry)
            //.LeftJoin(a => a.IndustryId == a.Industry.Id)
            .Page(input.CurrentPage, input.PageSize)
            .ToListAsync();

            var data = new PageOutput<CompanyListOutput>()
            {
                List = _mapper.Map<List<CompanyListOutput>>(list),
                Total = total
            };

            return ResponseOutput.Ok(data);
        }`
LeftJoin或者Include就算不加导航属性也会有作用，所以我想在代码中不加入Include或者LeftJoin就能有值，可以吗？
你太热心了，点赞，基本有问必答，NICE!

**Comment by 2881099** [comment]
考虑某些实体类的属性可能巨复杂，目前是有使用过的才会查出来。

**Comment by tonfy** [comment]
> 考虑某些实体类的属性可能巨复杂，目前是有使用过的才会查出来。

我怎么感觉导航设置不设置都不重要一样，因为我没有设置，我用到了它照样出数据。
比如上面代码，我不用Include和LeftJoin，也不对这个实体设置导航属性。

我在ToList的时候a.Industry.Name，这样Industry照样会有数据，所以我感觉好像设置不设置的没有什么影响一样。

**Comment by 2881099** [comment]
集合属性设置后，功能多一些。

导航属性设置后，不用每次都自己增加关联条件。
