### ISSUE TITLE
建议支持System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedAttribute特性

### ISSUE THREAD

**Issue by liuguiyou** [dotnetcore/FreeSql#378]
例如：
fsql.Aop.ConfigEntityProperty += (s, e) =>{
var generatedAttr = e.Property.GetCustomAttribute<System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedAttribute>(false);
                if (generatedAttr != null)
                {
                    if (generatedAttr.DatabaseGeneratedOption == System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)
                    {
                        e.ModifyResult.IsIdentity = true;
                    }
                    else
                    {
                        e.ModifyResult.CanInsert = false;
                        e.ModifyResult.CanUpdate = false;
                    }
                }
}

**Comment by 2881099** [comment]
确认一下，这样设置 aop 行为和 efcore 是一致的吗

**Comment by liuguiyou** [comment]
实际项目中这样写没发现问题
