### ISSUE TITLE
无法连接带密码的Sqlite数据库。

### ISSUE THREAD

**Issue by tchivs** [dotnetcore/FreeSql#379]
```c#
        static IFreeSql fsql = new FreeSql.FreeSqlBuilder()
            .UseConnectionString(FreeSql.DataType.Sqlite, @"Data Source=xxxr.db;Password=123;")
            .UseAutoSyncStructure(true) //自动同步实体结构到数据库
            .Build(); //请务必定义成 Singleton 单例模式
```
运行时提示
--- Cannot use "Password" connection string property: library was not built with encryption support, please see "https://www.sqlite.org/see" for more information

隔壁sugarSql可以连接，但是我好想用freesql，有没有好的办法呢。

**Comment by 2881099** [comment]
这个有版权问题，可以自己编译 sqlite 来使用。

默认支持密码方式，因为要付费。

**Comment by tchivs** [comment]
> 这个有版权问题，可以自己编译 sqlite 来使用。
> 
> 默认支持密码方式，因为要付费。

好的，我自己下载源码编译了一个可以用了
