### ISSUE TITLE
建议ISelect<T>接口增加ThenBy()方法和ThenByDescending()方法

### ISSUE THREAD

**Issue by StarryLibra** [dotnetcore/FreeSql#380]
由于ISelect接口缺少ThenBy()方法和ThenByDescending()方法，故如果使用LINQ表达式时，则orderby后面只能有一个排序项，不能添加多个排序项，对于使用LINQ表达式的话很不友好。

例如语句：
// IFreeSql fsql = new FreeSql.FreeSqlBuilder() ....
var q = from item in fsql.Queryable<CollecionEle>()
             where item.Col0 == true
             orderby item.Col1, item.Col2 descending
             select item;
将会提示：**未能找到源类型"ISelect<CollecionEle>"的查询模式的实现。未找到"ThenByDescending"。**

**Comment by 2881099** [comment]
这就蛋疼了，确实没测试到这个，我们的设计是 OrderBy(..).OrderBy(..)

收到，我们会在 FreeSql.Extensions.Linq 增加扩展方法

https://github.com/dotnetcore/FreeSql/blob/master/FreeSql.Tests/FreeSql.Tests/Linq/ISelectLinqToSqlTests.cs

**Comment by 2881099** [comment]
1.7.0-preview0718 版本已发布到 nuget
