### ISSUE TITLE
IsNullable 为false 时 能否对Entity值为null的字段 插入默认值？

### ISSUE THREAD

**Issue by pjy612** [dotnetcore/FreeSql#384]
如果是 字符串 就插入 ""
数字就插入 0 ？

**Comment by 2881099** [comment]
是的，比如 int 的话本身 isnullable false。
int? 的话本身 isnullable true。

isnullable 基本对 string 才有必要设置

**Comment by pjy612** [comment]
因为有string 设了非空 但是insert的时候还是插了null 。所以问问要怎么设置

**Comment by 2881099** [comment]
哦，你在说默认值。

isnullable 目前主要是给 codefirst 建表

**Comment by pjy612** [comment]
其实就是 CodeFirst 设置为 非空 字段时。
如果 插入时数据为没给实体对应字段赋值 是否能 自动对应位置插入空字符串？

**Comment by 2881099** [comment]
> 其实就是 CodeFirst 设置为 非空 字段时。
> 如果 插入时数据为没给实体对应字段赋值 是否能 自动对应位置插入空字符串？

这个优化，在 v1.8.0 上做好了

其实用 fsql.Aop.AuditValue 也可以拦截 null 值。

**Comment by pjy612** [comment]
Thanks♪(･ω･)ﾉ

**Comment by netssfy** [comment]
@2881099 额，请问这null自动转default的功能可以disable掉嘛。我觉得这个功能无意间打破了数据库的约束。因为null和空字符串其实语义上是不一样的，如果ORM自动做了这个转换而不是报错的话，相当于做了业务代码做的事情了。
想要把null和空字符串或者default值做mapping，应该是业务代码的事情，可以用AOP显示的去处理
