### ISSUE TITLE
更新实体-对比快照时的变化的问题

### ISSUE THREAD

**Issue by alenliao** [dotnetcore/FreeSql#385]
你好，根据示例：
var repo = fsql.GetRepository<Topic>();
var item = new Topic { Id = 1 };
repo.Attach(item); //此时快照 item
item.Title = "newtitle";
repo.Update(item); //对比快照时的变化
//UPDATE `tb_topic` SET `Title` = ?p_0
//WHERE (`Id` = 1)

若属性类型为int，则默认值会是0，当我想更新该属性为0的时候，要怎么处理？按照示例，我这边修改不了为0.

**Comment by 2881099** [comment]
是有这个问题，先查询再对比更新？说说你的看法

**Comment by alenliao** [comment]
如果是数字类型的，比如int/decimal等，不对比，直接更新。这样可好？

**Comment by alenliao** [comment]
我之前是先查出来，给属性赋值，再更新的，但因为可能变化的属性太多，有20多个，所以看到对比快照的方法就用了，发现有改为0不变化的问题。或许先查出来再对比更新才是最稳妥的。

**Comment by 2881099** [comment]
看起来，Attach适合指定更新，未知变化的属性默认值不能对比

**Comment by 2881099** [comment]
Attach 后，手工明确更新 status title 两个字段是可以的。

**Comment by alenliao** [comment]
NPOCO的更新感觉用得挺顺手的。
await _orderRepository.UpdateAsync(order, o => o.id == order.id, o => new { o.status });
实体,更新条件,更新的字段。
我们的freesql能不能也重载一个这样的方法？

**Comment by 2881099** [comment]
repo.UpdateDiy 这个 IUpdate 玩法很多
