### ISSUE TITLE
System.Data.SQLite 版本不一致

### ISSUE THREAD

**Issue by meesii** [dotnetcore/FreeSql#389]
未能加载文件或程序集“System.Data.SQLite, Version=1.0.112.1, Culture=neutral, PublicKeyToken=db937bc2d44ff139”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。

System.Data.SQLite.Core 1.0.112.1版本已经找不到了，但是FreeSql要求112版本。

**Comment by 2881099** [comment]
https://www.nuget.org/packages/System.Data.SQLite.Core/1.0.112.1

隐藏了，但是还能访问

**Comment by meesii** [comment]
安装不了112.1，提前至少要求112.2。但是运行时却需要112.1。最终解决版本是使用fsql1.4版本。

**Comment by 2881099** [comment]
看上去是 dll 版本冲突问题，freesql.provider.* 默认引用最新的 adonet 版本，如果项目内也引用了那个 adonet，并且版本低于 freesql.provider.*，就会出现这个情况。

**Comment by 2881099** [comment]
解决办法：

1、升级以及项目中的 adonet，保证一致

2、降低 freesql.provider.* 里面的 adonet 版本，保证一致，这个需要改源码编译

**Comment by 2881099** [comment]
1.7.0 将依赖 System.Data.SQLite.Core 1.0.113.1

**Comment by meesii** [comment]
非常感谢~！
