### ISSUE TITLE
变量参数没赋值绑定

### ISSUE THREAD

**Issue by changzhuan** [dotnetcore/FreeSql#390]
UseGenerateCommandParameterWithLambda为true后  GroupBy的Count查询，变量参数没赋值绑定
![image](https://user-images.githubusercontent.com/53025994/88512334-ff587080-d018-11ea-9ae6-ac94ef9c3cbe.png)

**Comment by 2881099** [comment]
麻烦附上：FreeSqlBuilder 初始化代码，实体类代码，查询代码

**Comment by changzhuan** [comment]
FreeSql 1.5.0
初始化代:
IFreeSql freeSql = new FreeSql.FreeSqlBuilder()
                        .UseConnectionString(FreeSql.DataType.Oracle, connectionStrings.DefaultConnection) 
                       .UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper)
                       .UseGenerateCommandParameterWithLambda(true)
                        .UseMonitorCommand(cmd =>
                          LogHelper.Debug(cmd.CommandText)
                        )
                        .Build();
实体类代码:
[Table(Name = "V_HospitalReport")]
    public class V_HospitalReport
    { 
        [Column(Name = "hospital_name")]
        public string HospitalName { get; set; }
      
        [Column(Name = "dep")]
        public string Dep { get; set; }
    
        [Column(Name = "instrna")]
        public string Instrna { get; set; }
   
        [Column(Name = "confirm_doctor_name")]
        public string ConfirmDoctorName { get; set; }
       
        [Column(Name = "Scheduled_Dttm")]
        public DateTime ScheduledDttm { get; set; } 
    }
查询代码:

 freeSql.Select<V_HospitalReport>() .Where(a => a.ScheduledDttm.Date >= startTime.Date
                && a.ScheduledDttm.Date <= (endTime.AddDays(1)).Date).GroupBy(a =>
              new
              {
                  a.HospitalName,
                  a.Dep,
                  a.Instrna,
                  a.ConfirmDoctorName,
                  a.ScheduledDttm.Date
              }).CountAsync();

**Comment by changzhuan** [comment]
ToListAsync方法变量有绑定，就是CountAsync()方法会没有

**Comment by 2881099** [comment]
```sql
select count(1) from (SELECT 1 as1 
FROM "V_HOSPITALREPORT" a 
WHERE (trunc(a."SCHEDULED_DTTM") >= trunc(to_timestamp('2020-07-27 19:41:01.869246','YYYY-MM-DD HH24:MI:SS.FF6')) AND trunc(a."SCHEDULED_DTTM") <= trunc((to_timestamp('2020-07-27 19:41:01.869247','YYYY-MM-DD HH24:MI:SS.FF6')+1))) 
GROUP BY a."HOSPITAL_NAME", a."DEP", a."INSTRNA", a."CONFIRM_DOCTOR_NAME", trunc(a."SCHEDULED_DTTM")) fta
```

我这边运行没有报错，输出的 sql 是上面的

**Comment by changzhuan** [comment]
我开启了UseGenerateCommandParameterWithLambda，输出的sql是
select count(1) from (SELECT 1 as1 
FROM "V_HOSPITALREPORT" a 
WHERE (trunc(a."SCHEDULED_DTTM") >= trunc(:exp_0) AND trunc(a."SCHEDULED_DTTM") <= trunc((:exp_1+1))) 
GROUP BY a."HOSPITAL_NAME", a."DEP", a."INSTRNA", a."CONFIRM_DOCTOR_NAME", trunc(a."SCHEDULED_DTTM") 
ORDER BY a."HOSPITAL_NAME" DESC) fta

**Comment by changzhuan** [comment]
CountAsync()方法里面没有变量
![image](https://user-images.githubusercontent.com/53025994/88539103-32175e80-d043-11ea-9873-1e3689bbac12.png)
ToListAsync方法里面变量有绑定 
![image](https://user-images.githubusercontent.com/53025994/88539168-53784a80-d043-11ea-879f-6ee57891ea51.png)

**Comment by 2881099** [comment]
1.7.0 nuget 上面发布好了

**Comment by changzhuan** [comment]
谢了
