### ISSUE TITLE
Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'

### ISSUE THREAD

**Issue by johnny-l-wong** [dotnetcore/FreeSql#391]
Hi Team, I have a problem as below:
The exception  is encountered when the project references both DotNetCore.CAP.SqlServer.dll and FreeSql.Provider.SqlServer.dll

![image](https://user-images.githubusercontent.com/8088858/88522538-11daa600-d029-11ea-9a90-407edb4c436e.png)
![image](https://user-images.githubusercontent.com/8088858/88522882-a04f2780-d029-11ea-942c-62cdfd4e6958.png)

**Comment by 2881099** [comment]
试试把 FreeSqlBuilder

UseConnectionString 

换成 

UseConnctionFactory(DataType.SqlServer, ()=> new Microsoft.Data.SqlClient.SqlConnection(str))

**Comment by 2881099** [comment]
别试了，不行，我正在把 System.Data.SqlClient 改为 Microsoft.Data.SqlClient，等待发布 nuget 包

**Comment by johnny-l-wong** [comment]
Thanks, I tried , got same error when change to UseConnectionFactory(DataType.SqlServer, () => new Microsoft.Data.SqlClient.SqlConnection(str))
![image](https://user-images.githubusercontent.com/8088858/88536447-69cfd780-d03e-11ea-81b1-0382b5719b72.png)

**Comment by 2881099** [comment]
v1.7.0 发布到 nuget 上了
