### ISSUE TITLE
升级到1.7版本后报错呢

### ISSUE THREAD

**Issue by pccai** [dotnetcore/FreeSql#392]
2020-07-28 23:00:11.9095|Error|12> mscorlib System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。“Microsoft.Data.SqlClient.TdsParser”的类型初始值设定项引发异常。
   在 FreeSql.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   在 FreeSql.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   在 FreeSql.SqlServer.SqlServerProvider`1..ctor(String masterConnectionString, String[] slaveConnectionString, Func`1 connectionFactory)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Activator.CreateInstance(Type type, Object[] args)
   在 FreeSql.FreeSqlBuilder.Build[TMark]()
   在 FreeSql.FreeSqlBuilder.Build()

使用MSSQL, 和1.6的FreeSqlBuilder() 有差异？
tks。

**Comment by 2881099** [comment]
引用的 adonet 驱动变化了，1.7.0之前是 system.data.sqlclient

1.7.0 引用的是 microsoft.data.sqlclient

https://github.com/dotnetcore/FreeSql/issues/382

**Comment by 2881099** [comment]
你的项目类型是 .net core 吗，是什么版本？

我这边单元测试通过了才发布的。

检查一下项目没引用的 adonet 是什么版本，可能是版本冲突。
