### ISSUE TITLE
分表时的索引问题

### ISSUE THREAD

**Issue by chukaif** [dotnetcore/FreeSql#393]
在对使用Index指定索引的表进行分表操作时，由于索引名称是固定的，因此在创建表时会出现已存在相同索引名称的问题，导致索引无法被创建，请问该如何解决此问题?
![image](https://user-images.githubusercontent.com/50015178/88901793-d851a700-d283-11ea-9ba5-13d7679a8a40.png)

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/366

[Index("{tablename}_idx_01", "name")]

**Comment by chukaif** [comment]
thank you，this solved my problem，I suggest that you write these into the documentation。

**Comment by chukaif** [comment]
> #366
> 
> [Index("{tablename}_idx_01", "name")]

thank you，this solved my problem，I suggest that you write these into the documentation。

**Comment by 2881099** [comment]
文档上补充好了，谢谢提醒
