### ISSUE TITLE
InsertOrUpdate 支持忽略 IgnoreColumns 吗？

### ISSUE THREAD

**Issue by 1haoyu** [dotnetcore/FreeSql#394]
InsertOrUpdate 支持忽略 IgnoreColumns 吗？

**Comment by 2881099** [comment]
v1.8.0 - 补充 fsql.InsertOrUpdate UpdateColumns 数据存在时只更新指定的字段；

只能针对数据存在时的更新设置。方向不一样，但也能达到忽略的效果。

当下的版本如果实体特性有 CanUpdate = false 不会进行更新。

**Comment by 2881099** [comment]
提示： fsql.InsertOrUpdate UpdateColumns 功能已经做好了，未发布
