### ISSUE TITLE
从1.3.5升级到1.7.0后报错，Ado.ExecuteNonQuery(CommandType.Text, stb.ToString(), paramList.ToArray());

### ISSUE THREAD

**Issue by Tony518** [dotnetcore/FreeSql#395]
你好，
我从1.3.5升级到1.7.0后，Ado.ExecuteNonQuery(CommandType.Text, stb.ToString(), paramList.ToArray());这一句一直报错，paramList中是有值的，在1.3.5是运行正常的
报错内容：SqlParameterCollection only accepts non-null SqlParameter type objects, not DBNull objects

**Comment by 2881099** [comment]
是不是 FreeSql.Provider.Sqlserver

1.6.0 会报错吗

1.7.0 换了 adonet 驱动包，Microsoft.Data.SqlClient

**Comment by Tony518** [comment]
是的，
1.6.0的没有试，我暂时已经先回到1.3.5了

**Comment by 2881099** [comment]
估计是跟改 adonet 驱动的机制有关，方便的话试下1.6.0

**Comment by 2881099** [comment]
可能很 paramList 里面的值有关，看是不是有 null，应该改成 DbNull.Value

**Comment by Tony518** [comment]
好的，谢谢，我先试下，有结果通知您

**Comment by Tony518** [comment]
我试了1.6.0的确是可以的， paramList中没有为null的

**Comment by 2881099** [comment]
Microsoft.Data.SqlClient 这个是微软推荐的新库。必须要换的。

可以去他的 github 搜索错误描述，看有没有相关回复。

**Comment by Tony518** [comment]
好的，谢谢

**Comment by 2881099** [comment]
如果用 System.Data.SqlClient 执行命令时，

传入的 DbParameter 类型是 Microsoft.Data.SqlClient.SqlParameter 类型就会报这个错误。

例如在使用 System.Data.SqlClient 的实现中使用如下代码：

```c#
fsql.Ado.Query<dynamic>(
    System.Data.CommandType.Text, 
    "select * from xxx where Id = @Id",
    new Microsoft.Data.SqlClient.SqlParameter("Id", 1)
);
```

另外，可以不使用具体的参数化类型传递，如下：

```c#
fsql.Ado.Query<dynamic>(
    "select * from xxx where Id = @Id",
    new { id = 1 }
);

// 或者

fsql.Ado.Query<dynamic>(
    "select * from xxx where Id = @Id",
    new Dictionary<string, object> { ["id"] = 1 }
);
```

#401

**Comment by Tony518** [comment]
感谢大佬，厉害啊
