### ISSUE TITLE
升到1.7之后，无法运行了

### ISSUE THREAD

**Issue by gwhzh21** [dotnetcore/FreeSql#398]
主要的问题是，当我使用了独立发布之后，运行不起来了。我觉得应该不能在此提这个问题
我的配置是
.net core 3.1
独立
win-64
然后运行exe，会提示。
An assembly specified in the application dependencies manifest (BXJ.WeAppApi.deps.json) was not found:
    package: 'Microsoft.Data.SqlClient.SNI.runtime', version: '2.0.0'
    path: 'runtimes/win-x86/native/Microsoft.Data.SqlClient.SNI.pdb'
老是这个提示

**Comment by 2881099** [comment]
freesql.provider.sqlserver 1.8.0 的adonet 换成了 microsoft.data.sqlclient，写个新的 coreapp31 demo 发布试试看会不会这样。

**Comment by gwhzh21** [comment]
就是最新建的。我还还没有写数据库的一行代码。连注入的代码都没有写。

**Comment by gwhzh21** [comment]
我换成了1.6就可以了。

**Comment by 2881099** [comment]
没办法微软推荐新的 adonet，被迫换的。

因为市面上其他开源项目换了，我们不换的话交互会有问题

**Comment by gwhzh21** [comment]
那看来要去那边提问了。

**Comment by 2881099** [comment]
你先问看怎么解决，有办法的话回复到这里。

实在没办法的话，我后面发布多一个 freesql.provider.sqlserverForSystem 包

**Comment by gwhzh21** [comment]
没事，我新建一个，直接用那个。看看有没有问题。

**Comment by gwhzh21** [comment]
我已经看到了。sni加载不了。很多人报。

**Comment by gwhzh21** [comment]
遇到同样的问题，请参考此解决方案。
https://github.com/dotnet/SqlClient/issues/612

**Comment by 2881099** [comment]
<PropertyGroup>
       <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
  </PropertyGroup>
