### ISSUE TITLE
SQL语句查询参数

### ISSUE THREAD

**Issue by JHeLiu** [dotnetcore/FreeSql#399]
目前库是 SELECT * FROM TABLE WHERE ID=?ID 
可以设置类似于原本的 @符号吗？
比如
SELECT * FROM ABLE WHERE ID=@ID;

**Comment by 2881099** [comment]
换个驱动就可以了 

FreeSql.Provider.MySqlConnector 是 @

FreeSql.Provider.MySql  是 ?
