### ISSUE TITLE
建议能结合EF Core的一些特性来弄

### ISSUE THREAD

**Issue by qcjxberin** [dotnetcore/FreeSql#4]
比如能识别下面的映射表及映射主键Id

` /// <summary>
        /// 映射表
        /// </summary>
        protected override void MapTable( EntityTypeBuilder<CgKssqbs> builder ) {
            builder.ToTable( "cg_kssqbs" );
        }
        
        /// <summary>
        /// 映射属性
        /// </summary>
        protected override void MapProperties( EntityTypeBuilder<CgKssqbs> builder ) {
            //Id编号
            builder.Property(t => t.Id)
                .HasColumnName("kssqbs_id");
        }`

**Comment by qcjxberin** [comment]
有新的进展了吗？

**Comment by 2881099** [comment]
不好意思，差点忘记了

请看wiki：
https://github.com/2881099/FreeSql/wiki/CodeFirst#%E5%A4%96%E9%83%A8%E9%85%8D%E7%BD%AE%E5%AE%9E%E4%BD%93

**Comment by 2881099** [comment]
```csharp
using FreeSql.DataAnnotations;
using Xunit;

namespace FreeSql.Tests.DataAnnotations {
	public class FluentTest {
		[Fact]
		public void Fluent() {
			g.mysql.CodeFirst
				.ConfigEntity<TestFluenttb1>(a => {
					a.Name("xxdkdkdk1").SelectFilter("a.Id22 > 0");
					a.Property(b => b.Id).Name("Id22").IsIdentity(true);
					a.Property(b => b.name).DbType("varchar(100)").IsNullable(true);
				})
				.ConfigEntity<TestFluenttb2>(a => {
					a.Name("xxdkdkdk2").SelectFilter("a.Idx > 0");
					a.Property(b => b.Id).Name("Id22").IsIdentity(true);
					a.Property(b => b.name).DbType("varchar(100)").IsNullable(true);
				});

			var ddl1 = g.mysql.CodeFirst.GetComparisonDDLStatements<TestFluenttb1>();
			var ddl2 = g.mysql.CodeFirst.GetComparisonDDLStatements<TestFluenttb2>();

			var t1id = g.mysql.Insert<TestFluenttb1>().AppendData(new TestFluenttb1 { }).ExecuteIdentity();
			var t1 = g.mysql.Select<TestFluenttb1>(t1id).ToOne();

			var t2lastId = g.mysql.Select<TestFluenttb2>().Max(a => a.Id);
			var t2affrows = g.mysql.Insert<TestFluenttb2>().AppendData(new TestFluenttb2 { Id = t2lastId + 1 }).ExecuteAffrows();
			var t2 = g.mysql.Select<TestFluenttb2>(t2lastId + 1).ToOne();
		}
	}

	class TestFluenttb1 {
		public int Id { get; set; }

		public string name { get; set; } = "defaultValue";
	}

	[Table(Name = "cccccdddwww")]
	class TestFluenttb2 {
		[Column(Name = "Idx", IsPrimary = true, IsIdentity = false)]
		public int Id { get; set; }

		public string name { get; set; } = "defaultValue";
	}
}
```
这是测试代码，目前已经发布了

**Comment by qcjxberin** [comment]
/// <summary>
        /// 映射表
        /// </summary>
        protected override void MapTable( EntityTypeBuilder<Auth> builder ) {
            builder.ToTable( "auth" );
        }
        
        /// <summary>
        /// 映射属性
        /// </summary>
        protected override void MapProperties( EntityTypeBuilder<Auth> builder ) {
            //Id编号
            builder.Property(t => t.Id)
                .HasColumnName("id");
        }
有研究过这一类的吗？

**Comment by 2881099** [comment]
目前设定方法名和Attribute是一样的，看上去比较尬，哈哈

**Comment by qcjxberin** [comment]
有办法改进支持一下吗？我想将你的这个框架和我们现在的系统结合起来用

**Comment by qcjxberin** [comment]
具体你可以看一下Util这个开源项目

**Comment by 2881099** [comment]
正好昨天在看util

![image](https://user-images.githubusercontent.com/16286519/52764803-7fc12680-305c-11e9-8f39-61e5bce77990.png)

是兼容这一段吗？

**Comment by qcjxberin** [comment]
是的，因为目前实体没法共用，会提示找不到字段

**Comment by 2881099** [comment]
可否方便发一些实体+map demo 作参考

**Comment by 2881099** [comment]
邮箱：2881099@qq.com

**Comment by qcjxberin** [comment]
我们这主要也就是主键Id字段的名字会不一样。你可以直接在Util的Demo基础上实现功能就能满足需求了。

**Comment by 2881099** [comment]
```csharp
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace FreeSql.Extensions.EFCoreModelBuilder {

	public static class CodeFirstExtensions {

		public static void ConfigEntity(this ICodeFirst codeFirst, ModelBuilder modelBuilder) {

			foreach (var type in modelBuilder.Model.GetEntityTypes()) {

				codeFirst.ConfigEntity(type.ClrType, a => {

					//表名
					var relationalTableName = type.FindAnnotation("Relational:TableName");
					if (relationalTableName != null) {
						a.Name(relationalTableName.Value?.ToString() ?? type.ClrType.Name);
					}

					foreach (var prop in type.GetProperties()) {

						var freeProp = a.Property(prop.Name);

						//列名
						var relationalColumnName = prop.FindAnnotation("Relational:ColumnName");
						if (relationalColumnName != null) {

							freeProp.Name(relationalColumnName.Value?.ToString() ?? prop.Name);
						}

						//主键
						freeProp.IsPrimary(prop.IsPrimaryKey());

						//自增
						freeProp.IsIdentity(prop.GetAnnotations().Where(z => 
							z.Name == "SqlServer:ValueGenerationStrategy" && z.Value.ToString().Contains("IdentityColumn") //sqlserver 自增
						).Any());

						//可空
						freeProp.IsNullable(prop.AfterSaveBehavior != Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Throw);

						//类型
						var relationalColumnType = prop.FindAnnotation("Relational:ColumnType");
						if (relationalColumnType != null) {

							var dbType = relationalColumnType.ToString();

							if (!string.IsNullOrEmpty(dbType)) {

								var maxLength = prop.FindAnnotation("MaxLength");
								if (maxLength != null)
									dbType += $"({maxLength})";

								freeProp.DbType(dbType);
							}
						}
					}
				});
			}
		}
	}
}
```
你先看看这段代码。使用的是扩展方法，意图将 EF ModelBuilder 对象直接配置为 FreeSql 的实体。
是否可行？代码还没上传（包括FreeSql）

**Comment by 2881099** [comment]
https://www.cnblogs.com/kellynic/p/10384165.html
在 EFCore 定义的实体中进行 FreeSql 开发

**Comment by qcjxberin** [comment]
我看看

**Comment by qcjxberin** [comment]
还需要针对每个实体来做下面这种配置吗？

fsql.CodeFirst
    .ConfigEntity<TestFluenttb1>(a => {
        a.Name("xxdkdkdk1").SelectFilter("a.Id22 > 0");
        a.Property(b => b.Id).Name("Id22").IsIdentity(true);
        a.Property(b => b.name).DbType("varchar(100)").IsNullable(true);
    })
    .ConfigEntity<TestFluenttb2>(a => {
        a.Name("xxdkdkdk2").SelectFilter("a.Idx > 0");
        a.Property(b => b.Id).Name("Id22").IsIdentity(true);
        a.Property(b => b.name).DbType("varchar(100)").IsNullable(true);
    });

**Comment by 2881099** [comment]
不需要啊，在Ef fuentapi 或onmodelcreating 配置

**Comment by qcjxberin** [comment]
有没有具体的Demo?

**Comment by 2881099** [comment]
v0.0.14
- ICodeFirst.ConfigEntity 可更新实体配置已缓存的数据；
- 防止同连接字符串被IFreeSql使用多次，发生连接池溢出bug（ado.net连接池原理，减少解释成本）；
- 增加 efcore_to_freesql 示例项目，现实与 EFCore 实体共存；

示例请见源码：
https://github.com/2881099/FreeSql/tree/master/Examples/efcore_to_freesql

在 Startup.cs 测试的，请看注释执行的SQL语句。

**Comment by 2881099** [comment]
所有 EFCore DBContext 继承 BaseDBContext

```csharp
	public class BaseDBContext : DbContext {

		public static IFreeSql Fsql { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder) {
			base.OnModelCreating(modelBuilder);
			Fsql.CodeFirst.ConfigEntity(modelBuilder.Model); //同步配置
		}
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
			optionsBuilder.UseSqlite(@"Data Source=|DataDirectory|\document.db;Pooling=true;Max Pool Size=10");
		}
	}
```

**Comment by qcjxberin** [comment]
和Util的一起使用有冲突，会导致原本的不可用。

**Comment by 2881099** [comment]
方便发个冲突小demo我的邮箱吗，2881099@qq.com

**Comment by qcjxberin** [comment]
晚点我发个Demo给你看一下。

**Comment by qcjxberin** [comment]
你可以试一下那些表名或者字段名带下划线的，一起使用的时候会导致映射的表名下拉线没有了，感觉好像没有起作用一样的。

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/53380572-ce4db980-39a8-11e9-9982-e9893f38b8d4.png)

测试了，下划线不会去掉啊。建议你还是发个demo给我

**Comment by qcjxberin** [comment]
这样直接用肯定没问题，你结合一下util使用试试。

**Comment by 2881099** [comment]
整个可运行的demo呀，我不知道util的使用习惯。

**Comment by qcjxberin** [comment]
我看了一下你的Demo，需要在Startup里配置一次数据库链接，也还需要在BaseDBContext里配置一次链接吗？

**Comment by 2881099** [comment]
只要配置一次就行，要么starup，或者basedbcontext那里

**Comment by qcjxberin** [comment]
看一下QQ

**Comment by qcjxberin** [comment]
能不能弄个单独只是基于basedbcontext的demo，我看了一下你的案例更多的是基于startup的
