### ISSUE TITLE
请问 关于MySql CodeFirst 和 FluentApi 使用时 对于 timestamp 或 其他字段 如何设置默认值？

### ISSUE THREAD

**Issue by pjy612** [dotnetcore/FreeSql#400]
timestamp 如何设置默认值为 CURRENT_TIMESTAMP 
如何追加 UPDATE CURRENT_TIMESTAMP？
特别是有多个timestamp 字段的时候
```
DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
```

**Comment by 2881099** [comment]
DbType = “datetime  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP”

**Comment by pjy612** [comment]
Thanks♪(･ω･)ﾉ
