### ISSUE TITLE
ado查询出来的datatable或者dataset如果数据行数为0不返回结构体

### ISSUE THREAD

**Issue by hvppy** [dotnetcore/FreeSql#403]
如图
![image](https://user-images.githubusercontent.com/4735951/89151542-caf23080-d593-11ea-9ac1-a9b519bf549e.png)
ado查询出来的datatable或者dataset如果数据行数为0不返回结构体,这个是有另外的设置参数吗

**Comment by 2881099** [comment]
是的，现在没记录不会返回结构

**Comment by 2881099** [comment]
v1.8.0-preview0805 已修复这个问题。

问题本身存在知道，没时间处理 Ado 相关的功能，就等人发现问题了再解决。
