### ISSUE TITLE
是否可以考虑增加对 string.Join() 方法的支持

### ISSUE THREAD

**Issue by hd2y** [dotnetcore/FreeSql#405]
代码：

```csharp
var list = freeSql.Queryable<Music>()
    .ToList((a) => new
    {
        a.Id,
        a.Name,
        Tags = string.Join(",", freeSql.Select<Tag>().Where(b => a.Id == b.MusicId).ToList(b => b.Name))
    });

public class Music
{
    [Column(IsIdentity = true)]
    public int Id { get; set; }

    public string Name { get; set; }
}

public class Tag
{
    [Column(IsIdentity = true)]
    public int Id { get; set; }

    public int MusicId { get; set; }

    public string Name { get; set; }
}
```

SQL 脚本：

```sql
-- SQLite
SELECT a.Id, a.Name, (SELECT GROUP_CONCAT(b.Name) FROM Tag b where a.Id = b.MusicId) FROM Music a;
```

其他数据库的实现：
+ PostgreSQL：https://blog.csdn.net/qq_16605855/article/details/79430491
+ MySQL：https://blog.csdn.net/zhangbingtao2011/article/details/81737925
+ SQLite3：https://blog.csdn.net/qhexin/article/details/51036541
+ SQL Server：https://www.cnblogs.com/longphui/p/4914157.html
+ Oracle：https://www.cnblogs.com/wanggang-java/p/10916191.html

**Comment by 2881099** [comment]
在考虑，何不直接在子查询里面处理，用表达式解析处理：

```c#
    .ToList((a) => new
    {
        a.Id,
        a.Name,
        Tags = freeSql.Select<Tag>().Where(b => a.Id == b.MusicId).ToFirst(b => SqlExt.GroupConcat(b.Name).Separator(",").ToValue())
    });
```

MySql 目前可以这样用，SqlExt.GroupConcat 已经实现了

**Comment by hd2y** [comment]
> 在考虑，何不直接在子查询里面处理，这样可以用在更多地方。
> 
> 用表达式解析处理：
> 
> ```cs
>     .ToList((a) => new
>     {
>         a.Id,
>         a.Name,
>         Tags = freeSql.Select<Tag>().Where(b => a.Id == b.MusicId)
>             .First(b => SqlExt.GroupConcat(b.Name).Separator(",").ToValue())
>     });
> ```
> 
> MySql 目前可以这样用，SqlExt.GroupConcat 已经实现了

其实主要在 SQL Server 中使用，目前类似的查询都还是用 SQL 来写，上面只是临时用 SQLite 写了个例子。🙂

**Comment by 2881099** [comment]
sqlserver 太蛋疼，"中国,上海,深圳," 最后的逗号很难处理。

**Comment by 2881099** [comment]
暂时只针对性的对 sqlserver 进行 string.Join + ToList 解析

```c#
fsql.Select<StringJoin01>().ToList(a => 
    string.Join(",", fsql.Select<StringJoin01>().As("b").ToList(b => b.name))
);
```

**Comment by hd2y** [comment]
> sqlserver 太蛋疼，"中国,上海,深圳," 最后的逗号很难处理。

这个忘记说了，前面引用的那个文章其实用法有问题，实际应该是把逗号放在前面，然后用 stuff 函数去处理。😂

可以参考一下：https://www.cnblogs.com/stevenjson/p/3673239.html

**Comment by 2881099** [comment]
> > sqlserver 太蛋疼，"中国,上海,深圳," 最后的逗号很难处理。
> 
> 这个忘记说了，前面引用的那个文章其实用法有问题，实际应该是把逗号放在前面，然后用 stuff 函数去处理。😂
> 
> 可以参考一下：https://www.cnblogs.com/stevenjson/p/3673239.html

不知道有这个函数，前后都试过，带会看能不能把 string.Join 一统江湖

**Comment by 2881099** [comment]
SELECT listagg(b."NAME",',') within group 
FROM "STRINGJOIN01" b

还非要在 within group 后面加 order by，有没有其他办法解决这个？

**Comment by 2881099** [comment]
> SELECT listagg(b."NAME",',') within group
> FROM "STRINGJOIN01" b
> 
> 还非要在 within group 后面加 order by，有没有其他办法解决这个？

用了一个复杂逻辑解决的，order by 延用子查询内的 .OrderBy() 或者 order by pk 或者 order by 1

**Comment by 2881099** [comment]
适配完成了，也测试了，老板验收

**Comment by hd2y** [comment]
验收不敢当，这效率只能说叶老板大气。👍🏻
