### ISSUE TITLE
请问在多连接实例的情况下，UnitOfWorkManager的注入问题

### ISSUE THREAD

**Issue by wanglantian** [dotnetcore/FreeSql#406]
![image](https://user-images.githubusercontent.com/30929803/89544346-9650d400-d834-11ea-9ecd-cc5712837f3e.png)

之前定义单实例IFreeSql没问题，现在注入了两个IFreeSql<TrainFlag> 和 IFreeSql<BIIIGFlag>,就提示"Unable to resolve service for type 'IFreeSql' while attempting to activate 'FreeSql.UnitOfWorkManager'."

想请教下这种情况下对于UnitOfWorkManager比较好的处理方式是什么？

**Comment by 2881099** [comment]
多库目前不行，主要是跨库事务不能简单这样解决，一致性有问题。所以没有提供

**Comment by 2881099** [comment]
如果不考虑一致性问题，倒是很好解决。

**Comment by wanglantian** [comment]
> 如果不考虑一致性问题，倒是很好解决。
如果不考虑跨库事务的问题，因为其中一个库只用来读。有解决方法吗...

**Comment by wanglantian** [comment]
参考了下代码首页的SASS项目，决定不注入UnitOfWork了，使用时利用IFreeSql实例创建，这样去试试

**Comment by wanglantian** [comment]
不注入UnitOfWork可以工作。只是每次用事务的时候都要创建一遍有点麻烦。可以参考下在AOP中启用事务。如果有其他好的解决方法，还期望能指教指教

**Comment by 2881099** [comment]
就是只是一个主库吗？其他库是从库？那怎么不用读写分离

**Comment by wanglantian** [comment]
不是，另一个要读的库是另一个系统的，就是读取下部分数据。

**Comment by 2881099** [comment]
统一注入主库为 IFreeSql

注入读库为 IFreeSql<TMark>，读库不要用仓储的功能查询，直接用原生的方法。

**Comment by wanglantian** [comment]
可以，这是一个较好的方法。但是感觉有点不太符合风格统一的理念。。。当前我还是决定不注入UnitOfWork,使用时自己创建。多谢指点
