### ISSUE TITLE
需求：是否可以在创建IFreeSql时有个参数可以设置默认的 schema模式 名称

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#407]
在pg中有模式的概念，官方建议是建一个同名的模式名称。建好同名模式后在使用codefisrt 建表时，默认是建在public下面的，虽然用SyncStructure时可以指定表名，或使用特性设置表名，但在使用时还是很不方便，是否可以增加一个配置项UseSchemaName，类似UseNameConvert 的形式，设置了就按照设置的来，没有就按照现有的方式来？

**Comment by hd2y** [comment]
这个问题我个人感觉是数据库授权问题，和 ORM 没太大关系。

**Comment by exy3351** [comment]
应该不是授权的问题，codefirst生成的sql语句加的模式名就是public，所以是建在pulic下了

**Comment by hd2y** [comment]
这样啊，那和我理解的不一样，平时用 Oracle 的模式多一些，所以看了 postgresql 的文章，认为和 Oracle 类似，可以通过连接串里指定用户配置对应的权限。

**Comment by 2881099** [comment]
可以在 Aop.ConfigEntity 上统一设置 ModifiyResult.Name 达到这个目的

**Comment by exy3351** [comment]
使用 ModifiyResult.Name  基本可以达到目的，但不能使用Table属性，如下面的实体对象就没法支持
 [Table(Name = "T_SJZD")]
    public class TTest2

**Comment by lxh023** [comment]
ModifiyResult.Name在表有配置Table属性的情况下，是无效的，还是建议增加一个配置项，类似UseSchemaName，类似UseNameConvert 的这种

**Comment by lxh023** [comment]
> > ModifiyResult.Name在表有配置Table属性的情况下，是无效的，还是建议增加一个freesqlbuilder配置项，类似UseSchemaName，类似UseNameConvert 的这种，就很方便了。因为实际场景，可能不同数据库的模式不一样。如postgresql默认为public
> 
> 这是优先级问题，可以设置的。
> 
> 指定表名的几种方法，优先级从小到大：
> 
> ```cs
> 1、实体类名
> 2、Aop fsql.Aop.ConfigEntity += (_, e) => e.ModifyResult.Name = "public.tabname"
> 3、FluentApi fsql.CodeFirst.ConfigEntity(a => a.Name("public.tabname"))
> 4、[Table(Name = "public.tabname")]
> 5、AsTable fsql.Select<T>().AsTable((_, old) => "public.tabname").ToList()
> ```
> 
> v3.2.660 可通过 FreeSqlBuilder().UseMappingPriority( 调整 2 3 4 优先级

---------------------------------------------------------------------------
刚试了，测试可以，就是把Aop的优先级调低即可，大佬牛逼。
附上我测试的关键代码:

IFreeSql freesql=FreeSqlBuilder()
...
.UseMappingPriority(MappingPriorityType.Attribute,MappingPriorityType.FluentApi,MappingPriorityType.Aop)
...
----
freesql.Aop.ConfigEntity+=(s,e)=>{
   if(!e.ModifyResult.Name.Contains("."))
      e.ModifyResult.Name="xxxxx."+e.ModifyResult.Name; ///xxxxx就是你的数据模式名称
}
---
[Table(Name="flow_model_cfg")]
public class FlowModelCfg {...}

**Comment by lxh023** [comment]
<pre>
IFreeSql freesql=FreeSqlBuilder()
...
.UseMappingPriority(MappingPriorityType.Attribute,MappingPriorityType.FluentApi,MappingPriorityType.Aop)
...
---------------------------------------------------------------------------------
freesql.Aop.ConfigEntity+=(s,e)=>{
   if(!e.ModifyResult.Name.Contains("."))
      e.ModifyResult.Name="xxxxx."+e.ModifyResult.Name; ///xxxxx就是你的数据模式名称
}
---------------------------------------------------------------------------------
[Table(Name="flow_model_cfg")]
public class FlowModelCfg {...}</pre>

但是这段代码执行后，[Table(Name="flow_model_cfg")] 就没有生效了，变成按类名来创建表

**Comment by lxh023** [comment]
现在只能自己建一个表的特性去折中实现了，参考
https://github.com/dotnetcore/FreeSql/wiki/自定义特性
<pre>
freesql.Aop.ConfigEntity += (s, e) =>
            {
                //修改默认的模式名称，默认为public
          
                var attr=e.EntityType.GetCustomAttributes(typeof(MyTableAttribute), false).FirstOrDefault() as MyTableAttribute;
                if (attr != null)
                    e.ModifyResult.Name = "xxxxx."+attr.TableName; //自定义特性表名

                //if (!e.ModifyResult.Name.Contains("."))
                //    e.ModifyResult.Name = "xxxxx." + e.ModifyResult.Name;
                //System.Console.WriteLine(e.ModifyResult.Name);
            };
----------------------------------------------------------
[MyTable(TableName = "flow_model_cfg")]
[Table(Name="flow_model_cfg")]
public class FlowModelCfg {...}
----------------------------------------------------------
 public class MyTableAttribute:System.Attribute
    {
        public string TableName { get; set; }
   }
</pre>

**Comment by 2881099** [comment]
> IFreeSql freesql=FreeSqlBuilder()
> ...
> .UseMappingPriority(MappingPriorityType.Attribute,MappingPriorityType.FluentApi,MappingPriorityType.Aop)
> ...
> ---------------------------------------------------------------------------------
> freesql.Aop.ConfigEntity+=(s,e)=>{
>    if(!e.ModifyResult.Name.Contains("."))
>       e.ModifyResult.Name="xxxxx."+e.ModifyResult.Name; ///xxxxx就是你的数据模式名称
> }
> ---------------------------------------------------------------------------------
> [Table(Name="flow_model_cfg")]
> public class FlowModelCfg {...}
> 但是这段代码执行后，[Table(Name="flow_model_cfg")] 就没有生效了，变成按类名来创建表。 用[Table(Name="xxxxxx.flow_model_cfg")] 可以。希望还是能有一个统一设置数据模式的地方

```c#
freesql.Aop.ConfigEntity+=(s,e)=>{
    var name = e.EntityType.GetCustomAttribute<TableAttribute>()?.Name ?? e.EntityType.Name;
    if (name.Contains(".") == false)
        e.ModifyResult.Name="xxxxx." + name;
}
```

**Comment by lxh023** [comment]
> > ## IFreeSql freesql=FreeSqlBuilder()
> > ...
> > .UseMappingPriority(MappingPriorityType.Attribute,MappingPriorityType.FluentApi,MappingPriorityType.Aop)
> > ...
> > ## freesql.Aop.ConfigEntity+=(s,e)=>{
> > if(!e.ModifyResult.Name.Contains("."))
> > e.ModifyResult.Name="xxxxx."+e.ModifyResult.Name; ///xxxxx就是你的数据模式名称
> > }
> > [Table(Name="flow_model_cfg")]
> > public class FlowModelCfg {...}
> > 但是这段代码执行后，[Table(Name="flow_model_cfg")] 就没有生效了，变成按类名来创建表。 用[Table(Name="xxxxxx.flow_model_cfg")] 可以。希望还是能有一个统一设置数据模式的地方
> 
> ```cs
> freesql.Aop.ConfigEntity+=(s,e)=>{
>     var name = e.EntityType.GetCustomAttribute<TableAttribute>()?.Name ?? e.EntityType.Name;
>     if (name.Contains(".") == false)
>         e.ModifyResult.Name="xxxxx." + name;
> }
> ```

实体特性是生效的，但是对FluentApi就不生效了，具体请看一下图
![Snipaste_2022-09-16_12-17-03](https://user-images.githubusercontent.com/8578755/190556035-04d4b226-41fa-4e03-9228-a310377ac0a8.png)

**Comment by 2881099** [comment]
freesql.Aop.ConfigEntity+=(s,e)=>{
    var name = e.EntityType.GetCustomAttribute<TableAttribute>()?.Name ?? //特性
        freesql.CodeFirst.GetConfigEntity(e.EntityType))?.Name ?? //FluentApi
        e.EntityType.Name;
    if (name.Contains(".") == false)
        e.ModifyResult.Name="xxxxx." + name;
};
