### ISSUE TITLE
InsertOrUpdate  无法保存 二进制 对象

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#409]
InsertOrUpdate  无法保存 二进制 对象，insert 、update以参数化的方式是可以的，是否可以在InsertOrUpdate 开放自定义是以参数化还是非参数化的方式执行？

**Comment by 2881099** [comment]
问题解决了，用 NoneParameter 做一般类型，特殊类型使用 DbParameter 混合一起执行。

1.8.0-preview0811
