### ISSUE TITLE
几种使用方式的性能有差异吗

### ISSUE THREAD

**Issue by liuyl1992** [dotnetcore/FreeSql#410]
要么FreeSql，原始用法；
要么FreeSql.Repository，仓储+工作单元习惯；
要么FreeSql.DbContext，有点像efcore的使用习惯；
要么FreeSql.BaseEntity，求简单使用这个；

几种使用方式的性能有差异吗，差异是多大呢，
如果是多数据库场景(可能很多)更推荐哪一种呢，又不会影响太大性能

**Comment by 2881099** [comment]
性能都差不多，原始用法没有状态管理，其他几种都有。

状态管理不适合大批量数据查询。
