### ISSUE TITLE
在Oracle中 Update 更新指定列报字符集不匹配的问题

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#411]
使用CodeFirst 根据实体建表
 [Description("检查结果表")]
    public class T_CHECK_RESULT
    {
[Column(StringLength = 64, IsNullable = false, IsPrimary = true)]
        [Description("编号")]
        public string ID { get; set; } = Guid.NewGuid().ToString();

/// <summary>
        /// 执行是否成功
        /// </summary>
        [Description("是否执行成功")]
        public bool Success { get; set; }

}

更新指定的列
var fsqlCheck = FreeSqlFactory.GetFreeSql(CheckDbinfo);
                    fsqlCheck?.Update<T_CHECK_RESULT>()
                        .SetSource(results)
                        .UpdateColumns(t => new {t.Success})
                        .ExecuteAffrows();

执行时报 ：ORA-12704: character set mismatch 

打印的Sql语句  UPDATE "T_CHECK_RESULT" 
SET "SUCCESS" =
CASE
		"ID" 
		WHEN '0d76013c-7c39-4b66-91d3-f8efcc961fc3' THEN
		0 
		WHEN '67abbcfe-b646-41a9-b853-3eb49aa7e52b' THEN
		0 
		WHEN 'e35cd4cb-0836-4413-b241-fd9aded4da20' THEN
		1 
	END 
WHERE
	( "ID" IN ( '0d76013c-7c39-4b66-91d3-f8efcc961fc3', '67abbcfe-b646-41a9-b853-3eb49aa7e52b', 'e35cd4cb-0836-4413-b241-fd9aded4da20' ) )

**Comment by 2881099** [comment]
把sql语句提出去执行测试，怎么调才是正确

**Comment by exy3351** [comment]
可执行的Sql语句：

UPDATE "T_CHECK_RESULT" 
SET "SUCCESS" =
CASE
		"ID" 
		WHEN N'0d76013c-7c39-4b66-91d3-f8efcc961fc3' THEN
		0 
		WHEN N'67abbcfe-b646-41a9-b853-3eb49aa7e52b' THEN
		0 
		WHEN N'e35cd4cb-0836-4413-b241-fd9aded4da20' THEN
		1 
	END 
WHERE
	( "ID" IN ( '0d76013c-7c39-4b66-91d3-f8efcc961fc3', '67abbcfe-b646-41a9-b853-3eb49aa7e52b', 'e35cd4cb-0836-4413-b241-fd9aded4da20' ) )

加了一个 N
