### ISSUE TITLE
需求：WithSql希望能参数化，谢谢！

### ISSUE THREAD

**Issue by ycqhg** [dotnetcore/FreeSql#413]
在很多场景下需要针对传入的条件进行参数化查询，需要根据条件空与否来进行拼装Parameter，比如：
var where = "";
if(name != "" && age > 0)
{
  where ="where Name=@Name and Age=@Age";
}
var sql = $“select * from tb {where}”;
**希望能重载WithSql增加一个参数：**
**ISelect<T1> ISelect<T1>.WithSql(string sql, [object parms = null]);**
**示例：
WithSql("select * from tb where Name=@Name and Age=@Age", new {Name="aaa", Age=22});
并且parms参数还可以传Dictionary<string, object>**

**Comment by 2881099** [comment]
1.8.0-preview0811 十分钟后可以下载
