### ISSUE TITLE
导航属性是否支持非主键的自定义字段进行关联

### ISSUE THREAD

**Issue by wf-soft** [dotnetcore/FreeSql#415]

**Comment by 2881099** [comment]
不能，非主键配置起来麻烦，失去了易用的特性。

不过，导航属性 IncludeMany 功能可以不配置关联，贪婪加载 文档中 有讲解。

**Comment by wf-soft** [comment]
@2881099 噢噢，不错我研究一下

**Comment by ThreeLambs** [comment]
如果不需要IncludeMany ，直接Leftjoin就好了。
如果需要IncludeMany ，再建一个相同实体（名字不同）设置主键为你想要关联的字段 ，就可以了 。方法总比困难多!

**Comment by 2881099** [comment]
see #604

**Comment by 2881099** [comment]
最新报道

非主键关联：https://github.com/dotnetcore/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb

https://freesql.net/guide/navigate-attribute.html
