### ISSUE TITLE
Mysql添加数据时产生异常

### ISSUE THREAD

**Issue by liuguiyou** [dotnetcore/FreeSql#416]
添加数据时产生异常，是DateTimeOffset类型导致的

MySql数据库
使用FreeSql.Provider.MySqlConnector

An unhandled exception occurred while processing the request.
MySqlException: Field 'create_time' doesn't have a default value
MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in ResultSet.cs, line 49

MySqlException: Field 'create_time' doesn't have a default value
MySqlConnector.MySqlDataReader.ActivateResultSet() in MySqlDataReader.cs, line 124

Exception: Field 'create_time' doesn't have a default value
FreeSql.MySql.Curd.MySqlInsert<T1>.RawExecuteIdentityAsync()

代码
var id = await freeSql.Insert<Brand>(new Brand()
            {
                Name = "测试",
                Description = "测试",
                Logo = "",
                CreateTime = DateTime.UtcNow,
                SourceFrom = "测试",
                SourceUrl = "",
                UpdateTime = null,
                SourceId = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString(),
                SortNo = 1,
                State = 1
            }).ExecuteIdentityAsync();

表定义
CREATE TABLE `brand` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '品牌名称',  `state` int(11) NOT NULL DEFAULT '1' COMMENT '数据状态1=有效,0=无效',  `sort_no` int(11) NOT NULL DEFAULT '0' COMMENT '排序号',  `description` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '描述',  `source_from` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '来源(如autohome)',  `source_id` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '来源id',  `source_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '来源url',  `logo` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '品牌logo',  `create_time` datetime NOT NULL,  `update_time` datetime DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=361 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='品牌'

实体类定义
public class Brand
    {

        /// <summary>
        /// 品牌Id
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("id")]
        [DataMember(Order = 0)]
        public int Id { get; set; } = 0;
        /// <summary>
        /// 名称 中文名+空格+(英文名)
        /// </summary>
        [Column("name")]
        [DataMember(Order = 1)]
        [StringLength(200)]
        public string Name { get; set; } = string.Empty;
        /// <summary>
        /// 描述
        /// </summary>
        [Column("description")]
        [DataMember(Order = 2)]
        [StringLength(8000)]
        public string Description { get; set; } = string.Empty;
        /// <summary>
        /// logo
        /// </summary>
        [Column("logo")]
        [DataMember(Order = 3)]
        [StringLength(500)]
        public string Logo { get; set; } = string.Empty;

        /// <summary>
        /// 添加时间
        /// </summary>
        [Column("create_time")]
        [DataMember(Order = 6)]
        public DateTimeOffset CreateTime { get; set; } = DateTime.UnixEpoch;
        /// <summary>
        /// 数据状态
        /// </summary>
        [Column("state")]
        [DataMember(Order = 7)]
        public int State { get; set; } = 0;
        /// <summary>
        /// 来源Id
        /// </summary>
        [Column("source_id")]
        [DataMember(Order = 9)]
        public string SourceId { get; set; } = "";
        /// <summary>
        /// 排序号
        /// </summary>
        [Column("sort_no")]
        [DataMember(Order = 13)]
        public int SortNo { get; set; } = 0;
        /// <summary>
        /// 更新时间
        /// </summary>
        [Column("update_time")]
        [DataMember(Order = 15)]
        public DateTimeOffset? UpdateTime { get; set; }
        /// <summary>
        /// url路径名
        /// </summary>
        [Column("source_from")]
        [DataMember(Order = 16)]
        [StringLength(160)]
        public string SourceFrom { get; set; } = string.Empty;
        /// <summary>
        /// 品牌所有权类型1=自有,2=第三方授权
        /// </summary>
        [Column("source_url")]
        [DataMember(Order = 17)]
        public string SourceUrl { get; set; } = string.Empty;
    }

**Comment by 2881099** [comment]
MySql 不支持 DateTimeOffset 类型。

https://github.com/dotnetcore/FreeSql/wiki/%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84
类型类型表，这里可以对照一下

**Comment by 2881099** [comment]
其实吧，用 DateTime 类型，全部使用 utc 时区存储就好了。

或者使用两个字段存储最通用，utc 时间 + timezone 分开存储，这样移植性更好。

**Comment by liuguiyou** [comment]
@2881099 多谢回复，FreeSql是否可以将DateTimeOffset 默认映射成mysql的datetime，这样大多数场景下是满足的，默认也不会报错

**Comment by 2881099** [comment]
用 Aop 应该能解决：

```csharp
fsql.Aop.ConfigEntityProperty += (s, e) => {
  if (e.Property.PropertyType == typeof(DateTimeOffset) || e.Property.PropertyType == typeof(DateTimeOffset?))
    e.ModifyResult.MapType = typeof(DateTime);
};
```
