### ISSUE TITLE
Sqlite InsertOrUpdate报UNIQUE constraint failed

### ISSUE THREAD

**Issue by Tony518** [dotnetcore/FreeSql#419]
Hello，
我用的1.6.0版本的freesql， 数据库是Sqlite ，当我InsertOrUpdate一个list， list中有两个元素，其中一个元素主键在数据库里已经存在，另一个是不存在的，此时调用InsertOrUpdate时，会报错。
![image](https://user-images.githubusercontent.com/15099434/90357916-0fe39000-e087-11ea-8589-2360d2c915df.png)

**Comment by 2881099** [comment]
监视到的 sql 发一下

**Comment by Tony518** [comment]
`INSERT INTO "LotusDocumentModel"("Sort", "CreateTime", "UpdateTime", "IsDeleted", "Version", "DbId", "DbName", "UniversalID", "CreationTime", "OpenDocUrl", "SyncStatus", "IsFieldCompleted", "IsPDFCompleted", "ErrMsg", "EncryptionStr") VALUES(0, datetime(current_timestamp,'localtime'), datetime(current_timestamp,'localtime'), 0, 0, 100, 'test', 'FD5B6AD1C79061D6482584560014ACA3', '2020-08-17 12:09:00', '', 0, 0, 0, '', ''), (0, datetime(current_timestamp,'localtime'), datetime(current_timestamp,'localtime'), 0, 0, 100, 'test', '1FD5B6AD1C79061D6482584560014ACA3', '2020-08-17 12:09:00', '', 0, 0, 0, '', '')
`
这种情况感觉应该是Replace Into才对

**Comment by 2881099** [comment]
实体类也发一下

**Comment by Tony518** [comment]
` [Index("uk_LotusDocumentModel_DbId", "DbId", false)]
    [Index("uk_LotusDocumentModel_UniversalID", "UniversalID", true)]
    [Table(Name = "LotusDocumentModel")]
    public class LotusDocumentModel : BaseEntityAttribute<LotusDocumentModel, int>
    {
        /// <summary>
        /// 关联数据库主键编号
        /// </summary>
        public int DbId { get; set; }

        /// <summary>
        /// 数据库名称
        /// </summary>
        [Column(DbType = "NVARCHAR2(500) DEFAULT ''", IsNullable = false)]
        public string DbName { get; set; } = string.Empty;


        /// <summary>
        /// 唯一编号
        /// </summary>
        [Column(DbType = "VARCHAR2(50) DEFAULT ''", IsNullable = false)]
        public string UniversalID { get; set; } = string.Empty;
        public DateTime CreationTime { get; set; }

        ///// <summary>
        ///// 唯一编号HashCode
        ///// </summary>
        //[Column(DbType = "INT DEFAULT '0'", IsNullable = false)]
        //public int UniIdHashCode { get; set; }
        /// <summary>
        /// 打开文档的Http Url
        /// </summary>
        [Column(DbType = "VARCHAR2(1000) DEFAULT ''", IsNullable = false)]
        public string OpenDocUrl { get; set; } = string.Empty;

        /// <summary>
        /// 同步状态（0-未开始 1-同步成功 2-同步失败 3-同步中）
        /// </summary>
        [Column(DbType = "INT DEFAULT '0'", IsNullable = false, MapType = typeof(int))]
        public SyncStatusEnum SyncStatus { get; set; } = SyncStatusEnum.Default;

        /// <summary>
        /// 字段是否已同步完成
        /// </summary>
        public bool IsFieldCompleted { get; set; } = false;
        /// <summary>
        /// PDF是否已同步完成
        /// </summary>
        public bool IsPDFCompleted { get; set; } = false;

        /// <summary>
        /// 错误消息
        /// </summary>
        [Column(DbType = "NVARCHAR2(2000) DEFAULT ''", IsNullable = false)]
        public string ErrMsg { get; set; } = string.Empty;

        /// <summary>
        /// 公钥加密串
        /// </summary>
        [Column(DbType = "NVARCHAR2(2000) DEFAULT ''")]
        public string EncryptionStr { get; set; } = string.Empty;
    }`

**Comment by 2881099** [comment]
大概率是因为这个实体类，有自增列。被判定成了 insert into

**Comment by Tony518** [comment]
的确有的，在BaseEntityAttribute基类里，这个会有影响，是吧？

**Comment by 2881099** [comment]
有的，InsertOrUpdate 只能根据主键进行操作。

**Comment by Tony518** [comment]
那这个实体类就不能用BaseEntity了？

**Comment by 2881099** [comment]
BaseEntity\<T\> 可以继承这个，然后在自己的实体中设置 Column(IsPrimary

**Comment by Tony518** [comment]
好的，谢谢，解决了
