### ISSUE TITLE
MySql 字段类型为 tinyint 时，生成的数据类型为 sbyte

### ISSUE THREAD

**Issue by neoayi** [dotnetcore/FreeSql#420]
如题，请问该从哪里设置配置，这样在生成实体时 tinyint 可以为 bool 类型的数据。

另外，题外话
MySQL 数据库中的枚举类型中 生成时，与 C# 的关键字产生冲突。是否这个需要从 数据库本身来杜绝这个枚举值的关键字。

![image](https://user-images.githubusercontent.com/137907/90376756-87c2b200-e0a9-11ea-87d2-e557e68c0a94.png)

**Comment by 2881099** [comment]
直接在模板上判断处理，sbyte是默认规则。开发出来设置，还不如在模版上改一下。

如果你用 freesql.generator 生成的实体，目录下会有一个 razor 模板文件，找到对应的位置修改一下重新生成。

**Comment by 2881099** [comment]
怎么改， replace 或者定义一个函数，判断处理下。

**Comment by neoayi** [comment]
嗯，了解了。
