### ISSUE TITLE
postgres BUG

### ISSUE THREAD

**Issue by 1haoyu** [dotnetcore/FreeSql#421]
postgres Codefirst int 类型 添加[Column(IsNullable = false)] 生成SQL 语句 会 变成   "xxxId" INT4 NOT NOT NULL,  会多一个NOT ，导致SyncStructure 错误
        [Column(IsNullable = false, IsPrimary = true, IsIdentity = true)]
        public int Id { get; set; }
如果是主键，添加 IsNullable = false，生成 SQL 语句为   "Id" INT4 NOT,  导致SyncStructure 错误,虽然是无关紧要的BUG，只是提一下

**Comment by 2881099** [comment]
升级一下可以解决

- 修复 1.7.1 IsNullable 遗留问题；

## v1.7.1 (Microsoft.Data.SqliClient 兼容问题)

- 调整 ColumnAttribute IsNullable 对 int/long 等值类型也可生效；

**Comment by 2881099** [comment]
https://github.com/2881099/FreeSql/wiki/%e6%9b%b4%e6%96%b0%e6%97%a5%e5%bf%97
更新日志，可以关注一下

目前可以升级到 1.8.0-preview 解决

**Comment by 2881099** [comment]
其实本来 int 不需要指明 IsNullable = false 的，默认就是 NOT NULL

**Comment by 1haoyu** [comment]
嗯，原本是MYSQL的codefirst ,顺手写了 NOT NULL，迁移到 postgres 产生的错误，我已经升级到 1.7.1了，才发现的BUG
