### ISSUE TITLE
在Oracle中string型的主键Id是否可以默认映射成Varchar而不是NVarchar

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#422]
在某些情况下需要使用字符串作为主键，如实体对象为
public class TTest
{
     [Column(Position = 1, IsPrimary = true, StringLength = 40)]
     public virtual string Id { get; set; }
}
此时用CodeFirst在Oracle建表，Id被映射层了NVarchar，但用NVarchar时经常会有“字符集不匹配”的问题，这种情况下，是否可以在Oracle中将主键映射成Varchar，而不是NVarchar

**Comment by 2881099** [comment]
如果是 guid 可以直接给类型 Guid

string 默认映射 nvarchar2

**Comment by exy3351** [comment]
由于需要支持多种数据库，在Sqlite中又没有guid，所以用insert into 时用的是时间+随机数，这种又转不了Guid，所以没法定义成Guid的类型

**Comment by 2881099** [comment]
Guid 如果都用 code first 可以支持。

Guid \| Guid? | char(36) | uniqueidentifier | uuid | char(36 CHAR) | character(36) | char(36)
-- | -- | -- | -- | -- | -- | --

https://github.com/dotnetcore/FreeSql/wiki/%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84
类型映射表

**Comment by exy3351** [comment]
可能没写清楚，是这种情况

**Comment by exy3351** [comment]
可能没写清楚，是这种情况
INSERT INTO table2(id,a,b....)
SELECT guid,a,b FROM ( select ......) t
这种情况下在sqlite好像是没生成guid的函数，想到的处理方案是：
1. 时间到秒+last_insert_id：之前用SqlSugar执行时可以正常使用，改为FreeSql后可能是 ExecuteNoQuery内部开了事务，导致last_insert_id返回的都是0，所以这个方案被否了
2.时间到秒+随机数：目前用的是这个，一次重复的概率不大，可以接受
在这种情况下生成的id不是guid，在查询时好像就没法转成正常的Guid类型了吧？？

**Comment by 2881099** [comment]
varchar 他 last_insert_id 有什么关系，没看懂

**Comment by exy3351** [comment]
是用场景是这样的，数据检查需要同时支持Oracle、PG、Sqlite等多种数据库。检查结果表的形式为
public class T_Check_Result{
   public string Id {get;set;}
}
写入结果的方式有两种，
1.是的到错误结果后通过实体的方式写入；
2.直接通过 INSERT INTO....SELECT  ...的方式写入；
第一种方式没什么问题；第二中方式，在记录错误Id时，Oracle、PG等库中直接使用数据库内置得Guid函数，但在Sqlite中没有这样内置的函数，所以想了其他方式来记录这个Id（其他方式就是上面提到的两种方案）。
这样在查询时，由于在Sqlite中Id不一定是Guid的形式，所以实体中的Id不好直接定义成Guid类型，所以实体才定义成字符串；
另外，映射成功GUID类型后，在PG中联表查询又存在类型不匹配的问题，所以不能映射成Guid；
由于字符串在Oracle中映射成了NVarchar，而NVarchar在使用过程中也经常有类型不匹配的问题，所以字段主键而言最好是定义成Varchar，这样问题就会少很多

这些是测试后遇到的问题。问题通过配置 DBType = “Varchar(40)” 的方式是可以解决，但这样总觉得有点别扭，其他数据库都正常，就因为一个Oracle就需要加一个这样的特性感觉很怪，从使用的便捷性来说，在Oracle中主键映射成Varchar而不是NVarchar应该是最方便的
这个只是建议，若觉得不合理，请忽略

**Comment by 2881099** [comment]
可以通过 fsql.Aop 根据数据库类型做个适配

**Comment by 2881099** [comment]
if oracle maptype = Guid
if sqlite maptype = string

实体类型都用 string

**Comment by exy3351** [comment]
通过Aop更麻烦一点，DBType = “Varchar(40)” 就可以解决问题，只是感觉使用不是太方便。先这样吧，问题能解决就行
