### ISSUE TITLE
希望该库可以支持SqlServer空间类型操作

### ISSUE THREAD

**Issue by RalphLuo** [dotnetcore/FreeSql#424]
您好，FreeSql是一个很棒的开源库，现在我也在工作中使用它，但是目前发现不能直接支持Microsoft.SqlServer.Types的SqlGeography、SqlGeometry类型映射，希望能改进兼容SqlServer的空间操作功能。

**Comment by 2881099** [comment]
谢谢支持。

大概了解了一下，sqlserver gis 环境比较复杂，不好接入。

Microsoft.SqlServer.Types 这个貌似是 .net framework 用的？我使用 Microsoft.Data.SqlClient 查询报错。

**Comment by 2881099** [comment]
mysql/postgresql 那边很早就支持 gis 类型，那边的类库环境相对比较干净。
