### ISSUE TITLE
希望 fsql.Ado 也能实现 Curd 事件

### ISSUE THREAD

**Issue by hvppy** [dotnetcore/FreeSql#425]
希望 fsql.Ado 也能实现 fsql.Aop.Curd.. 事件,因为还是难以避免orm+ado混合着用

**Comment by 2881099** [comment]
fsql.Aop.CommandBefore/CommandBeforeAfter

**Comment by hvppy** [comment]
> fsql.Aop.CommandBefore/CommandBeforeAfter

这个事件有了,很棒!

**Comment by hvppy** [comment]
> fsql.Aop.CommandBefore/CommandBeforeAfter

有个小问题,CommandAfter 里面的 Exception 没有赋值

**Comment by 2881099** [comment]
收到
