### ISSUE TITLE
希望IUpdate能够支持Update Set From的写法

### ISSUE THREAD

**Issue by KingSclie** [dotnetcore/FreeSql#426]
例如：
UPDATE  A_Table
SET  a_Name = (CASE WHEN b_Name IS NOT NULL THEN b_Name ELSE a_Name END), 
	a_Sex = (CASE WHEN b_Sex IS NOT NULL THEN b_Sex ELSE a_Sex END), 
        a_Card_type = (CASE WHEN b_Card_type IS NOT NULL THEN b_Card_type ELSE a_Card_type END), 
	 .......
FROM     B_Table
WHERE   a_Id = @aId AND b_Id=@bId

经常在某些场景会需要让某两个表进行数据同步或者多表部分数据整合到单表的情况，虽然可以通过先ISelect去查询数据然后通过IUpdate的SetRaw去实现，字段数小量还好，如果表字段相对较多，使用这种办法会让代码的写法变得繁琐而且庞大，希望以后的版本中有所改善，谢谢！

祝项目越来越好！

**Comment by 2881099** [comment]
该建议被提了多次，目前仍然坚持原则：批量联表操作危险⚠️，各数据库间 sql 语法有差异，容易让使用者误用。

freesql 拒绝危险操作。欢迎补充，谢谢
