### ISSUE TITLE
select查询后类型映射不区分大小写

### ISSUE THREAD

**Issue by YanmaY** [dotnetcore/FreeSql#427]
![7Z(VUDM 6CN_FB7MV G8NA](https://user-images.githubusercontent.com/7043862/90608037-a0ab9e80-e234-11ea-919a-325b29559ce3.png)
![~P8BPHGUENRKGUNUMESS`~S](https://user-images.githubusercontent.com/7043862/90608061-a86b4300-e234-11ea-8415-440bcfcfa043.png)
如图所示，删除掉Cadre中的education后可正常映射，否则会报错，说明在映射的时候并不区分大小写

**Comment by 2881099** [comment]
v1.8.0-preview0820 阔以解决

**Comment by YanmaY** [comment]
叶老板V5，这效率杠杠的👍👍👍
