### ISSUE TITLE
希望支持sql的isnull函数，例如min、max等函数取值为空时能赋一个自定义的默认值

### ISSUE THREAD

**Issue by cctczyg** [dotnetcore/FreeSql#428]
大神，目前项目有一个取最后操作时间跟当前时间对比的需求，找了好久都没找到有isnull函数的替代，只能写了个。。。.Max(a => a.Time) == null || 。。。.Max(a => a.Time) < DateTime.Now.AddMinutes(-5)应付一下，见笑了，期待加入类似isnull功能，如：。。。.Max(a => a.Time, DateTime.Now..AddMinutes(-10)），第二个参数就是我要自定义的值，谢谢，祝项目好！

**Comment by 2881099** [comment]
.Max(a => a.Time) ?? DateTime.Now..AddMinutes(-10)

c# 7.0 语法糖

**Comment by cctczyg** [comment]
这个语法糖哪里能塞到你的sql里去啊？

**Comment by 2881099** [comment]
.Max(a => a.Time) ?? DateTime.Now..AddMinutes(-10)

相当于先查询出来，为 null 就取后面的值

-----

.Max(a => a.Time ?? DateTime.Now..AddMinutes(-10))

相当于 select max(isnull(a.time, ...)) from

**Comment by cctczyg** [comment]
这样的话表里没数据时，max返回的还是null，我要的是 select isnull(max(a.time), ...) from，这样就不会返回null了

**Comment by 2881099** [comment]
所以你需要后面这个

**Comment by cctczyg** [comment]
其实准确的描述需求如下：
select * from a
left join b on a.x = b.x
where isnull(max(b.time), '2020-08-20 10:20:00') < a.Time
还是要在sql层面做适配，因为涉及到两个表之间的字段

**Comment by 2881099** [comment]
where max 这样能行？max 只能出现在 having 条件内。

**Comment by 2881099** [comment]
a.Time ?? DateTime.Now

对应

isnull(a.Time, getdate()

**Comment by 2881099** [comment]
表达式 | MySql | SqlServer | PostgreSQL | Oracle | 功能说明
-- | -- | -- | -- | -- | --
a ? b : c | case when a then b else c end | case when a then b else c end | case when a then b else c end | case when a then b else c end | a成立时取b值，否则取c值
a ?? b | ifnull(a, b) | isnull(a, b) | coalesce(a, b) | nvl(a, b) | 当a为null时，取b值
数字 + 数字 | a + b | a + b | a + b | a + b | 数字相加
数字 + 字符串 | concat(a, b) | cast(a as varchar) + cast(b as varchar) | case(a as varchar)\|\| b | a\|\| b | 字符串相加，a或b任意一个为字符串时
a - b | a - b | a - b | a - b | a - b | 减
a * b | a * b | a * b | a * b | a * b | 乘
a / b | a / b | a / b | a / b | a / b | 除
a / b | a div b | a / b | a / b | trunc(a / b) | 整除(a,b都为整数)
a % b | a % b | a % b | a % b | mod(a,b) | 模

**Comment by cctczyg** [comment]
http://106.55.166.58:6000/aaa.png

**Comment by cctczyg** [comment]
这难道是我的c#版本低了？

**Comment by 2881099** [comment]
这个是 c# 7.0 的语法，vs2017 以上才行。

实在不行可以看自定义表达式函数解析功能，定义一个 IsNull 出来。

参考：

```c#
[ExpressionCall]
public static class DbFunc {
  //必要定义 static + ThreadLocal
  static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

  public static DateTime FormatDateTime(this DateTime that, string arg1)
  {
    var up = context.Value;
    if (up.DataType == FreeSql.DataType.Sqlite) //重写内容
      up.Result = $"date_format({up.ParsedContent["that"]}, {up.ParsedContent["arg1"]})";
    return that;
  }
}

var sql1 = fsql.Select<SysModule>()
  .ToSql(a => a.CreateTime.FormatDateTime("yyyy-MM-dd"));
//SELECT date_format(a."CreateTime", 'yyyy-MM-dd') as1 
//FROM "SysModule" a
```

**Comment by cctczyg** [comment]
可是我的是vs2019啊，做的是netcore2.1的项目，用的FreeSql包是1.6.0的，那我再看看吧，谢谢了

**Comment by 2881099** [comment]
还有，你发的图片地址访问不了。

**Comment by 2881099** [comment]
a.Time ?? xxx

前面 a.Time 必须为 DateTime? 类型，否则用不了这个语法，可以转换一下再用：

(DateTime?)a.Time ?? xx

**Comment by cctczyg** [comment]
还真是的，我说怎么会报错呢，我用的是DateTime，我发的图片是测试的服务器，用的6000端口，chorme浏览器应该是禁用了，不过按你说的转换了一下就好了，谢谢了，我关issue了

**Comment by cctczyg** [comment]
不好意思，我又来了，刚看了一下，.Max(a => a.Time ?? DateTime.Now)生成的还是SELECT max(ifnull(o.`StartTime`, ...)) from ...，这样跟SELECT ifnull(max(o.`StartTime`), ...) from ...逻辑上还不是一回事

**Comment by 2881099** [comment]
所以用上面说的第一种：

**Comment by cctczyg** [comment]
好的，测试可以用 了，谢谢了
