### ISSUE TITLE
注意了！达梦数据库NVARCHAR2长度为36时，对应C#的数据类型是GUID，而不是String！！！

### ISSUE THREAD

**Issue by Lc3586** [dotnetcore/FreeSql#429]
![image](https://user-images.githubusercontent.com/34331208/90714403-29304a80-e2da-11ea-85e7-e76e4bed91c0.png)

![image](https://user-images.githubusercontent.com/34331208/90714504-609ef700-e2da-11ea-81e1-bf9ef419a107.png)

![image](https://user-images.githubusercontent.com/34331208/90714452-45cc8280-e2da-11ea-8865-d6a91839f654.png)

**Comment by 2881099** [comment]
达梦驱动的机制，dr.GetString 就没事。

目前如果真的要定义成字符串，尽量避开 36 长度。

**Comment by jinghongbo** [comment]
使用DMProvider 1.1.0 3462 可以解决这个问题
