### ISSUE TITLE
有没有多表关联查询后 然后union all 其他多表关联操作的处理方式

### ISSUE THREAD

**Issue by liuxunbiao** [dotnetcore/FreeSql#432]
有一个结果集是两个多表查询结果的并集 不用sql语句处理，freesql有处理方式吗

**Comment by 2881099** [comment]
```c#
var sql1 = fsql.Select<T>().ToSql();
var sql2 = fsql.Select<T2>().ToSql();

var list = fsql.Select<T>()
   .WithSql(sql1).WithSql(sql2).ToList();
```

**Comment by liuxunbiao** [comment]
> ```cs
> var sql1 = fsql.Select<T>().ToSql();
> var sql2 = fsql.Select<T2>().ToSql();
> 
> var list = fsql.Select<T>()
>    .WithSql(sql1).WithSql(sql2).ToList();
> ```

fsql.Select<T,T1,T2,T3...>() 没有withsql 方法

**Comment by 2881099** [comment]
union all 应该先把多表结果汇总，因为每个结果集返回的字段应该要一致。

再用单表 WithSql。

```c#
var sql1 = fsql.Select<T1, T2, T3>().ToSql((a,b,c) => new { 返回一样的字段 }, FieldAliasOptions.AsProperty);
var sql2 = fsql.Select<T4, T5, T6>().ToSql((a,b,c) => new { 返回一样的字段 }, FieldAliasOptions.AsProperty);

var list = fsql.Select<T>()
   .WithSql(sql1).WithSql(sql2).ToList();
```

**Comment by liuxunbiao** [comment]
> union all 应该先把多表结果汇总，因为每个结果集返回的字段应该要一致。
> 
> 再用单表 WithSql。
> 
> ```cs
> var sql1 = fsql.Select<T1, T2, T3>().ToSql((a,b,c) => new { 返回一样的字段 }, FieldAliasOptions.AsProperty);
> var sql2 = fsql.Select<T4, T5, T6>().ToSql((a,b,c) => new { 返回一样的字段 }, FieldAliasOptions.AsProperty);
> 
> var list = fsql.Select<T>()
>    .WithSql(sql1).WithSql(sql2).ToList();
> ```

在pgsql中 形成的 连接sql语句有问题

形成的sql语句比如  select “A” from (
select "A" A from "b"
) c
这个时候就会报找不到字段 “A”

另外union all 后有没有方法进行 分页

**Comment by 2881099** [comment]
pgsql 建议都用小写，FreeSqlBuilder UseNameConvert 可以设置。

Union All 分页，可以再 ToSql WithSql 套一层
