### ISSUE TITLE
为字段指定别名

### ISSUE THREAD

**Issue by zhouandke** [dotnetcore/FreeSql#433]
假设有两个类, Person的CityId 关联 City.Id
`
public class Person
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    /*  其它十几个属性  */

    public Guid CityId { get; set; }
}

public class City
{
    public Guid Id { get; set; }

    public string Name { get; set; }
}
`

而要查询的 PersonIndexVO 需要的是  CityName
`
    public class PersonIndexVO
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        /*  其它十几个属性  */

        public string CityName { get; set; }
    }
`
目前的做法是
`
var persons = fsql.Select<Person, City>().LeftJoin((p, c) => p.CityId == c.Id)
    .ToList((p, c) => new PersonIndexVO
    {
        Id = p.Id,
        Name = p.Name,
        Age = p.Age,
    /*  其它十几个属性  */
        CityName = c.Name
    });
`

当属性很多的时候, 这样写着就特别累, 那么可以自定义字段别名么, 像这样

var persons2 = fsql.Select<Person, City>().LeftJoin((p, c) => p.CityId == c.Id)
    .FieldAlias((p, c) => c.Name, "CityName")   // 指定 c.Name 的别名为 CityName, 这样就可以直接对应上 PersonIndexVO.CityName
    .ToList<PersonIndexVO>();

end

**Comment by 2881099** [comment]
试试这样写，看到回的数据，并且监视 sql

```c#
var persons = fsql.Select<Person, City>().LeftJoin((p, c) => p.CityId == c.Id)
.ToList((p, c) => new PersonIndexVO
{
CityName = c.Name
});
```

相关文档，见 DTO 映射查询

**Comment by zhouandke** [comment]
这回复速度真是绝了, 如果github 允许给一个项目点2次 star, 我想为这个项目点10次
