### ISSUE TITLE
动态插入数据 AsType() 时出错

### ISSUE THREAD

**Issue by NetRube** [dotnetcore/FreeSql#434]
object obj = new Topic { Title = "Test" };
fsql.Insert(obj).AsType(typeof(Topic)).ExecuteAffrows();

运行上面的代码后会抛出异常：
Exception: 操作的数据类型(Topic) 与 AsType(System.Object) 不一致，请检查。

**Comment by 2881099** [comment]
fsql.Insert\<object>().AsType(typeof(Topic)).AppendData(obj).ExecuteAffrows();

**Comment by NetRube** [comment]
感谢回复~
单条插入按上面的代码已经解决~
但批量插入时出错~

var jsonArr = Newtonsoft.Json.Linq.JArray.Parse("Topic.json");
var itemType = typeof(Topic);
var itemsType = itemType.MakeArrayType();
var items = jsonArr.ToOjbect(itemsType);
fsql.Insert<object>()
	.AsType(itemsType)
	.AppendData(items)
	.ExecuteAffrows();

运行上面的代码后会抛出异常：
Exception: IInsert.AsType 参数错误，请传入正确的实体类型
FreeSql.Internal.CommonProvider.InsertProvider<T1>.AsType(Type entityType)

**Comment by 2881099** [comment]
因为 items 是 object 类型，页不是 object[] 或者 List\<object\>

**Comment by NetRube** [comment]
改为AsType(itemType)又会出现错误：
Exception: 操作的数据类型(Topic[]) 与 AsType(Topic) 不一致，请检查。

能否在判断数据类型时检测一下是否为IEnumerable对象~这样应该就能解决了~

**Comment by NetRube** [comment]
在做数据迁移~ 有很多表~ 不想每个表都手动写代码~ 想在一个循环里完成~ 不知有没有更好的解决方法~

**Comment by 2881099** [comment]
循环程序集下所有类型，根据命名空间，或者特性，或者父类，或者。。

然后就能得到一个 Type[] 了

**Comment by 2881099** [comment]
> 改为AsType(itemType)又会出现错误：
> Exception: 操作的数据类型(Topic[]) 与 AsType(Topic) 不一致，请检查。
> 
> 能否在判断数据类型时检测一下是否为IEnumerable对象~ 这样应该就能解决了~

可以，下个版本会处理

**Comment by 2881099** [comment]
收回前面的承诺，这个涉及地方比较多，为了不影响使用习惯。暂时先不处理。

因为本身也是参数类型传入不正确导致的，不是 bug。

解决办法：将 obj 转为 object[] 再传入。

> 改为AsType(itemType)又会出现错误：
> Exception: 操作的数据类型(Topic[]) 与 AsType(Topic) 不一致，请检查。
> 
> 能否在判断数据类型时检测一下是否为IEnumerable对象~ 这样应该就能解决了~

**Comment by hyzx86** [comment]
很类似的问题哦
我这里之前用的是List<T>  需要修改为反射为数组
```
     var modelType = Type.GetType($"ABR.ADWSync.Core.MD.{input.TypeName}, ABR.ADWSync.Core");
            var listType = Type.GetType($"System.Collections.Generic.List`1[[{modelType.AssemblyQualifiedName}]]");
            try
            {
                var dataList = JsonConvert.DeserializeObject(input.Data ,listType);
                var k = await FreeSql.InsertOrUpdate<object>().AsType(modelType).SetSource(dataList).ExecuteAffrowsAsync();
                return k;
            }
            catch (Exception ex)
            {
                throw new UserFriendlyException(ex.Message, ex);
            }
```
修改反射为 数组
```   var modelType = Type.GetType($"ABR.ADWSync.Core.MD.{input.TypeName}, ABR.ADWSync.Core");
            var listType = Type.GetType($"ABR.ADWSync.Core.MD.{input.TypeName}[],ABR.ADWSync.Core");
            try
            {
                var dataList =(object[]) JsonConvert.DeserializeObject(input.Data, listType);
                _ = FreeSql.InsertOrUpdate<object>().AsType(modelType).SetSource(dataList).ExecuteAffrowsAsync();

            }
            catch (Exception ex)
            {
                throw new UserFriendlyException(ex.Message, ex);
            }
```

**Comment by NetRube** [comment]
> 收回前面的承诺，这个涉及地方比较多，为了不影响使用习惯。暂时先不处理。
> 
> 因为本身也是参数类型传入不正确导致的，不是 bug。
> 
> 解决办法：将 obj 转为 object[] 再传入。
> 
> > 改为AsType(itemType)又会出现错误：
> > Exception: 操作的数据类型(Topic[]) 与 AsType(Topic) 不一致，请检查。
> > 能否在判断数据类型时检测一下是否为IEnumerable对象~ 这样应该就能解决了~

感谢~ 已解决~ 经提醒将 obj 转为 object[] 再传入~

**Comment by NetRube** [comment]
> 很类似的问题哦
> 我这里之前用的是List 需要修改为反射为数组
> 
> ```
>      var modelType = Type.GetType($"xxx.Core.MD.{input.TypeName}, xxx.Core");
>             var listType = Type.GetType($"System.Collections.Generic.List`1[[{modelType.AssemblyQualifiedName}]]");
>             try
>             {
>                 var dataList = JsonConvert.DeserializeObject(input.Data ,listType);
>                 var k = await FreeSql.InsertOrUpdate<object>().AsType(modelType).SetSource(dataList).ExecuteAffrowsAsync();
>                 return k;
>             }
>             catch (Exception ex)
>             {
>                 throw new UserFriendlyException(ex.Message, ex);
>             }
> ```
> 
> 修改反射为 数组
> 
> ```
>             var listType = Type.GetType($"xxx.Core.MD.{input.TypeName}[],xxx.Core");
>             try
>             {
>                 var dataList = JsonConvert.DeserializeObject(input.Data, listType);
>                 _ = FreeSql.InsertOrUpdate<object>().AsType(modelType).SetSource(dataList).ExecuteAffrowsAsync();
> 
>             }
>             catch (Exception ex)
>             {
>                 throw new UserFriendlyException(ex.Message, ex);
>             }
> ```

感谢回复~
我的代码只需把
var items = jsonArr.ToOjbect(itemsType);
改成
var items = jsonArr.ToOjbect(itemsType) as object[];
就可以了~

**Comment by hyzx86** [comment]
哎 ~ 我说怎么改了还没用。。 这里还是不行 
必须 
```
  var dataList = (object[]) JsonConvert.DeserializeObject(input.Data, listType);
  _ = FreeSql.InsertOrUpdate<object>().AsType(modelType).SetSource(dataList).ExecuteAffrowsAsync();
```

**Comment by NetRube** [comment]
因为我的编程习惯是为了兼容性一般都是在底层判断并处理数据类型~
所以在我的代码里我已经 itemsType = itemType.MakeArrayType() 了~
我就认为 items = jsonArr.ToOjbect(itemsType) 之后 items 已经是 object[] 类型了~
那传入去 FreeSql 也已经是 object[] 类型了~
不是 bug~ 是我的错~
不过 FreeSql 也可以改进一下~ 增加兼容性~
