### ISSUE TITLE
考虑支持华为高斯数据库吗

### ISSUE THREAD

**Issue by johnseed** [dotnetcore/FreeSql#435]
华为高斯数据库GaussDB，国产化系统用的也挺多

**Comment by 2881099** [comment]
暂时不考虑。

**Comment by 2881099** [comment]
GaussDB 数据库基于 postgresql 开源改来的，目前支持 odbc 的方式进行访问。

引用 FreeSql.Provider.Odbc.dll，UseConnectionString(DataType.OdbcPostgreSQL, connecionString) 的方式可以访问。

以上方法来自群友的提供。
