### ISSUE TITLE
批量插入Bug提交

### ISSUE THREAD

**Issue by xuanyuan5005** [dotnetcore/FreeSql#437]
我在模拟3年数据量插入，每小时生产4W条记录。分8次插入，每次插入5000条。模拟程序，运行24小时之后。报错  FreeSQL Connection must be valid and open to rollback transaction。
           
               数据库服务器Percona 8.0。
              
               DeviceLog[] logs = CreateOneHourLog(day, today, hour);
                for (int i = 0; i < 8; i++)
                {
                    int start = i * 5000;
                    var sub = logs.AsSpan(start, 5000);
                    long tick = Environment.TickCount64;
                    string message = $"Begin save {day}-{hour}-{i} logs to ROCKS,and totoal is {logs.Length}";
                    Console.WriteLine(message);
                    rocksSql.Insert<DeviceLog>(sub.ToArray()).ExecuteAffrows();
                    long span = Environment.TickCount64 - tick;
                    message = $"Save {day}-{hour}-{i} logs to ROCKS,and totoal is {logs.Length} ,used {span} milliseconds.";
                    Console.WriteLine(message);
                    Thread.Sleep(5);
               }

**Comment by 2881099** [comment]
FreeSql.Provider.MysqlConnector.dll 这个也试试

还有 fsql.Insert(xxx).NoneParameter().ExecuteAffrow()

**Comment by xuanyuan5005** [comment]
谢谢
我再测试一下。

**Comment by xuanyuan5005** [comment]
补充一下，刚才发生异常，数据库写入3行成功。

**Comment by 2881099** [comment]
问题是否已解决？
