### ISSUE TITLE
关联树表使用toTreeList的问题

### ISSUE THREAD

**Issue by wanglantian** [dotnetcore/FreeSql#438]
树表dept，配置了导航属性之后，toTreeList()是没问题的。多了张表rel_dept,给rel_dept配置了导航属性Dept,
rel_dept.select.innerJoin(p=>p.Dept.Id == p.DeptId).where(p=>p.Dept.ParentId == p.Dept.Id),这样使用是不是有问题？

**Comment by 2881099** [comment]
ToTreeList 是内存做的，其实是先 ToList 返回平级数据，再内存加工为树状结构。

你说的方式没问题

**Comment by wanglantian** [comment]
但是在innerJoin后面加上where(p=>p.Dept.ParentId == p.Dept.Id)会导致sql语句中有where dept.parentId = dept.id。查询结果就为空了。

**Comment by 2881099** [comment]
那就是查询条件不对

**Comment by wanglantian** [comment]
是的，发现了。我在leftjoin(p=>p.dept.parentId == p.dept.parent.id)之后还使用了where(p=>p.dept.status != 1),导致sql中有两个leftjoin。把leftjoin去掉就可以了。innerJoin好像会有点问题，会导致根节点parentId为空的记录不包含在内。

**Comment by 2881099** [comment]
父子关系，用 leftjoin innerjoin 查询是什么需求？

如果是查询所有子记录，用 AsTreeCte

**Comment by wanglantian** [comment]
情况是这样的，rel_dept是一个关联表，dept是一个父子表。想从rel_dept开始获取到关联的dept的树形结构。目前是先从rel_dept表中获取到ids，然后再去dept表中用contains条件去toTreeList。

**Comment by 2881099** [comment]
```c#
fsql.Select<dept>()
    .Where(a => fsql.Select<rel_dept>().As("b").Where(b => ...).ToList(b => b.dept_id).Contains(a.id))
    .ToList();
```

这样？

**Comment by 2881099** [comment]
多监视SQL

**Comment by wanglantian** [comment]
对，这样是行的。一开始是这样写的：
`var select = _orgPermissionRepository.Select
                .LeftJoin(p => p.Page.ParentID == p.Page.Parent.ID)
                .Where(p => p.Page.RecordStatus == 1 && p.Page.DataStaus == 1 && p.Page.IsVisual == 1);`
sql是：
`SELECT a.`id`, a.`NavID`, a.`OrgID`
FROM `org_permission` a 
LEFT JOIN `om_page` a__Page__Parent ON a__Page__Parent.`ID` = a__Page.`ParentID` 
LEFT JOIN `om_page` a__Page ON a__Page.`ParentID` = a__Page__Parent.`ID` 
WHERE (a__Page.`RecordStatus` = 1 AND a__Page.`DataStaus` = 1 AND a__Page.`IsVisual` = 1)`
这样应该是行不通的。
可以，你这样写好一点，我是分成两段写了：
