### ISSUE TITLE
CodeFist 模式下表的存储引擎，是否可以指定？

### ISSUE THREAD

**Issue by xuanyuan5005** [dotnetcore/FreeSql#439]
CodeFist 模式下表的存储引擎，是否可以指定？

**Comment by 2881099** [comment]
不可以，可以尝试 

1. fsql.CodeFirst.GetXxx 得到 SQL，在 repalce 执行

2. 利用 Aop.CommandBefore 事件 replace CommandText

**Comment by xuanyuan5005** [comment]
个人建议：

1，在FreeSql.DataAnnotations.TableAttribute 增加一个Engine属性，来实现。
2，不要暴露太多的SQL语句和执行细节。

**Comment by 2881099** [comment]
谢谢建议，因为要考虑通用情况，所以给了在事件中 replace SQL 的方案。
