### ISSUE TITLE
SQL Server 多组条数据取每组最新的一条数据

### ISSUE THREAD

**Issue by gywei** [dotnetcore/FreeSql#441]
问：数据库一张表中有不同公司不同时间发来的数据，怎样取每个公司最新的那条数据呢？

 网上查到是使用分析函数**row_number() over (partiion by ... order by ...)**来进行分组编号，然后取分组标号值为1的记录即可。

以sql server为例：

select s.*  

from ( 

    select *, row_number() over (partition by [公司名] order by [时间] desc) as group_idx  

    from [表名]

) s

where s.group_idx = 1

请问如何用FreeSql 实现？不想用写死的SQL语句，想通过编程方式实现。
Freesql 里面好像没有row_number() over (partiion by ... order by ...) 这种东西？

**Comment by 2881099** [comment]
lambda 中使用 SqlExt.RowNumber

**Comment by 2881099** [comment]
fsql.Select\<T>().ToList(a=>new { item = a, last = SqlExt.RowNumber()....)

**Comment by gywei** [comment]
> fsql.Select<T>().ToList(a=>new { item = a, last = SqlExt.RowNumber()....)

SqlExt 是什么？freesql 里面没有这个类啊？

**Comment by 2881099** [comment]
扩展方法，老版本没有

**Comment by Zonciu** [comment]
@gywei 请问这个问题解决了吗，能不能提供一个成功的例子？

**Comment by LeaFrock** [comment]
> fsql.Select<T>().ToList(a=>new { item = a, last = SqlExt.RowNumber()....)

这样的话是不是相当于加载了整张表？

**Comment by 2881099** [comment]
```c#
fsql.Select<User1>()
    .Where(a => a.Id < 1000)
    .WithTempQuery(a => new
    {
        item = a,
        rownum = SqlExt.RowNumber().Over().PartitionBy(a.Nickname).OrderBy(a.Id).ToValue()
    })
    .Where(a => a.rownum == 1)
    .ToList();
```

提示：支持多表嵌套查询，fsql.Select<User1, UserGroup1>()

```sql
SELECT *
FROM (
    SELECT a.[Id], a.[Nickname], row_number() over( partition by a.[Nickname] order by a.[Id]) [rownum]
    FROM [User1] a
    WHERE a.[Id] < 1000
) a
WHERE (a.[rownum] = 1)
```
