### ISSUE TITLE
同步表 SyncStructure 有bug

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#442]
同步表的问题
1.同步表时，生成临时表后(_Free...Tmp_..),若在迁移之前的表失败后，生成的临时表不会删除，之后就没法在同步了，报表已存在；
2.迁移失败的原因是 在Oracle中 有个字段Remark之前创建的是Varchar2(4000)  (之前有SqlSugar创建的)，用 FreeSql 改成 stringLength  = - 1后，创建的类型为NClob，在迁移 Remark 时，就报 NClob的错误了

**Comment by 2881099** [comment]
这种情况建议不要自动同步了，自动同步适合一开始就用 FreeSql CodeFirst 的实体类。

**Comment by 2881099** [comment]
新实体可以用自动同步，旧实体在特性用禁用自动同步结构。
