### ISSUE TITLE
数据更新的时候多条件判断的时候括号识别错误了

### ISSUE THREAD

**Issue by wzohxia** [dotnetcore/FreeSql#444]
var t = await _context.Update<UniqueKey>(1000000000000000000).Set(a => new {
                LastNum = (a.CycleType == "year" && a.LastTime < stampYear)
                                || (a.CycleType == "month" && a.LastTime < stampMonth)
                                || (a.CycleType == "day" && a.LastTime < stampDay) ? 1 : a.LastNum + 1,
                LastTime = 1598946210468
            }).ExecuteAffrowsAsync();

数据监听的时候语句为
UPDATE  [UniqueKey]
SET     [LastNum] = CASE WHEN (([CycleType] = N'year'
                                AND [LastTime] < 1577808000000
                                OR [CycleType] = N'month'
                                AND [LastTime] < 1598889600000)
                               OR [CycleType] = N'day'
                               AND [LastTime] < 1598889600000) THEN 1
                         ELSE ([LastNum] + 1)
                    END ,
        [LastTime] = 1598946210468
WHERE   ([ID] = 1000000000000000000)

括号识别是错误的

**Comment by 2881099** [comment]
因为优先级关系，And 的括号不是必须的

结果是正确的

**Comment by wzohxia** [comment]
不好意思  没注意优先级的问题  只注意到了括号没有补齐

**Comment by 2881099** [comment]
括号太多了太不美观，所以做了一点优化

**Comment by wzohxia** [comment]
习惯用括号了 - -|||  无脑看代码 然后就形成惯性思维了
