### ISSUE TITLE
对于非null字段，自动处理给一个默认值

### ISSUE THREAD

**Issue by yunbaozhou** [dotnetcore/FreeSql#445]
比如：
表中定义一个非null字符串。在实例化对应的类时，值为null。

希望框架中将其处理为空字符串。

自其它非null 类型的属性也处理为默认值。

**Comment by 2881099** [comment]
暂时只对 string IsNullable = false 的情况作了处理。

改动较简单，未专门测试这个功能。

整体 5038 个单元测试已通过。
