### ISSUE TITLE
Freesql功能一些建议:增加update 的 whereif方法;orderbyIF 冗余方法

### ISSUE THREAD

**Issue by sundayisblue** [dotnetcore/FreeSql#446]
2个建议:
1 update 没有whereif，是否可以考虑增加个。虽然此场景不多见，但还是有人需要用，希望增加个。

2 orderbyIF ，是否可以考虑增加个。虽然OrderBy(true, a=>a.Id)实现了类似功能，但是有很多朋友根据whereIF会猜到orderbyIF，为了避免解释，还是建议增加个orderbyIF冗余方法

**Comment by 2881099** [comment]
- 增加 IUpdate/IDelete WhereIf 方法；
https://github.com/dotnetcore/FreeSql/commit/9e9891ded45dfa5a8f14e33ef63bff38c84c31ba
