### ISSUE TITLE
Repository对象多线程不安全

### ISSUE THREAD

**Issue by xiahaook** [dotnetcore/FreeSql#448]
能否具体说明下原因吗？使用中好避免

**Comment by 2881099** [comment]
不要同时多个线程使用一个repository对象就行

**Comment by xiahaook** [comment]
我在线程里面使用var userRepository = fsql.GetGuidRepository<User>();  并使用工作单元不影响吧

**Comment by xiahaook** [comment]
如果freesql 对象不定义为静态对象，是不是就不会共一个DbConnection

**Comment by 2881099** [comment]
freesql 单例，是线程安全的。

repository, unitofwork 线程不安全。

可以把 freesql 看航母，repository, unitofwork 看成小飞机。

**Comment by 2881099** [comment]
航母可以派出多架小飞机作战，小飞机只能听命一次。

**Comment by xiahaook** [comment]
![image](https://user-images.githubusercontent.com/34829364/92106148-8b2e9b00-ee16-11ea-9c79-eabff0b29d78.png)
我想请问xi下这里是每次都会重新获取一个新的连接对象吗?

**Comment by 2881099** [comment]
是的，unitofwork 的话就是固定用一个连接

**Comment by 2881099** [comment]
> > freesql 单例，是线程安全的。
> > repository, unitofwork 线程不安全。
> > 可以把 freesql 看航母，repository, unitofwork 看成小飞机。
> 
> 这里的repository 如果在不同线程我都 fsql.GetGuidRepository()重新获取，是不是就可以线程安全了

Get两个对象了，没线程问题

**Comment by xiahaook** [comment]
> > > freesql 单例，是线程安全的。
> > > repository, unitofwork 线程不安全。
> > > 可以把 freesql 看航母，repository, unitofwork 看成小飞机。
> > 
> > 
> > 这里的repository 如果在不同线程我都 fsql.GetGuidRepository()重新获取，是不是就可以线程安全了
> 
> Get两个对象了，没线程问题

感谢回复，明白了

**Comment by xiahaook** [comment]
还请教下，FluentApi以后会做成可以注入的方式吗？

**Comment by 2881099** [comment]
FluentApi 是实体的配置，用不用注入没关系

**Comment by xiahaook** [comment]
因为现在需要单独在外部统一配置好；
如果可以这样，就可以把这一部分配置抽象出去
  public class UserRoleRelationConfig:IEntityTypeConfiguration<UserRoleRelation>
   {
       public void Configure(EntityTypeBuilder<UserRoleRelation> builder)
       {
            builder.ToTable("T_UserRoleRelations");

            /**
             * 多对多:不用中间实体的多对多还不支持，要自己拆成用中间实体的两对一对多。
             * EF中（一对多）写法：builder.HasRequired(e => e.Role).WithMany();
             */
            builder.HasOne(e => e.Role).WithMany().HasForeignKey(e => e.RoleId).IsRequired();
            builder.HasOne(e => e.User).WithMany().HasForeignKey(e => e.UserId).IsRequired();
        }
   }

**Comment by xiahaook** [comment]
> FluentApi 是实体的配置，用不用注入没关系

你好，如果我是复合主键，FluentApi 怎么设置

**Comment by 2881099** [comment]
如果是 ef fluent api 风格，用他的语法设置。

如果是实体特性，在多个属性上标记 [Key] 或者 [Column(IsPrimary = true)]。

如果是 freesql fluent api 风格，

fsql.ConfigEntity\<T\>(e =>
{
  e.Property(p => p.Id1).IsPrimary(true);
  e.Property(p => p.Id2).IsPrimary(true);
});
