### ISSUE TITLE
参数化查询时，字符串条件使用NVarchar 有性能影响

### ISSUE THREAD

**Issue by xiahaook** [dotnetcore/FreeSql#451]
在查询语句中使用嵌套查询时，nvarchar的参数值与数据字段varchar匹配时有性能影响
FreeSql考虑可以指定string转 DbType吗？

**Comment by 2881099** [comment]
请提供实体类，查询代码，监视得到的 SQL。

> SqlServer nvarchar/varchar 已兼容表达式解析，分别解析为：N'' 和 ''，优化索引执行计划；

这项优化已经做过了，具体问题提供代码再说。

**Comment by xiahaook** [comment]
![image](https://user-images.githubusercontent.com/34829364/92231956-40795580-eee0-11ea-91de-a2bd0a156ad0.png)

**Comment by xiahaook** [comment]
你看【StoreHouseCode】这个字段是varchar,但是我条件用N'9401'；
生成的计划逻辑读取次数就翻倍了。

**Comment by xiahaook** [comment]
![image](https://user-images.githubusercontent.com/34829364/92232265-d7461200-eee0-11ea-8c78-cdd0381223a8.png)

**Comment by xiahaook** [comment]
dapper里面会全局有个指定string->varchar还是string ->nvarchar；默认情况下string ->nvarchar；
但是全局指定string->varchar，也有需要处理的，插入和更新时就需要针对有特殊字符的字段强制使用nvarchar

**Comment by 2881099** [comment]
没有看见 c# 代码？ freesql 代码，和实体类呢？

**Comment by 2881099** [comment]
freesql 默认会处理 nvarchar varchar，所以你还是把代码发出来看下吧

**Comment by xiahaook** [comment]
我看到框架中string默认对应nvarchar；如果出现这种参数化查询时，就是这样的代码

**Comment by xiahaook** [comment]
因为我之前用dapper时就出现这样的查询问题，

**Comment by xiahaook** [comment]
> freesql 默认会处理 nvarchar varchar，所以你还是把代码发出来看下吧
忘记说了，我使用的是这个方法
 public DataTable ExecuteDataTable(string cmdText, object parms = null) => ExecuteDataTable(null, null, CommandType.Text, cmdText, GetDbParamtersByObject(cmdText, parms));

**Comment by xiahaook** [comment]
> > freesql 默认会处理 nvarchar varchar，所以你还是把代码发出来看下吧
> > 忘记说了，我使用的是这个方法
> > public DataTable ExecuteDataTable(string cmdText, object parms = null) => ExecuteDataTable(null, null, CommandType.Text, cmdText, GetDbParamtersByObject(cmdText, parms));

我知道freesql通过实体映射没有问题。

**Comment by 2881099** [comment]
ado 这里确实没处理

**Comment by xiahaook** [comment]
不好意思，开始没有表达清楚。
因为项目里面会用到这样的方式进行查询
这个地方要是像dapper一样，增加一个DynamicParameters 来传递参数会不会好一点，就可以指定参数类型
