### ISSUE TITLE
使用ado查询时，需要使用主库

### ISSUE THREAD

**Issue by xiahaook** [dotnetcore/FreeSql#452]
public IList<SY_RolePermission> GetPermissions(string roleID)
        {
            string sql = @"SELECT  F.*
                            FROM dbo.SY_RolePermission AS F
                            WHERE [RoleID] = @RoleID";

            var list = base.Orm.Ado.Query<SY_RolePermission>(base.Orm.Ado.MasterPool.Get().Value, null, sql, new
            {
                RoleID = roleID
            });

            return list;
        }
ado时，使用主库查询是不是只能这样？
这里暂时用了一个简单sql，正常情况下这里会有一个复杂查询

**Comment by 2881099** [comment]
Ado.MasterPool.Get() 要用 using 使用，不然过一会就报错连接池已满。

一般不需要自己用这个Ado.MasterPool.Get()，使用一定要知道机制，要归还。

Ado.Query\<T>(“   select ...”)

select 前面空格就会去主库查询。

**Comment by xiahaook** [comment]
> MasterPool.Get

还有这等骚操作，"select 前面空格就会去主库查询" 这个在1.7版本有吗？
