### ISSUE TITLE
IncludeMany  可以再写子查询吗

### ISSUE THREAD

**Issue by wanglantian** [dotnetcore/FreeSql#455]
类似一个省 关联多个市，我想在includeMany 加上市是否在某张表中存在的判断。我用的是仓储方式。还望指点指点

**Comment by wanglantian** [comment]
`public async Task<IResultModel> ListByCityWithChecked(string proId)
        {
            var list = await _resCityInfoRepository.Orm.Select<ResCityInfo>()
                .IncludeMany(p => p.Franchisees.Select(o=> new PlatFranchisee { 
                    ID = o.ID,
                    Name = o.Name,
                    Checked = _proFranRepository.Orm.Select<ProFran>().Any(b=>b.ProId == proId && b.FranId == o.ID)
                }), then => then.Where(p => p.DataStaus == 1 && p.RecordStatus == 1).OrderBy(p => p.Name))
                .OrderBy(p => p.Pinyin)
                .ToListAsync();

            var data = _mapper.Map<List<FranCityOutput>>(list);

            return ResultModel.Success(data);
        }`
目前我这样写，可以起作用，但是有点画蛇添足的感觉

**Comment by 2881099** [comment]
includeMany 参数部分不能使用 Select Dto(其他实体类型)

**Comment by wanglantian** [comment]
知道了。我再去看看
