### ISSUE TITLE
Respository模式下状态管理会自动清空吗？

### ISSUE THREAD

**Issue by xiahaook** [dotnetcore/FreeSql#458]
你好，我使用在服务里面代码，服务我通过
 var servicesTypes = typesR.Where(t => typeof(IService).IsAssignableFrom(t));
builder.RegisterTypes(servicesTypes.ToArray()).AsImplementedInterfaces().InstancePerDependency();
服务我通过autofac注册，请问下面的仓储中状态管理什么时候清空？是否需要我手动清空？

public class MenuDomainService : IMenuDomainService
{
        private IBaseRepository<SY_Menu> _menuRepository;
        private IFreeSql _freeSql;

        public MenuDomainService(IFreeSql freeSql)
        {
            _menuRepository = freeSql.GetRepository<SY_Menu>();
            _freeSql = freeSql;
        }
        public IList<SY_Menu> GetList()
        {
            var list = _menuRepository.Where(x => x.IsStop == false).ToList();
            return list;
        }
}

**Comment by 2881099** [comment]
gc 会自动清除，不用手工管理

**Comment by xiahaook** [comment]
是我使用有问题吗？我的这种写法感觉一只没有处理

**Comment by xiahaook** [comment]
可以了
