### ISSUE TITLE
分页查询能否将Count(),Page() 放到ToList 之后

### ISSUE THREAD

**Issue by windhuan** [dotnetcore/FreeSql#459]
分页查询能否将Count(),Page() 放到ToList 之后

目前用法
fsql.Select<Box>().Count(out var total).Page(1,10).ToList(p=>new {p.Id})

当我在实现一个统一分页扩展函数的时候遇到了问题,即我没办法在函数内部确定Dto的类型

```
        public static PagedData<T> ToPagedData<T>(this ISelect<T> query, QueryParams queryParams) where T : class
        {
            PagedData<T> result = new PagedData<T>();
            int totalPage = 0;
            queryParams = queryParams ?? new QueryParams();
            query = query.OrderBy(queryParams.IsOrderBy, queryParams.OrderByString);
            result.Data = query.Count(out var totalCount).Page(queryParams.PageNo, queryParams.PageSize).ToList();
            result.PageNo = queryParams.PageNo;
            result.PageSize = queryParams.PageSize;
            result.TotalCount = totalCount;
            result.TotalPage = totalPage;
            return result;
        }
```

理想用法
fsql.Select<Box>().ToList(p=>new {p.Id}).Count(out var total).Page(1,10)

**Comment by 2881099** [comment]
count 不需要知道 dto 类型，可以放在前面

**Comment by windhuan** [comment]
我将函数实现贴上了， 使用ef的时候可以这样调用 query.Select(p=>new {p.id}).ToPagedData(queryParams);
函数内部也可以根据dto的字段进行排序 和前端传入的保持一致
我也尝试了使用AsQueryable后进行使用,但是发现AsQueryable只支持单表

**Comment by 2881099** [comment]
明白了，可以引用 FreeSql.Extensions.Linq，这里面定义了 Select 方法


fsql.Select<T>().Select(a=>new {}).Count(out var total).Page(1,20).ToList()

**Comment by windhuan** [comment]
好的 谢谢
