### ISSUE TITLE
有类似ef的全局filter吗？用来全局过滤IsDeleted=1?

### ISSUE THREAD

**Issue by hiwjcn** [dotnetcore/FreeSql#460]
类似这样的api：
```csharp
            builder.HasQueryFilter(x => x.IsDeleted == 0);
```

另外希望fluent map api是主流的配置方式，可以避免污染entity。
试用了一下freesql，api很简单。感谢团队的付出，同时希望坚持维护下去：）

**Comment by 2881099** [comment]
FreeSql 基础层实现了 Select/Update/Delete 可设置的全局过滤器功能。

```csharp
public static AsyncLocal<Guid> TenantId { get; set; } = new AsyncLocal<Guid>();

fsql.GlobalFilter
    .Apply<TestAddEnum>("test1", a => a.Id == TenantId.Value)
    .Apply<AuthorTest>("test2", a => a.Id == 111)
    .Apply<AuthorTest>("test3", a => a.Name == "11")
    .ApplyIf<TestAddEnum>("test4", () => TenantId.Value != Guid.Empty, a => a.Id == TenantId.Value);
    //1.9.0 ApplyIf 委托的返回值(第二个参数) true 才生效
```

Apply 泛型参数可以设置为任何类型，当使用 Select/Update/Delete 方法时会进行过滤器匹配尝试（try catch）：

- 匹配成功的，将附加 where 条件；
- 匹配失败的，标记下次不再匹配，避免性能损耗；

如何禁用？

```csharp
fsql.Select<TestAddEnum>().ToList(); //所有生效
fsql.Select<TestAddEnum>().DisableGlobalFilter("test1").ToList(); //禁用 test1
fsql.Select<TestAddEnum>().DisableGlobalFilter().ToList(); //禁用所有
```

fsql.Update/Delete 方法效果同上。

**Comment by 2881099** [comment]
不用为每个实体类设置过滤条件。

更多资料：https://github.com/dotnetcore/FreeSql/wiki/%E8%BF%87%E6%BB%A4%E5%99%A8

**Comment by 2881099** [comment]
目前是设计成 Build 之后使用的，全局只需执行一次设置，fsql.GlobalFilter.Apply\<ISoftDelete>(“softdelete”, a=> a.IsDeleted == true);

**Comment by hiwjcn** [comment]
谢谢 可以关闭issue了
