### ISSUE TITLE
UnitOfWorkManager,DbContextScopedFreeSql 两个类能否考虑分别提取接口，项目中关联的地方也改为关联接口，谢谢！！

### ISSUE THREAD

**Issue by jianliulin** [dotnetcore/FreeSql#461]
UnitOfWorkManager,DbContextScopedFreeSql 两个类能否考虑分别提取接口，项目中关联的地方也改为关联接口，

这样可以方便 注入的时候替换， services.AddScoped<IUnitOfWorkManager, MyUnitOfWorkManager>();

另外,UnitOfWorkManager 中的 _ormScoped 访问范围能否改为 protected，方便继承时可变更。
    public class UnitOfWorkManager : IDisposable
    {
    **protected** DbContextScopedFreeSql _ormScoped;
    ......
    }

**Comment by 2881099** [comment]
_ormScoped 可以通用 .Orm 访问，这个会定义在 IUnitOfWorkManager 内。

**Comment by 2881099** [comment]
刚才看了代码评估改动， IUnitOfWorkManager 这个暂时调不了，会影响旧的使用习惯。

其实可以自己再包装一下，也挺简单。

目前 UnitOfWorkManager 只用在了 DefaultRepository 构造函数上面，重新实现一个 MyRepository : BaseRepository 改变构造参数即可。
