### ISSUE TITLE
leftjoin 后面写动态条件，不是显示在on 条件后面，而是加载在where后面

### ISSUE THREAD

**Issue by wanglantian** [dotnetcore/FreeSql#464]
Hi,晚上好

遇到这样一个问题，希望能讨教讨教
leftjoin 是这样写的，希望 starttime  和 endTime 能动态加在on条件后面
 var list = await _platFranchiseeRepository.Orm.Select<PlatFranchisee, ProOrder>()
                .LeftJoin((a, b) => b.FranId == a.ID && (model.StartTime.HasValue ? (b.CreatedDate > model.StartTime) : true)
                && (model.EndTime.HasValue ? (b.CreatedDate < model.EndTime) : true) && b.PayStatus == 1 && b.TradeType == 2
                )
生成的sql语句  ：
select count(1) from (SELECT 1 as1 
FROM `plat_areamanager` a 
LEFT JOIN `plat_franchisee` b ON b.`ManagerId` = a.`ID` AND b.`DataStaus` = 1 AND b.`RecordStatus` = 1 
LEFT JOIN `pro_order` c ON c.`FranId` = b.`ID` AND c.`PayStatus` = 1 AND c.`TradeType` = 2 
WHERE (c.`CreatedDate` > '2020-09-01 00:00:00.000') AND (c.`CreatedDate` < '2020-09-30 00:00:00.000') AND (a.`RecordStatus` = 1) 
GROUP BY a.`ID`) fta;

加载到where后面了。
请问怎么能加这条件动态加在on后面呢

**Comment by 2881099** [comment]
你发的代码是两个表查询，但是sql是三个表？

**Comment by wanglantian** [comment]
在外面一层我有获取在plat_areamanager中的plat_franchisee 集合，然后在代码中通过contains来处理的，sql好像给优化处理
查询代码如下,有个franIds.Contains：
` var list = await _platFranchiseeRepository.Orm.Select<PlatFranchisee, ProOrder>()
                .LeftJoin((a, b) => b.FranId == a.ID && (model.StartTime.HasValue ? (b.CreatedDate > model.StartTime) : true)
                && (model.EndTime.HasValue ? (b.CreatedDate < model.EndTime) : true) && b.PayStatus == 1 && b.TradeType == 2
                
                )
                .WhereIf(model.FranName.NotNull(), (a, b) => a.Name.Contains(model.FranName))
                .Where((a, b) => a.DataStaus == 1 && a.RecordStatus == 1 && franIds.Contains(a.ID))
                .GroupBy((a, b) => a.ID)
                 .OrderByDescending(p => p.Sum(p.Value.Item2.OrderPoint))
                .Count(out var total)
                .Skip(model.IDisplayStart)
                .Take(model.IDisplayLength)
                .ToListAsync(p => new FranSaleStatisticOutput
                {
                    FranName = p.Max(p.Value.Item1.Name),
                    SalePoint = (int)p.Sum(p.Value.Item2.OrderPoint),
                    UseCash = p.Sum(p.Value.Item2.UseCashAmt)//,
                    //UsePoint = (int)p.Sum(p.Value.Item2.UsedPoint),
                    //Profit = p.Sum(p.Value.Item2.OrderPoint) - p.Sum(p.Value.Item2.FranInputPrice)
                });`

**Comment by 2881099** [comment]
整个查询代码，没有看到 plat_areamanager，但是1楼的SQL有 plat_areamanager

**Comment by wanglantian** [comment]
我先后调用了两个方法，第一次获取集合：
` public async Task<List<string>> GetFranList()
        {
            var franList = new List<string>();

            var managerId = await _platAreaManagerRepository
                .Where(p => p.UserId == _user.Id && p.RecordStatus == 1)
                .ToOneAsync(p => p.ID);

            if (string.IsNullOrEmpty(managerId)) {
                return franList;
            }

            var list = await _platFranchiseeRepository
                .Where(p => p.ManagerId == managerId && p.DataStaus == 1 && p.RecordStatus == 1)
                .ToListAsync(p => p.ID);

            return list;
            
        }`

获取到集合之后调第二个方法：
`public async Task<IResultModel> SaleAnalysis(FranSaleQueryInput model,List<string> franIds)
        {
            var list = await _platFranchiseeRepository.Orm.Select<PlatFranchisee, ProOrder>()
                .LeftJoin((a, b) => b.FranId == a.ID && (model.StartTime.HasValue ? (b.CreatedDate > model.StartTime) : true)
                && (model.EndTime.HasValue ? (b.CreatedDate < model.EndTime) : true) && b.PayStatus == 1 && b.TradeType == 2
                
                )
                .WhereIf(model.FranName.NotNull(), (a, b) => a.Name.Contains(model.FranName))
                .Where((a, b) => a.DataStaus == 1 && a.RecordStatus == 1 && franIds.Contains(a.ID))
                .GroupBy((a, b) => a.ID)
                 .OrderByDescending(p => p.Sum(p.Value.Item2.OrderPoint))
                .Count(out var total)
                .Skip(model.IDisplayStart)
                .Take(model.IDisplayLength)
                .ToListAsync(p => new FranSaleStatisticOutput
                {
                    FranName = p.Max(p.Value.Item1.Name),
                    SalePoint = (int)p.Sum(p.Value.Item2.OrderPoint),
                    UseCash = p.Sum(p.Value.Item2.UseCashAmt)//,
                    //UsePoint = (int)p.Sum(p.Value.Item2.UsedPoint),
                    //Profit = p.Sum(p.Value.Item2.OrderPoint) - p.Sum(p.Value.Item2.FranInputPrice)
                });

            var data = new TablePageOutput<FranSaleStatisticOutput>()
            {
                AaData = list,
                ITotalDisplayRecords = total,
                ITotalRecords = total,
                SEcho = model.SEcho
            };

            return ResultModel.Success(data);
        }`
通过UseMonitorCommand检测到的sql语句是合并过的，我以为是做了优化处理

**Comment by wanglantian** [comment]
尴尬了，不好意思，跟踪的方法错了。。。您先忙
