### ISSUE TITLE
Oracle CodeFirst 同步表结构的问题

### ISSUE THREAD

**Issue by kklldog** [dotnetcore/FreeSql#465]
hi ，使用freesql操作Oracle的时候使用freesql.CodeFirst.SyncStructure<App>() 同步表的时候报以下错误：
System.TypeInitializationException:“The type initializer for 'AgileConfig.Server.Data.Freesql.FreeSQL' threw an exception.”
OracleException: ORA-00907: 缺失右括号
ORA-06512: 在 line 2

我打印了一下生成的SQL在plsql里直接执行也会报错，不知道是不是Oracle版本问题？
BEGIN 
execute immediate 'CREATE TABLE "CLINIC"."app" (  
  "id" NVARCHAR(36), 
  "name" NVARCHAR(50), 
  "secret" NVARCHAR(36), 
  "create_time" TIMESTAMP(6) NOT NULL, 
  "update_time" TIMESTAMP(6) NULL, 
  "enabled" NUMBER(1) NOT NULL, 
  CONSTRAINT "CLINIC_app_pk1" PRIMARY KEY ("id")
) 
LOGGING 
NOCOMPRESS 
NOCACHE
';
END;

**环境：**
Windows 10
Core 3.1
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
TNS for 64-bit Windows: Version 11.2.0.1.0 - Production

**Comment by 2881099** [comment]
检查 Column DbType，实体类属性，定义了不支持的 DbType，就会这样

> 楼主：我知道了 Oracle那叫nvarchar2，但是我做多数据库支持的时候 dbtype不太好写啊

> 解决：Column StringLength = 255，属性定义成 string 类型，不手工设置 DbType。设置成 -1，会变成 nlob
