### ISSUE TITLE
with sql语句分页建议

### ISSUE THREAD

**Issue by hvppy** [dotnetcore/FreeSql#466]
业务有时候会把sql脚本定义在数据库里面,然后动态分页查询,fsql.ado或者fsql.select[dynamic]是不是可以考虑下支持分页查询呢

**Comment by luoyunchong** [comment]
```
   string sql = "select * from dbo.blog";
   DataTable dt = _fsql.Select<object>().WithSql(sql).Page(1,10).ToDataTable("*")
```

**Comment by hvppy** [comment]
> ```
>    string sql = "select * from dbo.blog";
>    DataTable dt = _fsql.Select<object>().WithSql(sql).Page(1,10).ToDataTable("*")
> ```

page(2,10) 就会有错误产生
System.InvalidOperationException: Sequence contains no elements

**Comment by 2881099** [comment]
> > ```
> >    string sql = "select * from dbo.blog";
> >    DataTable dt = _fsql.Select<object>().WithSql(sql).Page(1,10).ToDataTable("*")
> > ```
> 
> 
> page(2,10) 就会有错误产生
> 
> System.InvalidOperationException: Sequence contains no elements

是 sqlserver 吗，是有可能， sqlserver 分页依赖排序字段，object 找不到排序字段，手工设置 OrderBy(“getdate()”).Page(1, 20).ToList() 就行了

**Comment by hvppy** [comment]
> > > ```
> > >    string sql = "select * from dbo.blog";
> > >    DataTable dt = _fsql.Select<object>().WithSql(sql).Page(1,10).ToDataTable("*")
> > > ```
> > 
> > 
> > page(2,10) 就会有错误产生
> > System.InvalidOperationException: Sequence contains no elements
> 
> 是 sqlserver 吗，是有可能， sqlserver 分页依赖排序字段，object 找不到排序字段，手工设置 OrderBy(“getdate()”).Page(1, 20).ToList() 就行了

可以了,谢谢!

**Comment by hyzx86** [comment]
这个问题好难定位啊 ， 能不能优化下这个地方的错误提示啊？

**Comment by 2881099** [comment]
```c#
List<object> list = fsql.Select<object>().WithSql("select * from user1").ToList();

SELECT *
FROM ( select * from user1 ) a
```

下个版本已优化，返回 List\<字典\>
