### ISSUE TITLE
请教：实体特性中如何设置数据格式，例如：日期（yyyy-MM-dd）

### ISSUE THREAD

**Issue by songwk596** [dotnetcore/FreeSql#468]
请教：实体特性中如何设置数据格式，例如：日期（yyyy-MM-dd）

**Comment by 2881099** [comment]
是指查询返回数据的时候设置吗？

.ToList(a => a.CreateTime.ToString("yyyy-MM-dd"))

## 日期格式化
```c#
var t4 = fsql.Select<T>()
  .First(a => a.CreateTime.ToString("HH:mm:ss");
// SELECT date_format(a.`CreateTime`, '%H:%i:%s') as1 
// FROM `xxx` a 
// limit 0,1
```

> v1.5.0 支持了常用 c# 日期格式化，yyyy MM dd HH mm ss yy M d H hh h m s tt t

> tt t 为 AM PM
