### ISSUE TITLE
FreeSql v2.0.0 版本征集意见，年底发布

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#469]
感谢大家近两年的陪伴，和持续给出的优化建议，让 FreeSql 从无到有越来越强大。

FreeSql v2.0.0 版本现征集意见，年底发布。

欢迎跟帖发表你的需求意见。

**Comment by DoyouNetwork** [comment]
我技术有限只能说一句牛逼!~~

**Comment by tianxin8206** [comment]
支持tidb

**Comment by wangjunniit** [comment]
### 叶老板牛逼！！！！！！！！！！！！！

### 希望实现DbContext级别的过滤器。

比如有个需求，根据http请求header里的某个值增加过滤条件，伪代码如下：
```c#
public void ConfigureServices(IServiceCollection services) 
{
  services.AddSingleton<IFreeSql>(Fsql);
  services.AddFreeDbContext<SongContext>(options => options.UseFreeSql(Fsql));
}

public ValuesController(SongContext songContext) 
{
}
```
```c#
public interface ITenant 
{
    string TenantId { get; set; }
}

public class Song : ITenant
{
     public string TenantId { get; set; }
}

public class SongContext : DbContext 
{

    private string _tenantId;

    public DbSet<Song> Songs { get; set; }

    public SongContext (IHttpContextAccessor httpContextAccessor)
    {
         _tenantId = httpContextAccessor.HttpContext.Request.Headers["TenantId"];
    }

    protected override void OnModelCreating(ICodeFirst codefirst)
    {
        codefirst.AddQueryFilter<ITenant>( t => t.Tenant == _tenantId );
    }
}
```

**Comment by wangjunniit** [comment]
### 有没有可能与[https://github.com/dotnetcore/CAP](url)集成

CAP的常见用法下面两种，关键点是与一个Transaction进行关联
```c#
public class PublishController : Controller
{
    private readonly ICapPublisher _capBus;

    public PublishController(ICapPublisher capPublisher)
    {
        _capBus = capPublisher;
    }

    [Route("~/adonet/transaction")]
    public IActionResult AdonetWithTransaction()
    {
        using (var connection = new MySqlConnection(ConnectionString))
        {
            using (var transaction = connection.BeginTransaction(_capBus, autoCommit: true))
            {
                //your business logic code

                _capBus.Publish("xxx.services.show.time", DateTime.Now);
            }
        }

        return Ok();
    }

    [Route("~/ef/transaction")]
    public IActionResult EntityFrameworkWithTransaction([FromServices]AppDbContext dbContext)
    {
        using (var trans = dbContext.Database.BeginTransaction(_capBus, autoCommit: true))
        {
            //your business logic code

            _capBus.Publish("xxx.services.show.time", DateTime.Now);
        }

        return Ok();
    }
}
```
叶老板要不要考虑下

**Comment by luoyunchong** [comment]
@wangjunniit https://github.com/luoyunchong/DotNetCore.CAP.Provider

2种方式。
- 1.扩展方法中反射调用内部Flush方法。
- 2.修改源码中对应的switch代码，需要在其中引用freesql相关代码。

https://github.com/luoyunchong/DotNetCore.CAP.Provider/issues/1

**Comment by NMSAzulX** [comment]
### 在做封装的时遇到的问题：
    
如果使用 Freesql 自带的 JoinIn 泛型方法则没办法自定义外联表别名, 但使用不带泛型的 Join 方法参数就写死了字符串，不能兼容其他特殊语法的数据库了，所以那个泛型方法希望改进一下。  

#### 建议： Left/Inner/RightJoin(exp)  API 增加一个参数，即自定义别名，` LeftJoin(exp,string alias=default) `
#### 优点：
1、不耽误旧版本的使用
2、当 ToList<TReturn>(string)  API 支持匿名类映射后，参数需支持灵活多变的调整，以便返回表和匿名类字段一一对应，此时 JOIN 查询方法提供了别名方法之后，开发者可以手动构造 ToList 方法的参数来调整匿名类映射，封装起来极有用。
#### 例如：
```C# 

 LeftJoin< OutTable >(exp,  "MyAliasOut").
ToList<XXX>("MyAliasOut.Name AS MyName ");

```

**Comment by 2881099** [comment]
> ### 叶老板牛逼！！！！！！！！！！！！！
> ### 希望实现DbContext级别的过滤器。
> 比如有个需求，根据http请求header里的某个值增加过滤条件，伪代码如下：
> 
> ```cs
> public void ConfigureServices(IServiceCollection services) 
> {
>   services.AddSingleton<IFreeSql>(Fsql);
>   services.AddFreeDbContext<SongContext>(options => options.UseFreeSql(Fsql));
> }
> 
> public ValuesController(SongContext songContext) 
> {
> }
> ```
> 
> ```cs
> public interface ITenant 
> {
>     string TenantId { get; set; }
> }
> 
> public class Song : ITenant
> {
>      public string TenantId { get; set; }
> }
> 
> public class SongContext : DbContext 
> {
> 
>     private string _tenantId;
> 
>     public DbSet<Song> Songs { get; set; }
> 
>     public SongContext (IHttpContextAccessor httpContextAccessor)
>     {
>          _tenantId = httpContextAccessor.HttpContext.Request.Headers["TenantId"];
>     }
> 
>     protected override void OnModelCreating(ICodeFirst codefirst)
>     {
>         codefirst.AddQueryFilter<ITenant>( t => t.TenantId == _tenantId );
>     }
> }
> ```

目前 FreeSql.Repository 有仓储级别的过滤器，还有全局过滤器。文档：https://github.com/dotnetcore/FreeSql/wiki/%E8%BF%87%E6%BB%A4%E5%99%A8

**Comment by 2881099** [comment]
> ### 在做封装的时遇到的问题：
> 如果使用 Freesql 自带的 JoinIn 泛型方法则没办法自定义外联表别名, 但使用不带泛型的 Join 方法参数就写死了字符串，不能兼容其他特殊语法的数据库了，所以那个泛型方法希望改进一下。
> 
> #### 建议： Left/Inner/RightJoin(exp) API 增加一个参数，即自定义别名，`LeftJoin(exp,string alias=default)`
> #### 优点：
> 1、不耽误旧版本的使用
> 2、当 ToList(string) API 支持匿名类映射后，参数需支持灵活多变的调整，以便返回表和匿名类字段一一对应，此时 JOIN 查询方法提供了别名方法之后，开发者可以手动构造 ToList 方法的参数来调整匿名类映射，封装起来极有用。
> 
> #### 例如：
> ```cs
>  LeftJoin< OutTable >(exp,  "MyAliasOut").
> ToList<XXX>("MyAliasOut.Name AS MyName ");
> ```

大帅，是针对 LeftJoin\<T2\>((a,b) => a.id == b.id) 这个方法吗？这个方法别名是 lambda 参数名 b

**Comment by 2881099** [comment]
> 支持tidb

不知道引用 FreeSql.Provider.MySqlConnector.dll 能不能访问，等有空了搭建好环境了试试

**Comment by NMSAzulX** [comment]
> > ### 在做封装的时遇到的问题：
> > 如果使用 Freesql 自带的 JoinIn 泛型方法则没办法自定义外联表别名, 但使用不带泛型的 Join 方法参数就写死了字符串，不能兼容其他特殊语法的数据库了，所以那个泛型方法希望改进一下。
> > #### 建议： Left/Inner/RightJoin(exp) API 增加一个参数，即自定义别名，`LeftJoin(exp,string alias=default)`
> > #### 优点：
> > 1、不耽误旧版本的使用
> > 2、当 ToList(string) API 支持匿名类映射后，参数需支持灵活多变的调整，以便返回表和匿名类字段一一对应，此时 JOIN 查询方法提供了别名方法之后，开发者可以手动构造 ToList 方法的参数来调整匿名类映射，封装起来极有用。
> > #### 例如：
> > ```cs
> >  LeftJoin< OutTable >(exp,  "MyAliasOut").
> > ToList<XXX>("MyAliasOut.Name AS MyName ");
> > ```
> 
> 大帅，是针对 LeftJoin<T2>((a,b) => a.id == b.id) 这个方法吗？这个方法别名是 lambda 参数名 b

LeftJoin/RightJoin/InnerJoin  如果多表联合查询的话 这种命名怕是不太妥，如果加上参数，你的方法里可以判断以下，如果有命名了就用参数的命名，没有命名，就用b,  这样开放出来API对于二次开发的人员更加友好。

**Comment by lzw5399** [comment]
有没有计划支持一下SAP HANA。。。最近着实被这玩意搞得有点难受

**文档地址：**
https://help.sap.com/viewer/b3ee5778bc2e4a089d3299b82ec762a7/2.0.02/en-US/9165807e2ded490ea06f46035c3e58b1.html

**Comment by 2881099** [comment]
> > > ### 在做封装的时遇到的问题：
> > > 如果使用 Freesql 自带的 JoinIn 泛型方法则没办法自定义外联表别名, 但使用不带泛型的 Join 方法参数就写死了字符串，不能兼容其他特殊语法的数据库了，所以那个泛型方法希望改进一下。
> > > #### 建议： Left/Inner/RightJoin(exp) API 增加一个参数，即自定义别名，`LeftJoin(exp,string alias=default)`
> > > #### 优点：
> > > 1、不耽误旧版本的使用
> > > 2、当 ToList(string) API 支持匿名类映射后，参数需支持灵活多变的调整，以便返回表和匿名类字段一一对应，此时 JOIN 查询方法提供了别名方法之后，开发者可以手动构造 ToList 方法的参数来调整匿名类映射，封装起来极有用。
> > > #### 例如：
> > > ```cs
> > >  LeftJoin< OutTable >(exp,  "MyAliasOut").
> > > ToList<XXX>("MyAliasOut.Name AS MyName ");
> > > ```
> > 
> > 
> > 大帅，是针对 LeftJoin((a,b) => a.id == b.id) 这个方法吗？这个方法别名是 lambda 参数名 b
> 
> LeftJoin/RightJoin/InnerJoin 如果多表联合查询的话 这种命名怕是不太妥，如果加上参数，你的方法里可以判断以下，如果有命名了就用参数的命名，没有命名，就用b, 这样开放出来API对于二次开发的人员更加友好。

.LeftJoin("table2 AS MyAliasOut on a.id = MyAliasOut.xxid")

ToList<xxx>("MyAliasOut.Name AS MyName")

如果这样使用是否可行，都是纯字符串操作。

**Comment by 2881099** [comment]
> 有没有计划支持一下SAP HANA。。。最近着实被这玩意搞得有点难受
> 
> **文档地址：**
> https://help.sap.com/viewer/b3ee5778bc2e4a089d3299b82ec762a7/2.0.02/en-US/9165807e2ded490ea06f46035c3e58b1.html

## 今天做了调研：

1、从文档来看，技术上实现起来问题不大（都是关系型数据库），适配需要时间

2、从 nuget 上下载量来看（参数的 linq2db），实在太少

## 暂时作出的决定：

国内大环境正在实行”安可“国产化，我们更希望多点支持国产数据库。

从 nuget 查看下载量太少，暂时不会安排支持该数据库。

## 建议：

可以参考 Odbc 通用方案进行适配访问 SAP HANA，文档：https://github.com/dotnetcore/FreeSql/blob/master/Providers/FreeSql.Provider.Odbc/readme.md

该方案需要自己重写一套适配器：https://github.com/dotnetcore/FreeSql/blob/master/Providers/FreeSql.Provider.Odbc/Default/OdbcAdapter.cs

**Comment by NMSAzulX** [comment]
> > > > ### 在做封装的时遇到的问题：
> > > > 如果使用 Freesql 自带的 JoinIn 泛型方法则没办法自定义外联表别名, 但使用不带泛型的 Join 方法参数就写死了字符串，不能兼容其他特殊语法的数据库了，所以那个泛型方法希望改进一下。
> > > > #### 建议： Left/Inner/RightJoin(exp) API 增加一个参数，即自定义别名，`LeftJoin(exp,string alias=default)`
> > > > #### 优点：
> > > > 1、不耽误旧版本的使用
> > > > 2、当 ToList(string) API 支持匿名类映射后，参数需支持灵活多变的调整，以便返回表和匿名类字段一一对应，此时 JOIN 查询方法提供了别名方法之后，开发者可以手动构造 ToList 方法的参数来调整匿名类映射，封装起来极有用。
> > > > #### 例如：
> > > > ```cs
> > > >  LeftJoin< OutTable >(exp,  "MyAliasOut").
> > > > ToList<XXX>("MyAliasOut.Name AS MyName ");
> > > > ```
> > > 
> > > 
> > > 大帅，是针对 LeftJoin((a,b) => a.id == b.id) 这个方法吗？这个方法别名是 lambda 参数名 b
> > 
> > 
> > LeftJoin/RightJoin/InnerJoin 如果多表联合查询的话 这种命名怕是不太妥，如果加上参数，你的方法里可以判断以下，如果有命名了就用参数的命名，没有命名，就用b, 这样开放出来API对于二次开发的人员更加友好。
> 
> .LeftJoin("table2 AS MyAliasOut on a.id = MyAliasOut.xxid")
> 
> ToList("MyAliasOut.Name AS MyName")
> 
> 如果这样使用是否可行，都是纯字符串操作。

对 目前就是这样做的。这样做的话语法上就写死了，Pgsql 需要 a."id" 其他数据库可以直接写 a.id  适配就没办法用 freesql 的了.

**Comment by 2881099** [comment]
其实只要控制好大小写，就没这个问题了。

pgsql 名称不加引号，就会区分大小写。

oracle 名称不加引号，不区分大小写。（反着的）

FreeSqlBuilder 预留了 UseNameConvert 设置专门针对这种情况：

1、pgsql 使用 .UseNameConvert(FreeSql.Internal.NameConvertType.ToLower) 创建的表名、字段名都是用小写的方式，就没有强制要求写引号的问题了。

2、oracle 使用 .UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper) 创建的表名、字段名都是用大写的方式，就没有强制要求写引号的问题了。

NameConvertType 还有其他设置：

```c#
        /// <summary>
        /// 不进行任何处理
        /// </summary>
        None = 0,

        /// <summary>
        /// 将帕斯卡命名字符串转换为下划线分隔字符串
        /// <para></para>
        /// BigApple -> Big_Apple
        /// </summary>
        PascalCaseToUnderscore,

        /// <summary>
        /// 将帕斯卡命名字符串转换为下划线分隔字符串，且转换为全大写
        /// <para></para>
        /// BigApple -> BIG_APPLE
        /// </summary>
        PascalCaseToUnderscoreWithUpper,

        /// <summary>
        /// 将帕斯卡命名字符串转换为下划线分隔字符串，且转换为全小写
        /// <para></para>
        /// BigApple -> big_apple
        /// </summary>
        PascalCaseToUnderscoreWithLower,

        ///// <summary>
        ///// 将下划线分隔字符串命名字符串转换为帕斯卡
        ///// <para></para>
        ///// big_apple -> BigApple
        ///// </summary>
        //UnderscoreToPascalCase,

        /// <summary>
        /// 将字符串转换为大写
        /// <para></para>
        /// BigApple -> BIGAPPLE
        /// </summary>
        ToUpper,

        /// <summary>
        /// 将字符串转换为小写
        /// <para></para>
        /// BigApple -> bigapple
        /// </summary>
        ToLower
```

**Comment by tky753** [comment]
要不要兼容  v1.X  啊，有破坏性更新的话，能不能把 
`TSelect InnerJoin<T2>(Expression<Func<T1, T2, bool>> exp)` 的返回类型变成**ISelect<T1, T2>**  ?
现在 写各种join语句，几乎总是 `.From<T2>((a,b)=>a.XXXJoin(a1=>......)`

**Comment by tianxin8206** [comment]
自动建库的功能能加吗

**Comment by luoyunchong** [comment]
> 自动建库的功能能加吗

如果你使用Mysql或Sql Server，需要自动创建数据库.现阶段可请参考此代码，自行copy，**[FreeSqlExtensions.cs](https://github.com/luoyunchong/dotnetcore-examples/blob/master/ORM/FreeSql/OvOv.FreeSql/FreeSqlExtensions.cs)**

**Comment by litdev** [comment]
sql server下能支持timestamp类型的数据吗

**Comment by JHeLiu** [comment]
Ado 查询
1、希望添加查询单个对象，现在只看到 Query - List<T>  希望有一个  T QuerySingle 查询单个对象的
2、希望对 IN 参数扩展，可以支持  WHERE ID IN @Ids 类似于 dapper 一样

**Comment by kevin100702** [comment]
有没有办法让现有使用ef core的项目快速迁移到freesql， ef core 3把sqlserver 2008的分页模式不兼容了

**Comment by 2881099** [comment]
> 有没有办法让现有使用ef core的项目快速迁移到freesql， ef core 3把sqlserver 2008的分页模式不兼容了

如果实体类使用特性，freesql 能识别 90% 的 efcore 特性。

如果实体类使用fluent api，需要修改 OnModelCreating 参数类型为 ICodeFirst，能兼容大约 70% fluent api 语法。

EF.DbContext 换成 FreeSql.DbContext 可以解决大约 70% 的 crud 问题。

**Comment by LightCHY** [comment]
有没有可能使用类似于Hibernate的HQ查询语言。[https://www.cnblogs.com/bobomail/archive/2005/09/20/240352.html](url)

**Comment by alexinea** [comment]
> 有没有可能使用类似于Hibernate的HQ查询语言。https://www.cnblogs.com/bobomail/archive/2005/09/20/240352.html

Hi, @LightCHY  能简单说说你看中的是 HQL 的哪个点或哪些点么，因为很少用 Hibernate 或 NH，所以我暂时无法想象相对现有的 FreeSql APIs 而言，HQL 所能带来的益处。

**Comment by LightCHY** [comment]
> > 有没有可能使用类似于Hibernate的HQ查询语言。https://www.cnblogs.com/bobomail/archive/2005/09/20/240352.html
> 
> Hi, @LightCHY 能简单说说你看中的是 HQL 的哪个点或哪些点么，因为很少用 Hibernate 或 NH，所以我暂时无法想象相对现有的 FreeSql APIs 而言，HQL 所能带来的益处。

举个例子：使用HQL查询如下：
select order.id, sum(price.amount), count(item)
from Order as order
    join order.lineItems as item
    join item.product as product, Catalog as catalog
    join catalog.prices as price
where order.paid = false
    and order.customer = :customer
    and price.product = product
    and catalog.effectiveDate < sysdate
    and catalog.effectiveDate >= all (
        select cat.effectiveDate 
        from Catalog as cat
        where cat.effectiveDate < sysdate
    )
group by order
having sum(price.amount) > :minAmount
order by sum(price.amount) desc
如果用API的语法来coding是不是写的人与看的人都会很绕，HQL在使用上还是偏向于sql92语法（虽然有一点差距），但一眼就能看明白是什么意思，ORM对于update\delete\insert会好些，主要麻烦的是select，在遇到复杂的查询，不得不转成原始sql，原始sql就失去了Mapping的能力了

**Comment by anyangmaxin** [comment]
我这菜鸟能说啥，当然是支持啦，不过还是希望文档越多越好。

**Comment by fawdlstty** [comment]
提议支持Hive

**Comment by ddabb** [comment]
希望支持 freesql.Insert<T>(ISelect<T>)的语法，
因为感觉 freesql.Insert<T>(ISelect<T>.ToList())中的这部分把 ISelect<T>.ToList()的查询结果在内存中进行处理了。

**Comment by ddabb** [comment]
希望 提供一下 ISelect<T>.ToTreeListSql() 方法，每次都要运行才能看到Sql，我好慌啊。

**Comment by luoyunchong** [comment]
不是有tosql么

**Comment by qtbui159** [comment]
希望在ColumnAttribute中增加Converter，类似于Wpf中的IValueConverter中的设计

**Comment by jianliulin** [comment]
希望有单独同步索引的功能，在生产环境中不太适合同步表字段，但索引会根据使用情况来调整。

**Comment by liuguiyou** [comment]
希望2.0Ado.Query<XX>() 能够支持DataAnnotations特性映射行为，为保持旧版本兼容性，可以通过配置开关进行控制是否开启。

**Comment by HaoZhiYing** [comment]
希望提供类似 java mybatis-plus 类似的功能，让程序写sql 也有一种标准化 工程。让 freesql 变得全面。

**Comment by jj91821** [comment]
现在动态搜索功能比较弱，能否支持OData呢？odata支持分组查询、求和、还支持导航属性等功能蛮强的。

**Comment by jianxuanbing** [comment]
MySql 带有 `.` 的时候需要额外增加分号，是否可以在FluentAPI 那里 自己去解决呢

**Comment by NMSAzulX** [comment]
> @NMSAzulX 其实只要控制好大小写，就没这个问题了。pgsql 名称不加引号，就会区分大小写。oracle 名称不加引号，不区分大小写（反着的）。FreeSqlBuilder 预留了 UseNameConvert 设置专门针对这种情况：
> 
> 1、pgsql 使用 .UseNameConvert(FreeSql.Internal.NameConvertType.ToLower) 创建的表名、字段名都是用小写的方式，就没有强制要求写引号的问题了。
> 
> 2、oracle 使用 .UseNameConvert(FreeSql.Internal.NameConvertType.ToUpper) 创建的表名、字段名都是用大写的方式，就没有强制要求写引号的问题了。
> 
> NameConvertType 还有其他设置：
> 
> ```cs
>         /// <summary>
>         /// 将帕斯卡命名字符串转换为下划线分隔字符串
>         /// <para></para>
>         /// BigApple -> Big_Apple
>         /// </summary>
>         PascalCaseToUnderscore,
> 
>         /// <summary>
>         /// 将帕斯卡命名字符串转换为下划线分隔字符串，且转换为全大写
>         /// <para></para>
>         /// BigApple -> BIG_APPLE
>         /// </summary>
>         PascalCaseToUnderscoreWithUpper,
> 
>         /// <summary>
>         /// 将帕斯卡命名字符串转换为下划线分隔字符串，且转换为全小写
>         /// <para></para>
>         /// BigApple -> big_apple
>         /// </summary>
>         PascalCaseToUnderscoreWithLower,
> 
>         ///// <summary>
>         ///// 将下划线分隔字符串命名字符串转换为帕斯卡
>         ///// <para></para>
>         ///// big_apple -> BigApple
>         ///// </summary>
>         //UnderscoreToPascalCase,
> 
>         /// <summary>
>         /// 将字符串转换为大写
>         /// <para></para>
>         /// BigApple -> BIGAPPLE
>         /// </summary>
>         ToUpper,
> 
>         /// <summary>
>         /// 将字符串转换为小写
>         /// <para></para>
>         /// BigApple -> bigapple
>         /// </summary>
>         ToLower
> ```

这样给建表添加了额外的操作，既然有 Provider 了我肯定要优先使用 Provider 的实现，本身 Provider 可以完成这个功能，我还特意去区分数据库，而且上层封装都不用考虑 Proviedr 的实现，只对 FreeSql 扩展即可， 你说的方案我觉得扩展起来太麻烦了，很别扭。 

坚持之前的建议。

**Comment by 2881099** [comment]
> 希望有单独同步索引的功能，在生产环境中不太适合同步表字段，但索引会根据使用情况来调整。

生产环境同步索性问题也很大，当数据量过大的时候，管理索引很慢很慢。

建议别及依赖 CodeFirst，把它当作开发时的辅助工具即可。

**Comment by HaoZhiYing** [comment]
希望有这样一个单独 设置 列 的函数 与 tolist 单独剥离开，这样便于灵活和 封装

**Comment by windhuan** [comment]
FreeSql 能否改成非单例模式并且实现异步事务，目前使用仓储和UnitOfWork模式实现异步事务进行多表操作，代码不够简洁

**Comment by hjkl950217** [comment]
# 叶老板牛逼！
```
                 .GroupBy(t => new { t.mid, belongTime = t.gatherTime.ToString("yyyy") + "year" })
                 .ToList(t => new WaterMeterData()
                 {
                     mid = t.Key.mid,
                     BelongTime = t.Key.belongTime,
                     Flow = t.Max(t.Value.cycleNumber ?? t.Value.flow) - t.Min(t.Value.cycleNumber ?? t.Value.flow)
                 });
```
就特别好奇belongTime那里到底是怎么识别成功的，这功能就强到离谱！
用了一个多月freesql,感觉非常强，都不想用回EF了

# 建议方面：
发现一些缺点：
1.文档已经非常多了，而且方法上面也有比较多的。但在关键上面却没有(后面会举例，有空的话我也会来帮贡献文档)
2.支持到C#语法级别（如?? + - 等)和‘ToString("yyyy")’一类的方法。但因为命名空间不在freesql下面，不看文档还真的不知道有这种操作。

## 针对1：
比如用到groupBy("xxx")，文档上没有说明后面怎么使用，只说支持了原生语法，方法上面也返回的是`ISelect<T>`。这个就很蒙蔽，不敢用呀。
建议：一个是完善文档，而个是这类组合的用法，可以找个地方说明一下设计思想。这样即便文档上没有写具体怎么用，结合设计思想更能猜一起。


## 针对2：
我承认‘ToString("yyyy")’和`?? + - `这类支持非常强！但依然会心慌，因为这种支持依赖“约定”，并且这种依赖非常多。
查看文档后知道这是`freesql`对`DateTime`的支持，那`DateTimeOffset`呢？`ToString`这个方法从代码上看并不属于`freesql`的命名空间，就不知道还有多少支持是**约定**的。

在这个上面我到是建议同时支持‘EF’的那种设计方式，如`EF.Functions.Like(xxx)`这样最大的好处是我学会一个之后其他的自然就会了。 如果这样的话，可以先提供方法级，再提供约定级的方式。


其它建议：
再次感谢作者提供如此强大的库，刷新我对ORM上限的认知。在2.0上面，我到是建议可以先不做“功能上的加法”，应该做“设计上的减法”，把之前步子迈的太快留下的坑填填，把设计上面再精简精简并形成内部的设计风格。这样非常便于后期维护，否则项目会越来越臃肿复杂的

**Comment by 2881099** [comment]
@hjkl950217 谢谢支持

**Comment by jianliulin** [comment]
希望能在Column特性中添加一个能控制写入数据库日期精度的功能，
比如：
Column（DateTimeFormat=“yyyy-MM-dd ”）
public  DateTime  aDate {get;set;}

插入或者更新aDate 时候会忽略时间部分，

yyyy-MM-dd   ： 2020-11-10 11:55:21.537 =>   2020-11-10 00:00:00.0000

yyyy-MM-dd  HH  ：2020-11-10 11:55:21.537 =>   2020-11-10 11:00:00.0000

**Comment by fawdlstty** [comment]
@jianliulin setter呗

**Comment by kamikyo** [comment]
大佬，我这里主要有两个建议：
1。希望所有的异步方法能加上CancellationToken这一参数
2。希望特定的查询方法能返回ValueTask<T>类型的结果集
我知道这两个改动涉及的面非常的大，但是总还是想有个念头

**Comment by luoyunchong** [comment]
这种API设计，加CancellationToken，不知道怎么加，肯定是会影响API变化的，我觉得应该去掉params，只是少一个方便传参的方式。 @kamikyo  @2881099 
```
        Task<List<T>> QueryAsync<T>(CommandType cmdType, string cmdText, params DbParameter[] cmdParms);
```

**Comment by alexinea** [comment]
> 这种API设计，加CancellationToken，不知道怎么加，肯定是会影响API变化的，我觉得应该去掉params，只是少一个方便传参的方式。 @kamikyo @2881099
> 
> ```
>         Task<List<T>> QueryAsync<T>(CommandType cmdType, string cmdText, params DbParameter[] cmdParms);
> ```

这种情况下，为加上 `CancellationToken cancellationToken = default`，可把 `params DbParameter[] cmdParms` 参数改为工厂方法：

```
DbParameter[] SqlEx.Params(params DbParameter[] cmdParms)
```

如此一来，便可在不改动 Api 的情况下增加一个方法：
```
Task<List<T>> QueryAsync<T>(CommandType cmdType, string cmdText, params DbParameter[] cmdParms);
Task<List<T>> QueryAsync<T>(CommandType cmdType, string cmdText, DbParameter[] cmdParms, CancellationToken cancellationToken = default);
```

用法：
```
CancellationToken cancellationToken = ...;
var val = await one.QueryAsync(CommandType.Text, "SELECT ...", SqlEx.Params(xxx, xxx), cancellationToken);

var original = await one.QueryAsync(CommandType.Text, "SELECT ...", xxx, xxx);
```

**Comment by HaoZhiYing** [comment]
希望加一个这样得语法 

![image](https://user-images.githubusercontent.com/14025507/98889590-302fb900-24d5-11eb-82e4-e6df0262e111.png)

**Comment by tky753** [comment]
能不能基于现有的CodeFirst做一个类似于EfCore的生成Migration的工具，并扩展成基于版本的数据库迁移模式。
流程大概是这样：
1. 通过CodeFirst生成迁移Sql写进一个sql文件，sql文件名带上日期时间，用于判断执行顺序；
2. 用户可以根据自身需求酌情增改 sql文件内容；
3. 编译生成迁移程序；
4. ...... 之后的步骤就和EfCore的基本一样了。

这样的话，可以让CodeFirst更加的可控，或者说更加灵活，视图、存储过程啥的都好搞了。
至于回滚，不急着实现。
然后缺点：生成了具体的sql了，就不好跨数据库了，但我相信大部分的项目一开始敲定了使用某个数据库应该就不会轻易变了吧。
现在我迁移是依赖EfCore 和 FluentMigrator，如果能实现这个的话，就能替换掉其他的迁移方案了。

**Comment by jianliulin** [comment]
能不能添加一个Any(DynamicFilterInfo filterInfo) 函数，方便前端传回动态查询条件。

**Comment by sukney** [comment]
增加可空类型函数返回，像first 增加firstorDefault，model 映射支持字符串可空类型。

**Comment by landonzeng** [comment]
希望增加分表分库自动查询对应分表分库的数据

**Comment by hjkl950217** [comment]
> 增加可空类型函数返回，像first 增加firstorDefault，model 映射支持字符串可空类型。

我主观上更习惯FirstOrDefault这样的。。但是现在freesql已经用的人非常多了。。如果增加FirstOrDefault就意味着First的返回就不可能是null的，这意味着有破坏性更新，这不是大家想看到的。。

**Comment by landonzeng** [comment]
希望导航属性能够支持非主键的关联功能

**Comment by cnkker** [comment]
> 1、希望导航属性能够支持非主键的关联功能 2、希望添加二级缓存的功能

你需要先了解，为什么要用导航，到底解决了什么问题：[https://www.cnblogs.com/kellynic/p/13575053.html](url)

**Comment by ThreeLambs** [comment]
1. 像Dapper一样可以返回dynamic类型
2. 希望导航属性能够支持非主键的关联功能

**Comment by gudufy** [comment]
支持数据库的json类型

**Comment by 2881099** [comment]
> 支持数据库的json类型

什么数据库，json 类型一直支持的啊，这个 issues 是两年前的。

**Comment by gudufy** [comment]
> > 支持数据库的json类型
> 
> 什么数据库，json 类型一直支持的啊，这个 issues 是两年前的。

我用JsonMap生成的是varchar，现在最新版本的数据库基本都有json类型了

**Comment by sgf** [comment]
二级缓存 能不能有。
