### ISSUE TITLE
[求教]工作上从Repository转向DbContext的相关问题

### ISSUE THREAD

**Issue by Sinmo** [dotnetcore/FreeSql#470]
目前换到freesql的DbContext后遇到的以下问题,望解惑
1. 我有很多的 多对多的中间表, 例如: 
角色表      菜单表    角色菜单表
id Rname   id Mname    id  Rid Mid 
目前定义的中间表实体是
        [Column(IsIdentity = true, IsPrimary = true)]
        public int id { get; set; }

        public int Rid { get; set; }
        public virtual RoleEntity RoleEntity { get; set; }

        public int Mid { get; set; }
        public virtual MenuEntity MenuEntity { get; set; }

然后是角色的service

 // 新增角色 
 handle.RoleEntityDb.Add(entity);
 if (entity.Rid > 0)
{
       // 新增角色菜单中间表
       await _roleService.AddRoleMenus(role.Menus, role.Rid);
       // 向日志表新增一条日志
       await handle._logService.AddAsync(new Log() { Content = $"新增角色成功,角色Id:{ role.Rid}" });
}                 

现在有以下问题
1. 如果角色新增失败   我不执行 await handle.SaveChangesAsync(); 但失败日志怎么添加呢?
我现在是 在异常里 执行了 handle.RoleEntityDb.Remove(entity);  手动删除新增的数据,这种方法是不是正确的吗?

2. 我的删除都是软删除,
现在数据库里已经有一下数据   
roleMenus 
id Rid Mid  isTrue
1  1   1        true
2  1   2        true
3  2   1        true

页面传了个新角色菜单数组来

roleDto
Rid  1   Mens[]{ 1 }

代表目前,角色1 只有 菜单1 的权限了,  我要怎么将数据库的数据取出,然后把 id 2的  isTrue 改为 false呢?

3. 删除角色实体时(软删除),我是先查询再修改状态

 var entity = await handle
                               .RoleEntityDb
                               .Where(e => e.RId.Equals(query.Id) && e.isTure == true)
                               .FirstAsync();

  if (entity != null)
  {
      entity.IsActive = false;
      await handle.RoleEntityDb.UpdateAsync(entity);
  }

这种方法是正确的吗?

**Comment by 2881099** [comment]
1. 添加失败，让事务回滚，不用执行 Remove 操作。

不一定是 SaveChanges 会失败，Add/Update/Remove 都有可能失败。DbContext 机制可以看下文档介绍，简单点说他是一个智能合并执行的功能类。

2. 中间表一般不用存储其他信息，建议把这三个实体做成两个一对多。中间表的字段更新，可以使用用 IUpdate .Set(a=>a.IsTrue,true).ExecuteAffrows() 执行更新。

3. 先查询在更新可以。

软删除可以参考文档：全局过滤器
