### ISSUE TITLE
泛型TEntity复数形式

### ISSUE THREAD

**Issue by dingshuanglei** [dotnetcore/FreeSql#472]
泛型TEntity复数形式entities并非entitys
async public virtual Task<List<TEntity>> InsertAsync(IEnumerable<TEntity> entitys)

**Comment by 2881099** [comment]
Repository 还是 IFreeSql

**Comment by dingshuanglei** [comment]
> 存储库还是IFreeSql

DbSet、 BaseRepository、IBaseRepository还有Examples例子里面使用的复数很多都是entitys并非entities

**Comment by 2881099** [comment]
哦，你是指命名问题吗？

个人认为中式英文挺好，大家都懂。

**Comment by dingshuanglei** [comment]
> 哦，你是指命名问题吗？
> 
> 个人认为中式英文挺好，大家都懂。
我是翻看源码的时候看见Requierd写错了专门写了更新，所以看见TEntity复数是中式英语就提了issues，草率了
