### ISSUE TITLE
GlobalFilter生成的Sql语句问题

### ISSUE THREAD

**Issue by BigDream324** [dotnetcore/FreeSql#475]
>  我在FreeSql初始化后添加了GlobalFilter:

         freeSql.GlobalFilter
                    .Apply<Authority>($"{nameof(Authority)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<Broker>($"{nameof(Broker)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<FundAccount>($"{nameof(FundAccount)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<FundInfo>($"{nameof(FundInfo)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<OrderInfo>($"{nameof(OrderInfo)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<PositionInfo>($"{nameof(PositionInfo)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<Product>($"{nameof(Product)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<Role>($"{nameof(Role)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<RoleAuthority>($"{nameof(RoleAuthority)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<TradeInfo>($"{nameof(TradeInfo)}SoftDelete", o => o.IsDeleted != 1)
                    .Apply<User>($"{nameof(User)}SoftDelete", o => o.IsDeleted != 1);

> 之后Select查询User表的数据:

        var user = await DBManager.Instance.Select<DBModels.User>().Where(o => o.UserId == req.UserID).FirstAsync();

> 在freeSql.Aop.CurdAfter事件中,捕获到了刚才执行的Sql:

        SELECT a.`id`, a.`role_id`, a.`certificate_no`, a.`create_time`, a.`create_user`, a.`disk_id`, a.`disk_id_flag`, a.`email`, a.`id_card`, a.`ip`, a.`ip_flag`, a.`is_deleted`, a.`mac`, a.`mac_flag`, a.`modify_time`, a.`phone`, a.`status`, a.`user_id`, a.`user_name`, a.`user_password` 
        FROM `user` a 
        WHERE (a.`user_id` = 'admin') AND ((a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1) AND (a.`is_deleted` <> 1))
        limit 0,1

可以看出,在生成的Sql语句中出现了多条a.`is_deleted` <> 1 语句判断 ,显然这是不合理的.

**Comment by 2881099** [comment]
只有需要配置一个。

Apply 泛型参数可以设置为任何类型，当使用 Select/Update/Delete 方法时会进行过滤器匹配尝试（try catch）：

匹配成功的，将附加 where 条件；

匹配失败的，标记下次不再匹配，避免性能损耗；

**Comment by BigDream324** [comment]
如果我想在不同的表中加入不同的全局过滤条件可以实现吗? 
比如我只筛选Broker的IsDeleted!=1 其他的表IsDeleted字段不筛选,有办法做到吗?

**Comment by 2881099** [comment]
如何禁用？

fsql.Select\<TestAddEnum>().DisableGlobalFilter("test1").ToList(); //禁用 test1
fsql.Select\<TestAddEnum>().DisableGlobalFilter().ToList(); //禁用所有
fsql.Update/Delete 方法效果同上

然后再自己写 IsDeleted 条件
