### ISSUE TITLE
AsTreeCte() 会产生一个as_tree_cte表

### ISSUE THREAD

**Issue by tommyheng** [dotnetcore/FreeSql#476]
1、mysql数据库
2、
>             var freeSqlBuilder = new FreeSqlBuilder()
>                     .UseConnectionString(dbType, connstr)
>                     .UseAutoSyncStructure(dbcontext.AutoMigrationEnabled)
>                     .UseLazyLoading(false)
>                     .UseNoneCommandParameter(true);
> 
>             var fsql = freeSqlBuilder.Build();
>             services.AddFreeRepository();
>             services.AddScoped<UnitOfWorkManager>();
>             services.AddSingleton(fsql);

3、   实体

>     [Description("地区表")]
>     [Table(Name = "Area")]
>     public class AreaEntity : EntityBase<long>
>     {
>         public string Name { get; set; }
>         public long ParentId { get; set; }
> 
>         [Navigate(nameof(ParentId))]
>         public AreaEntity Parent { get; set; }
>         [Navigate(nameof(ParentId))]
>         public List<AreaEntity> Childs { get; set; }
>     }

4、测试(库里没创建表，也没有任何数据，只是开了UseAutoSyncStructure)

  var repo = _fsql.GetRepository<AreaEntity>();
  var list = await repo.Select.Where(m => m.Name == "辽宁省").AsTreeCte().ToListAsync();

5、数据库会出现 area和as_tree_cte 2个数据表

**Comment by 2881099** [comment]
经过测试确实存在这个问题，当开启了自动同步结构 .UseAutoSyncStructure(true)，会产生这个 as_tree_cte 表。

谢谢反馈，已修复。
