### ISSUE TITLE
where like条件建议 

### ISSUE THREAD

**Issue by scotly** [dotnetcore/FreeSql#477]
.Where(x=>!string.IsNullOrWhiteSpace(name)?x.DepName.Contains(name):false)  这样语句，打印的sql是 case when条件判断 ,但我的真实意图是三元表达式走了第二结果，则不包含该where条件。
请问我应该怎么做?

**Comment by scotly** [comment]
AND (case when not((N'' is null or N'' = '' or ltrim(N'') = '')) then (a.[DepName]) LIKE ('%'+cast(N'' as nvarchar(max))+'%') else 0 end)  这是测试生成的sql语句，这样的语句效率非常低
我觉得where就不要有这种语法，可以新增casewhen扩展,如casewhen(conditonExpress,trueVal,falseVal,defaultVal)

**Comment by 2881099** [comment]
.WhereIf(!string.IsNullOrWhiteSpace(name), x=>x.DepName.Contains(name))
.WhereIf(string.IsNullOrWhiteSpace(name), x => false)

这样？

**Comment by scotly** [comment]
原来如此，十分感谢
