### ISSUE TITLE
DynamicFilterOperator.GreaterThan 目前尚未支持字符串的比较，是否可以考虑支持?

### ISSUE THREAD

**Issue by jianliulin** [dotnetcore/FreeSql#479]
在使用DynamicFilterInfo 的时候，DynamicFilterOperator.GreaterThan 目前尚未支持字符串的比较，是否可以考虑支持? 谢谢！！

**Comment by 2881099** [comment]
已解决，使用起来和之前一样，没有增加额外使用的定义。

**Comment by jianliulin** [comment]
谢谢！！
