### ISSUE TITLE
[建议]可以优化下where条件的参数传递方式

### ISSUE THREAD

**Issue by bendingmoon** [dotnetcore/FreeSql#48]
例：
Ado.Query( "select * from xxx where Id = @Id and name=@name", new System.Data.SqlClient.SqlParameter("Id", 1), new System.Data.SqlClient.SqlParameter( "name", "text" ) );
如果能使用：
Ado.Query( "select * from xxx where Id = @0 and name=@1",  1,  "text" );
的方式调用的话，就更好了。

**Comment by 2881099** [comment]
谢谢反馈，建议非常的棒，目前尝试适配的过程中出现了实现问题，测试与原有逻辑。

需要推迟一点才能完成，再次感谢！
