### ISSUE TITLE
请教:如何使用Sqlite Cipher数据库? 

### ISSUE THREAD

**Issue by peng0829** [dotnetcore/FreeSql#480]
最近在尝试做一个软件,本地需要加密的sqlite数据库
但是官方的sqlite数据加密似乎并不支持Net core3.1
尝试了很久,并不知道该如何使用Sqlite Cipher.
本人新手,可能描述的不太清楚.
希望指点
万分感谢

**Comment by 2881099** [comment]
据悉，因涉及商业问题，默认的 sqlit 没有提供加密功能。

但是可以自己编译使用，使用者自己承担商业风险。

**Comment by peng0829** [comment]
> 据悉，因涉及商业问题，默认的 sqlit 没有提供加密功能。
> 
> 但是可以自己编译使用，使用者自己承担商业风险。

感谢

**Comment by peng0829** [comment]
再次感谢,我重新编译了一下文件
将官方的System.Data.SQLite改成了Microsoft.Data.Sqlite了,
已经解决了需求

**Comment by 2881099** [comment]
谢谢反馈，给后来人做参考
