### ISSUE TITLE
Insert Dictionary BUG

### ISSUE THREAD

**Issue by mansai** [dotnetcore/FreeSql#481]
table sql
CREATE TABLE [dbo].[TSysEnum] (
  [FEnumId] int  NOT NULL,
  [FEnumType] int  NULL,
  [FEnumCode] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [FEnumDesc] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [FCreateDateTime] datetime  NOT NULL
)

Dictionary<string, object> keys = new Dictionary<string, object>() { { "FEnumId", 4 }, { "FEnumType", 2 }, { "FEnumCode", "test" }, { "FEnumDesc", "测试" }, { "FCreateDateTime", DateTime.Now } };
 var model = _fsql.Insert(keys).AsTable(t => "TSysEnum").ExecuteInserted();

**Comment by 2881099** [comment]
不支持字典。

动态插入：fsql.Insert\<object\>().AppendData(实体对象).ExecuteAffrows()
