### ISSUE TITLE
动态类插入报错

### ISSUE THREAD

**Issue by mansai** [dotnetcore/FreeSql#482]
table sql
CREATE TABLE [dbo].[TSysEnum] (
  [FEnumId] int  NOT NULL,
  [FEnumType] int  NULL,
  [FEnumCode] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [FEnumDesc] nvarchar(255) COLLATE Chinese_PRC_CI_AS  NULL,
  [FCreateDateTime] datetime  NOT NULL
)

            AssemblyName aName = new AssemblyName(Guid.NewGuid().ToString());
            AssemblyBuilder ab = AssemblyBuilder.DefineDynamicAssembly(aName, AssemblyBuilderAccess.Run);
            ModuleBuilder mb = ab.DefineDynamicModule(aName.Name);
            TypeBuilder tb2 = mb.DefineType("TSysEnum", TypeAttributes.Public);
            tb2.DefineField("FEnumId", typeof(int), FieldAttributes.Public);
            tb2.DefineField("FEnumType", typeof(int), FieldAttributes.Public);
            tb2.DefineField("FEnumCode", typeof(string), FieldAttributes.Public);
            tb2.DefineField("FEnumDesc", typeof(string), FieldAttributes.Public);
            tb2.DefineField("FCreateDateTime", typeof(DateTime), FieldAttributes.Public);
            Type user = tb2.CreateType();
            object o2 = Activator.CreateInstance(user);
            FieldInfo[] fieldInfos = user.GetFields();
            user.GetField("FEnumId").SetValue(o2, 4);
            user.GetField("FEnumType").SetValue(o2, 2);
            user.GetField("FEnumCode").SetValue(o2, "test");
            user.GetField("FEnumDesc").SetValue(o2, "测试");
            user.GetField("FCreateDateTime").SetValue(o2, DateTime.Now);
            var model = _fsql.Insert(user).ExecuteInserted();

**Comment by 2881099** [comment]
用属性，不要用字段，

public int id { get; set; } //正确

public int id; //错误

**Comment by 2881099** [comment]
动态插入：fsql.Insert\<object\>().AsType(实体类型).AppendData(实体对象).ExecuteAffrows()

**Comment by mansai** [comment]
OK
