### ISSUE TITLE
字段和表注释Bug！

### ISSUE THREAD

**Issue by xuanyuan5005** [dotnetcore/FreeSql#484]
ColumnAttribute没有Comment属性，TableAttribute也没有Comment属性。但是启用UseAutoSyncStructure时候，表注释和字段注释，被清除了。

**Comment by 2881099** [comment]
功能用之前，必先了解下机制。

如果是已存在的表，肯定不适合再做 CodeFirst，除非能容忍发生的情况。

自动迁移注释文档，要求生成 xml 注释，否则运行时无法读取注释信息。

**Comment by 2881099** [comment]
## 备注 -> 迁移到数据库

FreeSql CodeFirst 支持将 c# 代码内的注释，迁移至数据库的备注。先决条件：

1、实体类所在程序集，需要开启 xml 文档功能；

2、xml 文件必须与程序集同目录，且文件名：xxx.dll -> xxx.xml；

> v1.5.0+ 版本增加了对 Description 特性的解析，优先级低于 c# 代码注释；

**Comment by xuanyuan5005** [comment]
功能用之前，必先了解下机制。

如果是已存在的表，肯定不适合再做 CodeFirst，除非能容忍发生的情况。

自动迁移注释文档，要求生成 xml 注释，否则运行时无法读取注释信息。
-------------------------------------------------------------------------------------------------
第一，开发是个迭代过程，已经存在表，也不是一成不变的。已经存在的可能是个原型，或者第一次版本。
第二， xml 注释并不是一个很好方案，他是对象的注释。对象注释和数据库字段注释是两个事情。

**Comment by 2881099** [comment]
代码注释，或者 [Description(...)] 都可以

**Comment by xuanyuan5005** [comment]
个人建议统一下！
代码生成SQL语句时候，很多次出现了，Comment这次词语和概念。前后呼应以及一致性会高出许多。

**Comment by luoyunchong** [comment]
Description 这种是官方就有的特性标签，

https://docs.microsoft.com/zh-cn/dotnet/api/system.componentmodel.descriptionattribute?view=netcore-3.1

@xuanyuan5005

**Comment by xuanyuan5005** [comment]
这个仅仅是一个 Column 的Comment。和官网的这个没有必然联系。
同样的问题也存在，TableAttribute，Table的Engine。

**Comment by 2881099** [comment]
暂时提供了 [Description("xxx")] 和 c#代码注释，两种使用方式够用的。

特别是 c# 代码注释，相信没有谁的实体类不写注释的。

ColumnAttribute 现在的属性名太多，我们也是想尽量减少理解成本，推荐使用 c#代码注释 的方式进行开发。


> 这个仅仅是一个 Column 的Comment。和官网的这个没有必然联系。
> 同样的问题也存在，TableAttribute，Table的Engine。

**Comment by 2881099** [comment]
感谢反馈，问题关闭。
