### ISSUE TITLE
1.9.0 MySql 生成的实体对象中，smallint 没有对应的属性标记 DbType=smallint

### ISSUE THREAD

**Issue by neoayi** [dotnetcore/FreeSql#486]
如题
1.9.0 MySql 生成的实体对象中，smallint 没有对应的属性标记 DbType=smallint

![image](https://user-images.githubusercontent.com/137907/95672988-2281cd80-0bcf-11eb-9b23-5eee28b3f691.png)

**Comment by 2881099** [comment]
c# short 对应的类型正是 smallint，缺省生成 DbType

**Comment by neoayi** [comment]
了解。
