### ISSUE TITLE
sqlite 查询内存溢出

### ISSUE THREAD

**Issue by yangbocheng** [dotnetcore/FreeSql#488]
wpf应用
freesql 1.9版本套件，，之前在1.4也能出现
一个批量导出业务的数据库操作全部在新开的一个单线程中，按如下调用, 通过异常信息定位到了图下197行
//该代码前面还有很多其它同样的调用，用于查询导出其他表
//此处应能查询到6000条数据，每条数据30个字段左右，难以复现该错误，想求教大佬可能是什么原因
![image](https://user-images.githubusercontent.com/32633109/95816806-85e83880-0d52-11eb-926b-d6ef7fc332c1.png)

之后出现内存溢出
![捕获](https://user-images.githubusercontent.com/32633109/95816844-a31d0700-0d52-11eb-96e0-504a44e40c57.JPG)

数据结构
```csharp
   [Table(Name = "t_detect_zy")]
    //[Table(Name = "t_point")]
    //[Index("importpoint_1", nameof(ImportPoint.excelId))]
    //内窥原始数据
    class ImportDetectzy:IlineStartEndinfo
    {
        [Column(IsPrimary = true, IsIdentity = true)]
        public int id { get; set; }
        public int excelId { get; set; }
        public DateTime insertTime { get; set; }


        public string workPlaceName { get; set; }

        public string expOri_No0 { get; set; }
        public string expOri_No1 { get; set; }

        public bool hasDefect { get; set; } 
        public string DefectType { get; set; }
        public string DefectName { get; set; }
        public string DefectLevel { get; set; }
        public string CheckMethod { get; set; }
        public string CheckDirection { get; set; } 
        public string CheckDate { get; set; }
        public string CheckMan { get; set; } 
        public string RecordMan { get; set; } 

        public string Struct_Defect_density { get; set; } 
        public string Struct_Repaire_index { get; set; } 
        public string Struct_Repaire_level { get; set; }

        public string Func_Defect_density { get; set; }
        public string Func_Maintain_index { get; set; } 
        public string Func_Maintain_level { get; set; }

        [Column(IsIgnore =true)]
        public string tempLno { get; set; }
        [Column(IsIgnore = true)]
        public string S_Point { get; set; }

        [Column(IsIgnore = true)]
        public string E_Point { get; set; }

        [Column(IsIgnore = true)]
        public double S_X { get; set; }
        [Column(IsIgnore = true)]
        public double S_Y { get; set; }
        [Column(IsIgnore = true)]
        public double E_X { get; set; }
        [Column(IsIgnore = true)]
        public double E_Y { get; set; }

    }

```

**Comment by yangbocheng** [comment]
附加 诊断模式巅峰应用实际占用内存1g多点，电脑i7，16G内存

**Comment by 2881099** [comment]
加 Limit(6000) 限制一下测试。

如果没报错，加大到60000，如此测试出内存溢出的临界值。

**Comment by yangbocheng** [comment]
最诡异的是，单独运行该区段是没问题的，可以正常查询和后续操作。该问题稳定复现在 运行该行197前的6，7个导出其他表，并做一些查询比对的操作后。  才出现这个bug

**Comment by yangbocheng** [comment]
![Uploading image.png…]()

**Comment by yangbocheng** [comment]
![image](https://user-images.githubusercontent.com/32633109/95817937-4b33cf80-0d55-11eb-850c-dade62dbf264.png)
一共1000条数据， 之前说错了

**Comment by 2881099** [comment]
你看下面的SQL，有 LIMIT 0, 1000

管理工具一般都是 top 1000 条，防止 UI 卡死。

实际不止 1000 条数据。

**Comment by yangbocheng** [comment]
在该行语句之前 也有多次 select调用，并且基本上都是查询多很多条目，有的2到3万条，也没有问题出现

**Comment by yangbocheng** [comment]
谢谢提醒  一共11026条

**Comment by yangbocheng** [comment]
我再调试下   找到一个准确快速复现的办法，我这儿现在复现一次要快半个小时才能运行到这儿

**Comment by yangbocheng** [comment]
大佬我搞不定了，这个问题只有运行全部流程才能复现，一次测试要半小时以上
实际导出部分是按照如下流程，进行每个表的查询，然后对该表的n个数据，调用arcgis的自有api插入到mdb中。基本上每秒钟向arcgis插入50条数据。比如1过程中调用fsql从sqlite中查询27144条，然后在1阶段进行arcgis处理，那么大概完成1阶段大概额外需要27144/50/60=9分钟，
查询爆出内存溢出问题总是在第8部，实际此处应查询出11796条。
经过测试，取消每个步骤间的原有arcgis操作及任何操作，即12345678过程直接顺序流畅查询正常运行；或者每个阶段仅处理全查出来的500条数据，此时能大大缩短阶段时间，此时全部阶段仍然能流畅往下运行
1     ##共查询 27144
2point     ##共查询 13783
3comb     ##共查询 6314
4outfall     ##共查询 9
5manhole     ##共查询 7540
6pipe     ##共查询 25795
7conduit     ##共查询 1349
8detectzy     ##共查询 11796
9其他

**Comment by 2881099** [comment]
这几个方向试试：

1、FreeSqlBuilder UseConnectionString 换成 UseConnectionFactory

```c#
var sqliteConn = new System.Data.SQLite.SQLiteConnection(@"Data Source=document.db");

//.UseConnectionString(FreeSql.DataType.Sqlite, @"Data Source=document.db")
.UseConnectionFactory(FreeSql.DataType.Sqlite, () => sqliteConn)
```

> 使用 sqliteConn 作为单一连接对象，不支持线程并发操作

2、同上使用 UseConnectionFactory data source=:memory:

> 这种是使用内存模式，同样注意线程并发问题

3、下载 FreeSql 源码，将 System.Data.Sqlite.Core 引用改成 Microsoft.Data.Sqlite，重新编译测试

**Comment by yangbocheng** [comment]
//sqlite初始化语句如下
```csharp
var connstr = @"Data Source=db/lgdb.db";
fsql = new FreeSqlBuilder()
                .UseConnectionString(DataType.Sqlite, connstr)
                .UseAutoSyncStructure(true)
                .Build();
```

**Comment by yangbocheng** [comment]
好的 谢谢大佬  我试下方法

**Comment by yangbocheng** [comment]
第一种方法没有成功。 但是原先是第8步查询失败，现在变成了第9步中查询失败。
仔细观察了一些诊断现象
有个现象申明：实际所有的阶段过程中，内存一直在增长，这是因为所有过程中arcgis相关的buffer未释放，设计为1~9阶段完成时统一释放arcgis相关 //每插入一行数据，需要创建一条新buffer, 导致在去全部插入前内存一致增长
现在猜测是arcgis的未释放的相关因素可能导致了 sqlite查询也出现了问题，可能是某种资源冲突或者句柄用完等

因此推测bug问题和freesql无关，而是arcgisAPI导致了某种冲突

**Comment by 2881099** [comment]
可以释放　fsql 再重新创建试试

**Comment by yangbocheng** [comment]
大佬我回复迟了。 因为急于交付软件，先通过先完全查询所有需要的全部种类表并处理，然后单独做arcgis插入临时解决

**Comment by yangbocheng** [comment]
fsql释放后，再创建的方式已尝试过, 仍然在原先一摸一样的位置出现了内存溢出问题
![image](https://user-images.githubusercontent.com/32633109/96087159-03987980-0ef6-11eb-8a2b-63be1792dede.png)

**Comment by yangbocheng** [comment]
fsql释放后，再创建的方式已尝试过, 仍然在原先一摸一样的位置出现了内存溢出问题
![image](https://user-images.githubusercontent.com/32633109/96087351-4a866f00-0ef6-11eb-9fdd-095fe06ae2d5.png)

**Comment by yangbocheng** [comment]
我注意到了一个现象。在原先的代码或者每次fsql释放后再创建的程序中，因为arcgis的插入释放问题，从第1阶段到第7阶段，内存占用从300M稳定增长到1.1G，但是在第7阶段的arcgis插入过程中，内存突然从1.1G变成了300多M，并且从此时开始，gc比之前多很多，而且arcgis的插入性能急剧下降，原先每秒大概50条插入，此刻之后大概每秒5条插入。然后进入第8阶段的瞬间，调用select，然后就直接出现内存溢出
![image](https://user-images.githubusercontent.com/32633109/96087942-4018a500-0ef7-11eb-8600-de3f9831b581.png)

**Comment by 2881099** [comment]
connstr = @"data source=db/lgdb.db;max pool size=1";

加一个这个参数，看看有没有好转

**Comment by yangbocheng** [comment]
好的，正在尝试，需要半小时等结果。重新表述下流程：在1~9阶段的业务中，都只用到了fsql的select功能，而向arcgis中插入处理过的数据调用的是arcgis的相关dll，总业务大概是[阶段1=fsql.select+处理+arcgis的dll插入] [阶段2=fsql.select+处理+arcgis的dll插入] ...，每次出错大概率在第8阶段sql.select数据中内存溢出

**Comment by yangbocheng** [comment]
加入参数后还是在第8阶段查询出现内存溢出。
通过调试发现gc越来越频繁，可能问题就在arcgis的资源释放上。这个问题可能可sqlite本身没有直接bug关系，所以准备研究下释放arcgis资源，这个方向可以吗？个人认为如果不是sqlite本身的原因可以关闭该问题了，谢谢大佬一直耐心指导排查方案

**Comment by yangbocheng** [comment]
@2881099  今天终于安定下来，复查这个问题，大佬知道是什么原因吗
如下 为了干净演示，是在主线程中窗体加载的瞬间就进行sql查询，反复查询pipe类型。
第一个能查询出55万条数据，此时内存增长到700M左右，然后执行第二个查询内存增长到1.1G时，稳定出现引发类型为“System.OutOfMemoryException”的异常
![image](https://user-images.githubusercontent.com/32633109/97289140-c337e480-1881-11eb-88bc-e6a85ecdf5ef.png)

**Comment by yangbocheng** [comment]
用的是sqlite3 freesql.provider.sqlite套件
测试，即使如下，在第2个查询处也是是内存溢出
![image](https://user-images.githubusercontent.com/32633109/97290127-1bbbb180-1883-11eb-96a1-10f4014933c2.png)

**Comment by 2881099** [comment]
pipe 数据很大吗？ ToChunk 这样用跟 ToList 效果一样。

ToChunk 是一边读，一边把数据写进文件，或者写到其他网络。防止数据全部加载到本机内存，导致溢出

**Comment by yangbocheng** [comment]
那我之前对ToChunlk的理解有误
pipe数据很大，30多个字段 目前表中50万条，后期可能有100万条
现在1是不知道为什么会出现查询内存溢出， 2是不知道这个全表查询以后该如何优雅安全的执行，大佬有什么建议吗，感觉单机应用有很多时候都被迫全表查询

**Comment by yangbocheng** [comment]
本机内存现在已经换成32G的配置，程序在上面的测试中第一条查询语句内存从100M左右上升到700M左右，第2条重复查询进行时从700增长到1.1G的瞬间，出现内存溢出的。。。。。。。。在单独写这个demo之前前，我尝试了在原工程里select<A>,select<B>...xx..这样顺序执行到内存大概也是占用1G的时候，也出现内存溢出

**Comment by 2881099** [comment]
用 64 位编译吗？看上去像32位内存。

**Comment by yangbocheng** [comment]
还好大佬提示32位的问题，我最终从以下2个方面一起好像解决了这个问题
1.
是的  由于工程引用了arcgis(32位)，无法按x64编译，之前项目勾选的是x86编译
于是重新按编译方法测试
anycpu 3.5G 时异常
X64 无限制 一直到最终8G都顺利执行完毕
X86 1.6G 时异常
原来是这个原因 ~~现在我更改项目为anycpu模式，可以稍微增大点内存占用

2.关于如何优雅的优化占用内存
在同一代码区的上下文是不能GC的，即使调用GC.Collect();GC.WaitForPendingFinalizers();，无效；但是如果把需要大量查询的代码段封装到函数中。函数调用后再gc，则可以回收.
![image](https://user-images.githubusercontent.com/32633109/97386651-3e93a780-190f-11eb-9d78-0f582744c672.png)

**Comment by 2881099** [comment]
问题已解决？

**Comment by yangbocheng** [comment]
已按上面回答的2个措施，解决了实际问题。1个是增大内存可占用性  2是及时有效回收从而控制内存总占用
