### ISSUE TITLE
请问下载的FreeSqlTool.exe本地运行不起来是什么原因？

### ISSUE THREAD

**Issue by linyaoTom** [dotnetcore/FreeSql#489]
请问下载的FreeSqlTool.exe本地运行不起来是什么原因？

**Comment by 2881099** [comment]
有3个生成器，FreeSqlTool.exe 运行不了大概率是运行环境的问题。

建议使用 FreeSql.Generator 生成，运行环境 .net core 3.1

## 安装 dotnet-tool 生成实体类（推荐使用）

dotnet tool install -g FreeSql.Generator

新建目录，在地址栏输入 cmd 快速打开命令窗口，输入命令：

FreeSql.Generator --help

命令行工具生成实体类极大好处，后续再次生成覆盖操作等于一键完成，并且支持 Mac/Linux 平台。

**Comment by linyaoTom** [comment]
欧克，三克油
