### ISSUE TITLE
Where语句中强制类型转换时sql语句生成异常

### ISSUE THREAD

**Issue by BigDream324** [dotnetcore/FreeSql#490]
代码如下:

>             EnumAuthority authority = EnumAuthority.UserAdd;
>             var sql = DBManager.Instance.Select<DBModels.UserAuthority>().Where(o => o.UserId == 1 && o.AuthorityId == (int)authority).ToSql();
>             Console.WriteLine(sql);

生成的语句为:

> SELECT a.`id`, a.`authority_id`, a.`user_id`, a.`is_deleted` 
> FROM `user_authority` a 
> WHERE (a.`user_id` = 1 AND a.`authority_id` = 'UserAdd') 

我是希望能够生成EnumAuthority.UserAdd对应的int判断而不是对UserAdd进行判断

**Comment by BigDream324** [comment]
如果写成这样是可以正常生成sql的

>             var authority = (int)EnumAuthority.UserAdd;
>             var sql = DBManager.Instance.Select<DBModels.UserAuthority>().Where(o => o.UserId == 1 && o.AuthorityId == authority).ToSql();
>             Console.WriteLine(sql);

**Comment by 2881099** [comment]
是枚举吧？mysql？

mysql 的实现默认会把 c# Enum 类型映射成 数据库的 enum 类型。

所以就出现了这种情况

**Comment by 2881099** [comment]
AuthorityId 是什么类型，int 还是 enum

**Comment by BigDream324** [comment]
> AuthorityId 是什么类型，int 还是 enum

是Enum

**Comment by 2881099** [comment]
如果是 Enum，并且数据库也是 enum，查询不会有什么问题吧

**Comment by BigDream324** [comment]
> 是枚举吧？mysql？
> 
> mysql 的实现默认会把 c# Enum 类型映射成 数据库的 enum 类型。
> 
> 所以就出现了这种情况

是mysql  数据库中存放的是int
但是再where语句中已经对该值做强制转换了, 用户的角度是想对int来判断

**Comment by 2881099** [comment]
实体属性上给个特性

```c#
[Column(MapType = typeof(int))]
public EnumAuthority AuthorityId { get; set; }
```

**Comment by BigDream324** [comment]
实体属性是int类型的

> 		[JsonProperty, Column(Name = "authority_id", DbType = "int",MapType =typeof(int))]
> 		public int AuthorityId { get; set; }

刚试过加上MapType = typeof(int)也还是一样的

其实我并不太纠结这个问题如何解决,  在二楼我已经自己给了解决方案, 
只是觉得这样可能会让人误解, 因为在freesql和mysql看来这个字段都是int, 在查找的时候我也做了强制转换,但是生成的sql却考虑到了枚举的处理, 感觉这样不太合理, 如果有时间改进一下最好.

**Comment by 2881099** [comment]
```c#
var sql1 = fsql.Select<Tb_allType>().Where(a => a.Id == (int)Tb_alltypeTESTFIELDENUM1.E2).ToSql();
var sql2id = (int)Tb_alltypeTESTFIELDENUM1.E2;
var sql2 = fsql.Select<Tb_allType>().Where(a => a.Id == sql2id).ToSql();

public partial class Tb_alltype
{
    [Column(IsPrimary = true, IsIdentity = true)]
    public int Id { get; set; }
}

public enum Tb_alltypeTESTFIELDENUM1
{
    E1 = 1, E2, E3, E5
}
```

sql1 和 sql2 得到的值都是：
```sql
SELECT a.`Id` 
FROM `tb_alltype` a 
WHERE (a.`Id` = 2)
```

**Comment by 2881099** [comment]
没有你说的问题啊，所以我问属性定义的是什么类型

如果是 int 没问题

如果是 enum，那就会转成 string，但是可以通过 MapType = typeof(int) 设置

**Comment by BigDream324** [comment]
> var e2 = Tb_alltypeTESTFIELDENUM1.E2;
> var sql1 = fsql.Select<Tb_allType>().Where(a => a.Id == (int)e2).ToSql();
> 
> public partial class Tb_alltype
> {
>     [Column(IsPrimary = true, IsIdentity = true)]
>     public int Id { get; set; }
> }
> 
> public enum Tb_alltypeTESTFIELDENUM1
> {
>     E1 = 1, E2, E3, E5
> }

如果是这样呢
