### ISSUE TITLE
FreeSql 1.9.0 连接mysql，text类型查询时提示Data too long for column 

### ISSUE THREAD

**Issue by huayun1010** [dotnetcore/FreeSql#491]
同一个数据库使用Dapper查询的是可以查询，换了FreeSql 提示Data too long for column ，就是text类型转string的时候，这个字段我存的是json字符串，把mysql 的配置文件的默认编码都改成了utf8  连接字符串也改了，还是有这个情况

**Comment by 2881099** [comment]
问题关了？

**Comment by huayun1010** [comment]
是的  使用的问题  ，启用了实体更新到数据库  把我跟同事的数据库的字段类型都改了
