### ISSUE TITLE
自定义函数可以返回boolean类型吗

### ISSUE THREAD

**Issue by Tony518** [dotnetcore/FreeSql#492]
你好，请教一个问题；
我有下面的代码，这个where条件中针对GZ的判断，我代码中很多地方使用到，我想分装一个自定义方法,类如CheckGZ()，不知道怎么处理？
`_fsql.Select<Table>()
                .Where(a => a.GZ != "SU" && a.GZ != "Therein CVC" && a.GZ != "Therein CT16" && a.GZ != "" &&
                         a.SalesForce == region).ToList();`

我想要的效果
`_fsql.Select<Table>()
                .Where(a => a.CheckGZ() &&
                         a.SalesForce == region).ToList();`

**Comment by 2881099** [comment]
可以啊，去看自定义解析

**Comment by Tony518** [comment]
感谢，
方便给一个返回bool类型比较的例子吗？传入的that就是接收的值吗？

**Comment by Tony518** [comment]
如果返回是bool类型的，这个返回值好像是随意定义的，是么？

**Comment by 2881099** [comment]
参考：https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Extensions/FreeSqlGlobalExpressionCallExtensions.cs
