### ISSUE TITLE
Noticeable slowness for Mssql Connection

### ISSUE THREAD

**Issue by Runaho** [dotnetcore/FreeSql#493]
Hello, I am developing a simple exam system and for this I have prepared a repository to help my sql methods.

![helper-repo](https://user-images.githubusercontent.com/16222645/96123049-f7fb8180-0efa-11eb-8f6a-3dc8b8bec28f.png)

The first problem is that the pool limit was not enough.
Then i increased the limit up to 30.000 and tried to make an automatic connection with the constractor and deconstractor.

This is how I solved the Pool problem, but I am worried that it might cause problems when the program is live.

For the slowness problem As an example, let's look at the login page with a 6-digit passcode.

<img src="https://user-images.githubusercontent.com/16222645/96125431-7efd2980-0efc-11eb-9054-4e1a8e92664e.png" width="40%">

**This process takes 8 seconds.**
Simple where for simple table.
There is the table ;

<img src="https://user-images.githubusercontent.com/16222645/96128247-c9cb7100-0efd-11eb-8a2a-311453091909.png" width="40%">

This is a razor page code ;
![page-code](https://user-images.githubusercontent.com/16222645/96127386-0e0a4180-0efd-11eb-91d5-dedb2e3973dd.png)

and this is method in repo;
![simple-user-where](https://user-images.githubusercontent.com/16222645/96128887-91786280-0efe-11eb-98b4-888bade1a1f9.png)

Asynchronous or not, it does not matter at all, even the smallest operation takes seconds. On detailed pages, when I have to do 6-7 operations at once, I encounter waiting times such as 30-90 seconds.

I think I'm making a mistake in the connection part, but the wiki couldn't find codes such as open and close connections.
Soo how can we fix this.

I use ; 
- .Net Core 3.1 Razor Pages
- SQL Server 2018
- Connection string details : Connection Timeout=30;Connection Lifetime=0;Min Pool Size=0;Max Pool Size=30000;Pooling=true;

I have used many micro orms before and this is the first time I am facing this kind of problem. I would be glad if you were kind.
Thanks.

**Comment by 2881099** [comment]
- IFreeSql is created once, while the program is running
- IFreeSql does not need to be released(Dispose)

## Solution 1: Define objects as static

```c#
static Lazy<IFreeSql> sqlserverLazy = new Lazy<IFreeSql>(() => new FreeSql.FreeSqlBuilder()
    .UseConnectionString(FreeSql.DataType.SqlServer, "Data Source=.;Integrated Security=True;Initial Catalog=freesqlTest;Pooling=true;Max Pool Size=3")
    .UseAutoSyncStructure(true)
    .UseNoneCommandParameter(true)
    .UseMonitorCommand(cmd => Console.WriteLine("\r\nThread" + Thread.CurrentThread.ManagedThreadId + ": " + cmd.CommandText))
    .Build());
public static IFreeSql fsql => sqlserverLazy.Value;
```

## Solution 2: IOC Injection is a singletion

```c#
public void ConfigureServices(IServiceCollection services)
{
    IFreeSql fsql = new FreeSql.FreeSqlBuilder()
        .UseConnectionString(FreeSql.DataType.SqlServer, "Data Source=.;Integrated Security=True;Initial Catalog=freesqlTest;Pooling=true;Max Pool Size=3")
        .UseAutoSyncStructure(true)
        .UseNoneCommandParameter(true)
        .UseMonitorCommand(cmd => Console.WriteLine("\r\nThread" + Thread.CurrentThread.ManagedThreadId + ": " + cmd.CommandText))
        .Build();
    services.AddSingleton<IFreeSql>(fsql);
}
```

**Comment by Runaho** [comment]
Thanks for the answer, now i have a pooling error.
In fact, this was the first way I did it. ( Solution 1 )
![pool-error](https://user-images.githubusercontent.com/16222645/96132172-be2e7900-0f02-11eb-9914-0f9f608474e7.png)

**Comment by 2881099** [comment]
Do not define static IFreeSql in all classes.

```c#
public static class db
{
    static Lazy<IFreeSql> sqlserverLazy = new Lazy<IFreeSql>(() => new FreeSql.FreeSqlBuilder()
        .UseConnectionString(FreeSql.DataType.SqlServer, "...;Max Pool Size=100")
        .UseAutoSyncStructure(true)
        .UseNoneCommandParameter(true)
        .UseMonitorCommand(cmd => Console.WriteLine("\r\n" + cmd.CommandText))
        .Build());
    public static IFreeSql sqlserver => sqlserverLazy.Value;
}
```

In use:

```c#
public class BlogController : Controller
{
    public void Test1()
    {
        var blog = db.sqlserver.Select<Blog>().First();
    }

    public void Test2()
    {
        var blog = db.sqlserver.Select<Blog>().First();
    }
}

public class TopicController : Controller
{
    public void Test1()
    {
        var topic1 = db.sqlserver.Select<Topic>().First();
    }

    public void Test2()
    {
        var topic2 = db.sqlserver.Select<Topic>().First();
    }
}
```

**Comment by luoyunchong** [comment]
Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.


 max pool size 30000

Make it smaller

**Comment by 2881099** [comment]
The first operation was slow because the network was not good. 

Set ConnectionString "min pool size=1" to speed up.

**Comment by Runaho** [comment]
You are right I have two connections.
After making one, the pool problem was solved.
And after making static one connection & min pool size = 1, speed has also normalized.

Thanks a lot!

> The first operation was slow because the network was not good.
> 
> Set ConnectionString "min pool size=1" to speed up.

**Comment by akelmj** [comment]
> IOC Injection is a singleton

How to call the singleton in the controller? can you add an example like you add in the db class?

Thanks.
