### ISSUE TITLE
求教:全局过滤器问题

### ISSUE THREAD

**Issue by 835718973** [dotnetcore/FreeSql#495]
var fsql = new FreeSqlBuilder()
                .UseConnectionString((DataType)Enum.Parse(typeof(DataType), dbType), connectionString)
                .UseAutoSyncStructure(false) //自动同步实体结构到数据库
                .Build(); //请务必定义成 Singleton 单例模式
                
fsql.GlobalFilter.Apply\<ISiteEntity>(GlobalFilterName.SITE_ID, p => p.SITEID == RT.SiteId);

全局过滤器添加这里指定的ISiteEntity是指只要实体中包含SITEID属性就会添加过滤还是满足实体是ISiteEntity的实现者才添加过滤？
目前测试是第一种情况，如果要实现第二种，有什么方式呢

**Comment by 2881099** [comment]
ApplyIf 用这个

**Comment by 2881099** [comment]
刚才检查了，ApplyIf 目前满足不了第二种需求

**Comment by 835718973** [comment]
有其他方式可以扩展实现吗?无法保证命名都能区分开来,希望能够通过接口实现的方式来进行约束，特别是一些以前的项目

**Comment by 2881099** [comment]
新增 ApplyOnly 方法，当实体类继承于指定的 TEntity 才生效，用法与 Apply 一样。
