### ISSUE TITLE
请教！场景：更新列为子查询比如Count,Max后的结果，该如何写？

### ISSUE THREAD

**Issue by LightCHY** [dotnetcore/FreeSql#496]
orm.Update<UBIRelation>()
                .Where("1=1")
                .Set(a => new UBIRelation
                {
                    CountVersion = Convert.ToInt32(orm.Select<UBIRelation>().Where(w => w.RelationID == a.RelationID).Count()),
                    IsCurrentVersion = false
                }).UpdateColumns(c => new { c.IsCurrentVersion })
                .ExecuteAffrows();
这个会报错：System.ArgumentNullException:“值不能为 null。
Arg_ParamName_Name”

**Comment by 2881099** [comment]
更新不能用子查询，试试这样

```c#
        orm.Update<UBIRelation>()
            .Where("1=1")
    .Set(“CountVersion = “ + orm.Select<UBIRelation>().Where(w => w.RelationID == a.RelationID).ToSql(“count(1)”))
            .ExecuteAffrows()```

**Comment by LightCHY** [comment]
> 更新不能用子查询，试试这样
> 
> ```cs
>         orm.Update<UBIRelation>()
>             .Where("1=1")
>     .SetRaw(“CountVersion = “ + orm.Select<UBIRelation>().Where(w => w.RelationID == a.RelationID).ToSql(“count(1)”))
>             .ExecuteAffrows()```
> ```
这个子查询的条件的RelationID == Update的RelationID这个如何写？

**Comment by 2881099** [comment]
```c#
orm.Update<UBIRelation>()
  .Where("1=1")
  .SetRaw(“CountVersion = “ + orm.Select<UBIRelation>().Where("a.RelationID = UBIRelation.RelationID").ToSql(“count(1)”))
  .ExecuteAffrows();
```
