### ISSUE TITLE
连接postgresql

### ISSUE THREAD

**Issue by zengpengkindle** [dotnetcore/FreeSql#497]
![image](https://user-images.githubusercontent.com/16894507/96698711-0694dd80-13c0-11eb-9a41-b08a2dc5a0af.png)
![image](https://user-images.githubusercontent.com/16894507/96698979-4fe52d00-13c0-11eb-882d-c4595c5cdb94.png)

**Comment by 2881099** [comment]
数据问题，检查一下

**Comment by zengpengkindle** [comment]
这个是 npgsql包的问题 直接用npgsql 也报这个错  你这个也是依赖npgsql  用jdbc 不会报错   大佬能解决下这个问题么  感觉被java 吊打一样

**Comment by 2881099** [comment]
检查数据，应该是哪一行的数据格式有问题。

**Comment by zengpengkindle** [comment]
确实是是数据转换不过来的问题 应该是npgsql 类型映射有问题 这个issue应该和npgsql提的 因为我用jdbc是没有问题的 谢谢大佬
