### ISSUE TITLE
什么时候支持时序DB。现在iot盛行

### ISSUE THREAD

**Issue by yaobo-lab** [dotnetcore/FreeSql#501]
来先支持下国产iot 时序db ：https://www.taosdata.com/cn/

**Comment by hd2y** [comment]
FreeSql 是一个关系型数据库的 ORM，对于非关系型数据库以及时序数据库暂时不会提供支持。

**Comment by 2881099** [comment]
TimescaleDB 1.6.0 发布，基于 PostgreSQL 的时序数据库

用这个

**Comment by yaobo-lab** [comment]
> TimescaleDB 1.6.0 发布，基于 PostgreSQL 的时序数据库
> 
> 用这个

 TimescaleDB 这个还没有用过。但  influxdb，跟 TDengine 就用了一年多了。TDengine 的确比 influxdb优秀。用过就知道。哈哈
