### ISSUE TITLE
多次为 't' 指定了列 'sex'。

### ISSUE THREAD

**Issue by cfires** [dotnetcore/FreeSql#507]
导航属性中存在一个同名字段时会报错，怎样可以避免
1.BodyAuditEntity

```c#
        [Column(Name = "Sex", StringLength = 2, Position = 4)]
        public string Sex { get; set; }

        [Navigate(nameof(ClassId))]
        public virtual BodyScheduleEntity ClassInfo { get; set; }
```

2.BodyScheduleEntity

`[Column(Name = "Sex", StringLength = 2, Position = 4)]
        public string Sex { get; set; }`
       

3.查询

```c#
 var list = await _bodyAuditRepository.Select
                .Where(a => a.DataType == unitType)
                .WhereIf(!string.IsNullOrEmpty(key), a => a.Name.Contains(key) || a.IdCard.Contains(key))
                **.Include(a => a.ClassInfo)**
                .Count(out var total)
                .OrderBy(true, a => a.CheckState)
                .OrderBy(true, a => a.ClassInfo.period)
                .OrderBy(true, a => a.ClassInfo.className)
                .OrderByDescending(true, a => a.CreatedTime)
                .Page(req.CurrentPage, req.PageSize)
                .ToListAsync();
```

**Comment by 2881099** [comment]
继承的？把实体类完整的发一下

**Comment by cfires** [comment]
1.  BodyAuditEntity 【包含Sex字段和BodyScheduleEntity 实体类的导航属性】
`public class BodyAuditEntity : BaseEntity
    {
        /// <summary>
        /// 班期标识-BodyScheduleEntity班期主键
        /// </summary>
        [Column(Name = "ClassId", StringLength = 70, Position = 2)]
        public string ClassId { get; set; }

        /// <summary>
        /// 姓名
        /// </summary>
        [Column(Name = "Name", StringLength = 20, Position = 3)]
        public string Name { get; set; }



        /// <summary>
        /// 出生日期
        /// </summary>
        [Column(Name = "Birthday", StringLength = 20, Position = 5)]
        public string Birthday { get; set; }

        /// <summary>
        /// 身份证
        /// </summary>
        [Column(Name = "IdCard", StringLength = 20, Position = 6)]
        public string IdCard { get; set; }

        /// <summary>
        /// 联系电话
        /// </summary>
        [Column(Name = "TelPhone", StringLength = 15, Position = 7)]
        public string TelPhone { get; set; }

        /// <summary>
        /// 学校名称
        /// </summary>
        [Column(Name = "SchoolName", StringLength = 50, Position = 8)]
        public string SchoolName { get; set; }

        /// <summary>
        /// 初潮年龄
        /// </summary>
        [Column(Name = "StuCCNL", StringLength = 20, Position = 9)]
        public int? StuCCNL { get; set; }

        /// <summary>
        /// 联系地址
        /// </summary>
        [Column(Name = "Address", StringLength = 100, Position = 10)]
        public string Address { get; set; }

        /// <summary>
        /// 审核状态
        /// </summary>
        [Column(Name = "CheckState")]
        public CheckState CheckState { get; set; }

        /// <summary>
        /// 审核人标识
        /// </summary>
        [Column(Name = "CheckUserId", StringLength = 70)]
        public string CheckUserId { get; set; }

        /// <summary>
        /// 审核人
        /// </summary>
        [Column(Name = "CheckUserName", StringLength = 20)]
        public string CheckUserName { get; set; }

        /// <summary>
        /// 审核时间
        /// </summary>
        [Column(Name = "CheckTime")]
        public DateTime? CheckTime { get; set; }

        /// <summary>
        /// 拒绝原因
        /// </summary>
        [Column(Name = "RefuseReason", StringLength = 100)]
        public string RefuseReason { get; set; }

        /// <summary>
        /// 采集状态
        /// </summary>
        [Column(Name = "CollectionState")]
        public CollectionState? CollectionState { get; set; }

        /// <summary>
        /// 采集时间
        /// </summary>
        [Column(Name = "CollectionDate")]
        public DateTime? CollectionDate { get; set; }

        /// <summary>
        /// 附件标识（多附件）
        /// </summary>
        [Column(Name = "AttachmentId", StringLength = 500)]
        public string AttachmentId { get; set; }

        /// <summary>
        /// 单位类型 1：形体   2：社康
        /// </summary>
        [Column(Name = "DataType")]
        public UnitType DataType { get; set; }

        /// <summary>
        /// 性别
        /// </summary>
        [Column(Name = "Sex", StringLength = 2, Position = 4)]
        public string Sex { get; set; }

        #region 导航属性
        /// <summary>
        /// 班期信息
        /// </summary>
        [Navigate(nameof(ClassId))]
        public virtual BodyScheduleEntity ClassInfo { get; set; }
        #endregion
    }`
2. BodyScheduleEntity 【衣包含一个sex字段】
` public class BodyScheduleEntity : BaseEntity
    {
        [Column(Name = "period")] 
        public int? period { get; set; }

        [Column(Name = "maxQuota")] 
        public int? maxQuota { get; set; }

        [Column(Name = "allDays")] 
        public int? allDays { get; set; } 

        [Column(Name = "schoolId", StringLength = 64)] 
        public string bodySchoolId { get; set; }

        [Column(Name = "ownership", StringLength = 64)] 
        public string ownership { get; set; }


        [Column(Name = "className", StringLength = 20)] 
        public string className { get; set; }

        [Column(Name = "sex", StringLength = 10)] 
        public string sex { get; set; }

        [Column(Name = "classType", StringLength = 20)] 
        public string classType { get; set; }
    }`

**Comment by 2881099** [comment]
**.Include(a => a.ClassInfo)** 加这个报错？如何重现

**Comment by cfires** [comment]
是的 去掉就没问题（两个实体有同名字段的时候 你加导航属性试试）

**Comment by 2881099** [comment]
我就是没有重现，所以才问

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/blob/master/FreeSql.Tests/FreeSql.Tests/Issues/507.cs

这个是无法重现的测试，看下怎么重现？

**Comment by cfires** [comment]
大佬，方便远程么，挺多页面都有这个问题的



caofangzh@163.com
 
发件人： 2881099
发送时间： 2020-10-31 07:11
收件人： dotnetcore/FreeSql
抄送： cfires; Author
主题： Re: [dotnetcore/FreeSql] 多次为 't' 指定了列 'sex'。 (#507)
https://github.com/dotnetcore/FreeSql/blob/master/FreeSql.Tests/FreeSql.Tests/Issues/507.cs
这个是无法重现的测试，看下怎么重现？
―

**Comment by cfires** [comment]
就是你代码写的那样  当前实体的导航属性关联的表中存在一个字段和当前实体重名 就是上述Sex 就会报错

**Comment by cfires** [comment]
> https://github.com/dotnetcore/FreeSql/blob/master/FreeSql.Tests/FreeSql.Tests/Issues/507.cs
> 
> 这个是无法重现的测试，看下怎么重现？
![image](https://user-images.githubusercontent.com/17745971/98187521-12e67200-1f4c-11eb-8a0a-6f0a8466feef.png)

**Comment by cfires** [comment]
caofangzh@163.com
 
发件人： 2881099
发送时间： 2020-10-29 19:45
收件人： dotnetcore/FreeSql
抄送： cfires; Author
主题： Re: [dotnetcore/FreeSql] 多次为 't' 指定了列 'sex'。 (#507)
我就是没有重现，所以才问
―

**Comment by cfires** [comment]
`WITH t AS ( SELECT TOP 20 a.[ID], a.[REVISION], a.[IS_DISABLED], a.[IS_DELETED], a.[GROUP_ID], a.[CREATED_BY], a.[CREATED_BY_NAME], a.[CREATED_TIME], a.[UPDATED_BY], a.[UPDATED_BY_NAME], a.[UPDATED_TIME], a.[Category], a.[Name], a.[Sex], a.[BirthDate], a.[Mobile], a.[Mail], a.[PersonalProfile], a.[HonorCertificate], a.[BankInfo], a.[AccountId], a.[IsLogin], a.[UnitId], a.[SortIndex],
a__Account.[ID] as25, a__Account.[REVISION] as26, a__Account.[IS_DISABLED] as27, a__Account.[IS_DELETED] as28, a__Account.[GROUP_ID] as29, a__Account.[CREATED_BY] as30, a__Account.[CREATED_BY_NAME] as31, a__Account.[CREATED_TIME] as32, a__Account.[UPDATED_BY] as33, a__Account.[UPDATED_BY_NAME] as34, a__Account.[UPDATED_TIME] as35, a__Account.[USER_TYPE], a__Account.[USER_NAME], a__Account.[DISPLAY_NAME], a__Account.[MOBILE], a__Account.[PASSWORD], a__Account.[MAIL], a__Account.[PERMISSION_ID], a__Account.[WEXIN], a__Account.[AVATAR], a__Account.[DESCRIPTION],
a__School.[ID] as46, a__School.[REVISION] as47, a__School.[IS_DISABLED] as48, a__School.[IS_DELETED] as49, a__School.[GROUP_ID] as50, a__School.[CREATED_BY] as51, a__School.[CREATED_BY_NAME] as52, a__School.[CREATED_TIME] as53, a__School.[UPDATED_BY] as54, a__School.[UPDATED_BY_NAME] as55, a__School.[UPDATED_TIME] as56, a__School.[SchName], a__School.[SchType], a__School.[SchNature], a__School.[SchLinkMan], a__School.[SchPhone], a__School.[SchAddress], a__School.[DistinctId], a__School.[GuidCode], a__School.[SortIndex] as65,
a__Unit.[ID] as66, a__Unit.[REVISION] as67, a__Unit.[IS_DISABLED] as68, a__Unit.[IS_DELETED] as69, a__Unit.[GROUP_ID] as70, a__Unit.[CREATED_BY] as71, a__Unit.[CREATED_BY_NAME] as72, a__Unit.[CREATED_TIME] as73, a__Unit.[UPDATED_BY] as74, a__Unit.[UPDATED_BY_NAME] as75, a__Unit.[UPDATED_TIME] as76, a__Unit.[UnitName], a__Unit.[UnitType], a__Unit.[UnitAddress], a__Unit.[DistinctId] as80, a__Unit.[ParentId], a__Unit.[SortIndex] as82, a__Unit.[LinkMan], a__Unit.[LinkPhone], ROW_NUMBER() OVER(
ORDER BY a.[Category], a.[UnitId], a.[SortIndex]) AS __rownum__
FROM [Basic_Staff] a
LEFT JOIN [Basic_UnitManage] a__Unit ON a__Unit.[ID] = a.[UnitId] AND ((a__Unit.[IS_DELETED] = 0))
LEFT JOIN [Basic_School] a__School ON a__School.[ID] = a.[UnitId] AND ((a__School.[IS_DELETED] = 0))
LEFT JOIN [sys_user] a__Account ON a__Account.[ID] = a.[AccountId] AND ((a__Account.[IS_DELETED] = 0))
WHERE ((a.[IS_DELETED] = 0)) ) SELECT t.* FROM t where __rownum__ > 10`

**Comment by 2881099** [comment]
给一个能运行的 console 程序 demo

**Comment by 2881099** [comment]
是不是需要升级解决的问题？

**Comment by cfires** [comment]
FreeSql版办从1.6.0升级到最新版本1.10.1后，该问题消失

**Comment by cfires** [comment]
是的 需要升级（问题版本1.6.0）

**Comment by cfires** [comment]
> FreeSql版本从1.6.0升级到最新版本1.10.1后，该问题消失

是的 需要升级（问题版本1.6.0）

**Comment by cfires** [comment]
> 是不是需要升级解决的问题？

是的 需要升级（问题版本1.6.0）
