### ISSUE TITLE
多对多，如何查关系表数据

### ISSUE THREAD

**Issue by tonfy** [dotnetcore/FreeSql#509]
多对多，如何查关系表数据，谢谢

**Comment by tonfy** [comment]
> 多对多，如何查关系表数据，谢谢

`var key = input.Filter?.Path;
            var list = await _materialLibraryRepository.Select
            .WhereIf(key.NotNull(), a => a.Path.Contains(key))
            .Where(a => _objectMaterialRepository.Select.Where(i => i.ObjType == CommonConsts.COMMON_MATERIAL_TYPE_PARK).ToList(b => b.MaterialId).Contains(a.Id))
            .Count(out var total)
            .OrderByDescending(true, c => c.Id)
            .Page(input.CurrentPage, input.PageSize)
            .ToListAsync<MaterialLibraryListOutput>();`
打算改用子查询了

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/issues/508
看下这个。。多对多。用户列表展示对应的多个分组。

**Comment by tonfy** [comment]
> #508
> 看下这个。。多对多。用户列表展示对应的多个分组。

我这边倒不需要展示另一个表的数据，主要是关系表中有一个字段，我需要通过这个关系表的字段过滤数据。
大概的SQL是这样的.
`select ml.* from sys_material_library ml
left outer join sys_object_material om on ml.Id = om.MaterialId
where om.MaterialId is not null and om.ObjType = 'park' `
sys_material_library是素材表，sys_object_material 是对象素材关系表，因为这两个表是公共的表，所以在关系表中设计了一个字段来区分

**Comment by tonfy** [comment]
通过上面的子查询是可以实现的，只是想知道有没有更简便的方法，实现类似上面SQL语句的效果。

**Comment by tonfy** [comment]
sys_material_library素材<-sys_object_material对象素材（ObjType="park"）->mr_park园区
取sys_material_library素材表中只属于park的素材

**Comment by luoyunchong** [comment]
[http://freesql.net/select-multi-table.html#_9%E3%80%81asselect](http://freesql.net/select-multi-table.html#_9%E3%80%81asselect
)

```
fsql.Select<Category>()
  .Where(a => a.Topics.AsSelect().Any(b => b.Title.Contains("xx")))
  .ToList();
```
效果等同于：
```
fsql.Select<Category>()
  .Where(a => fsql.Select<Topic>().Any(b => b.Title.Contains("xx")))
  .ToList();
```

**Comment by tonfy** [comment]
ok,谢谢
