### ISSUE TITLE
希望2.0Ado.Query<XX>() 能够支持DataAnnotations特性映射行为，为保持旧版本兼容性，可以通过配置开关进行控制是否开启。

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#513]
希望2.0Ado.Query<XX>() 能够支持DataAnnotations特性映射行为，为保持旧版本兼容性，可以通过配置开关进行控制是否开启。

_Originally posted by @liuguiyou in https://github.com/dotnetcore/FreeSql/issues/469#issuecomment-715251504_

**Comment by 2881099** [comment]
请列出详细的行为机制，讨论一下看会不会影响到旧的使用习惯。

**Comment by liuguiyou** [comment]
FreeSqlBuilder 增加UseQueryDataAnnotations(bool  value)方法
默认配置不启用
UseQueryDataAnnotations(true)时启用；

Ado.Query<T>(string cmdText, object parms = null, bool? useDataAnnotations=null) 方法 
增加参数bool? useDataAnnotations, 当useDataAnnotations不为null时
用来覆盖通过FreeSqlBuilder配置的特性映射设置

现在只想到这么多

**Comment by 2881099** [comment]
比如Column下面哪些特性功能有效

**Comment by liuguiyou** [comment]
使用到Column的name场景最多, 现在遇到的问题主要是数据库里的字段使用下划线命名法，实体属性一般使用Pascal大小写命名，导致sql语句要给返回字段定义别名

**Comment by 2881099** [comment]
如果是特性 name，可以在现有基本上兼容，优先使用特性 name，如果匹配不到再用属性名
