### ISSUE TITLE
标识列插入显式值

### ISSUE THREAD

**Issue by lclijingxuan** [dotnetcore/FreeSql#514]
插入数据时，如果列Id是int类型，而且自增长。
我需要手动指定这一列的值（使用背景：我从数据库A同步数据到数据库B）
直接插入提示错误：标识列插入显式值
请问该怎么处理？
谢谢。

**Comment by 2881099** [comment]
是说 set identity on 这个问题吗？

**Comment by lclijingxuan** [comment]
> 是说 set identity on 这个问题吗？

是的。请问该怎么解决或解决思路。
谢谢。

**Comment by 2881099** [comment]
用的哪种插入方式。

可以这样试试：

```c#
using (var conn = fsql.Ado.MasterPool.Get())
{
    fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 on").WIthConnection(conn.Value).ExecuteNonQuery();
    fsql.Insert(items).WithConnection(conn.Value).InsertIdentity().ExecuteAffrows();
    fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 off").WIthConnection(conn.Value).ExecuteNonQuery();
}
```

**Comment by lclijingxuan** [comment]
> 用的哪种插入方式。
> 
> 可以这样试试：
> 
> ```cs
> using (var conn = fsql.Ado.MasterPool.Get())
> {
>     fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 on").WIthConnection(conn.Value).ExecuteNonQuery();
>     fsql.Insert(items).WithConnection(conn.Value).InsertIdentity().ExecuteAffrows();
>     fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 off").WIthConnection(conn.Value).ExecuteNonQuery();
> }
> ```

我试试看。
谢谢。

**Comment by lclijingxuan** [comment]
> 用的哪种插入方式。
> 
> 可以这样试试：
> 
> ```cs
> using (var conn = fsql.Ado.MasterPool.Get())
> {
>     fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 on").WIthConnection(conn.Value).ExecuteNonQuery();
>     fsql.Insert(items).WithConnection(conn.Value).InsertIdentity().ExecuteAffrows();
>     fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 off").WIthConnection(conn.Value).ExecuteNonQuery();
> }
> ```

我用的是Insert<T>(source).ExecuteAffrows()

我试试看。
谢谢。

**Comment by lclijingxuan** [comment]
> 用的哪种插入方式。
> 
> 可以这样试试：
> 
> ```cs
> using (var conn = fsql.Ado.MasterPool.Get())
> {
>     fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 on").WIthConnection(conn.Value).ExecuteNonQuery();
>     fsql.Insert(items).WithConnection(conn.Value).InsertIdentity().ExecuteAffrows();
>     fsql.Ado.CommandFluent("set IDENTITY_INSERT 表名 off").WIthConnection(conn.Value).ExecuteNonQuery();
> }
> ```

或者有更简单的写法吗？
