### ISSUE TITLE
软删除

### ISSUE THREAD

**Issue by Tony518** [dotnetcore/FreeSql#516]
你好，请问有没有全局软删除的实现方案？
查询和删除自动过滤IsDelete条件？

**Comment by luoyunchong** [comment]
http://freesql.net/filters.html
会

**Comment by Tony518** [comment]
嗯，谢谢，我用了仓储的形式， 不过有一个问题，我执行Delete方法是，生成的sql是这样的`DELETE FROM [ProductDirectory] WHERE ([Id] IN (1)) AND ([IsDeleted] = 0)`， 我的数据还是被删除了

**Comment by luoyunchong** [comment]
自动过滤IsDelete条件。。

查询当然是 IsDelete条件。。`[IsDeleted] = 0`是指查未删除的。

删除自然也是 增加同样的过滤，删除未删除的。只是会过滤条件。不会把删除操作变成修改操作。

**Comment by luoyunchong** [comment]
https://github.com/zhontai/Admin.Core/blob/master/Admin.Core.Repository/Base/RepositoryBase.cs

删除时，如需软删除，可参考这个，继承现有的仓储增加新的API。
```
        public async Task<bool> SoftDeleteAsync(TKey id)
        {
            await UpdateDiy
                .SetDto(new { 
                    IsDeleted = true, 
                    ModifiedUserId = _user.Id, 
                    ModifiedUserName = _user.Name 
                })
                .WhereDynamic(id)
                .ExecuteAffrowsAsync();
            return true;
        }
```

**Comment by Tony518** [comment]
谢谢

**Comment by Huahuz** [comment]
软删除对于导航属性似乎是不太友好。
