### ISSUE TITLE
FreeSql 能否改成非单例模式并且实现异步事务，目前使用仓储和UnitOfWork模式实现异步事务进行多表操作，代码不够简洁

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#520]
FreeSql 能否改成非单例模式并且实现异步事务，目前使用仓储和UnitOfWork模式实现异步事务进行多表操作，代码不够简洁

_Originally posted by @windhuan in https://github.com/dotnetcore/FreeSql/issues/469#issuecomment-721586580_

**Comment by 2881099** [comment]
异步事务的问题，可以先提出解决方法，提供一个参考来讨论

**Comment by 2881099** [comment]
IFreeSql 单例没影响，把它看成 Dbcontext 或者 repository 的配置

**Comment by zhouandke** [comment]
试一试这个 [IFreeSql 事务另类玩法](https://github.com/dotnetcore/FreeSql/issues/322)
