### ISSUE TITLE
1.8.1版本之后使用SetSource更新数据报错

### ISSUE THREAD

**Issue by wzohxia** [dotnetcore/FreeSql#521]
```c#
var item = new List<Users>();

item.Add(new Users { ID = 1000000000000000001, SpellCode = "ces",Version=1 });

await _freeSql.Update<Users>().SetSource(item).UpdateColumns(info=>info.SpellCode).ExecuteAffrowsAsync();
```
![image](https://user-images.githubusercontent.com/22089141/98205289-d11cf200-1f72-11eb-9611-dd98f31b3f53.png)

v1.8.1不会报错 1.8.1以上的版本会报错

**Comment by 2881099** [comment]
实体类发一下，报的什么错

**Comment by wzohxia** [comment]
我试了实体类标签
`
[Key]
        public long ID { get; set; }

        [Description("名字")]
        public string Name { get; set; }

        [Description("账号")]
        [Column(IsNullable = false)]
        public string Account { get; set; }

        [Description("名称拼音首字母")]
        public string SpellCode { get; set; }

        [Description("乐观锁")]
        [Column(IsVersion = true, InsertValueSql = "1")]
        public long Version { get; set; }
`

如果 [Column(IsNullable = false)] 不使用就不会报错 使用了就会报错

**Comment by 2881099** [comment]
经过测试没有重现问题，测试代码：

https://github.com/dotnetcore/FreeSql/blob/5ad30ccb91f00033d6765cf86a0d37fe970aa01d/FreeSql.Tests/FreeSql.Tests/Issues/521.cs

**Comment by wzohxia** [comment]
```
 fsql.Aop.AuditValue += (s, e) => {
                if (e.Column.CsType == typeof(long)
                    && e.Property.GetCustomAttribute<SnowflakeAttribute>(false) != null
                    && e.Value?.ToString() == "0") {
                    e.Value =1;
                }
                
            };
```
我扩展了Aop  增加了SnowflakeAttribute 标签判断  去除这段就不会报错  增加了就会产生上述问题

**Comment by 2881099** [comment]
问题重现了，确实是个 bug，是 1.8.1 改出来的

**Comment by wzohxia** [comment]
好的

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/commit/8eadde930f4b1233b634ccf4b9e591d484f251e9

bug 这个时候产生的。准备发布 1.8.2、1.9.1、1.10.2 修复该问题。

**Comment by 2881099** [comment]
1.8.2、1.9.1、1.10.2 和当前 2.0.0-preview 最新版本一样
