### ISSUE TITLE
Sqlite encryption

### ISSUE THREAD

**Issue by zsolt777** [dotnetcore/FreeSql#523]
Hi! 

Could you tell me please how to use FreeSql to encrypt Sqlite database?

Thank you!

**Comment by 2881099** [comment]
It is reported that due to commercial issues, the default sqlit does not provide encryption.

However, it can be compiled and used by itself, and the user bears the commercial risk.

---

Solution:

Recompile the file. System.Data.SQLite Changed to Microsoft.Data.Sqlite.
