### ISSUE TITLE
只想查询其中的一部分字段

### ISSUE THREAD

**Issue by lclijingxuan** [dotnetcore/FreeSql#524]
假如对象MyObj有字段A, B, C....等很多字段，在查询时，我只想查询其中的一部分字段，而且返回值是List<MyObj>。
我的实现过程是：
freesql.Select\<MyObj\>()
.WithSql("select A, B, C from MyObj where ...")
.ToList();

但是查看时sql时，变成了下面这样：
select a.A, a.B, a.C, a....
from (
    传入的sql语句
) as a

而且出错了。错误提示：
除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。

请问该如何实现，才可以达到只查询其中一部分字段的效果。
谢谢。

**Comment by 2881099** [comment]
```c#
fsql.Select<MyObj>()
   .ToList(a => new MyObj
   {
       A = a.A, B = a.B
   });
```

**Comment by lclijingxuan** [comment]
(⊙o⊙)
谢谢。
