### ISSUE TITLE
github太卡，还有其他地方例如博客园或者gitee上可以提出问题吗？

### ISSUE THREAD

**Issue by lclijingxuan** [dotnetcore/FreeSql#525]
github太卡，而且也是英文的，使用诸多不便。
请问还有其他地方例如博客园或者gitee上可以提出问题吗？

**Comment by luoyunchong** [comment]
QQ群：4336577(已满)、8578575(在线)、52508226(在线)

**Comment by 2881099** [comment]
github 消息推送能及时收到

并且数据能得以保留，以便后来者查询，这点特别重要。

**Comment by lclijingxuan** [comment]
明白了。
最近使用了你的freesql，感觉很好用。
真的很感谢你。
