### ISSUE TITLE
关于mysql存储emoji图标问题

### ISSUE THREAD

**Issue by cctczyg** [dotnetcore/FreeSql#526]
大佬，咨询一下，我的用户表中有一个存储emoji图标的Nick字段，用的utf8mb4_general_ci字符集，未存储数据时，程序启动不会报错，但存储了一条数据之后，程序启动时初始化报以下错：

ALTER TABLE `xxx`.`UserInfo` MODIFY `Nick` NVARCHAR(50);
Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'Nick' at row 2

这是最近升级到1.10.1后出现的，以前没有这个问题，是不是有新套路了？谢谢

**Comment by luoyunchong** [comment]
把表的结构改成utf8mb4_general_ci

**Comment by cctczyg** [comment]
改了照旧

**Comment by 2881099** [comment]
1.10.1 没有这方面的功能修改

**Comment by luoyunchong** [comment]
连接串字符指定utf8mb4  @cctczyg 

Charset=utf8mb4;
