### ISSUE TITLE
修改部分字段与期望值不符合

### ISSUE THREAD

**Issue by lclijingxuan** [dotnetcore/FreeSql#529]
对象MyObj
    public class MyObj
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Gender Sex { get; set; } // Gender是枚举类型
        public DateTime Birth { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
    }
对应表MyObj，字段也是一一对应
我想修改其中的一部分字段
            _freeSql.Update<MyObj>()
                .SetSource(myObjs)
                **.Set(x => x.Number)
                .Set(x => x.Address)**
                .ExecuteAffrows();

期望的结果应该是修改Number、Address这两个字段，实际结果却是修改了Sex、Birth、Number、Address这四个字段

**Comment by 2881099** [comment]
Set、SetSource、SetDto 三个是平级功能，分别对应：

Set 在知道实体的时候使用，对应 update t set x = x 

SetSource 更新整个实体，可以配合 UpdateColumns/IgnoreColumns 指定或忽略字段

SetDto 是 Set 的批量操作

**Comment by lclijingxuan** [comment]
原来是我使用的方式不正确。我再试试。
谢谢。
