### ISSUE TITLE
我如何实现这样的更新操作呢?

### ISSUE THREAD

**Issue by lfq24** [dotnetcore/FreeSql#531]
请教一下:我的想实现这样的更新操作. SQL如下:
update tableA set Name = 'a' where UserId = 1 and Id in (select B.Id from tableB as B where B.Id>100);
我尝试这样不行,
Db.fsql.Update<tableA>()
              .Set(a => a.Name, 'a')
              .Where(a => a.UserId == 1)
//加下面的就出错了
              .Where(a => Db.fsql.Select<tableB >()
                  .Where(b => b.Id >100)
                  .ToList((b) => b.Id).Contains(a.Id));

**Comment by 2881099** [comment]
Db.fsql.Select()
.Where(b => b.Id >100)
.ToUpdate看看这个

**Comment by 2881099** [comment]
检查返回的 sql
