### ISSUE TITLE
Count() 增加一种模式, 可以指定DISTINCT 字段

### ISSUE THREAD

**Issue by zhouandke** [dotnetcore/FreeSql#533]
一个用户总是属于一个城市, 我想统计 用户所属城市的数量(只需要城市数量), 现在的查询方法是
`var count = fsql.Select<Person>().Distinct().ToList(o => o.CityId).Count();`
但这会导致所有 CityId 被读取到内存中, 再统计数量, 生成的语句
`SELECT DISTINCT a.[CityId] as1 FROM [Person] a`
可不可以增加一种模式, 直接生成
`SELECT COUNT(DISTINCT p.CityId) FROM [Person] p`
当然有可能是这样的形势
`var count = fsql.Select<Person>().Distinct(o => o.CityId).Count();`

**Comment by luoyunchong** [comment]
.First(a => Convert.ToInt64("count(DISTINCT(member_id))"))

**Comment by 2881099** [comment]
参考自定义表达式书解析文档

**Comment by luoyunchong** [comment]
@2881099 
```
        [Fact]
        public void Distinct()
        {

            long count = g.mysql.Select<testInsertNullable>().Select(a => a.price).Distinct().Count();
            /*生成的SQL，错误。Select(a=>a.price) 用的FreeSqlExtensionsLinqSql中的扩展方法。
              SELECT DISTINCT count(1) as1  FROM `testInsertNullable` a
             */

            /* 这才是对的SQL
             SELECT count(DISTINCT str1)  as1 FROM `testInsertNullable` a 
            */

            var list = g.mysql.Select<testInsertNullable>().Select(a => a.price).Distinct().ToList();
            //SELECT DISTINCT a.`price` as1  FROM `testInsertNullable` a
        }
```


![image](https://user-images.githubusercontent.com/18613266/98469949-7ce96a80-221d-11eb-82b7-e47abb29ba27.png)

**Comment by 2881099** [comment]
```c#
.Aggregate(a => Convert.ToInt32("count(distinct title)"), out var count)
.ToList();
```
