### ISSUE TITLE
多对多延时加载问题

### ISSUE THREAD

**Issue by zijiaxing** [dotnetcore/FreeSql#538]
1. T_TERM_TEACHER表：
`public partial class T_TERM_TEACHER {

		/// <summary>
		/// 主键ID
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)", IsPrimary = true)]
		public string ID { get; set; }

		/// <summary>
		/// 添加人(监察员主键ID)
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)")]
		public string ADDERID { get; set; }

		/// <summary>
		/// 添加时间
		/// </summary>
		[JsonProperty, Column(DbType = "DATE(7)")]
		public DateTime? ADDTIME { get; set; }

		/// <summary>
		/// 班级主键ID
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)")]
		public string CLASSID { get; set; }

		/// <summary>
		/// 删除时间
		/// </summary>
		[JsonProperty, Column(DbType = "DATE(7)")]
		public DateTime? DELTIME { get; set; }

		/// <summary>
		/// 年级主键ID
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)")]
		public string GRADEID { get; set; }

		/// <summary>
		/// 是否删除
		/// </summary>
		[JsonProperty]
		public bool? ISDEL { get; set; } = false;

		/// <summary>
		/// 序号
		/// </summary>
		[JsonProperty, Column(DbType = "NUMBER(22)")]
		public decimal? ORDERNUM { get; set; }

		/// <summary>
		/// 幼儿园主键ID
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)")]
		public string SCHOOLID { get; set; }

		/// <summary>
		/// 教师主键ID
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)")]
		public string TEACHERID { get; set; }

		public virtual T_TEACHER TEACHER { get; set; }

        /// <summary>
        /// 教师编号
        /// </summary>
        [JsonProperty, Column(DbType = "VARCHAR2(20 BYTE)")]
		public string TEACHERNO { get; set; }

		/// <summary>
		/// 期次主键ID
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)")]
		public string TERMID { get; set; }

        public virtual T_TERM TERM { get; set; }
    }`
2. T_TEACHER表：
`public partial class T_TEACHER {

		/// <summary>
		/// 主键
		/// </summary>
		[JsonProperty, Column(DbType = "CHAR(36 BYTE)", IsPrimary = true)]
		public string ID { get; set; }

		/// <summary>
		/// 出生年月
		/// </summary>
		[JsonProperty, Column(DbType = "DATE(7)")]
		public DateTime? BIRTHDAY { get; set; }

		/// <summary>
		/// 学历(0.高中、中专及以下 1.大专 2.本科 3.硕士 4.博士)
		/// </summary>
		[JsonProperty, Column(DbType = "NUMBER(2)")]
		public decimal? EDUCATION { get; set; }

		/// <summary>
		/// 性别(0.男 1.女)
		/// </summary>
		[JsonProperty, Column(DbType = "NUMBER(2)")]
		public decimal? SEX { get; set; }

		/// <summary>
		/// 专业
		/// </summary>
		[JsonProperty, Column(DbType = "VARCHAR2(100 BYTE)")]
		public string SPECIALITIES { get; set; }

		/// <summary>
		/// 教师姓名
		/// </summary>
		[JsonProperty, Column(DbType = "VARCHAR2(100 BYTE)")]
		public string TEACHERNAME { get; set; }

		/// <summary>
		/// 从业年份
		/// </summary>
		[JsonProperty, Column(DbType = "NUMBER(22)")]
		public decimal? WORKYEAR { get; set; }

		[Navigate(ManyToMany = typeof(T_TERM_TEACHER))]
		public virtual ICollection<T_TERM> TERMs { get; set; }
    }`
3. T_TERM表：
`public partial class T_TERM
    {

        /// <summary>
        /// 主键ID
        /// </summary>
        [JsonProperty, Column(DbType = "CHAR(36 BYTE)", IsPrimary = true)]
        public string ID { get; set; }

        /// <summary>
        /// 删除时间
        /// </summary>
        [JsonProperty, Column(DbType = "DATE(7)")]
        public DateTime? DELTIME { get; set; }

        /// <summary>
        /// 采集信息结束时间
        /// </summary>
        [JsonProperty, Column(DbType = "DATE(7)")]
        public DateTime? ENDDATE { get; set; }

        /// <summary>
        /// 是否删除
        /// </summary>
        [JsonProperty]
        public bool? ISDEL { get; set; } = false;

        /// <summary>
        /// 评审结束时间
        /// </summary>
        [JsonProperty, Column(DbType = "DATE(7)")]
        public DateTime? REVIEWENDDATE { get; set; }

        /// <summary>
        /// 评审开始时间
        /// </summary>
        [JsonProperty, Column(DbType = "DATE(7)")]
        public DateTime? REVIEWSTARTDATE { get; set; }

        /// <summary>
        /// 采集信息开始时间
        /// </summary>
        [JsonProperty, Column(DbType = "DATE(7)")]
        public DateTime? STARTDATE { get; set; }

        /// <summary>
        /// 期次名称
        /// </summary>
        [JsonProperty, Column(DbType = "VARCHAR2(100 BYTE)")]
        public string TERMNAME { get; set; }

        /// <summary>
        /// 年份
        /// </summary>
        [JsonProperty, Column(DbType = "NUMBER(22)")]
        public decimal? YEARNAME { get; set; }

        /// <summary>
        /// 教师列表
        /// </summary>
        [Navigate(ManyToMany = typeof(T_TERM_TEACHER))]
        public virtual ICollection<T_TEACHER> TEACHERs { get; set; }
    }`

查询语句：
`this.fsql.Select<T_TERM>()
                        .ToList();`

查询时报错：
![image](https://user-images.githubusercontent.com/6667659/99046729-250c8400-25ce-11eb-9eb7-8391946b80de.png)

**Comment by 2881099** [comment]
JSON 序列化的问题，与 orm 无关。

**Comment by 2881099** [comment]
\[JsonIgnore] 用起来

**Comment by zijiaxing** [comment]
必须用System.Text.Json.Serialization.JsonIgnore
而不是Newtonsoft.Json.JsonIgnore？？？

**Comment by 2881099** [comment]
具体看你用的哪个 Json 库了

**Comment by zijiaxing** [comment]
我用的Newtonsoft.Json，但是使用Newtonsoft.Json.JsonIgnore不行，换成System.Text.Json.Serialization.JsonIgnore就可以了

**Comment by 2881099** [comment]
JSON 序列化的问题，与 orm 无关。
