### ISSUE TITLE
实体类实现IEnumerable会报错…

### ISSUE THREAD

**Issue by ZZhenMiao** [dotnetcore/FreeSql#54]
不知道是不是我技艺不精哪里没弄懂……？
实体类T实现IEnumerable<subT>接口后，无法执行 CodeFirst.SyncStructure<T>();
错误提示：System.NullReferenceException:“未将对象引用设置到对象的实例。”

**Comment by 2881099** [comment]
不，你技艺很精。。。是我们没有开放

if (typeof(IEnumerable).IsAssignableFrom(entity)) return null;

大概是这样的一个判断，防止集合导航属性，pgsql 数组，也被当成了实体迁移。

**Comment by 2881099** [comment]
好吧，这里可以提升一个级别，判断 ICollection 不给通过

**Comment by 2881099** [comment]
兄弟，你使用的实体继承 IEnumable 大概长的是什么样子，方便发出来看下吗？解决什么样的场景

**Comment by ZZhenMiao** [comment]
啊哦原来如此，其实并不是必须继承那个接口，只是我在没有使用FreeSql之前，写了很多业务层的基类，自己定义了一些集合方式包括ITree等基础结构类型。

**Comment by ZZhenMiao** [comment]
在DB层方面，FreeSql肯定比我考虑得要多得多，没有开放自然是有原因的。我只需契合FreeSql重新改写一下那些基类就可以啦。

**Comment by 2881099** [comment]
好吧，那我们这边就不改动规则啦

**Comment by ZZhenMiao** [comment]
啊哈哈哈，当然，如果您经过深思熟虑，发现提升判断级别后，不会对其它方面造成影响。我还是建议提升一下，毕竟IEnumable对于.Net来说还是非常基础，非常重要的一个接口。

**Comment by 2881099** [comment]
if (typeof(IEnumerable).IsAssignableFrom(entity) && entity.IsGenericParameter == true) return null;

好的，暂时先这样。内部没问题，只会发生使用问题。比如：

Delete(IEnumable<T> items);

如果某实体这样实现的：

```csharp
class TestEnumable : IEnumable<TestEnumable> {
}
```

应该会有些使用上的冲突

**Comment by ZZhenMiao** [comment]
(づ￣ 3￣)づ
