### ISSUE TITLE
dbfirst 属性出现SYS_NC0000$  

### ISSUE THREAD

**Issue by yilei63** [dotnetcore/FreeSql#542]
数据脚本：
-- Create table
create table TEST_INDEX
(
  ID   NUMBER not null,
  TIME DATE
)
tablespace Testdb
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );
-- Add comments to the table 
comment on table TEST_INDEX
  is '测试自动创建索引列';
-- Create/Recreate primary, unique and foreign key constraints 
alter table TEST_INDEX
  add constraint PK_TESTINDEX primary key (ID)
  using index 
  tablespace Testdb
  pctfree 10
  initrans 2
  maxtrans 255;
-- Create/Recreate indexes 
create index IX_ITEM on TEST_INDEX (TO_CHAR(TIME,'yyyymm'))
  tablespace Testdb
  pctfree 10
  initrans 2
  maxtrans 255;
问题：只要创建索引时，使用函数，那么就会出现以SYS_NC开头的隐含字段
select *   from dba_ind_columns t  where T.Column_Name LIKE '%$'    and t.table_owner = '表拥有者' 
通过此语句可以查看

**Comment by 2881099** [comment]
已解决，请知晓
