### ISSUE TITLE
freesql现在已有codefirst功能，能不能有版本管理？跟FluentMigrator类似？

### ISSUE THREAD

**Issue by asine** [dotnetcore/FreeSql#544]
freesql现在已有codefirst功能，能不能有版本管理？跟FluentMigrator类似？

**Comment by 2881099** [comment]
FreeSql CodeFirst 默认只推荐在开发环境中使用。

- 自动对比更新，每次都会执行，版本号将非常多
- fsql.CodeFirst.GetComparisonDDLStatements 可以对比实体类与表的变化
