### ISSUE TITLE
是否可以重写表名和列名？

### ISSUE THREAD

**Issue by qiang999** [dotnetcore/FreeSql#545]
我的model定义如下：
![image](https://user-images.githubusercontent.com/15817336/99504297-4ef0ec80-29ba-11eb-9857-caea3c760b24.png)
使用freesql出的sql应该为a.CodeLength
而我的数据库使用SnakeCase编码，结构如下：
![image](https://user-images.githubusercontent.com/15817336/99504492-924b5b00-29ba-11eb-8d8c-2d8c6d75ada8.png)
是否可以提供一个方法去做转化？或者可以提供个解决方向？
谢谢！

**Comment by 2881099** [comment]
请看 Freesqlbuilder 的方法 UseNameConvert 方法，注释

**Comment by qiang999** [comment]
谢谢 
通过FreeSqlBuilder获取IFreeSql 可以通过UseNameConvert方法
如果集成ABP Vnext通过IDbConnection 对应的 IFreeSql 实例是否也可以支持，目前好像只能使CodeFirst.IsSyncStructureToLower进行大小写转换
IFreeSql fsql = repo.DbConnection.GetFreeSql(); //获取 IFreeSql 实例
https://github.com/dotnetcore/FreeSql/issues/267

**Comment by 2881099** [comment]
其实是 IFreeSql aop 功能实现的，具体看 Freesqlbuilder.cs 里面的代码

**Comment by 2881099** [comment]
把 freesqlbuilder.cs 里面定义的 aop 代码抠出来

**Comment by qiang999** [comment]
已解决，谢谢
