### ISSUE TITLE
代码生成器 SqlServer 生成不了自定义类别

### ISSUE THREAD

**Issue by yujun2354** [dotnetcore/FreeSql#546]
SqlServerCodeFirst里边
找到问题 inner join sys.types b on b.user_type_id = a.user_type_id 
并更改为 inner join systypes b on b.xusertype = a.system_type_id

**Comment by 2881099** [comment]
实体类生成器吗，对应应该是 SqlServerDbFirst

另外自定义类型是什么场景使用，这里的代码需要考虑 sqlserver 2005 兼容。

解决办法：下载源码，修改 SqlServerDbFirst，重新编译 FreeSql.Generator 这个项目(记得修改版本号)，本地更新

> dotnet tool update -g FreeSql.Generator —add-sourcr bin/Debug/

**Comment by yujun2354** [comment]
PowerDesigner里边自定义Domains
![1605697050(1)](https://user-images.githubusercontent.com/48638015/99521875-edd41380-29cf-11eb-93de-73d34e08fc11.png)

**Comment by yujun2354** [comment]
设计数据库时，很多字段类型都是一样的，为了方便自定义Domains，在生成数据库时会生成自定义类型

**Comment by 2881099** [comment]
按照 2楼 给的解决办法，解决了吗

**Comment by yujun2354** [comment]
已解决
