### ISSUE TITLE
实体特性设置ServerTime为utc时，查询时候是否能自动utc时间?

### ISSUE THREAD

**Issue by sundayisblue** [dotnetcore/FreeSql#547]
如果数据库里存入的utc，你还要再转一次吗？？

**Comment by 2881099** [comment]
上次说错了，实体特性设置ServerTime为utc，只代表【插入或更新的时候】使用 【数据库的utc时候】。

跟查询自动  utc 时间无关，查询回来的是数据库表已存在的数据值。
