### ISSUE TITLE
迁移到.NET 5报错，数据库为Oracle

### ISSUE THREAD

**Issue by Wenchel** [dotnetcore/FreeSql#549]
一切都没改变的情况下，由3.1升到5，使用Oracle数据库（使用FreeSql.Provider.Oracle），报“Exception has been thrown by the target of an invocation.”错误。
![image](https://user-images.githubusercontent.com/27775368/99660272-18d86900-2a9d-11eb-93b1-0efa063ee0e9.png)
配置代码如下：
![image](https://user-images.githubusercontent.com/27775368/99660398-47564400-2a9d-11eb-9e42-120496ead6a0.png)
同样的情况下，使用SQLServer（使用FreeSql.Provider.SqlServer），一切正常，配置代码如下：
![image](https://user-images.githubusercontent.com/27775368/99660688-acaa3500-2a9d-11eb-8a5b-27ad3dfa65dd.png)
运行正常：
![image](https://user-images.githubusercontent.com/27775368/99660764-c6e41300-2a9d-11eb-92d2-9871474300a9.png)

**Comment by Wenchel** [comment]
我又新建一个3.1的工程，用同样的配置使用Oracle：
![image](https://user-images.githubusercontent.com/27775368/99662783-ad909600-2aa0-11eb-8bb0-08bc34120cda.png)
一切正常：
![image](https://user-images.githubusercontent.com/27775368/99662888-d0bb4580-2aa0-11eb-957a-3521736bf503.png)

**Comment by 2881099** [comment]
经检查，错误发生成 OracleConnection .Open 方法。

Oralce 驱动与 .net5 不兼容导致，要等待 Oracle 修复问题。

或者暂时先不急着升级到 .net 5.0
