### ISSUE TITLE
代码生成器生成的字段顺序和数据库的表字段顺序不一致

### ISSUE THREAD

**Issue by hvppy** [dotnetcore/FreeSql#550]
代码生成器生成的字段顺序和数据库的表字段顺序不一致

**Comment by 2881099** [comment]
主键字段，外键字段，字段名

**Comment by 2881099** [comment]
主键最前面，其次是外键，最后是普通字段按名称

**Comment by hvppy** [comment]
测试下来,普通字段会按照名称进行排序

**Comment by 2881099** [comment]
是会按名称排序

order by 是否主键, 是否外键, 名称

**Comment by hvppy** [comment]
是否可以考虑只是主键和外键移到最前面,普通字段还是维持和数据库一致呢

**Comment by 2881099** [comment]
这个后面再考虑，如果现在解决可以尝试：

下载源码，拿 sqlsever 为例，Providers\FreeSql.Provider.SqlServer\SqlServerDbFirst.cs 看 503 行，注释它。

修改 Extensions\FreeSql.Generator\FreeSql.Generator.csproj 版本号，重新编译它。

进入 Extensions\FreeSql.Generator\bin\Debug 目录，进入目录 cmd 命令，执行命令：

> dotnet tool update -g FreeSql.Generator --add-source ./

**Comment by zilo555** [comment]
> 这个后面再考虑，如果现在解决可以尝试：
> 
> 下载源码，拿 sqlsever 为例，Providers\FreeSql.Provider.SqlServer\SqlServerDbFirst.cs 看 503 行，注释它。
> 
> 修改 Extensions\FreeSql.Generator\FreeSql.Generator.csproj 版本号，重新编译它。
> 
> 进入 Extensions\FreeSql.Generator\bin\Debug 目录，进入目录 cmd 命令，执行命令：
> 
> > dotnet tool update -g FreeSql.Generator --add-source ./
完美  不习惯命名排序。。。
既然是Dbfirst还是习惯按数据库的字段顺序来。。

**Comment by luoyunchong** [comment]
![(S_K4@V%Y}K4T IXZ47~%V7](https://user-images.githubusercontent.com/18613266/120761123-70c15380-c547-11eb-8dfa-62e0d06677b8.png)

运行FreeSql.Generator  命令工具后，可以生成模板。。 会生成一个.bat 。会有一个  -Razor 指定模板。可以修改此模板。如上文位置增加。.OrderBy(r=>r.Position).ToList()

可参考：
[FreeSql生成实体类.zip](https://github.com/dotnetcore/FreeSql/files/6596507/FreeSql.zip)
