### ISSUE TITLE
IncludeMany是否可以支持AsTable？

### ISSUE THREAD

**Issue by qiang999** [dotnetcore/FreeSql#551]
分库分表后，子表也会是一个实体对应多个数据库表，通过IncludeMany查询子表是否也可以AsTable?

**Comment by 2881099** [comment]
可以，在主体上设置，或者在 then 参数上设置

**Comment by qiang999** [comment]
> 可以，在主体上设置，或者在 then 参数上设置

感谢大佬，then上设置可行

**Comment by qiang999** [comment]
大佬帮忙看一下，写法有什么问题吗？生成的sql不太对劲
DbConnection.Select<Reimbursement>().AsTable((type, oldname) => "bpm_reimbursement").IncludeMany(x => x.Items.Where(v => v.ReimbursementId == x.Id), then => then.AsTable((type, oldname) => "bpm_reimbursement_item")).ToList();
sql:
SELECT  * from (SELECT a."id", a."creation_time", a."creator_id", a."last_modification_time", a."last_modifier_id", a."is_deleted", a."deleter_id", a."deletion_time", a."tenant_id", a."reimbursement_id", a."date", a."details", a."invoice_no", a."amount", a."tax", a."total_amount", a."rate" 
FROM "bpm_reimbursement" a 
WHERE ((a."reimbursement_id") in ('d6cd4947-98e2-4733-bbbd-03833a6bcf5a'))) ftb
 
UNION ALL
 
SELECT  * from (SELECT a."id", a."creation_time", a."creator_id", a."last_modification_time", a."last_modifier_id", a."is_deleted", a."deleter_id", a."deletion_time", a."tenant_id", a."reimbursement_id", a."date", a."details", a."invoice_no", a."amount", a."tax", a."total_amount", a."rate" 
FROM "bpm_reimbursement_item" a 
WHERE ((a."reimbursement_id") in ('d6cd4947-98e2-4733-bbbd-03833a6bcf5a'))) ftb

**Comment by 2881099** [comment]
DbConnection.Select\<T>()

.AsTable((type, oldname) => type == typeof(T) ? "bpm_reimbursement" : oldname)

上级这个 AsTable 会向下级传染，所以这里要加个判断

**Comment by qiang999** [comment]
我觉得生成的sql表名应该没有问题，所以不存在参数传递的问题。
业务逻辑大概如下：
bpm_reimbursement为主表，bpm_reimbursement_item为明细表
我想通过freesql的includemany查询返回结构如下：
"code": null,
  "instanceId": null,
  "tenantId": null,
  "remarks": "",
  "totalAmount": 11,
  "items": [
    {
      "tenantId": null,
      "reimbursementId": "39f850cd-0a51-3fab-db56-f56f43dd8c30",
      "date": "2020-10-18T16:00:00",
      "details": "1",
      "invoiceNo": "1",
      "amount": 1,
      "tax": 0,
      "totalAmount": 0,
      "rate": 0,
      "isDeleted": false,
      "deleterId": null,
      "deletionTime": null,
      "lastModificationTime": null,
      "lastModifierId": null,
      "creationTime": "2020-10-19T10:11:27.501365",
      "creatorId": "5ec1fa87-d4e3-9ae9-7b8c-39f51b5c7694",
      "id": "39f850cd-0a8d-c956-2eab-f7b709ab08f2"
    }
  ],
  "attachments": [],
  "isDeleted": false,
  "deleterId": null,
  "deletionTime": null,
  "lastModificationTime": null,
  "lastModifierId": null,
  "creationTime": "2020-10-19T10:11:27.500801",
  "creatorId": "5ec1fa87-d4e3-9ae9-7b8c-39f51b5c7694",
  "id": "39f850cd-0a51-3fab-db56-f56f43dd8c30"
model定义如下：
bpm_reimbursement
public class Reimbursement : FullAuditedEntity<Guid>, IMultiTenant
    {
        public virtual Guid? TenantId { get; protected set; }

        public virtual string Code { get; set; }

        public virtual string InstanceId { get; set; }

        public virtual string Remarks { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public virtual decimal TotalAmount { get; set; }

        public virtual List<ReimbursementItem> Items { get; set; }

        public virtual List<ReimbursementAttachment> Attachments { get; set; }

        protected Reimbursement()
        {

        }

        public Reimbursement(Guid id, Guid? tenantId, string remarks, decimal totalAmount, string code, string instanceId)
        {
            Id = id;
            TenantId = tenantId;
            Remarks = remarks;
            TotalAmount = totalAmount;
            Code = code;
            InstanceId = instanceId;
            Items = new List<ReimbursementItem>();
        }

        public virtual Reimbursement AddItem(ReimbursementItem item)
        {
            Check.NotNull(item.Id, nameof(item.Id));
            if (this.Items == null) this.Items = new List<ReimbursementItem>();
            if (!this.Items.Any(p => p.Id == item.Id))
            {
                var reimbursement = new ReimbursementItem(item.Id, TenantId, this.Id, item.Date, item.Details, item.InvoiceNo, item.Amount, item.Tax, item.TotalAmount, item.Rate);
                Items.Add(reimbursement);
            }
            return this;
        }

        public virtual void RemoveReimbursement(ReimbursementItem item)
        {
            Check.NotNull(item, nameof(item));
            this.Items.RemoveAll(comp => comp.Id == item.Id);
        }

        public virtual Reimbursement AddAttachment(ReimbursementAttachment attachment)
        {
            Check.NotNull(attachment.Id, nameof(attachment.Id));
            if (this.Attachments == null) this.Attachments = new List<ReimbursementAttachment>();
            if (!this.Attachments.Any(ou => ou.Id == attachment.Id))
            {
                var reimbursement = new ReimbursementAttachment(attachment.Id, TenantId, this.Id, attachment.Type, attachment.Code, attachment.Name, attachment.FileName,
                    attachment.Format, attachment.RootUrl, attachment.UploadDate);
                Attachments.Add(attachment);
            }
            return this;
        }

        public virtual void RemoveAttachment(ReimbursementAttachment attachment)
        {
            Check.NotNull(attachment, nameof(attachment));
            Attachments.RemoveAll(ou => ou.Id == attachment.Id);
        }

        public Reimbursement UpdateItems(List<ReimbursementItem> list)
        {
            for (int i = Items.ToList().Count - 1; i >= 0; i--)
            {
                if (list.Any(p => p.Amount == Items.ToList()[i].Amount && p.Date == Items.ToList()[i].Date && p.Details == Items.ToList()[i].Details
                && p.InvoiceNo == Items.ToList()[i].InvoiceNo))
                {

                }
                else
                {
                    Items.Remove(Items.ToList()[i]);
                }
            }
            foreach (var item in list)
            {
                if (Items.Any(p => p.Amount == item.Amount && p.Date == item.Date && p.Details == item.Details && p.InvoiceNo == item.InvoiceNo))
                {

                }
                else
                {
                    Items.Add(new ReimbursementItem(
                        id: item.Id,
                        tenantId: item.TenantId,
                        reimbursementId: item.ReimbursementId,
                        date: item.Date,
                        details: item.Details,
                        invoiceNo: item.InvoiceNo,
                        amount: item.Amount,
                        totalAmount: item.TotalAmount,
                        rate: item.Rate,
                        tax: item.Tax));
                }
            }
            return this;
        }
    }
bpm_reimbursement_item
public class ReimbursementItem : FullAuditedEntity<Guid>, IMultiTenant
    {
        public virtual Guid? TenantId { get; protected set; }

        public virtual Guid ReimbursementId { get; set; }

        public virtual DateTime Date { get; set; }

        public virtual string Details { get; set; }

        public virtual string InvoiceNo { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public virtual decimal Amount { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public virtual decimal Tax { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public virtual decimal TotalAmount { get; set; }

        [Column(TypeName = "decimal(18, 2)")]
        public virtual decimal Rate { get; set; } 

        public ReimbursementItem() { }

        public ReimbursementItem(Guid id, Guid? tenantId, Guid reimbursementId, DateTime date, string details,
            string invoiceNo, decimal amount, decimal tax, decimal totalAmount, decimal rate)
        {
            Id = id;
            TenantId = tenantId;
            ReimbursementId = reimbursementId;
            Date = date;
            Details = details;
            InvoiceNo = invoiceNo;
            Amount = amount;
            Tax = tax;
            TotalAmount = totalAmount;
            Rate = rate;
        }

        public override object[] GetKeys()
        {
            return new object[] { Id, ReimbursementId };
        }
    }

**Comment by qiang999** [comment]
通过DbConnection.Select().AsTable((type, oldname) => "bpm_reimbursement").IncludeMany(x => x.Items.Where(v => v.ReimbursementId == x.Id), then => then.AsTable((type, oldname) => "bpm_reimbursement_item")).ToList()无法获取

**Comment by 2881099** [comment]
AsTable 多次会产生 UNION ALL 效果，这样吧：

```c#
DbConnection.Select<Reimbursement>()

.AsTable((type, oldname) => type == typeof(Reimbursement) ? 
     "bpm_reimbursement" : "bpm_reimbursement_item")

.IncludeMany(x => x.Items.Where(v => v.ReimbursementId == x.Id))

.ToList()
```

**Comment by qiang999** [comment]
我大概知道问题了，我没做astable也是报错的。
应该是通过DbConnection无法进行IncludeMany
后来我测试了下，
通过FreeSqlBuilder()获取实例是ok的
通过DbConnection不可以，应该是这个问题
后续是否考虑IDbConnection扩展支持IncludeMany？

**Comment by 2881099** [comment]
你之前发了一条回复，怎么撤销了？

```
我大概知道问题了，我没做astable也是报错的。
应该是通过DbConnection无法进行IncludeMany
后来我测试了下，
通过FreeSqlBuilder()获取实例是ok的
通过DbConnection不可以，应该是这个问题
后续是否考虑IDbConnection扩展支持IncludeMany？
```

**Comment by qiang999** [comment]
谢谢
不是这个原因，搞错了，昨天debug了一下代码
是Select1Provider<T1> 类的includeToListSyncOrAsync方法使用了Transaction
通过DbConnection.select无法得到Transaction导致报错，传入Transaction可以解决问题
用Transaction.select
