### ISSUE TITLE
.net 5 控制台，会打印一连串警告

### ISSUE THREAD

**Issue by christan-duplicate** [dotnetcore/FreeSql#553]
Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.
Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.
Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.
Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.
Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later.

**Comment by 2881099** [comment]
什么数据库

**Comment by christan-duplicate** [comment]
sql server 2008 r2

**Comment by christan-duplicate** [comment]
`
class Program
    {
        private static readonly IFreeSql Fsql = new FreeSql.FreeSqlBuilder()
            .UseConnectionString(FreeSql.DataType.SqlServer, @"Data Source=127.0.0.1;Initial Catalog=test;user=sa;password=123456;")
            .UseAutoSyncStructure(false) //自动同步实体结构到数据库
            .UseGenerateCommandParameterWithLambda(true)
            .UseMonitorCommand(cmd => System.Console.WriteLine(cmd.CommandText))
            .Build(); //请务必定义成 Singleton 单例模式

        static void Main(string[] args)
        {
            var id = 32;
            var item = Fsql.Select<PrdProduct>().Where(p => p.ProdId == id).First();
            System.Console.WriteLine(JsonConvert.SerializeObject(item));
            System.Console.WriteLine("111");
        }
    }

    [Table(Name = "Prd_Product")]
    class PrdProduct
    {
        [Column(IsPrimary = true, IsIdentity = true)]
        public int ProdId { get; set; }


        public int BrandId { get; set; }


        public int TypeId { get; set; }

        public int Pid { get; set; }
    }
`

**Comment by 2881099** [comment]
试试用 FreeSql.Provider.SqlServerFoSystem.dll

移除 FreeSql.Provider.SqlServer.dll

他们两个引用的 adonet 驱动不同，另外注意很大的坑 sqlserver 2008，如果你的程序是 net5 部署到 linux 是不能访问的，adonet 的坑。

**Comment by christan-duplicate** [comment]
> 试试用 FreeSql.Provider.SqlServerFoSystem.dll
> 
> 移除 FreeSql.Provider.SqlServer.dll
> 
> 他们两个引用的 adonet 驱动不同，另外注意很大的坑 sqlserver 2008，如果你的程序是 net5 部署到 linux 是不能访问的，adonet 的坑。

winserver正常吗？

**Comment by christan-duplicate** [comment]
是：
FreeSql.Provider.SqlServerForSystem
吧

**Comment by 2881099** [comment]
winserver 可以

**Comment by christan-duplicate** [comment]
> winserver 可以

好的，多谢，换成 FreeSql.Provider.SqlServerForSystem 果然不打印警告了！

**Comment by MJTucDi** [comment]
我用的 sqlserver 2014 也报这个错误（引用的FreeSql.Provider.SqlServer）。
FreeSql.Provider.SqlServerForSystem  能部署到linux 上么？

**Comment by 2881099** [comment]
可以，二选一

**Comment by 2881099** [comment]
> 我用的.net5+ sqlserver 2014 也报这个错误（引用的FreeSql.Provider.SqlServer）。
> FreeSql.Provider.SqlServerForSystem 能部署到linux 上么？

可以，二选一

**Comment by MJTucDi** [comment]
> 
> 
> > 我用的.net5+ sqlserver 2014 也报这个错误（引用的FreeSql.Provider.SqlServer）。
> > FreeSql.Provider.SqlServerForSystem 能部署到linux 上么？
> 
> 可以，二选一

 谢谢叶老板[抱拳]
