### ISSUE TITLE
使用ExecuteConnectTest方法遇到的问题

### ISSUE THREAD

**Issue by abc35277** [dotnetcore/FreeSql#554]
文件：FreeSql.dll
接口：FreeSql
方法：**ExecuteConnectTest**
正确的数据库字符串：Data Source=.\xxx.db;Version=3;Pooling=True;Max Pool Size=100;
错误的数据库连接串：Data Source=.\xxx1.db;Version=3;Pooling=True;Max Pool Size=100;

以下是我调用的过程，OrmFactory是我自己写的单例工厂类
`public class CommonDAL
    {
        public static bool TestConnection()
        {
            return OrmFactory.Instance.Ado.ExecuteConnectTest();
        }
    }`

- 在我调用这个ExecuteConnectTest方法的时候我的本意是检测数据库连接字符串是否正确，但是结果就是当我使用上面的错误连接字符串的时候自动生成了一个新的（不正确的）数据库文件即xxx1.db。我希望的结果是返回false。

-另外需要一个切换数据库或者重新加载新的数据库连接的功能。

**Comment by luoyunchong** [comment]
http://freesql.net/sharding.html#%E5%88%86%E5%BA%93-idlebus
@abc35277

**Comment by abc35277** [comment]
回楼上 @luoyunchong 
可能我没太说清楚，我要的不是**分库分表**也不是**读写分离**。我只是想要**测试数据库连接**而已。**IdleBus**这个我没有用过。我的使用方式如下：
```
 private static IFreeSql CreateInstance()
        {
            var providerName = ConfigHelper.GetProviderName();
            var dataType = DataType.Sqlite;
            var providerType = typeof(FreeSql.Sqlite.SqliteProvider<>);
            if (providerName.Equals("FreeSql.Provider.MySql"))
            {
                providerType = typeof(FreeSql.MySql.MySqlProvider<>);
                dataType = DataType.MySql;
            }
            var re = new FreeSqlBuilder().UseConnectionString(dataType, ConnectionString, providerType)
            .UseMonitorCommand(cmd =>
            {
            }, (cmd, valueStr) =>
            {
            }).UseAutoSyncStructure(false).Build();
            return re;
        }
```
我的需求只有一个，就是通过某种手段**确认数据库连接是否正常**就像某些数据库工具都有的那个**测试连接**一样。我的预期或者我认为此方法的执行结果应该是如果sqlite文件不存在即连接错误此方法直接返回false或者抛出异常。

**Comment by luoyunchong** [comment]
sqlite在new FreeSqlBuilder().Build()的时候就会创建数据库。

**Comment by abc35277** [comment]
@luoyunchong 好的了解了，谢谢。
