### ISSUE TITLE
Xamarin android下AOT编译失败

### ISSUE THREAD

**Issue by ismlsmile** [dotnetcore/FreeSql#557]
用的是mysqlconnector，非AOT模式下正常，请问是否支持在android下的AOT？

**Comment by 2881099** [comment]
不支持 aot 编译

**Comment by ismlsmile** [comment]
现在能支持Xamarin.iOS吧？android下的AOT为啥不支持呢？

**Comment by 2881099** [comment]
AOT编译都不支持，因为有用到一些动态表达式计算

**Comment by ismlsmile** [comment]
https://github.com/dotnetcore/FreeSql/issues/126

我看有issue是说ios的。那现在能支持Xamain.ios吗？

**Comment by 2881099** [comment]
不用 aot 编译的话，可以使用

**Comment by ismlsmile** [comment]
Xamarin.iOS不是必须AOT吗？还可以非AOT？

**Comment by 2881099** [comment]
@densen2014 

不清楚，问下这位哥

> Xamarin.iOS不是必须AOT吗？还可以非AOT？

**Comment by densen2014** [comment]
你的编译界面截图来看看, 应该要link进去

**Comment by ismlsmile** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task FreeSqlMySqlConnectorGlobalExtensions/<>c__DisplayClass1_0`1::<ExecuteMySqlBulkCopyAsync>b__0(MySqlConnector.MySqlBulkCopy)' in assembly: 'FreeSql.Provider.MySqlConnector.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task MySqlConnector.MySqlBulkCopy::WriteToServerAsync(System.Data.DataTable,System.Threading.CancellationToken)
   在 Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   在 Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   在 Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   在 Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   在 Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   在 Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Mono.Linker.Steps.MarkStep.ProcessQueue()
   在 Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   在 Mono.Linker.Steps.MarkStep.Process()
   在 Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   在 MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   在 Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   在 Mono.Linker.Pipeline.Process(LinkContext context)
   在 MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   在 Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   在 Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   在 Xamarin.Android.Tasks.AndroidTask.Execute()	App1.Android

**Comment by 2881099** [comment]
可以结合源码编译试试，提示的这个错误是 Nested Method，不知道有没有影响

**Comment by ismlsmile** [comment]
把freesql的源码集成到工程里？

**Comment by 2881099** [comment]
> 把freesql的源码集成到工程里？

是的

**Comment by ismlsmile** [comment]
同样的错

**Comment by densen2014** [comment]
你到底是用在xf还是xamarin android？还是xamarin ios？

**Comment by ismlsmile** [comment]
Xamarin Forms，运行在Android环境下

**Comment by densen2014** [comment]
编译设置界面截图看看，首先，debug能不能运行？

**Comment by ismlsmile** [comment]
debug可以运行。release选项见下图

![image](https://user-images.githubusercontent.com/1876179/100328849-f055ef00-3007-11eb-94e3-6f59af4ef15f.png)

**Comment by densen2014** [comment]
你在叶老板哪个群？

**Comment by ismlsmile** [comment]
没进任何群，freesql我也第一次用。我在找一个xamarin下可用的orm框架，之前用的是dapper。freesql非aot模式下确实可用，但aot目前测试不行。我测试的时候是新建了一个demo工程，没有特殊的东西，用的是mysqlconnector，直接select了一张表，你们本地可以建个demo工程测试一下

**Comment by densen2014** [comment]
FreeSql使用xamarin form建立工程相关经验分享
https://github.com/dotnetcore/FreeSql/issues/569

**Comment by densen2014** [comment]
> 没进任何群，freesql我也第一次用。我在找一个xamarin下可用的orm框架，之前用的是dapper。freesql非aot模式下确实可用，但aot目前测试不行。我测试的时候是新建了一个demo工程，没有特殊的东西，用的是mysqlconnector，直接select了一张表，你们本地可以建个demo工程测试一下

FreeSql使用xamarin form建立工程相关经验分享
https://github.com/dotnetcore/FreeSql/issues/569

**Comment by densen2014** [comment]
> 没进任何群，freesql我也第一次用。我在找一个xamarin下可用的orm框架，之前用的是dapper。freesql非aot模式下确实可用，但aot目前测试不行。我测试的时候是新建了一个demo工程，没有特殊的东西，用的是mysqlconnector，直接select了一张表，你们本地可以建个demo工程测试一下

我用的是mssql和sqlite, 已经上架好久了.
![ios版](https://user-images.githubusercontent.com/8428709/100335962-de5b5880-2fd5-11eb-97a8-c818512bc6b0.png)
![安卓版](https://user-images.githubusercontent.com/8428709/100335967-def3ef00-2fd5-11eb-8ea4-25b64c6a53bd.png)

**Comment by ismlsmile** [comment]
那就是和mysqlconnector有关了，但直接用mysqlconnector的话AOT没问题，我现在就是用手写的模式。用了Freesql +mysqlconnector在AOT模式下就会有问题

**Comment by densen2014** [comment]
也许是mysqlconnector里面那个加密dll问题,你用另一个版本mysqlconnector试试看,我记得那个castelo啥的不能通过编译

**Comment by ismlsmile** [comment]
使用Mysql.Data，数据库都没连上，报System.PlatformNotSupportedException: Operation is not supported on this platform.

**Comment by densen2014** [comment]
xamarinFormApp例子,安卓,iOS,WPF
https://github.com/dotnetcore/FreeSql/tree/master/Examples/xamarinFormApp

--------
```

                #region mssql测试没问题

                //        fsql = new FreeSql.FreeSqlBuilder()
                //.UseConnectionString(FreeSql.DataType.SqlServer, "Data Source=192.168.1.100;Initial Catalog=demo;Persist Security Info=True;MultipleActiveResultSets=true;User ID=sa;Password=a123456;Connect Timeout=30;min pool size=1;connection lifetime=15")
                //.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
                //.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
                //.Build();

                #endregion

                #region Sqlite需要反射,明天有时间再补充代码

                //                fsql = new FreeSql.FreeSqlBuilder()
                //.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=document.db; Pooling=true;Min Pool Size=1")
                //.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
                //.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
                //.Build();

                #endregion

                #region mysql使用 reeSql.Provider.MySqlConnector , debug和release都设置为不链接即可

                fsql = new FreeSql.FreeSqlBuilder()
.UseConnectionString(FreeSql.DataType.MySql, "Data Source=192.168.1.100;Port=3306;User ID=root;Password=a123456; Initial Catalog=test;Charset=utf8; SslMode=none;Min pool size=1")
.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
.Build();
                #endregion

                fsql.CodeFirst.SyncStructure<Item>();
                if (fsql.Select<Item>().Count()<10) fsql.Insert<Item>().AppendData(items).ExecuteAffrows();
                var res = fsql.Select<Item>().ToList(a=>a.Text);
                res.ForEach(a => {
                    Debug.WriteLine(" <== 测试测试测试 ==> " + a);
                });
```

**Comment by ismlsmile** [comment]
" debug和release都设置为不链接即可"
请问这个在哪里配置？

**Comment by densen2014** [comment]
你下载例子先试试.
在项目生成里面[链接]选项

**Comment by ismlsmile** [comment]
试了下这个工程（https://github.com/dotnetcore/FreeSql/tree/master/Examples/xamarinFormApp），设置了不链接确实能编译通过，改成链接SDK就编译通不过，说明这个选项确实是有关系的。但有个问题，这个工程并没有启用AOT，我设置了启用AOT后，存档成apk会报失败，提示XA3001: 无法 AOT 程序集: Mono.Android.dll

**Comment by densen2014** [comment]
怎么开启aot？我找了好久没找到，是不是要企业版才行

**Comment by ismlsmile** [comment]
需要企业版

![image](https://user-images.githubusercontent.com/1876179/100535253-356d6180-3252-11eb-9803-88cdb4ec8d7b.png)
