### ISSUE TITLE
Mysql 链接失败？Navicat可以链接

### ISSUE THREAD

**Issue by kingreatwill** [dotnetcore/FreeSql#561]
【主库】状态不可用，等待后台检查程序恢复方可使用。Authentication to host 'xxx' for user 'root' using method 'mysql_native_password' failed with message: Access denied for user 'root'@'xx' (using password: YES)

**Comment by kingreatwill** [comment]
'''
public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
            Fsql = new FreeSql.FreeSqlBuilder()
                .UseConnectionString(FreeSql.DataType.MySql, @"Data Source=49.235.74.85;Port=3306;User ID=root;Password=132456;Initial Catalog=yiyandb;Charset=utf8;Max pool size=100;")
                .UseAutoSyncStructure(true)
                //.UseMonitorCommand(cmd => Trace.WriteLine(cmd.CommandText))
                .UseNoneCommandParameter(true)
                .Build();
            //Fsql.Aop.TraceBefore += (_, e) => Trace.WriteLine($"----TraceBefore---{e.Identifier} {e.Operation}");
            //Fsql.Aop.TraceAfter += (_, e) => Trace.WriteLine($"----TraceAfter---{e.Identifier} {e.Operation} {e.Remark} {e.Exception?.Message} {e.ElapsedMilliseconds}ms\r\n");
            //BaseEntity.Initialization(Fsql, () => _asyncUow.Value);
        }

        public IConfiguration Configuration { get; }
        public static IFreeSql Fsql { get; private set; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.Configure<SidebarMenu>(Configuration.GetSection("sidebarMenu"));
            services.AddControllersWithViews();
            services.AddSingleton<IFreeSql>(Fsql);
        }

'''

**Comment by kingreatwill** [comment]
```
public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFreeSql _fsql;

        public HomeController(ILogger<HomeController> logger, IFreeSql fsql)
        {
            _logger = logger;
            _fsql = fsql;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoadData(DataTablesParameters parameters)
        {
            var list = _fsql.Select<Employ>().ToList();
           // _fsql.Select<Employ>().WithSql("");
            return Json(new DataTablesResult<Employ>(parameters.Draw, 10, 10, list));
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
```

**Comment by 2881099** [comment]
Authentication to host 'xxx' for user 'root' using method 'mysql_native_password' failed with message: Access denied for user 'root'@'xx' (using password: YES)

按这个信息搜索答案

**Comment by luoyunchong** [comment]
@kingreatwill 手动创建数据库。FreeSql。 MySql不会创建数据库。

**Comment by kingreatwill** [comment]
谢谢了，搞了半天，密码错了。
