### ISSUE TITLE
优化查询对Enum的支持

### ISSUE THREAD

**Issue by ddabb** [dotnetcore/FreeSql#566]
var result = Orm.Select<process>().Where(c=>c.attributes.HasFlag(ProcessAttribute.Published)&& c.attributes.HasFlag(ProcessAttribute.PublishedWS)).ToList();
该语句执行报错，报错内容为 **未实现函数表达式 c.attributes.HasFlag(Convert(Published, Enum)) 解析**
![image](https://user-images.githubusercontent.com/15926828/100297907-b6b2c300-2fca-11eb-92b9-9484854d0966.png)
希望扩展 where条件对enum的位运算。并在DynamicFilterOperator 追加 EnumHasFlag 方法

**Comment by 2881099** [comment]
大佬可以把自定义解析代码贴上来

**Comment by ColinZeb** [comment]
hasflag可用用&代替

**Comment by ddabb** [comment]
不是大佬，但是自定义解析代码来了
        
        /// <summary>
        /// context 必须静态
        /// </summary>
        static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

        /// <summary>
        /// 等价于Enum.HasFlag方法,用于freesql 解析的扩展方法，坐等某天freesql招安。
        /// </summary>
        /// <param name="that"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public static bool EnumHasFlag(this Enum that, [RawValue] Enum value)
        {
            var up = context.Value;

            var thatLong = Convert.ToInt64(that);
            var valueLong = Convert.ToInt64(value);
            up.Result = $"{ up.ParsedContent["that"]} & {valueLong} = {valueLong}";
            return (thatLong & valueLong) == valueLong; //该返回值不影响 sql解析
        }
