### ISSUE TITLE
优化-结构调整

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/FreeSql#567]
## 背景
我在开发时发现没有`OrderByIf``  `IncludeIf` 方法(后面发现有if版本)，然后就自己用扩展方法的方式扩展了出来。

## 优化目标
今天在查看接口定义时，发现原接口有这种定义。 然后就想简化下基础接口。大体思路如下：
1. 参考微软的分布式缓存接口设计，接口只提供必要的方法,同一套方法只保留一个，其它功能以接口扩展方法方式提供
2. 原接口方法暂时不删，打上过时标记并移动到有`old`后缀的文件夹中。 原接口修改为`partial`的方式。

## 为什么要这样设计呢？
微软的分布式缓存接口设计：接口只提供最最最基础的方法，其它全是扩展方法提供。

这样的好处是其它的接口实现只需要实现最核心的逻辑即可，然后扩展起来非常容易。缺点是需要接口定义时设计的非常抽象。
否则的话当需要新功能是就需要在接口上面增加，然后实现也要增加对应版本，我们都知道代码越多越难管理

## 优化过程
1. 分析出多余的方法
2.  剥离到专门的扩展方法类中.计划放在`FreeSql`库的`Extensions`文件夹中

如果讨论同意，后面我会把代码PR过来。现在已经在修改中

**Comment by 2881099** [comment]
非常用心写了这么多。

OrderByIf/IncludeIf 是后面加进来，IncludeIf 貌似支持集合属性。

目前2.0已经发布，Api 方面的调整暂时不合适提交，但是这个建议可以留给后面新需求的时候遵从。

当下如果影响到你的本地代码，对比下功能看有什么差异，回帖讨论解决你的问题

**Comment by hjkl950217** [comment]
功能上影响不大，我当时以为没有就自己在项目中封装了一个，如下:
```
        public static ISelect<T1> BaseFunction_If<T1, TMember1, TMember2>(
            Func<Expression<Func<T1, TMember1>>, ISelect<T1>> func,
            Func<Expression<Func<T1, TMember2>>, ISelect<T1>> func1,
            Expression<Func<T1, TMember1>> expByTrue,
            Expression<Func<T1, TMember2>> expByFalse,
            bool condition)
            where T1 : class
        {
            return condition ? func(expByTrue) : func1(expByFalse);
        }

        public static ISelect<T1> OrderByDescendingIf<T1, TMember1, TMember2>(
            this ISelect<T1> select,
            bool condition,
            Expression<Func<T1, TMember1>> expByTrue,
            Expression<Func<T1, TMember2>> expByFalse)
            where T1 : class
        {
            return ISelectExtension.BaseFunction_If(select.OrderByDescending, select.OrderByDescending, expByTrue, expByFalse, condition);
        }
```

这种思路就是接口和实现只需要有`OrderByDescending`就可以了。后续为了方便使用的API则用扩展方法的方式编码

**Comment by hjkl950217** [comment]
OrderByIf 没有找到哇。 可能在库里有，智能感知没有感知出来，影响不大，这种真没有自己封一个也没什么。

**Comment by hjkl950217** [comment]
我想的是把接口上面的方便使用API剥离出来， 也不会影响代码使用。

**Comment by 2881099** [comment]
OrderBy 重载方法，当时觉得命名不好看就用重载做的

**Comment by hjkl950217** [comment]
哦哦  这种有看到，包括where也有。 我就是想把这种放在扩展方法上而不是接口上面，这样更灵活一点。 扩展方法想加多少加多少，完全不会影响主接口相关的逻辑
