### ISSUE TITLE
Xamarin 下使用的问题

### ISSUE THREAD

**Issue by gwhzh21** [dotnetcore/FreeSql#568]
freesql2
看了前面的demo.引入了freesql2。

            string MicrosoftdbPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Microsoft.Data.Sqlite.db");
freeSql = new FreeSql.FreeSqlBuilder()
.UseConnectionString(FreeSql.DataType.Sqlite, MicrosoftdbPath)
.UseAutoSyncStructure(true)
                .UseLazyLoading(true)
                .Build();
生成之后，无法使用。连不上数据库。

 然后看了前面的demo.试着在三个项目中引入mono.data.sqlite，都引入不了。

**Comment by densen2014** [comment]
FreeSql使用xamarin form建立工程相关经验分享
https://github.com/dotnetcore/FreeSql/issues/569

**Comment by densen2014** [comment]
### 参考
---------
使用sqlite
https://github.com/dotnetcore/FreeSql/issues/183
Xamarin IOS 错误：Encoding 936 data could not be found
https://github.com/dotnetcore/FreeSql/issues/126
Xamarin 下使用问题汇总
https://github.com/dotnetcore/FreeSql/issues/124

**Comment by gwhzh21** [comment]
试了下。
1>Mono.Data.Sqlite. 引入不了，提示，.net framework4.6.2
2>把栗子改成了sqlite,
#region Sqlite需要反射,明天有时间再补充代码
                string MicrosoftdbPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Microsoft.Data.Sqlite.db");

                fsql = new FreeSql.FreeSqlBuilder()
.UseConnectionString(FreeSql.DataType.Sqlite, $"Data Source={MicrosoftdbPath};",
typeof(FreeSql.Sqlite.SqliteProvider<>))
.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
.Build();

                #endregion
但是一直在输出 

11-27 05:04:28.937 W/Mono    (24610): DllImport unable to load library 'SQLite.Interop.dll'.
 select 1 from main.sqlite_master where type='table' and name='Item'【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:33 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))
11-27 05:04:28.939 I/mono-stdout(24610):  select 1 from main.sqlite_master where type='table' and name='Item'【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:33 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))
Thread started: <Thread Pool> #7
Thread started: <Thread Pool> #8
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
[HotReload] (2020-11-27 05:04:26.0): INFO: (xamarinFormApp.Android) (HotReloadAgent) HotReload: Initialized Agent.
[HotReload] (2020-11-27 13:04:29.9): INFO: XAML 热重载已连接且准备就绪。
【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:38 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))
11-27 05:04:33.942 I/mono-stdout(24610): 【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:38 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))
【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:43 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))
11-27 05:04:38.945 I/mono-stdout(24610): 【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:43 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))
【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:48 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))11-27 05:04:43.947 I/mono-stdout(24610): 【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:48 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))

【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:53 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))11-27 05:04:48.949 I/mono-stdout(24610): 【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:53 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))

【主库】仍然不可用，下一次恢复检查时间：11/27/2020 5:04:58 AM，错误：(SQLite.Interop.dll assembly:<unknown assembly> type:<unknown type> member:(null))

**Comment by gwhzh21** [comment]
例子是昨天
xamarinFormApp例子,安卓,iOS,WPF
https://github.com/dotnetcore/FreeSql/tree/master/Examples/xamarinFormApp

**Comment by gwhzh21** [comment]
暂时先用 sqlite-net-pcl 可惜不能统一代码。

**Comment by 2881099** [comment]
.UseConnectionString(FreeSql.DataType.Sqlite, () => new Mono.Data.SqliteConnection($"Data Source={MicrosoftdbPath};"),
typeof(FreeSql.Sqlite.SqliteProvider<>))

如果没记错，要这样定义 IFreeSql

**Comment by gwhzh21** [comment]
Mono.Data. 这个我引用不了。在单独的android里面可以，但是在Xamarin.Forms 项目里面。就提示。引入了.net framework4.6.2没有引入对应的NETStandard.Library2.0.3还是啥的冲突。然后就放弃了。

**Comment by densen2014** [comment]
查看

https://github.com/dotnetcore/FreeSql/issues/183

**Comment by gwhzh21** [comment]
但是我在是Xamarin.Forms 项目里面用的。

**Comment by gwhzh21** [comment]
大约懂了。获取连接要放到各种平台的项目下面。

**Comment by densen2014** [comment]
对的,不同平台内置的sqlite驱动不一致,所以要反射出来用
