### ISSUE TITLE
FreeSql使用xamarin form建立工程相关经验分享

### ISSUE THREAD

**Issue by densen2014** [dotnetcore/FreeSql#569]
### 参考
---------
使用sqlite
https://github.com/dotnetcore/FreeSql/issues/183
Xamarin IOS 错误：Encoding 936 data could not be found
https://github.com/dotnetcore/FreeSql/issues/126
Xamarin 下使用问题汇总
https://github.com/dotnetcore/FreeSql/issues/124
xamarinFormApp例子,安卓,iOS,WPF
https://github.com/dotnetcore/FreeSql/tree/master/Examples/xamarinFormApp

--------
```

                #region mssql测试没问题

                //        fsql = new FreeSql.FreeSqlBuilder()
                //.UseConnectionString(FreeSql.DataType.SqlServer, "Data Source=192.168.1.100;Initial Catalog=demo;Persist Security Info=True;MultipleActiveResultSets=true;User ID=sa;Password=a123456;Connect Timeout=30;min pool size=1;connection lifetime=15")
                //.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
                //.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
                //.Build();

                #endregion

                #region Sqlite需要反射,明天有时间再补充代码

                //                fsql = new FreeSql.FreeSqlBuilder()
                //.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=document.db; Pooling=true;Min Pool Size=1")
                //.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
                //.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
                //.Build();

                #endregion

                #region mysql使用 reeSql.Provider.MySqlConnector , debug和release都设置为不链接即可

                fsql = new FreeSql.FreeSqlBuilder()
.UseConnectionString(FreeSql.DataType.MySql, "Data Source=192.168.1.100;Port=3306;User ID=root;Password=a123456; Initial Catalog=test;Charset=utf8; SslMode=none;Min pool size=1")
.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
.UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
.Build();
                #endregion

                fsql.CodeFirst.SyncStructure<Item>();
                if (fsql.Select<Item>().Count()<10) fsql.Insert<Item>().AppendData(items).ExecuteAffrows();
                var res = fsql.Select<Item>().ToList(a=>a.Text);
                res.ForEach(a => {
                    Debug.WriteLine(" <== 测试测试测试 ==> " + a);
                });
```

**Comment by densen2014** [comment]
### Android篇
--------
**安卓编译**
![安卓编译](https://user-images.githubusercontent.com/8428709/100334985-bd463800-2fd4-11eb-90f9-38ef9e8089fe.png)
![安卓编译2](https://user-images.githubusercontent.com/8428709/100334988-bddece80-2fd4-11eb-9132-e2626d1f354a.png)
**安卓调试**
![安卓调试](https://user-images.githubusercontent.com/8428709/100334989-be776500-2fd4-11eb-9cb4-dcf43764278c.png)
![安卓调试2](https://user-images.githubusercontent.com/8428709/100334993-be776500-2fd4-11eb-8315-8698d341c88f.png)
**安卓引用程序集**
![安卓引用程序集](https://user-images.githubusercontent.com/8428709/100334994-be776500-2fd4-11eb-9e8b-4daa0c0e51ec.png)

**Comment by densen2014** [comment]
### ios篇
---------
**ios编译**
![ios编译](https://user-images.githubusercontent.com/8428709/100334816-8e2fc680-2fd4-11eb-98f4-517ddcfbee61.png)
![ios编译2](https://user-images.githubusercontent.com/8428709/100334818-8ec85d00-2fd4-11eb-8342-a9ea770b1001.png)
**ios调试**
![ios调试](https://user-images.githubusercontent.com/8428709/100334820-8ec85d00-2fd4-11eb-86f1-f8c1ed513ce2.png)
![ios调试2](https://user-images.githubusercontent.com/8428709/100334822-8ec85d00-2fd4-11eb-975f-02084f306ad0.png)
**ios引用程序集**
![ios引用程序集](https://user-images.githubusercontent.com/8428709/100334824-8f60f380-2fd4-11eb-81c2-e8d1338365f5.png)

**Comment by zhangboyanzhangboyan** [comment]
mssql
使用安卓设备管理器下的模拟系统，sqlserver本地数据库连不上
【主库】状态不可用，等待后台检查程序恢复方可使用。A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

**Comment by 2881099** [comment]
分别用 FreeSql.Provider.SqlServer.dll 和 FreeSql.Provider.SqlServerForSystem.dll 试试

**Comment by densen2014** [comment]
> mssql
> 使用安卓设备管理器下的模拟系统，sqlserver本地数据库连不上
> 【主库】状态不可用，等待后台检查程序恢复方可使用。A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

先跑一下demo
https://github.com/dotnetcore/FreeSql/issues/124
