### ISSUE TITLE
在oracle中,db优先时

### ISSUE THREAD

**Issue by jetydu** [dotnetcore/FreeSql#57]
![image](https://user-images.githubusercontent.com/25604796/58688385-d9a0ee80-83b6-11e9-9131-b3a02deb7b3b.png)
在oracle中,出现当数据类型DbTypeTextFull=DATE(7)出现异常
未实现DATE(7) 类型映射
oracledbfirst.cs  86行.

**Comment by 2881099** [comment]
好的，收到

**Comment by jetydu** [comment]
GetCs 还有这些函数的大小写问题

**Comment by 2881099** [comment]
这个不好改了，扯着蛋连在一体的地方多

> GetCs 还有这些函数的大小写问题
