### ISSUE TITLE
fsql.Ado.Query能否支持参数化查询

### ISSUE THREAD

**Issue by anhuizf1** [dotnetcore/FreeSql#571]
为防止SQL注入，能否在fsql.Ado.Query中增加参数化支持，比如 AddParameter("@P1", value1)

**Comment by 2881099** [comment]
fsql.Ado.Query(sql, new { 参数名 =111 })

或者

fsql.Ado.CommandFluent(sql).方法，F12 看一看就懂了

**Comment by anhuizf1** [comment]
好多，明白了，谢谢。

**Comment by anhuizf1** [comment]
var res = fsql.Ado.Query<ClientEntity>("select * from IRAP..stb_Channels where ClientID= ?P1",
                new { P1 = clientId }  ). First();

总是报语法错误：
System.Exception: “?”附近有语法错误。
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): “?”附近有语法错误。

**Comment by anhuizf1** [comment]
是提示误导了我，根据提示变量是？ ，其实是@才行（对sqlserver）  
var res = fsql.Ado.Query<ClientEntity>("select * from IRAP..stb_Channels where ClientID=@P1",
                new { P1=clientId}  ).First();

**Comment by 2881099** [comment]
最开始文档是按 mysql.data 习惯做的，所以是 ?

关于 Ado 这块大概有四个习惯：

- odbc 是 ? 并且没有标识，所以freesql禁用了 odbc 参数化
- oracle 是 :
- mysql.data 是 ?
- mysqlconnector 是 @
- 其他基本都是 @

Ado 不是 FreeSql 重点功能，所以参数化前辍需要使用者自己确定后，再使用，? @ : 都是对的，看使用的数据库。

**Comment by anhuizf1** [comment]
好！ 解释的非常专业 ！freesql很棒。加油。
