### ISSUE TITLE
如果SysRole类的属性为RoleName，但是对应数据库的字段名为“ROLE_NAME”，使用InsertInto时会报错

### ISSUE THREAD

**Issue by yinhaichao** [dotnetcore/FreeSql#576]
如果SysRole类的属性为RoleName，但是对应数据库的字段名为“ROLE_NAME”，使用InsertInto时会报错

	public partial class SysRole {

		/// <summary>
		/// GUID
		/// </summary>
		[JsonProperty, Column(Name = "GUID", DbType = "VARCHAR2(60 BYTE)", IsPrimary = true)]
		public string Guid { get; set; }
		
		/// <summary>
		/// 角色名称
		/// </summary>
		[JsonProperty, Column(Name = "ROLE_NAME", DbType = "NVARCHAR2(40)")]
		public string RoleName { get; set; }

		/// <summary>
		/// 角色排序
		/// </summary>
		[JsonProperty, Column(Name = "SORT")]
		public int Sort { get; set; }
	}

-------------------------------------

Db.Select<SysRole>().Where(a => a.Guid == "xxxx").InsertInto("", a => new SysRole
                    {
                        Guid = "x123123dasfafd",
                        RoleName = $"{a.RoleName}-复制",
                        Sort = a.Sort
                    });

而且如果我把RoleName = $"{a.RoleName}-复制",改成“Guid.NewGuid().ToNormalWithinCodeGuid(a.WithinCode)”，会报错
“未实现函数表达式 NewGuid().ToNormalWithinCodeGuid(a.WithinCode) 解析”，当然ToNormalWithinCodeGuid是自定义的一个扩展方法

public static string ToNormalWithinCodeGuid(this Guid guid,string withinCode)
        {
            return $"{withinCode}{guid.ToString("N")}";
        }

**Comment by 2881099** [comment]
问题不是 InsertInto，而是表达式不能解析？

**Comment by 2881099** [comment]
1、如果是报错异常：The given key 'xxx' was not present in the dictionary.

升级到 v2.3.0-preview1129 (myget.org)

> 安装前添加源：https://www.myget.org/F/ncc/api/v3/index.json

---

2、如果是自定义解析问题，代码如下（详细见提交记录的代码）：

```c#
[ExpressionCall]
public static class _576Extensions
{
	public static ThreadLocal<ExpressionCallContext> expContext = new ThreadLocal<ExpressionCallContext>();

	public static string ToNormalWithinCodeGuid([RawValue] this Guid that, string withinCode)
	{
		expContext.Value.Result = $"{expContext.Value.ParsedContent["withinCode"]} || '{that.ToString("N")}'";
		return null;
	}
}
```

**Comment by 2881099** [comment]
Guid = "x123123dasfafd"

另外，这里用常用会导致 SQL 错误，具体监视一下 SQL 就明白我说的错误了。解决办法：

Guid = "'x123123dasfafd'"

> 注意单引号

机制在文档（[返回查询数据](https://github.com/dotnetcore/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%95%b0%e6%8d%ae)）：

```c#
//返回SQL字段
List<匿名类> t9 = fsql.Select<Topic>().ToList(a => new {
    cstitle = "substr(a.title, 0, 2)", //将 substr(a.title, 0, 2) 作为查询字段
    csnow = Convert.ToDateTime("now()"), //将 now() 作为查询字段
    //奇思妙想：怎么查询开窗函数的结果
});
```
