### ISSUE TITLE
oracle数据库，通过命令生成的实体不正确

### ISSUE THREAD

**Issue by LevyTerritory** [dotnetcore/FreeSql#577]
oracle的NUMBER(4)对应的c#类型应该是short，而现在生成的是sbyte

**Comment by 2881099** [comment]
short 最大值是 32767，你可以试试到 oracle 执行以下命令：

```sql
SELECT CAST(32767 AS number(4)) FROM dual
```

报错：SQL 错误 [1438] [22003]: ORA-01438: 值大于为此列指定的允许精度

**Comment by 2881099** [comment]
所以映射成 sbyte 是最保险的，或者改大 number(4) -> number(6) 就会映射成 short 了。

如果一定要 number(4) 生成 short，可以做几下几个步骤：

1、下载源码修改：FreeSql.Provider.Oracle/OracleDbFirst.cs 125行

2、增加 FreeSql.Generator.csproj 版本号，编译它

3、进入 FreeSql.Generator\bin\Debug 目录，执行 cmd 命令更新生成器：

> dotnet tool update -g FreeSql.Generator --add-source ./

**Comment by LevyTerritory** [comment]
首先，谢谢回答！
我觉得在DBFirst模式下应该以DB为准吧，oracle的number(4) 最大值是9999，映射成short才是保险的

**Comment by LevyTerritory** [comment]
首先，谢谢回答！
我觉得在DBFirst模式下应该以DB为准吧，oracle的number(4) 最大值是9999，映射成short才是保险的

**Comment by 2881099** [comment]
> 首先，谢谢回答！
> 我觉得在DBFirst模式下应该以DB为准吧，oracle的number(4) 最大值是9999，映射成short才是保险的

这个是按 codefirst 思路做的，因为 orm 操作主要以 c# 实体类为主，当 c# short 32767 无法存储至 oracle number(4)
