### ISSUE TITLE
查询表达式中不识别new Guid

### ISSUE THREAD

**Issue by tiansfather** [dotnetcore/FreeSql#578]
freesql版本:2.0
使用以下方式产生的sql语句有问题
 DbPool.GetGuidRepository<A>().Where(o => o.Id == new Guid("5fc2d9e2-b642-c0b8-0085-9aa63da6af48"));
最后产生的查询语句为"id=" ，直接语法错误了

**Comment by 2881099** [comment]
Guid.Parse
