### ISSUE TITLE
FreeSql.Generator 好像依赖于.net core 3.1 , 机器只有5.0的时候无法运行

### ISSUE THREAD

**Issue by fishjimi** [dotnetcore/FreeSql#582]
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64

**Comment by 2881099** [comment]
可以自己编译一个本地安装，dotnet tool 包太大，多适配一个目标框架多20兆。

进入 bin/Debug 目录执行 cmd 本地安装

dotnet tool install -g freesql.generator —add-source ./

**Comment by fishjimi** [comment]
大佬真迅速！
