### ISSUE TITLE
MySql  CodeFirst 外键咨询

### ISSUE THREAD

**Issue by xuanyuan5005** [dotnetcore/FreeSql#584]
您好：

我在使用 CodeFirst 配置外键关系无效，于是阅读源码。
但是从FreeSql.Provider.MySql/MySqlCodeFirst.cs这里代码，没够看到外键生成的逻辑？是忽略，还是有其他途径？

如果采用MySQL数据库，CodeFirst模式的话，外键关系如何配置？

**Comment by 2881099** [comment]
不支持外键生成。

**Comment by lhtuling** [comment]
哦 我也发现这个问题了!   不支持外键的话代码就要写的更严谨点了~~   我等菜鸟平常都靠数据库的外键限制少写不少代码来着

**Comment by longletian** [comment]
配置导航属性会自动生成一个外键吗？

**Comment by 2881099** [comment]
> 配置导航属性会自动生成一个外键吗？

不生成物理外键
