### ISSUE TITLE
AsTreeCte()会把软删除的数据也查出来

### ISSUE THREAD

**Issue by tonfy** [dotnetcore/FreeSql#589]
递归的方法会把软删除的数据也查出来了，软删除和多租户，我是由全局过滤的，但这个过滤在递归中起不到作用，有什么方法可以解决的吗

**Comment by 2881099** [comment]
这确实是个麻烦事，orm 不知道软删除的字段。

开放一个设置，API 不知道怎么定义。

最后建议树表，最好用物理删除。
