### ISSUE TITLE
批量导入数据，导入到数据库中的数据少了

### ISSUE THREAD

**Issue by zhujinhu21** [dotnetcore/FreeSql#59]
我从excel中读取数据，读取到List集合中的个数是133905，

var fsql = new FreeSql.FreeSqlBuilder()
                                  .UseConnectionString(FreeSql.DataType.SqlServer, conn_string)
                                  .UseAutoSyncStructure(false) //自动同步实体结构到数据库
                                  .Build();
userList = fsql.Insert<Users>(entityList).ExecuteInserted();
debug看到entityList总数是133905

调用后，数据库中只有133653条，少了几百条数据。

**Comment by 2881099** [comment]
此时userList多少长度

**Comment by 2881099** [comment]
```csharp
fsql.Insert<TEntity>(entityList).NoneParameter().ExecuteInserted();
```

这样执行试试

**Comment by 2881099** [comment]
经测试发现，未使用 NoneParameter() 执行时，由于一个分割计算基数错误，导致丢失了部分。

使用 .NoneParameter() 不会出现这个情况。

**Comment by 2881099** [comment]
谢谢反馈

**Comment by 2881099** [comment]
提交代码忘了给 #59

v0.6.9 更新了这个问题。

**Comment by zhujinhu21** [comment]
@2881099 谢谢，我更新测试下
