### ISSUE TITLE
oracle 主键过长错误 ORA-00972: 标识符过长 #383

### ISSUE THREAD

**Issue by 835718973** [dotnetcore/FreeSql#590]
CONSTRAINT "EMACROWEB_basic_user_in_role_pk1" PRIMARY KEY ("Id")

CodeFist模式下Oracle数据库生成的主键约束名称过长(用户名_表名_pk1),其中用户名称这一组成部分是否有必要呢？
在#383有人提这个问题，用OraclePrimaryKeyName确实能解决，但每个实体都添加这个特性，不是特别方便，是否有其它方式在configentity时修改这个值呢

**Comment by luoyunchong** [comment]
[https://github.com/dotnetcore/FreeSql/issues/383](https://github.com/dotnetcore/FreeSql/issues/383)
