### ISSUE TITLE
升级到 rds mysql8.0 的时候会频繁报出 Reading from the stream has failed

### ISSUE THREAD

**Issue by yanght** [dotnetcore/FreeSql#591]
在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
         在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n 
           在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
            在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n 
              在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n 
                在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n  
                 在 System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n 
                   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   
                   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
                    在 System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n 
                      在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   
                      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n 
                        在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n  
                         在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n  
                          在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
                          在 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()","InnerException":{"Message":"出现错误。","ExceptionMessage":"Fatal error encountered during command execution.","ExceptionType":"MySql.Data.MySqlClient.MySqlException","StackTrace":"  
                           在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)\r\n 
                             在 MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)\r\n  
                              在 System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   
                              在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n 
                                在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n  
                                 在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n 
                                   在 FreeSql.Internal.CommonProvider.AdoProvider.<ExecuteReaderMultipleAsync>d__141.MoveNext()","InnerException":{"Message":"出现错误。","ExceptionMessage":"Fatal error encountered attempting to read the resultset.","ExceptionType":"MySql.Data.MySqlClient.MySqlException","StackTrace":"  
                                    在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()\r\n  
                                     在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)","InnerException":{"Message":"出现错误。","ExceptionMessage":"Reading from the stream has failed.","ExceptionType":"MySql.Data.MySqlClient.MySqlException","StackTrace":" 
                                     在 MySql.Data.MySqlClient.MySqlStream.LoadPacket()\r\n  
                                    在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()\r\n 
                                      在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)\r\n   
                                   在 MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)\r\n  
                                    在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)\r\n  
                                    在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()","InnerException":{"Message":"出现错误。","ExceptionMessage":"尝试读取超出流末尾的内容。","ExceptionType":"System.IO.EndOfStreamException","StackTrace":"  
 在 MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)\r\n  
  在 MySql.Data.MySqlClient.MySqlStream.LoadPacket()"}}}}}

**Comment by 2881099** [comment]
Fatal error encountered during command execution.

一堆信息，只需要看这个就行了，去百度找有很多方式可以尝试一下。
