### ISSUE TITLE
主键 int类型 使用 InsertOrUpdate 时候有问题

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#596]
新增时候对象的id为0  执行InsertOrUpdate   会变成修改第一条内容  
guid的主键则不会有这个问题  
应该是只检测主键是不是null了
这个情况怎么处理~

**Comment by 2881099** [comment]
他不是自增就会插入

**Comment by lhtuling** [comment]
> int主键，如果值是0，但不是自增。
> 
> 就会插入

明白了!忽略了这一点  好的多谢
