### ISSUE TITLE
Mysql Where内用单个&连接符链接多个条件 的问题

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#599]
Where内用单个&连接符链接多个条件
  生成的sql语句  where条件也是用&链接的  会导致不能正确查询出数据
例如
.Where(it => it.A == A & it.B == B);
这个情况就查询不出数据
把&换成2个&&这样就ok  感觉在这个使用中没必要区分这两个情况吧!
还是说有其他的考虑?

**Comment by luoyunchong** [comment]
https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/boolean-logical-operators

**Comment by lhtuling** [comment]
> https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/boolean-logical-operators

大佬这个&和&&的区别我明白的  不过我意思是在咱们这个where的用途中没有必要用&这个特性吧   正常应该是&  和&&都生成为AND吧  如果需要做区分的复杂查询也是用()括号来区分的啊
mysql生成为&这个符号  查询数据错误的!

**Comment by 2881099** [comment]
& 是位操作，不是 AND

意义不同，位操作数据库支持的

**Comment by lhtuling** [comment]
> & 是位操作，不是 AND
> 
> 意义不同，位操作数据库支持的

好的明白了~~  菜鸟之前没用过&所以产生误解~~  以为mysql里面&用不到呢
