### ISSUE TITLE
oracle生成的表，有双引号，在plsql dev里面直接打开表，提示找不到表

### ISSUE THREAD

**Issue by jetydu** [dotnetcore/FreeSql#6]
oracle生成的表，有双引号，在plsql dev里面直接打开表，提示找不到表，最好能把双引号去掉，不然用plsql dev比较麻烦
internal override string QuoteSqlName(string name) => $"{name.Trim('"')}";

**Comment by 2881099** [comment]
不加双引号使用，其实是转成小写执行。

声明 FreeSql 的时候有一个选项：
.UseSyncStructureToLower(true) //转小写同步结构

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/53139452-a7683f80-35c4-11e9-924d-db6a90c7dbc5.png)

**Comment by 2881099** [comment]
哦小写貌似也不行，这个选项是针对 pgsql 加的，看来 oracle 下还是不适合加双引号

**Comment by 2881099** [comment]
一类人：加双引号能保留表名、字段名的原型（大小写混用）。
另一类人：不加的话会显示成全大写，其实也比较蛋疼。

多刚才去掉双引号，运行单元测试时候出现的错误：

1、自增序列名也找不见了，由于之前是加双引号的；
。。。后面发现错误再整理进来

**Comment by 2881099** [comment]
声明 FreeSql 的时候增加了一个选项：
.UseQuoteSqlName(false) //默认是true，数据库名称使用 [] 或 `` 或 "" 包含起来，取决于数据库类别

**Comment by 2881099** [comment]
后来我想到了一个更好的解决办法
UseSyncStructureToUpper(true)

这样迁移后就是大写了，完美解决你的问题。
