### ISSUE TITLE
MySQL 5.5.562版本 用Tolist(t=>....)  或者 泛型方式_fsql.Select<T>().ToSql()会报错   同样代码在8.0版本上不会报错

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#600]
一般报这个错误 
(0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3)'

**Comment by lhtuling** [comment]
是不是有最低支持版本呢?

**Comment by 2881099** [comment]
大概率是因为 datetime(3)，这个在 mysql 5.5 不支持

解决办法：

1、[Column(DbType = "DATETIME")]

2、统一处理的话写个AOP

```c#
fsql.Aop.ConfigEntityProperty += (s, e) =>
{
    if (e.Property.PropertyType == typeof(DateTime) || e.Property.PropertyType == typeof(DateTime?))
         e.ModifyResult.DbType = "DATETIME";
};
```

https://github.com/dotnetcore/FreeSql/issues/75

**Comment by 2881099** [comment]
这个问题以前有发生过，多用关键字搜索 issues，或许有想找的答案。

**Comment by lhtuling** [comment]
> 这个问题以前有发生过，多用关键字搜索 issues，或许有想找的答案。

好的感谢 我搜了 可能提问的方式和关键词不太一样 下次多搜搜看!  感谢大佬回复
