### ISSUE TITLE
CentOS8 ARM 下连接 SQL Server 2008 R2（Hypervisor）

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#601]
本文主要记录在 ARM 系统下无法连接SQL Server 2008 R2 的解决过程。

解决方案是使用 ODBC 的方式连接数据库，进行操作。

资料：https://www.cnblogs.com/miaowacao/p/14100506.html

**Comment by densen2014** [comment]
其他参考资料:

.net core linux环境下 System.Data.SqlClient.SqlException: Connection Timeout Expired.
在windows环境下运行完全正常，但在linux环境下运行报异常，提示
`System.Data.SqlClient.SqlException: Connection Timeout Expired. The timeout period elapsed during the post-login phase.`
原因是net core 的System.Data.SqlClient最低支持SqlServer 2008 R2 SP3,小于这个版本的就会报错

类似的错误还有
`[SQL Server 2005] System.Data.SqlClient: pre-login fails `
