### ISSUE TITLE
IsIgnore返回数据也没有关联

### ISSUE THREAD

**Issue by xcmonline** [dotnetcore/FreeSql#602]
当数据库有一个字段设置了IsIgnore，表示在更新或新增时不需要该字段，但在查询时需要关联出该字段，返回的数据却也过滤掉了。
比如表1 在新增或修改时不需要 字段 userName，但在使用withsql查询时有userName，这时实体的映射就没有了userName的数据。

**Comment by 2881099** [comment]
CanInsert = false, CanUpdate = false
