### ISSUE TITLE
freesql如何建立非主键导航属性

### ISSUE THREAD

**Issue by Crazyfang** [dotnetcore/FreeSql#604]
在开发中遇到一个问题，需要保留多条不同时间段的数据，一个时间只会有一条数据是有效的，则建立导航属性时需要以非主键建立导航属性，如何实现呢
例子：
`class A {
public long Id { get;set;}
public string AId { get;set;}
public List<B> BList {get;set;}
}`

`class` B {
public long Id {get;set;}
public string BId {get;set;}
public string ForeignEntity {get;set;}
}`

B中的ForeignEntity存储的是A中的AId，如何让A中的AId和B中的ForeignEntity关联起来

**Comment by 2881099** [comment]
导航属性的关系：只能与外部类的主键关键。

或者使用中临时配置关系，具体见文档，联表、多表查询。

**Comment by 2881099** [comment]
如果只是查询，可以尝试以下方法扩展：

```csharp
public class JoinTest01
{
    public int id { get; set; }
    public string code { get; set; }
    public string parentcode { get; set; }
    public string name { get; set; }

    [JoinCondition("a.parentcode = b.code")]
    public JoinTest01 Parent { get; set; }
}

var sql = fsql.Select<JoinTest01>()
    .Include(a => a.Parent.Parent)
    .Where(a => a.Parent.Parent.code == "001")
    .ToSql();
//SELECT a."id", a."code", a."parentcode", a."name" 
//FROM "jointest01" a 
//LEFT JOIN "jointest01" a__Parent ON a__Parent.parentcode = a.code 
//LEFT JOIN "jointest01" a__Parent__Parent ON a__Parent__Parent.parentcode = a__Parent.code 
//WHERE (a__Parent__Parent."code" = '001')


fsql.Aop.ParseExpression += (_, e) =>
{
    if (e.Expression is MemberExpression memExp == false) return;
    ParameterExpression parmExp = null;
    var exps = new List<MemberExpression>();
    exps.Add(memExp);
    while (memExp.Expression != null)
    {
        if (memExp.Expression is MemberExpression parentExp)
        {
            exps.Add(parentExp);
            memExp = parentExp;
            if (fsql.CodeFirst.GetTableByEntity(memExp.Type) == null) return;
            continue;
        }
        if (memExp.Expression is ParameterExpression parmExp2)
        {
            parmExp = parmExp2;
            break;
        }
        return;
    }
    if (parmExp == null) return;
    var oldTables = e.Tables.ToArray();
    var result = e.FreeParse(e.Expression);
    for (var a = oldTables.Length; a < e.Tables.Count; a++)
    {
        if (string.IsNullOrEmpty(e.Tables[a].NavigateCondition) == false) continue;
        var parentTableAlias = e.Tables[a].Alias?.Split(new[] { "__" }, StringSplitOptions.None);
        if (parentTableAlias == null || parentTableAlias.Length <= 1) continue;
        var parentTable = e.Tables.Where(c => c.Alias == string.Join("__", parentTableAlias.Take(parentTableAlias.Length - 1))).FirstOrDefault();
        if (parentTable == null || parentTable.Table.Properties.TryGetValue(parentTableAlias.Last(), out var navProp) == false) continue;
        var joinAttr = navProp.GetCustomAttribute<JoinConditionAttribute>();
        if (joinAttr == null) continue;
        e.Tables[a].NavigateCondition = joinAttr.Condition
            .Replace("a.", e.Tables[a].Alias + ".")
            .Replace("b.", parentTable.Alias + ".");
    }
    e.Result = result;
};

public class JoinConditionAttribute : Attribute
{
    public string Condition { get; set; }
    public JoinConditionAttribute(string condition) => Condition = condition;
}
```

**Comment by sgf** [comment]
> 如果只是查询，可以尝试以下方法扩展，OneToOne/ManyToOne 有效：
> 
> ```cs
> public class JoinTest01
> {
>     public int id { get; set; }
>     public string code { get; set; }
>     public string parentcode { get; set; }
>     public string name { get; set; }
> 
>     [JoinCondition("a.parentcode = b.code")]
>     public JoinTest01 Parent { get; set; }
> }
> 
> var sql = fsql.Select<JoinTest01>()
>     .Include(a => a.Parent.Parent)
>     .Where(a => a.Parent.Parent.code == "001")
>     .ToSql();
> //SELECT a."id", a."code", a."parentcode", a."name" 
> //FROM "jointest01" a 
> //LEFT JOIN "jointest01" a__Parent ON a__Parent.parentcode = a.code 
> //LEFT JOIN "jointest01" a__Parent__Parent ON a__Parent__Parent.parentcode = a__Parent.code 
> //WHERE (a__Parent__Parent."code" = '001')
> 
> 
> fsql.Aop.ParseExpression += (_, e) =>
> {
>     if (e.Tables == null) return;
>     if (e.Expression is MemberExpression memExp == false) return;
>     ParameterExpression parmExp = null;
>     var exps = new List<MemberExpression>();
>     exps.Add(memExp);
>     while (memExp.Expression != null)
>     {
>         if (memExp.Expression is MemberExpression parentExp)
>         {
>             exps.Add(parentExp);
>             memExp = parentExp;
>             if (fsql.CodeFirst.GetTableByEntity(memExp.Type) == null) return;
>             continue;
>         }
>         if (memExp.Expression is ParameterExpression parmExp2)
>         {
>             parmExp = parmExp2;
>             break;
>         }
>         return;
>     }
>     if (parmExp == null) return;
>     var oldTables = e.Tables.ToArray();
>     var result = e.FreeParse(e.Expression);
>     for (var a = oldTables.Length; a < e.Tables.Count; a++)
>     {
>         if (string.IsNullOrEmpty(e.Tables[a].NavigateCondition) == false) continue;
>         var parentTableAlias = e.Tables[a].Alias?.Split(new[] { "__" }, StringSplitOptions.None);
>         if (parentTableAlias == null || parentTableAlias.Length <= 1) continue;
>         var parentTable = e.Tables.Where(c => c.Alias == string.Join("__", parentTableAlias.Take(parentTableAlias.Length - 1))).FirstOrDefault();
>         if (parentTable == null || parentTable.Table.Properties.TryGetValue(parentTableAlias.Last(), out var navProp) == false) continue;
>         var joinAttr = navProp.GetCustomAttribute<JoinConditionAttribute>();
>         if (joinAttr == null) continue;
>         e.Tables[a].On = joinAttr.Condition
>             .Replace("a.", e.Tables[a].Alias + ".")
>             .Replace("b.", parentTable.Alias + ".");
>     }
> };
> 
> public class JoinConditionAttribute : Attribute
> {
>     public string Condition { get; set; }
>     public JoinConditionAttribute(string condition) => Condition = condition;
> }
> ```

太复杂.这么做舍本逐末了.还不如价格连接查询来得简单.

**Comment by 2881099** [comment]
最新报道

非主键关联：https://github.com/dotnetcore/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb

https://freesql.net/guide/navigate-attribute.html

**Comment by sgf** [comment]
> 最新报道
> 
> 非主键关联：https://github.com/dotnetcore/FreeSql/wiki/%e5%ae%9e%e4%bd%93%e5%85%b3%e7%b3%bb
> 
> https://freesql.net/guide/navigate-attribute.html

终于加了!  感谢作者!
