### ISSUE TITLE
System.InvalidCastException: 指定的转换无效。

### ISSUE THREAD

**Issue by daiweixm** [dotnetcore/FreeSql#608]
在 Oracle.ManagedDataAccess.Client.OracleDataReader.GetDecimal(Int32 i)
   在 Oracle.ManagedDataAccess.Client.OracleDataReader.GetValue(Int32 i)
   在 FreeSql.Internal.Utils.InternalDataReaderGetValue(CommonUtils commonUtil, DbDataReader dr, Int32 index)
   在 lambda_method(Closure , Type , Int32[] , DbDataReader , Int32 , CommonUtils )
   在 FreeSql.Internal.Utils.ExecuteArrayRowReadClassOrTuple(String flagStr, Type typeOrg, Int32[] indexes, DbDataReader row, Int32 dataIndex, CommonUtils _commonUtils)
   在 FreeSql.Internal.CommonProvider.AdoProvider.<>c__DisplayClass49_0`1.<Query>b__0(FetchCallbackArgs`1 fetch)
   在 FreeSql.Internal.CommonProvider.AdoProvider.<>c__DisplayClass79_0.<ExecuteReader>b__0(FetchCallbackArgs`1 fetch, Int32 result)
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   --- 内部异常堆栈跟踪的结尾 ---
   在 FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException)
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReader(DbConnection connection, DbTransaction transaction, Action`1 fetchHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.AdoProvider.Query[T](Type resultType, DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms)
   在 FreeSql.Internal.CommonProvider.AdoProvider.Query[T](CommandType cmdType, String cmdText, DbParameter[] cmdParms)

**Comment by daiweixm** [comment]
1	408.407727272727	150.24	176
在oracle中，使用to_number，对三列转换，在实体层，使用Decimal属性接受第一列报错。

**Comment by 2881099** [comment]
oracle adonet 实现不友好，建议少用 sql

**Comment by 2881099** [comment]
Oracle.ManagedDataAccess.Client.OracleDataReader.GetDecimal(Int32 i)

错误发生在 adonet 里面
