### ISSUE TITLE
升级到1.10版本后，多主键的表，根据一个主键更新数据（包含另一个主键更新），生成的sql变成了插入

### ISSUE THREAD

**Issue by linyaoTom** [dotnetcore/FreeSql#610]
uow.Orm.Update<BA_BatchInfo>()
                         .SetRaw("MaterialCode = @MaterialCode,MaterialName=@MaterialName,ModelCode=@ModelCode", new { MaterialCode = detail.ReMaterialCode, MaterialName = materialItem.MaterialName, ModelCode = materialItem.ModelCode })
                       .Where("BatchCode = @BatchCode ", new { BatchCode = detail.BatchCode})
                       .WithTransaction(uow.GetOrBeginTransaction()).ExecuteAffrows();

**Comment by 2881099** [comment]
啥问题
