### ISSUE TITLE
FreeSqlGlobalExtensions.cs  172行  if (existsProp.DeclaringType != prop)  判断是不是永远为真？

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#611]
![image](https://user-images.githubusercontent.com/23652113/102624125-89e36d00-417e-11eb-9195-cb1ed87a783a.png)
    public static Dictionary<string, PropertyInfo> GetPropertiesDictIgnoreCase(this Type that) => that == null ? null : _dicGetPropertiesDictIgnoreCase.GetOrAdd(that, tp =>
    {
        var props = that.GetProperties().GroupBy(p => p.DeclaringType).Reverse().SelectMany(p => p); //将基类的属性位置放在前面 #164
        var dict = new Dictionary<string, PropertyInfo>(StringComparer.CurrentCultureIgnoreCase);
        foreach (var prop in props)
        {
            if (dict.TryGetValue(prop.Name, out var existsProp))
            {
                if (existsProp.DeclaringType != prop) dict[prop.Name] = prop;
                continue;
            }
            dict.Add(prop.Name, prop);
        }
        return dict;
    });

**Comment by 2881099** [comment]
这里写的原因是考虑了 new 重写属性。

**Comment by 2881099** [comment]
if (existsProp.DeclaringType != prop.DeclaringType) dict[prop.Name] = prop;

这行应该这样判断，已修正，谢谢
