### ISSUE TITLE
实现匿名类型查询

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#613]
我实现匿名类型查询，像下面这样：
ifreeSql.SelectAnonymousType(new {Name="",Id=0 }).WithSql("TableOrSjql")
请问大神，有没有可能把它加到FreeSql中，
如果需要，怎么贡献代码？

**Comment by 2881099** [comment]
暂时不需要，谢谢

匿名类型这样定义看起来比较别扭，不知道有没有了解过 c# 9.0 record，可能更合适做这种功能，伪代码：

```c#
record Dto(string name, int id);

fsql.Select<Dto>().WithSql("TableOrSjql").ToList();
```

**Comment by sqlite-me** [comment]
OK
