### ISSUE TITLE
WhereIf逻辑问题

### ISSUE THREAD

**Issue by mic277203** [dotnetcore/FreeSql#615]
我希望从界面获取时间后，判断时间是否为空，而进行条件拼凑，但是现在这边很矛盾。如果为空，它还是会去执行ToDateTime，于是就抛出

**System.FormatException:“该字符串未被识别为有效的 DateTime。”**

`
var startTime = "";
fsql.Select<TestTable>()
.WhereIf(!string.IsNullOrEmpty(startTime), "a.CreateTime>:StartTime", new { StartTime = Convert.ToDateTime(startTime)})
.ToList()`

**Comment by 2881099** [comment]
var startTime = ""; fsql.Select<TestTable>() .WhereIf(!string.IsNullOrEmpty(startTime),  a=> a.CreateTime > DateTime.Parse(startTime))
