### ISSUE TITLE
求助:实体创建如何忽略主键？

### ISSUE THREAD

**Issue by 835718973** [dotnetcore/FreeSql#617]
目前遇到一个需求,对数据修改时需要保存数据的历史记录,历史记录表与原表的结构一致但是历史记录中的Id字段是会重复的。
目前发现如果能够使用astable+忽略主键创建可以最小代价实现，但是忽略主键不知道有没有方法实现

**Comment by 2881099** [comment]
主键是自增？具体监视 sql

**Comment by 835718973** [comment]
不是自增，就一个Id字符串
g.oracle.Insert<Song>().AsTable(s => s + "_his").AppendData(new Song()).ExecuteAffrows();
想通过这种方式来创建一个历史记录表存储数据，但是创建_his表的时候同时生成了主键，如何实现在这个步骤不生成主键标记

**Comment by 2881099** [comment]
class Song_his : Song
{
   \[Column(IsPrimary = false)]
   public override int Key { get; set; }
}

这样如何？

**Comment by 835718973** [comment]
这个可以不生成主键，但是需要为每个历史记录创建一个对应实体,效果不是特别理想，只能作为备选方案

**Comment by 2881099** [comment]
分开，比在一个实体上做条件分支好维护，可以考虑弄个 T4 生成继承

**Comment by 835718973** [comment]
现在在尝试通过运行时动态创建历史记录实体类实现,主要功能能够实现了，但是有点小问题
var obj= Activator.CreateInstance(t);
            var car = new Car()
            {
                Id = "aaa",
                Name = "bbb"
            };
            car.Map(obj);

            //反射方法调用
            var method = GetType().GetMethod(nameof(Insert)).MakeGenericMethod(t);
            method.Invoke(null, new object[] { obj });
            //直接调用
            fsql.Insert(obj).AsType(t).ExecuteAffrows();

        public static void Insert<T>(T entity) where T:class
        {
            
            fsql.Insert(entity).ExecuteAffrows();
        }
其中t是通过TypeBuilder创建的动态类，在这种情况反射调用能正常操作，但是直接调用astype操作报错
System.Exception:“操作的数据类型(History) 与 AsType(System.Object) 不一致，请检查。”
这个是个bug吗？

**Comment by 2881099** [comment]
```c#
fsql.Insert<object>()
.AsType(t)
.AppendData(obj)
.ExecuteAffrows();
```

https://www.cnblogs.com/FreeSql/p/14118470.html
