### ISSUE TITLE
使用FreeSql.Generator 命令行方式生成数据库实体类时-NameOptions的 # 下划线转驼峰属性不生效

### ISSUE THREAD

**Issue by xiaoxiongcn** [dotnetcore/FreeSql#618]
执行脚本：
FreeSql.Generator -Razor "__razor.cshtml.txt" -NameOptions 0,0,0,1 -NameSpace A.Models -DB "Oracle,Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST =10.87.0.43)(PORT = 1521)))(CONNECT_DATA =(SID= ORCL)));User ID=KANBAN;Password=MPT_KANBAN" -Filter View+StoreProcedure -FileName "{name}.cs"
资料来源数据库为Oracle，使用  -NameOptions  # 下划线转驼峰属性生成实体类后似乎只去掉了下划线，例： GSG_EQUI_DAY_DATA为GSGEQUIDAYDATA ，EQUIPMENT_ID为EQUIPMENTID ，下图作为参考
![image](https://user-images.githubusercontent.com/61345559/102965328-97a34480-4528-11eb-9179-e0dec810da33.png)

**Comment by 2881099** [comment]
-NameOptions 0,0,1,1

试试这样

**Comment by xiaoxiongcn** [comment]
已经ok了，谢谢
