### ISSUE TITLE
关于arm下面sqlite无法连接问题

### ISSUE THREAD

**Issue by cctczyg** [dotnetcore/FreeSql#621]
大佬好！
最近尝试将应用迁入arm平台，但第一关数据连接受阻，特咨询大佬：
1、系统环境参数：Linux Linux.dotnet 4.1.15-1.2.0+gd87b5be #1 SMP PREEMPT Tue Aug 7 14:36:07 CST 2018 armv7l GNU/Linux
2、发布目标框架：netcoreapp3.1
3、发布目标运行时：可移植的
4、sqlite连接字符串："Data Source=/root/publish/Data/wincc.db;Version=3;"
5、报错：Unhandled exception. System.Exception: 【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
请大佬确认一下，是否在arm环境下有什么注意事项？辛苦！谢谢！

**Comment by densen2014** [comment]
可能sqlite没arm驱动

**Comment by 2881099** [comment]
试试自己编译 FreeSql.Provider.Sqlite 把引用的 adonet 换成 Microsoft.Data.Sqlite.dll

**Comment by cctczyg** [comment]
@2881099 @densen2014 好的，我了解一下驱动相关的问题，谢了

**Comment by cctczyg** [comment]
我自己编译了一套linux-arm下的sqlite运行库，放到runtimes/linux-arm/native文件夹下，已经可以正常运行了，谢大佬提醒。
附文件：链接: https://pan.baidu.com/s/1ymDpFgsTK77ITKpwDOaQuQ 提取码: jaff

**Comment by dashenxian** [comment]
@cctczyg 你编译这个是arm32架构的吗？我在arm64的docker中复制到runtimes/linux-arm/native和runtimes/linux-arm64/native，仍然会报错，另外，你的sqlite源代码从哪里下载的呢？

**Comment by meizihuai** [comment]
> 我自己编译了一套linux-arm下的sqlite运行库，放到runtimes/linux-arm/native文件夹下，已经可以正常运行了，谢大佬提醒。 附文件：链接: https://pan.baidu.com/s/1ymDpFgsTK77ITKpwDOaQuQ 提取码: jaff

大佬，我这里linux-arm32也是不行，请问能联系你吗

**Comment by meizihuai** [comment]
> UseConnctionFactory(DataType.Sqlite, ()=> new Microsoft.Data.Sqlite.SqliteConnection(str))

换成这样也是不行呢

**Comment by densen2014** [comment]
加群4336577

**Comment by densen2014** [comment]
arm,树莓派使用freesql说明
         1.添加包
        <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.0.100" />
        <PackageReference Include = "Microsoft.Data.Sqlite" Version="6.0.3" />

         2.代码
        Microsoft.Data.Sqlite.SqliteConnection _database = new Microsoft.Data.Sqlite.SqliteConnection($"Data Source=document.db");

        var fsql = new FreeSql.FreeSqlBuilder()
        .UseConnectionFactory(FreeSql.DataType.Sqlite, () => _database, typeof(FreeSql.Sqlite.SqliteProvider<>))
        .UseAutoSyncStructure(true)
        .UseNoneCommandParameter(true) //必须开启,因为Microsoft.Data.Sqlite内插处理有bug
        .UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
        .Build();

例子:  https://github.com/densen2014/FreeSqlDemos/tree/master/ARM_ConsoleApp

**Comment by densen2014** [comment]
**有条件的同学直接试试 FreeSql.Provider.SqliteCore 包,使用的就是Microsoft.Data.Sqlite驱动.**
