### ISSUE TITLE
级联保存时，怎样自动填充雪花算法生成的主键值

### ISSUE THREAD

**Issue by rungroo** [dotnetcore/FreeSql#622]
数据库主键 id 采用 long 类型，代码中通过[审计属性值](https://github.com/dotnetcore/FreeSql/wiki/AOP#%E5%AE%A1%E8%AE%A1%E5%B1%9E%E6%80%A7%E5%80%BC)自动生成主键。
当级联保存（OneToMany）时，保存的实体都没有填充id，期望自动填充。
```
  [Table(Name = "song")]
  public class Song
  {
    [Column(IsPrimary = true)]
    public long Id { get; set; }

    public string Name { get; set; }

    [Navigate(nameof(Tag.SongId))]
    public List<Tag> Tags { get; set; }
  }

  [Table(Name = "song_tag")]
  public class Tag
  {
    [Column(IsPrimary = true)]
    public long Id { get; set; }

    public string Name { get; set; }

    [Column(Name = "song_id")]
    public long SongId { get; set; }

    [Navigate(nameof(SongId))]
    public Song Song { get; set; }
  }
```

```
      var cts = new[] {
        new Song
        {
            Name = "分类1",
            Tags = new List<Tag>(new[]
            {
                new Tag { Name = "分类1_1" },
                new Tag { Name = "分类1_2" },
                new Tag { Name = "分类1_3" }
            })
        },
        new Song
        {
            Name = "分类2",
            Tags = new List<Tag>(new[]
            {
                new Tag { Name = "分类2_1" },
                new Tag { Name = "分类2_2" }
            })
        }
      };

      var repo = fsql.GetRepository<Song>();
      return repo.Insert(cts);
```

结果是数据成功保存，但主外键不一致。
跟踪生成的sql：执行完主表插入后，freesql通过以下语句查询数据，明显有问题：
```
      SELECT a.`Id`, a.`Name`, a.`song_id`
      FROM `song_tag` a
      WHERE (a.`Id` = 0)
      limit 0,1
```

请问如何使用自定义id算法时使用级联保存功能？

**Comment by 2881099** [comment]
AuditValue 代码怎么写的

**Comment by rungroo** [comment]
fsql.Aop.AuditValue += (s, e) =>
      {
        if (e.AuditValueType == FreeSql.Aop.AuditValueType.Insert)
        {
          // id
          //if (e.Column.Attribute.IsPrimary
          //  && e.Property.GetCustomAttribute<SnowflakeAttribute>(false) != null
          //  && e.Value?.ToString() == "0")
          //{
          //  e.Value = SnowflakeAttribute.GetId();
          //}
          if (e.Property.Name == "Id") e.Value = SnowflakeAttribute.GetId(); // <===========================

          // 其他字段处理...
        }

        if (e.AuditValueType == FreeSql.Aop.AuditValueType.Update)
        {
          // 其他字段处理...
        }

          // 其他字段处理...
      };

> AuditValue 代码怎么写的

**Comment by rungroo** [comment]
> AuditValue 代码怎么写的

freesql代码没有太多研究，请教一下：
1. 审计的设计是否是高于级联处理，会在 sql 中将级联关系覆盖掉，也就是说二者本身不可以并存？
2. 主键guid类型试过了没问题，我看源码中也针对自增和guid有大量的处理。问题是guid以字符串的形式充当主键非常别扭，我希望基于freesql有一个比较优雅的方案。

**Comment by 2881099** [comment]
AuditValue 有可能覆盖原来的值，所以需要判断一下本身有没有值，再填充

**Comment by rungroo** [comment]
> AuditValue 有可能覆盖原来的值，所以需要判断一下本身有没有值，再填充

好的，多谢！
