### ISSUE TITLE
group by问题

### ISSUE THREAD

**Issue by bilujun** [dotnetcore/FreeSql#623]
1：实体类
[Table(Name = "s_facility")]
public partial class S_facility {

[JsonProperty, Column(DbType = "date", IsPrimary = true)]
public DateTime Date { get; set; }

[JsonProperty, Column(IsPrimary = true)]
public int EnterpriseId { get; set; }

[JsonProperty, Column(IsPrimary = true)]
public byte FacilityType { get; set; }

[JsonProperty, Column(DbType = "tinyint(4)", IsPrimary = true)]
public sbyte Dot { get; set; }

[JsonProperty]
public ushort FacilityCount { get; set; }

[JsonProperty]
public ushort FacilityOpenCount { get; set; }

}

2：tosql代码
var sql = fsql.Select<S_facility>()
                    .Where(a => a.Date == date.Date)
                    .Where(a => enterpriseIds.Contains(a.EnterpriseId))
                    .Where(a => a.FacilityType == 1)
                    .GroupBy(a => a.Dot)
                    .ToSql(a => new {
                        Dot = a.Key,
                        FacilityCount = a.Sum(a.Value.FacilityCount),
                        FacilityOpenCount = a.Sum(a.Value.FacilityOpenCount)
                    });
生成sql语句,sql语句在mysql workbench能执行
SELECT a.`Dot`, sum(a.`FacilityCount`) as1, sum(a.`FacilityOpenCount`) as2 
FROM `s_facility_20201230` a 
WHERE (a.`Date` = cast(date_format('2020-12-30 00:00:00.000','%Y-%m-%d') as datetime)) AND (((a.`EnterpriseId`) in (5))) AND (a.`FacilityType` = 1) 
GROUP BY a.`Dot`

3：tosql改成tolist代码throw exception
var rows = fsql.Select<S_facility>()
                    .Where(a => a.Date == date.Date)
                    .Where(a => enterpriseIds.Contains(a.EnterpriseId))
                    .Where(a => a.FacilityType == 1)
                    .GroupBy(a => a.Dot)
                    .ToList(a => new {
                        Dot = a.Key,
                        FacilityCount = a.Sum(a.Value.FacilityCount),
                        FacilityOpenCount = a.Sum(a.Value.FacilityOpenCount)
                    });
错误信息："Exception has been thrown by the target of an invocation."
堆栈信息：
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at FreeSql.Internal.CommonProvider.SelectGroupingProvider.InternalToList(Expression select, Type elementType, Boolean isAsync)
   at FreeSql.Internal.CommonProvider.SelectGroupingProvider`2.ToList[TReturn](Expression`1 select)

**Comment by 2881099** [comment]
是不是数据问题，我这边测试没出现错误。

**Comment by bilujun** [comment]
![image](https://user-images.githubusercontent.com/68941962/103330354-17d32800-4a9c-11eb-92a4-446f60893b28.png)
数据没问题，这个是tosql生成的查询结果。奇怪的很，用了这么多group by 就这一个有问题。

**Comment by bilujun** [comment]
这个测试的表没数据的

**Comment by 2881099** [comment]
检查几个 freesql.dll freesql.provider.mysql.dll 版本是否一致？

**Comment by bilujun** [comment]
恩，找到原因了，这个表不在这个库中，实际错误是表不存在，抛出的异常最好能改进下

**Comment by 2881099** [comment]
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   在 FreeSql.Internal.CommonProvider.SelectGroupingProvider.InternalToList(Expression select, Type elementType) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\SelectGroupingProvider.cs 中: 第 112 行
   在 FreeSql.Internal.CommonProvider.SelectGroupingProvider`2.ToList[TReturn](Expression`1 select) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\SelectGroupingProvider.cs 中: 第 208 行
   在 FreeSql.Tests.Issues._623.MySqlGroupBy() 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql.Tests\FreeSql.Tests\Issues\623.cs 中: 第 52 行

  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(int, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Action<FreeSql.Internal.Model.FetchCallbackArgs<System.Data.Common.DbDataReader>, int>, System.Action<System.Data.Common.DbDataReader, int>, System.Data.CommandType, string, int, System.Data.Common.DbParameter[]) (位于 AdoProvider.cs 中)

内部异常 1:
Exception: Table 'cccddd.ts_facility' doesn't exist

内部异常 2:
MySqlException: Table 'cccddd.ts_facility' doesn't exist


完整错误信息

**Comment by bilujun** [comment]
恩，现在明白了，一开始只是查自己抛出的Exception，没想到去看innerexception，谢谢大佬。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/FreeSql"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 中午12:55
收件人:&nbsp;"dotnetcore/FreeSql"<FreeSql@noreply.github.com&gt;;
抄送:&nbsp;"故乡的云"<540195677@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/FreeSql] group by问题 (#623)





 
System.Reflection.TargetInvocationException
 HResult=0x80131604
 Message=Exception has been thrown by the target of an invocation.
 Source=System.Private.CoreLib
 StackTrace:
 在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
 在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
 在 FreeSql.Internal.CommonProvider.SelectGroupingProvider.InternalToList(Expression select, Type elementType) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\SelectGroupingProvider.cs 中: 第 112 行
 在 FreeSql.Internal.CommonProvider.SelectGroupingProvider2.ToList[TReturn](Expression1 select) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\SelectGroupingProvider.cs 中: 第 208 行
 在 FreeSql.Tests.Issues._623.MySqlGroupBy() 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql.Tests\FreeSql.Tests\Issues\623.cs 中: 第 52 行
 
此异常最初是在此调用堆栈中引发的:
 [外部代码]
 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(int, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Action<FreeSql.Internal.Model.FetchCallbackArgs<System.Data.Common.DbDataReader&gt;, int&gt;, System.Action<System.Data.Common.DbDataReader, int&gt;, System.Data.CommandType, string, int, System.Data.Common.DbParameter[]) (位于 AdoProvider.cs 中)
 
内部异常 1:
 Exception: Table 'cccddd.ts_facility' doesn't exist
 
内部异常 2:
 MySqlException: Table 'cccddd.ts_facility' doesn't exist
 
完整错误信息
