### ISSUE TITLE
Identity如何设置初始值和增量

### ISSUE THREAD

**Issue by wangshenglong** [dotnetcore/FreeSql#625]
/// <summary>
        /// 自增ID
        /// </summary>
        [Description("自增ID")]
        [Column(IsIdentity = true)]
        public int appId { get; set; }

如何设置identity(101,2)这样的

**Comment by 2881099** [comment]
目前不支持

**Comment by wangshenglong** [comment]
[Description("自增ID")]
        [Column(IsPrimary = true, DbType = "int Identity(101,1)")]
        public int appId { get; set; }

我这样设置后,可以用但是我docker重新更新下后..就报语法错误...自动同步实体类

**Comment by 2881099** [comment]
这倒是提醒我了，这样呢？

[Column(IsPrimary = true, IsIdentity = true, DbType = "int Identity(101,1)")]

**Comment by wangshenglong** [comment]
> 这倒是提醒我了，这样呢？
> 
> [Column(IsPrimary = true, IsIdentity = true, DbType = "int Identity(101,1)")]

不行...重启后就是语法错误

**Comment by wangshenglong** [comment]
> 这倒是提醒我了，这样呢？
> 
> [Column(IsPrimary = true, IsIdentity = true, DbType = "int Identity(101,1)")]

就是第一次同步实体类的时候可以,但是后面如我docker容器重启了,他会继续同步实体类,这时候就报语法错误了

**Comment by 2881099** [comment]
你没有加 IsIdentity = true

**Comment by wangshenglong** [comment]
> 你没有加 IsIdentity = true

改过了,加了一样的结果

**Comment by 2881099** [comment]
目前仍然不支持

**Comment by peng0829** [comment]
请问一下,这里这样使用是可以的嘛?
类:
 [Column(IsIdentity = true)]
Code
第一次创建数据库后,创建表
CodeFirst.SyncStructure<User>();
然后设置当前值
.Ado.ExecuteNonQuery(@"
SELECT setval('public.""User_Code_seq""', 10000, true);");
这样实现初始值是10000,是可行的吗?

**Comment by 2881099** [comment]
可以
