### ISSUE TITLE
占用连接池 connection_sum 经常导致出现 主库状态不可用的情况

### ISSUE THREAD

**Issue by goodluckily** [dotnetcore/FreeSql#626]
【主库】状态不可用，等待后台检查程序恢复方可使用。Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

出现这样的报错

**Comment by 2881099** [comment]
单例定义的 IFreeSql ？
