### ISSUE TITLE
Oracle11g中FreeSql.Generator生成DATE类型实体的问题

### ISSUE THREAD

**Issue by hvppy** [dotnetcore/FreeSql#627]
oracle11g中定义的类型为DATE,用工具FreeSql.Generator生成的实体属性为[JsonProperty, Column(DbType = "DATE(7)")],然后codefirst根据实体创建表的时候就会有问题:ORA-00907: missing right parenthesis,是因为生成的语句为:"MyDate" DATE(7),这个写法oracle报错,改为[JsonProperty, Column(DbType = "DATE")]之后程序可以正常执行

**Comment by 2881099** [comment]
好的，先改模板再生成一次解决当下使用问题
