### ISSUE TITLE
IgnoreColumns 似乎会影响到 CanUpdate

### ISSUE THREAD

**Issue by fishjimi** [dotnetcore/FreeSql#631]
fsql.Aop.ConfigEntityProperty += (s, e) =>
            {
                if (e.Property.Name == "CreatedAt" || e.Property.Name == "UpdatedAt")
                {
                    e.ModifyResult.CanInsert = false;
                    e.ModifyResult.CanUpdate = false;
                }
            };

原来在aop里指定了不修改这两个字段，运行也挺正常

但是后来发现 当在 Update.SetSource中使用IgnoreColumns忽略其他额外字段的时候，CreatedAt和UpdatedAt字段会被更新，
去掉IgnoreColumns后恢复正常

**Comment by 2881099** [comment]
是会，文档应该写过。

**Comment by 2881099** [comment]
IgnoreColumns 相当于强制，重新设置忽略

**Comment by fishjimi** [comment]
虽然似乎感觉有点不太符合预期，不过我还是换种方式用吧，感谢大佬日夜不眠
