### ISSUE TITLE
规范性建议：将JSON库更换为System.Data.Json

### ISSUE THREAD

**Issue by rungroo** [dotnetcore/FreeSql#633]
目前官方已推荐使用System.Data.Json作为标准Json解析库，无论从性能还是规范性上都比 Newtonsoft.Json 更强，希望作者考虑。

> ASP.NET Core 3.0 uses System.Text.Json by default for JSON serialization. System.Text.Json:
> Reads and writes JSON asynchronously.
> Is optimized for UTF-8 text.
> Typically higher performance than Newtonsoft.Json.

详细信息可以从这里了解：
https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0

**Comment by 2881099** [comment]
FreeSql 与 json 无关，你是说 JsonMap 扩展库吗？

**FreeSql.Extensions.JsonMap** 的代码实现比较简单，可以自行修改解决。

目前 newtonsoft.json 在易用性上仍然有比较大的优势。

**Comment by rungroo** [comment]
好的，多谢

**Comment by frisktale** [comment]
希望postgresql的驱动包能换成System.Text.Json，现在使用的是Newtonsoft.Json。只是个人建议，不换也行
