### ISSUE TITLE
mysql 使用官方代码FreeSqlExtensions.cs 创建数据库后不能立马使用

### ISSUE THREAD

**Issue by zh163yx** [dotnetcore/FreeSql#634]
使用FreeSqlExtensions内的代码，在新建数据库后下一条代码执行插入操作时会报错，提示找不到数据库，但此时mysql内已经有了该数据库，但是主库状态还是false 只有等主库再次检测后才能插入。如何让主库立马可用,而不是要等待一会,毕竟我已经看到mysql创建成功了

**Comment by luoyunchong** [comment]
https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Infrastructure/FreeSql/FreeSqlExtension.cs

用的这个吗。。这个我已经改成反射获取了。。在Build之前 创建数据的。

**Comment by zh163yx** [comment]
> https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Infrastructure/FreeSql/FreeSqlExtension.cs
> 
> 这个我已经改成反射获取字符串了。。在建立之前创建数据库的。

用的这个链接上的，我从使用手册上直接打开的,我尝试下你给的这个连接试下
https://github.com/luoyunchong/dotnetcore-examples/blob/master/ORM/FreeSql/OvOv.FreeSql/FreeSqlExtensions.cs

**Comment by zh163yx** [comment]
> https://github.com/luoyunchong/lin-cms-dotnetcore/blob/master/src/LinCms.Infrastructure/FreeSql/FreeSqlExtension.cs
> 
> 用的这个吗。。这个我已经改成反射获取字符串了。。在Build之前 创建数据库的。

谢谢，这个方式解决了刚才的问题。
