### ISSUE TITLE
类型映射和部分类的结合使用

### ISSUE THREAD

**Issue by rungroo** [dotnetcore/FreeSql#636]
目前我是使用dbfirst方式生成的实体code，由于有枚举字段（比如说blog_type），直接修改生成器生成的类显然不安全，所以在部分类中加入了枚举：
```
    [Column(Name = "blog_type", MapType = typeof(sbyte))]// <--------------------------请问这里该如何标注
    public BlogType BlogTypeEnum
    {
      get
      {
        return (BlogType)this.BlogType;
      }
      set
      {
        this.BlogType = (sbyte)value;
      }
```

或者有没有其他的方法。

**Comment by 2881099** [comment]
MapType = typeof(int) 这样可以

**Comment by rungroo** [comment]
> MapType = typeof(int) 这样可以

会提示 BlogTypeEnum 字段不存在，其实它对应的是 blog_type 字段，但 blog_type 字段已经在 BlogType 属性标记了，这里再标记会提示重复。
如果给 BlogTypeEnum 标记 IsIgnore=true，会提示 SubjectTypeEnum 被忽略，请检查 IsIgnore 设置。

**Comment by rungroo** [comment]
额，我描述再清楚点儿：
partial class C1.cs <----------代码生成器生成
```
    [JsonProperty, Column(Name = "blog_type")]
    public long BlogType { get; set; }
```

partial class C2.cs
```
    [Column(Name = "blog_type", MapType = typeof(sbyte))]// <--------------------------请问这里该如何标注
    public BlogType BlogTypeEnum
    {
      get
      {
        return (BlogType)this.BlogType;
      }
      set
      {
        this.BlogType = (sbyte)value;
      }
    }
```

**Comment by 2881099** [comment]
```c#
[Column(Name = "blog_type", MapType = typeof(long))]
public BlogType BlogType { get; set; }
```

这样就行了

**Comment by rungroo** [comment]
> ```cs
> [Column(Name = "blog_type", MapType = typeof(long))]
> public BlogType BlogType { get; set; }
> ```
> 
> 这样就行了

额，这样得手动修改自动生成的文件，存在覆盖风险。目前也没想到一个好的办法，只能把枚举改成静态类。
