### ISSUE TITLE
分组排序 取第一条内容的问题

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#641]
碰到这个需求 
分组后 根据明细表的一个字段排序后 取第一条

按照下面的解决方式
测试发现 不可以排序后取第一条 比如需要按照ID倒叙排序最大的  上面的sql语句用法查出来的都是正序第一个

求大佬指点 哪里搞错了~
_Originally posted by @lhtuling in https://github.com/dotnetcore/FreeSql/issues/430#issuecomment-758102882_

**Comment by lhtuling** [comment]
等于是分组后明细表里的字段排序好像无效了  所以取出来的都是id最小的一条

**Comment by densen2014** [comment]
> 等于是分组后明细表里的字段排序好像无效了  所以取出来的都是id最小的一条

咨询的时候最好带上你自己的代码

**Comment by lhtuling** [comment]
> > 等于是分组后明细表里的字段排序好像无效了  所以取出来的都是id最小的一条
> 
> 咨询的时候最好带上你自己的代码

好的  代码太乱 我整理个demo试试

**Comment by densen2014** [comment]
select部分代码加你的类就行了

**Comment by lhtuling** [comment]
`
    public class Member
    {
        [FreeSql.DataAnnotations.Column( IsPrimary = true, IsIdentity = true)]
        public int Uid { get; set; }
        public string WxId { get; set; }
        public string WxName { get; set; }
    }

    public class Msg
    {
        [ FreeSql.DataAnnotations.Column( IsPrimary = true, IsIdentity = true)]
        public int Id { get; set; }
        public string Content { get; set; }
        public string WxId { get; set; }
    }`
Member表内容
uid	WxId		WxName
1	wxid_11111	张三
2	wxid_22222	李四
3	wxid_33333	王五
4	wxid_44444	麻子六


Msg表内容
id	Content	WxId
1	消息1	wxid_11111
2	消息2	wxid_11111
3	消息3	wxid_11111
4	消息4	wxid_11111
5	aaaa		wxid_22222
6	bbbb	wxid_22222
7	cccc		wxid_22222

按照430 Issues的写法 加上分组 
`
var sql = fsql.Select<Member, Msg>()
                .LeftJoin((a, b) => b.WxId == (fsql.Select<Msg>().As("b2").Where(b2 => b2.WxId == a.WxId).First(b2 => b2.WxId)))
                .GroupBy("b.WxId")
                .OrderByDescending((a, b) =>b.Id)
                .ToSql((a, b) => new { a, b });`
 出来结果是
2	wxid_22222	李四	5	aaaa	wxid_22222
1	wxid_11111	张三	1	消息1	wxid_11111
3	wxid_33333	王五			
取出的是正序的第一条 
实际需要的是倒叙的第一条  也就是最新的一条数据  
同时取出  Member的数据和Msg的最新一条数据
大佬帮忙看看怎么搞~~感谢

**Comment by lhtuling** [comment]
> select部分代码加你的类就行了

大佬 上面详细发了下问题  有空帮忙看下感谢~

**Comment by densen2014** [comment]
生成的sql发一下. 我打开电脑看看

**Comment by lhtuling** [comment]
> 生成的sql发一下. 我打开电脑看看

SELECT a."Uid" as1, a."WxId" as2, a."WxName" as3, b."Id" as4, b."Content" as5, b."WxId" as6 
FROM "Member" a 
LEFT JOIN "Msg" b ON b."WxId" = (SELECT b2."WxId" 
    FROM "Msg" b2 
    WHERE (b2."WxId" = a."WxId") 
    limit 0,1) 
GROUP BY b.WxId 
ORDER BY b."Id" DESC

感谢大佬了  这么晚了~~

**Comment by densen2014** [comment]
![QQ截图20210111192341](https://user-images.githubusercontent.com/8428709/104222436-950a7f80-5442-11eb-9f1b-76bb903705d5.png)
按你的数据执行出来只有一条结果

**Comment by lhtuling** [comment]
![image](https://user-images.githubusercontent.com/44140500/104222610-83929900-547d-11eb-93e4-ed3bb4cab7d4.png)

我这执行出来是3条的 
> ![QQ截图20210111192341](https://user-images.githubusercontent.com/8428709/104222436-950a7f80-5442-11eb-9f1b-76bb903705d5.png)
> 按你的数据执行出来只有一条结果

**Comment by lhtuling** [comment]
不着急 大佬有空帮忙再看也行  这么晚了早点休息

**Comment by densen2014** [comment]
我在西欧时区
![QQ截图20210111193750](https://user-images.githubusercontent.com/8428709/104224004-a81e4f00-5444-11eb-8445-5140f8068782.png)

**Comment by densen2014** [comment]
你数据库是sqlite吗?是的话 zip一个发这里附件, 叶老板起来了也会看到

**Comment by lhtuling** [comment]
好的

**Comment by lhtuling** [comment]
[db - 复制.zip](https://github.com/dotnetcore/FreeSql/files/5797691/db.-.zip)

**Comment by densen2014** [comment]
sqlite数据
[000_freesql.zip](https://github.com/dotnetcore/FreeSql/files/5797695/000_freesql.zip)
数据截图
![数据截图](https://user-images.githubusercontent.com/8428709/104224283-119e5d80-5445-11eb-94d3-b04c05614e50.png)
SQLITE执行截图
![QQ截图20210111193750](https://user-images.githubusercontent.com/8428709/104224353-2aa70e80-5445-11eb-82b7-a2a1cd38aaec.png)
MSSQL执行截图
![mssql执行截图](https://user-images.githubusercontent.com/8428709/104224322-211da680-5445-11eb-889b-dca892e94720.png)

**Comment by densen2014** [comment]
> [db - 复制.zip](https://github.com/dotnetcore/FreeSql/files/5797691/db.-.zip)

你试试我的 https://github.com/dotnetcore/FreeSql/files/5797695/000_freesql.zip

**Comment by lhtuling** [comment]
> > [db - 复制.zip](https://github.com/dotnetcore/FreeSql/files/5797691/db.-.zip)
> 
> 你试试我的 https://github.com/dotnetcore/FreeSql/files/5797695/000_freesql.zip

![image](https://user-images.githubusercontent.com/44140500/104224870-85119080-5480-11eb-8297-077b3846f9f0.png)
你两列内容搞反了~~~

**Comment by densen2014** [comment]
> > > [db - 复制.zip](https://github.com/dotnetcore/FreeSql/files/5797691/db.-.zip)
> > 
> > 
> > 你试试我的 https://github.com/dotnetcore/FreeSql/files/5797695/000_freesql.zip
> 
> ![image](https://user-images.githubusercontent.com/44140500/104224870-85119080-5480-11eb-8297-077b3846f9f0.png)
> 你两列内容搞反了~~~

我看到了. 你先睡吧. 我等下看看,好像是生成不太对,sqlite比较不严格,mssql就执行不了的.group少了uid.

**Comment by lhtuling** [comment]
恩恩好的 感谢大佬了

**Comment by densen2014** [comment]
你把问题复杂化了,这就是一个include的问题

**Comment by densen2014** [comment]
不知道你是不是要这个结果
```
            var sql = fsql.Select<Member, Msg>()
                .LeftJoin((a, b) => a.WxId == b.WxId)
                .OrderByDescending((a, b) => b.Id)
                .ToOne((a, b) => new { a, b });
```
![sss](https://user-images.githubusercontent.com/8428709/104226106-925e5900-5447-11eb-8de2-e372d04f605c.png)

**Comment by lhtuling** [comment]
> 不知道你是不是要这个结果
> 
> ```
>             var sql = fsql.Select<Member, Msg>()
>                 .LeftJoin((a, b) => a.WxId == b.WxId)
>                 .OrderByDescending((a, b) => b.Id)
>                 .ToOne((a, b) => new { a, b });
> ```
> 
> ![sss](https://user-images.githubusercontent.com/8428709/104226106-925e5900-5447-11eb-8de2-e372d04f605c.png)

不对的  这个是只取一条  我是需要按照Member表的内容找到Msg表关联的最新一条消息

**Comment by lhtuling** [comment]
等于是在现在的连表查询基础上对Msg表加个排序  取ID最大的一条

**Comment by lhtuling** [comment]
> 你把问题复杂化了,这就是一个include的问题
> 
> https://github.com/dotnetcore/FreeSql/wiki/%e5%a4%9a%e8%a1%a8%e6%9f%a5%e8%af%a2

百度到个方法  修改测试数据是正确的
`SELECT
    max.*, MAX(max.WxId) lineMax
FROM
    (
        SELECT
            *
        FROM
            Msg a		
					
				LEFT JOIN Member b on a.WxId=b.WxId
				WHERE b.uid=1
        ORDER BY
            Id DESC
    LIMIT 100
    ) max
		
GROUP BY
    WxId`

大佬看看用咱们的库应该怎么写

**Comment by lhtuling** [comment]
SELECT
    max.*
FROM
    (
        SELECT
            *
        FROM
            Msg a		
					
				LEFT JOIN Member b on a.WxId=b.WxId
				WHERE b.uid=1  --条件可以去掉
        ORDER BY
            Id DESC
    LIMIT 100
    ) max
		
GROUP BY
    WxId


在网上找到了个方法  修改测试是ok的  然后大佬看看用咱们的库应该怎么写!

**Comment by 2881099** [comment]
#430 不能满足吗

**Comment by lhtuling** [comment]
> #430 不能满足吗

貌似是不能的   
需要下面这样的结果
![image](https://user-images.githubusercontent.com/44140500/104267455-a26c4c00-54cc-11eb-8dac-a05570aa4b1d.png)

**Comment by lhtuling** [comment]
430那个 出来的是最老的一条 不是最新一条的  等于是排序无效

我参考这个文章上面sql语句修改是正常的↓ 
https://blog.csdn.net/weixin_36795183/article/details/104649398

**Comment by 2881099** [comment]
按照 #430 LeftJoin 的写法，可以正确查询：

```sql
SELECT 
*
FROM member a
LEFT JOIN msg b ON b.id = (SELECT b2.id FROM msg b2 WHERE ( b2.wxid = a.wxid ) ORDER BY b2.id desc LIMIT 0,1) 
```

```
uid	WxId	WxName	id	Content	WxId1
1	wxid_11111	张三	4	消息4	wxid_11111
2	wxid_22222	李四	7	cccc	wxid_22222
3	wxid_33333	王五			
4	wxid_44444	麻子六			
```

**Comment by 2881099** [comment]
把 LEFT JOIN 换成 INNER JOIN 就和你要的结果一样了

**Comment by lhtuling** [comment]
> 把 LEFT JOIN 换成 INNER JOIN 就和你要的结果一样了

好的感谢大佬  我试试   不过用咱们的库应该怎么写呢   可以的话麻烦甩个代码

**Comment by lhtuling** [comment]
> 把 LEFT JOIN 换成 INNER JOIN 就和你要的结果一样了
对的  sql语句测试ok   sql基础不扎实   麻烦大佬们了

**Comment by 2881099** [comment]
```c#
var result = freeSql.Select<Member, Msg>()    
  .InnerJoin((a, b) => b.Id == (freeSql.Select<Msg>().As("b2").Where(b2 => b2.WxId == a.WxId).OrderByDescending(b2 => b2.Id).First(b2 => b2.Id)))
  .ToList((a, b) => new { a, b });
```

**Comment by luoyunchong** [comment]
```
var result = freeSql.Select<BaseType>()
  .IncludeMany(r => r.BaseItems.Take(1))
  .ToList();
}
```
这段代码中BaseItems.Take(1) ，Take前可以oderby的。。这是最简单的，想精确生成 想要的sql。

https://github.com/dotnetcore/FreeSql/issues/430 left join 后,Where 也能order by 的。

**Comment by lhtuling** [comment]
> ```
> var result = freeSql.Select<BaseType>()
>   .IncludeMany(r => r.BaseItems.Take(1))
>   .ToList();
> }
> ```
> 
> 这段代码中BaseItems.Take(1) ，Take前可以oderby的。。这是最简单的，想精确生成 想要的sql。
> 
> #430 left join 后,Where 也能order by 的。

感谢各位大佬  成功了!~!!  sql不扎实所以都用rom了    碰到复杂的就挠头~~
成功解决了  感谢!

**Comment by lhtuling** [comment]
> ```cs
> var result = freeSql.Select<Member, Msg>()    
>   .InnerJoin((a, b) => b.Id == (freeSql.Select<Msg>().As("b2").Where(b2 => b2.WxId == a.WxId).OrderByDescending(b2 => b2.Id).First(b2 => b2.Id)))
>   .ToList((a, b) => new { a, b });
> ```

不用导航属性  这个完美解决 其他碰到的朋友可以参考使用
