### ISSUE TITLE
子查询  b."isdeleted"='f‘重复生成了

### ISSUE THREAD

**Issue by rongguohao** [dotnetcore/FreeSql#642]
数据库：postgresql

代码：
     var items = await DbContext.Select<SysDict>()
                        .WhereIf(query.DictType.HasValue, a => a.DictType == query.DictType)
                        .WhereIf(query.DictName.HasValue(), a => a.DictName.Contains(query.DictName))
                        .WhereIf(query.DictCode.HasValue(), a => a.DictCode.Contains(query.DictCode))
                        .OrderByDescending(a => a.CreateTime)
                        .Count(out var total)
                        .Page(query.PageIndex, query.PageSize)
                        .ToListAsync(a => new DictDto
                        {
                            Id = a.Id,
                            ParentId = a.ParentId,
                            DictCode = a.DictCode,
                            DictName = a.DictName,
                            Remark = a.Remark,
                            CreateTime = a.CreateTime,
                            ItemNames = string.Join('，', DbContext.Select<SysDict>().Where(b => a.Id == b.ParentId).ToList(b => b.ItemName))
                        });

生成sql如下：

SELECT a."id" as1, a."parentid" as2, a."dictcode" as3, a."dictname" as4, a."remark" as5, a."createtime" as6, (SELECT string_agg((b."itemname")::text,'，')
    FROM "sysdict" b
    WHERE (a."id" = b."parentid") AND (b."isdeleted" = 'f') AND (b."isdeleted" = 'f')) as7
FROM "sysdict" a
WHERE (a."dicttype" = 0) AND (a."isdeleted" = 'f')
ORDER BY a."createtime" DESC
limit 10
offset 10

**Comment by 2881099** [comment]
实体类发一下

**Comment by 2881099** [comment]
可以了，下个版本优化解决 v2.3.0

**Comment by rongguohao** [comment]
> 可以了，下个版本优化解决 v2.3.0
大佬 辛苦
