### ISSUE TITLE
generator tool根据SqlServer2012生成实体类时，存在string类型属性默认值设定错误问题

### ISSUE THREAD

**Issue by ShangQuX** [dotnetcore/FreeSql#645]
如下是生成的代码：
[Column(DbType = "varchar(2)")]
public string Status { get; set; } = "NULL";
[Column(DbType = "varchar(255)")]
public string Remarks { get; set; } = "NULL";
上代码在插入时造成的结果有2个，分别是Remarks字段默认是null，但在数据库中存储为“NULL”字符；Status因长度限制插入失败；

**Comment by 2881099** [comment]
改模板 Replace 一下，再生成

**Comment by 2881099** [comment]
> __razor.cshtml.txt

> __重新生成.bat

生成后，目录下会有这两个文件，第一个是模板文件

第二个双击可以重新生成。

**Comment by ShangQuX** [comment]
我已经通过改“__razor.cshtml.txt”模版，修正了此问题。仅仅想表达默认生成存在这个问题。

**Comment by 2881099** [comment]
好的，非常感谢，已处理
