### ISSUE TITLE
FreeSql.Repository.SaveMany 级联保存 希望增加参数指定只做插入、更新、删除的一种或两种操作

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#647]
FreeSql.Repository.SaveMany的级联保存非常方便。
但在很多情境下只希望做插入、更新、删除的一种操作，SaveMany对更新、删除操作出错的风险更大，如果用参数指定具体的操作，这样更安全，更明确。
也可以返回操作响应的记录数量。
希望大神考虑下吗！

**Comment by 2881099** [comment]
感谢建议，方便的话，提供一些简单的伪代码，对设计 api 有帮助。

**Comment by 2881099** [comment]
最近也在考虑 SaveMany 能否支持继续向下保存。

**Comment by 2881099** [comment]
文档更新了，聚合根实验室
