### ISSUE TITLE
net core 3.1 连接 Oracle 

### ISSUE THREAD

**Issue by yangjinzzz** [dotnetcore/FreeSql#648]
![image](https://user-images.githubusercontent.com/22075757/104703057-d4421480-5751-11eb-98a0-bf0fbfae2a35.png)

**Comment by yangjinzzz** [comment]
![image](https://user-images.githubusercontent.com/22075757/104703105-e3c15d80-5751-11eb-8517-ca024c385908.png)

**Comment by yangjinzzz** [comment]
`#region  freesql引用
			Fsql = new FreeSqlBuilder()
					 .UseConnectionString(FreeSql.DataType.Oracle, "Oracle,Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST =ip)(PORT = 1521)))(CONNECT_DATA =(SID= ORCL)));User ID=账号;Password=密码")
					 .UseAutoSyncStructure(false) //不自动更新,用dotnet-tool更新实体类
					 .Build();
			////审计,操作耗时很高时执行
			//Fsql.Aop.CurdAfter += (s, e) =>
			//{
			//	if (e.ElapsedMilliseconds > 200)
			//	{
			//		//记录日志
			//		//发送短信给负责人
			//	}
			//};
			//Fsql.Aop.AuditValue += (s, e) =>
			//{
			//	//统一插入创建时间()
			//	if (e.Property.Name == "create_time" && e.Value == null)
			//	{
			//		e.Value = DateTime.Now;
			//	}
			//};
			//过滤器(示例,ID==1的时候才允许查询,当前User)
			//Fsql.GlobalFilter.Apply<User>("Show", p => p.Id == 1);
			services.AddSingleton<IFreeSql>(Fsql);
			////全局过滤器(满足条件则全部过滤掉)
			//services.AddFreeRepository(filter => filter.Apply<User>("delete", p => p.IsDelete == 1));
	     services.AddScoped<UnitOfWorkManager>();
		 services.AddFreeRepository(null, typeof(Startup).Assembly);`

**Comment by 2881099** [comment]
> "Oracle,Data Source=...

连接串错误，前面多了 Oracle,
