### ISSUE TITLE
树形结构有的带条件过滤子节点的么？

### ISSUE THREAD

**Issue by dzw159** [dotnetcore/FreeSql#649]
AsTreeCte()
.ToTreeList()

获取的树状对象的Childs 对象能否过滤 IsDelete=0（带上条件过滤）

**Comment by 2881099** [comment]
有设置全局过滤器吗

**Comment by 2881099** [comment]
```c#
fsql.Select<Tree>()
    .Where(a => a.IsDelete == 0)
    .AsTreeCte()
    .ToList()
```

这样？

**Comment by dzw159** [comment]
fsql.Select<Tree>()
    .Where(a => a.IsDelete == 0)
    .AsTreeCte()
    .ToList()

这个补充后，查询出来的 Childs集合包含了没有 过滤 IsDelete == 0 的，想带个条件，也将获取的 Childs里头过滤一下

**Comment by yaobo-lab** [comment]
这个问题是没有解决的只能：在AsTreeCte 后再加条件
.AsTreeCte()
.Where(a => a.IsDelete == 0)

**Comment by dzw159** [comment]
好的，谢谢你



董志文
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/FreeSql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月7日(星期六) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/FreeSql] 树形结构有的带条件过滤子节点的么？ (#649)





 
这个问题是没有解决的只能：在AsTreeCte 后再加条件
 .AsTreeCte()
 .Where(a =&gt; a.IsDelete == 0)
