### ISSUE TITLE
Freesql code first 外键

### ISSUE THREAD

**Issue by junbao520** [dotnetcore/FreeSql#654]
FreeSQL code first 生成数据库时，数据库中没有建立外键？
请问下是在那点配置数据库中生成外键了？
数据库 sqlserver 2017

**Comment by 2881099** [comment]
FreeSql CodeFirst 没有物理外键同步功能。

导航属性，只是实体间在 c# 语言中的一种虚拟关系。

**Comment by junbao520** [comment]
谢谢! 非常感谢，个人建议可以考虑做一个配置可选项，是否生成物理外键！
