### ISSUE TITLE
AsTable分表的索引命名问题

### ISSUE THREAD

**Issue by pxy372407031** [dotnetcore/FreeSql#655]
数据库:           PostgreSQL
Freesql版本： 2.0.105
由于PostgreSQL的索引名称好像是数据库内唯一，不能重名。你们在创建索引时会加上表名称来防止重名。 格式：  uk_表名称_索引名。
但是我在使用AsTable实现分表的时候，好像没有根据分表名称来命名，导致索引重名。  这个是我没配置好的原因还是说目前不支持PostgreSQL分表呢？

**Comment by 2881099** [comment]
分表场景的索引可以这样：[Index("{tablename}_idx_01", "phone")]

**Comment by pxy372407031** [comment]
好的，我试下，谢谢

**Comment by zbxpcq** [comment]
tablename这个变量  从哪里来?

**Comment by zbxpcq** [comment]
> 分表场景的索引可以这样：[Index("{tablename}_idx_01", "phone")]

tablename 这个变量从哪里来？

**Comment by luoyunchong** [comment]
[Table(Name="xxx")]或者默认当前实体
