### ISSUE TITLE
asp.net core 5.0 环境下连接oracle数据库连不上

### ISSUE THREAD

**Issue by syrjgc11006** [dotnetcore/FreeSql#658]
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)
【主库】仍然不可用，下一次恢复检查时间：2021/1
 been thrown by the target of an invocation.)

**Comment by 2881099** [comment]
解决版本：试试手工引用 oracle ado.net 驱动到最新版本

原因：freesql 2.0.105 所引用的 oracle ado.net 驱动版本，之前测试是不支持 .net50 的。

**Comment by syrjgc11006** [comment]
好的  谢谢

**Comment by LevyTerritory** [comment]
你这个问题和Freesql没关系。是因为.net core 5.0对二进制序列化做了限制(高的安全验证)，要在project下设置EnableUnsafeBinaryFormatterSerialization为true
`<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	</PropertyGroup>`
