### ISSUE TITLE
数组列 自动转Json的问题  数据库时候自动转换 

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#659]
有这个功能么我恍惚在哪里看到过  然后翻文档又找不到了~~~  文档能搜索就更好了

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/105441183-f6ccb400-5ca2-11eb-821e-acd24ebe0ae2.png)

**Comment by lhtuling** [comment]
额 这个搜索 搜json好多的  源码里都出来了~~~
大佬咱们这个库有上面我说的这个功能么

**Comment by lhtuling** [comment]
貌似搜到了   左边有分类
JsonMap 是这个东西么?  我在看看

**Comment by luoyunchong** [comment]
FreeSql.Extensions.JsonMap

https://github.com/dotnetcore/FreeSql/wiki/%E5%AE%9E%E4%BD%93%E7%89%B9%E6%80%A7

**Comment by lhtuling** [comment]
> FreeSql.Extensions.JsonMap
> 
> https://github.com/dotnetcore/FreeSql/wiki/%E5%AE%9E%E4%BD%93%E7%89%B9%E6%80%A7

好的感谢~~  我记得好像看到过...越是用的时候越找不到  尴尬
