### ISSUE TITLE
FreeSql.Tools在字段名称转换的问题上，希望把ID转换成Id

### ISSUE THREAD

**Issue by kiyeer** [dotnetcore/FreeSql#66]
比如：HouseID，希望转成HouseId

**Comment by 2881099** [comment]
模板上可以临时修改一下来使用

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/60570981-3ff9a200-9da5-11e9-8b11-502697852ac4.png)

**Comment by kiyeer** [comment]
嗯，我临时修改了UFString方法
![E88E5E73-6F71-486c-8A22-752BD95982FC](https://user-images.githubusercontent.com/2967639/60572439-3160ba00-9da8-11e9-8997-6681547527e7.png)
还有就是，如果表的外键指向本表，会生成的两个相同的名称
![727046AA-82B5-49e5-9B54-2F30FE0E0C65](https://user-images.githubusercontent.com/2967639/60572569-77b61900-9da8-11e9-8fc9-a37443460b25.png)

**Comment by kiyeer** [comment]
还发现生成导航属性名没有被转换。比如首字母大写，下划线也没有转驼峰

**Comment by 2881099** [comment]
确实，以前写的dotnetGen是硬编码做的生成，模板处理这些太麻烦了，感谢反馈，有时间我考虑一下

**Comment by kiyeer** [comment]
我看你们文档上对UnitOfWork使用推荐使用using方式，我想问可以用AddScoped的方式注入吗？

**Comment by 2881099** [comment]
他们有人使用 AOP 做工作单元

[UnitOfWork]
public ... MethodName() {
}

**Comment by kiyeer** [comment]
感谢这么快回复，还有一个问题，我觉得MySql的tinyint(1)应该生成bool类型，而不是sbyte类型。这个问题在EFCore生成是也存在。

**Comment by 2881099** [comment]
bool 应该对应 bit，tinyint 类型 ado.net 执行查询数据返回确实是 sbyte 类型

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/60580882-6f65da00-9db8-11e9-8276-2b85175438e5.png)

**Comment by kiyeer** [comment]
的确如你所说，bit是二进制的，不是1就是0，用于逻辑类型更适合，好像网上搜索，大多用tinyin(1)做为bool类型。因为有人说bit不支持索引。搞不大懂了。
