### ISSUE TITLE
使用 Select.WithSql 执行 Sql 语句失败.

### ISSUE THREAD

**Issue by Roadbeg** [dotnetcore/FreeSql#660]
执行 Select.WithSql("Select top 1 Name From tbldata ").ToOne&lt;string&gt;
提示 没有为该对象构造参数的构造函数. 
估计  使用 .ToOne&lt;int&gt; 之类也会同样提示.

**Comment by Roadbeg** [comment]
执行  Select.WithSql("Select Count(*) as RecordCount From tbldata ").ToOne&lt;JeRecordCount&gt;()
提示 映射异常: JeRecordCount 没有一个属性名相同.
JeRecordCount定义如下.
public class JeRecordCount
	{
		public int RecordCount { get; set; }
	}

**Comment by 2881099** [comment]
Select 是什么类型，怎么出来的。

这个错误意思是 fsql.Select\<T>() 实体类型 T，没有找到和 JeRecordCount 类型相同的属性，内部不知道怎么查询。注意：不是认 sql as xxx

fsql.Select\< JeRecordCount>().Count()

或者

fsql.Ado.Query<int>(sql)

都可以解决问题

**Comment by Roadbeg** [comment]
Select 是其它类别,比如 上面的就是表 tbldata 的模型.
我看到可以指定  &lt;TDto&gt;
意思是这个 TDto 必须 与 实体 有至少一个属性名称相同?
那比如 我上面举例的那样, 我只是想取得 count(*).  或者我是想取得 sum 之类统计.
这样返回的数据就可能与模型没有任何一个属性名相同. 这个时候, 就必须 使用 ado.query 来实现?

如果是 fsql.select&lt;XX&gt;().Count() 会不会已经 把所有记录取到本地成为 list 了再取的 count ?  这样的话,开销就太大了.

**Comment by 2881099** [comment]
不会全部加载，具体可以监视执行的 sql
