### ISSUE TITLE
Net5下可以加上DateTime？避免警告：Warning CS8073吗

### ISSUE THREAD

**Issue by pccai** [dotnetcore/FreeSql#661]
class Topic {
    [Column(ServerTime = DateTimeKind.Utc, CanUpdate = false)]
    public **DateTime?** CreateTime { get; set; }
    
    [Column(ServerTime = DateTimeKind.Utc)]
    public **DateTime?** UpdateTime { get; set; }
}

加上？避免警告：Warning CS8073: The result of the expression is always ‘false’ since the value of type ‘DateTime’ is never equal to ‘null’ of type ‘DateTime?’

**Comment by pccai** [comment]
例如： IFreeSql.Select<Topic>().Where(a => a.UpdateTime == null || a.UpdateTime <= GlobalConstants.SYS_DATE_EMPTY)

**Comment by 2881099** [comment]
具体什么意思，编译警告？
