### ISSUE TITLE
ORA-00972: 标识符过长

### ISSUE THREAD

**Issue by zhuhuanzi** [dotnetcore/FreeSql#662]
Oralce 11g ,我的字段长度为30个字符，报错标识符过长。然后同样的实体我用Devart.Data.Oracle.EFCore这个包是好的。麻烦叶老板看看能不能解决下

**Comment by zhuhuanzi** [comment]
是插入的时候

**Comment by 2881099** [comment]
首先，监视 sql。

大概是，开了自动迁移？监视 sql 你会发现 pkname 过长，这个是生成的 pkname，表名 30，但是还有后缀大概 5个吧

最后，可以用实体特性 [OraclePrimaryName( 指定主键名
