### ISSUE TITLE
ToPagedList()  DTO映射返回怎么做 ?

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#667]
用这个做分页查询比
 .Count(out var total) //总记录数量
    .Page(1, 20)
    .Tolist();
方便

如果能dto映射就更方便了~  不知道可以不

**Comment by 2881099** [comment]
.ToList\<Dto\>();

文档：返回数据

https://github.com/dotnetcore/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%95%b0%e6%8d%ae

### Dto 映射查询

```c#
fsql.Select<Song>().ToList<Dto>();
//情况1：Dto 与 Song 属性名相同的字段被查询，返回 List<Dto>

fsql.Select<Song>().ToList(a => new Dto { xxx = a.ext }) 
//情况2：Dto 与 Song 属性名相同的字段被查询，纠正映射 ext，返回 List<Dto>

fsql.Select<Song>().ToList(a => new Song { id = a.id }) 
//情况3：Lambda 与 Song 类型一样，只查询指定字段 id，返回 List<Song>

fsql.Select<Song>().ToList(a => new { id = a.id }) 
//情况4：Lambda 匿名类型，只查询指定字段 id，返回 List<匿名对象>
请仔细处理区别，请仔细处理区别，请仔细处理区别

fsql.Select<Song>().ToList(a => new Dto(a.id))
//情况5：只查询 id，返回 List<Dto>

fsql.Select<Song>().ToList(a => new Dto(a.id) { xxx = a.ext })
//情况6：查询 id, ext，返回 List<Dto>

fsql.Select<Song>().ToList(a => new Song(a.id))
//情况7：查询 id，返回 List<Song>

fsql.Select<Song>().ToList(a => new Song(a.id) { xxx = a.ext })
//情况8：查询 id, ext，返回 List<Song>
```

- GroupBy 所有方法不使用 DTO 映射规则

- 这种映射支持单表/多表，在查询数据之前映射（不是先查询所有字段再到内存映射）

查找规则，查找属性名，会循环内部对象 _tables（join 查询后会增长），以 主表优先查，直到查到相同的字段。

如：

> A, B, C 都有 id，Dto { id, a1, a2, b1, b2 }，A.id 被映射。也可以指定 id = C.id 映射。

友情提醒：在 dto 可以直接映射一个导航属性

**Comment by lhtuling** [comment]
> .ToList<Dto>();
> 
> 文档：返回数据
> 
> https://github.com/dotnetcore/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%95%b0%e6%8d%ae
> 
> ### Dto 映射查询
> ```cs
> fsql.Select<Song>().ToList<Dto>();
> //情况1：Dto 与 Song 属性名相同的字段被查询，返回 List<Dto>
> 
> fsql.Select<Song>().ToList(a => new Dto { xxx = a.ext }) 
> //情况2：Dto 与 Song 属性名相同的字段被查询，纠正映射 ext，返回 List<Dto>
> 
> fsql.Select<Song>().ToList(a => new Song { id = a.id }) 
> //情况3：Lambda 与 Song 类型一样，只查询指定字段 id，返回 List<Song>
> 
> fsql.Select<Song>().ToList(a => new { id = a.id }) 
> //情况4：Lambda 匿名类型，只查询指定字段 id，返回 List<匿名对象>
> 请仔细处理区别，请仔细处理区别，请仔细处理区别
> 
> fsql.Select<Song>().ToList(a => new Dto(a.id))
> //情况5：只查询 id，返回 List<Dto>
> 
> fsql.Select<Song>().ToList(a => new Dto(a.id) { xxx = a.ext })
> //情况6：查询 id, ext，返回 List<Dto>
> 
> fsql.Select<Song>().ToList(a => new Song(a.id))
> //情况7：查询 id，返回 List<Song>
> 
> fsql.Select<Song>().ToList(a => new Song(a.id) { xxx = a.ext })
> //情况8：查询 id, ext，返回 List<Song>
> ```
> 
> * GroupBy 所有方法不使用 DTO 映射规则
> * 这种映射支持单表/多表，在查询数据之前映射（不是先查询所有字段再到内存映射）
> 
> 查找规则，查找属性名，会循环内部对象 _tables（join 查询后会增长），以 主表优先查，直到查到相同的字段。
> 
> 如：
> 
> > A, B, C 都有 id，Dto { id, a1, a2, b1, b2 }，A.id 被映射。也可以指定 id = C.id 映射。
> 
> 友情提醒：在 dto 可以直接映射一个导航属性

ToPagedList()里面没有这些用法的   这个用法我知道的  

用
.Count(out var total) //总记录数量
.Page(1, 20)
.Tolist();可以实现

想问下  ToPagedList()有没有  这个方法分页更方便  返回的是 PagedModel<T>

**Comment by lhtuling** [comment]
又找了下 应该是没有  可以封装下  ~~加一个带dot映射的扩展就ok了~~
