### ISSUE TITLE
求助：请问如何进行UNION的操作

### ISSUE THREAD

**Issue by haycun** [dotnetcore/FreeSql#668]
WithSql使用的是UNION ALL，需要进行UNION的查询操作，除了使用自己编写SQL语句的方式，应该怎么编写，谢谢

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/478

**Comment by haycun** [comment]
那如果想生成这样的语句该如何处理

//SELECT  * from (SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime` 
//FROM ( SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime` 
//    FROM `Topic` a 
//    WHERE ((a.`Title`) LIKE '%xxx%') ) a) ftb
// 
//**UNION**
// 
//SELECT  * from (SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime` 
//FROM ( SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime` 
//    FROM `Topic` a 
//    WHERE ((a.`Title`) LIKE '%yyy%') ) a) ftb

**Comment by luoyunchong** [comment]
没有。

**Comment by haycun** [comment]
UNION在多表查询时剔除重复行还是很实用的，是否可以考虑在后续的版本中添加上？

**Comment by 2881099** [comment]
> 那如果想生成这样的语句该如何处理
> 
> //SELECT * from (SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime`
> //FROM ( SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime`
> // FROM `Topic` a
> // WHERE ((a.`Title`) LIKE '%xxx%') ) a) ftb
> //
> //**UNION**
> //
> //SELECT * from (SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime`
> //FROM ( SELECT a.`Id`, a.`Title`, a.`Content`, a.`CreateTime`
> // FROM `Topic` a
> // WHERE ((a.`Title`) LIKE '%yyy%') ) a) ftb

这个不是可以用 or 查询吗

**Comment by haycun** [comment]
写错了，我原意是多张表的情况下
`//SELECT * from (SELECT a.Id, a.Title, a.Content, a.CreateTime
//FROM ( SELECT a.Id, a.Title, a.Content, a.CreateTime
// FROM **TopicOne** a
// WHERE ((a.Title) LIKE '%xxx%') ) a) ftb
//
//**UNION**
//
//SELECT * from (SELECT a.Id, a.Title, a.Content, a.CreateTime
//FROM ( SELECT a.Id, a.Title, a.Content, a.CreateTime
// FROM **TopicTwo** a
// WHERE ((a.Title) LIKE '%yyy%') ) a) ftb`

**Comment by pjy612** [comment]
试试那个 分表查询 同对象 
.AsTable((type,oldname)=>type==typeof(T1)?"TopicOne":oldname)
.AsTable((type,oldname)=>type==typeof(T2)?"TopicTwo":oldname)
