### ISSUE TITLE
ToList 方法是否有个bug

### ISSUE THREAD

**Issue by hajiuxbz** [dotnetcore/FreeSql#67]
List<TReturn> ToList<TReturn>(Expression<Func<T1, TReturn>> select);

这个方法使用在进行dto进行批量转换时无法使用属性的扩展方法，提示System.Exception:“未实现函数表达式

**Comment by 2881099** [comment]
贴上代码看看

**Comment by qq635842671** [comment]
public IActionResult Index()
        {
           
            return View(_novelsService.Books.ToList(r => new BookListResourceModel
            {
                Id = r.Id,
                Name = r.Name,
                PicName = r.Thumb,
                CateId = r.ChannelId,
                CreatrTime = r.CreatrTime.ToStringDateTime(),
                UpdataTime = r.UpdataTime.ToStringDateTime(),
            }));
        }


public static string ToStringDateTime(this int timestamp)
        {
            var tz = TimeZoneInfo.ConvertTimeToUtc(new DateTime(1970, 1, 1, 0, 0, 0, 0));
            return tz.AddSeconds(Convert.ToInt64(timestamp)).ToString("yyyy-MM-dd HH:mm:ss");
        }

不知道怎么排版 请见谅。

**Comment by 2881099** [comment]
这个自定义函数不支持，或者要拦截表达式来实现

**Comment by qq635842671** [comment]
好吧 不太懂这个表达式 以为跟普通一样 谢谢

**Comment by 2881099** [comment]
不行的，简单一点，就是Dto改成匿名类，查完后Select转一次

**Comment by 2881099** [comment]
先返回int值，再计算出DateTime

**Comment by qq635842671** [comment]
明白
