### ISSUE TITLE
使用[JsonMap] 后  插入正常   查询时候使用[JsonMap] 的列取不到值

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#670]
已开启
_freeSql.UseJsonMap();

查询时候为空
public class Msg : EntityBase<int>
    {
....
        [JsonMap]
        public List<long> Tels { get; set; }
        [JsonMap] 
        public List<int> ErrorIndexs{ get; set; }
....
}
上面2列查询时候内容为空   数据库是存在内容的

**Comment by lhtuling** [comment]
额  删除掉数据库表重新运行代码发现  加JsonMap的列直接不生成了~~~
应该是这个问题导致的
我在看看啥情况吧~~

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/653

**Comment by lhtuling** [comment]
见鬼了~~JsonMap就是不生效   没做版本控制....
上午还可以正常写入和查询  下午改了点东西感觉不会修改到有关的啥东西啊   就是不能用  
sqlite的数据库  jsonMap完全无效  
删除表后在生成的表里压根没有这一列  
用你说的单独建立一个class也是一样  碰到这种问题好头疼....

先不用了~~~ 先自己手动转换存字符串吧
