### ISSUE TITLE
InsertOrUpdate 方法支持指定重复的键

### ISSUE THREAD

**Issue by cocosip** [dotnetcore/FreeSql#671]
我们使用 `ABP vNext`作为我们的开发框架,在我们的业务上至少需要支持 pg数据库与 oracle 数据库, 我们目前几张表的主键是 ABP中的 Guid类型，但是业务上的唯一键是以 'TenantId'+'Uid' 两个字段组合成的唯一索引。
pg数据库下我们使用 OnConflictDoUpdate 方法能够指定多个字段的唯一键,但是在Oracle下由于未能提供额外的扩展方法，只能使用InsertOrUpdate 方法。但是InsertOrUpdate方法无法指定多个字段的唯一键。 EF Core 的InsertOrUpdate 方法又是遥遥无期。

**Comment by 2881099** [comment]
多定义一个实体类

**Comment by cocosip** [comment]
已经使用唯一单主键作为id了
