### ISSUE TITLE
查询时枚举转换优化

### ISSUE THREAD

**Issue by HaoZhiYing** [dotnetcore/FreeSql#673]
![image](https://user-images.githubusercontent.com/14025507/106359918-913a9080-6350-11eb-9e92-9140fd0a5d97.png)

语法：State = w.State == StateEnum.正常 ? "正常" : "停用",
优化后语法：State=w.State.ToString(),

**Comment by 2881099** [comment]
Lambda 表达式树翻译纯服务器行为，如果需要考虑客户端行为，还需要考虑以下情形：

情况1：Where(p => p.Status.ToString() == "完成")

情况2：ToList(p => new { xxx = p.Status.ToString() == "完成" ? 1 : 0 })

**Comment by pjy612** [comment]
@HaoZhiYing 好奇用的什么插件？

**Comment by HaoZhiYing** [comment]
> @HaoZhiYing 好奇用的什么插件？

rider
