### ISSUE TITLE
Distinct() 并分页后Count()返回的数据不对

### ISSUE THREAD

**Issue by eddyyuen** [dotnetcore/FreeSql#674]
例如：
freesql.select().distinct().count(out var count).page(1,2).tolist(p=>p.username)
返回的数据是对的。但是 count 值是username去重前的数据。

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/533

暂时先这样，下个版本解决

**Comment by 2881099** [comment]
> count 值是username去重前的数据。

这个因为在 count 的时候已经执行了，并不知道 p.username。

FreeSql 没有像 linq 那样的 Select(p => p.username) 方法。

暂时想到的办法是这样：

```c#
freesql.select().distinct().count(p => p.username, out var count)

    .page(1,2).tolist(p=>p.username)
```

**Comment by eddyyuen** [comment]
这个可能还要再改进一下，因为一般需要Distinct的不只一个字段
例如根据部门姓名去重
freesql.select().distinct().count(out var count).page(1,2).tolist(p=>new{p.username,p.department)

**Comment by 2881099** [comment]
.Aggregate(a => SqlExt2.DistinctCount(a.Key.title + "|" + a.Key.xxx), out var count)

暂时先这样？

或者重载多一个 public static long DistinctCount(object column1, object column2) 方法？

**Comment by eddyyuen** [comment]
> .Aggregate(a => SqlExt2.DistinctCount(a.Key.title + "|" + a.Key.xxx), out var count)
> 
> 暂时先这样？
> 
> 或者重载多一个 public static long DistinctCount(object column1, object column2) 方法？

其实我的SQL比较复杂，按以上两种方法都挺麻烦的。
所以现在的做法是先 Count() ，再分页。
有没有可能把 ToList 里的 OrderInfo 自动分析组合好需要的字段？

fssql.Select<Order>()
                .Page(PageIndex, PageSize)  
                .Distinct()  
                .ToList(it => new OrderInfo()  
                {
                    FundsNumber = it.FundsNumber,
                    ApproveUser = it.ApproveUser ,
                    ApproveTime = it.Updatetime,
                    IsDanger = it.IsDanger,
                    LabId = it.LabId,
                    OrderId = it.ParentOrderId,
                    AssetsApproveUser = it.AssetsApproveUser ,
                    OrderStatus = it.Status
                });

**Comment by 2881099** [comment]
.ToList(it => new OrderInfo()

目前的自动映射机制，这样用有风险，如果有未指定的字段，也可能被自动映射。https://github.com/dotnetcore/FreeSql/wiki/%e8%bf%94%e5%9b%9e%e6%95%b0%e6%8d%ae#11dto-%E6%98%A0%E5%B0%84%E6%9F%A5%E8%AF%A2

稍后发布一个 preview 解决你当前问题

**Comment by 2881099** [comment]
引用 FreeSql.Extensions.Linq.dll

大概语法如下：

```c#
fsql.Select<T>()
    .Select(it => new
{
FundsNumber = it.FundsNumber,
ApproveUser = it.ApproveUser ,
ApproveTime = it.Updatetime,
IsDanger = it.IsDanger,
LabId = it.LabId,
OrderId = it.ParentOrderId,
AssetsApproveUser = it.AssetsApproveUser ,
OrderStatus = it.Status
})
    .Distinct()
    .Count(out count)
    .ToList();
```

**Comment by kamikyo** [comment]
@2881099 大佬，你这个可以适配这种应用场景吗
.Select<T1,T2,T3,T4,T5....>().Select((a,b,c,d,e,f)=> new {...})
.Page()
.Distinct()
最终生成的distinct count就类似于这样：
select count(*) from (select distinct col1 ,col2 , col3 from table) A
集合查询那部分还是不变

**Comment by 2881099** [comment]
> @2881099 大佬，你这个可以适配这种应用场景吗
> .Select<T1,T2,T3,T4,T5....>().Select((a,b,c,d,e,f)=> new {...})
> .Page()
> .Distinct()
> 最终生成的distinct count就类似于这样：
> select count(*) from (select distinct col1 ,col2 , col3 from table) A
> 集合查询那部分还是不变

```c#
var sql = fsql.Select<T1,T2,T3,T4,T5....>().ToSql((a,b,c,d,e,f)=> new {...}, FieldAliasOptions.AsProperty);
var count = fsql.Select<object>().WithSql(sql).Count();
```

**Comment by Zonciu** [comment]
遇到类似的问题，我要查询时间字段并Distinct，然后取得Count，现在Count是直接取整行数据，Distinct的结果就不正确了。
