### ISSUE TITLE
事务不能回滚

### ISSUE THREAD

**Issue by gwhzh21** [dotnetcore/FreeSql#675]
使用FreeSql 2.0.105
FreeSql.Provider.PostgreSQL 2.0.105
FreeSql.DbContext  2.0.105

保存时，提时 字段不存在。但是数据还是保存进去了。
 using (var ctx = _freeSql.CreateDbContext())
                {
                    var persons = ctx.Set<Person>();
                    var applyperson = ctx.Set<PersonApply>();
                    var persontreepath = ctx.Set<PersonTreepath>();
                    ctx.Add(oneperson);
                    await ctx.SaveChangesAsync();
                    var id = oneperson.Id;

                    persontreepath.Add(new PersonTreepath()
                    {
                        Ancestor = id,
                        Descendant = id,
                        ParentId = id,
                        PathLength = 0,
                        PathOrder = 0
                    });

                    if (upPersonTreepaths != null && upPersonTreepaths.Count > 0)
                    {
                        foreach (var item in upPersonTreepaths)
                        {
                            persontreepath.Add(new PersonTreepath()
                            {
                                Ancestor = item.Ancestor,
                                Descendant = id,
                                ParentId = id,
                                PathLength = item.PathLength+1,
                                PathOrder = item.PathOrder+1
                            });
                        }
                    }

                    if (upPersons != null && upPersons.Count > 0)
                    {
                        foreach (var item in upPersons)
                        {
                            item.LowerNum += 1;
                            var getpersonlevel = await PersonLevel.GetPersonLevelByPersonNum
                                (item.LowerNum, _freeSql, _memoryCache);
                            item.PersonLevelId = getpersonlevel.Id;
                            persons.Update(item);
                        }
                    }

                    await ctx.SaveChangesAsync();

                }

**Comment by 2881099** [comment]
ctx.SaveChangesAsync 等于提交事务，不要分多次执行

**Comment by gwhzh21** [comment]
var id = oneperson.Id; 需要获取这个自增id，我应该怎么做？

**Comment by 2881099** [comment]
ctx.Add(oneperson);
var id = oneperson.Id;

如果是自增，直接取值就行了

**Comment by gwhzh21** [comment]
可以了，谢谢。我有一句代码写错了。放在了外面，所以我一直在觉得奇怪。为什么报错了，没有回滚。
