### ISSUE TITLE
 Db.Transaction(() =>{}） in asp.net core

### ISSUE THREAD

**Issue by ensleep** [dotnetcore/FreeSql#676]
在asp.net core api的控制器中使用事务，目前我以

            Db.Transaction(() =>
            {
               //....
            });

的方式执行，是否会有问题，其中Db是以SingleTone注入到控制器的IFreeSql。我看文档中说适合单线程如Winform中使用，但是我不知道在asp.net core api的控制器中使用是否会有问题，并且我整个项目使用的都是这个注入的Db。如果不是这样使用，应该使用哪些方式达到原生using(var trans=conn.BeginTransition())的效果。谢谢~

**Comment by 2881099** [comment]
可以这样用，也可以用aop事务

**Comment by ensleep** [comment]
谢谢……
