### ISSUE TITLE
分库分表插件bug

### ISSUE THREAD

**Issue by coderdp** [dotnetcore/FreeSql#678]
包版本：

```xml
    <PackageReference Include="FreeSql" Version="2.0.105" />
    <PackageReference Include="FreeSql.Provider.MySql" Version="2.0.105" />
    <PackageReference Include="FreeSql.Repository" Version="2.0.105" />
    <PackageReference Include="IdleBus" Version="1.5.2" />
```

mysql表定义：
```sql
 `user_name` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人',
```

实体定义：

```c#
        /// <summary>
        /// 操作人
        /// </summary>
        [JsonProperty, Column(Name = "user_name")]
        public string UserName { get; set; }
```

集合只有一条时，插入失败：
![image](https://user-images.githubusercontent.com/12269641/107012980-ba39a600-67d4-11eb-9885-e9200539dda4.png)

如果插入条数>1条时，会成功：
![image](https://user-images.githubusercontent.com/12269641/107012914-9f673180-67d4-11eb-85ad-5ab952ca1531.png)
![image](https://user-images.githubusercontent.com/12269641/107013108-e523fa00-67d4-11eb-98ca-8b5f09d92fef.png)

**Comment by coderdp** [comment]
抱歉，图给反了。bug描述：插入一条时，会提示不能为null；>1条时成功。

**Comment by 2881099** [comment]
把两次执行的SQL监视发出来一下

**Comment by coderdp** [comment]
你好，因为批量插入返回的对象时 list，无法打印sql。
![image](https://user-images.githubusercontent.com/12269641/107033684-9edc9400-67f0-11eb-859e-a5609ee74c59.png)
我上传了示例代码，可以重现这个bug。https://github.com/coderdp/TestFreeSql.git

**Comment by 2881099** [comment]
我测试了源码，没有出现错误

```sql
CREATE TABLE IF NOT EXISTS `cccddd`.`test_freesql` (  
  `id` INT(11), 
  `user_name` VARCHAR(128), 
  PRIMARY KEY (`id`)
) Engine=InnoDB;

INSERT INTO `test_freesql`(`id`, `user_name`) VALUES(1, NULL)
```

**Comment by 2881099** [comment]
MySqlException Column 'user_name' cannot be null.

这个数据应该是数据库返回的，user_name 在数据库是 not null 吗？

**Comment by 2881099** [comment]
如果数据库 user_name not null，可以试试实体特性这样：

```c#
[JsonProperty, Column(DbType = "varchar(128)", IsNullable = false)]
public string user_name { get; set; }
```

IsNullable = false，当加了此标记后，上述测试产生的 SQL 将会变成这样：

```sql
INSERT INTO `test_freesql`(`id`, `user_name`) VALUES(1, '')
```

**Comment by coderdp** [comment]
嗯，加了 IsNullable 这个特性后单条/批量都可以了插入成功。但是还是有点疑惑：不加这个特性的情况下，批量插入和单条插入表现应该一致呀，但是目前是批量插入成功，单条提示 MySqlException Column 'user_name' cannot be null.
另外：DB字段约束如下：`user_name` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人' 的情况下，使用 https://github.com/2881099/FreeSql.Tools 这个工具生成的实体不会带有 IsNullable 特性，所以是工具存在问题？

**Comment by 2881099** [comment]
用 FreeSql.Generator 生成实体类试试。

FreeSql.Tools 这个更新维护比较麻烦，已经很久没更新了。

批量，单条插入，以最终执行的 SQL 为准，试试监控一下 SQL，发出来分析一下。

**Comment by coderdp** [comment]
用 FreeSql.Generator 生成实体类也是有问题。
表结构如下：
`CREATE TABLE `test_freesql` (
  `id` int(11) NOT NULL COMMENT '主键自增id',
  `user_name` varchar(128) NOT NULL DEFAULT '' COMMENT '操作人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`
使用 FreeSql.Generator 生成的结构如下：
`

	[JsonObject(MemberSerialization.OptIn), Table(Name = "test_freesql", DisableSyncStructure = true)]
	public partial class TestFreesql {

		/// <summary>
		/// 主键自增id
		/// </summary>
		[JsonProperty, Column(Name = "id", IsPrimary = true)]
		public int Id { get; set; }

		/// <summary>
		/// 操作人
		/// </summary>
		[JsonProperty, Column(Name = "user_name", StringLength = 128)]
		public string UserName { get; set; }

	}
`
还是没有带 IsNullable  特性

**Comment by 2881099** [comment]
好的，晚上测试修复一下

**Comment by 2881099** [comment]
问题已确认，是特性生产的判断问题，已修复，下个版本 FreeSql.Generator 2.3 可以解决。

预计 2021年02月20日 发布 v2.3

**Comment by 2881099** [comment]
问题已确认，是特性生产的判断问题，已修复，下个版本 FreeSql.Generator 2.3 可以解决。

预计 2021年02月20日 发布 v2.3
