### ISSUE TITLE
支持符号调试

### ISSUE THREAD

**Issue by MetSystem** [dotnetcore/FreeSql#679]
方便定位问题
![image](https://user-images.githubusercontent.com/7943054/107140582-f1878e80-695d-11eb-857e-bb0027cc2c94.png)

**Comment by 2881099** [comment]
什么意思？

**Comment by luoyunchong** [comment]
感觉像这种需求
- https://github.com/dotnet/sourcelink
- https://www.cnblogs.com/lwqlun/p/9988369.html

**Comment by luoyunchong** [comment]
@2881099  
CAP 也支持这种，[https://github.com/dotnetcore/CAP/blob/bdfd1016e61394f603da1a84ab8567a42bf740d9/src/Directory.Build.props](https://github.com/dotnetcore/CAP/blob/bdfd1016e61394f603da1a84ab8567a42bf740d9/src/Directory.Build.props)
可以方便开发者，使用F10，就能进入源码调试。

**Comment by MetSystem** [comment]
要么将以下属性添加到 .csproj 文件：
```
<PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
</PropertyGroup>
```
https://docs.microsoft.com/zh-cn/nuget/create-packages/symbol-packages-snupkg

**Comment by luoyunchong** [comment]
已增加。下次发包就会支持。
