### ISSUE TITLE
关于Ado中ExecuteDataTable与ExecuteDataSet查询的问题

### ISSUE THREAD

**Issue by haycun** [dotnetcore/FreeSql#680]
使用Ado中ExecuteDataTable和ExecuteDataSet查询没有数据返回

var result = fsql.Ado.ExecuteDataTable(CommandType.Text, "SELECT * FROM DEMO");
var result = fsql.Ado.ExecuteDataSet(CommandType.Text, "SELECT * FROM DEMO");

以上result均无数据返回，但使用var result = fsql.Ado.Query<DEMO>(CommandType.Text, "SELECT * FROM DEMO");是有结果返回的。

**以上情况调用存储过程都没有数据返回**。如下：
var result = fsql.Ado.Query<DEMO>(CommandType.StoredProcedure, "SELECT * FROM DEMO", "CKTEST",new SqlParameter("pid", 1));

var result = fsql.Ado.ExecuteDataTable(CommandType.StoredProcedure, "SELECT * FROM DEMO", "CKTEST",new SqlParameter("pid",1));

var result = fsql.Ado.ExecuteDataSet(CommandType.StoredProcedure, "SELECT * FROM DEMO", "CKTEST",new SqlParameter("pid", 1));

var result= fsql.Ado.CommandFluent("CKTEST")
                .CommandType(CommandType.StoredProcedure)
                .CommandTimeout(60)
                .WithParameter("pid", 1)
                .ExecuteDataSet();

存储过程为
CREATE PROCEDURE [dbo].[CKTEST]
	@pid int
AS
BEGIN
	SET NOCOUNT ON;
	 SELECT  *  FROM DEMO WHERE PID=@pid
END

**Comment by 2881099** [comment]
fsql.Ado.Query(CommandType.StoredProcedure, "SELECT * FROM DEMO", "CKTEST",new SqlParameter("pid", 1));


这个是什么意思，存储过程？怎么有 select *

**Comment by 2881099** [comment]
var result = fsql.Ado.ExecuteDataTable(CommandType.Text, "SELECT * FROM DEMO");
var result = fsql.Ado.ExecuteDataSet(CommandType.Text, "SELECT * FROM DEMO");

这两种我刚才测试了，是有数据的。

Console.WriteLine(result.Rows.Count);

**Comment by haycun** [comment]
> fsql.Ado.Query(CommandType.StoredProcedure, "SELECT * FROM DEMO", "CKTEST",new SqlParameter("pid", 1));
> 
> 这个是什么意思，存储过程？怎么有 select *

写错了!



> var result = fsql.Ado.ExecuteDataTable(CommandType.Text, "SELECT * FROM DEMO");
> var result = fsql.Ado.ExecuteDataSet(CommandType.Text, "SELECT * FROM DEMO");
> 
> 这两种我刚才测试了，是有数据的。
> 
> Console.WriteLine(result.Rows.Count);


看了，确实是有数据，不过有一点没搞明白，为什么在VS2019中断点调试的时候，在预览中是空白的

![1](https://user-images.githubusercontent.com/11908366/107146869-b305ca00-6985-11eb-9515-e7c78b3dc394.png)
