### ISSUE TITLE
更新时出错

### ISSUE THREAD

**Issue by wujian777** [dotnetcore/FreeSql#682]
var repo = fsql.GetRepository<Topic>();
var item = new Topic { Id = 1 };
repo.Attach(item); //此时快照 item
item.Title = "newtitle";
repo.Update(item); //对比快照时的变化
使用此方式更新时，布尔型属性字段第一次能够更新，第二次不能更新，其它属性（包括枚举）的字段能够正常更新。

**Comment by 2881099** [comment]
完整的测试代码，和实体类，发出来一下
