### ISSUE TITLE
关于mysql的time和TimeSpan的问题

### ISSUE THREAD

**Issue by qtbui159** [dotnetcore/FreeSql#683]
有一个Timespan代表的是20:00:00，数据中有2个字段timeStar和timeEnd用的是time类型字段，然后用freesql生成的sql语句是这样的
`SELECT a.`timeStart`, a.`timeEnd`
FROM `testttt` a 
WHERE (a.`timeStart` <= 72000000000) AND (a.`timeEnd` >= 72000000000)`

但是查不出东西，后来搜了下 发现 20:00:00 转换为数字的话应该是200000才能在mysql中正确识别
`SELECT a.`timeStart`, a.`timeEnd`
FROM `testttt` a 
WHERE (a.`timeStart` <= 200000) AND (a.`timeEnd` >=200000)`
改成这样就能查出数据了

这个是bug吗？还是应该加什么attribute呀

**Comment by 2881099** [comment]
TimeSpan 是可能会有这个问题，不好处理。

建议用 long 代替 TimeSpan。

**Comment by densen2014** [comment]
> TimeSpan 是可能会有这个问题，不好处理。
> 
> 建议用 long 代替 TimeSpan。

我也遇到这个问题了, 应该怎么处理? 显示要正确的话, 字段定义还得是 public TimeSpan Hora { get; set; } 吧, 是要自己比对那里改成long吗
