### ISSUE TITLE
SqlServer的GetTablesByDatabase方法在库的排序规则为Chinese_PRC_CS_AS时报错“列名 'owner' 无效”

### ISSUE THREAD

**Issue by mumumi** [dotnetcore/FreeSql#684]
Chinese_PRC_CS_AS和默认排序规则Chinese_PRC_CI_AS主要区别是区分大小写

**Comment by 2881099** [comment]
是的，SQL大小写问题，等修复

**Comment by 2881099** [comment]
v2.3.0-preview20210209 (myget.org)

> 安装前添加源：https://www.myget.org/F/ncc/api/v3/index.json

- 修复 SqlServer 支持 Chinese_PRC_CS_AS 区分小大写；#684

2021年02月20日发布 v2.3.0 正式版本
