### ISSUE TITLE
请教：InnerJoin是否可以与一个内存表进行查询呢？

### ISSUE THREAD

**Issue by lfq24** [dotnetcore/FreeSql#685]
我已经有一个内存表：List<User>Users ;
我想通过Db.fsql.Select查询数据库后，再与 内存表Users 进行InnerJoin。因为我想使用FreeSQL中ToList()这个强大的映射功能。
但是没发现提供类似的功能：
List<A> test = Db.fsql.Select<Order>()
                .from(Users)
                .InnerJoin(。。。。)
//------------
目前我也在尝试通过下面方法解决，但没能实现像FreeSQL中ToList()这个强大的映射功能。不知道以后FreeSQL是否考虑增加上述功能？
List<A> test = Db.fsql.Select<Order>().toList();
test.join(Users , a=>a.Id,  b=>b.Id, new A{
 //这里需要写太多字段。没办法自动映射
})

**Comment by 2881099** [comment]
这个暂时做不了
