### ISSUE TITLE
建议增加AsTable过滤器功能

### ISSUE THREAD

**Issue by d4ilys** [dotnetcore/FreeSql#688]
叶老板您好。
**起因**：我们平台最初设计并不是支持多租户，也是采用DBFirst模式进行开发。
但是需求来了，平台需要支持多租户，我原本想采用数据库隔离租户，但是由于使用dotnetcore.cap分布式事务问题，无法实现。于是改为按表分离租户，CodeFirst开发模式，这样就会用到AsTable，但是我们的代码已经开发完成，每个方法都需要增加。
所以建议大佬增加AsTable过滤器功能。
这样多租户模式下，按表隔离变的轻松，就和按字段隔离一样，AOP实现维护更简单。
**想法**：在GlobalFilter增加ApplyAsTable的扩展方法。
db.GlobalFilter.ApplyAsTable<FreeSqlFilter>("AsTableFilter", (type, oldname) => $"{oldname}_TerantId");   //租户ID
这样每个CRUD表都会加上TerantId或者分表日期
能力有限，想法不正确请见谅~

**Comment by 2881099** [comment]
使用代码：

```c#
var builder = new FreeSqlBuilder().UseConnectionString(DataType.Sqlite, "data source=db1.db");
var fsql = new MyFreeSql(builder);
fsql.RegisterGlobalAsTable(typeof(Topic), () => $"topic_{asyncLocalTerantId.Value}");
fsql.RegisterGlobalAsTable(typeof(Categate), () => $"categate_{asyncLocalTerantId.Value}");
//...

//注入
services.AddSingleton<IFreeSql>(fsql);

fsql.Select<Topic>().ToSql();
```

> asyncLocalTerantId.Value 需要自己定义和控制值，它是 AsyncLocal<string> 类型

定义代码：

```c#
using FreeSql;
using FreeSql.Internal;
using FreeSql.Internal.CommonProvider;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace net50_webapi_global_astable
{
    public partial class MyFreeSql : IFreeSql
    {
        internal IFreeSql _orm;

        public MyFreeSql(FreeSqlBuilder builder)
        {
            _orm = builder.Build();
        }

        public IAdo Ado => _orm.Ado;
        public IAop Aop => _orm.Aop;
        public ICodeFirst CodeFirst => _orm.CodeFirst;
        public IDbFirst DbFirst => _orm.DbFirst;
        public GlobalFilter GlobalFilter => _orm.GlobalFilter;
        public void Dispose() => _orm.Dispose();

        public void Transaction(Action handler) => _orm.Transaction(handler);
        public void Transaction(IsolationLevel isolationLevel, Action handler) => _orm.Transaction(isolationLevel, handler);

        public ISelect<T1> Select<T1>() where T1 : class
        {
            return _orm.Select<T1>().AsTable((type, oldname) => GetTableName(type, oldname));
        }
        public ISelect<T1> Select<T1>(object dywhere) where T1 : class => Select<T1>().WhereDynamic(dywhere);

        public IDelete<T1> Delete<T1>() where T1 : class
        {
            var del = _orm.Delete<T1>();
            return del.AsTable(oldname => GetTableName((del as DeleteProvider<T1>)?._table.Type, oldname));
        }
        public IDelete<T1> Delete<T1>(object dywhere) where T1 : class => Delete<T1>().WhereDynamic(dywhere);

        public IUpdate<T1> Update<T1>() where T1 : class
        {
            var up = _orm.Update<T1>();
            return up.AsTable(oldname => GetTableName((up as UpdateProvider<T1>)?._table.Type, oldname));
        }
        public IUpdate<T1> Update<T1>(object dywhere) where T1 : class => Update<T1>().WhereDynamic(dywhere);

        public IInsert<T1> Insert<T1>() where T1 : class
        {
            var ins = _orm.Insert<T1>();
            return ins.AsTable(oldname => GetTableName((ins as InsertOrUpdateProvider<T1>)?._table.Type, oldname));
        }
        public IInsert<T1> Insert<T1>(T1 source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(T1[] source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(List<T1> source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(IEnumerable<T1> source) where T1 : class => Insert<T1>().AppendData(source);

        public IInsertOrUpdate<T1> InsertOrUpdate<T1>() where T1 : class
        {
            var insup = _orm.InsertOrUpdate<T1>();
            return insup.AsTable(oldname => GetTableName((insup as InsertOrUpdateProvider<T1>)?._table.Type, oldname));
        }

        internal string GetTableName(Type type, string oldname)
        {
            if (_globalAsTables.TryGetValue(type, out var list))
                foreach (var item in list)
                {
                    var newname = item?.Invoke();
                    if (string.IsNullOrEmpty(newname) == false) return newname;
                }
            return oldname;
        }
        internal readonly Dictionary<Type, List<Func<string>>> _globalAsTables = new Dictionary<Type, List<Func<string>>>();
        public void RegisterGlobalAsTable(Type type, Func<string> tableName)
        {
            if (_globalAsTables.TryGetValue(type, out var list) == false) _globalAsTables.Add(type, list = new List<Func<string>>());
            list.Add(tableName);
        }
    }

    public static class MyFreeSqlExtensions
    {
        public static ISelect<T1> DisableGlobalAsTable<T1>(this ISelect<T1> that)
        {
            var s0p = (that as Select0Provider);
            if (s0p != null) s0p._tableRules.Clear();
            return that;
        }
        public static IInsert<T1> DisableGlobalAsTable<T1>(this IInsert<T1> that) where T1 : class
        {
            var s0p = (that as InsertProvider<T1>);
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
        public static IUpdate<T1> DisableGlobalAsTable<T1>(this IUpdate<T1> that) where T1 : class
        {
            var s0p = (that as UpdateProvider<T1>);
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
        public static IDelete<T1> DisableGlobalAsTable<T1>(this IDelete<T1> that) where T1 : class
        {
            var s0p = (that as DeleteProvider<T1>);
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
        public static IInsertOrUpdate<T1> DisableGlobalAsTable<T1>(this IInsertOrUpdate<T1> that) where T1 : class
        {
            var s0p = (that as InsertOrUpdateProvider<T1>);
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
    }
}
```

**Comment by d4ilys** [comment]
感谢老大，真的给力，学习了~
做了一点修改，指定所有的表都加上相应的标识。
使用代码：
`
//租户ID，这样就全部的表都会加上"_1"
fsql.RegisterGlobalAsTable("_1");    `
`
using FreeSql;
using FreeSql.Internal;
using FreeSql.Internal.CommonProvider;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp25
{
    public partial class MyFreeSql : IFreeSql
    {
        internal IFreeSql _orm;

        public MyFreeSql(FreeSqlBuilder builder)
        {
            _orm = builder.Build();
        }

        public IAdo Ado => _orm.Ado;
        public IAop Aop => _orm.Aop;
        public ICodeFirst CodeFirst => _orm.CodeFirst;
        public IDbFirst DbFirst => _orm.DbFirst;
        public GlobalFilter GlobalFilter => _orm.GlobalFilter;
        public void Dispose() => _orm.Dispose();

        public void Transaction(Action handler) => _orm.Transaction(handler);
        public void Transaction(IsolationLevel isolationLevel, Action handler) => _orm.Transaction(isolationLevel, handler);

        public ISelect<T1> Select<T1>() where T1 : class
        {
            return _orm.Select<T1>().AsTable((type, oldname) => $"{oldname}{GetTableName()}");
        }
        public ISelect<T1> Select<T1>(object dywhere) where T1 : class => Select<T1>().WhereDynamic(dywhere);

        public IDelete<T1> Delete<T1>() where T1 : class
        {
            var del = _orm.Delete<T1>();
            return del.AsTable(oldname => $"{oldname}{GetTableName()}");
        }
        public IDelete<T1> Delete<T1>(object dywhere) where T1 : class => Delete<T1>().WhereDynamic(dywhere);

        public IUpdate<T1> Update<T1>() where T1 : class
        {
            var up = _orm.Update<T1>();
            return up.AsTable(oldname => $"{oldname}{GetTableName()}");
        }
        public IUpdate<T1> Update<T1>(object dywhere) where T1 : class => Update<T1>().WhereDynamic(dywhere);

        public IInsert<T1> Insert<T1>() where T1 : class
        {
            var ins = _orm.Insert<T1>();
            return ins.AsTable(oldname => $"{oldname}{GetTableName()}");
        }
        public IInsert<T1> Insert<T1>(T1 source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(T1[] source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(List<T1> source) where T1 : class => Insert<T1>().AppendData(source);
        public IInsert<T1> Insert<T1>(IEnumerable<T1> source) where T1 : class => Insert<T1>().AppendData(source);

        public IInsertOrUpdate<T1> InsertOrUpdate<T1>() where T1 : class
        {
            var insup = _orm.InsertOrUpdate<T1>();
            return insup.AsTable(oldname => $"{oldname}{GetTableName()}");
        }

        internal string GetTableName()
        {
            return tenementName;
        }

        internal string tenementName = string.Empty;
        public void RegisterGlobalAsTable(string tenement)
        {
            tenementName = tenement;
        }
    }

    public static class MyFreeSqlExtensions
    {
        public static ISelect<T1> DisableGlobalAsTable<T1>(this ISelect<T1> that)
        {
            var s0p = that as Select0Provider;
            if (s0p != null) s0p._tableRules.Clear();
            return that;
        }
        public static IInsert<T1> DisableGlobalAsTable<T1>(this IInsert<T1> that) where T1 : class
        {
            var s0p = that as InsertProvider<T1>;
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
        public static IUpdate<T1> DisableGlobalAsTable<T1>(this IUpdate<T1> that) where T1 : class
        {
            var s0p = that as UpdateProvider<T1>;
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
        public static IDelete<T1> DisableGlobalAsTable<T1>(this IDelete<T1> that) where T1 : class
        {
            var s0p = that as DeleteProvider<T1>;
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
        public static IInsertOrUpdate<T1> DisableGlobalAsTable<T1>(this IInsertOrUpdate<T1> that) where T1 : class
        {
            var s0p = that as InsertOrUpdateProvider<T1>;
            if (s0p != null) s0p._tableRule = null;
            return that;
        }
    }
}`
