### ISSUE TITLE
MySql的Enum类型字段查询问题

### ISSUE THREAD

**Issue by lclijingxuan** [dotnetcore/FreeSql#689]
环境：
1、Net Core 5.0
2、MySQL 8.0.23
3、FreeSql 2.0.105, FreeSql.Provider.MySqlConnector 2.0.105

代码
MySQL中定义了列Type类型int，NetCore中定义Type类型是枚举
查询时代码：Where(x => x.Type == instance.Type)
生成的SQL语句：WHERE (a.`Type` = 'xxx')

结果自然是查询不出来。

但是在SQLServer2008中上述代码生成的SQL语句没有问题，可以正常使用。

请问在MySQL中该问题如何解决？麻烦指点迷津。谢谢。

**Comment by 2881099** [comment]
https://github.com/dotnetcore/FreeSql/issues/75

**Comment by lclijingxuan** [comment]
统一将 enum 映射为 int

fsql.Aop.ConfigEntityProperty += (s, e) =>
{
    if (e.Property.PropertyType.IsEnum)
         e.ModifyResult.MapType = typeof(int);
};

注意：e.Property.PropertyType 有可能是 EnumStatus? 这种可空类型，请自行处理。

问题解决。
谢谢。
