### ISSUE TITLE
Aop.ConfigEntityProperty如何自定义属性指定字段长度

### ISSUE THREAD

**Issue by systemhejiyong** [dotnetcore/FreeSql#69]
Aop.ConfigEntityProperty代码：
```
freesql.Aop.ConfigEntityProperty = (s, e) =>
{
	if (e.Property.PropertyType == typeof(string))
	{
		var strLen = e.Property.GetCustomAttribute<System.ComponentModel.DataAnnotations.MaxLengthAttribute>();
		if (strLen != null && e.ModifyResult.DbType.IndexOf("(") == 0)
		{
			e.ModifyResult.DbType = e.ModifyResult.DbType + "(" + strLen.Length + ")";
		}
	}
};
```
实体属性：
```
[MaxLength(50)]
 public string UserName { get; set; }
```

代码中`e.ModifyResult.DbType`将会等于空，最终生成数据表就报语法错误了。
![image](https://user-images.githubusercontent.com/1458065/60757693-60915880-a040-11e9-8194-28d3783280bf.png)

生成的脚本中有两个问题一个是无类型，一个是表名多出了一个`_FreeSqlTmp_`
![image](https://user-images.githubusercontent.com/1458065/60757751-24aac300-a041-11e9-9727-b3d9b86d5bca.png)

**Comment by 2881099** [comment]
类型此时为空，所以都变成了(数字)

_FreeSqlTmp_ 是正常的，结构变化后，创建临时表，导入数据后，删除旧表，然后再把他的名改回旧表的名字

**Comment by 2881099** [comment]
```
freesql.Aop.ConfigEntityProperty = (s, e) =>
{
	if (e.Property.PropertyType == typeof(string))
	{
		var strLen = e.Property.GetCustomAttribute<System.ComponentModel.DataAnnotations.MaxLengthAttribute>();
		if (strLen != null)
		{
			e.ModifyResult.DbType = freesql.CodeFirst.GetDbInfo(e.Property.PropertyType)?.dbtype + "(" + strLen.Length + ")";
		}
	}
};
```

改成这样试试

**Comment by systemhejiyong** [comment]
这样可以，现在不知道为什么有一个类的一直没有设置长度成功。
![image](https://user-images.githubusercontent.com/1458065/60771237-889fbb00-a117-11e9-948d-f95afd82207e.png)

![image](https://user-images.githubusercontent.com/1458065/60771235-7887db80-a117-11e9-8839-6926ce77cc64.png)

**Comment by 2881099** [comment]
断点看了没

**Comment by 2881099** [comment]
把断点打在 Aop.ConfigEntityProperty 里面调一下看看，是不是特性名不对，用了其他空间的？

**Comment by 2881099** [comment]
又是不是可能其他地方配置了 FluentAPI，有优先级

优先级
数据库特性 > 实体特性 > FluantApi（配置特性） > Aop（配置特性）

**Comment by systemhejiyong** [comment]
已经可以了， 忘记当用到SysRole这个实体的时候，才会去执行修改表。

**Comment by pjy612** [comment]
囧 为啥不直接 在 ModifyResult 里面 加个 int? Length 的属性？

**Comment by 2881099** [comment]
v0.9.12

增加 MaxLength 特性的解析，实体字符串长度设置；

```csharp
class Topic {
    [MaxLength(128)]
    public string Title { get; set; }
}
```

MaxLength 可以是任何命令空间下的特性

**Comment by pjy612** [comment]
```
e.ModifyResult.DbType = freesql.CodeFirst.GetDbInfo(e.Property.PropertyType)?.dbtype + "(" + strLen.Length + ")";
```
这段 要是能整合到 一个 属性里面 是不是更好 避免出错？ 在Aop处理也直观一些
