### ISSUE TITLE
ExecutePgCopyAsync执行报错问题

### ISSUE THREAD

**Issue by arcchen** [dotnetcore/FreeSql#693]
await  oInsert.AppendData(items).ExecutePgCopyAsync();
请教ExecutePgCopyAsync 执行报一下错误问题：
System.MissingMethodException:“Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.”

**Comment by 2881099** [comment]
检查 npgsql 版本，是否有提示的这个方法，建议新建一个 demo 小项目测试，注意 npgsql.dll 版本

**Comment by luoyunchong** [comment]
请问该问题是否解决。
https://github.com/dotnetcore/FreeSql/issues/783 
是不是可能和这个问题一样。。在.net core 3.1上就不行。缺少方法。

**Comment by 2881099** [comment]
如果有必要，请单独安装升级 npgsql.dll 到最新版本
