### ISSUE TITLE
Exception信息 国际化

### ISSUE THREAD

**Issue by VShawn** [dotnetcore/FreeSql#694]
当前版本发生异常时，会抛出中文异常信息，当我们对接国际客户时，客户就会产生疑问：他们看不懂中文，于是就要求换成他们能看懂的错误输出。

例如：

https://github.com/dotnetcore/FreeSql/blob/c12c5523525818abaa05b03d2dfd6ae70b6e7964/Providers/FreeSql.Provider.Sqlite/SqliteAdo/SqliteConnectionPool.cs#L193

因此我建议在今后的版本中考虑到国际化的需求。

**Comment by 2881099** [comment]
需求暂时先记下，谢谢反馈

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/issues/1155#issuecomment-1153837889
- v3.2.663 support provider、Extensions Exceptions 多语言
