### ISSUE TITLE
关于IncludeMany后then使用asTable表名的sql错误

### ISSUE THREAD

**Issue by pigwing** [dotnetcore/FreeSql#696]
主库数据库出错（执行SQL）〓〓〓〓〓〓〓〓〓〓〓〓〓〓〓
SELECT  * from (SELECT a."Id", a."ProjectId",
FROM "DeviceEntity" a 
WHERE ((a."ProjectId") in (1))) ftb
 
UNION ALL
 
SELECT  * from (SELECT a."Id", a."ProjectId", 
FROM "1_Device" a 
WHERE ((a."ProjectId") in (1))) ftb
42P01: relation "DeviceEntity" does not exist

在then中使用了AsTable把DeviceEntity的类名通过AsTable改为1_Device的分表名字,但是SQL中,UNION ALL后面的FROM表名是正确的但是前面的依然是DeviceEntity

**Comment by 2881099** [comment]
freesql 查询代码怎么写的？

**Comment by pigwing** [comment]
projectReposiory.Where(e=>e.Id == 1).IncludeMany(e=>e.ProjectId, then=>{then.AsTable("1_Device")})

**Comment by pjy612** [comment]
@2881099 
大佬 wiki 里面 分库分表 里面的 AsTable 使用方法。
里面的 type 作用 没说清楚，能抽空完善一下吗？
如果 多个 
AsTable 后 又追加了 Join 的话 
Select<A>()
.AsTable((t,oldname)=>"a_1")
.AsTable((t,oldname)=>"a_2")
.AsTable((t,oldname)=>"a_3")
.LeftJoin<B>((a,b)=>a.id==b.aid)

这种 后面 SQL 中 B的表名也会变，需要 判断 type 。。。
AsTable((t,oldname)=> t==typeof(A)? "a_3":oldname)

**Comment by 2881099** [comment]
@pjy612 是的，内部判断，目前是这样做的

**Comment by pjy612** [comment]
> @pjy612 是的，内部判断，目前是这样做的

@2881099  没，就是希望大佬对于 这种 分表和 Join 结合使用的情况。
在原生或仓储的使用不同上，能在 wiki 上面 提一下可以这么用，不然 不多摸索下 可能 会不知道要这么用。
