### ISSUE TITLE
where 中的条件判断怎么用？

### ISSUE THREAD

**Issue by huafeis** [dotnetcore/FreeSql#697]
return fsSql.Select<Acs_card>()
              .Where(a => a.card_uid == uid)
              .ToList();
当uid为空的话，该条件无效，怎么用啊?

**Comment by 2881099** [comment]
.Whereaif(uid != null, a => a.card_uid == uid)

**Comment by huafeis** [comment]
> .Whereaif(uid != null, a => a.card_uid == uid)

谢了~
