### ISSUE TITLE
ManyToMany条件的问题

### ISSUE THREAD

**Issue by j4587698** [dotnetcore/FreeSql#698]
ManyToMany能作为查询条件吗？以wifi中song, tag来举例的话
如果用then只影响Tag的数量，Song的数量不会变？
如果用Tag去查询Song，分页用skip take做好像没法获取到count？
where中用any好像也不行，因为where的时候IncludeMany还没有执行，是null。
还有其他的办法可以根据Tag来查询Song，并且支持分页吗？

**Comment by 2881099** [comment]
可以作为条件查询的

https://www.cnblogs.com/kellynic/p/13575053.html
《导航属性【到底】可以解决什么问题？》

文中第6节有提到多对多查询，根据 tag 查询 topic

```c#
fsql.Select<Topic>()
   .Where(a => a.Tags.AsSelect().Any(b => b.name = "c#"))
   .ToList();
```

**Comment by j4587698** [comment]
@2881099 好的，谢谢。建议把这些对应的文章地址放到wiki里，我在wiki里没找到才问的，没有发现对应的cnblog地址

**Comment by 2881099** [comment]
> @2881099 好的，谢谢。建议把这些对应的文章地址放到wiki里，我在wiki里没找到才问的，没有发现对应的cnblog地址

这篇文章，wiki 里面有链接，在导航关系配置里面
