### ISSUE TITLE
oracle升级0.1.1后的新问题

### ISSUE THREAD

**Issue by jetydu** [dotnetcore/FreeSql#7]
List<Topic> t1 = context.fsql.Select<Topic>().Where(a => a.Id > 0).ToList();
执行这个的时候，报Oracle.ManagedDataAccess.Client.OracleException:“ORA-00955: 名称已由现有对象使用
ORA-06512: 在 line 4”
应该是UseAutoSyncStructure验证有错

**Comment by 2881099** [comment]
是的，我前面提到了关闭 QuoteSqlName 会发生的问题。

如果是老项目，不依靠 freesql 迁移，可以关掉 UseAutoSyncStructure 功能；
如果是新项目，可以切换到新的数据库中，UseAutoSyncStructure 功能开启重新同步；

我的建议：如果是新项目，我倒是建议不要关 QuoteSqlName，多录入一对引号没什么成本，保留原名称而不是转换名称为大写。

我也寻求过其他人建议，他们说使用oracle一般不会加引号，哈哈。

**Comment by 2881099** [comment]
刚才去掉双引号，运行单元测试时候出现的错误：

1、自增序列名也找不见了，由于之前是加双引号的；
2、CodeFirst迁移脚本执行出错（这项有些伤，可能是测试的名称与oracle自有的冲突）；
。。。后面发现错误再整理进来

**Comment by 2881099** [comment]
UseQuoteSqlName(false) 应该是留给老项目，没有强制使用引号的时候使用的。
