### ISSUE TITLE
当表中加入JsonMap的字段,使用LeftJoin会触发异常

### ISSUE THREAD

**Issue by pigwing** [dotnetcore/FreeSql#700]
当表中有JsonMap的字段时候,经过测试,IncludeMany不会触发异常,但是使用LeftJoin查询后.会触发Value cannot be null. (Parameter 'method')
```
class B {
   public long Id{get;set;}
}

class A {
   [JsonMap]
   public Dictionary<string, object> Map {get;set}
   public long BId{get;set;}
   public B B {get;set;}
}
```
类似: ``freesql.Select<A>().LeftJoin(e => e.B.Id == e.BId).ToListAsync();``
会触发``Value cannot be null. (Parameter 'method')``

**Comment by luoyunchong** [comment]
写个demo出来。

或者用Extra 来替换Dictionary<string, object>，再试下。

```
    public class Extra : Dictionary<string, object>
    {

    }
```

**Comment by 2881099** [comment]
我用1楼的代码测试，没有发生错误。

**Comment by pigwing** [comment]
@2881099 发生在postgresql的数据库上

**Comment by pigwing** [comment]
目前我的解决方式是ToListAsync内的callbak函数手动赋值,那就不会触发Value cannot be null. (Parameter 'method'),不然直接ToListAsync,freesql对JsonMap字段自动赋值的时候就会触发以上异常,强调一下,我是用**postgresql**

**Comment by pigwing** [comment]
原来是我includeMany的时候,是手动筛选字段查询的 ,也就等于上面的手动赋值,所以没触发异常

**Comment by pigwing** [comment]
是跟这个issues一致的 [https://github.com/dotnetcore/FreeSql/issues/996](url) 
[https://github.com/dotnetcore/FreeSql/commit/3a453d918dd7a3742df82c3240aa3dbbe20ef2e5](url) 已修复
