### ISSUE TITLE
子查询IN开启参数化的BUG

### ISSUE THREAD

**Issue by wangxiwangque** [dotnetcore/FreeSql#701]
![image](https://user-images.githubusercontent.com/37373632/108960871-8b1aa400-76b1-11eb-9509-3188989821fb.png)
2021-02-24 14:20:32,329 DEBUG InfoLogger - 【SQL】SELECT count(1) as1 
FROM "ACCESS_RECORD" a 
WHERE (trunc(a."CREATE_DATE") >= trunc(:exp_0)) AND (trunc(a."CREATE_DATE") < trunc(:exp_1)) AND (((a."ACCESS_HOSPITAL_CODE") in (SELECT b."HOSPITAL_CODE" 
    FROM "HOSPITAL" b 
    WHERE (b."HOSPITAL_PROVINCE" = :exp_0) AND (b."HOSPITAL_CITY" = :exp_1))))
2021-02-24 14:20:32,350 DEBUG InfoLogger - 【参数】{":exp_0":"2021-02-23T00:00:00",":exp_1":"2021-02-24T00:00:00"}
参数化的时候，子表IN的时候，子表的查询参数无法被正确使用

**Comment by 2881099** [comment]
收到，是最新版本吗？

**Comment by wangxiwangque** [comment]
> 收到，是最新版本吗？

是的 2.3.100

**Comment by 2881099** [comment]
前几天在外地手机上没仔细看，问题确实存在。

原因：两个独立的 ISelect 同时产生了相同的 exp_0，下标。

解决办法：

```c#
//上述代码不变

var select = _repository.Orm.Select<AccessRecord>();
(select as Select0Provider)._params = (select1 as Select0Provider)._params;

select.WhereIf(....).WhereIf(...).Where(...);
```

**Comment by 2881099** [comment]
FreeSql 是每步解析，所以有这个缺点。

**Comment by 2881099** [comment]
临时方案，定义扩展方法：

```c#
var select = _repository.Orm.Select<AccessRecord>().ShareParameter(select1)
    .WhereIf(....).WhereIf(...).Where(...);


public static ISelect<T> ShareParameter<T>(this ISelect<T> select, object selectSource) where T : class
{
    var parms = (selectSource as Select0Provider)?._params;
    if (parms != null) (select as Select0Provider)._params = parms;
    return select;
}
```

**Comment by wangxiwangque** [comment]
谢谢 明天学习的时候 我来试一下
