### ISSUE TITLE
reponsitory在insert的时候的bug

### ISSUE THREAD

**Issue by tiger-wwz** [dotnetcore/FreeSql#702]
如果我给这个reponsitory添加了一个datafilter并且里面表达式树中使用了Array.Contains方法，那么在插入的时候就会报空指针异常。
![image](https://user-images.githubusercontent.com/18282682/109098661-a8f11300-775c-11eb-9ceb-1bd3209ffda6.png)

**Comment by tiger-wwz** [comment]
现在我就只能在每次插入的时候禁用datafilter。
![image](https://user-images.githubusercontent.com/18282682/109101441-a7761980-7761-11eb-8fb8-61e9dac02779.png)

**Comment by 2881099** [comment]
datafilter 尽量不依赖外部变量为 null 的操作、也不要使用导航属性。
