### ISSUE TITLE
关于导航属性的问题

### ISSUE THREAD

**Issue by tiger-wwz** [dotnetcore/FreeSql#704]
[代码样例](https://github.com/dotnetcore/FreeSql/files/6046968/ConsoleApp1.zip)
1.insert的时候如果datafilter里面使用了导航属性，则会报错
2.select的导航属性生效但是update和delete报错
3.Array.contains方法里面无法使用导航属性

**Comment by 2881099** [comment]
1. 为什么insert的时候回去执行datafilter的逻辑呢？

这个早期加入的机制，会进行数据验证。文档：https://github.com/dotnetcore/FreeSql/wiki/Repository#%E8%BF%87%E6%BB%A4%E4%B8%8E%E9%AA%8C%E8%AF%81

---

2.  为什么查询的时候datafilter导航可以，但是update和delete不行呢 

查询很容易支持多表查询，导航属性会自动产生多表查询，导航属性此时是：已知条件。

update/delete 多表关联操作危险，默认不支持，导航属性此时是：未知条件。

---

3. 还有一个就是contains的问题,无法使用导航属性

这个我测试下来是正常的。

```c#
var ids = new long[] { 1 };
var sql1 = userrep.Select.Where(g => ids.Contains(g.TeamID)).ToSql();
var sql2 =userrep.Select.Where(g => ids.Contains(g.Team.ID)).ToSql();
```

sql1:

```sql
SELECT a."ID", a."Name", a."TeamID" 
FROM "user" a 
WHERE (((a."TeamID") in (1)))
```

sql2:
SELECT a."ID", a."Name", a__Team."ID" as3, a__Team."Name" as4, a."TeamID" 
FROM "user" a 
LEFT JOIN "Team" a__Team ON a__Team."ID" = a."TeamID" 
WHERE (((a__Team."ID") in (1)))
```sql

```
