### ISSUE TITLE
pg 视图和表左连接 生成的语法有错误

### ISSUE THREAD

**Issue by zengpengkindle** [dotnetcore/FreeSql#705]
freeSql1.Select<View, BookCard>()
                     .LeftJoin((a, b) => a.WypIdcard == b.key)
                         .Where((a, b) => string.IsNullOrEmpty(b.key)).Take(takeDataNumber）

生成的sql语句是 select * from view ,bookcard  条件也缺失了

**Comment by 2881099** [comment]
视图和表，在 ORM 层面看是一样的。

这种问题不大可能出现，有再次确认是 bug 吗？重现的话麻烦提供 demo
