### ISSUE TITLE
这样写，在事务tran提交前，会不会对model对应表中查询到的资料加行锁？

### ISSUE THREAD

**Issue by FighterLuo** [dotnetcore/FreeSql#707]
var c =await _freesql.select<model>().WithTransaction(tran).ToList();
这样写，在事务tran提交前，会不会对model对应表中查询到的资料加行锁？其他人无法修改？

**Comment by 2881099** [comment]
这样写不会锁住查询的记录。

for update 使用过没有，这个可以锁住查询的行，待事务提交才释放。

第一步：了解 for update

第二步：了解 for update 事务

第三步：使用 FreeSql .Select\<T\>().WithTransaction(tran).ForUpdate().ToList();
