### ISSUE TITLE
关于WhereDynamicFilter的建议

### ISSUE THREAD

**Issue by LostAsk** [dotnetcore/FreeSql#708]
如果动态参数value是表的字段，该如何定义，这样的意义前端通过type名称，动态反射进行多表查询，筛选，甚至select自定义字段， 可以实现前端动态条件更灵活
![S3U%IB~)J0RJ{3V$L4Q$2WG](https://user-images.githubusercontent.com/46678241/109406699-311e2500-79b6-11eb-88e9-f6c8eb046386.png)

这个是测试文件
[ss.txt](https://github.com/dotnetcore/FreeSql/files/6056227/ss.txt)

**Comment by 2881099** [comment]
暂时想到的缺点，可能有数据安全问题。

万一 Value 输入的不是 a.TopicId，是 a.UserId（真实存在），那查询返回的结果可能不符合预期。

期待更多人加入进来讨论。

**Comment by LostAsk** [comment]
> 暂时想到的缺点，可能有数据安全问题。
> 
> 万一值输入的不是a.TopicId，是a.UserId（真实存在），那查询返回的结果可能不符合预期。
> 
> 期待更多人加入进来讨论。

![image](https://user-images.githubusercontent.com/46678241/109412632-08ad1f80-79e4-11eb-8e8e-2b8fc69fb4a7.png)

**Comment by mansai** [comment]
安全问题，可以通过参数设置来控制，或者dto来控制，dto里没有userid字段，也不会有安全问题。sqlsugar是支持别名的传参的，建议增加此功能。
