### ISSUE TITLE
Repository.Update(List<Data>) 更新集合数据的奇怪问题

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#709]
FreeSql版本：2.3.100
数据库：Ms SqlServer 2012
FrameWork :  dot net FrameWork 4.0 

List集合共有七条数据，更新第五条（下标4）时，失败。

完整Demo代码：

    class Program
    {
        static void Main(string[] args)
        {
            var free = new FreeSql.FreeSqlBuilder();
            free.UseConnectionString(FreeSql.DataType.SqlServer, "Data Source=lSer;Initial Catalog=Platform;User ID=sa;PassWord=999999;Min Pool Size=100");
            free.UseAutoSyncStructure(true);
            
            var freeSql = free.Build();
                 List<Data> list = new List<Data>() { };
            var rep = freeSql.GetRepository<Data>(t => t.DepNo == 1);
            if (!rep.Select.Any())
            {
                for (var i = 0; i < 7; i++)
                {
                    list.Add(new Data { DepNo = 1, Name = "Name" + (i + 1) });
                }
                rep.Insert(list);
            }
           
                list = rep.Select.ToList();
           
            // 每次只更新下面其中一个
            list[3].Name = "Modify4";//updated =1 ,更新成功
                                     // list[4].Name = "Modify5";//updated=0，没有更新，失败
                                     // list[5].Name = "Modify6";//updated=6，更新成功

            var updated = rep.Update(list);
        }

        class Data
        {
            [Column(IsIdentity =true)]
            public int Id { get; set; }
            public int DepNo { get; set; }
            public string Name { get; set; }
        }
    }//2.3.100

list[4].Name = "Modify5";//updated=0，没有更新，失败 。只有这一句时，更新失败

**Comment by densen2014** [comment]
加主键
    [Column(IsIdentity = true, IsPrimary = true)]
    public int Id { get; set; }

**Comment by 2881099** [comment]
```sql
UPDATE [Data] SET [Name] = CASE [Id]
WHEN 4 THEN N'Modify4'
WHEN 5 THEN N'Modify5'
WHEN 6 THEN N'Modify6' END
WHERE ([Id] IN (4,5,6)) AND ([DepNo] = 1)
```

我测试执行 var updated = rep.Update(list); 得到的 SQL 是上面的，是正常的

**Comment by 2881099** [comment]
```c#
list[3].Name = "Modify4";//updated =1 ,更新成功
// list[4].Name = "Modify5";//updated=0，没有更新
// list[5].Name = "Modify6";//updated=6，更新成功

var updated = rep.Update(list);
```

如果这样执行，是没有反应，因为 list[3].Name 值本身就是 "Modify4"

**Comment by sqlite-me** [comment]
![image](https://user-images.githubusercontent.com/23652113/110058446-47a0f380-7d9d-11eb-9b47-51d1027fae37.png)
上面是数据库的值

**Comment by 2881099** [comment]
> ![image](https://user-images.githubusercontent.com/23652113/110058446-47a0f380-7d9d-11eb-9b47-51d1027fae37.png)
> 上面是数据库的值

测试你发的代码没有发现问题

**Comment by sqlite-me** [comment]
> 加主键
> [Column(IsIdentity = true, IsPrimary = true)]
> public int Id { get; set; }

加上也一样

**Comment by sqlite-me** [comment]
> ```cs
> list[3].Name = "Modify4";//updated =1 ,更新成功
> //list[4].Name = "Modify5";//updated=0，没有更新
> //list[5].Name = "Modify6";//updated=6，更新成功
> 
> var updated = rep.Update(list);
> ```
> 
> 如果这样执行，是没有反应，因为 list[3].Name 值本身就是 "Modify4"

list[4].Name = "Modify5";//updated=0，只有这一句时，更新失败，把数据改一下，也一样，其它的都正常

**Comment by 2881099** [comment]
> > ```cs
> > list[3].Name = "Modify4";//updated =1 ,更新成功
> > //list[4].Name = "Modify5";//updated=0，没有更新
> > //list[5].Name = "Modify6";//updated=6，更新成功
> > 
> > var updated = rep.Update(list);
> > ```
> > 
> > 
> > 如果这样执行，是没有反应，因为 list[3].Name 值本身就是 "Modify4"
> 
> list[4].Name = "Modify5";//updated=0，只有这一句时，更新失败，把数据改一下，也一样，其它的都正常

因为数据库 list[4].Name 值也是 "Modify5" 啊

**Comment by 2881099** [comment]
你是不是在外部修改了数据库的值，想 rep.Update(list); 也能更新？

我这边测不出你说的问题。

**Comment by sqlite-me** [comment]
> 你是不是在外部修改了数据库的值，想 rep.Update(list); 也能更新？
> 
> 我这边测不出你说的问题。

![image](https://user-images.githubusercontent.com/23652113/110127075-21606f80-7e00-11eb-8c3f-385a83914b19.png)
        static void Main(string[] args)
        {
            var free = new FreeSql.FreeSqlBuilder();
            free.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=test.db");
            free.UseAutoSyncStructure(true);

            var freeSql = free.Build();
            List<Data> list = new List<Data>() ;
            var rep = freeSql.GetRepository<Data>(t => t.DepNo == 1);
            if (!rep.Select.Any())            {
                for (var i = 0; i < 7; i++)
                    list.Add(new Data { DepNo = 1, Name = "Name" + (i + 1) });
                rep.Insert(list);
            }

            list = rep.Select.ToList();
            Console.WriteLine("before update:"+list[4].Name);
            list[4].Name = "Modify5";//updated=0，没有更新，失败
            Console.WriteLine("set new value:" + list[4].Name);
            Console.WriteLine("update Count:"+rep.Update(list));
            list = rep.Select.ToList();
            Console.WriteLine("reloaded:" + list[4].Name);
            Console.ReadLine();
        }
    }
    class Data
    {
        [Column(IsIdentity = true,IsPrimary =true)]
        public int Id { get; set; }
        public int DepNo { get; set; }
        public string Name { get; set; }
    }
![image](https://user-images.githubusercontent.com/23652113/110127182-48b73c80-7e00-11eb-8eaf-9005fb7aa2a7.png)

没有改过数据

**Comment by sqlite-me** [comment]
我在家用sqlite数据库又测了一遍，也一样
只有下标为4的不能更新

**Comment by 2881099** [comment]
重新测试了，确实是 bug，稍后会发布版本解决

**Comment by 2881099** [comment]
v2.3.200 版本已发布解决这个问题
