### ISSUE TITLE
达梦数据库group by 分页 问题

### ISSUE THREAD

**Issue by kamikyo** [dotnetcore/FreeSql#710]
大佬，如何做goup by之后再分页？目前将group和page两个混用时，生成的sql会是这样:
select a,b,c,rownum as '_rownum_' from t where...group by a,b,c。这时group by会出错，因为有一个rownum列没包含进去。如果手动补上的话，原本想要的group by也有失去了意义（因为每行的rownum肯定是不一样的）

issues里还有另外两个同类问题，但都是使用的sqlserver，所以没有参考性
达梦数据库生成的列长这样：
![image](https://user-images.githubusercontent.com/7645337/109951697-fb13d480-7d18-11eb-8036-e589dffb949a.png)

**Comment by 2881099** [comment]
收到，生成时判断了数据库类型，多嵌套了一层处理。
