### ISSUE TITLE
查询条件带子查询，且子查询中有分组，要如何去实现？

### ISSUE THREAD

**Issue by axinno1** [dotnetcore/FreeSql#713]
select * from DayProfit dp where dp.[Time] in(SELECT  MAX([Time])
FROM    DayProfit temp
WHERE   temp.[Time] > DATEADD(Day, -30, dateadd(ms, 0, DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)))
GROUP BY [Day])
order by dp.Time

**Comment by 2881099** [comment]
(SELECT MAX([Time])
FROM DayProfit temp
WHERE temp.[Time] > DATEADD(Day, -30, dateadd(ms, 0, DATEADD(dd, DATEDIFF(dd, 0, getdate()), 0)))
GROUP BY [Day])

1、上面这段是可以用 ISelect.ToSql() 得到的

2、其他交给 Where(sql)
