### ISSUE TITLE
在Oracle数据库中，FreeSql支持根据实体类生成区分大小写的table和字段名称吗？

### ISSUE THREAD

**Issue by xiaoxiongcn** [dotnetcore/FreeSql#716]
![image](https://user-images.githubusercontent.com/61345559/110411841-32da9d80-80c6-11eb-8c08-5e1ad42f5c75.png)
类似图上这种，在Oracle数据库中，FreeSql支持根据实体类生成区分大小写的table和字段名称吗？

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/wiki/API

- UseNameConvert 可指定
