### ISSUE TITLE
使用SqlExt.Count抛出错误

### ISSUE THREAD

**Issue by kugarliyifan** [dotnetcore/FreeSql#717]
想要实现的效果sql:
select sum(Amount) as TotalAmount,count(1) as TotalCount from xxx where State=1

C#代码是:
![image](https://user-images.githubusercontent.com/18448413/110414576-0e34f480-80cb-11eb-931c-c1357325aa50.png)

在SqlExt.Count()上抛出错误:
`
SqlException: count 函数要求有 1 个参数。
Microsoft.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__188_0(Task<SqlDataReader> result)

Exception: count 函数要求有 1 个参数。
FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool<DbConnection> pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, bool isThrowException)
`

查看了源代码SqlExt.Count()的代码为:
`SqlExtExtensions.Over<long>("count()")`

少了传入列或者固定值

**Comment by 2881099** [comment]
ToAggerate(g=> new {
sum1 = g.Sum(g.Key.Amount),
cou1 = g....
})

**Comment by 2881099** [comment]
SqlExt.Count 是给开创函数用的，不一样

**Comment by kugarliyifan** [comment]
弱弱的问一下,,为啥g.Sum(),,如果传入的列是int类型的,,输出却是decimal的....

**Comment by 2881099** [comment]
防溢出
