### ISSUE TITLE
Dameng查询可空guid数据出错

### ISSUE THREAD

**Issue by WilsonHung** [dotnetcore/FreeSql#719]
public class CTestDm {
        [Column(IsIdentity = true, IsPrimary = true)]
        public int ID { get; set; }
        public string User { get; set; }
        public Guid? guid { get; set; }
        public DateTime CreateTime { get; set; }
 }
//使用codefisrt,guid 映射为 char(36)
//插入可空guid没有问题
//插入后查询报错，测试了sqlite(character(36))是没有问题的
            var us = new CTestDm();
            us.User = "hws";
            us.CreateTime = DateTime.Now;
            //Guid为空，不赋值
            _fs.Insert(us).ExecuteAffrows();
            //赋值成功，查询返回错误
            var kk = _fs.Select<CTestDm>().ToList();

错误如下：
FormatException: Unrecognized Guid format.
System.Guid+GuidResult.SetFailure(bool overflow, string failureMessageID)

Exception: Unrecognized Guid format.
FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool<DbConnection> pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, bool isThrowException)

**Comment by 2881099** [comment]
freesql 用的哪个版本，数据库表值是 null ？还是有值但不符合 Guid 格式？

**Comment by WilsonHung** [comment]
freesql使用的2.3.200；net 5.0 mvc模板
dameng使用v8(链接：https://pan.baidu.com/s/1rKt0kvhXveanBz0jfQPSiA 
提取码：oaak)
使用的codefirst建表

提交的示例代码就是模拟数据库表为空的情况：
        var us = new CTestDm();
        us.User = "hws";
        us.CreateTime = DateTime.Now;
        //Guid为空，不赋值
        _fs.Insert(us).ExecuteAffrows();
        //赋值成功，查询返回错误
        var kk = _fs.Select<CTestDm>().ToList();

**Comment by WilsonHung** [comment]
我刚刚又测试了一下，应该是插入数据有问题，
我使用dameng自己的工具插入数据，为空时，数据表值显示"NULL",
但是使用:
var us = new CTestDm();
      us.User = "hws";
      us.CreateTime = DateTime.Now;
      //Guid为空，不赋值为null
      _fs.Insert(us).ExecuteAffrows();
插入后，在数据管理工具看到的是“空”字符串
![Uploading Image 1.png…]()

**Comment by 2881099** [comment]
是不是设置了 Aop.AuditValue 事件，检查一下

正常如果实体类定义的主键特性，是 Guid 写入不会是空字符串

**Comment by WilsonHung** [comment]
我刚刚又测试了一下，应该是插入数据有问题，
我使用dameng自己的工具插入数据，为空时，数据表值显示"NULL",
但是使用:
var us = new CTestDm();
us.User = "hws";
us.CreateTime = DateTime.Now;
//Guid为空，不赋值为null
_fs.Insert(us).ExecuteAffrows();
插入后，在数据管理工具看到的是“空”字符串（“\0”？）。

![Image 1](https://user-images.githubusercontent.com/32768851/110897178-ef876580-8337-11eb-924f-4ec7cf87eafc.png)

**Comment by WilsonHung** [comment]
这是个历史遗留问题，guid不是主键，是个可空字段； 
同时程序没有设置Aop.AuditValue 事件

**Comment by 2881099** [comment]
guid 实体类属性怎么定义的

这样试试

public Guid? GuidField { get; set; }

**Comment by WilsonHung** [comment]
之前类就是如上定义的，插入的还是空字符串，您可以自己试一下？

    public class CTestDm
    {
        [Column(IsIdentity = true, IsPrimary = true)]
        public int ID { get; set; }
        public string User { get; set; }

        public Guid? guid { get; set; }

        public Guid? GuidField { get; set; }

        public DateTime CreateTime { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            var _fs = new FreeSqlBuilder().UseConnectionString(DataType.Dameng,
                    "DamengConnectStr“)
                    .UseAutoSyncStructure(true).Build();

            var us = new CTestDm();
            us.User = "hws";
            us.CreateTime = DateTime.Now;
            us.guid = null;
            _fs.Insert(us).ExecuteAffrows();

            var kk = _fs.Select<CTestDm>().ToList();
            Console.WriteLine("Hello World!");
        }
    }
