### ISSUE TITLE
父子关系查询，查询不出父类的问题

### ISSUE THREAD

**Issue by iisp** [dotnetcore/FreeSql#720]
实体类
        /// <summary>
        /// 父级ID
        /// </summary>
        public long ParentId { get; set; }

        /// <summary>
        /// 父级
        /// </summary>
        [Navigate(nameof(ParentId))]
        public CategoryEntity Parent { get; set; }

查询时， var list = await _CategoryRepository.Select
            .Include(a => a.Parent)，查询出来的结果，a.Parent 是null值，请问这有是什么问题呢

**Comment by 2881099** [comment]
监视 SQL
