### ISSUE TITLE
分区函数

### ISSUE THREAD

**Issue by KindergartenKiller2009** [dotnetcore/FreeSql#725]
是不是只能通过SQL语句进行分区?有没有自带的方法?

**Comment by hd2y** [comment]
参考 #731

参考：https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Extensions/FreeSqlGlobalExpressionCallExtensions.cs

分区函数懵了一下，应该是指开窗函数吧：`.. over([partition by ..] order by ...)` 这种。
