### ISSUE TITLE
MySQL数据库是否不支持ExecuteDeleted方法?

### ISSUE THREAD

**Issue by bighamx** [dotnetcore/FreeSql#726]
使用该方法删除数据会报错  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RETURNING `ID` as `ID`....
但是使用ExecuteAffrows来删除则可以成功

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/112616259-7838f200-8e5e-11eb-9ef5-f501b2f2bf8a.png)

https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Interface/Curd/IDelete.cs

**Comment by bighamx** [comment]
> ![image](https://user-images.githubusercontent.com/18613266/112616259-7838f200-8e5e-11eb-9ef5-f501b2f2bf8a.png)
> 
> https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Interface/Curd/IDelete.cs

谢谢 我没怎么看文档😅

**Comment by bighamx** [comment]
.
