### ISSUE TITLE
使用 FreeSql，连接阿里云 mysql  RDS ，间歇性出现 【主库】状态不可用，等待后台检查程序恢复方可使用

### ISSUE THREAD

**Issue by coderdp** [dotnetcore/FreeSql#728]
版本：2.0.105.0，mysql 数据库连接字符串已配置：Connection Lifetime=20;
注入：
`.AddSingleton<AmcService>()`
使用方式如下：
`
异常信息：
Unable to connect to any of the specified MySQL hosts.","Data":null,"InnerException":{"ClassName":"System.Exception","Message":"【主库】状态不可用，等待后台检查程序恢复方可使用。Unable to connect to any of the specified MySQL hosts.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":

**Comment by 2881099** [comment]
Service单例不常规，一个 Service 一个 fsql 更加不常规的操作，具体看下文档，或者示范xiang mu

**Comment by 2881099** [comment]
Service单例不常规，一个 Service 一个 fsql 更加不常规的操作，具体看下文档，或者示范xiang mu

**Comment by coderdp** [comment]
感谢回复。
我这个项目内需要切换多个数据库，AService 是单例的针对A库的操作，BService 是单例的针对B库的操作。
业务场景大概就是：数据需要从A库读出，写入B库，所以这样操作了。

**Comment by coderdp** [comment]
我这个场景是不是使用：https://github.com/dotnetcore/FreeSql/wiki/%e5%88%86%e8%a1%a8%e5%88%86%e5%ba%93 这个比较合适？一个 fsql，Register 多个链接，根据业务切换链接
