### ISSUE TITLE
pgsql string类型问题

### ISSUE THREAD

**Issue by hajiuxbz** [dotnetcore/FreeSql#73]
生成的字段是255长度的varchar  但是如果字符串长度超过255就会一直卡着没任何反应

用的仓储的InsertAsync方法

**Comment by 2881099** [comment]
不会抛出异常吗？如果直接使用IFreeSql.Insert方法呢

**Comment by hajiuxbz** [comment]
奇怪，刚去特地去复现了 结果又有异常且不会无限等待了，或许是的用多线程进行插入时我的线程问题吧，
非常抱歉，我有时间在测试下 多线程的问题在给您答复。

**Comment by 2881099** [comment]
这块直通npgsql底层，没做包装，按理会抛出异常

**Comment by hajiuxbz** [comment]
是的，按理是这样的，当时确实没铺捉到，可能是线程问题？但是我只是手动定义了[Column(DbType = "Text NOT NULL")] 就不会无限等待了。 具体我在观察
