### ISSUE TITLE
SQLite在ARM环境下支持

### ISSUE THREAD

**Issue by lucodercom** [dotnetcore/FreeSql#730]
SQLite在树莓派3b下面（32位）找不到dll

**Comment by 2881099** [comment]
see: #621

**Comment by densen2014** [comment]
arm,树莓派使用freesql说明
         1.添加包
        <PackageReference Include="FreeSql.Provider.Sqlite" Version="3.0.100" />
        <PackageReference Include = "Microsoft.Data.Sqlite" Version="6.0.3" />

         2.代码
        Microsoft.Data.Sqlite.SqliteConnection _database = new Microsoft.Data.Sqlite.SqliteConnection($"Data Source=document.db");

        var fsql = new FreeSql.FreeSqlBuilder()
        .UseConnectionFactory(FreeSql.DataType.Sqlite, () => _database, typeof(FreeSql.Sqlite.SqliteProvider<>))
        .UseAutoSyncStructure(true)
        .UseNoneCommandParameter(true) //必须开启,因为Microsoft.Data.Sqlite内插处理有bug
        .UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
        .Build();

例子:  https://github.com/densen2014/FreeSqlDemos/tree/master/ARM_ConsoleApp

**Comment by densen2014** [comment]
**有条件的同学直接试试 FreeSql.Provider.SqliteCore 包,使用的就是Microsoft.Data.Sqlite驱动.**
