### ISSUE TITLE
创建表的时候可以设置字段描述吗？

### ISSUE THREAD

**Issue by gweffect** [dotnetcore/FreeSql#732]

**Comment by densen2014** [comment]
可以。wiki搜一下实体类说明

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/wiki/CodeFirst#%E5%A4%87%E6%B3%A8

![image](https://user-images.githubusercontent.com/18613266/113721156-da78d900-9721-11eb-8d41-e180ce6ab6c7.png)
