### ISSUE TITLE
请问如何支持HasFlag

### ISSUE THREAD

**Issue by lclijingxuan** [dotnetcore/FreeSql#734]
1、环境.NET Core 5, MySQL 8, FreeSql版本V2.3.200
2、某字段MyEnum类型，数据库中映射成了int
3、在查询时.Where(x=>MyEnumValue.HasFlag(x.Xxx)
4、在生成SQL语句时，发现HasFlag并没有起作用

目前我只想到有把MyEnum映射成varchar，另外https://github.com/dotnetcore/FreeSql/issues/566
除了这些方法，请问FreeSql有内置的支持吗？

谢谢。

**Comment by luoyunchong** [comment]
直接用 MyEnumValue==x.Xxx呢。

想支持，就复制上面链接的代码。
