### ISSUE TITLE
关于Oracle数据库中DATE类型在FreeSql中自动生成SQL为to_timestamp，导致索引未用到的问题。

### ISSUE THREAD

**Issue by nirdino** [dotnetcore/FreeSql#737]
我的Oracle有表中字段TRACE_TIME是Date类型且记录精确到秒，在FreeSQL中使用s.TRACE_TIME.Between(BeginTime, EndTime)时自动生成的SQL为between to_timestamp('2021-04-09 00:00:00.000000','YYYY-MM-DD HH24:MI:SS.FF6') and to_timestamp('2021-04-09 23:59:59.000000','YYYY-MM-DD HH24:MI:SS.FF6')；而索引只能to_date生效；
![image](https://user-images.githubusercontent.com/5669487/114271390-a8c68180-9a43-11eb-9477-dd606608e209.png)
![image](https://user-images.githubusercontent.com/5669487/114271488-2c806e00-9a44-11eb-808d-c31b7a935671.png)
除了直接改源码，有没有办法将自动生成的to_timestamp改为to_date？谢谢

**Comment by nirdino** [comment]
[ExpressionCall]
    public static class DbFunc
    {
        //必要定义 static + ThreadLocal
        static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();

        public static DateTime to_date(this DateTime that)
        {
            var up = context.Value;
            if (up.DataType == FreeSql.DataType.Oracle) //重写内容
            {
                up.Result = $"{up.ParsedContent["that"]}";
                up.Result = up.Result.Replace("to_timestamp", "to_date");
            }
            return that;
        }
    }

结帖。。。

**Comment by GDLiuYuXin** [comment]
“to_date”只能局限在lambda表达式中使用，我在属性做处理感觉体验会好些
`public class MyTable
{
    [Column(IsPrimary = true, IsNullable = false, Name = "DATE", RewriteSql = "TO_dateStr({0}, 'YYYY/MM/DD HH24:MI:SS')")]
    public string _dateStr { get; private set; }
    [Column(IsIgnore = true)]
    public DateTime DATE
    {
        get
        {
            _ = DateTime.TryParse(_dateStr, out DateTime result);
            return result;
        }
        set
        {
            _dateStr = value.ToString("yyyy/MM/dd HH:mm:ss");
        }
    }
}`

**Comment by GDLiuYuXin** [comment]
“DbFunc.to_date”只能局限在lambda表达式中使用吧，在属性做处理感觉体验会好些
```
public class MyTable
{
    [Column(Name = "DATE", RewriteSql = "TO_DATE({0}, 'YYYY/MM/DD HH24:MI:SS')")]
    public string _dateStr { get; private set; }
    [Column(IsIgnore = true)]
    public DateTime DATE
    {
        get
        {
            _ = DateTime.TryParse(_dateStr, out DateTime result);
            return result;
        }
        set
        {
            _dateStr = value.ToString("yyyy/MM/dd HH:mm:ss");
        }
    }
}
```

**Comment by 2881099** [comment]
RewriteSql 和 自定义表达式函数，作用不一样。
