### ISSUE TITLE
查询语句与sql字段不对应的问题

### ISSUE THREAD

**Issue by seamusic** [dotnetcore/FreeSql#740]
我有一个实体

```    
public class WaterlevelModel
    {
        public string Id { get; set; }
        public string BoreholeId { get; set; }
        public float? Depth { get; set; }
        public string Name { get; set; }
        public string Property { get; set; }
        public int No { get; set; }
        public DateTime? MeasureTime { get; set; }
    }
```

本来，是可以直接查询：
```
var list = context.Select<WaterlevelModel>()
.Where(x => x.ProjectId == boreholeModel.Project.Id).ToList();
```

但现在的问题来了，因为这个实体我想对应两个不同的数据库，其中一个数据库会缺少某些字段的，比如MeasureTime 这个字段。按道理，我只需要写成如下就应该可以查询得到：
```
var list = context.Select<WaterlevelModel>()
                    .WithSql("select * from WaterLevels where BoreholeId=@BoreholeId", new { BoreholeId = id })
                    .ToList();
```

但问题是，生成的语句会从WaterlevelModel人生成sql语句，如下：
```
SELECT a.[Id], a.[BoreholeId], a.[Depth], a.[Name], a.[Property], a.[No], a.[MeasureTime] 
FROM ( select * from WaterLevels where BoreholeId=@BoreholeId ) a
```
导致查询报错：SqlException: 列名 'MeasureTime' 无效

请问，有没办法直接执行sql语句，映射到实体，映射不上就为空的。
同时，不要在实体上加配置，感觉实体还是比较纯净点好。

**Comment by seamusic** [comment]
查找文档，找到了办法：
`
context.Select<WaterlevelModel>()
                    .WithSql("select * from WaterLevels where BoreholeId=@BoreholeId", new { BoreholeId = id })
                    .ToList(x => new WaterlevelModel()
                    {
                        BoreholeId = x.BoreholeId,
                        Depth = x.Depth,
                        Id = x.Id,
                        Name = x.Name,
                        No = x.No
                    })
`

这……太不优雅了，也不够灵活。请问还有没有其它解决办法呢？

**Comment by luoyunchong** [comment]
没有。下一个。🤣🤣🤣

**Comment by luoyunchong** [comment]
写继承。

**Comment by 2881099** [comment]
或者：

fsql.Ado.Query\<WaterlevelModel\>(sql);
