### ISSUE TITLE
DbContext方式注入HostedService报错

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/FreeSql#741]
注入代码
```
services.AddSingleton(Fsql);
services.AddFreeDbContext<TDbContext>(x=>x.UseFreeSql(Fsql));
//后台服务注入
services.AddHostedService<ServerHealthCheck>();

//ServerHealthCheck构造函数
 public ServerHealthCheck(ILogger<ServerHealthCheck> Logger, CfgContext Fsql) {
            this.Logger = Logger;
            this.Fsql = Fsql;
 }
```
注入会报以下错误
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: TestService.ServerHealthCheck': Cannot consume scoped service 'TestService.CfgContext' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)'

**Comment by bao2314483** [comment]
补充下,即使用以下方式获取也发现问题,虽然运行没有报错,但是发现数据并没有插入数据库,但是日志打印出sql语句
```
using (var CfgCt = Scope.CreateScope().ServiceProvider.GetService<CfgContext>()) {
   await CfgCt.Servers.AddAsync(MyServer);
}
```

**Comment by luoyunchong** [comment]
第二种没有SaveChangesAsync
