### ISSUE TITLE
2.3.200.0  MS Sqlserver 使用AsAlias对表取别名错误，Select 、InnerJoin、Where、OrderBy都没有生效，只有表后面的生效

### ISSUE THREAD

**Issue by sqlite-me** [dotnetcore/FreeSql#742]
2.3.200.0  MS Sqlserver 使用AsAlias对表取别名错误，Select 、InnerJoin、Where、OrderBy都没有生效，只有表后面的生效

`freeSql.Select<T_Business, Sys_Parameter>()
                .AsAlias((t,o)=>t.Equals(typeof(T_Business))?"t":(t.Equals(typeof(Sys_Parameter))?"p":o))
                .InnerJoin((t,p)=>t.DepNo==p.DepID)
                .Where((t,p) => t.DepNo == depNo  && t.IsDel == 0)
                .OrderByDescending((t, p) => t.CreateTime)
                .ToList<T_Business>(“t.ID,t.DepNo,t.Name,p.FName as BName”);
`
生成的Sql如下，
**SELECT t.ID,t.DepNo,t.Name,p.FName as BName 
FROM [T_Business] t 
INNER JOIN [Sys_Parameter] p ON a.[DepNo] = b.[DepID] AND a.[BID] = b.[BM] AND b.[LBBM] = 11 
WHERE (a.[DepNo] = 1 AND a.[IsDel] = 0) 
ORDER BY a.[CreateTime] DESC**

我把ToList方法变成无参的ToList<T_Business>()后生成的Sql：
**SELECT  a.[ID] as1, a.[DepNo] as2, a.[Name] as3, a.[FName ] as4** 
FROM [T_Business] t 
INNER JOIN [Sys_Parameter] p ON a.[DepNo] = b.[DepID] AND a.[BID] = b.[BM] AND b.[LBBM] = 11 
WHERE (a.[DepNo] = 1 AND a.[IsDel] = 0) 
ORDER BY a.[CreateTime] DESC

这是怎么回事，是我哪里没写对吗？

**Comment by 2881099** [comment]
AsAlias 目前还没开放使用说明哦

目前最直接的改别名，可以直接操作如下：

var sel = freeSql.Select\<T_Business, Sys_Parameter\>();

(sel as Select0Provider)._tables[0].Alias = “t”;

sel.InnerJoin....

**Comment by sqlite-me** [comment]
嗯，谢谢
