### ISSUE TITLE
update_time 字段自动赋值不稳定

### ISSUE THREAD

**Issue by taoqijing** [dotnetcore/FreeSql#744]
`/// <summary>
        /// 更新时间
        /// </summary>
        [JsonProperty, Column(Name = "update_time", ServerTime = DateTimeKind.Local)]
        public DateTime? UpdateTime { get; set; }`

**Comment by taoqijing** [comment]
第一次插入数据的时候是没问题的，之后每次更新字段的时候，update_time变得不稳定，有时候会更新有时候不会

**Comment by 2881099** [comment]
用 Aop.CommandBefore 事件把执行的 SQL 监控起来。

我猜你可能用的是仓储？

**Comment by taoqijing** [comment]
是使用的仓储，那我监控先，谢谢
