### ISSUE TITLE
连接达梦8，执行查询操作报“出现无效的表或视图名”

### ISSUE THREAD

**Issue by AmassMountainSea** [dotnetcore/FreeSql#745]
运行环境 .net5 .NET Standard 2.0 
依赖注入
`IFreeSql fsql = new FreeSql.FreeSqlBuilder()
			 .UseConnectionString(FreeSql.DataType.Dameng, @"server=192.168.0.222;port=5236;user id=SYSDBA;password=SYSDBA;database=YW_DAGL;")
			 .Build();
			services.AddSingleton<IFreeSql>(fsql);`
模式名称：SYSDBA
表名：BASE_USERS
查询方法
`var sql = _fsql.Select<Base_Users>().Where(m => m.USER_CODE == loginModel.USER_CODE && m.USER_PWD == loginModel.USER_PWD).ToSql();

List<Base_Users> list =  _fsql.Select<Base_Users>().Where(m=>m.USER_CODE == loginModel.USER_CODE && m.USER_PWD == loginModel.USER_PWD).ToList();`
执行时，报`第3 行附近出现错误:
无效的表或视图名[Base_Users]`
模式名称没错，表存在，表名没错
请问还需要在哪里进行配置吗？

**Comment by AmassMountainSea** [comment]
![1](https://user-images.githubusercontent.com/63187537/115518896-42e7be80-a2bb-11eb-8fd8-578004d926f4.jpg)
![2](https://user-images.githubusercontent.com/63187537/115518898-4418eb80-a2bb-11eb-9c44-f57f13fb378b.jpg)
![3](https://user-images.githubusercontent.com/63187537/115518902-44b18200-a2bb-11eb-9f67-054c6bbf3153.jpg)

**Comment by AmassMountainSea** [comment]
![4](https://user-images.githubusercontent.com/63187537/115519058-6e6aa900-a2bb-11eb-8fec-12ae1b441b5c.jpg)
![5](https://user-images.githubusercontent.com/63187537/115519069-6f9bd600-a2bb-11eb-8a9b-16fb2c14b7dc.jpg)
![6](https://user-images.githubusercontent.com/63187537/115519073-70346c80-a2bb-11eb-8d21-4b9de820058b.jpg)

**Comment by AmassMountainSea** [comment]
好像是拼接sql语句时，模式名称没有加上，该什么处理呀。。。。。。。。好烦

**Comment by 2881099** [comment]
最近其他事务缠身，回复不及时，有问题可以加群直接问大家。

你的问题我回复过很多次，达梦使用起来，尽量贴合 Oracle 习惯，不要用模式，或者模式要与登陆的 userid 同名。

Oracle 是这样的，没有模式，也没有多个数据库，每个 userid 配置表权限，然后登陆后只能操作已配置好权限的那些表。

**Comment by pccai** [comment]
string sqlConnDM8Cfg = "server=192.1.1.10;port=5236;user id=TEST;password=123456;database=TEST2;schema=TEST2";
链接字符串上最新驱动可以设置schema参数，用于指定模式到非当前连接的Userid下去，但是开启db架构自动同步后，fs还是把表结构创建到TEST下去了，不在TEST2下。
TEST2是从TEST下创建的模式： CREATE SCHEMA "TEST2" AUTHORIZATION "TEST";
