### ISSUE TITLE
JsonMap 特性的数据类型映射问题

### ISSUE THREAD

**Issue by hd2y** [dotnetcore/FreeSql#746]
目前在 `PostgreSQL` 中使用 `JsonMap` 有两点问题与需求：

1. 希望如果使用 `PostgreSQL` 数据库，Code First 数据类型映射默认为 `jsonb`。
2. 目前如果使用 `JsonMap` 后数据类型默认为 `StringLeng = -2`，用户 `Column` 特性指定的数据类型不生效。希望使用 `JsonMap` 特性后，默认数据类型优先使用用户 `Column` 特性指定的 `DbType`。

❤ 希望针对以上问题与需求能够做出调整。

**Comment by iyume** [comment]
这个 issue 有更新吗？

我在 pg 使用 `[JsonMap, Column(Name = "images", DbType = "jsonb")]` 依旧在数据库产生 text 数据类型

**Comment by 2881099** [comment]
```c#
[JsonMap, Column(Name = "images", MapType = typeof(JToken))]
```
