### ISSUE TITLE
FreeSql.All 发布时一个小问题, 事实证明'偷懒'没有好下场.

### ISSUE THREAD

**Issue by SangKuanJi** [dotnetcore/FreeSql#750]
windows 10 开发环境. 使用 mysql数据库. 
当我偷懒直接引用了 FreeSql.All 后.
开发环境, 没有问题.
centos 上使用 "dotnet xxxx.dll" 启动, 没有问题. 
但是当使用  systemctl start xxxx.service 启动时就发生异常.
使用 journalctl -fu xxxx.service 查看日志,看到下面的报错:
` `An assembly specified in the application dependencies manifest (xxxxxx.deps.json) was not found: package: 'Microsoft.Data.SqlClient', version: '2.1.1'`

于是我尝试手动添加包   `Install-Package Microsoft.Data.SqlClient -Version 2.1.1`
也确保程序目录有 Microsoft.Data.SqlClient.dll  文件. 
但是依然异常. 

最后 删除了 FreeSql.All  只添加了. 'FreeSql' 'FreeSql.Provider.MySql' 'FreeSql.Repository'  正常启动.

**Comment by 2881099** [comment]
是的，ado.net 包依赖问题严重。
