### ISSUE TITLE
如何关闭连接池

### ISSUE THREAD

**Issue by carbonhe** [dotnetcore/FreeSql#755]
请问如何关闭连接池，我使用了npgsql官网文档上面的`Pooling=false`貌似没有效果。

**Comment by 2881099** [comment]
关闭连接池，每次都是新 socket，性能很差的。

如果一定要用，可以用 Pooling=false，配合 FreeSqlBuilder UseConnectionFactory 试试吧，看看这个方法的注释。

**Comment by carbonhe** [comment]
好的 谢谢
