### ISSUE TITLE
在有查询条件的情况下，递归和级联查询不能同时生效

### ISSUE THREAD

**Issue by shengqi** [dotnetcore/FreeSql#760]
[Demo.zip](https://github.com/dotnetcore/FreeSql/files/6410818/Demo.zip)

                var v = fsql.Select<RuleGroup>()
                   .IncludeMany(t => t.Rules, then => then
                        .IncludeMany(t => t.RuleParams, then => then
                            .Include(t => t.Parameter)))
                   .Where(t => t.Id == ruleGroup.Id).AsTreeCte().ToTreeList();

我的业务中有RuleGroup、Rule、RuleParam和Parameter这些表，其中，RuleGroup是自递归的，Group下面还有可能会有Rule，然后Rule又有参数关系（RuleParam）以及参数信息（Parameter），以上是我构建的查询语句，当没有Where(t => t.Id == ruleGroup.Id)条件时，直接用.ToTreeList();就可以将规则组的树构建好，而且下面的规则及参数信息都会附带上。但是一旦加上这个where条件后，树关系就出不来了，这时将AsTreeCte()加到ToTreeList();前面，可以将树关系构建出来，但是附带的规则及后面的属性又出不来了。请问是我这个写法有问题，还是别的什么原因，望指教。

**Comment by 2881099** [comment]
提供一下 demo 测试程序 + 测试数据，最好是 console app 类型的，用 sqlite 数据库。

**Comment by shengqi** [comment]
@2881099 你好，demo和测试数据已经提供上去了，麻烦帮忙看一下，谢谢。
