### ISSUE TITLE
Sqlite同步表时是否可以不区分大小写

### ISSUE THREAD

**Issue by exy3351** [dotnetcore/FreeSql#761]
数据表实体新加了字段，在使用SyncStructure同步表时发现数据表没有升级成功，根据sql发现时大小写的问题。
同步时生成的判断表是否存在的语句是  select sql from main.sqlite_master where type='table' and name='T_ATTACH'
但数据库中是小写（由于历史原因之前的大小写比较乱，不好统一）。期望在不区分大小写的数据库类型中，这种是否可以在判断时不区分大小写？

**Comment by 2881099** [comment]
1、实体特性

```c#
[Table(Name = "t_attach")]
public class T_ATTACH
{...}
```

2、统一处理

```c#
new FreeSqlBuilder()
   .UseNameConvert(...ToLower)
   .Build();
```
