### ISSUE TITLE
.Net 5发布为单文件时会出现异常

### ISSUE THREAD

**Issue by ziokuroi** [dotnetcore/FreeSql#762]
如题，测试代码如下：
 
        static void Main(string[] args) {
            Console.WriteLine("Test Start!");
            var fsql = new FreeSql.FreeSqlBuilder()
                .UseConnectionString(FreeSql.DataType.MySql,
                    "Data Source=127.0.0.1;" +
                    "Port=3306;" +
                    "User ID=test;" +
                    "Password=test;" +
                    "Initial Catalog=dotnet;" +
                    "Charset=utf8;" +
                    "SslMode=none;" +
                    "Max pool size=10"
                )
                .UseNameConvert(NameConvertType.PascalCaseToUnderscoreWithLower)
                .UseAutoSyncStructure(false)
                .Build();
            Console.ReadKey();
        }

发布指令

> dotnet publish -r win-x64 -f net5.0 -p:PublishSingleFile=true --no-self-contained

运行单文件则会提示

> 【主库】仍然不可用，下一次恢复检查时间：2021/5/7 1:50:05，错误：(The type initializer for 'MySql.Data.MySqlClient.Replication.ReplicationManager' threw an exception.)

如果不发布为单文件则不会出现这个问题

**Comment by luoyunchong** [comment]
换这个包.不会有问题。
```
FreeSql.Provider.MySqlConnector
```

**Comment by ziokuroi** [comment]
> 
> 
> 换这个包.不会有问题。
> 
> ```
> FreeSql.Provider.MySqlConnector
> ```

感谢答复，更换包之后没有问题了，谢谢！
