### ISSUE TITLE
继承的属性无法映射到数据库？

### ISSUE THREAD

**Issue by HuangRan** [dotnetcore/FreeSql#766]
使用FreeSql CodeFirst 无法映射继承自父类的属性到数据库列。

**Comment by luoyunchong** [comment]
支持，请给出示例。

**Comment by HuangRan** [comment]
> 支持，请给出示例。
//父类
public abstract class Entity
{
      public string Id {get;}
}
//子类
public class Test:Entity
{

}

fsql.CodeFirst.IsAutoSyncStructure = true;
fsql.CodeFirst.ConfigEntity<Test>(x =>
{
         x.Name("Test");
         x.Property(a => a.Id).IsPrimary(true);   
 });
 fsql.CodeFirst.SyncStructure<Person>();

我发现当父类的属性为只读属性时，无法映射到数据库。

另外还有几个问题不知道FreeSQL是否支持
1. 是否支持映射字段（类似efcore中的 UsePropertyAccessMode(PropertyAccessMode.Field)）
2. 是否支持值对象（类似efcore中的OwnsOne  WithOwner）


谢谢。

**Comment by luoyunchong** [comment]
都不支持，请直接写 get ;set;

**Comment by 2881099** [comment]
或者

public string Id { get; protected set; }
