### ISSUE TITLE
枚举类型插入失败

### ISSUE THREAD

**Issue by yundexiaobin** [dotnetcore/FreeSql#768]
使用ef的模型并生成表，在不使用FreeSql本身的Column特性情况下， 插入数据时，枚举字段的值是字符串而不是整型类型，造成插入失败

**Comment by luoyunchong** [comment]
请给出具体代码

**Comment by jianxuanbing** [comment]
> 使用ef的模型并生成表，在不使用FreeSql本身的Column特性情况下， 插入数据时，枚举字段的值是字符串而不是整型类型，造成插入失败

这个目测设置一下映射类型即可

**Comment by 2881099** [comment]
see: #75 #27
