### ISSUE TITLE
参数化，查询效果不稳定的BUG

### ISSUE THREAD

**Issue by wangxiwangque** [dotnetcore/FreeSql#771]
![image](https://user-images.githubusercontent.com/37373632/117942520-b8d0ca00-b33d-11eb-8cbb-608277a34c95.png)
sql进行参数化后，生成的语句在首次执行的时候，可以达到预期效果，但过段时间后，执行效率立马跌至谷底，查询速度再也上不去了。

**Comment by wangxiwangque** [comment]
![image](https://user-images.githubusercontent.com/37373632/117947186-8b3a4f80-b342-11eb-8410-06cd6464aa8f.png)
![image](https://user-images.githubusercontent.com/37373632/117947223-94c3b780-b342-11eb-9b27-668ff7d2e7f4.png)
![image](https://user-images.githubusercontent.com/37373632/117947273-9e4d1f80-b342-11eb-84e9-036ebdba0371.png)
原因是想使用oracle的时候让时间查询可以快一点，因此加了自定义方法，结果发现严重影响查询速度

**Comment by luoyunchong** [comment]
这不是参数化吧，直接把代码发出来。。或提供一个console的项目重现。

**Comment by wangxiwangque** [comment]
[相关代码.zip](https://github.com/dotnetcore/FreeSql/files/6470007/default.zip)
由于时间相关跟项目庞大只能提供相关设计到的代码
![image](https://user-images.githubusercontent.com/37373632/118068868-ae620f00-b3d5-11eb-9a8c-b44693e55d43.png)
![image](https://user-images.githubusercontent.com/37373632/118068892-ba4dd100-b3d5-11eb-9a78-94cd07a6f6a8.png)

**Comment by wangxiwangque** [comment]
这个是相关查询日志记录
[2021-05-12Debug.zip](https://github.com/dotnetcore/FreeSql/files/6470016/2021-05-12Debug.zip)

**Comment by wangxiwangque** [comment]
![image](https://user-images.githubusercontent.com/37373632/118100104-a8d1ec80-b408-11eb-9ab4-b68384f4751e.png)
这两个语句的区别从最终执行结果来看应该相差不大的但实际查询接口偏差太大了

**Comment by luoyunchong** [comment]
IdleBus GetRepository  每Get一次， IdleBus就Register  一次。。这不合理。

**Comment by wangxiwangque** [comment]
[examples.zip](https://github.com/dotnetcore/FreeSql/files/6491776/examples.zip)
写了一个简单的demo可以看下

**Comment by luoyunchong** [comment]
数据发一些。

**Comment by 2881099** [comment]
从你的日志 SQL 来看，不是参数化啊
