### ISSUE TITLE
关于实体扩展属性的赋值

### ISSUE THREAD

**Issue by tt123456tt** [dotnetcore/FreeSql#772]
叶老板，做多表联合查询的时候，我希望返回一个MenuEntity，其中ParentName 是一个扩展字段，应该取联合表b中的Name值，请问下这种应该怎么写？  我看文档里面有个fsql.Select<Song>().ToList(a => new Song(a.id) { xxx = a.ext })  这个示例写法，这是需要去MenuEntity中增加构造函数么？

var query = Orm.Select<MenuEntity, MenuEntity, AccountEntity>()
                        .LeftJoin((a, b, c) => a.ParentId == b.Id)
                        .LeftJoin((a, b, c) => a.CreatedUserId == c.Id)
                        .Where((a, b, c) => a.Id == id);
            var ret = query.FirstAsync((a, b, c) => new { a, ParentName = b.Name });

**Comment by luoyunchong** [comment]
带构造函数 传a.id 这种方式，看清文档，是只查询，id和a.ext

你可以 建 一个dto，继承MenuEntity，多一个ParentName，。然后用这种方式。
fsql.Select<Song>().ToList(a => new Dto { xxx = a.ext }) 
//情况2：Dto 与 Song 属性名相同的字段被查询，纠正映射 ext，返回 List<Dto>

**Comment by tt123456tt** [comment]
这样写的话，就会多出好多dto了，而且各层都要对应处理，叶老板有没有可能实现  var ret = query.FirstAsync<MenuEntity>((a, b, c) => new { a, ParentName = b.Name });  或者 var ret = query.FirstAsync((a, b, c) => new MenuEntity { ParentName = b.Name }); 这种写法

**Comment by luoyunchong** [comment]
第一种不支持吗，支持的。
第二种，这种就是只取b.Name的值。

**Comment by tt123456tt** [comment]
第一种我想能直接转换成MenuEntity   ，不用再加工😂

**Comment by luoyunchong** [comment]
这不是你偷懒的理由。查询的文档仔细看。

**Comment by tt123456tt** [comment]
看了好多遍了    确实满足不了我的需求哇     我在MenuEntity里面加了个扩展字段  ParentName ，查询的时候希望把联合表中的b.Name赋值给这个ParentName,最终返回的是一个MenuEntity 呀。现在除了dto的方式外，var ret = query.FirstAsync((a, b, c) => new { a, ParentName = b.Name }); 这种方式返回的是一个匿名对象

**Comment by 2881099** [comment]
> 这样写的话，就会多出好多dto了，而且各层都要对应处理，叶老板有没有可能实现 var ret = query.FirstAsync((a, b, c) => new { a, ParentName = b.Name }); 或者 var ret = query.FirstAsync((a, b, c) => new MenuEntity { ParentName = b.Name }); 这种写法

这两种不是都支持吗
