### ISSUE TITLE
是否能支持   select<dynamic>().withsql(sql)   或select<DataTable>().withsql(sql) 

### ISSUE THREAD

**Issue by s899000** [dotnetcore/FreeSql#775]

**Comment by s899000** [comment]
var query = DB.test5.Select<DataTable>().WithSql("select * from usr").Page(1,10).ToOne();
  var query2 = DB.test5.Select<dynamic>().WithSql("select * from usr").Page(1, 10).ToList();

类似以上语句

**Comment by s899000** [comment]
var query = DB.test5.Select<DataTable>().WithSql("select * from usr").Page(1,10).ToOne();
            var query2 = DB.test5.Select<dynamic>().WithSql("select * from usr").Page(1, 10).ToList();
类似以上语句

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/issues/466

**Comment by s899000** [comment]
> #466

 DataTable dt = DB.test5.Select<object>("select * from usr").ToDataTable("*");
提示 System.Exception:“对象名 'Object' 无效。”
