### ISSUE TITLE
CommandTimeout无效

### ISSUE THREAD

**Issue by liuyu66** [dotnetcore/FreeSql#777]
#### 问题描述及重现步骤：

fsql.Select<>().CommandTimeout(10).ToList()查询200万+的数据表超时不起作用。
#### 数据库的具体版本
```
oracle11g 11.2.0版本
```

#### 安装的包
```
1.freesql 2.5.100.0
2.freesql.dbcontext 1.8.1.0
3.FreeSql.Provider.Oracle 2.5.100.0
4.Oracle.ManagedDataAccess 4.122.19.1
```

#### .net framework/. net core？ 及具体版本
```
.net framework 4.5
```

**Comment by 2881099** [comment]
正常啊，CommandTimeout 超时10秒无响应，200万+的数据一直有响应，所有不会触发超时。

这是 ado.net 内部功能，我们决定不了。或者你们在应用层自己解决。

**Comment by NovaNick** [comment]
我在SqlServer的链接字符串中，配置了CommandTimeout ，貌似也是无效...
