### ISSUE TITLE
MySQL ExecuteInsertedAsync() 批量插入 RETURNING 报错 

### ISSUE THREAD

**Issue by wangchaoit** [dotnetcore/FreeSql#784]
#### 问题描述及重现步骤：

fsql.Insert(list).ExecuteInsertedAsync()

报错 提示 RETURNING 附近报错

是我的mysql版本太低了 不支持 RETURNING  语法吗？

我在网上查询资料说 mysql 不支持 RETURNING  [资料出处](https://stackoverflow.com/questions/2796244/syntax-for-returning-clause-in-mysql-pdo)
#### 数据库的具体版本
```
MySQL版本：5.7.34
FreeSQL版本：205.100

```

#### 安装的包
```
freesql
freesql.dbcontext
freesq.provider.mysql
```

#### .net framework/. net core？ 及具体版本
```
netcore5.0
```

**Comment by luoyunchong** [comment]
注意：此方法只有 Postgresql/SqlServer 有效果 
[https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Interface/Curd/IInsert.cs/#L147](https://github.com/dotnetcore/FreeSql/blob/master/FreeSql/Interface/Curd/IInsert.cs/#L147)
```
fsql.Insert(list).ExecuteInsertedAsync()
```


你可以 用这个方法试试 ``ExecuteIdentityAsync()``

**Comment by wangchaoit** [comment]
> Mysql8.0

谢谢你 我了解了
