### ISSUE TITLE
同一个线程进来，先删后加会报错：不可添加，已存在于状态管理

### ISSUE THREAD

**Issue by axinno1** [dotnetcore/FreeSql#790]
#### 问题描述及重现步骤：
前端参数传了两条数据用作InsertAsync，在添加之前删除关联的关系表的所有数据，然后在添加，保证assign表中永远是最后添加的条数这是大前提，在新增的时候就报不可添加，已存在于状态管理：(1, , 1, 1, 6803258175836524544)这个错

#### 数据库的具体版本
```
mysql 5.7.34
```

#### 安装的包
```
FreeSql.DbContext 2.5.100
```

#### .net framework/. net core？ 及具体版本
```
 net core3.1
```

**Comment by 256051** [comment]
我偶尔也有这个问题

**Comment by 2881099** [comment]
使用同一个仓储对象，对同一个实体对象，添加多次就会这样。
