### ISSUE TITLE
how to where with iselect grouping

### ISSUE THREAD

**Issue by thanhhactld** [dotnetcore/FreeSql#796]
firstly, thanks the team for you contributes, because freesql help our developement to be easy.
currently i want to create query like this:

```
select * from Item where CategoryId in (
 select CategoryId from Item group by CategoryId having count (CategoryId) >1
);
```

How i do this under freesql

**Comment by thanhhactld** [comment]
Or Sql Statement like this, Im not sure freesql support simple CTE
```
with CTE as (
     select raw."CategoryId"
    from  "Item" raw group by raw."CategoryId" having count(raw."CategoryId") > 1
)  select *
from "Item" raw2
inner join CTE on CTE."CategoryId" = raw2."CategoryId"
```

**Comment by luoyunchong** [comment]
> firstly, thanks the team for you contributes, because freesql help our developement to be easy.
> currently i want to create query like this:
> 
> ```
> select * from Item where CategoryId in (
>  select CategoryId from Item group by CategoryId having count (CategoryId) >1
> );
> ```
> 
> How i do this under freesql


use ToSql  
```csharp
var sql = fsql
     .Select<Item>()
     .GroupBy(r => r.CategoryId).Having(u => u.Count() > 1)
     .ToSql(b => b.Key);

  fsql.Select<Item>().Where($"CategoryId in ({sql})").ToList();
```

sql
```sql
 SELECT a."Id", a."CategoryId" 
FROM "Item" a 
WHERE (CategoryId in (SELECT a."CategoryId" 
FROM "Item" a 
GROUP BY a."CategoryId" 
HAVING (count(1) > 1)))
```

Or Use
```csharp
var list3 = fsql
    .Select<object>()
    .WithSql(@"select * from Item where CategoryId in (
select CategoryId from Item group by CategoryId having count(CategoryId) > 1
) ")
    .ToList<Item>("*");

var list4 = fsql
    .Select<Item>()
    .WithSql(@"select * from Item where CategoryId in (
select CategoryId from Item group by CategoryId having count(CategoryId) > 1
) ")
    .ToList();
```


```sql
SELECT * 
          FROM ( select * from Item where CategoryId in (
           select CategoryId from Item group by CategoryId having count(CategoryId) > 1
          )  ) a

 SELECT a."Id", a."CategoryId" 
      FROM ( select * from Item where CategoryId in (
       select CategoryId from Item group by CategoryId having count(CategoryId) > 1
      )  ) a
```

**Comment by thanhhactld** [comment]
> > firstly, thanks the team for you contributes, because freesql help our developement to be easy.
> > currently i want to create query like this:
> > ```
> > select * from Item where CategoryId in (
> >  select CategoryId from Item group by CategoryId having count (CategoryId) >1
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How i do this under freesql
> 
> use ToSql
> 
> ```cs
> var sql = fsql
>      .Select<Item>()
>      .GroupBy(r => r.CategoryId).Having(u => u.Count() > 1)
>      .ToSql(b => b.Key);
> 
>   fsql.Select<Item>().Where($"CategoryId in ({sql})").ToList();
> ```
> 
> sql
> 
> ```sql
>  SELECT a."Id", a."CategoryId" 
> FROM "Item" a 
> WHERE (CategoryId in (SELECT a."CategoryId" 
> FROM "Item" a 
> GROUP BY a."CategoryId" 
> HAVING (count(1) > 1)))
> ```
> 
> Or Use
> 
> ```cs
> var list3 = fsql
>     .Select<object>()
>     .WithSql(@"select * from Item where CategoryId in (
> select CategoryId from Item group by CategoryId having count(CategoryId) > 1
> ) ")
>     .ToList<Item>("*");
> 
> var list4 = fsql
>     .Select<Item>()
>     .WithSql(@"select * from Item where CategoryId in (
> select CategoryId from Item group by CategoryId having count(CategoryId) > 1
> ) ")
>     .ToList();
> ```
> 
> ```sql
> SELECT * 
>           FROM ( select * from Item where CategoryId in (
>            select CategoryId from Item group by CategoryId having count(CategoryId) > 1
>           )  ) a
> 
>  SELECT a."Id", a."CategoryId" 
>       FROM ( select * from Item where CategoryId in (
>        select CategoryId from Item group by CategoryId having count(CategoryId) > 1
>       )  ) a
> ```

**Comment by thanhhactld** [comment]
> > firstly, thanks the team for you contributes, because freesql help our developement to be easy.
> > currently i want to create query like this:
> > ```
> > select * from Item where CategoryId in (
> >  select CategoryId from Item group by CategoryId having count (CategoryId) >1
> > );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How i do this under freesql
> 
> use ToSql
> 
> ```cs
> var sql = fsql
>      .Select<Item>()
>      .GroupBy(r => r.CategoryId).Having(u => u.Count() > 1)
>      .ToSql(b => b.Key);
> 
>   fsql.Select<Item>().Where($"CategoryId in ({sql})").ToList();
> ```
> 
> sql
> 
> ```sql
>  SELECT a."Id", a."CategoryId" 
> FROM "Item" a 
> WHERE (CategoryId in (SELECT a."CategoryId" 
> FROM "Item" a 
> GROUP BY a."CategoryId" 
> HAVING (count(1) > 1)))
> ```
> 
> Or Use
> 
> ```cs
> var list3 = fsql
>     .Select<object>()
>     .WithSql(@"select * from Item where CategoryId in (
> select CategoryId from Item group by CategoryId having count(CategoryId) > 1
> ) ")
>     .ToList<Item>("*");
> 
> var list4 = fsql
>     .Select<Item>()
>     .WithSql(@"select * from Item where CategoryId in (
> select CategoryId from Item group by CategoryId having count(CategoryId) > 1
> ) ")
>     .ToList();
> ```
> 
> ```sql
> SELECT * 
>           FROM ( select * from Item where CategoryId in (
>            select CategoryId from Item group by CategoryId having count(CategoryId) > 1
>           )  ) a
> 
>  SELECT a."Id", a."CategoryId" 
>       FROM ( select * from Item where CategoryId in (
>        select CategoryId from Item group by CategoryId having count(CategoryId) > 1
>       )  ) a
> ```

Thanks for your suggestion , I got that by use this state

`
 var greaterThan1Spec = freeSql.Select<Item>()
                    .As("conflict")
                    .GroupBy(x => x.CategoryId)
                    .Having(x => x.Count() > 1)
                ;
var conflictSql = greaterThan1Spec.ToSql(x => x.Key,
        FieldAliasOptions.AsProperty);
    var querySpec = freeSql.Select<Item>()
            .WithSql($"{conflictSql}")
            .From<Item>((item, greaterThan1) =>
                pig.InnerJoin(x => x.CategoryId.Equals(greaterThan1.CategoryId)))
        ;
`

=> and the output:
`
Select * 
FROM ( SELECT conflict."CategoryId" 
    FROM "Item" conflict 
    GROUP BY conflict."CategoryId" 
    HAVING (count(1) > 1) ) a 
INNER JOIN "Item" item ON a."CategoryId" = item."CategoryId" 
`
