### ISSUE TITLE
啥时候能把双引号的优化下

### ISSUE THREAD

**Issue by jetydu** [dotnetcore/FreeSql#8]
啥时候能把双引号的优化下

**Comment by 2881099** [comment]
刚才考虑了一下，把上次 UseQuoteSqlName 删掉了

增加了 UseSyncStructureToUpper(true)，代码没什么改变，这个功能只作一件事，将类名、属性性通通转成全大写，生成的SQL语句仍然会包含 "" 双引号。

但不影响在外部直接使用 select * from 表名

**Comment by 2881099** [comment]
单元测试通过了，我现在发布 0.1.5 版本，包含 FreeSql.Repository

**Comment by 2881099** [comment]
更新日志：
https://github.com/2881099/FreeSql/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97

**Comment by 2881099** [comment]
仓库文档：https://github.com/2881099/FreeSql/wiki/Repository

**Comment by wwq3021** [comment]
UseQuoteSqlName 启用之后 ，有几率导致tosql 不生成 as 别名

**Comment by 2881099** [comment]
提供一下重现demo
