### ISSUE TITLE
将Freesql的dynamicfilterinfo标记为[serialable] 

### ISSUE THREAD

**Issue by 835718973** [dotnetcore/FreeSql#802]
Freesql的DynamicFilterInfo目前未标记未[Serialble]，目前我在远程RPC的工程中需要序列化传递dynamicfilterInfo,是否可以将其标记为可序列化或者有其它原因导致不能这么做？

**Comment by luoyunchong** [comment]
先用一个类继承这个类，加上`[Serializable]`,看测试可以吗。
如果测试在DynamicFilterInfo加上`[Serializable]`可解决RPC序列化问题，PR is Welcome!

**Comment by 2881099** [comment]
传 string 也可以的，DynamicFilterInfo 和 JSON 可以互转

**Comment by 835718973** [comment]
![image](https://user-images.githubusercontent.com/20808204/122543301-37680800-d05e-11eb-821f-661053c2f183.png)
请问下拉去源码后编译产生了许多这种错误，但是代码本身并没有提示错误，有什么其它注意事项吗？
因为有许多其它参数需要一起处理，直接序列化会高效与方便许多，所以如果没有不良影响，希望能够添加此特性

**Comment by 835718973** [comment]
![image](https://user-images.githubusercontent.com/20808204/122543301-37680800-d05e-11eb-821f-661053c2f183.png)
请问下拉去源码后编译产生了许多这种错误，但是代码本身并没有提示错误，有什么其它注意事项吗？
因为有许多其它参数需要一起处理，直接序列化会高效与方便许多，所以如果没有不良影响，希望能够添加此特性
