### ISSUE TITLE
DateTime查询问题

### ISSUE THREAD

**Issue by j4587698** [dotnetcore/FreeSql#804]
#### 问题描述及重现步骤：

使用DateTime.Year进行查询，代码类似
```where.And(x => x.PublishTime.Year == 2021);```

在Sqlite数据库中，`x.PublishTime.Year == 2021`会转换成`strftime('%Y',a."PublishTime") = 2021`，前面为char类型，后面是int类型，无法查询到正确的数据。
如果使用
```where.And(x => x.PublishTime.Year.ToString() == "2021");```
会转换为`cast(strftime('%Y',a."PublishTime") as character) = '2021'`，也无法查询到正确数据。

应该转换为`strftime('%Y',a."PublishTime") = '2021'`，即前后都为char，在c#中表示应该类似为
```where.And(x => x.PublishTime.Year == "2021");```
但是由于数据类型不一致，无法编译通过。

#### 数据库的具体版本

Sqlite

#### 安装的包

FreeSql.All  2.5.100

#### .net framework/. net core？ 及具体版本

.Net5

**Comment by luoyunchong** [comment]
`where.And(x => x.PublishTime.Year.ToString() == "2021");` 测试 没问题。

**Comment by luoyunchong** [comment]
sqlite  `strftime('%m',a."CreateTime")`  查出来的数据 是06 而不是 6 。所以这个时间处理上还是有问题。
