### ISSUE TITLE
在sqlserver中，条件表达式中的”枚举.tostring()“会被意外解析为cast(x as nvarchar)

### ISSUE THREAD

**Issue by LiuFu2014** [dotnetcore/FreeSql#806]
#### 问题描述及重现步骤：
1. 使用仓储模式进行where条件查询
2. 在where条件查询中，使用枚举.tostring()，比如 OrderRepository.where(t=>t.Code = OrderType.ReceiptOrder.ToString()).ToList();此方式会被解析为 “WHERE (a.[Code] = cast(5 as nvarchar(100)))”

#### 数据库的具体版本
```
sqlserver2012
```

#### 安装的包
```
Freesql
Freesql.DbContext
FreeSql.Provider.SqlServer
版本均为2.5.2
```

#### .net framework/. net core？ 及具体版本
```
.net framework 4.8
```

### 备注
同样在mysql5.7数据库上，枚举可以正常被解析成字符串

**Comment by 2881099** [comment]
有表达式树里，有人需求转换成数值，有人需求转化成 string。

你的情况快速解决方法：

```c#
var code = OrderType.ReceiptOrder.ToString();

...Where(t => t.Code == code).ToList();
```

下个版本解决枚举 .ToString 的解析，应该转成字符串。

**Comment by 2881099** [comment]
.Where(a => object.Equals(a.Code, OrderType.ReceiptOrder))
