### ISSUE TITLE
MySql时间列数值为0000-00-00 00:00:00，会提示转换类型错误

### ISSUE THREAD

**Issue by coolqingcheng** [dotnetcore/FreeSql#808]
在MySQL中，如果列为时间，手动插入一条值为0000-00-00 00:00:00的数据，那么查询的时候，会报错

**Comment by luoyunchong** [comment]
System.FormatException:“String '000-00-00 00:00:00' was not recognized as a valid DateTime.”

![image](https://user-images.githubusercontent.com/18613266/123248885-020a6100-d51b-11eb-8362-1af747d21a78.png)


DateTime.MinValue 值也是 {0001/1/1 0:00:00}
