### ISSUE TITLE
FreeSQL连接Access数据库，连接不成功！

### ISSUE THREAD

**Issue by fan0217** [dotnetcore/FreeSql#819]
报错：【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误

IFreeSql 声明：
` public static IFreeSql FSql { get; } = new FreeSql.FreeSqlBuilder()
              .UseConnectionString(FreeSql.DataType.MsAccess, "Provider=Microsoft.Jet.OleDb.4.0; D:\\data.mdb")
              .UseAutoSyncStructure(true) //自动同步实体结构到数据库
              .Build();`

**Comment by densen2014** [comment]
应该没问题的, 你试试我的测试代码:

using FreeSql.DataAnnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;

namespace FreeSqlDemos
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var fsql = new FreeSql.FreeSqlBuilder()
            //.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=document.db; Pooling=true;Min Pool Size=1")
            .UseConnectionString(FreeSql.DataType.Sqlite, "Provider=Microsoft.Jet.OleDb.4.0;Data Source=document.mdb")
            .UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
            .UseMonitorCommand(cmd => Console.Write(cmd.CommandText))
            .Build();

            var r = new Random();

            var ItemList = new List<Item>()
            {
                new Item {  Text = "假装 First item" , Description="This is an item description." },
                new Item {  Text = "的哥 Second item", Description="This is an item description." },
                new Item { Text = "四风 Third item", Description="This is an item description." },
                new Item {  Text = "加州 Fourth item", Description="This is an item description." },
                new Item { Text = "阳光 Fifth item", Description="This is an item description." },
                new Item {  Text = "孔雀 Sixth item - "+ r.Next(11000).ToString(), Description="This is an item description." }
            };

            if (fsql.Select<Item>().Count() <100)
            {
                fsql.Insert<Item>().AppendData(ItemList).ExecuteAffrows();
            }
            ItemList = fsql.Select<Item>().ToList();


            Console.WriteLine("\r\n\r\nItemListCount: " + ItemList.Count());
            Console.WriteLine("\r\n\r\nLastItem: " + ItemList.Last().Text);


        }
    }


    public class Item
    {
        [Column(IsIdentity = true)]
        [DisplayName("序号")]
        public int Id { get; set; }

        [DisplayName("名称")]
        public string Text { get; set; }

        [DisplayName("描述")]
        public string Description { get; set; }
    }

}

**Comment by fan0217** [comment]
访问Access，为什么用的是FreeSql.DataType.Sqlite，而不是FreeSql.DataType.MsAccess？


以下是您提供的代码：
var fsql = new FreeSql.FreeSqlBuilder()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;//.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=document.db; Pooling=true;Min Pool Size=1")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.UseConnectionString(FreeSql.DataType.Sqlite, "Provider=Microsoft.Jet.OleDb.4.0;Data Source=document.mdb")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.UseMonitorCommand(cmd =&gt; Console.Write(cmd.CommandText))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.Build();

**Comment by fan0217** [comment]
你提供的：
var fsql = new FreeSql.FreeSqlBuilder()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;//.UseConnectionString(FreeSql.DataType.Sqlite, "Data Source=document.db; Pooling=true;Min Pool Size=1")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.UseConnectionString(FreeSql.DataType.Sqlite, "Provider=Microsoft.Jet.OleDb.4.0;Data Source=document.mdb")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.UseMonitorCommand(cmd =&gt; Console.Write(cmd.CommandText))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;.Build();


自动创建的数据库实际上是SQLite（只是改变了一个后缀），并不是Access，如果用FreeSql.DataType.MsAccess，依然连接不上。
