### ISSUE TITLE
IDbFirst有获取原数据库的存储过程/视图/触发器的计划么？

### ISSUE THREAD

**Issue by zcy6187** [dotnetcore/FreeSql#82]
如果能够获取存储过程/视图/触发器，可以很方便的编写基于Freesql的代码开发平台。希望各位大神考虑一下。

**Comment by 2881099** [comment]
视图现在应该可以的，存储过程触发器目前不行。谢谢支持

**Comment by zcy6187** [comment]
大部分传统行业需要的软件，还是基于数据库的。如果Freesql可以获取数据库的这些关键信息，还可以开发趁手的自定义运维工具。肯定相当有市场。

**Comment by 2881099** [comment]
哈哈，这样有些偏题了
