### ISSUE TITLE
使用HasData不能添加种子数据

### ISSUE THREAD

**Issue by siwliwuhen** [dotnetcore/FreeSql#823]
代码如下:
IFreeSql fsql = new FreeSqlBuilder()
                .UseConnectionString(DataType.MySql, Configuration.GetConnectionString("MYSQL_DB1"))
                .UseAutoSyncStructure(true)
                .Build();
 fsql.CodeFirst.SyncStructure<doorconfig>();
            //种子数据
            fsql.CodeFirst.Entity<doorconfig>(eb =>
            {
                eb.HasData(new List<doorconfig>() { new doorconfig() { name = "ceshi" } });
            });

**Comment by luoyunchong** [comment]
原来是这么用的。先设置种子数据，后设置同步表结构。

```
            fsql.CodeFirst.Entity<NewClass>(eb =>
            {
                eb.HasData(new List<NewClass>() { new NewClass() { Name = "ceshi" } });
            });
            fsql.CodeFirst.SyncStructure<NewClass>();
```
