### ISSUE TITLE
Freesql-postgresql   xml类型的bug

### ISSUE THREAD

**Issue by worldofchu** [dotnetcore/FreeSql#824]
#### 问题描述及重现步骤：
正常使用freesql-postgresql 其中某表字段 为xml类型，进行insert操作报错42804: column "myxml" is of type xml but expression is of type character varying
是不是 postgresql的xml类型没有支持，因为已经设置实体特性的dbtype="xml"，但是 还是保存报错 期望xml实际上是varchar，我搜了master的源码 根本没发现类型 NpgsqlDbType.xml
#### 数据库的具体版本
```

```

#### 安装的包
```
最新稳定版本freesql
```

#### .net framework/. net core？ 及具体版本
```
net6
```

**Comment by Every-days** [comment]
> #### 问题描述及重现重现：
> 正常使用freesql-postgresql 因为某个表字段为xml类型，进行插入操作报错42804: column "myxml" is of type xml but expression is of type character variables 是不是postgresql的xml类型没有支持，已经设置了特性的dbtype ="xml"，但还是保存了报错的需求xml实际上是varchar，我搜到了master的源码根本没发现类型NpgsqlDbType.xml
> 
> #### 数据库的具体版本
> ```
> 
> ```
> 
> #### 安装包
> ```
> 最新稳定版本freesql
> ```
> 
> #### .net 框架/. net core？ 及具体版本
> ```
> net6
> ```



> #### 问题描述及重现重现：
> 正常使用freesql-postgresql 因为某个表字段为xml类型，进行插入操作报错42804: column "myxml" is of type xml but expression is of type character variables 是不是postgresql的xml类型没有支持，已经设置了特性的dbtype ="xml"，但还是保存了报错的需求xml实际上是varchar，我搜到了master的源码根本没发现类型NpgsqlDbType.xml
> 
> #### 数据库的具体版本
> ```
> 
> ```
> 
> #### 安装包
> ```
> 最新稳定版本freesql
> ```
> 
> #### .net 框架/. net core？ 及具体版本
> ```
> net6
> ```

问下，最后怎么解决的
