### ISSUE TITLE
网上看到的关于FreeSql的性能的一个问题。

### ISSUE THREAD

**Issue by athinboy** [dotnetcore/FreeSql#828]
网上看到一篇文章，不知道是否有用，请留意。
https://www.cnblogs.com/ningyouyou/p/14206554.html

**Comment by 2881099** [comment]
where 参数化默认没有开启，可以开启的，写文章的人没研究透。

就是说，FreeSql 可以参数化，也可以不参数化。

SET NOCOUNT ON 不能说 EF 性能好，因为事实它的性能并不好，反推想一下 dapper 没执行这个。

**Comment by athinboy** [comment]
多谢！
@2881099 希望freesql加强推广，早日完成国际化！
