### ISSUE TITLE
DisableSyncStructure

### ISSUE THREAD

**Issue by shishirong** [dotnetcore/FreeSql#829]
#### Feature 特性
想要FreeSql.Generator 能有设置DisableSyncStructure默认值的选项。

**Comment by densen2014** [comment]
fsql build 直接不开同步结构不行吗

**Comment by luoyunchong** [comment]
运行一次后，会生成一个bat和一个cshtml。可以直接修改模板来实现。

**Comment by shishirong** [comment]
> fsql build 直接不开同步结构不行吗

因为从普通使用者的角度，通常使用的是dotnet tool install -g FreeSql.Generator的，并不自己编译。

**Comment by densen2014** [comment]
默认就是关闭的, 
`.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】，FreeSql不会扫描程序集，只有CRUD时才会生成表。`
你默认别打开, 需要同步的时候再手动同步结构就好了

**Comment by shishirong** [comment]
> 默认就是关闭的,
> `.UseAutoSyncStructure(true) //自动同步实体结构【开发环境必备】，FreeSql不会扫描程序集，只有CRUD时才会生成表。`
> 你默认别打开, 需要同步的时候再手动同步结构就好了

我的意思是用FreeSql.Generator从数据库生成实体类的时候，生成的实体类的DisableSyncStructure特性可以通过参数来设定。
