### ISSUE TITLE
oracle的支持

### ISSUE THREAD

**Issue by slcboy** [dotnetcore/FreeSql#830]
工具FreeSql.Tools-1.0.0对oracle生成Model无效, tree的菜单是无法展开的.

**Comment by luoyunchong** [comment]
可能表太多了，展开很慢。。之前用过几次，支持的。oracle 版本多少。

**Comment by slcboy** [comment]
oracle 是11.2.0.4.0的版本。


你确定是可以展开？？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/FreeSql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/FreeSql] oracle的支持 (#830)





 
可能表太多了，展开很慢。。之前用过几次，支持的。oracle 版本多少。

**Comment by luoyunchong** [comment]
可以展开，能在tree上看到表。。

**Comment by slcboy** [comment]
是用的dskin,还是winform? 那个加载不要太慢了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/FreeSql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午12:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/FreeSql] oracle的支持 (#830)





 
可以展开，能在tree上看到表。。
