### ISSUE TITLE
能否增加插入根据字典 或dto 如更新那样 后台不需要把dto 转为实体

### ISSUE THREAD

**Issue by linchengzong** [dotnetcore/FreeSql#833]
能否增加插入根据字典 或dto 如更新那样 后台不需要把dto 转为实体

#### 简要描述原因
因为后台dto 转为实体的时候，如果字段是字符串类型还好，如果碰到的是数字型 默认会变成0 但是实际是想根据前端传过来的dto 或者字典直接插入 不需要进行实体转化,我在SqlSugar 看到有这样的功能

**Comment by 2881099** [comment]
```c#
int?

byte?

long?

DateTime?
```

**Comment by 2881099** [comment]
新版本 fsql.InsertDct 方法可以插入字典
