### ISSUE TITLE
讨论：graphql、事务撤销

### ISSUE THREAD

**Issue by fawdlstty** [dotnetcore/FreeSql#84]
graphql是一种查询语言，感觉加入对这种语言的支持后，对于后端会非常省事，同样也便于前端调试与开发。地址：<https://github.com/graphql-dotnet/graphql-dotnet>

---

事务撤销对于需要精确控制的场合，比如修改name的值，执行前生成逆向sql，具体步骤为查询name的值，并生成逆向操作sql。示例

| id | name |
| --- | --- |
| 1 | kangkang |

假如待执行sql为：`update t set name = 'michael' where id = 1`

那么生成逆向sql为：`update t set name = 'kangkang' where id = 1`

用于在事务失败时执行撤销

**Comment by 2881099** [comment]
万一撤销的语句执行错误怎么办

**Comment by fawdlstty** [comment]
通过钉钉或短信通知运维。。。

**Comment by 2881099** [comment]
感觉上除非该行锁住，不给其他程序再次修改。不然回滚错误后，其他程序又update了该行。。。

**Comment by fawdlstty** [comment]
这种模式一般用于cqrs；对于command的执行使用单线程处理的方式来说，本身不会有什么问题

**Comment by 2881099** [comment]
好的，没有明白你的原意，是想 FreeSql 支持回滚后执行的操作？还是支持 graphsql 的设计？

**Comment by fawdlstty** [comment]
我觉得这个项目可以考虑支持graphql的查询操作，以及事务回滚操作

**Comment by 2881099** [comment]
https://github.com/dlukez/graphql-dotnet-annotations

这两天在看相关资料，看到了这个库。

graphql 和 这个都不依赖 ef，这个看上去用起来比较简单，打特性就可以了。

**Comment by 2881099** [comment]
https://github.com/graphql-dotnet/conventions

这个看上去也挺简单

**Comment by fawdlstty** [comment]
我最近想了下，事物撤销没有应用价值。graphql用于，表中column较多，但需要读取的字段较少的情况，在查询时只查询需要用到的内容，然后通过DTO或类似方式传输给目标对象

**Comment by 2881099** [comment]
但是直接把请求方的内容转成查询，也很危险。graphql scheme 可以自动生成，但不安全。

**Comment by fawdlstty** [comment]
虽然看起来不安全，但安全性似乎不应该是底层库所应该考虑的事务。毕竟底层库设计的再安全，上层也能用的天花乱坠
