### ISSUE TITLE
代码生成工具无法读取到Oracle视图数据

### ISSUE THREAD

**Issue by ljg20150305** [dotnetcore/FreeSql#840]
![image](https://user-images.githubusercontent.com/11326150/128284580-0438e0ce-d399-4f70-af5c-4116b0f2c3b1.png)
代码生成工具生成Oracle实体时会默认加上当前登录用户为条件，但实际上我得视图得Owner是不属于链接字符串配置得用户得

**Comment by luoyunchong** [comment]
只能获取当前userid下的数据库，视图。

想要获取其他userid下的视图，自然要指定对应 的uesrid.

**Comment by ljg20150305** [comment]
关键是现在没有指定用userid的参数，所以导致这种情况就没办法使用了，是否可以追加一个userid的可配选项呢？

**Comment by luoyunchong** [comment]
连接串的userid

**Comment by ljg20150305** [comment]
但是我现在就是遇到这种视图不是链接串配置得用户这种情况呢，这种情况要怎么解决呢？视图和表都属于别的用户，但是我有权限读取它，我觉得对于生成工具来说没必要限制一定要当前用户吧？是否可以增加一个可配选项呢？

**Comment by luoyunchong** [comment]
#845  因该参数schema无法正常获取，所以在oracle下的其他用户的表、views无法获取。

**Comment by ljg20150305** [comment]
好的，查了下，是oracle的原因。
