### ISSUE TITLE
FreeSql.Select<object>().AsType(type)动态查询bug

### ISSUE THREAD

**Issue by 835718973** [dotnetcore/FreeSql#855]
![image](https://user-images.githubusercontent.com/20808204/129876970-ed0c836d-ba4c-4475-b5d6-4a59c0a97cf0.png)
Object of type 

'System.Linq.Expressions.Expression1`1[System.Func`2[Hy.Items.Entity.Items.Item,System.Collections.Generic.IEnumerable`1[Hy.Items.Entity.WorkOrderRules.WorkOrderRuleDetail]]]' 

cannot be converted to type 

'System.Linq.Expressions.Expression`1[System.Func`2[System.Object,System.Collections.Generic.IEnumerable`1[Hy.Items.Entity.WorkOrderRules.WorkOrderRuleDetail]]]'.

```c#

ISelect<object> select = freeSql.Select<object>().AsType(type);
        Expression<Func<object, object>> selExp = null;
        if (criteria != null)
        {
            if (!criteria.Filter.IsNullOrEmpty())
            {
                select.WhereDynamicFilter(criteria?.Filter);
            }

            if (!criteria.IncludePropertys.IsNullOrEmpty())
            {
                foreach (string property in criteria.IncludePropertys)
                {
                    select.IncludeByPropertyName(property);
                }
            }
}
```

当freeSql.Select<object>().AsType(type)来动态查询一个类型时,指定的IncludeByPropertyName的参数如果是指向一个list集合，就会产生一个类型转换错误，如截图下方所示,在使用asType以后,应该以动态指定的类型未准吧.
我不确定这是否是一个bug或者有其它考量，希望能尽快有一个好的解决方案。

**Comment by 2881099** [comment]
能提供一下完整的测试 demo 吗

**Comment by 835718973** [comment]
freesql实例创建
`private IFreeSql freesql = new FreeSqlBuilder()//初始化FreeSql
            .UseConnectionString(DataType.Oracle, "user id=FREESQLTEST;password=FREESQLTEST;data source=xxx.xxx.xxx.xxx/entire; Pooling=true;min pool size=5;max pool size=100;")
            .UseAutoSyncStructure(true)
            .UseGenerateCommandParameterWithLambda(true)
            .UseNoneCommandParameter(false)
            .Build();`
单元测试代码:
`
        [Test()]
        public void IncludePropertyTest()
        {
            try
            {
                freesql.Aop.CommandBefore += (o, e) =>
                {

                };
                var type = typeof(Person);
                var select = freesql.Select<object>().AsType(type);
                select.IncludeByPropertyName(nameof(Person.AddressList));
                var p = select.ToOne();
            }catch(Exception ex)
            {

            }
        }
`

**Comment by 2881099** [comment]
请上传一下 console app 项目，可以直接运行的，谢谢。

**Comment by 835718973** [comment]
[FreeSqlIncludePropertyTest.zip](https://github.com/dotnetcore/FreeSql/files/7102528/FreeSqlIncludePropertyTest.zip)
@2881099

**Comment by 2881099** [comment]
新版本已解决
