### ISSUE TITLE
是否可以把注解独立出来

### ISSUE THREAD

**Issue by sevencat** [dotnetcore/FreeSql#861]
#### Feature 特性
注解独立出来为一个包

#### 简要描述原因
减少依赖性

#### 使用场景
有时候有的实体定义包需要给其他项目用，单独的注解包就可以解决，不用带上整个大包。

**Comment by 2881099** [comment]
这个建议以前讨论过，维护问题不适合拆得太细。

**Comment by luoyunchong** [comment]
用类似这种操作，单独打个包?
```
<ItemGroup>
	 <Compile Include="../FreeSql.Provider.MySql/**/*.cs" Exclude="../FreeSql.Provider.MySql/obj/**/*" />
</ItemGroup>
```
https://github.com/dotnetcore/FreeSql/blob/master/Providers/FreeSql.Provider.MySqlConnector/FreeSql.Provider.MySqlConnector.csproj

**Comment by luoyunchong** [comment]
bin单独引用
[FreeSql.DataAnnotations.zip](https://github.com/dotnetcore/FreeSql/files/7210012/FreeSql.DataAnnotations.zip)

代码，可直接放到同FreeSql目录,自行编译。
[FreeSql.DataAnnotations202109221850.zip](https://github.com/dotnetcore/FreeSql/files/7210026/FreeSql.DataAnnotations202109221850.zip)

![image](https://user-images.githubusercontent.com/18613266/134330860-a9b70fc5-a7a2-48cc-91b8-3b5053960524.png)

实际 代码仅

```
	<ItemGroup>
		<Compile Include="../FreeSql/DataAnnotations/ColumnAttribute.cs" Link="DataAnnotations/ColumnAttribute.cs"></Compile>
		<Compile Include="../FreeSql/DataAnnotations/IndexAttribute.cs" Link="DataAnnotations/IndexAttribute.cs"></Compile>
		<Compile Include="../FreeSql/DataAnnotations/TableAttribute.cs" Link="DataAnnotations/TableAttribute.cs"></Compile>
		<Compile Include="../FreeSql/DataAnnotations/NavigateAttribute.cs" Link="DataAnnotations/NavigateAttribute.cs"></Compile>
		<Compile Include="../FreeSql/DataAnnotations/Special/OraclePrimaryKeyNameAttribute.cs" Link="DataAnnotations/Special/OraclePrimaryKeyNameAttribute.cs"></Compile>
	</ItemGroup>

```
