### ISSUE TITLE
DisableGlobalFilter 失败原因？

### ISSUE THREAD

**Issue by yaobo-lab** [dotnetcore/FreeSql#862]
#### 数据库的具体版本
```

```

#### 安装的包
```
2.5200
```

#### .net framework/. net core？ 及具体版本
```
5.0
```

`         
 
 
   var sql = _fsql.Select<BillItem>().DisableGlobalFilter("SoftDelete").
                    Where(m => m.BillDateInt <= job.BillDate && m.IsDel > 0).
                    Limit(2000).ToUpdate().Set(m => m.IsDel, 0).ToSql();

            sql = _fsql.Select<BillItem>().
              Where(m => m.BillDateInt <= job.BillDate && m.IsDel > 0).
              Limit(2000).ToUpdate().Set(m => m.IsDel, 0).DisableGlobalFilter("SoftDelete").ToSql();

`

如上两句 DisableGlobalFilter 都会失效果原因是？

**Comment by 2881099** [comment]
ToUpdate，没复盖测试

**Comment by 2881099** [comment]
```c#
sql = _fsql.Select<BillItem>()
     .DisableGlobalFilter("SoftDelete")
     .Where(m => m.BillDateInt <= job.BillDate && m.IsDel > 0)
    .Limit(2000)

    .ToUpdate().DisableGlobalFilter("SoftDelete")
    .Set(m => m.IsDel, 0).ToSql();
```

暂时先这样吧

**Comment by yaobo-lab** [comment]
> ```cs
> sql = _fsql.Select<BillItem>()
>      .DisableGlobalFilter("SoftDelete")
>      .Where(m => m.BillDateInt <= job.BillDate && m.IsDel > 0)
>     .Limit(2000)
> 
>     .ToUpdate().DisableGlobalFilter("SoftDelete")
>     .Set(m => m.IsDel, 0).ToSql();
> ```
> 
> 暂时先这样吧

thx
