### ISSUE TITLE
缺少EF里的字段并发控制

### ISSUE THREAD

**Issue by wangronghua** [dotnetcore/FreeSql#863]
#### Feature 特性
字段的并发控制属性，类似EF里的ConcurrencyCheck

#### 简要描述原因
比如金额、积分字段，更新时需要防止并发覆盖，RowVersion乐观锁粒度太大了。

**Comment by 2881099** [comment]
```c#
fsql.Update<T>()
.Where(a => a.Id == 1 && a.Field == oldvalue)
.Set(a => a.Field, newvalue)
.ExecuteAffrows();
```

**Comment by EternityTeam** [comment]
应配合一个表的操作结果(ExecuteAffrows 乐观锁)使用事务更新金额/积分字段

**Comment by 2881099** [comment]
我觉得这种并发字段的控制，颗粒度不需要全局，局部需要时处理就好。

谁也不能保证整个应用程序内的更新，都需要控制并发。
