### ISSUE TITLE
为code first模式加入外键约束

### ISSUE THREAD

**Issue by truemogician** [dotnetcore/FreeSql#864]
通过导航属性实现级联操作是个好办法，但缺乏数据库自身的外键约束会埋下隐患，比如当插入数据的外键数据不存在于关联表中时，有外键约束的话数据库会报错，但没有就会被视为合法数据；此外缺乏外键导致数据库完全依赖FreeSql框架，如果出于某些原因需要换用其他ORM或者写一些SQL，会带来极大的麻烦。  
导航属性的逻辑和外键非常相似，更何况db first模式已经支持了外键到导航属性的迁移，所以何不把code first的导航属性也同步写入数据库的外键约束呢？

**Comment by 2881099** [comment]
在空表、空数据的时候，外键管理很容易。

在已经有表数据的情况下，外键的重建管理成本相当麻烦。没有外键的情况下可能只需要处理1个表结构+数据，返之可能需要同时处理1-10个表结构+数据，更容易丢失数据。

**Comment by truemogician** [comment]
但code first不就是空表空数据么？你是在考虑如果加了外键，已经用code first做出来的项目升级到新版的问题么？

**Comment by 2881099** [comment]
> 但code first不就是空表空数据么？你是在考虑如果加了外键，已经用code first做出来的项目升级到新版的问题么？

是的

**Comment by truemogician** [comment]
或许可以考虑把CodeFirst外键做成一个单独的Package？这样已有项目升级也不会受到影响了
