### ISSUE TITLE
PostgreSQL及其衍生仓库对于基类非int的枚举类的转换问题

### ISSUE THREAD

**Issue by truemogician** [dotnetcore/FreeSql#875]
在添加或更新记录时，如果其中的枚举类基类不是默认的int，会发生类型转换错误   
Bug的根源：[PostgreSQLUtils](https://github.com/dotnetcore/FreeSql/blob/540f2251b3761bc0caeb2e2894b67272d101f659/Providers/FreeSql.Provider.PostgreSQL/PostgreSQLUtils.cs#L87)  
将`(int)value`改成`Convert.ChangeType(value, Enum.GetUnderlyingType(value.GetType()))`应该就可以解决

**Comment by 2881099** [comment]
好的，我这边综合考虑一下，参考你给的 PR 。
