### ISSUE TITLE
一对多导航属性无法生效

### ISSUE THREAD

**Issue by jinghuian** [dotnetcore/FreeSql#880]
#### 问题描述及重现步骤：
 [JsonProperty]
  [Navigate(nameof(BP_BARCODE_QUEUE.BQ_BARCODE_PACK_ID))]
  public virtual List<BP_BARCODE_QUEUE> BarCodesInfo { get; set; }
--未报异常
 var s = _freeSql.CodeFirst.GetTableByEntity(typeof(BP_BARCODE_PACK)).GetTableRef("BarCodesInfo", true);

#### 数据库的具体版本
```
sql server 2008
```

#### 安装的包
```
FreeSql
FreeSql.DbContext
FreeSql.Provider.SqlServer
FreeSql.Repository
```

#### .net framework/. net core？ 及具体版本
```
 .net framework 4.7
```

**Comment by luoyunchong** [comment]
详细说明
