### ISSUE TITLE
ColumnAttribute 与TableAttribute 增加描述字段

### ISSUE THREAD

**Issue by athinboy** [dotnetcore/FreeSql#883]
#### Feature 特性
ColumnAttribute 与TableAttribute 增加描述字段，对应数据库里面的列注释和表注释。

#### 简要描述原因

列描述和表描述不可或缺。
才用freesql，可能有其他方式实现。

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/wiki/CodeFirst#%E5%A4%87%E6%B3%A8

**Comment by athinboy** [comment]
@luoyunchong  谢谢。
