### ISSUE TITLE
未来会支持二级缓存吗？

### ISSUE THREAD

**Issue by Dishone** [dotnetcore/FreeSql#887]
未来会支持二级缓存吗？类似于 EFCore + https://github.com/VahidN/EFCoreSecondLevelCacheInterceptor

**Comment by 2881099** [comment]
缓存，可以看下 FreeRedis，CSRedisCore，和 FreeSql 一个作者

**Comment by sgf** [comment]
> 缓存，可以看下 FreeRedis，CSRedisCore，和 FreeSql 一个作者

Redis是Redis，并不是每个项目都有上redis的条件的。
