### ISSUE TITLE
希望可以增加一种实体映射模式，字段对象只映射其中一个字段到数据库，表列名还是码表字段名

### ISSUE THREAD

**Issue by kensmaster** [dotnetcore/FreeSql#890]
比如：public CodeTable Sex{get;set;}  这里Sex就是一个码表字段
下面这个对象是所有码表字段通用对象
public class CodeTable {
public string Code{get;set;} 该字段用于保存数据库，如：1,2,3
public string Name{get;set;} 该字段用于其他表解析Code返回页面显示
}
请看EF实现：
//UserInfo
var myUserInfo = builder.Entity().ToTable("UserInfo", "public");
myUserInfo.Property(e => e.Sex.Code).HasColumnName("Sex");
myUserInfo.Property(e => e.FactoryType.Code).HasColumnName("FactoryType");
myUserInfo.Property(e => e.Dept.Code).HasColumnName("Dept");
myUserInfo.Property(e => e.LineType.Code).HasColumnName("LineType");

**Comment by kensmaster** [comment]
目前FreeSql这么用会提示找不到属性Code
fsql.CodeFirst.Entity(a=>{
a.Property(e => e.Sex.Code).HasColumnName("Sex");
});

**Comment by 2881099** [comment]
暂时不支持
