### ISSUE TITLE
命名空间不一致导致方法或属性具有二义性

### ISSUE THREAD

**Issue by wtujvk** [dotnetcore/FreeSql#899]
#### Feature 特性
可能导致系统命名空间污染。

#### 简要描述原因
一下方法或属性具有二义性。
系统的命名空间，例如System.Linq.Expressions 建议改为 FreeSql.Expressions等

![image](https://user-images.githubusercontent.com/17868266/136136930-de805146-9a0d-4d99-9dd4-9f6222c28eb1.png)

#### 使用场景
扩展方法命名空间不一致引发二义性问题。

**Comment by luoyunchong** [comment]
参考

[https://github.com/dotnet/aspnetcore/blob/main/src/Caching/SqlServer/src/SqlServerCachingServicesExtensions.cs#L9](https://github.com/dotnet/aspnetcore/blob/main/src/Caching/SqlServer/src/SqlServerCachingServicesExtensions.cs#L9)

一般遵循扩展类所在命名空间。

**Comment by hjkl950217** [comment]
目前应该是针对谁扩展，命名空间就和它一样，然后在方法上面做区分。。比如系统有where,然后在同样命名空间下扩展出了whereIf。
