### ISSUE TITLE
where过滤外键count报错

### ISSUE THREAD

**Issue by zsq1576154634** [dotnetcore/FreeSql#903]
#### 问题描述及重现步骤：

查询时通过where过滤外键列表数量时提示找不到列Count，
![image](https://user-images.githubusercontent.com/52565295/136651004-3fbe8b57-1eb0-46ac-a245-8711665e0635.png)
![image](https://user-images.githubusercontent.com/52565295/136651033-0636fb6e-aed3-4b60-b1da-22a785469dd3.png)
![image](https://user-images.githubusercontent.com/52565295/136651046-f9187e77-0f71-4724-a9c2-4bd55c871ddf.png)
![image](https://user-images.githubusercontent.com/52565295/136650992-2b5470e3-2ce2-4fc8-8d09-eed8778233e5.png)

#### 数据库的具体版本
```
mysql 5.6
```

#### 安装的包
```freesql 2.6.1

```

#### .net framework/. net core？ 及具体版本
```.net 6

```

**Comment by luoyunchong** [comment]
使用`AsSelect()`
```csharp
var d1 = _userRepository.Select.IncludeMany(r => r.LinGroups).Where(r => r.LinGroups.AsSelect().Any()).ToList();
var d2 = _userRepository.Select.IncludeMany(r => r.LinGroups).Where(r => r.LinGroups.AsSelect().Count() > 0).ToList();
```
