### ISSUE TITLE
如果ToList的vm中，与数据库字段名相同，但vm中的字段类型不同，会导致类型转换错误。

### ISSUE THREAD

**Issue by sdwdjzhy** [dotnetcore/FreeSql#904]
#### 问题描述及重现步骤：
如果ToList的vm中，与数据库字段名相同，但vm中的字段是只读的并类型不同，会导致类型转换错误。
加了` [Column(IsIgnore = true)]` 也不行
按道理，我项目中的type 只有 get属性，不应该会加入到数据库的搜索字段中

具体项目查看： https://gitee.com/sdwdjzhy/TestFreesql
#### 数据库的具体版本
```
sql server  11.0.3156.0
```

#### 安装的包
```
FreeSql.Provider.SqlServer  2.6.100
```

#### .net framework/. net core？ 及具体版本
```
.net framework 4.7.2
.net core 5.0
```

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/137057945-42659cf5-a4c4-4de2-9ffc-0c75584bb7ea.png)

因为有映射规则，如果使用主键的构造函数，会只映射部分字段，未取的字段不会映射。
如果直接像你那种操作，会取所有字段。赋值给对应的字段，类型自然要一致。
```
     var list1 = Fsql.Select<tTest>().ToList(i => new tTestVM(i.Id) { Name = i.Name });
```

加构造函数
```
        public tTestVM(int id)
        {
            Id = id;
        }

        public tTestVM()
        {
        }
```

**Comment by sdwdjzhy** [comment]
额，好吧，确实没注意到还有这种操作。
不过要是没有主键的话，估计就挂了。我还是修改dto的字段名吧
