### ISSUE TITLE
MsAccess中根据时间查询会报:“标准表达式中数据类型不匹配。“的错误,调试拿到SQL后发现SQL有误。

### ISSUE THREAD

**Issue by Wenchel** [dotnetcore/FreeSql#912]
#### 问题描述及重现步骤：
数据库为MsAccess，在使用`await _dbAccess.Select<Entity>().Where(it=>it.Date>=_config.StartTime && it.Jiaozhahao==0).ToListAsync();`报”标准表达式中数据类型不匹配。“的错误：
![image](https://user-images.githubusercontent.com/27775368/138375997-abb9d4cc-990b-4d6c-9c57-12356b0f49ae.png)

调试拿到其SQL为：  
```
SELECT a.[SerialNumber], a.[Date], ......
FROM [testresult] a 
WHERE (a.[Date] >= '2021-10-01 00:00:00' AND a.[Jiaozhahao] = 0)
```
经过查询后发现在Access使用时间比较大小时，时间需要用#括起来，即`a.[Date] >= '2021-10-01 00:00:00'`为`a.[Date] >= #2021-10-01 00:00:00#`，尝试使用SQL直接去访问，代码大致如下：
```
await _dbAccess.Ado.QueryAsync<Entity>(@"SELECT a.[SerialNumber], a.[Date]...
FROM[testresult] a
WHERE(a.[Date] >= #2021-10-01 00:00:00# AND a.[Jiaozhahao] = 0)");
```
返回正确的结果：
![image](https://user-images.githubusercontent.com/27775368/138376176-b4c97b8c-411c-4856-9802-b03415a90f3d.png)

#### 数据库的具体版本

Microsoft Access，版本较老，需要使用2007及以下的Access才能打开。

#### 安装的包
```
2.6.100
```

#### .net framework/. net core？ 及具体版本
```
.net framework 4.8
```

**Comment by Wenchel** [comment]
> 【自定义表达式解析】
> 
> ```cs
> [ExpressionCall]
> public static class DbFunc
> {
>   //必要定义 static + ThreadLocal
>   static ThreadLocal<ExpressionCallContext> context = new ThreadLocal<ExpressionCallContext>();
> 
>   public static DateTime ToMsAccessDate(this DateTime that)
>   {
>     var up = context.Value;
>     if (up.DataType == FreeSql.DataType.MsAccess) //重写内容
>     {
>       var valueStr = up.ParsedContent["that"];
>       if (valueStr.StartsWith("'") && valueStr.EndsWith("'"))
>         up.Result = $"#{valueStr.Trim('\'')}#";
>     }
>     return that;
>   }
> }
> 
> var date = DateTime.Now;
> var sql1 = fsql.Select<SysModule>()
>   .ToSql(a => a.CreateTime >= date.ToMsAccessDate());
> ```

谢谢老板解答，已经使用自定义方式

**Comment by hd2y** [comment]
AOP 的方案：
```cs
freeSql.Aop.ParseExpression += (s, e) =>
{
    if (freeSql.Ado.DataType == DataType.MsAccess && !e.Expression.IsParameter())
    {
        var val = e.Expression.GetConstExprValue();
        if (val is DateTime date)
        {
            e.Result = $"#{date.ToString("yyyy-MM-dd HH:mm:ss")}#";
        }
        else if (val is TimeSpan time)
        {
            e.Result = $"#{time.ToString(@"hh\:mm\:ss")}#";
        }
    }
};
```

`TimeSpan` 时间的比较查询会有问题，暂时不知道是不是写法不对，建议转成字符串后再做比较。
