### ISSUE TITLE
AsTreeCte 递归查询的where条件传变量时 无法正确生成sql 报错：必须声明标量变量 "@exp_0

### ISSUE THREAD

**Issue by hwjsun** [dotnetcore/FreeSql#922]
var name = "中国";
var t2 = fsql.Select<Area>()
  .Where(a => a.Name ==  name)  //假如这里赋值就没问题，使用变量就报错
  .AsTreeCte() //查询 中国 下的所有记录
  .OrderBy(a => a.Code)
  .ToTreeList();
使用ToSql() 可以发现 @exp_0 没有被赋值

**Comment by 981476460** [comment]
最后怎么解决的？我也遇到该问题了

**Comment by hwjsun** [comment]
自己拼接SQL吧。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月10日(星期一) 上午10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnetcore/FreeSql] AsTreeCte 递归查询的where条件传变量时 无法正确生成sql 报错：必须声明标量变量 ***@***.***_0 (Issue #922)





 
最后怎么解决的？我也遇到该问题了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 2881099** [comment]
有空了我测试一下，再回复

**Comment by 2881099** [comment]
已经解决了
