### ISSUE TITLE
ExecuteMySqlBulkCopy没有提供Aop.CurdBefore和Aop.CurdAfter事件

### ISSUE THREAD

**Issue by VicBilibily** [dotnetcore/FreeSql#926]
#### Feature 特性
ExecuteMySqlBulkCopy批量插入时能够提供Aop.CurdAfter事件

#### 简要描述原因
文件批量插入没有sql语句，但仍希望能够提供执行耗时通知。

#### 使用场景
开发测试阶段需要查验记录执行耗时，部署版本需要知道具体的慢语句以便做优化。

**Comment by 2881099** [comment]
BulkCopy 不支持 Aop.CrudBefore 事件
