### ISSUE TITLE
IEnumerable<string>类型竟然映射不出来字段？

### ISSUE THREAD

**Issue by bing-byte-9527** [dotnetcore/FreeSql#928]
#### 数据库的具体版本
```

```

#### 安装的包
```

```

#### .net framework/. net core？ 及具体版本

.net core 5.0

**Comment by bing-byte-9527** [comment]
用的是PostgreSQL，我有张表里一个字段用的是IEnumerable<string>类型，然后这个字段一直没生成出来，也没报错，换成 string[] 就可以了

**Comment by luoyunchong** [comment]
参考 类型映射  IEnumerable 不是基础类型。集合请参考 IEnumerable<实体类> 导航属性配置。 

https://github.com/dotnetcore/FreeSql/wiki/%e7%b1%bb%e5%9e%8b%e6%98%a0%e5%b0%84#%E9%BB%98%E8%AE%A4%E7%B1%BB%E5%9E%8B%E6%98%A0%E5%B0%84

**Comment by hjkl950217** [comment]
同意。。假如`IEnumerable `要支持。。那意味着相当多的类型都应该支持，而这不是大多数人需要的
