### ISSUE TITLE
CustomAdapter 重写UnicodeStringRawSql方法没有效果

### ISSUE THREAD

**Issue by rongguohao** [dotnetcore/FreeSql#929]
#### 问题描述及重现步骤：
   继承CustomAdapter  重写UnicodeStringRawSql方法没有效果  试了重写QuoteSqlNameLeft  和 QuoteSqlNameRight是可以的
    public class ClickHouseAdapter : FreeSql.Custom.CustomAdapter
    {

        public override char QuoteSqlNameLeft => '`';
        public override char QuoteSqlNameRight => '`';

        public override string UnicodeStringRawSql(object value, ColumnInfo mapColumn)
        {
            return value == null ? "NULL" : string.Concat("'",value.ToString().Replace("'", "''"), "'");
        }
    }

#### 安装的包
```
FreeSql.Provider.Custom  2.6.100
```

#### .net framework/. net core？ 及具体版本
```
.net core
```

**Comment by 2881099** [comment]
这个怎么重现，目前看到在 CustomAdo.cs 内是有调用该方法的。并且也是 virtual 来定义的

**Comment by rongguohao** [comment]
> 这个怎么重现，目前看到在 CustomAdo.cs 内是有调用该方法的。并且也是 virtual 来定义的

上次已经解决过了
