### ISSUE TITLE
人大金仓数据库连接异常

### ISSUE THREAD

**Issue by xuanhuangkeji** [dotnetcore/FreeSql#931]
#### 问题描述及重现步骤：
直接导入包FreeSql.Provider.KingbaseES
测试代码：
var connStr = "Server=xxxxxx;Port=60049;UID=system;PWD=123456;database=test;MAXPOOLSIZE=2";

            var fsql = new FreeSqlBuilder()
                .UseConnectionString(DataType.KingbaseES, connStr)
                .Build();

直接提示密码认证失败
若是使用OdbcKingbaseES，再导入odbc包会一直提示找不到没有数据源名称

另一个群里的朋友遇到的人大金仓的问题
![image](https://user-images.githubusercontent.com/10877862/140466725-7749e089-3ddf-47e8-9e55-d0665d92eeff.png)

#### 数据库的具体版本
KingbaseES V008R006C005B001

#### 安装的包
FreeSql.Provider.KingbaseES

#### .net framework/. net core？ 及具体版本
.net framework 4.5/4.6.1
.net 5

PS:直接从官方下载ndp包，然后覆盖对应的Kdbndp.dll，问题解决，可以正常运行
但是每次生成发布都会覆盖掉，都要重新覆盖

**Comment by 2881099** [comment]
如果有必要，请 PR 一下最新的 Kdbndp.dll

**Comment by luoyunchong** [comment]
https://www.kingbase.com.cn/qd/index.htm ado.net 驱动这里可以下载
