### ISSUE TITLE
一个常驻后台的持续性的任务如果持续的提交事务，会阻塞API接口的所有事务提交。

### ISSUE THREAD

**Issue by silentdance** [dotnetcore/FreeSql#932]
#### 问题描述及重现步骤：
1. 使用框架Asp.NET Core + autofac, 编写一个API程序，编写一个接口使用UnitOfWork更新DB。
2. 使用框架.Net Core + autofac编写一个控制台程序，使用UnitOfWork，持续的提交事务。
3. 先运行控制台程序，使之开始持续的提交事务。
4. 运行并调用Asp.Net Core的API接口，连续调用数次后，之后所有的事务提交会全部超时，并报异常 Connection must be valid and open to rollback transaction（Mysql 命令执行超时会报这个）。

#### 数据库的具体版本
```
MySql 5.7
```

#### 安装的包
```
FreeSql 2.6.100
FreeSql.DbContext 2.6.100
```

#### .net framework/. net core？ 及具体版本
```
.net core 3.1
```

**Comment by silentdance** [comment]
假如适用IFreeSql.Transaction则没有上述问题，但是又少了何时进行提交的操作细节。

**Comment by silentdance** [comment]
翻看文档，找到这样一句，也许这就是问题所在了，DotNetCore 应该安装的版本应该是FreeSql.Repository
环境1：.NET Core 或 .NET 5.0+
dotnet add package FreeSql.Repository

环境2、.NET Framework
Install-Package FreeSql.DbContext

**Comment by silentdance** [comment]
我会再关注这个问题，在测试环境稳定一段时间后再关闭这个Issue.

**Comment by silentdance** [comment]
然而好像并不行 -_-!

**Comment by luoyunchong** [comment]
只连续调用 api的接口，不执行那个定时任务，会报错吗。

二个包实际 一样。

**Comment by silentdance** [comment]
> 只连续调用 api的接口，不执行那个定时任务，会报错吗。
> 
> 二个包实际 一样。

如果不开控制台程序则不会，我最高开过20个并发去测试API，没有出现问题。

现在测试场景是都使用UnitOfWork+Repository,开控制台监听MQ队列并执行事务，API接受WebRequest, 写一个测试程序高频率的去调用它们，就会出现控制台程序在一直执行，API全部事务超时，

使用IFreeSql.Transaction没有上述问题，感觉是UnitOfWrok多次提交的时候把什么资源池占满了似的。

**Comment by luoyunchong** [comment]
数据库是本地的吗，是否存在网络环境

**Comment by silentdance** [comment]
是网络环境。

**Comment by silentdance** [comment]
我尝试再写一个复现场景的project出来，现在的都是公司代码，不太方便放出来。

**Comment by luoyunchong** [comment]
用本地的数据库测试下。或者 设置Command Timeout大一点，连接串：Command Timeout=100 或更大？。默认是30s,

如果不是内网，就设置 连接串 Min pool size=1。

**Comment by zhangkeyuan** [comment]
请问这个问题解决了吗？我现在也频繁遇到这个问题Connection must be valid and open to rollback transaction
![image](https://user-images.githubusercontent.com/24730412/162107075-1874b846-31e6-4848-8a99-24a29687ab99.png)
用的这个扩展方法

**Comment by 2881099** [comment]
@zhangkeyuan 你用的是哪种事务

**Comment by zhangkeyuan** [comment]
> @zhangkeyuan 你用的是哪种事务

https://github.com/dotnetcore/FreeSql/issues/932 用的这个另类事务

**Comment by zhangkeyuan** [comment]
> @zhangkeyuan 你用的是哪种事务

https://github.com/dotnetcore/FreeSql/issues/322 用的这个另类事务

**Comment by zhangkeyuan** [comment]
> > @zhangkeyuan 你用的是哪种事务
> 
> #322 用的这个另类事务

补充说明下：也是和楼主相似，有一个控制台程序后台任务，和API BackgroundService一直再跑
