### ISSUE TITLE
withsql 分组后分页问题

### ISSUE THREAD

**Issue by bing-byte-9527** [dotnetcore/FreeSql#933]
#### 数据库的具体版本
```
postgresql 
```

#### 安装的包
```

```

#### .net framework/. net core？ 及具体版本
```

```

**Comment by bing-byte-9527** [comment]
代码如下：
var query = _channelInfoRepository.Select.WithSql(@"select  channel_id,min(channel_name_en)channel_name_en, min(channel_name_local) channel_name_local,
min(channel_api_version) channel_api_version,
array_agg( DISTINCT  currency_types) currency_types,
array_agg( DISTINCT  platforms) platforms from channel_info GROUP BY channel_id
").Page(page, pageSize).Count(out var totalCount).ToList(c => new ChannelInfoPageListOutput
            {
                ChannelId = c.ChannelId,
                ChannelApiVersion = c.ChannelApiVersion,
                ChannelNameEn = c.ChannelNameEn,
                ChannelNameLocal = c.ChannelNameLocal
            });

**Comment by bing-byte-9527** [comment]
错误：
42P01: relation "channel_info" does not exist

**Comment by bing-byte-9527** [comment]
这是生成的sql，无法执行
SELECT a."channel_id" as1, a."channel_api_version" as2, a."channel_name_en" as3, a."channel_name_local" as4 
FROM ( select channel_id ChannelId,
min(channel_name_en)ChannelNameEn, min(channel_name_local) ChannelNameLocal,
min(channel_api_version) ChannelApiVersion

 from base.channel_info GROUP BY channel_id
 ) a

**Comment by bing-byte-9527** [comment]
这是生成的sql，无法执行
SELECT a."channel_id" as1, a."channel_api_version" as2, a."channel_name_en" as3, a."channel_name_local" as4 
FROM ( select channel_id ChannelId,
min(channel_name_en)ChannelNameEn, min(channel_name_local) ChannelNameLocal,
min(channel_api_version) ChannelApiVersion

 from base.channel_info GROUP BY channel_id
 ) a

**Comment by bing-byte-9527** [comment]
SELECT a.ChannelId as1, a.ChannelNameEn as2, a.ChannelNameEn as3, a.ChannelNameLocal as4 
FROM ( select channel_id ChannelId,
min(channel_name_en)ChannelNameEn, min(channel_name_local) ChannelNameLocal,
min(channel_api_version) ChannelApiVersion

 from base.channel_info GROUP BY channel_id
 ) a
这样才能正确执行

**Comment by luoyunchong** [comment]
https://github.com/dotnetcore/FreeSql/wiki/withsql

```csharp
      var query = _channelInfoRepository.Select.WithSql(@"select channel_id,min(channel_name_en)channel_name_en, min(channel_name_local) channel_name_local,
      min(channel_api_version) channel_api_version,
      array_agg( DISTINCT currency_types) currency_types,
      array_agg( DISTINCT platforms) platforms from channel_info GROUP BY channel_id
      ").Page(page, pageSize).Count(out var totalCount)
      .ToList<ChannelInfoPageListOutput>("*");
```
