### ISSUE TITLE
Unable connect to database via ODBC

### ISSUE THREAD

**Issue by viktoraskas** [dotnetcore/FreeSql#935]
Hi,

I am trying to connect to Sybase Adaptive Server Anywhere 9.0 database via ODBC drivers but not successfully.
I have tried various connection strings with no luck.
"Driver={Adaptive Server Anywhere 9.0};Data Source=192.168.88.44;Port=2638;UID=dba;PWD=sql;DATABASE=26e;"
"Driver={SQL Anywhere 17};Host=192.168.88.44;Port=2638;UID=dba;PWD=sql;DATABASE=26e;"
What could be correct connection string?

**Comment by 2881099** [comment]
You first use ODBC to connect directly to the database. Is the test successful?

```c#
using (var conn = new OdbcConnection(connectionString))
{
    conn.Open();
    conn.Close();
}
```

**Comment by viktoraskas** [comment]
It was wrong connection string. 
Must be @"Driver=Adaptive Server Anywhere 9.0;ENG=DEMO;UID=dba;PWD=sql;DBN=myDatabaseName;LINKS=TCPIP(HOST=HostNameOrIP);"
Thanks.
