### ISSUE TITLE
AsTreeCte 查询的能否增加子集的条件查询

### ISSUE THREAD

**Issue by wzohxia** [dotnetcore/FreeSql#936]
比如
var list = await _repository.Select
                        .Where(a => a.Code == "AppLibrary")
                        .AsTreeCte()
                        .Where(a => a.IsDel == false)
                        .ToListAsync();
现在只能在树查询出来之后再去判断是否软删除
能否再AsTreeCte中去增加条件是否软删除

**Comment by 2881099** [comment]
```c#
.Where(a => a.IsDel == false)
.AsTreeCte()
```
