### ISSUE TITLE
.NET6 linux x64 独立打包问题

### ISSUE THREAD

**Issue by yaobo-lab** [dotnetcore/FreeSql#942]
#### 问题描述及重现步骤：

代码如下： 
![image](https://user-images.githubusercontent.com/21329253/142123996-57af01ed-0930-44e2-9908-eef8f4c49266.png)
 

打包配置 
![1](https://user-images.githubusercontent.com/21329253/142122855-c13a3dd1-de20-4a07-8cdc-ee3f2e5e08b6.png)

编译二进制文件后放在linux上运行：
 ./WebApi

mysql 连接字符串：
server=127.0.0.1;database=demo;uid=root;pwd=123456;charset='utf8';SslMode=None;Convert Zero Datetime=True;Allow Zero Datetime=True;Allow User Variables=True

一直报主库不可用：但我本能调试用同样的MYSQL 连接字符串，是无问题的。

![image](https://user-images.githubusercontent.com/21329253/142125225-c86380d5-37f0-413b-9786-c872fcb07f2a.png)

#### 数据库的具体版本
```
mysql 8.0
```

#### 安装的包
```
   <PackageReference Include="FreeSql.Provider.MySql" Version="2.6.100" />
    <PackageReference Include="FreeSql.Repository" Version="2.6.100" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />

```

#### .net framework/. net core？ 及具体版本
```
.NET 6
```

**Comment by yaobo-lab** [comment]
测试了下。独立打包成windows 也存在同样的问题

**Comment by 2881099** [comment]
尝试一：单独引用 MySql.Data.dll

尝试二：移除 FreeSql.Provider.MySql，增加 FreeSql.Provider.MySqlConnector

**Comment by yaobo-lab** [comment]
> 尝试一：单独引用 MySql.Data.dll
> 
> 尝试二：移除 FreeSql.Provider.MySql，增加 FreeSql.Provider.MySqlConnector

移除 FreeSql.Provider.MySql，增加 FreeSql.Provider.MySqlConnector。这个方法可以。

是不是用了反射导致加到不了dll ？

**Comment by 2881099** [comment]
FreeSql.Provider.MySql.dll 也许不支持独立打包 @yaobo-lab
