### ISSUE TITLE
FreeSql.DatabaseModel.DbColumnInfo.Coment字段建议改名

### ISSUE THREAD

**Issue by cn-troy** [dotnetcore/FreeSql#958]
#### Feature 特性
建议修改FreeSql.DatabaseModel.DbColumnInfo字段Coment为 Comment

#### 简要描述原因
FreeSql.DatabaseModel.DbTableInfo中同样有字段Comment标识备注.
但是在FreeSql.DatabaseModel.DbColumnInfo中却变成了Coment, 估计是作者少按了一下.
建议在FreeSql.DatabaseModel.DbTableInfo中添加Comment字段或者修改Coment字段

**Comment by 2881099** [comment]
增加了 Comment 并且暂时保存 Coment，不会影响到现有的生态。
