### ISSUE TITLE
ExecuteSqlBulkCopy带上事务报错

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/FreeSql#962]
```
Fsql.Transaction(() =>
            {
                //全部清除
                Fsql.Delete<SysHrOrgnization>().Where("1=1").ExecuteAffrows();
                //创建
                Fsql.Insert(data).ExecuteSqlBulkCopy();
            });
```
提示报错如下:
Microsoft.Data.SqlClient.SqlException: 'Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
The statement has been terminated.'

**Comment by luoyunchong** [comment]
目前需要这样使用。
```
Fsql.Insert(data).WithTransaction(Fsql.Ado.TransactionCurrentThread).ExecuteSqlBulkCopy();
```

**Comment by bao2314483** [comment]
> 目前需要这样使用。
> 
> ```cs
> Fsql.Transaction(() =>
> {
>       //全部清除
>      Fsql.Delete<SysHrOrgnization>().Where("1=1").ExecuteAffrows();
>      //创建
>      Fsql.Insert(data).WithTransaction(Fsql.Ado.TransactionCurrentThread).ExecuteSqlBulkCopy();
> });
> ```

感谢大佬解答
