### ISSUE TITLE
Select<T>().WithSql(string sql)

### ISSUE THREAD

**Issue by 1344695152** [dotnetcore/FreeSql#963]
### 数据库
Ms Sql server

### 表结构：
A表：Id,Name
B表:Id,AId,IsBurn
### 按A统计B中，还有多少设备IsBurn=0
以下是我的SQL
`
SELECT
	a.Id ,a.Name,COUNT(1) as CountValue
FROM B b
FULL JOIN  A a on b.AId=a.Id
GROUP BY a.Id ,a.Name
ORDER BY a.Name
`
在数据库测试时,能跑通,复制到代码使用就失败
`
Select<T>().WithSql(string  sql)
`

#### 安装的包
```
FreeSql 2.6.100
FreeSql.Provider.SqlServer 2.6.100
```

#### .net framework/. net core？ 及具体版本
```
.net framework 4.6
```

#### 错误信息
`
System.Exception
  HResult=0x80131500
  Message=除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
  Source=FreeSql
  StackTrace:
   在 FreeSql.Internal.CommonProvider.AdoProvider.LoggerException(IObjectPool`1 pool, PrepareCommandResult pc, Exception ex, DateTime dt, StringBuilder logtxt, Boolean isThrowException) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\AdoProvider\AdoProvider.cs 中: 第 92 行
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(Int32 multipleResult, DbConnection connection, DbTransaction transaction, Action`2 fetchHandler, Action`2 schemaHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\AdoProvider\AdoProvider.cs 中: 第 688 行
   在 FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReader(DbConnection connection, DbTransaction transaction, Action`1 fetchHandler, CommandType cmdType, String cmdText, Int32 cmdTimeout, DbParameter[] cmdParms) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\AdoProvider\AdoProvider.cs 中: 第 559 行
   在 FreeSql.Internal.CommonProvider.Select0Provider`2.ToListAfPrivate(String sql, GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select0ProviderReader.cs 中: 第 110 行
   在 FreeSql.Internal.CommonProvider.Select0Provider`2.ToListPrivate(GetAllFieldExpressionTreeInfo af, ReadAnonymousTypeOtherInfo[] otherData) 在 C:\Users\28810\Desktop\github\FreeSql\FreeSql\Internal\CommonProvider\SelectProvider\Select0ProviderReader.cs 中: 第 134 行
   在 FreeSql.Internal.CommonProvider.Select0Provider`2.ToList(Boolean includeNestedMembers) 在 
  此异常最初是在此调用堆栈中引发的: 
    [外部代码]
    FreeSql.Internal.CommonProvider.AdoProvider.ExecuteReaderMultiple(int, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Action<FreeSql.Internal.Model.FetchCallbackArgs<System.Data.Common.DbDataReader>, int>, System.Action<System.Data.Common.DbDataReader, int>, System.Data.CommandType, string, int, System.Data.Common.DbParameter[]) (位于 AdoProvider.cs 中)

内部异常 1:
SqlException: 除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。

`

**Comment by densen2014** [comment]
语句没写全？orm跑不了提示什么错误？

**Comment by densen2014** [comment]
按提示修正sql语句即可，这个报错跟orm无关。

**Comment by 1344695152** [comment]
报错在issues中，简要信息:System.Exception HResult=0x80131500 Message=除非另外还指定了 TOP、OFFSET 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。我后续去掉Order by 使用ORm中Orm中的OrderBys实现






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年12月15日(星期三) 下午4:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotnetcore/FreeSql] Select<T&gt;().WithSql(string sql) (Issue #963)





 
语句没写全？orm跑不了提示什么错误？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luoyunchong** [comment]
使用withsql 会在外面生成一层 select * from (xxx)  a 

在sql server下子查询，不像mysql。有order by 就必须 要有分页过滤。上面sql server已经告诉 你了。

sql改成这样
```sql
SELECT a.Id ,a.Name,COUNT(1) as CountValue FROM B b FULL JOIN A a on b.AId=a.Id GROUP BY a.Id ,a.Name ORDER BY a.Name   offset 0 rows
```
```csharp
Select<T>().WithSql(string sql)
```
或使用如下方式

```csharp
Select<T>().WithSql("SELECT a.Id ,a.Name,COUNT(1) as CountValue FROM B b FULL JOIN A a on b.AId=a.Id GROUP BY a.Id ,a.Name").OrderBy("a.Name")
```

**Comment by 1344695152** [comment]
> 使用withsql 会在外面生成一层`select * from (xxx) a `
> 
> 在下子查询，不像。有就必须 要有分页过滤。上面sql server已经告诉 你了。在后加订购`sql server``mysql``order by ``offset 0 rows`
> 
> sql改成这样
> 
> ```sql
> SELECT a.Id ,a.Name,COUNT(1) as CountValue 
> FROM B b
> FULL JOIN A a on b.AId=a.Id 
> GROUP BY a.Id ,a.Name 
> ORDER BY a.Name   offset 0 rows
> ```
> 
> ```cs
> Select<T>().WithSql(string sql)
> ```
> 
> 或使用如下方式
> 
> ```cs
> Select<T>().WithSql(@"SELECT a.Id ,a.Name,COUNT(1) as CountValue
> FROM B b 
> FULL JOIN A a 
> on b.AId=a.Id 
> GROUP BY a.Id ,a.Name").OrderBy("a.Name")
> ```

谢谢你的解答
