### ISSUE TITLE
ClickHouse数据库插入时如果有字段为Json序列化后字符串并且设置NoneParameter会报错

### ISSUE THREAD

**Issue by skyland-zero** [dotnetcore/FreeSql#968]
ClickHouse数据库插入时如果有字段为Json序列化后字符串并且设置NoneParameter会报错

#### 问题描述及重现步骤：
具体请查看：
https://github.com/skyland-zero/ClickHouseJsonTextIssue

#### 数据库的具体版本
```
ClickHouse v21.12  
安装系统： Ubuntu 20.04 lts
```

#### 安装的包
```
FreeSql.Provider.ClickHouse 3.0.100
```

#### .net framework/. net core？ 及具体版本
```
dotnet  6.0.101
```

**Comment by ANCB520** [comment]
#973 已修改

**Comment by skyland-zero** [comment]
> #973 已修改

谢谢，大佬牛逼
