### ISSUE TITLE
ClickHouse异步插入带多个长字段实体表数据时出现Invalid URI: The Uri string is too long异常

### ISSUE THREAD

**Issue by skyland-zero** [dotnetcore/FreeSql#969]
ClickHouse异步插入带多个长字段实体表数据时出现Invalid URI: The Uri string is too long异常

#### 问题描述及重现步骤：
具体请查看：
https://github.com/skyland-zero/FreeSqlClickHouseUriToLongIssue

#### 数据库的具体版本
```
ClickHouse v21.12  
安装系统： Ubuntu 20.04 lts
```

#### 安装的包
```
FreeSql.Provider.ClickHouse 3.0.100
```

#### .net framework/. net core？ 及具体版本
```
dotnet  6.0.101
```

**Comment by ANCB520** [comment]
单条数据插入，字符串值过长时会有这个问题，可以暂时使用List插入的方式来解决这个问题

**Comment by skyland-zero** [comment]
> 单条数据插入，字符串值过长时会有这个问题，可以暂时使用List插入的方式来解决这个问题

好的

**Comment by ZUOXIANGE** [comment]
@2881099  我在最新版本也遇到了这个问题,和上边的代码不同的地方是我插入的字符串更长

**Comment by d4ilys** [comment]
@ZUOXIANGE 可以先开启参数化 new FreeSqlBuilder().UseNoneCommandParameter(true) 解决，关闭参数化参数过长会出现这个问题，原因是Clickhouse.client这个Ado驱动底层原因。
如果有特殊处理 后续版本会加入ExecuteBulkCopy
