### ISSUE TITLE
连接远程数据库时，注意事项

### ISSUE THREAD

**Issue by 2881099** [dotnetcore/FreeSql#97]
## 如果在本地开发环境，设置 min pool size = 1 可减少启动时间

由于内部实现默认做了预热效果(默认预热 5)，设置 min pool size 可减少启动时间

## 如果连接远程服务器，特别是云数据库，设置 Connection LifeTime=20 可防止服务器主动断开连接，导致程序报错

云服务器，远程服务器大多有主动关闭一段时间不活跃的连接，所以需要设置 Connection LifeTime=20 防止连接断开后执行出错。单位为秒。

**Comment by asdcxzsx** [comment]
自动创建数据库好像没有么，这个很简单的功能别忘了，ctx.Database.EnsureCreated()~

**Comment by 2881099** [comment]
> 自动创建数据库好像没有么，这个很简单的功能别忘了，ctx.Database.EnsureCreated()~

对，正是因为简单所以没做
