### ISSUE TITLE
期望在Aop_CurdBefore 时，可以直接设置值返回，不再继续执行

### ISSUE THREAD

**Issue by xiaochen20034** [dotnetcore/FreeSql#972]
#### Feature 特性
期望在Aop_CurdBefore 时，可以有个属性，直接设置值返回，不再继续执行。
类似于执行SQL的一个拦截器，满足某些条件时，程序处理，而不会继续执行。

#### 简要描述原因
我想根据用户查询的表，直接从缓存获取数据，然后返回给Service，而不去执行数据库查询
在更新时，我想根据表清除缓存
#### 使用场景
读取数据时，可以直接从缓存读取返回数据，而这个功能又不想编写在业务层面。

**Comment by 2881099** [comment]
其实缓存没必要在 orm 上做，市面上任何一个动态代理，都可以轻松在 IService 实现层进行拦截

**Comment by EternityTeam** [comment]
可以包装一层服务做这个，你这个方案思路不是很合理。
