### ISSUE TITLE
自增属性，Insert频繁会异常

### ISSUE THREAD

**Issue by 773596523** [dotnetcore/FreeSql#986]
#### 问题描述及重现步骤：
在日志分表中，实现如下
![image](https://user-images.githubusercontent.com/33311705/147537103-2b33d7f9-fc70-4fb5-9217-fd183b79a637.png)
![image](https://user-images.githubusercontent.com/33311705/147537124-171ad653-1a3a-4ecc-b32f-36aee17797e4.png)
![image](https://user-images.githubusercontent.com/33311705/147537141-50f5cec0-41cc-41d5-92da-ff097cc17c9a.png)
经常会报出
System.Exception: 不可添加，自增属性有值：(29,url, Basic, PullStoreHouse, 123.57.33.28, 2021/12/11 2:21:09, 200, {"orgId":""}, {"pullNum":0,"pushNum":0,"errId":0,"errMsg":"仓库共拉取0行，推送0行"}, 99)
   在 FreeSql.DbSet`1.CanAdd(TEntity data, Boolean isThrow) 位置 C:\Users\28810\Desktop\github\FreeSql\FreeSql.DbContext\DbSet\DbSet.cs:行号 301
   在 FreeSql.DbSet`1.AddPriv(TEntity data, Boolean isCheck) 位置 C:\Users\28810\Desktop\github\FreeSql\FreeSql.DbContext\DbSet\DbSetSync.cs:行号 34
   在 FreeSql.DbSet`1.Add(TEntity data) 位置 C:\Users\28810\Desktop\github\FreeSql\FreeSql.DbContext\DbSet\DbSetSync.cs:行号 95
   在 FreeSql.BaseRepository`1.Insert(TEntity entity) 位置 C:\Users\28810\Desktop\github\FreeSql\FreeSql.DbContext\Repository\Repository\BaseRepository.cs:行号 100

#### 数据库的具体版本
```
Sqlserver 2008
```

#### 安装的包
```
2.6.100
```

#### .net framework/. net core？ 及具体版本
```
.net framework 4.8
```

**Comment by 773596523** [comment]
有时候正常，有时候就报错

**Comment by 2881099** [comment]
你用的是仓储对象插入是会这样。

重现你的操作是：

```c#
var item = new Entity { ... };
var repo = fsql.GetRepository<Entity>();

repo.Insert(item); //正常
Console.WriteLine(item.Id); //此时已经得到自增的新值

repo.Insert(item); //再次插入时，报错，不可添加，自增属性有值
```

是正常现象。

如果你想继续插入，可以考虑直接用 fsql.Insert(item).ExecuteAffrows();

**Comment by 773596523** [comment]
1.这里用途是记录了api运行的日志，log只会insert一次，并没有insert多次，跑过一段时间发现大多数都正常，但还是有不少的异常提示：自增属性有值
2.model上也定义CanInsert=false，是否优先级太低没有使用？
3.及时model的自增属性Id有值，是否考虑Insert时忽略？

目前解决方案是把Insert改成InsertOrUpdate

**Comment by luoyunchong** [comment]
CanInsert 没有用的。本来就是主键，自增。 使用**仓储**同一个对象只能插入一次。检查代码哪里有重复调用此方法。

**Comment by 773596523** [comment]
我理解 字段已经是自增了 为何Insert的时候不忽略？

**Comment by luoyunchong** [comment]
已经多次说明，仓储 新增对象，会把id回传。对于同 一对象来说，状态跟踪不能多次insert。。还没到数据库层面。
