### ISSUE TITLE
2.5.2版本  ROW_NUMBER() 分页时自动加排序，造成分页混乱，同时skip方法也有此问题

### ISSUE THREAD

**Issue by jinghuian** [dotnetcore/FreeSql#988]
#### 问题描述及重现步骤：
2.5.2版本 分页时自动加排序，造成分页混乱，ROW_NUMBER() 必须排序 判断自动加了排序。
SqlServer 2012+ 版本，使用最新的 fetch next rows 分页；但并没有使用该语法
分页第一页 使用 
select top 10 from XXX

分页第二页 使用
SELECT count(1) as1 
FROM  表名 a 
WHERE (1=1);
WITH t AS ( SELECT 列名, ROW_NUMBER() OVER( 
ORDER BY 列名 ) AS __rownum__ 
FROM 表名 a 
WHERE (1=1) ) SELECT t.* FROM t where __rownum__ between 11 and 20

#### 数据库的具体版本
```
sql server 2008
```

#### 安装的包
```
freesql.sqlserver
```

#### .net framework/. net core？ 及具体版本
```
.net 4.7.2
```

**Comment by luoyunchong** [comment]
分页取第二页，必须加order by ，否则无法正常执行。你用的sql server2008.当然不会用2012的语法。

**Comment by jinghuian** [comment]
@luoyunchong 分页的问题 第二次分页必须加 排序的话，第一次直接使用 top 也应该加排序，否则 第一次分页和第二次分页 一个不排序 一个排序 显示会异常的

**Comment by 2881099** [comment]
建议分页时，自己增加一个order by
