### ISSUE TITLE
.net6 的新日期  时间 类型   dateolny  timeolny  不支持

### ISSUE THREAD

**Issue by lhtuling** [dotnetcore/FreeSql#991]
#### 问题描述及重现步骤：
![image](https://user-images.githubusercontent.com/44140500/147724299-629469d4-34b0-4a12-918e-2f69e823dd3a.png)
``````
public class Clock : EntyBase
{
      public int UserId { get; set; }
      public User User { get; set; }
      public DateOnly ClockDate { get; set; }
      public TimeOnly? ClockInTime { get; set; }
      public TimeOnly? ClockOutTime { get; set; }
}
``````
DateOnly 
TimeOnly
3个字段不会处理 并且会报错
#### 数据库的具体版本
```
sqlite 3
```

#### 安装的包
```
3.0.100
```

#### .net framework/. net core？ 及具体版本
```
.net 6
```

**Comment by 2881099** [comment]
sqlserver  新版本已支持，怕官方变化，等.net80在考虑全部支持
